HPCC-17317 DOCS: ECLWatch Add Delete Part
hpcc-systems/HPCC-Platform pull request #10030
Opened 2017-05-23 22:09 UTC by g-pan

Fix HPCC-17317 DOCS:ECLWatch Add Delete Part
Add documentation to the ECL Watch doc on 
using the Roxie Package Maps, Add, Delete, Activate Part.

Initial Pull Request, Expecting comments and feedback. 

@JamesDeFabia please review
@miguelvazq please review
@afishbeck please review 

Build results and PDF can be reviewed at 
http://10.240.32.243/job/DocDev0IV/3/CE=ubuntu-14.04-amd64-1/artifact/build-docs/Release/docs/The_ECL_Watch_Manual-6.3.0-trunk0.pdf
(Chrome users may need to download the file to review)

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-05-23 22:23 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 70274155df89527463a970e06eda91db587aaef3
Build: failed
Number of Error(s): 511
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3100: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3100: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3100: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3100: parser error : StartTag: invalid
 ... ( comment is too long, 518 lines, 87751 bytes, truncated) ... 
 Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/CoreErrors.cpp.o
[100%] Building CXX object aws-cpp-sdk-sqs/CMakeFiles/aws-cpp-sdk-sqs.dir/source/SQSErrors.cpp.o
make: *** [all] Error 2
Get ECLWatch build result


```

2017-05-24 12:55 UTC, JamesDeFabia requested changes
Comments inline

2017-05-24 12:55 UTC, JamesDeFabia commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +          <title id="Packagemap_Actions">Packagemap Actions</title>
s/b two words: Package Map Actions

2017-05-24 12:55 UTC, JamesDeFabia commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +            </figure>To Add a packagemap to the target cluster:</para>
package map (two words)

2017-05-24 12:55 UTC, JamesDeFabia commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +              equiv?*/</para>
You left a comment. Replace with the description

2017-05-24 12:55 UTC, JamesDeFabia commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +              desired.</para>
Check the boxes to Activate or Overwrite, as desired

2017-05-24 12:55 UTC, JamesDeFabia commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +          package map.</para>
`<emphasis role="bold">Deactivate</emphasis>  button`

2017-05-24 12:55 UTC, JamesDeFabia commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +          package map and make the selected package map active.</para>
`<emphasis role="bold">Activate</emphasis>  button`

2017-05-24 13:36 UTC, g-pan commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +          <title id="Packagemap_Actions">Packagemap Actions</title>
Don't think you are looking at the latest commit. This was fixed in a later commit.

2017-05-24 14:14 UTC, miguelvazq commented
@g-pan Additional functionality for parts is located in the details as we discussed offline.

2017-05-24 14:15 UTC, richardkchapman commented
Needs rebasing foe a clean merge

2017-05-24 17:08 UTC, afishbeck reviewed
@g-pan a few comments and general bits of knowledge.

2017-05-24 17:08 UTC, afishbeck commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +          one. You can do this through the interface in ECLWatch.</para>
ECLWatch or command line?

2017-05-24 17:08 UTC, afishbeck commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +              equiv?*/</para>
btw, I don't think I support process filter on command line.  It's one of those complex things that if I start to think people really want or need it I will add but over the last 5 years or so no one seems to be needing it.

2017-05-25 06:02 UTC, richardkchapman commented
Needs rebasing for a clean merge

2017-05-26 14:20 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 60e5d9917a737a8a37e679dbf0d62815b088e67e
Build: failed
Number of Error(s): 85
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3100: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3100: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3100: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3100: parser error : StartTag: invalid 
 ... ( comment is too long, 92 lines, 13512 bytes, truncated) ... 
 Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/CoreErrors.cpp.o
[100%] Building CXX object aws-cpp-sdk-sqs/CMakeFiles/aws-cpp-sdk-sqs.dir/source/SQSErrors.cpp.o
make: *** [all] Error 2
Get ECLWatch build result


```

2017-05-26 15:25 UTC, g-pan commented
Keeping pull request open, while work in progress - preserving comments.  Will rebase when ready. Please hold off merging until rebased.

2017-05-30 15:16 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 15efcfe260b67ba913d3b95825d1484569251077
Build: failed
Number of Error(s): 85
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3068: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3100: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3100: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3100: parser error : StartTag: invalid element name
/mnt/disk1/home/vamosax/smoketest/PR-10030/HPCC-Platform/docs/HPCCClientTools/CT_Mods/CT_ECL_CLI.xml:3100: parser error : StartTag: invalid 
 ... ( comment is too long, 92 lines, 13512 bytes, truncated) ... 
 Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/CoreErrors.cpp.o
[100%] Building CXX object aws-cpp-sdk-sqs/CMakeFiles/aws-cpp-sdk-sqs.dir/source/SQSErrors.cpp.o
make: *** [all] Error 2
Get ECLWatch build result


```

2017-05-30 18:51 UTC, g-pan commented
Due in part to a hardware outage, and in part to some of the commit conflicts and comments here, I am closing this pull request, only to replace it with a single commit pull request.

2017-05-30 18:51 UTC, closed without merging