HPCC-17711 Roxie ssl listener passphrase decrypt
hpcc-systems/HPCC-Platform pull request #10054
Opened 2017-05-31 19:52 UTC by mckellyln

Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [x] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [x] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [ ] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

testsocket and soapplus tests were run successfully

2017-05-31 19:53 UTC, mckellyln commented
@afishbeck please review.

2017-05-31 20:27 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: ef39eae426a5a023fcbe1167b09da37199bbdadb
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 95.855 seconds |


Install hpccsystems-platform-community_6.4.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |730 |730 |0 |
|test (thor) |624 |624 |0 |
|test (roxie) |758 |758 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-01 15:29 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 062d1773317977cce617d880d1a55505f77cfb88
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.054 seconds |


Install hpccsystems-platform-community_6.4.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |730 |730 |0 |
|test (thor) |624 |624 |0 |
|test (roxie) |758 |758 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-01 15:45 UTC, mckellyln commented
@afishbeck I had to change it so certfile, keyfile and passphrase are independent and persistent in case there were > 1 ssl listeners.
If you don't like the cast in free in dtor I can change these 3 to be not const.

2017-06-01 16:06 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: ef01bdff9822404bd440e7ff194a333e136b4e25
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.612 seconds |


Install hpccsystems-platform-community_6.4.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |730 |730 |0 |
|test (thor) |624 |624 |0 |
|test (roxie) |758 |758 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-01 16:09 UTC, mckellyln commented
@afishbeck updated again, removed cast and changed certfile, keyfile, passphrase to be not const.

2017-06-01 16:43 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 55948a59bc3614a1037c6270ce1cfc5e65c5553b
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.943 seconds |


Install hpccsystems-platform-community_6.4.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |730 |730 |0 |
|test (thor) |624 |624 |0 |
|test (roxie) |758 |758 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-01 18:05 UTC, mckellyln commented
@afishbeck updated again to use StringAttr.  Please review.

2017-06-01 18:07 UTC, mckellyln commented on roxie/ccd/ccdprotocol.cpp
>                  {
Should I use .str() in the streq() ?

2017-06-01 18:07 UTC, mckellyln commented on roxie/ccd/ccdprotocol.cpp
> +                            secureContext.setown(createSecureSocketContextEx(certFile.get(), keyFile.get(), passPhrase.get(), ServerSocket));
Should I use .str() here ?

2017-06-01 18:21 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: c29ada1e5f865ee4b82f15646bccccc53738536d
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 90.767 seconds |


Install hpccsystems-platform-community_6.4.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |730 |730 |0 |
|test (thor) |624 |624 |0 |
|test (roxie) |758 |758 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-01 18:47 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: ca0efd624ebed2b0208f445d2fdc20acb9af890f
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.28 seconds |


Install hpccsystems-platform-community_6.4.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |730 |730 |0 |
|test (thor) |624 |624 |0 |
|test (roxie) |758 |758 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-01 19:20 UTC, afishbeck requested changes
@mckellyln some comments.

2017-06-01 19:20 UTC, afishbeck commented on roxie/ccd/ccdmain.cpp
> +                    const char *certFilePtr = nullptr;
You don't need all of these xPtr variables.  Just use certFileName.str() when you pass it as a parameter to the createListener factory,

2017-06-01 19:20 UTC, afishbeck commented on roxie/ccd/ccdmain.cpp
> +                    const char *keyFilePtr = nullptr;
Same here.

2017-06-01 19:20 UTC, afishbeck commented on roxie/ccd/ccdmain.cpp
> +                    const char *passPhrasePtr = nullptr;
same.

2017-06-01 19:20 UTC, afishbeck commented on roxie/ccd/ccdprotocol.cpp
>                  {
yes, and if you do you don't need to first check protocol.get().
`if (streq(protocol.str(), "ssl"))`
is all you need.

2017-06-01 19:20 UTC, afishbeck commented on roxie/ccd/ccdprotocol.cpp
> +                            secureContext.setown(createSecureSocketContextEx(certFile.get(), keyFile.get(), passPhrase.get(), ServerSocket));
if createSecureSocketContextEx can handle nullptrs then this is fine.  If createSecureSocketContextEx can only handle "" then use .str()

2017-06-01 19:20 UTC, afishbeck commented on roxie/ccd/ccdmain.cpp
> +                    roxieServer.setown(protocolPlugin->createListener(protocol ? protocol : "native", createRoxieProtocolMsgSink(ip, port, numThreads, suspended), port, listenQueue, config, certFileP
Again, If you just do:
`createListener(protocol ? protocol : "native", createRoxieProtocolMsgSink(ip, port, numThreads, suspended), port, listenQueue, config, certFileName.str(), keyFileName.str(), passPhrase.str())`

Then you don't need all of those extra variables.

2017-06-01 19:58 UTC, mckellyln commented
@afishbeck updated.  Thanks for your comments.

2017-06-01 19:59 UTC, mckellyln commented
Yes, createSecureSocketContextEx() is ok with nullptr args.

2017-06-01 20:24 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: c5cb8627496964d567c4c4479e50917bd725c579
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 94.87 seconds |


Install hpccsystems-platform-community_6.4.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |730 |730 |0 |
|test (thor) |624 |624 |0 |
|test (roxie) |758 |758 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-01 20:28 UTC, afishbeck approved these changes
@mckellyln looks good

2017-06-02 07:15 UTC, merged