HPCC-17410 Add roxie cluster into WsDFUXRef.DFUXRefList
hpcc-systems/HPCC-Platform pull request #10103
Opened 2017-06-09 19:05 UTC by wangkx

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-06-09 19:38 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: ee5ceb6031640c0976952dd79cd7c659ec5733ec
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 41.245 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |736 |736 |0 |
|test (thor) |630 |630 |0 |
|test (roxie) |765 |764 |1 |


Errors:
- test
  - roxie
    - schedule2, 

HPCC Stop: OK
HPCC Uninstall: OK

2017-06-09 20:55 UTC, wangkx commented
@afishbeck please review.

2017-06-23 01:16 UTC, afishbeck requested changes

2017-06-23 01:16 UTC, afishbeck commented on esp/services/ws_dfu/ws_dfuXRefService.cpp
> +                    isThorCluster = true;
I find setting this flag and checking it a little less clear than just wrapping this section in:

`switch (cluster.getPlatform())`
`{`
`case ThorLCRCluster:`
`case RoxieCluster:`
`}`

2017-06-23 01:16 UTC, afishbeck commented
@wangkx back to you

2017-06-23 19:33 UTC, wangkx commented
@afishbeck I made the changes. Please review.

2017-06-23 20:04 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 60374e6983cc475ab20e8f02350640c3bd0e5bb3
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 42.323 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |741 |741 |0 |
|test (thor) |636 |636 |0 |
|test (roxie) |768 |768 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-23 22:13 UTC, afishbeck commented on esp/services/ws_dfu/ws_dfuXRefService.cpp
> +                SCMStringBuffer roxieProcess;
Trivial, but I usually put braces {} around any "case" with local variables.. even though in some cases like this one it's probably not necessary.

2017-06-23 22:14 UTC, afishbeck approved these changes
Trivial comment, but looks fine.

2017-06-26 10:16 UTC, merged