Neo h17317 parts
hpcc-systems/HPCC-Platform pull request #10118
Opened 2017-06-13 19:55 UTC by g-pan

Fix HPCC-17317 DOCS:ECLWatch Add Delete Part
Add documentation to the ECL Watch doc on
using the Roxie Package Maps, Add, Delete, Activate Part
New Pull request, Replacing Pull Request # 10030, 10050 & 10056 - due to
substantial changes and some technical difficulties

@JamesDeFabia  please review
@miguelvazq please review
@afishbeck please review

For convenience PDF can be reviewed at: 
http://10.240.32.243/view/Docs/job/DocDev05/CE=ubuntu-14.04-amd64-1/lastSuccessfulBuild/artifact/build-docs/Release/docs/The_ECL_Watch_Manual-6.4.0-rc1.pdf
 resulting from successful test build.

Signed-off-by: g-pan <greg.panagiotatos@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [x] I have added tests to cover my changes.
http://10.240.32.243/view/Docs/job/DocDev05/CE=ubuntu-14.04-amd64-1/
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-06-13 20:29 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 7ad918bccaed293166a4ca73f0c1aa0bb0618865
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.893 seconds |


Install hpccsystems-platform-community_6.4.0-rc3.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-13 21:58 UTC, afishbeck commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +          <para>To validate any package map:</para>
Not sure on exact wording, but the key is these are packagemaps that aren't yet on the system.

Something like "To validate an external packagemap"
and/or "a packagemap not yet uploaded onto the environment."

2017-06-13 21:58 UTC, afishbeck commented
@g-pan just one minor comment.

2017-06-14 13:24 UTC, JamesDeFabia commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +          <para>To validate any package map:</para>
I like: "To validate a package map not yet uploaded to the environment:"

2017-06-14 13:37 UTC, g-pan commented
@afishbeck please let me know if this change is better.

2017-06-14 13:50 UTC, JamesDeFabia requested changes
Only one minor change

2017-06-14 13:50 UTC, JamesDeFabia commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +                packagemap.</para>
package map

2017-06-14 14:05 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: d9d7ff8fc7a6b14c60c74cbf894d9b633f51449b
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 95.578 seconds |


Install hpccsystems-platform-community_6.4.0-rc3.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-14 15:16 UTC, afishbeck approved these changes
@g-pan looks good.

2017-06-14 18:39 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 2d60b463112468b5cf97987be154a0a0c9d037fa
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.462 seconds |


Install hpccsystems-platform-community_6.4.0-rc3.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-15 18:15 UTC, g-pan commented
Rebased for a nice clean merge

2017-06-15 18:47 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 3ced03394b243cfda92562200c79e384e338a648
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.667 seconds |


Install hpccsystems-platform-community_6.4.0-rc3.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-15 19:12 UTC, miguelvazq commented
FYI ECLWAPkgParts01.jpg will not have some of the fields in them after https://github.com/hpcc-systems/HPCC-Platform/pull/10094 is merged.

2017-06-15 19:12 UTC, miguelvazq commented on docs/ECLWatch/ECLWa_mods/ECLWatchQueries.xml
> +                <para>The Filter also also supports wild cards.</para>
You have an extra "also" in here

2017-06-15 20:07 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 033ad88caa080c17da718b7e63982eebefb5d1a9
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 96.159 seconds |


Install hpccsystems-platform-community_6.4.0-rc3.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-15 20:13 UTC, miguelvazq commented
Looks fine other than my image comment.

2017-06-16 12:19 UTC, g-pan commented
Added https://track.hpccsystems.com/browse/HPCC-17827 for image update.

2017-06-16 14:45 UTC, merged