HPCC-17751 Definition Explorer/Details Widget
hpcc-systems/HPCC-Platform pull request #10128
Opened 2017-06-16 17:24 UTC by miguelvazq

We can now show the XML tied to each definition in this interface. This interface is better suited for embedding into the IDE for DESDL. The bookmark should follow the following syntax.

<protocol://host:port>/?Widget=DynamicESDLDefinitionQueryWidget

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-06-16 18:42 UTC, miguelvazq commented
@GordonSmith Please review. 
@rpastrana Please review translations
@g-pan Will need documentation

2017-06-19 13:14 UTC, rpastrana commented
@miguelvazq ES translations look fine.

2017-06-20 13:45 UTC, miguelvazq commented
@GordonSmith bump.

2017-06-20 14:44 UTC, GordonSmith requested changes

2017-06-20 14:44 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDefinitionQueryWidget.js
> +#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
Date wrong and I don't think we need to copyright header once the licence file is present in the repo.

2017-06-20 14:44 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDefinitionQueryWidget.js
> +                var selection = context.grid.getSelected();
Should really test if there was a selection (it might have been a de-selection)

2017-06-20 16:37 UTC, miguelvazq commented
@GordonSmith Modified.

2017-06-26 14:37 UTC, GordonSmith commented
Looks fine.

2017-06-26 14:37 UTC, GordonSmith approved these changes

2017-06-26 14:43 UTC, rpastrana commented
@richardkchapman just as a follow up since this is late in the RC time-frame, this change is isolated, doesn't cause any work-flow interruptions, provides a significant usability improvement, and supports recent ECLIDE 6.4 changes

2017-06-27 10:51 UTC, richardkchapman commented on esp/src/eclwatch/nls/es/hpcc.js
> +    title_Definitions: "Definiciónes",
We will need to cycle around the other translations again...

2017-06-27 11:38 UTC, GordonSmith commented on esp/src/eclwatch/nls/es/hpcc.js
> +    title_Definitions: "Definiciónes",
@miguelvazq FYI the translations.

2017-06-27 11:41 UTC, merged