HPCC-17866 Document upper size limit for DATA/STRING types
hpcc-systems/HPCC-Platform pull request #10156
Opened 2017-06-26 19:15 UTC by JamesDeFabia

Signed-off-by: Jim DeFabia <jamesdefabia@lexisnexis.com>

@ghalliday Please review 

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-06-26 20:52 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 3f567ec3aa4d4aa62fb69f4958f1ec914d107503
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.836 seconds |


Install hpccsystems-platform-community_6.4.0-rc3.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-06-27 08:45 UTC, ghalliday requested changes

2017-06-27 08:45 UTC, ghalliday commented on docs/ECLLanguageReference/ECLR_mods/Basics-Constants.xml
> +    <para>The upper size limit for any string constant is 4GB (2^32), although
I don't think the extra comment about running out of memory adds anything.  I'm not sure it is worth documenting the maximum length of a string constant at all, no one is going to have a string constant that long.

2017-06-27 08:45 UTC, ghalliday commented on docs/ECLLanguageReference/ECLR_mods/Value-Data.xml
> +  <para>The upper size limit for any DATA value is 4GB (2^32), although you
I would remove the comment about running out of memory.  Same goes for all the other items.

2017-06-27 08:45 UTC, ghalliday commented on docs/ECLLanguageReference/ECLR_mods/Value-QString.xml
> +  <para>The upper size limit for any QSTRING value is 4GB (2^32), although you
Limit is probably 2^32 characters (which is smaller).

2017-06-27 08:45 UTC, ghalliday commented on docs/ECLLanguageReference/ECLR_mods/Value-Data.xml
> +  <para>The upper size limit for any DATA value is 4GB (2^32), although you
Actually the limits are probably 2^32-17!
I wouldn't document that, but it also may not be worth saying 2^32.

2017-06-27 08:46 UTC, ghalliday commented
@JamesDeFabia see comments

2017-06-27 16:29 UTC, JamesDeFabia commented
@ghalliday Edits made, back to you

2017-06-28 11:45 UTC, ghalliday commented on docs/ECLLanguageReference/ECLR_mods/Value-QString.xml
> +  <para>The upper size limit for any QSTRING value is 4GB.</para>
Technically the maximum length if 4G (=> maximum size is 3Gb), but I will merge anyway

2017-06-28 11:46 UTC, ghalliday approved these changes

2017-06-28 11:46 UTC, merged