HPCC-17923 DOCS:ECLWatch Common Elements
hpcc-systems/HPCC-Platform pull request #10267
Opened 2017-07-19 16:55 UTC by g-pan

Fix HPCC-17923 DOCS:ECLWatch Common Elements
Add chapter (or section(s)) to ECL Watch to
detail common elements in ECL Watch which work
universally throughout the interface.
Also addresses HPCC-14064

@JamesDeFabia please review
@miguelvazq please review

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [x] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [X] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2017-07-19 17:26 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 73a86e8a299cdc56f36d14392903d85df7df5ee5
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.522 seconds |


Install hpccsystems-platform-community_6.4.0-rc6.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-07-19 17:41 UTC, JamesDeFabia requested changes
Comments inline

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +      within ECL Watch.</para>
Replace 3 sentences with this one:
There are common elements that are useful anywhere within ECL Watch.

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +
Opening a new page of the current view is useful in several ways:

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +            <para>Open in new page is a shareable link. You can right-click on
Open in New Page

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +            from the drop list. You can now share or send that link and the
from the drop list
s/b
from the context menu

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +            a filter for jobs from a specific user, then shared that new page
New pages maintain filter states. If you have set a filter and share a link, the new page has the same filter set.

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +              files)</para>
, and Roxie queries

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +          then copy an <emphasis>Open new Page</emphasis> link with the filter
s/b role="bold" and say: Open in New Page

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +          refine the results displayed until you clear the filter.</para>
Filter conditions limit the results displayed until you clear the filter.

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +
This paragraph needs to be worded better

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +          light will display a color based on the the overall (configurable)
HPCC Monitoring and Reporting s/b italics

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +          it as a CSV formatted file. You can then open the CSV file in any
...ability to download selected rows as a ...

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +        </sect3>
which supports CSV format.

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +        supports wild cards. To limit or filter your search results you can
wildcard

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +          <para>The <emphasis role="bold">Open Legacy ECL Watch</emphasis>
Open Legacy ECL Watch has been removed.

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +          opens a tab to the HPCC Systems<superscript>®</superscript> download
This has changed. It now has a submenu ...

2017-07-19 17:41 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +            change your password, right from the User Details window. <!--***? is this still valid : don't see where this is in new ECLWatch ***--><orderedlist>
This is still valid, you can remove comment

2017-07-20 12:58 UTC, g-pan commented
Updates made. @JamesDeFabia please review.

2017-07-20 13:29 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 91a2b29a7d4840ea8e5a8a9be57cdda175f7ac05
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.637 seconds |


Install hpccsystems-platform-community_6.4.0-rc6.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-07-20 14:30 UTC, miguelvazq commented on docs/ECLWatch/TheECLWatchMan.xml
> +            the page or refresh to see current state.</para>
It's live **if** there is an auto-refresh mechanism in place.

2017-07-20 14:43 UTC, JamesDeFabia requested changes
comments inline

2017-07-20 14:43 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +        <para>The banner area of ECL Watch appears at the top of all pages.
The banner area of ECL Watch appears at the top of all pages. The Banner Items are a constant in the interface. The top banner remains a fixture at the top of your window as you navigate through the pages.

3 sentences when one will do. Keep "The banner area of ECL Watch appears at the top of all pages."

2017-07-20 16:52 UTC, JamesDeFabia approved these changes
Looks good now

2017-07-20 17:00 UTC, g-pan commented
Revised, updated, and squashed for a clean merge.

2017-07-20 17:25 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 252700cab9af2ccb092500494055354f4b97113a
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.805 seconds |


Install hpccsystems-platform-community_6.4.0-rc6.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-07-20 18:22 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 94893601a233a2895c49be049b7b76811eda0259
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.387 seconds |


Install hpccsystems-platform-community_6.4.0-rc6.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-07-21 06:24 UTC, merged