HPCC-18041 Unicode Implementation of ExcludeLastWord
hpcc-systems/HPCC-Platform pull request #10321
Opened 2017-08-09 15:23 UTC by dskaff

- Adds testcases to ecllibarry/teststd/uni/TestExcludeLastWord.ecl
- Adds documentation to ecllibrary/std/Uni.ecl
- Adds code to plugins/unicodelib.cpp

Signed-off-by: David Skaff <david.skaff@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2017-08-09 15:35 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 5bb8673846c237f1147c85194ff800a9a2cfc02f
Build: failed
Number of Error(s): 14
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/CoreErrors.cpp.o
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.hpp:104:1: error: expected unqualified-id before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.hpp:106:1: error: expected unqualified-id before \xe2\x80\x98==\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.hpp:108:1: error: expected unqualified-id before \xe2\x80\x98>>\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:85:3: error: expected primary-expression before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:85:5: error: expected primary-expression before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:85:7: error: expected primary-expression before \xe2\x80\x98<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:85:9: error: \xe2\x80\x98HEAD\xe2\x80\x99 was not declared in this scope
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:726:1: error: expected unqualified-id before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:1522:1: error: expected \xe2\x80\x98}\xe2\x80\x99 at end of input
make[2]: *** [plugins/unicodelib/CMakeFiles/unicodelib.dir/unicodelib.cpp.o] Error 1
make[1]: *** [plugins/unicodelib/CMakeFiles/unicodelib.dir/all] Error 2
[100%] Building CXX object aws-cpp-sdk-sqs/CMakeFiles/aws-cpp-sdk-sqs.dir/source/SQSErrors.cpp.o
make: *** [all] Error 2
Get ECLWatch build result

2017-08-09 18:47 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: a2e39252c92d2712881dc6fc397d0fd4e06e2dcc
Build: failed
Number of Error(s): 14
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.hpp:104:1: error: expected unqualified-id before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.hpp:106:1: error: expected unqualified-id before \xe2\x80\x98==\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.hpp:108:1: error: expected unqualified-id before \xe2\x80\x98>>\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:85:3: error: expected primary-expression before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:85:5: error: expected primary-expression before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:85:7: error: expected primary-expression before \xe2\x80\x98<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:85:9: error: \xe2\x80\x98HEAD\xe2\x80\x99 was not declared in this scope
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:726:1: error: expected unqualified-id before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:1522:1: error: expected \xe2\x80\x98}\xe2\x80\x99 at end of input
make[2]: *** [plugins/unicodelib/CMakeFiles/unicodelib.dir/unicodelib.cpp.o] Error 1
make[1]: *** [plugins/unicodelib/CMakeFiles/unicodelib.dir/all] Error 2
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/CoreErrors.cpp.o
[100%] Building CXX object aws-cpp-sdk-sqs/CMakeFiles/aws-cpp-sdk-sqs.dir/source/SQSErrors.cpp.o
make: *** [all] Error 2
Get ECLWatch build result

2017-08-09 19:20 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 0c19b22d46b6c4d99af9de3835617f9b0be48806
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 45.089 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |743 |1 |
|test (thor) |639 |638 |1 |
|test (roxie) |772 |771 |1 |


[Errors:](https://gist.github.com/79dede51cbc971a8adab07da68edf710)
- test
  - hthor
    - 675\. [teststdlibrary](https://gist.github.com/HPCCSmoketest/79dede51cbc971a8adab07da68edf710#file-teststdlibrary-no-log), 
  - thor
    - 587\. [teststdlibrary](https://gist.github.com/HPCCSmoketest/79dede51cbc971a8adab07da68edf710#file-teststdlibrary-no-log), 
  - roxie
    - 708\. [teststdlibrary](https://gist.github.com/HPCCSmoketest/79dede51cbc971a8adab07da68edf710#file-teststdlibrary-no-log), 

HPCC Stop: OK
HPCC Uninstall: OK

2017-08-09 19:46 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 283ac6405735044bd038b8705a4ffebfafa20981
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 44.318 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-09 20:22 UTC, dskaff commented
@johnholt please code review.

2017-08-09 21:10 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 88980399d9751a72b2b6f6fa75f20e284eac738b
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 42.3 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-14 15:11 UTC, ghalliday requested changes
@dskaff a good first stab, but I have some concerns about some of the code.

2017-08-14 15:11 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +            if (bi.previous() == bi.first() && wordidx == 1)
This isn't safe.  Both bi.first() and bi.previous() modify the current iterator position.  It is undefined which is called first.

I think you should be comparing against 0.

2017-08-14 15:11 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +            if (bi.previous() == bi.first() && wordidx == 1)
It isn't clear what this code is here for - there should be a comment to describe why

2017-08-14 15:11 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +void excludeLastWord(RuleBasedBreakIterator& bi, UnicodeString & source)
style: Not keen on a parameter that is modified being called source (see other PRs for comments)

2017-08-14 15:11 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +            if (bi.previous() == bi.first() && wordidx == 1)
Actually documentation says:  
The character index of the preceding text boundary, or UBRK_DONE if all text boundaries have been returned.

I'm not sure what you are testing here.

2017-08-14 15:11 UTC, ghalliday commented
Also checkboxes are not completed on the PR.

2017-08-14 15:28 UTC, dskaff commented on plugins/unicodelib/unicodelib.cpp
> +            if (bi.previous() == bi.first() && wordidx == 1)
Normally, the function only removes the trailing white spaces of the last word, but when the source string only contains one word, the leading and trailing white spaces are removed (according to the string test cases).
The condition sets the iterator at the position previous to the beginning of the last word. If the string is only one word, then that position should be equal to bi.first().

2017-08-14 15:29 UTC, dskaff commented on plugins/unicodelib/unicodelib.cpp
> +            if (bi.previous() == bi.first() && wordidx == 1)
I'll change bi.first() to 0

2017-08-14 19:36 UTC, dskaff commented on plugins/unicodelib/unicodelib.cpp
> +            if (bi.previous() == bi.first() && wordidx == 1)
I don't believe that it will return UBRK_DONE unless you are using bi.preceding() while on the first boundary.

2017-08-14 21:20 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 0858c91c46139dbca7c065f7866f9b45d9374378
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 42.965 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-15 15:02 UTC, dskaff commented
@ghalliday please code review

2017-08-18 09:38 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +            if (bi.getRuleStatus() != UBRK_WORD_NONE)
This needs a comment explaining the logic - I can't follow it - or why bi.previous() would be called twice before checking it is 0.

2017-08-18 14:10 UTC, dskaff commented
@ghalliday I've commented the code

2017-08-18 14:20 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 9a4ac55b4f423575383931c6b28dc19a1a3d0325
Build: failed
Number of Error(s): 14
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.hpp:105:1: error: expected unqualified-id before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.hpp:107:1: error: expected unqualified-id before \xe2\x80\x98==\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.hpp:109:1: error: expected unqualified-id before \xe2\x80\x98>>\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:86:3: error: expected primary-expression before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:86:5: error: expected primary-expression before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:86:7: error: expected primary-expression before \xe2\x80\x98<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:86:9: error: \xe2\x80\x98HEAD\xe2\x80\x99 was not declared in this scope
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:727:1: error: expected unqualified-id before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-10321/HPCC-Platform/plugins/unicodelib/unicodelib.cpp:1586:1: error: expected \xe2\x80\x98}\xe2\x80\x99 at end of input
make[2]: *** [plugins/unicodelib/CMakeFiles/unicodelib.dir/unicodelib.cpp.o] Error 1
make[1]: *** [plugins/unicodelib/CMakeFiles/unicodelib.dir/all] Error 2
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/CoreErrors.cpp.o
[100%] Building CXX object aws-cpp-sdk-sqs/CMakeFiles/aws-cpp-sdk-sqs.dir/source/SQSErrors.cpp.o
make: *** [all] Error 2
Get ECLWatch build result

2017-08-21 15:20 UTC, ghalliday approved these changes

2017-08-21 15:58 UTC, merged

2017-08-21 16:12 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 43e3d7ea316c1c36f816cce2d9008f898131ad9e
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 46.405 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK