HPCC-18112 Unicode Implementation for StartsWith
hpcc-systems/HPCC-Platform pull request #10322
Opened 2017-08-09 15:24 UTC by dskaff

- Adds test cases for normal string and unicode capabilities
- Tests for new normalizer function involving an optional parameter.
- Documentation for startsWith in ecllibrary/std/Uni.ecl
- Adds code for the startsWith in unicodelib.cpp
- Adds code for the normalizationFormCheck function in unicodelib.cpp

Signed-off-by: David Skaff <david.skaff@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2017-08-09 16:02 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: b82af63bbcecd75a782d3b796dbe8182950c6b73
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 44.162 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |638 |1 |
|test (roxie) |772 |772 |0 |


[Errors:](https://gist.github.com/ae5db72928d922587da6040e2221a85a)
- test
  - thor
    - 587\. [teststdlibrary](https://gist.github.com/HPCCSmoketest/ae5db72928d922587da6040e2221a85a#file-teststdlibrary-w20170809-130157-2-log), 

HPCC Stop: OK
HPCC Uninstall: OK

2017-08-09 18:15 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 2e3523bce34b332bb56141667677b4e0859b24f1
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 44.421 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-09 19:20 UTC, dskaff commented
@johnholt please code review.

2017-08-14 15:34 UTC, ghalliday requested changes
See comments.

2017-08-14 15:34 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +    else if (form[3] == nfkc[3])
This could access invalid memory - e.g., if "XYZ" is passed as the form.  It would be clearer to explicitly compare against the characters.

2017-08-14 15:34 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +    return;
redundant return.

2017-08-14 15:34 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +    return;
errorCode should be checked.

2017-08-14 15:34 UTC, ghalliday commented on plugins/unicodelib/unicodelib.hpp
> +UNICODELIB_API bool UNICODELIB_CALL ulUnicodeLocaleStartsWith(unsigned srcLen, UChar const * src, unsigned prefLen, UChar const * pref, unsigned formLen, char const * form, bool bo);
The bo parameter looks wrong.

2017-08-14 15:34 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +        ol = FALSE;
should use false not FALSE

2017-08-14 15:34 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +        return ol;
return false; - no need to assign to o1

2017-08-14 15:34 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +    prefix.trim();
John, is it correct that this is removing leading spaces?

2017-08-14 15:34 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +        return ol;
see comments above

2017-08-14 15:34 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +    return ol;
return true I think.

2017-08-14 23:05 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: f830726a60495da3a1e9f552d3a9f697d27cd136
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 45.114 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-21 19:54 UTC, dskaff commented
@ghalliday the last thing to do to this branch is to correctly implement the errorcode check after normalizing

2017-08-21 20:28 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 29ab8efed72129b044f17cd4a4e4c46a9011c97f
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 43.478 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-23 14:31 UTC, dskaff commented on plugins/unicodelib/unicodelib.cpp
> +    return;
I'm currently checking it with a U_FAILURE(errorCode) condition at the end of the function. What should it return if it's true? the source string, unaltered?

2017-08-23 18:39 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 93ef57e18214026a15a51abde259d543e9836112
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 42.953 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-24 08:57 UTC, ghalliday commented on plugins/unicodelib/unicodelib.cpp
> +static const char * nfc = "NFC";
These variables are not used - please remove them.

2017-08-24 09:03 UTC, ghalliday commented on ecllibrary/teststd/uni/TestStartsWith.ecl
> +    EXPORT Test44 := ASSERT(Uni.StartsWith(t1,t2,'NFKD') = TRUE);
Do you have any examples which fail on some normalizations, but pass on others?  That would ensure the correct normalization was being used for the different cases.

2017-08-24 09:03 UTC, ghalliday approved these changes

2017-08-24 09:04 UTC, ghalliday commented
@dskaff a couple of minor comments - looks very close to being ready to merge.

2017-08-24 15:23 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 2e0776862983c6d0da432d769786b171741aadc4
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 46.317 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-24 15:57 UTC, merged