HPCC-11151 Support xpath(‘<>’) for write
hpcc-systems/HPCC-Platform pull request #10348
Opened 2017-08-20 00:13 UTC by afishbeck

When #OPTION('writeInlineContent', true); is used writing a field with
XPATH('Name/<>') will output the string without XML/JSON encoding
the content.  This allows users to insert arbitrary XML/JSON into
the output.

Also works with sets of strings XPATH('SetName/Name/<>').

There are 3 forms:
 '<>' Writes the content without a root tag.  Reading reads all
    content of parent.
 'Name<>' Writes the content without a <Name> tag.  Reading reads the
    content of the tag <Name>.
 'Name/<>' Writes the content inside <Name>.  Reading reads the
    content of the tag <Name>.

Also fixes generated schemas to indicate locations where arbitrary
content might appear.

Signed-off-by: Anthony Fishbeck <anthony.fishbeck@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2017-08-20 00:17 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: fe6fce8eb72d7c71a0b10121d12efb2ff1053a69
Build: failed
Number of Error(s): 6
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/CoreErrors.cpp.o
[100%] Building CXX object aws-cpp-sdk-sqs/CMakeFiles/aws-cpp-sdk-sqs.dir/source/SQSErrors.cpp.o
/mnt/disk1/home/vamosax/smoketest/PR-10348/HPCC-Platform/common/wuwebview/wuwebview.cpp:912:93: error: no matching function for call to \xe2\x80\x98IResultSetFactory::createResultSetMeta(IConstWUResult*&)\xe2\x80\x99
make[2]: *** [common/wuwebview/CMakeFiles/wuwebview.dir/wuwebview.cpp.o] Error 1
make[1]: *** [common/wuwebview/CMakeFiles/wuwebview.dir/all] Error 2
make: *** [all] Error 2
Get ECLWatch build result

2017-08-20 00:50 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 66eeb6c909d3c89936b7ff8fc1d1394a15d106da
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 43.914 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |746 |746 |0 |
|test (thor) |641 |641 |0 |
|test (roxie) |774 |774 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-24 19:51 UTC, afishbeck commented
@richardkchapman you may want to take a look at where this overlapped with your dynamic typeinfo changes.
@ghalliday Can you review?

2017-09-04 12:17 UTC, ghalliday requested changes
@afishbeck some initial comments.  It is probably worth me reviewing it all again later because it is quite a lot to take in at once.

Main issues are utf8 encoding of strings, and main comment is using enumerations instead of byte.

2017-09-04 12:17 UTC, ghalliday commented on ecl/hql/hqlutil.cpp
> +                bool isNamed = ((lenTagName >= lenContents + 1) && *--finger=='/');
minor: finger[-1] cleaner than *--finger, since the latter implies you are going to use the updated variable later on.

2017-09-04 12:17 UTC, ghalliday commented on ecl/hqlcpp/hqlhtcpp.cpp
> +        buildXmlSerializeScalar(loopctx, curElement, itemName, false);
The fourth parameter is a contentFlag, not a boolean.  Using an enum for the parameter would have caught it.

2017-09-04 12:17 UTC, ghalliday commented on common/thorhelper/thorxmlwrite.cpp
> +void CommonXmlWriter::outputInline(unsigned len, const char *field, const char *fieldname)
minor style: Cleaner if length parameter are size32_t rather than unsigned.

2017-09-04 12:17 UTC, ghalliday commented on esp/services/ws_workunits/ws_workunitsService.cpp
> +        if (0)//!req.getBypassCachedResult())
more: Is this left in by mistake?

2017-09-04 12:17 UTC, ghalliday commented on rtl/eclrtl/rtlfield.cpp
> +            target.outputInline(lenAscii, ascii.getstr(), field->hasNamedContentXpath() ? queryScalarXPath(field) : nullptr);
Same issues of conversion to utf8.

2017-09-04 12:17 UTC, ghalliday commented on rtl/eclrtl/rtlfield.cpp
> +        target.outputInline(thisLength, str, field->hasNamedContentXpath() ? queryScalarXPath(field) : nullptr);
Need to be careful about length v size.  (Worth naming size variables appropriately.)

2017-10-25 09:47 UTC, richardkchapman commented
@afishbeck This seems to be stalled (and needs rebasing)

2017-10-28 22:39 UTC, afishbeck commented
Will reopen when I return from PTO.

2017-10-28 22:39 UTC, closed without merging