HPCC-18175 DOCS:More detail on deschedule/reschedule
hpcc-systems/HPCC-Platform pull request #10347
Opened 2017-08-19 00:52 UTC by g-pan

Fix HPCC-18175 DOCS:More detail on deschedule/reschedule
Added more detail to the ECL Scheduler book, which by inclusion
will also update the ECL Watch doc.

@JamesDeFabia please review
   Tested:  http://10.240.32.243/view/Docs/job/DocDev0IV/

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2017-08-23 12:23 UTC, JamesDeFabia requested changes
comments inline

2017-08-23 12:23 UTC, JamesDeFabia commented on docs/ECLScheduler/ECLSched-Mods/ECLSchedComp.xml
> +        completes all of the COUNT there is no reschedule option.</para>
Once a workunit completes the COUNT, there is no reschedule option.

2017-08-23 12:23 UTC, JamesDeFabia commented on docs/ECLScheduler/ECLSched-Mods/ECLSchedComp.xml
> +        selected scheduled workunit. Press the <emphasis
to change a selected scheduled workunit. 
s/b 
to reschedule a descheduled workunit.

2017-08-23 12:23 UTC, JamesDeFabia commented on docs/ECLScheduler/ECLSched-Mods/ECLSchedComp.xml
> +        where it stopped and resumes whatever COUNT remains. Once a workunit
resumes the remaining COUNT.

2017-08-24 18:00 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 42040edc174944f9949055b5e50c0c17a7187596
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.141 seconds |


Install hpccsystems-platform-community_6.4.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-28 14:51 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 346e915fd08e85198d87049121de73e1ac533950
Build: failed
Number of Error(s): 1
-- Configuring incomplete, errors occurred!
Get ECLWatch build result

2017-08-28 15:05 UTC, g-pan commented
Not sure, what happened here, somehow the wrong commit message hijacked this Pull Req. 
I tried to amend when I squashed the commits, but no luck. I manually edited the message here. @JamesDeFabia  please review. Tested here: http://10.240.32.243/view/Docs/job/DocDev0IV/ 
Still Valid, and to show that build succeeds. where smoketest reports failure.

2017-08-28 15:32 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: d3e93a88641aab05544aaa0ca91815fcfd069895
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.898 seconds |


Install hpccsystems-platform-community_6.4.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-28 18:10 UTC, JamesDeFabia approved these changes
Good to merge

2017-08-30 10:20 UTC, merged