HPCC-18218 Upgrade ESP to timeout session after client
hpcc-systems/HPCC-Platform pull request #10372
Opened 2017-08-29 14:32 UTC by wangkx

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2017-08-29 14:33 UTC, wangkx commented
@RussWhitehead please review.

2017-08-29 15:15 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 3328451925af7ffd628eff6dd04fc5bbc1f1b7dc
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 46.091 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-29 17:28 UTC, RussWhitehead commented
Please add a commit message to describe the reason for this PR

2017-08-29 17:37 UTC, RussWhitehead requested changes
A couple minor questions/comments

2017-08-29 17:37 UTC, RussWhitehead commented on esp/bindings/http/platform/httpbinding.cpp
> +            clientSessionTimeoutSeconds = ESP_SESSION_TIMEOUT;
Can't ESP_SESSION_TIMEOUT be passed as the second argument to getPropInt?

2017-08-29 17:37 UTC, RussWhitehead commented on esp/bindings/http/platform/httpbinding.hpp
> +    int                     serverSessionTimeoutSeconds = 2*ESP_SESSION_TIMEOUT; //-1: never
Would it be helpful to create a "#define NEVER_TIMEOUT -1"  ?

2017-08-29 17:37 UTC, RussWhitehead commented on initfiles/componentfiles/configxml/esp.xsd.in
> +	                  <tooltip>Inactive session duration, in minutes, that is used to timeout a sesion on ESP client. Specify 0 for default timeout, -1 for never time out.</tooltip>
"session" misspelled

2017-08-29 19:13 UTC, RussWhitehead commented
@wangkx Looks good

2017-08-29 19:32 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: e60c085cc435cd34050635f498b0ee5bdba4703a
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 42.828 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-29 19:40 UTC, wangkx commented
@richardkchapman this PR is ready to be merged.

2017-08-29 19:59 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 8caf10cbd9ace7068acb585580912ce497f90ab6
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 44.842 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-30 10:03 UTC, richardkchapman commented
@wangkx Please squash

2017-08-30 13:33 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 423f8c5a953d95488641c11ee62175036a53a8dc
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 46.967 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |91 |91 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-30 14:22 UTC, wangkx commented
@richardkchapman this PR has been squashed. Please merge.

2017-08-31 08:55 UTC, merged