HPCC-18168 DOCS:Updates Installing and Running
hpcc-systems/HPCC-Platform pull request #10378
Opened 2017-08-30 20:08 UTC by g-pan

Fix HPCC-18168 DOCS:Updates Installing and Running
Updates to the Installing and Running the HPCC Platform
document. Specifically to the init system calls.

Build Test Output (and resultant PDFs) can be found on: 
http://10.240.32.243/job/DocDev05/CE=ubuntu-14.04-amd64-1/

@Michael-Gardner please review.
@JamesDeFabia please review.

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2017-08-30 20:40 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 4b28d54fa3f7a7aed768ac11dddf9b0b3fdb95dd
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.402 seconds |


Install hpccsystems-platform-community_6.4.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-30 23:03 UTC, JamesDeFabia requested changes
Just a couple of comments inline...

2017-08-30 23:03 UTC, JamesDeFabia commented on docs/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +            hpcc-init directly, and not use a 'service' call.</para>
We suggest calling hpcc-init directly instead of using a 'service' call.

2017-08-30 23:03 UTC, JamesDeFabia commented on docs/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +                  though most distributions are deprecating the service calls.
However, you should be aware that most distributions are deprecating the service calls.

2017-08-30 23:03 UTC, JamesDeFabia commented on docs/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +                </listitem>
We suggest calling hpcc-init directly instead of using a 'service' call.

2017-08-31 08:56 UTC, richardkchapman commented
@g-pan

2017-08-31 12:50 UTC, g-pan commented
@Michael-Gardner please review

2017-08-31 13:00 UTC, JamesDeFabia approved these changes
Looks good to me. 
@Michael-Gardner you get last word

2017-08-31 13:03 UTC, Michael-Gardner commented
Reading through the changes and matching them up with my notes.  Will be done shortly.

2017-08-31 13:12 UTC, Michael-Gardner requested changes
Looks good aside from a few minor comments.

2017-08-31 13:12 UTC, Michael-Gardner commented on docs/DynamicESDL/DynamicESDL_Includer.xml
> +                    are stopped (on Centos/Red Hat):<para> <programlisting>sudo /etc/init.d/hpcc-init status</programlisting>
Don't think we need the (on Centos/redhat) comment here.  It will be the same across all distros.

2017-08-31 13:12 UTC, Michael-Gardner commented on docs/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
>          </listitem>
Shouldn't this be ...
'sudo dpkg -i <Deb filename> && sudo apt-get install -f' ?

2017-08-31 13:27 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: cd543a8d96c7d2dbdefb93f59d74b13b4dab4c70
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.567 seconds |


Install hpccsystems-platform-community_6.4.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-31 13:44 UTC, g-pan commented
Revisions made, squashed and rebased.

2017-08-31 14:25 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 7156f2a8449586afbe7291c481d490b6039df6ad
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.602 seconds |


Install hpccsystems-platform-community_6.4.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-08-31 15:45 UTC, Michael-Gardner commented
Changes look good.

2017-08-31 15:54 UTC, JamesDeFabia commented
@richardkchapman This looks good to merge

2017-08-31 16:20 UTC, merged