HPCC-18061 DOCS:XREF does not display Thor cluster
hpcc-systems/HPCC-Platform pull request #10444
Opened 2017-09-21 17:36 UTC by g-pan

Fix HPCC-18061 DOCS:XREF does not display Thor cluster
Add documentation for XREF case on a multi-Thor system
where it does not display any or all Thor clusters.
(due to cluster not matching nodeGroup attribute)
Unit test and resultant PDF can be viewed in the ECL Watch manual
found on : http://10.240.32.243/view/Docs/job/DocDev0V/

@JamesDeFabia please review
@jakesmith please review 

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Unit test and resultant PDF can be viewed in the ECL Watch manual
found on : http://10.240.32.243/view/Docs/job/DocDev0V/

2017-09-21 17:45 UTC, g-pan commented
To resolve the conflict, lines 2340 - 2400 should be removed from the conflicted file.

2017-09-21 18:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: d4f4505df92e35f1fb514c0c41a2d976c8099a61
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.098 seconds |


Install hpccsystems-platform-community_6.4.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-09-21 18:20 UTC, JamesDeFabia requested changes
For screenshot --ECLWA436.jpg, it makes more sense to check the checkboxes next to both orphan files. You wouldn't delete one file part and not delete the replicated file part.

2017-09-21 19:18 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 0bf5f026af00e075cfe902e64ecb6cfa4ef376cf
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.514 seconds |


Install hpccsystems-platform-community_6.4.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-09-21 21:27 UTC, JamesDeFabia approved these changes
Looks good from my POV. @jakesmith should have the last word

2017-09-22 10:23 UTC, jakesmith requested changes

2017-09-22 10:23 UTC, jakesmith commented on docs/ECLWatch/TheECLWatchMan.xml
> +          with more than one Thor cluster, ECL Watch only displays the Thor
>For a configuration with more than one Thor cluster

Need to be clear that it's not any configuration with greater than 1 Thor, but clusters with greater than 1 Thor on the same physical group.

Perhaps:

> For a configuration with more than one Thor cluster on the same physical node group, ...

2017-09-22 10:23 UTC, jakesmith commented on docs/ECLWatch/TheECLWatchMan.xml
> +          matches the nodeGroup in the configuration.)</para>
It doesn't display nodes anywhere, does it? It displays file parts.


Should the whole of the above comment in fact be talking about which Thor's are listed, not nodes, or parts.
Eclwatch XREF will only show the primary Thor not the other Thor's that share the same node group.

2017-09-22 10:23 UTC, jakesmith commented on docs/ECLWatch/TheECLWatchMan.xml
> +          <para>Typically, these files are deleted. To Delete, check the boxes
>Typically, these files are deleted.

Perhaps:

>Typically, these files will need to be deleted.

2017-09-22 10:23 UTC, jakesmith commented
@g-pan - a few mostly minor suggested changes.

2017-09-22 11:51 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +        "lost and found" files. These "orphan" are files which are found on
our style is to use the Oxford comma, so:
**to find "orphaned", "lost", and "found" files.**

2017-09-22 13:08 UTC, g-pan commented
@jakesmith please review changes. 
@richardkchapman I don't understand this conflict, not showing up in my local branch.

2017-09-22 13:36 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 4220b2772e9f2127f33a5be5cf1a5ff60a111ffa
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.331 seconds |


Install hpccsystems-platform-community_6.4.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-09-22 13:43 UTC, jakesmith commented
>I don't understand this conflict, not showing up in my local branch.
@g-pan - the commit SHA your commit is based on is not up to date. i.e. it is not the same as the upstream candidate-6.4.x SHA

2017-09-22 15:10 UTC, jakesmith commented
@g-pan - apart from rebasing issue, changes look good.

2017-09-22 18:01 UTC, g-pan commented
@jakesmith Thank You

2017-09-22 18:36 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 9c9ba324de77e7d7ce1fab0cf4134571e70fe3c3
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 94.348 seconds |


Install hpccsystems-platform-community_6.4.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-09-25 09:35 UTC, merged