HPCC-18419 Service to retrieve serialized typeInfo informatio
hpcc-systems/HPCC-Platform pull request #10480
Opened 2017-10-08 12:34 UTC by shamser

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2017-10-08 14:06 UTC, richardkchapman commented
Commit titles need fixing - and please squash

2017-10-08 18:35 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 0767f258faf5435da4f9dd3add218a5bac7f2975
Build: failed
Number of Error(s): 9
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/CoreErrors.cpp.o
[100%] Building CXX object aws-cpp-sdk-sqs/CMakeFiles/aws-cpp-sdk-sqs.dir/source/SQSErrors.cpp.o
/mnt/disk1/home/vamosax/smoketest/PR-10480/HPCC-Platform/esp/services/ws_dfu/ws_dfuService.cpp:1585:41: error: \xe2\x80\x98exportJsonType\xe2\x80\x99 was not declared in this scope
/mnt/disk1/home/vamosax/smoketest/PR-10480/HPCC-Platform/esp/services/ws_dfu/ws_dfuService.cpp:1586:42: error: \xe2\x80\x98exportBinaryType\xe2\x80\x99 was not declared in this scope
/mnt/disk1/home/vamosax/smoketest/PR-10480/HPCC-Platform/esp/services/ws_dfu/ws_dfuService.cpp:2273:49: error: \xe2\x80\x98exportJsonType\xe2\x80\x99 was not declared in this scope
/mnt/disk1/home/vamosax/smoketest/PR-10480/HPCC-Platform/esp/services/ws_dfu/ws_dfuService.cpp:2279:50: error: \xe2\x80\x98exportBinaryType\xe2\x80\x99 was not declared in this scope
make[2]: *** [esp/services/ws_dfu/CMakeFiles/ws_dfu.dir/ws_dfuService.cpp.o] Error 1
make[1]: *** [esp/services/ws_dfu/CMakeFiles/ws_dfu.dir/all] Error 2
make: *** [all] Error 2
Get ECLWatch build result

2017-10-08 19:33 UTC, afishbeck requested changes

2017-10-08 19:33 UTC, afishbeck commented on esp/services/ws_dfu/ws_dfuService.cpp
> +            throw MakeStringException(ECLWATCH_DFU_ACCESS_DENIED, "Failed to access DFUDefFile. Permission denied.");
Wrong method name in exception text.

2017-10-08 19:33 UTC, afishbeck commented on esp/scm/ws_dfu.ecm
> +};
Should we support:

  [min_ver("1.37")] bool IncludeJsonTypeInfo(true);
  [min_ver("1.37")] bool IncludeBinTypeInfo(true);

2017-10-08 19:33 UTC, afishbeck commented on esp/services/ws_dfu/ws_dfuService.cpp
> +        PROGLOG("DFUDefFile: %s", fileName);
Wrong method name.

2017-10-08 19:33 UTC, afishbeck commented on esp/services/ws_dfu/ws_dfuService.cpp
> +        StringBuffer username;
could just use a const char * and context.queryUserName() (or whatever it's called).

2017-10-08 19:33 UTC, afishbeck commented on esp/services/ws_dfu/ws_dfuService.cpp
> +        StringBuffer rawStr,returnStr;
Unused.

2017-10-08 19:33 UTC, afishbeck commented on esp/services/ws_dfu/ws_dfuService.cpp
> +            throw MakeStringException(ECLWATCH_MISSING_PARAMS,"No record definition for file %s.",fileName);
"ECL record definition" or just "ECL definition".

2017-10-08 19:33 UTC, afishbeck commented on esp/services/ws_dfu/ws_dfuService.cpp
> +            throw MakeStringException(ECLWATCH_CANNOT_PARSE_ECL_QUERY, "Failed in parsing ECL query: %s @ %d:%d.", errtext.str(), first->getColumn(), first->getLine());
Change "query" to "record definition".

2017-10-08 19:33 UTC, afishbeck commented on esp/services/ws_dfu/ws_dfuService.cpp
> +            throw MakeStringException(ECLWATCH_CANNOT_PARSE_ECL_QUERY, "Failed in parsing ECL query.");
same.

2017-10-08 19:33 UTC, afishbeck commented on esp/services/ws_dfu/ws_dfuService.cpp
> +                throw MakeStringException(ECLWATCH_CANNOT_PARSE_ECL_QUERY, "Failed in parsing ECL query: %s @ %d:%d.", errtext.str(), first->getColumn(), first->getLine());
same.

2017-10-08 19:33 UTC, afishbeck commented on esp/services/ws_dfu/ws_dfuService.cpp
> +                throw MakeStringException(ECLWATCH_CANNOT_PARSE_ECL_QUERY, "Failed in parsing ECL query.");
same.

2017-10-08 19:33 UTC, afishbeck commented on esp/services/ws_dfu/ws_dfuService.hpp
> +	bool onDFURecordTypeInfo(IEspContext &context, IEspDFURecordTypeInfoRequest &req, IEspDFURecordTypeInfoResponse &resp);
indentation.

2017-10-08 19:34 UTC, afishbeck commented
@shamser back to you.

2017-10-08 20:37 UTC, afishbeck approved these changes
@shamser looks good

2017-10-08 20:51 UTC, shamser commented
@ghalliday it's ready to merge.

2017-10-08 20:58 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 520cd0049a64b32df4daca050a468071f49474bc
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 41.165 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |92 |92 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |741 |3 |
|test (thor) |639 |638 |1 |
|test (roxie) |772 |772 |0 |


[Errors:](https://gist.github.com/79a252b2decd0a402934dced8877a009)
- test
  - hthor
    - 285\. [imgkey](https://gist.github.com/HPCCSmoketest/79a252b2decd0a402934dced8877a009#file-imgkey-w20171008-174914-8-log), 448\. [pipe](https://gist.github.com/HPCCSmoketest/79a252b2decd0a402934dced8877a009#file-pipe-w20171008-174954-8-log), 456\. [pipe9](https://gist.github.com/HPCCSmoketest/79a252b2decd0a402934dced8877a009#file-pipe9-w20171008-174956-log), 
  - thor
    - 260\. [imgkey](https://gist.github.com/HPCCSmoketest/79a252b2decd0a402934dced8877a009#file-imgkey-w20171008-175310-3-log), 

HPCC Stop: OK
HPCC Uninstall: OK

2017-10-08 21:04 UTC, ghalliday commented on esp/services/ws_dfu/ws_dfuService.cpp
> +        MultiErrorReceiver errs;
This code should really be shared with the code below - a bit too much cut and paste.

2017-10-08 21:25 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 0087e060ea9fef0a7d79e726420689bf6aaec624
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 41.308 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |92 |92 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |741 |3 |
|test (thor) |639 |638 |1 |
|test (roxie) |772 |772 |0 |


[Errors:](https://gist.github.com/d9d05541792c26f80beda401d8ff52de)
- test
  - hthor
    - 285\. [imgkey](https://gist.github.com/HPCCSmoketest/d9d05541792c26f80beda401d8ff52de#file-imgkey-w20171008-181608-4-log), 448\. [pipe](https://gist.github.com/HPCCSmoketest/d9d05541792c26f80beda401d8ff52de#file-pipe-w20171008-181648-1-log), 456\. [pipe9](https://gist.github.com/HPCCSmoketest/d9d05541792c26f80beda401d8ff52de#file-pipe9-w20171008-181650-3-log), 
  - thor
    - 260\. [imgkey](https://gist.github.com/HPCCSmoketest/d9d05541792c26f80beda401d8ff52de#file-imgkey-w20171008-182009-log), 

HPCC Stop: OK
HPCC Uninstall: OK

2017-10-09 13:03 UTC, shamser commented
@ghalliday Code modified as per code review comment.

2017-10-09 13:28 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 989cbf159536c72bc94a432476fa118a2f8adb22
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 45.573 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |92 |92 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |741 |3 |
|test (thor) |639 |638 |1 |
|test (roxie) |772 |772 |0 |


[Errors:](https://gist.github.com/d3347d852374e67d6429fec7df56d7fb)
- test
  - hthor
    - 285\. [imgkey](https://gist.github.com/HPCCSmoketest/d3347d852374e67d6429fec7df56d7fb#file-imgkey-w20171009-101935-4-log), 448\. [pipe](https://gist.github.com/HPCCSmoketest/d3347d852374e67d6429fec7df56d7fb#file-pipe-w20171009-102014-2-log), 456\. [pipe9](https://gist.github.com/HPCCSmoketest/d3347d852374e67d6429fec7df56d7fb#file-pipe9-w20171009-102017-log), 
  - thor
    - 260\. [imgkey](https://gist.github.com/HPCCSmoketest/d3347d852374e67d6429fec7df56d7fb#file-imgkey-w20171009-102309-3-log), 

HPCC Stop: OK
HPCC Uninstall: OK

2017-10-09 19:07 UTC, ghalliday commented on esp/services/ws_dfu/ws_dfuService.cpp
> +        OwnedHqlExpr record = getEclRecordDefinition(df->queryAttributes().queryProp("ECL"));
This will now crash if queryProp("ECL") is null

2017-10-09 19:09 UTC, ghalliday commented
@shamser see comment above

2017-10-09 19:51 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: defab96dfd7f81f42a7511833d6637a086a9602d
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 41.009 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |92 |92 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |741 |3 |
|test (thor) |639 |638 |1 |
|test (roxie) |772 |772 |0 |


[Errors:](https://gist.github.com/19b69a4ac31a6937e9c2962405d72607)
- test
  - hthor
    - 285\. [imgkey](https://gist.github.com/HPCCSmoketest/19b69a4ac31a6937e9c2962405d72607#file-imgkey-w20171009-164213-2-log), 448\. [pipe](https://gist.github.com/HPCCSmoketest/19b69a4ac31a6937e9c2962405d72607#file-pipe-w20171009-164253-1-log), 456\. [pipe9](https://gist.github.com/HPCCSmoketest/19b69a4ac31a6937e9c2962405d72607#file-pipe9-w20171009-164254-2-log), 
  - thor
    - 260\. [imgkey](https://gist.github.com/HPCCSmoketest/19b69a4ac31a6937e9c2962405d72607#file-imgkey-w20171009-164610-4-log), 

HPCC Stop: OK
HPCC Uninstall: OK

2017-10-09 19:59 UTC, merged

2017-10-09 20:44 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: e4e5e16b2a2fff7ac2f95c6bc2220fe3276cd0ec
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 40.833 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |92 |92 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |744 |744 |0 |
|test (thor) |639 |639 |0 |
|test (roxie) |772 |772 |0 |


HPCC Stop: OK
HPCC Uninstall: OK