HPCC-18518 Improve ws_FsService exception error message for missing Drop Zone.
hpcc-systems/HPCC-Platform pull request #10498
Opened 2017-10-13 15:35 UTC by AttilaVamos

Exted exception error message.

Signed-off-by: Attila Vamos <attila.vamos@gmail.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Tested manually with DFUPlus.

2017-10-13 15:38 UTC, AttilaVamos commented
@richardkchapman please review and check whether the target is appropriate.

2017-10-13 16:11 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: da115a48ed65d40238830455f5dbd34d7d11b90d
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.697 seconds |


Install hpccsystems-platform-community_6.4.4-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |96 |96 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-10-17 11:48 UTC, richardkchapman commented
@rpastrana Please review

2017-10-17 13:02 UTC, rpastrana requested changes
@AttilaVamos one suggestion.

2017-10-17 13:20 UTC, richardkchapman commented
There's a typo in the commit message (Exted)

2017-10-17 13:30 UTC, AttilaVamos commented
@rpastrana I can't see your suggestion.

2017-10-17 13:50 UTC, rpastrana commented
@AttilaVamos I'm not sure what happened to my original message, here it is again:
At the point where the exception in thrown, we don't know if the error is due to an address or a path mismatch. Also, it might be helpful to point users to configuration.
"No dropzone configured for <IP> and <Path>. Check your system dropzone configuration"

2017-10-17 15:52 UTC, AttilaVamos commented
@rpastrana Actually the CLocalEnvironmnet doesn't provide more information about why the address and the path not match. Actually it provides a Boolean value only. Perhaps another JIRA needed to implement that if it is really necessary.
Error messages updated.

2017-10-17 16:35 UTC, rpastrana commented on esp/services/ws_fs/ws_fsService.cpp
> +            throw MakeStringException(ECLWATCH_DROP_ZONE_NOT_FOUND, "Drop zone to target '%s' not found for network address '%s'. Check your system drop zone configuration.", destFile.str(), ip);
@AttilaVamos
"No dropzone configured for 'IP' and 'PATH'. Check your system dropzone configuration" seems more direct and to the point. @JamesDeFabia  what do you think?
Also, is it "Dropzone" or "drop zone" ?

2017-10-17 17:34 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 95ce511a1d990a48bdc6c9e1bc094d5b8f78ad2b
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.29 seconds |


Install hpccsystems-platform-community_6.4.4-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |96 |96 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-10-17 20:36 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: aec1fcac6e1e0cfed0a42ae60f74d379adf95169
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.534 seconds |


Install hpccsystems-platform-community_6.4.4-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |96 |96 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-10-20 16:49 UTC, AttilaVamos commented
@richardkchapman 'useDropZoneRestriction' flag handling added.

2017-10-20 16:59 UTC, AttilaVamos commented
ESP server crashed. Something is missing.

2017-10-20 17:15 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 9ad73e2925d45313f2fa764d7cdc4906bc28e891
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.753 seconds |


Install hpccsystems-platform-community_6.4.4-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |96 |96 |0 | |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-10-20 17:21 UTC, AttilaVamos commented
@richardkchapman ESP crash fixed, please review.

2017-10-20 18:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 52870f2cecaf9ae3f9383acfe44f01f3e63522f4
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.08 seconds |


Install hpccsystems-platform-community_6.4.4-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |96 |96 |0 | |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-10-23 11:25 UTC, merged