IDE-641 DOCS:Other language functionality
hpcc-systems/HPCC-Platform pull request #10535
Opened 2017-10-19 18:56 UTC by g-pan

Fix IDE-641 DOCS:Other language functionality
Document the ECL IDE functionality
for other languages in addition to ECL.

@JamesDeFabia please review
@dehilsterlexis please review 
PDF and Build Test output can be obtained from http://10.240.32.243/view/Docs/job/DocDevII/
(this content can be found on pg 40-41 of the ECL IDE and Client Tools doc)

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Successful Build Test http://10.240.32.243/view/Docs/job/DocDevII/

2017-10-19 20:49 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 562222e1e7e11fae820c9a47eb44c0a099b97883
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 94.114 seconds |


Install hpccsystems-platform-community_6.4.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-10-25 15:26 UTC, JamesDeFabia requested changes
Comments inline. Be aware that the same changes need to be made for each file type.

2017-10-25 15:26 UTC, JamesDeFabia commented on docs/HPCCClientTools/CT_Mods/CT_ECL_IDE.xml
> +                          <para>Colorized file differentiation</para>
Colorized file differentiation is confusing. What you are trying to say is: 
Repository icon is colorized to identify the file type.

2017-10-25 15:26 UTC, JamesDeFabia commented on docs/HPCCClientTools/CT_Mods/CT_ECL_IDE.xml
> +
also Submit Selected

2017-10-25 15:26 UTC, JamesDeFabia commented on docs/HPCCClientTools/CT_Mods/CT_ECL_IDE.xml
> +                        </listitem>
Syntax Highlighting

2017-10-26 18:05 UTC, g-pan commented
Updated. Added changes based on comments. @JamesDeFabia please review
@dehilsterlexis please review

2017-10-26 18:27 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 93836e12379999ea9b1ec3c2ca134b4c7a069b22
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.05 seconds |


Install hpccsystems-platform-community_6.4.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-10-26 18:57 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: b68fdd7c6d3bb4f108702a35efa6bad3fa5e330f
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.697 seconds |


Install hpccsystems-platform-community_6.4.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |733 |733 |0 |
|test (thor) |627 |627 |0 |
|test (roxie) |760 |760 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-10-26 18:58 UTC, JamesDeFabia approved these changes
Looks good to merge

2017-10-26 20:35 UTC, dehilsterlexis commented
Looks good to me

2017-10-27 11:10 UTC, merged