HPCC-17569 Add roxie support for persistent http connections
hpcc-systems/HPCC-Platform pull request #10892
Opened 2018-02-20 15:51 UTC by afishbeck

Signed-off-by: Anthony Fishbeck <anthony.fishbeck@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-02-20 15:54 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 95abcc20eb70cddcaf7d0b039bd8c5abcbf88627
Number of Error(s): 8
 /usr/bin/install -c -m 644 include/antlr3.h include/antlr3baserecognizer.h include/antlr3basetree.h include/antlr3basetreeadaptor.h include/antlr3bitset.h include/antlr3collections.h include/antlr3commontoken.h include/antlr3commontree.h include/antlr3commontreeadaptor.h include/antlr3commontreenodestream.h include/antlr3convertutf.h include/antlr3cyclicdfa.h include/antlr3debugeventlistener.h include/antlr3defs.h include/antlr3encodings.h include/antlr3errors.h include/antlr3exception.h include/antlr3filestream.h include/antlr3input.h include/antlr3interfaces.h include/antlr3intstream.h include/antlr3lexer.h include/antlr3memory.h include/antlr3parser.h include/antlr3parsetree.h include/antlr3recognizersharedstate.h include/antlr3rewritestreams.h include/antlr3string.h include/antlr3tokenstream.h include/antlr3treeparser.h antlr3config.h /mnt/disk1/home/vamosax/smoketest/PR-10892/build/esp/services/ws_sql/antlr3c/include
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/CoreErrors.cpp.o
[100%] Building CXX object aws-cpp-sdk-sqs/CMakeFiles/aws-cpp-sdk-sqs.dir/source/SQSErrors.cpp.o
/mnt/disk1/home/vamosax/smoketest/PR-10892/HPCC-Platform/common/thorhelper/roxiehelper.cpp:1615:55: error: invalid use of void expression
/mnt/disk1/home/vamosax/smoketest/PR-10892/HPCC-Platform/common/thorhelper/roxiehelper.cpp:1615:86: error: invalid use of void expression
make[2]: *** [common/thorhelper/CMakeFiles/thorhelper.dir/roxiehelper.cpp.o] Error 1
make[1]: *** [common/thorhelper/CMakeFiles/thorhelper.dir/all] Error 2
make: *** [all] Error 2
Get ECLWatch build result

[Build error:](https://gist.github.com/a1bd2c3ccc140d06ea45a48aaf6c96fc)
Build log [Build log](https://gist.github.com/HPCCSmoketest/a1bd2c3ccc140d06ea45a48aaf6c96fc#file-result-18-02-20-12-00-37-log)

2018-03-01 10:03 UTC, richardkchapman commented
These smoketest errors look unrelated. @AttilaVamos can you check?

2018-03-01 10:53 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 95abcc20eb70cddcaf7d0b039bd8c5abcbf88627
Number of Error(s): 8
 /usr/bin/install -c -m 644 include/antlr3.h include/antlr3baserecognizer.h include/antlr3basetree.h include/antlr3basetreeadaptor.h include/antlr3bitset.h include/antlr3collections.h include/antlr3commontoken.h include/antlr3commontree.h include/antlr3commontreeadaptor.h include/antlr3commontreenodestream.h include/antlr3convertutf.h include/antlr3cyclicdfa.h include/antlr3debugeventlistener.h include/antlr3defs.h include/antlr3encodings.h include/antlr3errors.h include/antlr3exception.h include/antlr3filestream.h include/antlr3input.h include/antlr3interfaces.h include/antlr3intstream.h include/antlr3lexer.h include/antlr3memory.h include/antlr3parser.h include/antlr3parsetree.h include/antlr3recognizersharedstate.h include/antlr3rewritestreams.h include/antlr3string.h include/antlr3tokenstream.h include/antlr3treeparser.h antlr3config.h /mnt/disk1/home/vamosax/smoketest/PR-10892/build/esp/services/ws_sql/antlr3c/include
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/CoreErrors.cpp.o
[100%] Building CXX object aws-cpp-sdk-sqs/CMakeFiles/aws-cpp-sdk-sqs.dir/source/SQSErrors.cpp.o
/mnt/disk1/home/vamosax/smoketest/PR-10892/HPCC-Platform/common/thorhelper/roxiehelper.cpp:1615:55: error: invalid use of void expression
/mnt/disk1/home/vamosax/smoketest/PR-10892/HPCC-Platform/common/thorhelper/roxiehelper.cpp:1615:86: error: invalid use of void expression
make[2]: *** [common/thorhelper/CMakeFiles/thorhelper.dir/roxiehelper.cpp.o] Error 1
make[1]: *** [common/thorhelper/CMakeFiles/thorhelper.dir/all] Error 2
make: *** [all] Error 2
Get ECLWatch build result

[Build error:](https://gist.github.com/4a305e830959a04c39971af732dfcc7b)
Build log [Build log](https://gist.github.com/HPCCSmoketest/4a305e830959a04c39971af732dfcc7b#file-result-18-03-01-06-58-56-log)

2018-03-01 18:15 UTC, AttilaVamos requested changes
There is one problem which prevents to build your code.

2018-03-01 18:15 UTC, AttilaVamos commented on common/thorhelper/roxiehelper.cpp
> +        StringAttrBuilder headText(contentHead.clear()), tailText(contentTail.clear());
If I see well, the contentHead.clear() has no return value (void) and a StringAttrBuilder object needs a reference. 
I think the proper way is:
contentHead.clear();
contentTail.clear();
StringAttrBuilder headText(contentHead), tailText(contentTail);
(And it is build, I tested.)

2018-03-02 16:35 UTC, afishbeck commented
@richardkchapman Updated.

2018-03-02 17:11 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: ec842320011d6f0b88412c384acee3d4feb624ee
Build: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |83 |83 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |765 |765 |0 |
|test (thor) |679 |679 |0 |
|test (roxie) |792 |790 |2 |


[Errors:](https://gist.github.com/3e1882fadbd495849e92a4451896de80)
- test
  - roxie
    - 531\. [roxiepipe](https://gist.github.com/HPCCSmoketest/3e1882fadbd495849e92a4451896de80#file-roxiepipe-w20180302-131256-3-log), 576\. [soapcall (targetIP=127001, goodPort=9876, blacListedPort=9875)](https://gist.github.com/HPCCSmoketest/3e1882fadbd495849e92a4451896de80#file-soapcall-targetip-127001,-goodport-9876,-blaclistedport-9875-w20180302-131313-1-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   11 sec (00:00:11) |  181 sec (00:03:01) |   56 sec (00:00:56) |    6 sec (00:00:06) |   40 sec (00:00:40) | 1336 sec (00:22:16) |   32 sec (00:00:32) | 1662 sec (00:27:42) |

2018-03-02 17:53 UTC, closed without merging