HPCC-18904 Various DESDL U/I changes
hpcc-systems/HPCC-Platform pull request #10901
Opened 2018-02-22 17:06 UTC by miguelvazq

- Alphabetize definition items
- By default land on Dynamic ESDL tab

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-02-22 17:09 UTC, miguelvazq commented
@GordonSmith Please review.

2018-02-22 17:35 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 1ad5cbd09e133b85501e98b69e94ab0cc498f335
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 1 | 65 | 88.367 seconds |


Error(s): 
/mnt/disk1/home/vamosax/smoketest/PR-10901/build/esp/src/build/eclwatch/DynamicESDLDefinitionQueryWidget.js:
DynamicESDLDefinitionQueryWidget.js.uncompressed.js:17: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
    dojo/_base/declare,
    ^/mnt/disk1/home/vamosax/smoketest/PR-10901/build/esp/src/build/eclwatch/hpcc.js:
hpcc.js.uncompressed.js:64446: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
    dojo/_base/declare,
    ^/mnt/disk1/home/vamosax/smoketest/PR-10901/build/esp/src/build/eclwatch/TargetSelectClass.js:
TargetSelectClass.js.uncompressed.js:17: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
    dojo/_base/declare,
    ^

Install hpccsystems-platform-community_6.4.12-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |97 |97 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |734 |734 |0 |
|test (thor) |628 |628 |0 |
|test (roxie) |761 |761 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   10 sec (00:00:10) |  158 sec (00:02:38) |  159 sec (00:02:39) |    8 sec (00:00:08) |   36 sec (00:00:36) | 1090 sec (00:18:10) |   32 sec (00:00:32) | 1493 sec (00:24:53) |

2018-02-22 18:56 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: cc1620d3428f3e1bc249aa40821ea5ca885de8a2
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.031 seconds |



Install hpccsystems-platform-community_6.4.12-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |97 |97 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |734 |734 |0 |
|test (thor) |628 |628 |0 |
|test (roxie) |761 |761 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    7 sec (00:00:07) |  156 sec (00:02:36) |  163 sec (00:02:43) |    7 sec (00:00:07) |   38 sec (00:00:38) | 1093 sec (00:18:13) |   33 sec (00:00:33) | 1497 sec (00:24:57) |

2018-02-22 22:32 UTC, GordonSmith requested changes

2018-02-22 22:32 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDefinitionQueryWidget.js
> +                    context.grid.select({Name:firstRowSelection[0].Name});
Need to test if firstRowSelection.length?

2018-02-22 22:32 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLQueryWidget.js
> +            if (currSel.id == this.definitionQueryWidget.id && !this.definitionQueryWidget.initalized) {
Should be "==="

2018-02-23 09:38 UTC, richardkchapman commented
@miguelvazq

2018-02-23 15:52 UTC, miguelvazq commented
@GordonSmith Modified.

2018-02-23 16:41 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: ebe3507c26a68d7967f6bb61eb1ca015fb69021d
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 90.171 seconds |



Install hpccsystems-platform-community_6.4.12-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |97 |97 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |734 |734 |0 |
|test (thor) |628 |628 |0 |
|test (roxie) |761 |761 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   12 sec (00:00:12) |  159 sec (00:02:39) |  162 sec (00:02:42) |    7 sec (00:00:07) |   35 sec (00:00:35) | 1085 sec (00:18:05) |   32 sec (00:00:32) | 1492 sec (00:24:52) |

2018-02-26 09:36 UTC, GordonSmith requested changes

2018-02-26 09:36 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDefinitionQueryWidget.js
> +                if (context.params.firstLoad) {
Should probably be `context.params.firstLoad && ressults.length`

2018-02-26 16:55 UTC, miguelvazq commented
Good point. Updated.

2018-02-26 17:45 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 49f1f763ae2dfd37b9feaae6ed2a1ff9a0d09321
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 90.861 seconds |



Install hpccsystems-platform-community_6.4.12-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |97 |97 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |734 |734 |0 |
|test (thor) |628 |628 |0 |
|test (roxie) |761 |761 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  158 sec (00:02:38) |  163 sec (00:02:43) |    8 sec (00:00:08) |   38 sec (00:00:38) | 1097 sec (00:18:17) |   33 sec (00:00:33) | 1505 sec (00:25:05) |

2018-03-01 13:24 UTC, richardkchapman commented
@GordonSmith Ok to merge?

2018-03-01 13:25 UTC, GordonSmith commented
Looks good.

2018-03-01 13:27 UTC, merged