HPCC-18601 Re-evaluate package maps widget in 7.0
hpcc-systems/HPCC-Platform pull request #10958
Opened 2018-03-13 18:25 UTC by miguelvazq

Improving some of the code in PackageMapQueryWidget.js to take advantage
of the ECLWatch framework. U/I was not loading in 7.0.0 due
to some changes in dependencies - that has been fixed. Also, improve overall usability and
performance.

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-03-13 18:50 UTC, miguelvazq commented
@GordonSmith Please review

2018-03-13 18:52 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 6f5d98e29f6f0322a23f11c6429c7ea917ddad25
Build: success
ECL Watch:  Rebuilding Site
Rebuild: success

Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |83 |83 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |765 |765 |0 |
|test (thor) |679 |679 |0 |
|test (roxie) |792 |792 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   10 sec (00:00:10) |  181 sec (00:03:01) |  126 sec (00:02:06) |    7 sec (00:00:07) |   38 sec (00:00:38) | 1117 sec (00:18:37) |   32 sec (00:00:32) | 1511 sec (00:25:11) |

2018-04-11 20:02 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 3af17b87986b4ad5a4ff33faa7b830e6367ee747
Build: success
ECL Watch:  Rebuilding Site
Rebuild: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |85 |85 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |759 |759 |0 |
|test (thor) |686 |686 |0 |
|test (roxie) |799 |799 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   36 sec (00:00:36) |  181 sec (00:03:01) |  116 sec (00:01:56) |    7 sec (00:00:07) |   23 sec (00:00:23) | 1103 sec (00:18:23) |   17 sec (00:00:17) | 1483 sec (00:24:43) |

2018-04-18 08:56 UTC, GordonSmith requested changes
Looks ok - just some commented code to remove.

2018-04-18 08:56 UTC, GordonSmith commented on esp/src/eclwatch/PackageMapQueryWidget.js
> +        // },
Remove commented code.

2018-04-18 09:09 UTC, richardkchapman commented
@miguelvazq

2018-04-25 04:05 UTC, miguelvazq commented
@GordonSmith

2018-04-25 04:13 UTC, miguelvazq commented
@GordonSmith Removed comments and rebased

2018-04-25 04:54 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: f874e38ef3f10092e4d278db65cbda3828bcbbcd
Build: success
ECL Watch:  Rebuilding Site
ModuleNotFoundError: Module not found: Error: Cant resolve hpcc/ESPUtil in /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/eclwatch
    at factoryCallback (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at resolver (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/dojo-webpack-plugin/lib/DojoAMDModuleFactoryPlugin.js:73:7)
    at asyncLib.parallel (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/async/dist/async.js:3874:9
    at /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/async/dist/async.js:1048:13)
    at /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/async/dist/async.js:958:16
    at /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/async/dist/async.js:3871:13
    at resolvers.normal.resolve (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/tapable/lib/Tapable.js:252:11)
    at /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/mnt/disk1/home/vamosax/smokete
 ... ( comment is too long, 110 lines, 8618 bytes, truncated) ... 
[Build error:](https://gist.github.com/9d41fc09b304de7148b45d4814e98aa1)
Build log [Build log](https://gist.github.com/HPCCSmoketest/9d41fc09b304de7148b45d4814e98aa1#file-result-18-04-25-01-37-23-log)

```

2018-04-26 14:09 UTC, GordonSmith requested changes
I suspect this will fail linting due to duplicate vars.

2018-04-26 14:09 UTC, GordonSmith commented on esp/src/eclwatch/PackageMapQueryWidget.js
>              var context = this;
Already declared.

2018-04-26 14:09 UTC, GordonSmith commented on esp/src/eclwatch/PackageMapQueryWidget.js
> +            var context = this;
Already declared.

2018-04-26 15:04 UTC, miguelvazq commented
@GordonSmith Updated.

2018-04-26 15:53 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 5f5134d984149f335081adb3c6945ad0aa95841d
Build: success
ECL Watch:  Rebuilding Site
ModuleNotFoundError: Module not found: Error: Cant resolve hpcc/ESPUtil in /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/eclwatch
    at factoryCallback (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at resolver (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/dojo-webpack-plugin/lib/DojoAMDModuleFactoryPlugin.js:73:7)
    at asyncLib.parallel (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/async/dist/async.js:3874:9
    at /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/async/dist/async.js:1048:13)
    at /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/async/dist/async.js:958:16
    at /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/async/dist/async.js:3871:13
    at resolvers.normal.resolve (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/tapable/lib/Tapable.js:252:11)
    at /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/mnt/disk1/home/vamosax/smokete
 ... ( comment is too long, 110 lines, 8618 bytes, truncated) ... 
[Build error:](https://gist.github.com/290db3394410e1d16ab904212594ff23)
Build log [Build log](https://gist.github.com/HPCCSmoketest/290db3394410e1d16ab904212594ff23#file-result-18-04-26-11-27-39-log)

```

2018-05-03 15:15 UTC, miguelvazq commented
@GordonSmith I am not seeing where the smoketest would fail? Is this suspect? `Cant resolve hpcc/ESPUtil in /mnt/disk1/home/vamosax/smoketest/PR-10958/build/esp/src/tmp/eclwatch`

2018-05-07 18:29 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 58564cea800b9aa3f0279662c8b251234b4c40bf
Build: success
ECL Watch:  Rebuilding Site
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

Rebuild: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |784 |784 |0 |
|test (thor) |715 |715 |0 |
|test (roxie) |828 |828 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2018-05-07 18:45 UTC, miguelvazq commented
@GordonSmith Should be good now.

2018-05-08 07:32 UTC, GordonSmith approved these changes
Looks good.

2018-05-08 07:44 UTC, merged