HPCC-19601 Connect logMsgManager only when dali is available
hpcc-systems/HPCC-Platform pull request #11110
Opened 2018-05-02 21:53 UTC by wangkx

In HPCC-19504, the connectLogMsgManagerToDali() call is added when
ESP is started in order to access dali audit log. That causes that
 some esp like configMgr cannot be started since the esp does not
has a dali connection. In fix moves the call into ESP's initDali()
function. Also moves the disconnectLogMsgManagerFromDali() call
to the detachESPFromDali(). A dali detach check is added into
WsDfu.DFUDeleteFiles() so that a user cannot delete a logical
file when dali is detached.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-05-02 21:56 UTC, wangkx commented
@rpastrana Please review. I did a test for ConfigMgr and it was loaded. I also did a test for deleting a file and the log line was shown in the dali audit log.

2018-05-03 01:35 UTC, rpastrana requested changes
@wangkx a couple of questions and a comment.

2018-05-03 01:35 UTC, rpastrana commented on esp/services/ws_dfu/ws_dfuService.cpp
> +        throw MakeStringException(ECLWATCH_INVALID_INPUT, "Dali server is detached. Please try later.");
The ESP server is detached from Dali.

2018-05-03 01:35 UTC, rpastrana commented on esp/platform/espcfg.cpp
> +        connectLogMsgManagerToDali();
should we do this even if wsdfu is not bound on this esp process? is anybody else  dali logging ?

2018-05-03 01:35 UTC, rpastrana commented on esp/services/ws_dfu/ws_dfuService.hpp
> +        detached = false;
we might consider protecting access to detached...

2018-05-03 01:37 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 7ef395f891fe1a5976d69ccd412a1e7c5f901187
Build: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |780 |780 |0 |
|test (thor) |711 |711 |0 |
|test (roxie) |824 |824 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   18 sec (00:00:18) |  187 sec (00:03:07) |   55 sec (00:00:55) |    6 sec (00:00:06) |   22 sec (00:00:22) | 1201 sec (00:20:01) |   17 sec (00:00:17) | 1506 sec (00:25:06) |

2018-05-03 20:36 UTC, closed without merging