HPCC-19088 Document Std TimeZone functions
hpcc-systems/HPCC-Platform pull request #11149
Opened 2018-05-10 20:31 UTC by JamesDeFabia

Signed-off-by: Jim DeFabia <jamesdefabia@lexisnexis.com>
@dcamper Please review (pdf sent via email)

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-05-11 11:52 UTC, dcamper requested changes
Looks very good.  A few small changes.

2018-05-11 11:52 UTC, dcamper commented on docs/EN_US/ECLStandardLibraryReference/SLR-Mods/FindTZData.xml
> +          <entry>A new DATASET(TZDataLayout) containing the found
Recommend adding the record definition for TZDataLayout somewhere on this page (similar to what was done for Std.File.SuperfileContents).

2018-05-11 11:52 UTC, dcamper commented on docs/EN_US/ECLStandardLibraryReference/SLR-Mods/AdjustTimeTZ.xml
> +          <entry>REQUIRED. The time value to adjust.</entry>
Note that the data type is Std.Date.Time_t.

2018-05-11 11:52 UTC, dcamper commented on docs/EN_US/ECLStandardLibraryReference/SLR-Mods/ToLocalTime.xml
> +          <entry>REQUIRED. The UTC time value to adjust.</entry>
Note that the data type is Std.Date.Time_t.

2018-05-11 11:52 UTC, dcamper commented on docs/EN_US/ECLStandardLibraryReference/SLR-Mods/ToUTCTime.xml
> +          <entry>REQUIRED. The time value to adjust.</entry>
Note that the data type is Std.Date.Time_t.

2018-05-11 11:53 UTC, dcamper commented
@JamesDeFabia Looks great, overall.  Just a few minor changes.

2018-05-11 12:30 UTC, JamesDeFabia commented
@dcamper requested changes made, back to you

2018-05-11 12:35 UTC, dcamper requested changes
@JamesDeFabia Two minor things I missed first time around, then I think we'll be done.

2018-05-11 12:35 UTC, dcamper commented on docs/EN_US/ECLStandardLibraryReference/SLR-Mods/AdjustTimeTZ.xml
> +          non-empty uppercase string;</entry>
Trailing semicolon.

2018-05-11 12:35 UTC, dcamper commented on docs/EN_US/ECLStandardLibraryReference/SLR-Mods/ToUTCTime.xml
> +          string;</entry>
Trailing semicolon.

2018-05-11 13:06 UTC, JamesDeFabia commented
@dcamper back to you. Once you approve, i will squash

2018-05-11 13:07 UTC, dcamper approved these changes
@JamesDeFabia Looks great; can merge.

2018-05-11 13:09 UTC, JamesDeFabia commented
@richardkchapman This is good to merge. If you want me to squash, let me know

2018-05-11 13:17 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 2fb9c0ba392c4aea4506c97c907e66b81fb21d72
Build: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |784 |784 |0 |
|test (thor) |715 |715 |0 |
|test (roxie) |828 |828 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   22 sec (00:00:22) |  357 sec (00:05:57) |  109 sec (00:01:49) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1164 sec (00:19:24) |   18 sec (00:00:18) | 1705 sec (00:28:25) |

2018-05-11 13:47 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 32b0510c218a1aee9785eecb34768f13ef0263d4
Build: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |784 |784 |0 |
|test (thor) |715 |715 |0 |
|test (roxie) |828 |828 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   34 sec (00:00:34) |  355 sec (00:05:55) |  114 sec (00:01:54) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1189 sec (00:19:49) |   19 sec (00:00:19) | 1746 sec (00:29:06) |

2018-05-14 06:57 UTC, richardkchapman commented
@JamesDeFabia Please squash

2018-05-14 15:12 UTC, merged