HPCC-19561 Document nice-based priorities
hpcc-systems/HPCC-Platform pull request #11154
Opened 2018-05-11 15:13 UTC by g-pan

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

@mckellyln please review
@JamesDeFabia please review

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Successful integration testing :  http://10.240.32.243/view/Docs%207.0/job/Docs70-2/

2018-05-11 15:43 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 465e2274e7b891b16bad76620beb7cd3d1d8a8ca
Build: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |784 |784 |0 |
|test (thor) |715 |714 |1 |
|test (roxie) |828 |828 |0 |


[Errors:](https://gist.github.com/adc2033152967ca8da761c6488ca67dc)
- test
  - thor
    - 381\. [keyed_join3 (multiPart=false, forceRemoteKeyedLookup=true, forceRemoteKeyedFetch=true)](https://gist.github.com/HPCCSmoketest/adc2033152967ca8da761c6488ca67dc#file-keyed_join3-multipart-false,-forceremotekeyedlookup-true,-forceremotekeyedfetch-true-w20180511-113135-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  353 sec (00:05:53) |  108 sec (00:01:48) |    6 sec (00:00:06) |   27 sec (00:00:27) | 1223 sec (00:20:23) |   19 sec (00:00:19) | 1744 sec (00:29:04) |

2018-05-14 14:13 UTC, mckellyln commented
@g-pan I think the wording is ok.
Just FYI, I think the initial intended purpose of nice here was to lower the priority of longer running, heavy cpu usage processes, such as Thor, so that user interaction and pre-flight etc. would be more responsive while HPCC jobs were running.

2018-05-14 17:44 UTC, JamesDeFabia requested changes
one minor comment

2018-05-14 17:44 UTC, JamesDeFabia commented on docs/EN_US/HPCCSystemAdmin/HPCCSystemAdministratorsGuide.xml
> +        priorities. As nice is the Linux program which invokes scripts and
"As nice is the Linux program which invokes scripts and utilities with specified priorities" <--  Is a sentence fragment. Remove the word "As" and it's fine.

2018-05-14 18:04 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 368c42a5c3bb210ba177539e35b0f131ebfc05c4
Build: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |784 |784 |0 |
|test (thor) |715 |715 |0 |
|test (roxie) |828 |828 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  336 sec (00:05:36) |  111 sec (00:01:51) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1154 sec (00:19:14) |   19 sec (00:00:19) | 1672 sec (00:27:52) |

2018-05-14 18:32 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 111735a2f25499d352101b5a942e4b4cf19c5252
Build: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |784 |784 |0 |
|test (thor) |715 |715 |0 |
|test (roxie) |828 |828 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   18 sec (00:00:18) |  350 sec (00:05:50) |  111 sec (00:01:51) |    6 sec (00:00:06) |   27 sec (00:00:27) | 1149 sec (00:19:09) |   19 sec (00:00:19) | 1680 sec (00:28:00) |

2018-05-14 19:20 UTC, JamesDeFabia approved these changes
Looks good

2018-05-15 07:38 UTC, richardkchapman commented
@g-pan Please squash

2018-05-15 15:11 UTC, g-pan commented
squashed.

2018-05-16 08:39 UTC, merged