HPCC-3126 Rationalize ftslave and dafilesrv configuration
hpcc-systems/HPCC-Platform pull request #11196
Opened 2018-05-18 20:58 UTC by g-pan

Synapses of dafilesrv and ftslave, included in HPCC System Adminstrators guide. 

@jakesmith please review
@JamesDeFabia please review

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Completed Successful Build Test :  http://10.240.32.243/view/Docs%207.0/job/DocDev70/27/CE=ubuntu-14.04-amd64-1/

(HPCC Systems Administrators Guide)

2018-05-18 21:32 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: ea5138d56b5afcfe3798bf57003eecbc8c9c93c5
Build: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |786 |786 |0 |
|test (thor) |717 |717 |0 |
|test (roxie) |830 |830 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   37 sec (00:00:37) |  342 sec (00:05:42) |  112 sec (00:01:52) |    9 sec (00:00:09) |   29 sec (00:00:29) | 1166 sec (00:19:26) |   20 sec (00:00:20) | 1715 sec (00:28:35) |

2018-05-21 08:28 UTC, jakesmith commented on docs/EN_US/HPCCSystemAdmin/SA-Mods/DAFtslave.xml
> +    <para>The dafilesrv daemon runs as a process on every Thor or Roxie node.
Not just Thor and Roxie nodes, all hpcc nodes may require it at some stage. Anything that requires a file from another node will go via dafilesrv - so e.g. hthor creates files access by others will require a dafilesrv on the eclagent nodes, esp accessing logs from any remote component will require a dafilesrv to be running on the node that/those components are running on.

2018-05-21 08:28 UTC, jakesmith commented on docs/EN_US/HPCCSystemAdmin/SA-Mods/DAFtslave.xml
> +    when deploying data to the nodes. The ftslave is launched on demand as
It is not used by Thor or eclagent - it is only a process used by spraying by Dfu server.

2018-05-21 08:28 UTC, jakesmith commented on docs/EN_US/HPCCSystemAdmin/SA-Mods/DAFtslave.xml
> +    security.</para>
>It is also used to enable file security

That could be misleading. Or need to be clear that talking about physical vs logical security.
Dafilesrv can be configured to allow SSL connections only, which secures remote access to physical files.

2018-05-21 08:28 UTC, jakesmith commented
@g-pan - a couple of comments.

2018-05-22 11:18 UTC, g-pan commented
Excellent feedback @jakesmith I have incorporated it into the latest commit. 
@Michael-Gardner can you please review line # 31 for validity.

2018-05-22 12:04 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 29f339915e4f6390aa491ee7d47ec3a0f70fea3b
Build: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |786 |786 |0 |
|test (thor) |717 |717 |0 |
|test (roxie) |830 |830 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   30 sec (00:00:30) |  346 sec (00:05:46) |  111 sec (00:01:51) |    8 sec (00:00:08) |   29 sec (00:00:29) | 1148 sec (00:19:08) |   19 sec (00:00:19) | 1691 sec (00:28:11) |

2018-05-22 20:09 UTC, g-pan commented
@JamesDeFabia please review

2018-05-23 12:32 UTC, JamesDeFabia requested changes
comments inline

2018-05-23 12:32 UTC, JamesDeFabia commented on docs/EN_US/HPCCSystemAdmin/SA-Mods/DAFtslave.xml
> +    maintenance. Particularly for installations or upgrades. Even if you issue
Particularly for installations or upgrades. <-- sentence fragment

2018-05-23 12:32 UTC, JamesDeFabia commented on docs/EN_US/HPCCSystemAdmin/SA-Mods/DAFtslave.xml
> +    package.</para>
1) Doesn't the installer handle this automatically? 
2) The two sentences are better as a single sentence : Issue the following command to stop the dafilesrv daemon, then verify that dafilesrv is not running before running the installation package. 
3) Doesn't say HOW to verify that it is not running.

2018-05-23 14:59 UTC, g-pan commented
@Michael-Gardner after a few additional changes the line number changed. Could you please review line # 37 in the DAFtslave.xml file.

2018-05-23 15:47 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: f4c7fe6ada836e18a7644d931f39643a8df6f166
Build: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |786 |786 |0 |
|test (thor) |717 |717 |0 |
|test (roxie) |830 |830 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   28 sec (00:00:28) |  348 sec (00:05:48) |  111 sec (00:01:51) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1360 sec (00:22:40) |   18 sec (00:00:18) | 1900 sec (00:31:40) |

2018-05-30 13:46 UTC, Michael-Gardner commented on docs/EN_US/HPCCSystemAdmin/SA-Mods/DAFtslave.xml
> +    <programlisting>sudo /etc/HPCCSystems/sbin/hpcc-run.sh -a dafilesrv stop</programlisting>
should probably also add the systemd alternative here?

Also should be OPT not ETC for the root of this.

2018-05-30 14:21 UTC, g-pan commented
@Michael-Gardner please review latest revision.

2018-05-30 14:53 UTC, JamesDeFabia approved these changes
Looks reasonable from my POV. @Michael-Gardner should have the last word

2018-06-05 12:39 UTC, g-pan commented
@Michael-Gardner could you please review the changes you requested.

2018-06-05 13:12 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: b79b4e511e2491b7203fbf75a335badc69ec366d
Build: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |786 |786 |0 |
|test (thor) |717 |717 |0 |
|test (roxie) |830 |830 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   21 sec (00:00:21) |  355 sec (00:05:55) |  111 sec (00:01:51) |    9 sec (00:00:09) |   29 sec (00:00:29) | 1358 sec (00:22:38) |   19 sec (00:00:19) | 1902 sec (00:31:42) |

2018-06-18 17:32 UTC, Michael-Gardner commented
@g-pan Looks good to go!

2018-06-22 12:05 UTC, merged