HPCC-19755 Improve WsWorkunits.WUResultBin - file contents read
hpcc-systems/HPCC-Platform pull request #11219
Opened 2018-05-23 15:37 UTC by wangkx

1. if a logical file is created by a DFU workunit, the existing
WUResultBin cannot read the file contents due to the failure of
retrieve cluster name though the DFU workunit. In this fix, the
code is added to retrieve cluster name based on DFU workunit id.
2. if an ESP client already knows the cluster name, I am adding
a cluster name into the WUResultBin request so that the name
can be used directly without DFU workunit.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-05-23 15:38 UTC, wangkx commented
@afishbeck please review.

2018-05-23 17:06 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 00d3197e65267939efc53541635d49e7e6c7d87d
Build: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |786 |786 |0 |
|test (thor) |717 |717 |0 |
|test (roxie) |830 |830 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   35 sec (00:00:35) |  172 sec (00:02:52) |   61 sec (00:01:01) |    9 sec (00:00:09) |   29 sec (00:00:29) | 1385 sec (00:23:05) |   18 sec (00:00:18) | 1709 sec (00:28:29) |

2018-07-20 20:48 UTC, afishbeck commented on esp/services/ws_workunits/ws_workunitsService.cpp
> +            Owned<IPropertyTree> wuProps;// = getArchivedWorkUnitProperties(wuid);
Doesn't seem it will do anything.

2018-07-20 21:29 UTC, afishbeck requested changes
Looks like ECL workunits won't work, but the rest is fine.

2018-07-20 21:30 UTC, afishbeck commented
@wangkx some comments.

2018-07-23 21:33 UTC, wangkx commented on esp/services/ws_workunits/ws_workunitsService.cpp
> +            Owned<IPropertyTree> wuProps;// = getArchivedWorkUnitProperties(wuid);
This is copied from the existing code. I will fix it.

2018-07-24 12:08 UTC, wangkx commented
@afishbeck I rebased my first commit to the latest master. The second commit here is my changes based on your review. Please review.

2018-07-25 23:36 UTC, afishbeck approved these changes
@wangkx looks fine.

2018-07-26 09:00 UTC, richardkchapman commented
@wangkx Please squash

2018-07-26 12:52 UTC, wangkx commented
@richardkchapman squashed.

2018-07-26 13:19 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 5690eea4e642d8e493b3f622132226acbff2686d
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |797 |797 |0 |
|test (thor) |728 |728 |0 |
|test (roxie) |868 |868 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   26 sec (00:00:26) |  173 sec (00:02:53) |   61 sec (00:01:01) |    9 sec (00:00:09) |   30 sec (00:00:30) | 1308 sec (00:21:48) |   18 sec (00:00:18) | 1625 sec (00:27:05) |

2018-07-26 13:55 UTC, richardkchapman commented
Reviewed-By: Anthony Fishbeck <anthony.fishbeck@lexisnexis.com>
Reviewed-By: Richard Chapman <rchapman@hpccsystems.com>

2018-07-30 08:39 UTC, richardkchapman commented
@wangkx The Jira ticket HPCC-19755 claims to be already resolved. Is this an additional fix to that issue, or is it referring to the wrong ticket?

2018-07-30 12:34 UTC, wangkx commented
This PR is for HPCC-19755. From my email history, I can see that you closed the HPCC-19755 on last Thursday. I did not see an email for merging this PR.

2018-07-30 16:09 UTC, richardkchapman commented
Looks like I added a comment to this PR rather than closing it, presumable accidentally.

2018-07-30 16:09 UTC, merged