DESDL UI to conform to ESP 2.0
hpcc-systems/HPCC-Platform pull request #11239
Opened 2018-05-25 16:37 UTC by miguelvazq

Make DESDL U/I compatible with _ver1.4 and greater

Signed-off-by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-05-25 17:06 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 04ff6d2bf61139988bb42c6468d5d5c9c839f232
Build: success
ECL Watch:  Rebuilding Site
Lint error(s): 
eclwatch/DynamicESDLDefinitionQueryWidget.js: line 180, col 52, Confusing plusses.
eclwatch/DynamicESDLDefinitionQueryWidget.js: line 99, col 40, TargetSelectWidget is not defined.
eclwatch/DynamicESDLDetailsWidget.js: line 176, col 29, domAttr is not defined.
3 errors
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! eclwatch@1.0.0 lint: `jshint --config ./.jshintrc ./eclwatch`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the eclwatch@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /mnt/disk1/home/vamosax/.npm/_logs/2018-05-25T16_38_45_006Z-debug.log
npm ERR! Test failed.  See above for more details.

Lint warning(s): 
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
Creating group hpcc ...\x1b[32m [   OK    ]  \x1b[0m 
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |786 |786 |0 |
|test (thor) |717 |717 |0 |
|test (roxie) |830 |830 |0 |


HPCC Stop: OK
HPCC Uninstall: OK


 ... ( comment is too long, 62 lines, 2272 bytes, truncated) ... 
[Build error:](https://gist.github.com/cf4b97d854b5695411d4f82c378a5410)
Build log [Build log](https://gist.github.com/HPCCSmoketest/cf4b97d854b5695411d4f82c378a5410#file-result-18-05-25-12-37-54-log)

Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   21 sec (00:00:21) |  173 sec (00:02:53) |  128 sec (00:02:08) |    9 sec (00:00:09) |   30 sec (00:00:30) | 1353 sec (00:22:33) |   18 sec (00:00:18) | 1732 sec (00:28:52) |

```

2018-05-29 10:22 UTC, GordonSmith requested changes

2018-05-29 10:22 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDefinitionQueryWidget.js
> +            this.dialog.show();
Is this show needed here (also called at the bottom)?

2018-05-29 10:22 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDefinitionQueryWidget.js
> +                EspProcName: "myesp", //"myesp"
Remove commented code

2018-05-29 10:22 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDefinitionQueryWidget.js
> +                Config: "<Methods><Method name=" + +"/></Methods>"
Is there meant to be a "name" inside the `+ +`?

2018-05-29 10:22 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLQueryWidget.js
> +                    // LastEditBy: {label: this.i18n.LastEditedBy, width: 90}
Remove commented code.

2018-05-29 10:22 UTC, GordonSmith commented on esp/src/eclwatch/templates/DynamicESDLDetailsWidget.html
> +                            <img src="${dojoConfig.urlInfo.resourcePath}/img/clippy.png" alt="Copy to clipboard">
The alt should probably be in i18n?

2018-05-29 11:15 UTC, GordonSmith commented
@miguelvazq also see the lint errors above.

2018-05-29 15:46 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 0c90b6a7ebcbc6bcdaef3eb3c9af213da63c3721
Build: success
ECL Watch:  Rebuilding Site
Rebuild: success
Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |786 |786 |0 |
|test (thor) |717 |717 |0 |
|test (roxie) |830 |830 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   27 sec (00:00:27) |  170 sec (00:02:50) |  129 sec (00:02:09) |   10 sec (00:00:10) |   31 sec (00:00:31) | 1187 sec (00:19:47) |   19 sec (00:00:19) | 1573 sec (00:26:13) |

2018-05-30 14:24 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.2.1511 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 984dcf168546739ac06d46d112410851ff6f6cbc
Build: success
ECL Watch:  Rebuilding Site
Rebuild: success
Install hpccsystems-platform-community_7.0.0-beta1rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |88 |88 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |786 |786 |0 |
|test (thor) |717 |717 |0 |
|test (roxie) |830 |830 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   20 sec (00:00:20) |  174 sec (00:02:54) |  126 sec (00:02:06) |   10 sec (00:00:10) |   31 sec (00:00:31) | 1181 sec (00:19:41) |   19 sec (00:00:19) | 1561 sec (00:26:01) |

2018-05-30 14:27 UTC, GordonSmith approved these changes
Looks fine.

2018-05-30 16:08 UTC, richardkchapman commented
Looks to me like some of the autoformat changes may have been lost?

@GordonSmith

2018-05-30 20:20 UTC, GordonSmith commented
@richardkchapman Yes, but its not a big deal, we are all going to be turning on out "Format on save" option and are using matching IDEs going forward (and GitHub has made the ?w=1 option available from a button now,.

2018-05-31 09:37 UTC, richardkchapman commented
@GordonSmith Meaning some future PR is also going to look confusing, as well as this one. Is it hard to get this one right?

2018-05-31 09:41 UTC, GordonSmith commented
If we can get it right for the beta then yes lets do that.

2018-05-31 13:57 UTC, richardkchapman commented
Looks like it's a choice between missing the beta and fixing this issue - so I will merge as-is.

2018-05-31 13:58 UTC, merged