HPCC-19145 Fix some JSON output issues.
hpcc-systems/HPCC-Platform pull request #11363
Opened 2018-06-28 17:45 UTC by jakesmith

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-06-28 17:46 UTC, jakesmith commented
NB: Not ready for merging yet.

2018-06-28 17:47 UTC, jakesmith commented
@afishbeck - please review what's here + look at the JSON IXmlWriterExt issue:
```
// JCSMORE - json string coming back from IXmlWriterExt is always rootless the moment, so workaround it by supplying ptr_noRoot to reader
// writer should be fixed.
```
which is causing the "Response" to not be in a object { }

2018-06-28 18:14 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 75bfb9b53b06ceb13cd797257842b367feae0a09
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |789 |789 |0 |
|test (thor) |720 |719 |1 |
|test (roxie) |860 |860 |0 |


[Errors:](https://gist.github.com/1b0f6fe354fa68ac599769cae8b76932)
- test
  - thor
    - 717\. [xmlread (multiPart=true)](https://gist.github.com/HPCCSmoketest/1b0f6fe354fa68ac599769cae8b76932#file-xmlread-multipart-true-w20180628-140856-8-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   21 sec (00:00:21) |  171 sec (00:02:51) |   61 sec (00:01:01) |    9 sec (00:00:09) |   30 sec (00:00:30) | 1290 sec (00:21:30) |   20 sec (00:00:20) | 1602 sec (00:26:42) |

2018-06-28 23:11 UTC, jakesmith commented
@afishbeck - https://track.hpccsystems.com/browse/HPCC-18831 will address the rootless issue.
I've linked this issue and made a comment there about a dependent change that will need to be made when that change is made.

The above smoketest failure is unrelated - looks like it's related to an upmerged change from this issue: https://track.hpccsystems.com/browse/HPCC-19874

2018-06-28 23:19 UTC, jakesmith commented
Removed namescope from "Row".

@afishbeck - please review

2018-06-29 09:22 UTC, AttilaVamos commented
Master is fixed (related to xmlread error) and this PR is rescheduled.

2018-06-29 10:47 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: ab8aca6f7476095c9d0da8a2343bbde115a28393
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |789 |789 |0 |
|test (thor) |720 |720 |0 |
|test (roxie) |860 |860 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   14 sec (00:00:14) |  171 sec (00:02:51) |   61 sec (00:01:01) |    8 sec (00:00:08) |   29 sec (00:00:29) | 1312 sec (00:21:52) |   19 sec (00:00:19) | 1614 sec (00:26:54) |

2018-07-18 14:12 UTC, afishbeck approved these changes
@jakesmith looks good.

2018-07-18 14:47 UTC, jakesmith commented
@afishbeck - there was a merge conflict that needed solving, now resolved. Please double check.

2018-07-18 16:08 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 296a3948db36047de72b3680fd74a5bb2d894b36
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |88 |1 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Unittest error(s):
DigiSignUnitTest run segfault



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |790 |790 |0 |
|test (thor) |721 |721 |0 |
|test (roxie) |861 |861 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   24 sec (00:00:24) |  172 sec (00:02:52) |   61 sec (00:01:01) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1290 sec (00:21:30) |   19 sec (00:00:19) | 1601 sec (00:26:41) |

2018-07-18 16:50 UTC, AttilaVamos commented
I don't think that faulted  DigiSignUnitTest is related to this PR. Re-schedule and let us see.

2018-07-18 16:50 UTC, jakesmith commented
@AttilaVamos - the 'DigiSignUnitTest' is unrelated to this PR - but should be looked at.
Can you get some details of where it crashed ( a stack ) , so that @RussWhitehead can look at?

2018-07-18 16:51 UTC, jakesmith commented
@AttilaVamos - well re-scheduled run might not crash - but that doesn't mean there's not a temperamental issue that should be investigated. Is there a core/logs with stack for the segfauilt ?

2018-07-18 16:58 UTC, afishbeck requested changes

2018-07-18 16:58 UTC, afishbeck commented on common/remote/sockfile.cpp
> +                responseWriter->outputBeginArray("dfs:Row");
@jakesmith technically "dfs:Row" is not correct.  The contents of Row are defined by the ECL Record specific schema, not by the schema identified by the unique id "urn:hpcc:dfs".  I would only add the dfs namepace to the EOG boolean.

2018-07-18 17:07 UTC, AttilaVamos commented
@jakesmith no core file and no more logs, yet.

2018-07-18 17:56 UTC, jakesmith commented
@afishbeck - it looks like my merge conflict was to an old version of my branch and lost the "dfs:Row" changes in the process.

Have now pushed a commit to fix and have re-tested.
Please check and I'll squash the new commit.

2018-07-18 20:20 UTC, afishbeck approved these changes
@jakesmith looks good

2018-07-19 01:37 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 5b7865fb83922a244f2396e141d3b034a9e747d3
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |790 |790 |0 |
|test (thor) |721 |721 |0 |
|test (roxie) |861 |861 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   23 sec (00:00:23) |  172 sec (00:02:52) |   62 sec (00:01:02) |    8 sec (00:00:08) |   29 sec (00:00:29) | 1278 sec (00:21:18) |   19 sec (00:00:19) | 1591 sec (00:26:31) |

2018-07-19 08:44 UTC, merged