HPCC-19670 DOCS:Remove Graph Control
hpcc-systems/HPCC-Platform pull request #11360
Opened 2018-06-28 12:57 UTC by g-pan

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

@JamesDeFabia please review
(for TheECLWatchMan.xml only need review new lines 425-426)
@miguelvazq  FYI; optionally review

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Successful UNIT Testing results: http://10.240.32.243/view/Docs%207.0/job/DocDevII/

2018-06-28 13:40 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: a47896487ea3f4cdeada78651065b056ae7a78fb
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |789 |789 |0 |
|test (thor) |720 |719 |1 |
|test (roxie) |860 |860 |0 |


[Errors:](https://gist.github.com/1d349faec3199038da5455c9bcf504aa)
- test
  - thor
    - 717\. [xmlread (multiPart=true)](https://gist.github.com/HPCCSmoketest/1d349faec3199038da5455c9bcf504aa#file-xmlread-multipart-true-w20180628-093452-5-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   14 sec (00:00:14) |  347 sec (00:05:47) |  113 sec (00:01:53) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1287 sec (00:21:27) |   18 sec (00:00:18) | 1814 sec (00:30:14) |

2018-06-28 15:05 UTC, JamesDeFabia requested changes
Comments inline

2018-06-28 15:05 UTC, JamesDeFabia commented on docs/EN_US/HPCCClientTools/CT_Mods/CT_ECL_IDE.xml
> +                  <entry>The graph viewer control is built in to the ECL IDE.
This option is no longer in the IDE's Preferences > Other  tab. You should remove the entire row

2018-06-28 16:16 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 62f7ccf48cf28b1635d24309f837d8cb73efc2de
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |789 |789 |0 |
|test (thor) |720 |719 |1 |
|test (roxie) |860 |860 |0 |


[Errors:](https://gist.github.com/27fe852999f7ec79df5b8b4b3be4a72c)
- test
  - thor
    - 717\. [xmlread (multiPart=true)](https://gist.github.com/HPCCSmoketest/27fe852999f7ec79df5b8b4b3be4a72c#file-xmlread-multipart-true-w20180628-120752-2-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   35 sec (00:00:35) |  355 sec (00:05:55) |  109 sec (00:01:49) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1475 sec (00:24:35) |   19 sec (00:00:19) | 2028 sec (00:33:48) |

2018-06-29 09:22 UTC, AttilaVamos commented
Master is fixed (related to xmlread error) and this PR is rescheduled.

2018-06-29 09:52 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 62f7ccf48cf28b1635d24309f837d8cb73efc2de
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |789 |789 |0 |
|test (thor) |720 |719 |1 |
|test (roxie) |860 |860 |0 |


[Errors:](https://gist.github.com/84f3fded1cc44041b44b26a57c22ef9e)
- test
  - thor
    - 717\. [xmlread (multiPart=true)](https://gist.github.com/HPCCSmoketest/84f3fded1cc44041b44b26a57c22ef9e#file-xmlread-multipart-true-w20180629-054644-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   21 sec (00:00:21) |  334 sec (00:05:34) |  113 sec (00:01:53) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1305 sec (00:21:45) |   19 sec (00:00:19) | 1827 sec (00:30:27) |

2018-06-29 10:02 UTC, AttilaVamos commented
Now it is upmerged and this PR rescheduled again.

2018-06-29 13:06 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 62f7ccf48cf28b1635d24309f837d8cb73efc2de
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |789 |789 |0 |
|test (thor) |720 |720 |0 |
|test (roxie) |860 |860 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   33 sec (00:00:33) |  349 sec (00:05:49) |  111 sec (00:01:51) |    9 sec (00:00:09) |   30 sec (00:00:30) | 1281 sec (00:21:21) |   18 sec (00:00:18) | 1831 sec (00:30:31) |

2018-07-02 09:06 UTC, jakesmith commented
tagging back to original reviewers : @JamesDeFabia @miguelvazq

2018-07-02 14:44 UTC, JamesDeFabia approved these changes
Looks good now

2018-07-02 15:09 UTC, richardkchapman commented
@GordonSmith Please review

2018-07-03 11:00 UTC, GordonSmith approved these changes
Looks ok - but appears to have a bunch of unrelated changes?

2018-07-03 11:09 UTC, merged