HPCC-19306 Support OpenSSL 1.1 and Ubuntu 18.04
hpcc-systems/HPCC-Platform pull request #11432
Opened 2018-07-18 11:58 UTC by richardkchapman

Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:
Compiled

2018-07-18 11:59 UTC, richardkchapman commented
@RussWhitehead Please review

2018-07-18 11:59 UTC, richardkchapman commented on system/security/securesocket/securesocket.cpp
> +#define OPENSSL_USE_DEPRECATED 1
Actually this didn't seem to help so I should probably remove it

2018-07-18 12:00 UTC, richardkchapman commented on system/security/securesocket/securesocket.cpp
> +        RSA_free(rsa);
I think we were probably leaking this before?

2018-07-18 13:16 UTC, RussWhitehead requested changes

2018-07-18 13:16 UTC, RussWhitehead commented on system/security/securesocket/securesocket.cpp
> +        RSA *rsa = RSA_generate_key(m_bits, RSA_F4, NULL, NULL);
Should throw if NULL returned here and RSA_new() on 1241

2018-07-18 14:08 UTC, RussWhitehead approved these changes
Looks good to go

2018-07-18 15:13 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d207d8de5bc76d34046f36d729cab8c94b365d52
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |790 |790 |0 |
|test (thor) |721 |721 |0 |
|test (roxie) |861 |861 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   32 sec (00:00:32) |  173 sec (00:02:53) |   61 sec (00:01:01) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1271 sec (00:21:11) |   19 sec (00:00:19) | 1591 sec (00:26:31) |

2018-07-19 08:48 UTC, richardkchapman commented
@ghalliday Please merge

2018-07-19 10:35 UTC, ghalliday commented on system/security/securesocket/securesocket.cpp
> +        CRYPTO_mem_leaks(bio_err);
whitespace: indentation off

2018-07-19 10:49 UTC, ghalliday commented
@richardkchapman please squash first.  One minor whitespace comment.

2018-07-19 10:54 UTC, richardkchapman commented
@ghalliday Back to you

2018-07-19 11:06 UTC, merged