HPCC-20089 Rationalize and consolidate the developer documentation
hpcc-systems/HPCC-Platform pull request #11431
Opened 2018-07-18 10:34 UTC by ghalliday

Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-07-18 10:36 UTC, ghalliday commented
@richardkchapman @JamesDeFabia please review.

Note, this is complete - many of these document could do with revising - e.g. I have added a list of some of the items to the style guide.  However I think that should be done as a separate PR.  This at least puts most of the documentation in once place and makes it easier to find.

2018-07-18 11:53 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 88e1bd2280e44861f4fa56e379164275c72620d1
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |790 |790 |0 |
|test (thor) |721 |721 |0 |
|test (roxie) |861 |861 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   13 sec (00:00:13) |  353 sec (00:05:53) |  115 sec (00:01:55) |    9 sec (00:00:09) |   30 sec (00:00:30) | 1287 sec (00:21:27) |   20 sec (00:00:20) | 1827 sec (00:30:27) |

2018-07-26 13:24 UTC, JamesDeFabia requested changes
Minor comments inline, but overall, this is a great reorganization.

2018-08-02 12:46 UTC, ghalliday commented on devdoc/Development.rst
> +The HPCC platform requires a number of third party tools and libraries in order to build.  The `HPCC Wiki`_ contains the
It is a link - see the last line of the file.

2018-08-02 12:46 UTC, ghalliday commented on devdoc/Development.rst
> +**MORE** Completely out of date - needs rewriting.
yes, something to look at later.

2018-08-02 12:46 UTC, ghalliday commented
@JamesDeFabia you need to mention someone when you have finished.
@richardkchapman please review/merge

2018-08-02 12:55 UTC, richardkchapman commented on devdoc/Development.rst
> +The most upto date details of building the system are found on the HPCC Wiki at
up-to-date

2018-08-02 12:56 UTC, richardkchapman commented on devdoc/Development.rst
> +flavors of Linux, FreeBSD, and other platforms. You should install cmake version 2.8.3 or later before building the
I think we need later than 2.8.3 these days

2018-08-02 12:59 UTC, richardkchapman commented
@ghalliday A couple of trivial comments but I'll happily merge anyway

2018-08-02 13:38 UTC, JamesDeFabia commented
@ghalliday I agree with @richardkchapman . This should be merged and we (you) can address the trivial changes later

2018-08-03 08:13 UTC, merged