HPCC-20017 Unable to review packagemap info
hpcc-systems/HPCC-Platform pull request #11513
Opened 2018-07-31 14:56 UTC by miguelvazq

Grid rendering was not occuring due to a grid.store.query is not found. This is a legacy widget that still needs some updating. The grid now populates with packages and the user can continue onto review packagemap info.

Signed-off-by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-07-31 14:57 UTC, miguelvazq commented
@GordonSmith Please review.

2018-07-31 16:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: abf81303937557e4b70227c5c4cec9cab5c9aee5
Build: success
ECL Watch:  Rebuilding Site
Rebuild: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |804 |804 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   42 sec (00:00:42) |  173 sec (00:02:53) |  118 sec (00:01:58) |    8 sec (00:00:08) |   29 sec (00:00:29) | 1291 sec (00:21:31) |   19 sec (00:00:19) | 1680 sec (00:28:00) |

2018-08-02 08:00 UTC, GordonSmith requested changes

2018-08-06 11:09 UTC, richardkchapman commented
@miguelvazq

2018-08-06 20:29 UTC, miguelvazq commented
@GordonSmith updated.

2018-08-06 21:50 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 76452ed51e7623c2e68d951e68875b79bca1a062
Build: success
ECL Watch:  Rebuilding Site
Rebuild: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |804 |804 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |877 |1 |


[Errors:](https://gist.github.com/aa271ba320fd431e002a14921f81e080)
- test
  - roxie
    - 592\. [schedule2](https://gist.github.com/HPCCSmoketest/aa271ba320fd431e002a14921f81e080#file-schedule2-w20180806-172155-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  174 sec (00:02:54) |  127 sec (00:02:07) |    7 sec (00:00:07) |   28 sec (00:00:28) | 2975 sec (00:49:35) |   16 sec (00:00:16) | 3343 sec (00:55:43) |

2018-08-07 13:06 UTC, GordonSmith requested changes

2018-08-07 13:06 UTC, GordonSmith commented on esp/src/src/ESPPackageProcess.ts
> +    // countProperty: "PageSize",
Remove commented code

2018-08-07 13:06 UTC, GordonSmith commented on esp/src/src/ESPPackageProcess.ts
> +    return new Observable(store);
I don't think it matters, but I think its meant to be:  `return Observable(store);`

2018-08-07 18:35 UTC, miguelvazq commented
@GordonSmith updated.

2018-08-07 19:24 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d39b62e4cd34b30f937c3262d7673950dbcd9b1b
Build: success
ECL Watch:  Rebuilding Site
Rebuild: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |804 |804 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   29 sec (00:00:29) |  174 sec (00:02:54) |  107 sec (00:01:47) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1300 sec (00:21:40) |   20 sec (00:00:20) | 1665 sec (00:27:45) |

2018-08-09 05:09 UTC, GordonSmith requested changes
One minor comment - otherwise looks good

2018-08-09 05:09 UTC, GordonSmith commented on esp/src/eclwatch/TargetSelectClass.js
> +                            if (targetData[i].Processes.Item) {
Should this be `lang.exists("Processes.Item.length", targetData[i])`?

2018-08-09 11:06 UTC, ghalliday commented
@miguelvazq

2018-08-09 14:17 UTC, miguelvazq commented
@GordonSmith updated and tested.

2018-08-09 15:04 UTC, GordonSmith approved these changes
Looks good.

2018-08-09 15:04 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 12e51b2aafec39dfd96deeb80e3b88c2e05b17dd
Build: success
ECL Watch:  Rebuilding Site
Lint error(s): 
npm ERR! Test failed.  See above for more details.

Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
Creating group hpcc ...\x1b[32m [   OK    ]  \x1b[0m 
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |805 |805 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

[Build error:](https://gist.github.com/7ca647dac7d9f150af1575990d8b6e29)
Build log [Build log](https://gist.github.com/HPCCSmoketest/7ca647dac7d9f150af1575990d8b6e29#file-result-18-08-09-10-38-19-log)

Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   31 sec (00:00:31) |  174 sec (00:02:54) |  132 sec (00:02:12) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1276 sec (00:21:16) |   18 sec (00:00:18) | 1666 sec (00:27:46) |

2018-08-09 15:29 UTC, miguelvazq commented
@ghalliday ready for merge.

2018-08-09 16:17 UTC, merged