HPCC-20150 Document ESP support for Dynamic ESDL Proxy mode
hpcc-systems/HPCC-Platform pull request #11540
Opened 2018-08-03 19:29 UTC by JamesDeFabia

Signed-off-by: Jim DeFabia <jamesdefabia@lexisnexis.com>
@afishbeck Please review (Sent Pdf also)

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-08-03 20:10 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: e9e8651621ccb69589e8f37aea687d413a21c61c
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |804 |804 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   14 sec (00:00:14) |  348 sec (00:05:48) |  114 sec (00:01:54) |    9 sec (00:00:09) |   30 sec (00:00:30) | 1311 sec (00:21:51) |   18 sec (00:00:18) | 1844 sec (00:30:44) |

2018-08-05 20:04 UTC, afishbeck commented on docs/EN_US/HPCCClientTools/CT_Mods/CT_ESDL_CLI.xml
> +          <para>You can specify a proxy for ESDL service methods on another
Perhaps something like "You can specify that ESDL service methods be proxied to another ESP instance"?

2018-08-05 20:05 UTC, afishbeck commented on docs/EN_US/HPCCClientTools/CT_Mods/CT_ESDL_CLI.xml
> +  &lt;Proxy method="myMethod3" address="http://10.45.22.1:292" /&gt;
"address" attribute was correct, but is changing to "forwardTo".

2018-08-05 20:05 UTC, afishbeck commented on docs/EN_US/HPCCClientTools/CT_Mods/CT_ESDL_CLI.xml
> +  &lt;Proxy method="myWild*" address="http://10.45.22.1:292" /&gt;
"address" attribute was correct, but is changing to "forwardTo".

2018-08-05 20:05 UTC, afishbeck commented on docs/EN_US/HPCCClientTools/CT_Mods/CT_ESDL_CLI.xml
> +          <para><programlisting>&lt;Proxy method="myWild*" address="http://10.45.22.1:292" /&gt; </programlisting>This
"address" attribute was correct, but is changing to "forwardTo".

2018-08-05 20:07 UTC, afishbeck requested changes
@JamesDeFabia minor changes requested, otherwise looks good.

2018-08-24 16:44 UTC, JamesDeFabia commented
@afishbeck Edits made, back to you

2018-08-24 18:48 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 0a1e743e57852809738fd572759d46bceb6ee56e
Build: success
Install hpccsystems-platform-community_7.0.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |805 |805 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   25 sec (00:00:25) |  344 sec (00:05:44) |  143 sec (00:02:23) |   19 sec (00:00:19) |   42 sec (00:00:42) | 1380 sec (00:23:00) |   19 sec (00:00:19) | 1972 sec (00:32:52) |

2018-08-28 21:40 UTC, afishbeck commented on docs/EN_US/HPCCClientTools/CT_Mods/CT_ESDL_CLI.xml
> +  &lt;Proxy method="myMethod3" address="http://10.45.22.1:292" /&gt;
@JamesDeFabia Looks like address has been changed to forwardTo below, but the one example above hasn't been changed.

2018-08-28 22:54 UTC, afishbeck requested changes
@JamesDeFabia just the one usage of "address" otherwise looks good.

2018-08-29 12:59 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 8ba3c60e2962e85853636cff124670fb5002a5f1
Build: success
Install hpccsystems-platform-community_7.0.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |805 |805 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   21 sec (00:00:21) |  329 sec (00:05:29) |  143 sec (00:02:23) |   21 sec (00:00:21) |   43 sec (00:00:43) | 1337 sec (00:22:17) |   20 sec (00:00:20) | 1914 sec (00:31:54) |

2018-08-31 15:44 UTC, afishbeck approved these changes
@JamesDeFabia looks good.

2018-09-05 14:39 UTC, afishbeck commented
@JamesDeFabia just tagging you.  not sure why this still shows up on my list.

2018-09-05 14:40 UTC, JamesDeFabia commented
@richardkchapman this should be good to merge

2018-09-05 14:45 UTC, merged