HPCC-20269 Initial ESP XSD review
hpcc-systems/HPCC-Platform pull request #11554
Opened 2018-08-08 14:24 UTC by kenrowland

Add initial ESP XSD including necessary supporting changes

Signed-off-by: Ken Rowland <kenneth.rowland@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-08-08 14:25 UTC, kenrowland commented
@rpastrana @RussWhitehead @JamesDeFabia @wangkx 

Please review. See accompanying email for more information

2018-08-08 14:53 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 5a7e26e79711a21190f82eeecf7e2371749b4a81
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |804 |804 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   23 sec (00:00:23) |  173 sec (00:02:53) |   62 sec (00:01:02) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1312 sec (00:21:52) |   20 sec (00:00:20) | 1625 sec (00:27:05) |

2018-08-08 17:20 UTC, kenrowland commented
@afishbeck Please review as well. You are probably most interested in the esp.xsd.

2018-08-08 18:47 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: ee389474ebbedcf01beec0594bb536b6cae99f1f
Build: success
Install hpccsystems-platform-community_7.0.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |804 |804 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   13 sec (00:00:13) |  172 sec (00:02:52) |   61 sec (00:01:01) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1451 sec (00:24:11) |   20 sec (00:00:20) | 1752 sec (00:29:12) |

2018-08-14 14:49 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 82696df962f36a6ce34850596a4f7bb660b28fc0
Build: success
Install hpccsystems-platform-community_7.0.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |805 |805 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   21 sec (00:00:21) |  174 sec (00:02:54) |   62 sec (00:01:02) |    9 sec (00:00:09) |   29 sec (00:00:29) | 1477 sec (00:24:37) |   17 sec (00:00:17) | 1789 sec (00:29:49) |

2018-08-23 12:49 UTC, kenrowland commented
@rpastrana Updating last person.
Per our discussion, this review is only for the conversion of the XSD. Another JIRA will be opened for Keven and/or Tony to review its correctness.

2018-09-04 16:33 UTC, rpastrana commented
@kenrowland please rebase so I can review

2018-09-04 18:24 UTC, rpastrana reviewed
@kenrowland a few comments

2018-09-05 15:05 UTC, kenrowland reviewed
@rpastrana Please see replies.

2018-09-05 15:05 UTC, kenrowland commented on configuration/config2/ConfigPath.cpp
> +    bool rc = found == m_presentInList;
It is, and some future work has changed this method. For now I will leave this as is. Future PR will update this method

2018-09-05 15:05 UTC, kenrowland commented on configuration/config2/ConfigPath.cpp
> +                std::size_t compareLength = (notPos == std::string::npos) ? 1 : 2;
I don't think so, unless we want to do validate all XPaths as being well formed.

2018-09-05 15:05 UTC, kenrowland commented on configuration/config2/XSDSchemaParser.cpp
> +                            pAttr->setCodeDefault(vals[1]);
That change has not been implemented in this PR as it was decided after this PR was made. It is coming in a later PR that will address all current XSDs and the code necessary.

2018-09-05 15:05 UTC, kenrowland commented on initfiles/componentfiles/configschema/xsd/esp.xsd
> +                        <xs:element name="EspBinding" maxOccurs="unbounded" hpcc:itemType="espbinding" hpcc:category="ESP Bindings" hpcc:insertLimitType="attribute" hpcc:insertLimitData="service"
OK, just make sure that a Config Manager 2.0 Jira is opened so it is tracked.

2018-09-05 19:34 UTC, kenrowland commented
@rpastrana Rebased. Once merged, the next PR can also be rebased into a single commit also.

2018-09-05 20:16 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: f17301bb57522dddbd06ae5a2d52d361b5b14402
Build: success
Install hpccsystems-platform-community_7.0.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |805 |805 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  173 sec (00:02:53) |   93 sec (00:01:33) |   19 sec (00:00:19) |   41 sec (00:00:41) | 1352 sec (00:22:32) |   19 sec (00:00:19) | 1705 sec (00:28:25) |

2018-09-06 02:00 UTC, rpastrana commented on configuration/config2/ConfigPath.cpp
> +    bool rc = found == m_presentInList;
go ahead and clean it up now.

2018-09-06 02:14 UTC, rpastrana requested changes
@kenrowland

2018-09-06 02:14 UTC, rpastrana commented on configuration/config2/ConfigPath.cpp
> +                std::size_t compareLength = (notPos == std::string::npos) ? 1 : 2;
is it possible attr can contain '=!' or even '!xyz='? If so, make sure you're not making any assumptions about notpos and equalpos

2018-09-06 02:14 UTC, rpastrana commented on initfiles/componentfiles/configschema/xsd/esp.xsd
> +                        <xs:element name="EspBinding" maxOccurs="unbounded" hpcc:itemType="espbinding" hpcc:category="ESP Bindings" hpcc:insertLimitType="attribute" hpcc:insertLimitData="service"
you have to make sure the version of config2.0 XSDs reflect the content of the configmgr XSDs at the time your release config 2.0

2018-09-06 16:30 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d6e0237d00dc90c0dbfa6fedf3a6ce9334d45875
Build: success
Install hpccsystems-platform-community_7.0.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |805 |805 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   23 sec (00:00:23) |  174 sec (00:02:54) |   93 sec (00:01:33) |   21 sec (00:00:21) |   43 sec (00:00:43) | 1311 sec (00:21:51) |   20 sec (00:00:20) | 1685 sec (00:28:05) |

2018-09-06 18:17 UTC, kenrowland commented
@rpastrana changed return code and processing of attribute values list. Please review. All other open comments are noted.

2018-09-12 21:04 UTC, rpastrana approved these changes
@kenrowland

2018-09-13 15:02 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 94c737f3ce69a671ef909b87b54f4455893e8dc4
Build: success
Install hpccsystems-platform-community_7.0.0-rc2.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   20 sec (00:00:20) |  185 sec (00:03:05) |   95 sec (00:01:35) |   19 sec (00:00:19) |   42 sec (00:00:42) | 1507 sec (00:25:07) |   19 sec (00:00:19) | 1887 sec (00:31:27) |

2018-09-13 15:05 UTC, kenrowland commented
@richardkchapman please merge

2018-09-14 07:43 UTC, merged