HPCC-20241 Retrieve User Details from LDAP server
hpcc-systems/HPCC-Platform pull request #11577
Opened 2018-08-16 20:10 UTC by wangkx

In session based ESP, the ISecUser may not contains the User
Details because ESP does not authenticate every request and
the User Details are not filled in. WsAccount should retrieve
User Details directly from LDAP server.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-08-16 20:11 UTC, wangkx commented
@RussWhitehead please review.

2018-08-16 20:18 UTC, RussWhitehead requested changes

2018-08-16 20:18 UTC, RussWhitehead commented on system/security/LdapSecurity/ldapconnection.cpp
> +                        }
your search filter specifies distinguishedName, but you are not extracting it

2018-08-16 20:21 UTC, RussWhitehead approved these changes

2018-08-16 20:39 UTC, wangkx commented
@richardkchapman this PR is ready to be merged.

2018-08-16 21:28 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d74ed0ef388fefe58d53b547ce9f029a79e9a4b7
Build: success
Install hpccsystems-platform-community_7.0.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |89 |89 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |805 |805 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   21 sec (00:00:21) |  175 sec (00:02:55) |   61 sec (00:01:01) |    7 sec (00:00:07) |   28 sec (00:00:28) | 1282 sec (00:21:22) |   19 sec (00:00:19) | 1593 sec (00:26:33) |

2018-08-24 06:54 UTC, richardkchapman commented
When is this code called? Any performance concerns? @afishbeck can you sanity-check?

2018-08-28 22:53 UTC, afishbeck commented
The changes look ok. But I have a question for @RussWhitehead 

So getUserInfo now always seems to retrieve an extra 3 fields from LDAP.

The particular usage for this JIRA is only to display user info on demand, but

@RussWhitehead per Richards question, how often / where is getUserInfo and retrieveUserInfo (in IPermissionsProcessor) called?  And how much overhead does a few extra fields being retrieved add?

2018-09-05 14:32 UTC, RussWhitehead commented
@afishbeck These is called whenever a user logs in, and when they view/change their user info, and when exporting user account information. Since we did not introduce any additional calls to LDAP, there should be no performance issues. 
@richardkchapman Looks good for merge

2018-09-05 14:46 UTC, merged