HPCC-20405 Report authorization failures to TxSummary in ws_sql
hpcc-systems/HPCC-Platform pull request #11639
Opened 2018-09-03 00:37 UTC by wangkx

Inside ESP WsSQL service code, call ensureFeatureAccess() to
report authorization failures to TxSummary.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-09-03 01:09 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 0141799141626948072a490daed2634450639244
Build: success
Install hpccsystems-platform-community_7.0.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |805 |805 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   20 sec (00:00:20) |  180 sec (00:03:00) |   93 sec (00:01:33) |   21 sec (00:00:21) |   44 sec (00:00:44) | 1337 sec (00:22:17) |   19 sec (00:00:19) | 1714 sec (00:28:34) |

2018-09-03 01:10 UTC, wangkx commented
@rpastrana please review.

2018-09-05 13:08 UTC, rpastrana requested changes
@wangkx looks good. Some of the original messages were invalid.

2018-09-05 13:08 UTC, rpastrana commented on esp/services/ws_sql/ws_sqlService.cpp
> +    context.ensureFeatureAccess(WSSQLACCESS, SecAccess_Write, -1, "WsSQL::SetRelatedIndexes failed to execute SQL. Permission denied.");
original error message was wrong. should be "WsSQL::SetRelatedIndexes: Permission denied."

2018-09-05 13:08 UTC, rpastrana commented on esp/services/ws_sql/ws_sqlService.cpp
> +        context.ensureFeatureAccess(WSSQLACCESS, SecAccess_Read, -1, "Failed to execute SQL. Permission denied.");
original error message was wrong. should be "WsSQL::onGetRelatedIndexes: Permission denied."

2018-09-05 13:08 UTC, rpastrana commented on esp/services/ws_sql/ws_sqlService.cpp
> +       context.ensureFeatureAccess(WSSQLACCESS, SecAccess_Write, -1, "Failed to execute SQL. Permission denied.");
original error message was wrong. should be "Failed to execute Prepared SQL. Permission denied."

2018-09-05 13:08 UTC, rpastrana commented on esp/services/ws_sql/ws_sqlService.cpp
> +    context.ensureFeatureAccess(WSSQLACCESS, SecAccess_Write, -1, "Failed to fetch results (open workunit). Permission denied.");
original error message was wrong. should be "CwssqlEx::onCreateTableAndLoad: Permission denied."

2018-09-05 14:05 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 2f8a884052afbf89c802250305dd32d81a01e545
Build: success
Install hpccsystems-platform-community_7.0.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |805 |805 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   10 sec (00:00:10) |  173 sec (00:02:53) |   94 sec (00:01:34) |   19 sec (00:00:19) |   41 sec (00:00:41) | 1323 sec (00:22:03) |   19 sec (00:00:19) | 1679 sec (00:27:59) |

2018-09-05 14:41 UTC, wangkx commented
@rpastrana please review my last commit.

2018-09-05 15:10 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d2d7329d5023ae44fca958c34551f0c9fc1719f2
Build: success
Install hpccsystems-platform-community_7.0.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |805 |805 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  174 sec (00:02:54) |   94 sec (00:01:34) |   20 sec (00:00:20) |   42 sec (00:00:42) | 1357 sec (00:22:37) |   18 sec (00:00:18) | 1722 sec (00:28:42) |

2018-09-05 15:31 UTC, rpastrana approved these changes
@wangkx looks good!

2018-09-05 16:05 UTC, merged

2018-09-05 16:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 403d1a7f54f1603d240f131bd7e39f601ad3cd9a
Build: success
Install hpccsystems-platform-community_7.0.0-rc1.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |805 |805 |0 |
|test (thor) |729 |729 |0 |
|test (roxie) |878 |878 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   30 sec (00:00:30) |  174 sec (00:02:54) |   94 sec (00:01:34) |   21 sec (00:00:21) |   43 sec (00:00:43) | 1327 sec (00:22:07) |   20 sec (00:00:20) | 1709 sec (00:28:29) |