IDE-715 Add Programmer's Guide Example Code to IDE examples
hpcc-systems/HPCC-Platform pull request #11672
Opened 2018-09-06 19:15 UTC by JamesDeFabia

Signed-off-by: Jim DeFabia <jamesdefabia@lexisnexis.com>
@GordonSmith Please review

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-09-07 08:04 UTC, GordonSmith requested changes

2018-09-07 08:04 UTC, GordonSmith commented on docs/EN_US/ECLProgrammersGuide/PRG_Mods/PrG_Creating_example_data.xml
> +    folder. To use it, you should copy it to your MyFIles folder. </para>
Typo = My**FI**les

2018-09-07 08:04 UTC, GordonSmith commented on docs/EN_US/ECLProgrammersGuide/PRG_Mods/PrG_Creating_example_data.xml
> +        <para>In the ECL IDE, expand the <emphasis
"In the ECL IDE" is duplicated from introduction paragraph

2018-09-07 08:04 UTC, GordonSmith commented on docs/EN_US/ECLProgrammersGuide/PRG_Mods/PrG_Creating_example_data.xml
> +        <para>In the ECL IDE, expand the <emphasis role="bold">My
"In the ECL IDE" is duplicated from introduction paragraph

2018-09-07 09:29 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 62f6941f4c773a0d789fd124bb05922edf6dd7a4
Number of Error(s): 4
cp: cannot stat \xe2\x80\x98/mnt/disk1/home/vamosax/smoketest/PR-11672/HPCC-Platform/docs/EN_US/ECLProgrammersGuide/PRG_Mods/ECL Code Files/*.ecl\xe2\x80\x99: No such file or directory
make[2]: *** [RelWithDebInfo/docs/EN_US/ECL_Code_Files_EN_US.zip] Error 1

[Build error:](https://gist.github.com/b6329503f0d9bdb5c8f938ce7ca74425)
Build log [Build log](https://gist.github.com/HPCCSmoketest/b6329503f0d9bdb5c8f938ce7ca74425#file-result-18-09-07-05-30-30-log)

2018-09-07 10:32 UTC, richardkchapman commented
@JamesDeFabia

2018-09-07 12:55 UTC, JamesDeFabia commented
@GordonSmith edits made,  back to you

2018-09-07 13:28 UTC, GordonSmith approved these changes
Looks good.

2018-09-07 13:46 UTC, richardkchapman commented
@JamesDeFabia Please squash

2018-09-07 14:35 UTC, JamesDeFabia commented
@richardkchapman I have squashed  and pushed

2018-09-07 14:47 UTC, merged

2018-09-07 15:30 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 510dbf361b8dc8b59fabb33138f99e75c241ab15
Number of Error(s): 4
cp: cannot stat \xe2\x80\x98/mnt/disk1/home/vamosax/smoketest/PR-11672/HPCC-Platform/docs/EN_US/ECLProgrammersGuide/PRG_Mods/ECL Code Files/*.ecl\xe2\x80\x99: No such file or directory
make[2]: *** [RelWithDebInfo/docs/EN_US/ECL_Code_Files_EN_US.zip] Error 1

[Build error:](https://gist.github.com/778664d4b5c88f74dd8e9c5e3117d247)
Build log [Build log](https://gist.github.com/HPCCSmoketest/778664d4b5c88f74dd8e9c5e3117d247#file-result-18-09-07-11-31-40-log)

2018-09-10 08:09 UTC, richardkchapman commented
@JamesDeFabia Can you check the smoketest issue please

2018-09-10 12:06 UTC, JamesDeFabia commented
@richardkchapman I think I know the issue. Working on it