HPCC-20249 Updates to ECL IDE Docs
hpcc-systems/HPCC-Platform pull request #11747
Opened 2018-09-24 19:50 UTC by g-pan

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

NOTE: Inclusive of JIRAs   HPCC-20240, HPCC-20243, HPCC-20250, HPCC-20251, HPCC-20258, HPCC-20261, HPCC-20264, and HPCC-20273 
All pertaining to the ECL IDE

@JamesDeFabia please review

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Integration Build: http://10.240.32.243/view/Docs%207.0/job/DocDevII/

2018-09-24 19:59 UTC, HPCCSmoketest commented
1/1. Process of PR-11747, label: H20240-IDEs starts now. Estimated completion time is ~ 0.5 hour(s)

2018-09-24 20:34 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 140bd6664482f65dbb973c07b77daba8bdcf6f61
Build: success
Install hpccsystems-platform-community_7.0.0-rc2.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   11 sec (00:00:11) |  355 sec (00:05:55) |  145 sec (00:02:25) |   19 sec (00:00:19) |   41 sec (00:00:41) | 1490 sec (00:24:50) |   19 sec (00:00:19) | 2080 sec (00:34:40) |

2018-09-25 19:51 UTC, JamesDeFabia requested changes
Few comments inline.

2018-09-25 19:51 UTC, JamesDeFabia commented on docs/EN_US/HPCCClientTools/CT_Mods/CT_ECL_IDE.xml
> +                  <programlisting role="tab"><emphasis role="bold">Open Builder:</emphasis> Opens a saved query(.ECL file) in a new ECL Builder window. CTRL-O
CTRL+O

2018-09-25 19:51 UTC, JamesDeFabia commented on docs/EN_US/HPCCClientTools/CT_Mods/CT_ECL_IDE.xml
>                    window saves the ECL file to the Repository. CTRL-S</entry>
CTRL+S

2018-09-25 19:51 UTC, JamesDeFabia commented on docs/EN_US/HPCCClientTools/CT_Mods/CT_ECL_IDE.xml
> +                  CTRL-F </entry>
CTRL+F

2018-09-25 19:51 UTC, JamesDeFabia commented on docs/EN_US/HPCCClientTools/CT_Mods/CT_ECL_IDE.xml
> +                  <entry>Closes all open the workunits</entry>
remove "the"

2018-09-26 17:48 UTC, g-pan commented
requested changes made, @JamesDeFabia please review

2018-09-26 17:52 UTC, JamesDeFabia approved these changes
Good to merge

2018-09-26 17:59 UTC, HPCCSmoketest commented
1/1. Process of PR-11747, label: H20240-IDEs starts now. Estimated completion time is ~ 0.5 hour(s)

2018-09-26 18:37 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 9de3881864f07fceb2727b6dad2b6b500b4856a6
Build: success
Install hpccsystems-platform-community_7.0.0-rc2.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |94 |94 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   39 sec (00:00:39) |  346 sec (00:05:46) |  143 sec (00:02:23) |   20 sec (00:00:20) |   42 sec (00:00:42) | 1644 sec (00:27:24) |   18 sec (00:00:18) | 2252 sec (00:37:32) |

2018-09-27 08:32 UTC, merged