HPCC-20065 Add sr translations
hpcc-systems/HPCC-Platform pull request #11799
Opened 2018-10-03 01:58 UTC by kunalaswani

Adding sr translations and alphabetizing hpcc.js file

Signed-off-by: Kunal Aswani <kunal.aswani@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-10-03 02:19 UTC, HPCCSmoketest commented
1/1. Process of PR-11799, label: HPCC-20065 starts now. Estimated completion time is ~ 0.5 hour(s)

2018-10-03 03:19 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: a8e652dd739eb6970a1fd071734367e524d9c0bb
Build: success
ECL Watch:  Rebuilding Site
Lint error(s): 
eclwatch/nls/sr/hpcc.js: line 849, col 32, Duplicate key YouAreAboutToRemoveUserFrom.
1 error
> eclwatch@1.0.0 test /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! code ELIFECYCLE
> eclwatch@1.0.0 test /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! errno 2
> eclwatch@1.0.0 test /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! eclwatch@1.0.0 lint: `jshint --config ./.jshintrc ./eclwatch`
> eclwatch@1.0.0 test /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! Exit status 2
> eclwatch@1.0.0 test /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! 
> eclwatch@1.0.0 test /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! Failed at the eclwatch@1.0.0 lint script.
> eclwatch@1.0.0 test /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> eclwatch@1.0.0 test /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! A complete log of this run can be found in:
> eclwatch@1.0.0 test /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR!     /mnt/disk1/home/vamosax/.npm/_logs/2018-10-03T02_23_06_475Z-debug.log
> eclwatch@1.0.0 test /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
ERROR: lint exited with 2.
npm ERR! Test failed.  See above for more details.

Lint warning(s): 
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

Install hpccsystems-platform-community_7.0.0-rc2.el7.x86_64.rpm
Creating group hpcc ...\x1b[32m [   OK    ]  \x1b[0m 
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|w
 ... ( comment is too long, 106 lines, 4665 bytes, truncated) ... 
[Build error:](https://gist.github.com/1d9ae9a458abd90251f54b48b97cf7a3)
Build log [Build log](https://gist.github.com/HPCCSmoketest/1d9ae9a458abd90251f54b48b97cf7a3#file-result-18-10-02-22-22-31-log)

Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   28 sec (00:00:28) |  191 sec (00:03:11) |  174 sec (00:02:54) |   22 sec (00:00:22) |   44 sec (00:00:44) | 3129 sec (00:52:09) |   15 sec (00:00:15) | 3603 sec (01:00:03) |

```

2018-10-03 14:19 UTC, HPCCSmoketest commented
1/1. Process of PR-11799, label: HPCC-20065 starts now. Estimated completion time is ~ 0.5 hour(s)

2018-10-03 14:22 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 735692996992d5e9ac45c08861fb319c1f1b4e71
Number of Error(s): 4
/mnt/disk1/home/vamosax/smoketest/PR-11799/HPCC-Platform/testing/unittests/cfgmgr2unittests.cpp:29:26: fatal error: SchemaItem.hpp: No such file or directory
make[2]: *** [testing/unittests/CMakeFiles/unittests.dir/cfgmgr2unittests.cpp.o] Error 1

[Build error:](https://gist.github.com/2b217666ade201445836053b8801845a)
Build log [Build log](https://gist.github.com/HPCCSmoketest/2b217666ade201445836053b8801845a#file-result-18-10-03-10-23-07-log)

2018-10-03 15:04 UTC, HPCCSmoketest commented
This PR (11799) is in the 4/6 position of the queue. Estimated start time is after ~2.0 hour(s)

2018-10-03 15:38 UTC, HPCCSmoketest commented
This PR (11799) is in the 3/5 position of the queue. Estimated start time is after ~1.5 hour(s)

2018-10-03 16:27 UTC, HPCCSmoketest commented
This PR (11799) is in the 2/4 position of the queue. Estimated start time is after ~1.0 hour(s)

2018-10-03 17:03 UTC, HPCCSmoketest commented
This PR (11799) is in the 1/3 position of the queue. Estimated start time is after ~0.5 hour(s)

2018-10-03 17:36 UTC, HPCCSmoketest commented
5/7. Process of PR-11799, label: HPCC-20065 starts now. Estimated completion time is ~ 0.5 hour(s)

2018-10-03 18:09 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 735692996992d5e9ac45c08861fb319c1f1b4e71
Build: success
ECL Watch:  Rebuilding Site
Rebuild: success
Install hpccsystems-platform-community_7.0.0-rc2.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   30 sec (00:00:30) |  189 sec (00:03:09) |  168 sec (00:02:48) |   22 sec (00:00:22) |   44 sec (00:00:44) | 1509 sec (00:25:09) |   21 sec (00:00:21) | 1983 sec (00:33:03) |

2018-10-04 13:36 UTC, kunalaswani commented
@emuharemagic please review

2018-10-04 14:05 UTC, emuharemagic requested changes
looks like most of the changes were picked up from the wrong source;

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    FilesWarning: "Broj vraćenih datoteka je preveliki. Vraćeno je samo prvih 100.000 datoteka sortiranih po datumu / vremenu. Ako želite ograničiti rezultate, podesite filter.",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    GraphControl: "Kontrola Grafova",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    LastEdit: "Poslednja Izmjena",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    LastEditedBy: "Autor Poslednje Izmjene",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    LastEditTime: "Vrijeme Poslednje Izmjene",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    Legend: "Legenda",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    Lock: "Zaključaj",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    LoggingOut: "Odjavljivanje",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    Login: "Prijavljivanje",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    Logout: "Odjavite se",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    LogVisualization: "Registrujte Vizuelizaciju",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    MaxSkew: "Maksimalni Skju (Distorzija)",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    MinSkew: "Minimalni Skju (Distorzija)",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    PleaseLogin: "Molimo prijavite se koristeći svoje korisničko ime i lozinku",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    PleaseSelectAServiceToBind: "Izaberite Servis za Upotrebu",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    PublishedByMe: "Moji Objavljeni Servisi",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    ReAuthenticate: "Ponovo se prijavite koristeći svoje korisničko ime i lozinku",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    ReportAnError: "Prijavite grešku",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    ReportError: "Prijavite grešku",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    ServiceName: "Ime Servisa",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    Table: "Tabela",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    title_BindingConfiguration: "Konfiguracija za Povezivanje",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    title_BindingDefinition: "Definicija Povezivanja",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    Unlock: "Otključajte",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    UpdateDFs: "Ažurirajte DFS",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    UserLogin: "Prijavite se samo koristeći svoje korisničko ime",
pls use the correct source tab for this

2018-10-04 14:05 UTC, emuharemagic commented on esp/src/eclwatch/nls/sr/hpcc.js
> +    YouAreAboutToDeleteDefinition: "Vi ste u procesu brisanja ove definicije. Da li ste sigurni da to želite učiniti?",
pls use the correct source tab for this

2018-10-04 14:41 UTC, kunalaswani commented
@emuharemagic sorry about that, my tabs got crossed, please review, corrected.

2018-10-04 14:44 UTC, HPCCSmoketest commented
Process of PR-11799, label: HPCC-20065 starts now. Estimated completion time is ~ 0.5 hour(s)

2018-10-04 15:17 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: df4fe79fe214cad30f21c1366069edb6c1930832
Build: success
ECL Watch:  Rebuilding Site
Rebuild: success
Install hpccsystems-platform-community_7.0.0-rc2.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  185 sec (00:03:05) |  166 sec (00:02:46) |   20 sec (00:00:20) |   42 sec (00:00:42) | 1495 sec (00:24:55) |   18 sec (00:00:18) | 1942 sec (00:32:22) |

2018-10-04 17:41 UTC, emuharemagic approved these changes

2018-10-04 17:46 UTC, merged