HPCC-20803 Document Sync up of SSH Keys
hpcc-systems/HPCC-Platform pull request #11897
Opened 2018-11-07 15:40 UTC by g-pan

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

@JamesDeFabia please review
@cloLN optionally, please review

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

http://10.240.32.243/view/Docs%207.0/job/AnotherDocBuild7/

2018-11-07 15:43 UTC, HPCCSmoketest commented
Process of PR-11897, label: H20803-Sync starts now. Estimated completion time is ~ 0.5 hour(s)

2018-11-07 15:49 UTC, JamesDeFabia requested changes
see comments inline

2018-11-07 15:49 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +          the system to work properly. If you used the
it is quite important that the certificates and SSH keys all match across all nodes in order for the system to work properly.
s/b
certificates and SSH keys **must** match across all nodes in order for the system to work properly.

2018-11-07 15:49 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +          steps above, this could insure that everything is properly in sync.
could insure?

2018-11-07 15:49 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +          are running on a CentOS 7 cluster, could use the following commands:
Does this only work on Centos 7?

2018-11-07 16:15 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: f124ed22a5b5d663be11ebee528850a317ccdc74
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   20 sec (00:00:20) |  340 sec (00:05:40) |    0 sec (00:00:00) |   26 sec (00:00:26) |   19 sec (00:00:19) | 1471 sec (00:24:31) |   19 sec (00:00:19) | 1895 sec (00:31:35) |

2018-11-08 21:57 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: fd0d76cbbceeffa53606c42bac55a89a7be4bee4
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   12 sec (00:00:12) |  367 sec (00:06:07) |    0 sec (00:00:00) |   28 sec (00:00:28) |   18 sec (00:00:18) | 1488 sec (00:24:48) |   17 sec (00:00:17) | 1930 sec (00:32:10) |

2018-11-12 20:38 UTC, g-pan commented
@JamesDeFabia please review. 
See http://10.240.32.243/view/Docs%207.0/job/AnotherDocBuild7/

2018-11-13 13:53 UTC, JamesDeFabia requested changes
A couple of grammar/style changes noted inline

2018-11-13 13:53 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +          <para>On a multi-node HPCC system certificates and SSH keys must all
needs a comma between:  system, certificates

2018-11-13 13:53 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +          match across all nodes in order for the system to work properly. If
match across all nodes for the system to work properly.

2018-11-13 13:53 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +          they do all match up. Another way to ensure this is the case is to
Another way to ensure this is the case is to
    sb
Another way to ensure this is to

2018-11-14 20:47 UTC, g-pan commented
updated, and rebased. @JamesDeFabia please review

2018-11-14 20:48 UTC, HPCCSmoketest commented
Process of PR-11897, label: H20803-Sync starts now. Estimated completion time is ~ 0.5 hour(s)

2018-11-14 20:49 UTC, JamesDeFabia approved these changes
good to merge

2018-11-14 21:20 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 032031b1d27658dd9d9b01314772a03862672609
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   37 sec (00:00:37) |  336 sec (00:05:36) |    0 sec (00:00:00) |   27 sec (00:00:27) |   18 sec (00:00:18) | 1454 sec (00:24:14) |   20 sec (00:00:20) | 1892 sec (00:31:32) |

2018-11-23 16:42 UTC, richardkchapman commented
@cloLN Please review

2018-11-28 16:19 UTC, g-pan commented
Updated and Rebased.

2018-11-28 17:35 UTC, HPCCSmoketest commented
This PR (11897) is in the 1/4 position of the queue. Estimated start time is after ~0.5 hour(s)

2018-11-28 17:49 UTC, HPCCSmoketest commented
Process of PR-11897, label: H20803-Sync starts now. Estimated completion time is ~ 0.5 hour(s)

2018-11-28 18:14 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: c5e53b7624ca06adf0e4f33d5aa1584e6761c36d
Build: success
Build: success
HPCC Start: Fail
HPCC start:
Starting mydafilesrv ...     [   OK    ]  
Starting mydali ...          [ TIMEOUT ] 
Starting mydfuserver ...     [ TIMEOUT ] 
Starting myeclagent ...      [ TIMEOUT ] 
Starting myeclccserver ...   [ TIMEOUT ] 
Starting myeclscheduler ...  [   OK    ]  
Starting myesp ...           [ TIMEOUT ] 
Starting myroxie ...         [ TIMEOUT ] 
Starting mysasha ...         [ TIMEOUT ] 
Starting mythor ...          [ TIMEOUT ] 
 
HPCC status:
mydafilesrv     is stopped,
mydali          is stopped,
mydfuserver     is stopped,
myeclagent      is stopped,
myeclccserver   is stopped,
myeclscheduler  ( pid    31481 ) is running ...
myesp           is stopped,
myroxie         is stopped,
mysasha         is stopped,
mythor          is stopped,
res: mydafilesrv     is stopped,
mydali          is stopped,
mydfuserver     is stopped,
myeclagent      is stopped,
myeclccserver   is stopped,
myesp           is stopped,
myroxie         is stopped,
mysasha         is stopped,
mythor          is stopped,
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   23 sec (00:00:23) |  350 sec (00:05:50) |    0 sec (00:00:00) |   27 sec (00:00:27) | 1027 sec (00:17:07) |    0 sec (00:00:00) |    0 sec (00:00:00) | 1427 sec (00:23:47) |

2018-11-28 20:10 UTC, HPCCSmoketest commented
This PR (11897) is in the 1/6 position of the queue. Estimated start time is after ~0.5 hour(s)

2018-11-28 20:39 UTC, HPCCSmoketest commented
Process of PR-11897, label: H20803-Sync starts now. Estimated completion time is ~ 0.5 hour(s)

2018-11-28 21:15 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: c5e53b7624ca06adf0e4f33d5aa1584e6761c36d
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |31 |0 |0 |0 |31 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Unittest error(s):
```
```

Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   43 sec (00:00:43) |  349 sec (00:05:49) |    0 sec (00:00:00) |   30 sec (00:00:30) |   19 sec (00:00:19) | 1651 sec (00:27:31) |   18 sec (00:00:18) | 2110 sec (00:35:10) |

2018-11-28 23:46 UTC, HPCCSmoketest commented
This PR (11897) is in the 1/4 position of the queue. Estimated start time is after ~0.5 hour(s)

2018-11-29 00:16 UTC, HPCCSmoketest commented
Process of PR-11897, label: H20803-Sync starts now. Estimated completion time is ~ 0.5 hour(s)

2018-11-29 00:49 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: c5e53b7624ca06adf0e4f33d5aa1584e6761c36d
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   36 sec (00:00:36) |  346 sec (00:05:46) |    0 sec (00:00:00) |   27 sec (00:00:27) |   18 sec (00:00:18) | 1489 sec (00:24:49) |   18 sec (00:00:18) | 1934 sec (00:32:14) |

2018-11-29 09:09 UTC, HPCCSmoketest commented
Process of PR-11897, label: H20803-Sync starts now. Estimated completion time is ~ 0.5 hour(s)

2018-11-29 09:42 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: c5e53b7624ca06adf0e4f33d5aa1584e6761c36d
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   44 sec (00:00:44) |  356 sec (00:05:56) |    0 sec (00:00:00) |   27 sec (00:00:27) |   18 sec (00:00:18) | 1500 sec (00:25:00) |   19 sec (00:00:19) | 1964 sec (00:32:44) |

2018-11-29 09:42 UTC, HPCCSmoketest commented
This PR (11897) is in the 1/1 position of the queue. Estimated start time is after ~0.5 hour(s)

2018-11-29 10:11 UTC, HPCCSmoketest commented
Process of PR-11897, label: H20803-Sync starts now. Estimated completion time is ~ 0.5 hour(s)

2018-11-29 10:44 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: c5e53b7624ca06adf0e4f33d5aa1584e6761c36d
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   20 sec (00:00:20) |  361 sec (00:06:01) |    0 sec (00:00:00) |   27 sec (00:00:27) |   18 sec (00:00:18) | 1495 sec (00:24:55) |   17 sec (00:00:17) | 1938 sec (00:32:18) |

2019-01-09 16:35 UTC, cloLN commented
Looks good.

2019-01-09 17:25 UTC, merged