HPCC-20372 Removing subfiles action does nothing
hpcc-systems/HPCC-Platform pull request #11968
Opened 2018-11-30 19:41 UTC by miguelvazq

Querying the store did nothing when refreshing. ESPLogicalFile handles
the refresh just fine.

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-11-30 19:42 UTC, miguelvazq commented
@GordonSmith Please review.

2018-11-30 19:42 UTC, HPCCSmoketest commented
Process of PR-11968, label: HPCC-20372 starts now. Estimated completion time is ~ 0.5 hour(s)

2018-11-30 20:13 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: fbda693fed790cc9ed4922661458a52e2decf2a9
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |808 |808 |0 |
|test (thor) |732 |732 |0 |
|test (roxie) |881 |881 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   37 sec (00:00:37) |  188 sec (00:03:08) |    0 sec (00:00:00) |   65 sec (00:01:05) |   22 sec (00:00:22) | 1494 sec (00:24:54) |   19 sec (00:00:19) | 1825 sec (00:30:25) |

2018-12-01 06:14 UTC, GordonSmith requested changes

2018-12-01 06:14 UTC, GordonSmith commented on esp/src/eclwatch/SFDetailsWidget.js
> -                    this._onSubFileRefresh();
I think the following might be preferable (will need a test):
```
var context = this;
this.logicalFile.removeSubfiles(this.subfilesGrid.getSelected()).then(function() {
    context._onSubFileRefresh();
});
```

2018-12-01 06:15 UTC, GordonSmith commented on esp/src/eclwatch/SFDetailsWidget.js
> -                    this._onSubFileRefresh();
IOW currently the refresh is happening before the remove has completed.

2018-12-03 09:56 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: fbda693fed790cc9ed4922661458a52e2decf2a9
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |808 |808 |0 |
|test (thor) |732 |732 |0 |
|test (roxie) |881 |881 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   35 sec (00:00:35) |  190 sec (00:03:10) |    0 sec (00:00:00) |   62 sec (00:01:02) |   22 sec (00:00:22) | 1520 sec (00:25:20) |   20 sec (00:00:20) | 1849 sec (00:30:49) |

2018-12-04 14:49 UTC, HPCCSmoketest commented
Process of PR-11968, label: HPCC-20372 starts now. Estimated completion time is ~ 0.5 hour(s)

2018-12-04 15:19 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 012319b02528182a26ca22813dfec807c9aadb7f
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |808 |808 |0 |
|test (thor) |732 |732 |0 |
|test (roxie) |881 |881 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   40 sec (00:00:40) |  187 sec (00:03:07) |    0 sec (00:00:00) |   63 sec (00:01:03) |   23 sec (00:00:23) | 1461 sec (00:24:21) |   20 sec (00:00:20) | 1794 sec (00:29:54) |

2018-12-07 14:14 UTC, miguelvazq commented
@GordonSmith bump

2018-12-07 14:28 UTC, GordonSmith requested changes

2018-12-07 14:45 UTC, miguelvazq commented on esp/src/eclwatch/SFDetailsWidget.js
> +                        context._onSubFileRefresh();
Looks like my last commit did not get pushed

2018-12-07 17:21 UTC, miguelvazq commented on esp/src/eclwatch/SFDetailsWidget.js
> +                        context._onSubFileRefresh();
Tested with _onSubFileRefresh seems to just refresh grid with "Zero Rows". The setting of the query seems to zero out the grid results. The refresh ESPLogicalFile seems to do the job which is why I omitted the setting of the query.

2018-12-11 16:04 UTC, miguelvazq commented
@GordonSmith Updated. Feel free to test

2018-12-11 16:05 UTC, HPCCSmoketest commented
Process of PR-11968, label: HPCC-20372 starts now. Estimated completion time is ~ 0.5 hour(s)

2018-12-11 16:35 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 5c1b44f9c5099c1c2c8530bb693a1ec3031c017a
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |808 |808 |0 |
|test (thor) |732 |732 |0 |
|test (roxie) |881 |881 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   25 sec (00:00:25) |  188 sec (00:03:08) |    0 sec (00:00:00) |   63 sec (00:01:03) |   18 sec (00:00:18) | 1482 sec (00:24:42) |   19 sec (00:00:19) | 1795 sec (00:29:55) |

2018-12-13 09:27 UTC, GordonSmith approved these changes
Looks fine.

2018-12-13 10:36 UTC, merged