HPCC-21152 Active WUs not attaching to correct queue
hpcc-systems/HPCC-Platform pull request #11985
Opened 2018-12-06 17:55 UTC by GordonSmith

Removed some erroneous debug statements

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-12-06 17:57 UTC, GordonSmith commented
@miguelvazq please review (and test)

2018-12-06 18:00 UTC, HPCCSmoketest commented
Process of PR-11985, label: HPCC-21152 starts now. Estimated completion time is ~ 0.5 hour(s)

2018-12-06 18:12 UTC, miguelvazq commented
Code looks good.

Testing: It would be ideal to add the ServerName : queuename
Line #205 ESPQueue.ts

`return this.ServerName + (this.ClusterName ? " - " + this.ClusterName : "");`

2018-12-06 18:30 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 9d78fb5084322bc2141ae7dab26e43c84f4feeab
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |808 |808 |0 |
|test (thor) |732 |732 |0 |
|test (roxie) |881 |881 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   52 sec (00:00:52) |  188 sec (00:03:08) |    0 sec (00:00:00) |   65 sec (00:01:05) |   21 sec (00:00:21) | 1466 sec (00:24:26) |   19 sec (00:00:19) | 1811 sec (00:30:11) |

2018-12-07 09:11 UTC, GordonSmith commented
@miguelvazq ready for review

2018-12-07 09:15 UTC, HPCCSmoketest commented
Process of PR-11985, label: HPCC-21152 starts now. Estimated completion time is ~ 0.5 hour(s)

2018-12-07 09:46 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 9499bc893b0fc78cce42e4a30f60c125ede7023c
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |808 |808 |0 |
|test (thor) |732 |732 |0 |
|test (roxie) |881 |881 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   47 sec (00:00:47) |  188 sec (00:03:08) |    0 sec (00:00:00) |   64 sec (00:01:04) |   18 sec (00:00:18) | 1504 sec (00:25:04) |   19 sec (00:00:19) | 1840 sec (00:30:40) |

2018-12-07 15:08 UTC, miguelvazq reviewed
Minor comment.

2018-12-07 15:08 UTC, miguelvazq commented on esp/src/src/ESPQueue.ts
> +export function GetTargetCluster(name, createIfMissing = false) {
This syntax seems odd

2018-12-07 15:08 UTC, miguelvazq commented on esp/src/src/ESPQueue.ts
> +export function GetServerJobQueue(name, createIfMissing = false) {
This syntax seems odd

2018-12-07 15:35 UTC, miguelvazq requested changes

2018-12-07 15:35 UTC, miguelvazq commented on esp/src/src/ESPQueue.ts
> +        return this.ServerName + (this.ClusterName ? " - " + this.ClusterName : "");
return this.ServerType + (this.ClusterName ? " - " + this.ClusterName : "");

2018-12-07 15:36 UTC, miguelvazq commented on esp/src/src/ESPQueue.ts
> +export function GetServerJobQueue(name, createIfMissing = false) {
As discussed this seems fine.

2018-12-07 15:40 UTC, GordonSmith commented
@miguelvazq change made as requested.

2018-12-07 15:41 UTC, HPCCSmoketest commented
This PR (11985) is in the 1/2 position of the queue. Estimated start time is after ~0.5 hour(s)

2018-12-07 15:50 UTC, miguelvazq commented on esp/src/src/ESPQueue.ts
> +export function GetTargetCluster(name, createIfMissing = false) {
As discussed this seems fine.

2018-12-07 15:58 UTC, miguelvazq commented
Tested and looks good.

2018-12-07 15:58 UTC, miguelvazq approved these changes

2018-12-07 16:09 UTC, miguelvazq commented
@richardkchapman Ready for merge.

2018-12-07 16:10 UTC, HPCCSmoketest commented
Process of PR-11985, label: HPCC-21152 starts now. Estimated completion time is ~ 0.5 hour(s)

2018-12-07 16:21 UTC, merged

2018-12-07 16:41 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: f1a13343950f1150d1e33fd20efd94b178c03cef
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |808 |808 |0 |
|test (thor) |732 |732 |0 |
|test (roxie) |881 |881 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   37 sec (00:00:37) |  189 sec (00:03:09) |    0 sec (00:00:00) |   58 sec (00:00:58) |   21 sec (00:00:21) | 1467 sec (00:24:27) |   19 sec (00:00:19) | 1791 sec (00:29:51) |