HPCC-21186 Service level transforms should run for all methods
hpcc-systems/HPCC-Platform pull request #12012
Opened 2018-12-18 21:38 UTC by afishbeck

We should treat service level transforms as common to all methods.
We can provide a way to selectively call common transforms in the
future.

Signed-off-by: Anthony Fishbeck <anthony.fishbeck@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2018-12-18 21:38 UTC, HPCCSmoketest commented
Process of PR-12012, label: desdlAlwaysRunServiceLevelTransforms starts now. Estimated completion time is ~ 0.5 hour(s)

2018-12-18 21:39 UTC, afishbeck commented
@timothyklemm please review and if possible test this change.

2018-12-18 22:07 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: ffbdd9d14f4beb9319926ab2bd6ac0c29395fb28
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |808 |808 |0 |
|test (thor) |732 |732 |0 |
|test (roxie) |882 |882 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   35 sec (00:00:35) |  185 sec (00:03:05) |    0 sec (00:00:00) |    2 sec (00:00:02) |   17 sec (00:00:17) | 1471 sec (00:24:31) |   20 sec (00:00:20) | 1730 sec (00:28:50) |

2018-12-19 03:41 UTC, timothyklemm requested changes
Preliminary testing was successful. I was able to move some method level transforms to service level. All transforms were processed, as evidenced by seeing the modified request in the log file.

All of the review comments are related to code redundancy. Not sure if old code is still necessary, but if it is it should share code with the new implementation and not duplicate it.

2018-12-19 22:33 UTC, afishbeck commented on esp/services/esdl_svc_engine/esdl_svc_custom.hpp
>         virtual void processTransform(IEspContext * context, IPropertyTree *tgtcfg, IPropertyTree *tgtctx, IEsdlDefService &srvdef, IEsdlDefMethod &mthdef, StringBuffer & request, IPropertyTree * bind
This method could come in handy, I'll keep it for now, but may decide to remove it later.

2018-12-19 22:34 UTC, afishbeck commented on esp/services/esdl_svc_engine/esdl_svc_custom.cpp
> +void CEsdlCustomTransform::processTransform(IEspContext * context, IPropertyTree *theroot, IXpathContext *xpathContext, const char *defaultTarget)
I've commoned up the code.

2018-12-19 22:34 UTC, afishbeck commented on esp/services/esdl_svc_engine/esdl_svc_custom.cpp
> +void processServiceAndMethodTransforms(IEsdlCustomTransform *serviceCrt, IEsdlCustomTransform *methodCrt, IEspContext * context, IPropertyTree *tgtcfg, IPropertyTree *tgtctx, IEsdlDefService &srvdef,
I've commoned up the code and used an initializer_list.  May switch to a vector later if we need something more flexible.

2018-12-19 22:35 UTC, afishbeck commented
@timothyklemm updated and squashed please review.

2018-12-19 22:36 UTC, HPCCSmoketest commented
Process of PR-12012, label: desdlAlwaysRunServiceLevelTransforms starts now. Estimated completion time is ~ 0.5 hour(s)

2018-12-19 23:05 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 3c9d2f7f23747005dc21a09c6d76ee8316c2692b
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |808 |808 |0 |
|test (thor) |732 |732 |0 |
|test (roxie) |882 |882 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   35 sec (00:00:35) |  184 sec (00:03:04) |    0 sec (00:00:00) |    2 sec (00:00:02) |   19 sec (00:00:19) | 1497 sec (00:24:57) |   19 sec (00:00:19) | 1756 sec (00:29:16) |

2018-12-20 12:23 UTC, timothyklemm approved these changes
Reviewed and tested. Service and method level transforms both applied.

2018-12-20 13:22 UTC, merged