HPCC-20903 Send html page for session reload when invalid session
hpcc-systems/HPCC-Platform pull request #12050
Opened 2019-01-10 21:50 UTC by wangkx

When ECLWatch page is closed without logging out, the ESP session
may be timed out in ESP, but, not in Internet browser. If the user
reopens ECLWatch by typing in the IP, the existing ESP returns a
JSON error. This fix replaces the JSON error with a html page.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2019-01-10 21:51 UTC, wangkx commented
@RussWhitehead @miguelvazq please review.

2019-01-10 22:10 UTC, HPCCSmoketest commented
Process of PR-12050, label: h20903 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-01-10 22:39 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: f022417a71044810be9b40ab7cd6d4249c434fb0
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |808 |808 |0 |
|test (thor) |732 |732 |0 |
|test (roxie) |882 |882 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   44 sec (00:00:44) |  188 sec (00:03:08) |    0 sec (00:00:00) |    2 sec (00:00:02) |   18 sec (00:00:18) | 1449 sec (00:24:09) |   18 sec (00:00:18) | 1719 sec (00:28:39) |

2019-01-11 01:28 UTC, RussWhitehead reviewed
Looks good, a few minor comments

2019-01-11 14:52 UTC, wangkx commented on esp/bindings/http/platform/httpservice.cpp
> +        content.appendf("<img id=\"logo\" src=\"%s%s\" />", espURL.str(), authReq.authBinding->queryLoginLogoURL());
The indentation here is a better read the HTML code.

2019-01-11 14:57 UTC, wangkx commented on initfiles/componentfiles/configxml/esp.xsd.in
> +                        <xs:attribute name="loginLogoURL" type="xs:string" use="optional" default="/esp/files/eclwatch/img/Loginlogo.png">
Someone may want to change this if the img files are installed into another location. We do the same as for logonURL, etc.

2019-01-11 15:03 UTC, wangkx commented on esp/bindings/http/platform/httpbinding.cpp
> +        const char* _loginLogoURL = authDomainTree->queryProp("@loginLogoURL");
This is in readAuthDomainCfg() which will not be called if the previous _loginLogoURL is set ( line 312).

2019-01-11 15:14 UTC, RussWhitehead commented
@wangkx Looks good to me
@miguelvazq Waiting for your review

2019-01-11 15:39 UTC, wangkx commented
@miguelvazq please double check the html code.

2019-01-12 00:35 UTC, miguelvazq requested changes

2019-01-12 00:35 UTC, miguelvazq commented on esp/bindings/http/platform/httpservice.cpp
> +                "#button {"
Remove button style

2019-01-12 00:35 UTC, miguelvazq commented on esp/bindings/http/platform/httpservice.cpp
> +               ".button:hover {"
Remove button style

2019-01-12 00:35 UTC, miguelvazq commented on esp/bindings/http/platform/httpservice.cpp
> +                ".visible {"
Remove .visible class

2019-01-14 14:16 UTC, HPCCSmoketest commented
Process of PR-12050, label: h20903 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-01-14 14:19 UTC, wangkx commented
@miguelvazq I just removed the code based on your comments. Please review.

2019-01-14 14:45 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 3f802a8746d1cace88d68ca41bcddbb02c6fc737
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |808 |808 |0 |
|test (thor) |732 |732 |0 |
|test (roxie) |882 |882 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   30 sec (00:00:30) |  184 sec (00:03:04) |    0 sec (00:00:00) |    2 sec (00:00:02) |   19 sec (00:00:19) | 1449 sec (00:24:09) |   19 sec (00:00:19) | 1703 sec (00:28:23) |

2019-01-14 16:19 UTC, miguelvazq commented
Looks good.

2019-01-14 16:19 UTC, miguelvazq approved these changes

2019-01-14 16:47 UTC, HPCCSmoketest commented
This PR (12050) is in the 1/1 position of the queue. Estimated start time is after ~0.5 hour(s)

2019-01-14 17:19 UTC, HPCCSmoketest commented
Process of PR-12050, label: h20903 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-01-14 17:48 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 6b520c4d27eb20983b650764c247f3d255b75d88
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |808 |808 |0 |
|test (thor) |732 |732 |0 |
|test (roxie) |882 |882 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   31 sec (00:00:31) |  186 sec (00:03:06) |    0 sec (00:00:00) |    2 sec (00:00:02) |   17 sec (00:00:17) | 1451 sec (00:24:11) |   17 sec (00:00:17) | 1704 sec (00:28:24) |

2019-01-14 18:24 UTC, wangkx commented
@richardkchapman this PR is ready to be merged.

2019-01-15 10:21 UTC, merged