HPCC-20218 Update Data Handling doc and images
hpcc-systems/HPCC-Platform pull request #12107
Opened 2019-01-28 20:38 UTC by g-pan

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

@JamesDeFabia please review 

http://10.240.32.243/view/Docs%207.0/job/DocDev70/49/CE=ubuntu-14.04-amd64-1/artifact/build-docs/Release/docs/EN_US/HPCCDataHandling_EN_US-7.0.0-documentation0.pdf#page=7

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [X] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [X] The commit message is properly formatted and free of typos.
  - [X] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [X] My change requires a change to the documentation.
  - [X] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [X] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [X] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Successful Unit Testing: http://10.240.32.243/view/Docs%207.0/job/DocDev70/

2019-01-28 20:41 UTC, HPCCSmoketest commented
Process of PR-12107, label: H20218-WinSCP starts now. Estimated completion time is ~ 0.5 hour(s)

2019-01-28 21:13 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 76da1fb7ba13dcdbfd0253fd6bc9dc38e9f022ed
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   25 sec (00:00:25) |  364 sec (00:06:04) |    0 sec (00:00:00) |   29 sec (00:00:29) |   20 sec (00:00:20) | 1415 sec (00:23:35) |   19 sec (00:00:19) | 1872 sec (00:31:12) |

2019-01-29 02:07 UTC, JamesDeFabia requested changes
I know the intent is to make the instructions software-agnostic, but there are some missing details. We need to tell users to choose SFTP as the protocol. Hostname, port, user credentials... See the steps in the Jira. 
We do not want to document the 3rd party software, but we need to inform users what info they need to know to use a tool to secure copy over SFTP.

2019-01-29 02:09 UTC, JamesDeFabia commented
Also the PDF linked is NOT the same as these source files,

2019-01-29 18:31 UTC, HPCCSmoketest commented
Process of PR-12107, label: H20218-WinSCP starts now. Estimated completion time is ~ 0.5 hour(s)

2019-01-29 19:02 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 6dee34211550405de451dfe67e7a2b21e1b1819e
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   25 sec (00:00:25) |  350 sec (00:05:50) |    0 sec (00:00:00) |   26 sec (00:00:26) |   18 sec (00:00:18) | 1432 sec (00:23:52) |   20 sec (00:00:20) | 1871 sec (00:31:11) |

2019-01-29 19:05 UTC, g-pan commented
Updated and Rebased. @JamesDeFabia please review

2019-01-29 19:38 UTC, JamesDeFabia requested changes
almost there.. just one minor change inline

2019-01-29 19:38 UTC, JamesDeFabia commented on docs/EN_US/HPCCDataHandling/DH-Mods/DH-Mod1.xml
> +            your HPCC Cluster's IP address through port 22 in your SCP tool.
your Landing Zone's IP or hostname

2019-01-29 20:09 UTC, HPCCSmoketest commented
Process of PR-12107, label: H20218-WinSCP starts now. Estimated completion time is ~ 0.5 hour(s)

2019-01-29 20:41 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 23fbdfeb4ea610897b86c0301e9a1eda51483839
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |95 |95 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |806 |806 |0 |
|test (thor) |730 |730 |0 |
|test (roxie) |879 |879 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   24 sec (00:00:24) |  353 sec (00:05:53) |    0 sec (00:00:00) |   26 sec (00:00:26) |   18 sec (00:00:18) | 1435 sec (00:23:55) |   19 sec (00:00:19) | 1875 sec (00:31:15) |

2019-01-29 21:04 UTC, JamesDeFabia approved these changes
Looks good

2019-01-30 07:17 UTC, merged