HPCC-20896 Support ESP session cookie verification
hpcc-systems/HPCC-Platform pull request #12169
Opened 2019-02-12 21:14 UTC by wangkx

An new ESP method /esp/verify is added to verify ESP session
cookies. The method can be used to verify a session ID
during the first load of any ECL Watch page. If no cookie
name is specified, all the cookies in HTTP Cookie header are
verified.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2019-02-12 21:17 UTC, HPCCSmoketest commented
Process of PR-12169, label: h20896 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-02-12 21:46 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 653baae644684c28d09a535a2a2a631126c01d74
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |101 |101 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |813 |813 |0 |
|test (thor) |739 |739 |0 |
|test (roxie) |887 |887 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  186 sec (00:03:06) |    0 sec (00:00:00) |    2 sec (00:00:02) |   18 sec (00:00:18) | 1453 sec (00:24:13) |   19 sec (00:00:19) | 1695 sec (00:28:15) |

2019-02-12 21:55 UTC, wangkx commented
@RussWhitehead please review.

2019-02-13 19:33 UTC, RussWhitehead requested changes
A few comments and questions

2019-02-13 19:33 UTC, RussWhitehead commented on esp/bindings/http/platform/httpservice.cpp
> +        cookie.verificationDetails.set("ESP cannot verify this cookie. This cookie is only valid when updating an expired passwsord.");
Misspelling (passwsord)

2019-02-13 19:33 UTC, RussWhitehead commented on esp/bindings/http/platform/httpservice.cpp
> +                cookies.append(*(new CESPCookieVerification("ESPSessionID", "")));
Why is this necessary?  You already know "name" is "ESPSessionID", except perhaps for the casing of that string. Can't you always call
    cookies.append(*(new CESPCookieVerification(name, "")));

2019-02-13 19:33 UTC, RussWhitehead commented on esp/bindings/http/platform/httpservice.cpp
> +        return false;
When could sessionID be 0?  No sessions enabled?  Perhaps a comment here would help

2019-02-13 19:33 UTC, RussWhitehead commented on esp/bindings/http/platform/httpservice.cpp
> +        if (timeNow - lastSessionCleanUpTime >= authReq.authBinding->getCheckSessionTimeoutSeconds())
I prefer to see parenthesis around "timeNow - lastSessionCleanUpTime"

2019-02-13 19:33 UTC, RussWhitehead commented on esp/bindings/http/platform/httpservice.cpp
> +    if (!checkValid && !isSessionIDCookieValid)
I believe this could be coded as "else if"

2019-02-13 19:58 UTC, wangkx commented
@RussWhitehead please review my changes.

2019-02-13 20:02 UTC, HPCCSmoketest commented
Process of PR-12169, label: h20896 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-02-13 20:15 UTC, RussWhitehead approved these changes
@wangkx Looks good

2019-02-13 20:31 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 9060b20a8348a403b51b97205657231399ad995d
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |101 |101 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |819 |819 |0 |
|test (thor) |744 |744 |0 |
|test (roxie) |893 |893 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   22 sec (00:00:22) |  185 sec (00:03:05) |    0 sec (00:00:00) |    3 sec (00:00:03) |   17 sec (00:00:17) | 1453 sec (00:24:13) |   19 sec (00:00:19) | 1699 sec (00:28:19) |

2019-02-13 21:07 UTC, HPCCSmoketest commented
Process of PR-12169, label: h20896 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-02-13 21:36 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: efc5f54ae142ff65c74e833a9abb4a0ff5a69edb
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |101 |101 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |819 |819 |0 |
|test (thor) |744 |744 |0 |
|test (roxie) |893 |893 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   25 sec (00:00:25) |  188 sec (00:03:08) |    0 sec (00:00:00) |    3 sec (00:00:03) |   19 sec (00:00:19) | 1442 sec (00:24:02) |   21 sec (00:00:21) | 1698 sec (00:28:18) |

2019-02-13 21:37 UTC, wangkx commented
@richardkchapman this PR is ready to be merged.

2019-02-14 08:52 UTC, merged