HPCC-21519 THOR - Make sure audience and message class is sensible
hpcc-systems/HPCC-Platform pull request #12204
Opened 2019-02-21 10:16 UTC by shamser

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2019-02-21 10:17 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-02-21 10:19 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: a475db506c62d05b61c66f7f9610187245068e5e
Number of Error(s): 4
/mnt/disk1/home/vamosax/smoketest/PR-12204/HPCC-Platform/common/thorhelper/thorxmlread.cpp:608:84: error: \xe2\x80\x98INERRLOG\xe2\x80\x99 was not declared in this scope

[Build error:](https://gist.github.com/a1ec96b31430f90c64c0b0784f493b36)
Build log [Build log](https://gist.github.com/HPCCSmoketest/a1ec96b31430f90c64c0b0784f493b36#file-result-19-02-21-05-23-43-log)

2019-02-21 11:02 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-02-21 11:05 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: a475db506c62d05b61c66f7f9610187245068e5e
Number of Error(s): 4
/mnt/disk1/home/vamosax/smoketest/PR-12204/HPCC-Platform/common/thorhelper/thorxmlread.cpp:608:84: error: \xe2\x80\x98INERRLOG\xe2\x80\x99 was not declared in this scope

[Build error:](https://gist.github.com/df21223dd4734eb892b64d9eef4ecb5f)
Build log [Build log](https://gist.github.com/HPCCSmoketest/df21223dd4734eb892b64d9eef4ecb5f#file-result-19-02-21-06-09-21-log)

2019-02-21 14:16 UTC, HPCCSmoketest commented
This PR (12204) is in the 3/4 position of the queue. Estimated start time is after ~1.5 hour(s)

2019-02-21 14:45 UTC, HPCCSmoketest commented
This PR (12204) is in the 2/3 position of the queue. Estimated start time is after ~1.0 hour(s)

2019-02-21 15:14 UTC, HPCCSmoketest commented
This PR (12204) is in the 1/2 position of the queue. Estimated start time is after ~0.5 hour(s)

2019-02-21 15:43 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-02-21 15:45 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: a475db506c62d05b61c66f7f9610187245068e5e
Number of Error(s): 4
/mnt/disk1/home/vamosax/smoketest/PR-12204/HPCC-Platform/common/thorhelper/thorxmlread.cpp:608:84: error: \xe2\x80\x98INERRLOG\xe2\x80\x99 was not declared in this scope

[Build error:](https://gist.github.com/5c54b3b8241068a04de4efcbf5e5ae2a)
Build log [Build log](https://gist.github.com/HPCCSmoketest/5c54b3b8241068a04de4efcbf5e5ae2a#file-result-19-02-21-10-49-31-log)

2019-02-25 16:44 UTC, HPCCSmoketest commented
This PR (12204) is in the 1/6 position of the queue. Estimated start time is after ~0.5 hour(s)

2019-02-25 17:14 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Estimated completion time is ~0.5 hour(s)

2019-02-25 17:16 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: aad0d1a204b5409939e7a04b66f3de4450a9b227
Number of Error(s): 4
/mnt/disk1/home/vamosax/smoketest/PR-12204/HPCC-Platform/common/thorhelper/thorxmlread.cpp:608:84: error: \xe2\x80\x98INERRLOG\xe2\x80\x99 was not declared in this scope

[Build error:](https://gist.github.com/426cdfebd32c2be1b14fa58a50f8f32b)
Build log [Build log](https://gist.github.com/HPCCSmoketest/426cdfebd32c2be1b14fa58a50f8f32b#file-result-19-02-25-12-20-46-log)

2019-02-26 11:15 UTC, HPCCSmoketest commented
This PR (12204) is in the 1/1 position of the queue. Estimated start time is after ~0.5 hour(s)

2019-02-26 11:44 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: d9ca28bd0a1434e196508f6ccc2d7d8fff61a889
Estimated completion time is ~0.5 hour(s)

2019-02-26 12:13 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d9ca28bd0a1434e196508f6ccc2d7d8fff61a889
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |101 |101 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |819 |819 |0 |
|test (thor) |744 |744 |0 |
|test (roxie) |893 |893 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   24 sec (00:00:24) |  192 sec (00:03:12) |    0 sec (00:00:00) |    2 sec (00:00:02) |   18 sec (00:00:18) | 1442 sec (00:24:02) |   20 sec (00:00:20) | 1698 sec (00:28:18) |

2019-02-26 12:13 UTC, HPCCSmoketest commented
This PR (12204) is in the 1/1 position of the queue. Estimated start time is after ~0.5 hour(s)

2019-02-26 12:41 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: 5933e27f1b3722ca99a064ed60db67c541d19ab3
Estimated completion time is ~0.5 hour(s)

2019-02-26 13:10 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 5933e27f1b3722ca99a064ed60db67c541d19ab3
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |101 |101 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |819 |819 |0 |
|test (thor) |744 |744 |0 |
|test (roxie) |893 |893 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   22 sec (00:00:22) |  186 sec (00:03:06) |    0 sec (00:00:00) |    2 sec (00:00:02) |   18 sec (00:00:18) | 1443 sec (00:24:03) |   18 sec (00:00:18) | 1689 sec (00:28:09) |

2019-02-28 10:27 UTC, shamser commented
@jakesmith Please can you review the logging changes in the Thor

2019-03-01 10:23 UTC, jakesmith commented
@shamser - I'll review the 2nd commit, but is it intentional that this 2nd commit contains non-thor related changes too? e.g. dllserver / environment / roxiehelper ?

2019-03-01 13:16 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: eeead1f44a6c7db4be6444d34b169cca93141f6f
Estimated completion time is ~0.5 hour(s)

2019-03-01 13:18 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: eeead1f44a6c7db4be6444d34b169cca93141f6f
Number of Error(s): 5
/mnt/disk1/home/vamosax/smoketest/PR-12204/HPCC-Platform/system/jlib/jmutex.hpp:996:7: error: use of deleted function \xe2\x80\x98std::atomic<_Tp*>::atomic(const std::atomic<_Tp*>&) [with _Tp = OsDiskInfo]\xe2\x80\x99

[Build error:](https://gist.github.com/7847029142be681e284ade4b152c7d6c)
Build log [Build log](https://gist.github.com/HPCCSmoketest/7847029142be681e284ade4b152c7d6c#file-result-19-03-01-08-22-52-log)

2019-03-01 13:50 UTC, shamser commented
@jakesmith It shouldn't contain changes related to other components.  Leave the commit until I've looked into this.

2019-03-01 14:14 UTC, HPCCSmoketest commented
This PR (12204) is in the 2/7 position of the queue. Estimated start time is after ~1.0 hour(s)

2019-03-01 14:44 UTC, HPCCSmoketest commented
This PR (12204) is in the 1/6 position of the queue. Estimated start time is after ~0.5 hour(s)

2019-03-01 15:14 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: eeead1f44a6c7db4be6444d34b169cca93141f6f
Estimated completion time is ~0.5 hour(s)

2019-03-01 15:44 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: eeead1f44a6c7db4be6444d34b169cca93141f6f
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |104 |104 |0 |0 |0 |34 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |24 sec  (00:00:24) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |25 sec  (00:00:25) |
|test (hthor) |819 |819 |0 |247 sec  (00:04:07) |
|test (thor) |744 |744 |0 |595 sec  (00:09:55) |
|test (roxie) |893 |893 |0 |350 sec  (00:05:50) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   20 sec (00:00:20) |  191 sec (00:03:11) |    0 sec (00:00:00) |    2 sec (00:00:02) |   18 sec (00:00:18) | 1504 sec (00:25:04) |   19 sec (00:00:19) | 1754 sec (00:29:14) |

2019-03-05 11:12 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: b6ddde888841b19c2a40ded50f080b3baa36c349
Estimated completion time is ~0.5 hour(s)

2019-03-05 11:15 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: b6ddde888841b19c2a40ded50f080b3baa36c349
Number of Error(s): 4
/mnt/disk1/home/vamosax/smoketest/PR-12204/HPCC-Platform/common/remote/rmtspawn.cpp:459:29: error: \xe2\x80\x98MCwarning\xe2\x80\x99 was not declared in this scope

[Build error:](https://gist.github.com/91c92f23a2f9d8a6f3882c37bce1378a)
Build log [Build log](https://gist.github.com/HPCCSmoketest/91c92f23a2f9d8a6f3882c37bce1378a#file-result-19-03-05-06-19-35-log)

2019-03-05 11:45 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: b8ceefe329e2b632206c78ec369a9be695501fc0
Estimated completion time is ~0.5 hour(s)

2019-03-05 12:18 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: b8ceefe329e2b632206c78ec369a9be695501fc0
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |104 |104 |0 |0 |0 |34 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |24 sec  (00:00:24) |
|setup (thor) |11 |11 |0 |45 sec  (00:00:45) |
|setup (roxie) |11 |11 |0 |18 sec  (00:00:18) |
|test (hthor) |819 |819 |0 |258 sec  (00:04:18) |
|test (thor) |744 |744 |0 |584 sec  (00:09:44) |
|test (roxie) |893 |893 |0 |521 sec  (00:08:41) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   22 sec (00:00:22) |  193 sec (00:03:13) |    0 sec (00:00:00) |    2 sec (00:00:02) |   19 sec (00:00:19) | 1646 sec (00:27:26) |   19 sec (00:00:19) | 1901 sec (00:31:41) |

2019-03-05 14:46 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: dfa90a389fdd6229ef79d5d24baed9532badc3c8
Estimated completion time is ~0.5 hour(s)

2019-03-05 14:49 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: dfa90a389fdd6229ef79d5d24baed9532badc3c8
Number of Error(s): 6
/mnt/disk1/home/vamosax/smoketest/PR-12204/HPCC-Platform/thorlcr/thorutil/thmem.cpp:1181:79: error: \xe2\x80\x98IWARNLOG\xe2\x80\x99 was not declared in this scope

[Build error:](https://gist.github.com/7108ae308552004ace3699efdc1d6104)
Build log [Build log](https://gist.github.com/HPCCSmoketest/7108ae308552004ace3699efdc1d6104#file-result-19-03-05-09-53-03-log)

2019-03-06 10:08 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: 1890633ebe066465414f308932d962e9373a2f14
Estimated completion time is ~0.5 hour(s)

2019-03-06 10:11 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 1890633ebe066465414f308932d962e9373a2f14
Number of Error(s): 6
/mnt/disk1/home/vamosax/smoketest/PR-12204/HPCC-Platform/thorlcr/thorutil/thbuf.cpp:1864:76: error: \xe2\x80\x98IWARNLOG\xe2\x80\x99 was not declared in this scope

[Build error:](https://gist.github.com/846ffefbbb9917d4f87ceef609dfb421)
Build log [Build log](https://gist.github.com/HPCCSmoketest/846ffefbbb9917d4f87ceef609dfb421#file-result-19-03-06-05-15-06-log)

2019-03-13 13:49 UTC, jakesmith commented
@shamser - I've been holding off reviewing this, because it still contains a lot of non related files in the commit (+ the build failure).

2019-04-11 07:33 UTC, shamser commented
@jakesmith Unrelated changes removed and rebased.  Please can you review?

2019-04-11 07:47 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: d9830e64d74fd604d1223adc253bed743341c26b
Estimated completion time is ~0.5 hour(s)

2019-04-11 08:13 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d9830e64d74fd604d1223adc253bed743341c26b
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |36 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |23 sec  (00:00:23) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |22 sec  (00:00:22) |
|test (hthor) |823 |823 |0 |158 sec  (00:02:38) |
|test (thor) |748 |748 |0 |594 sec  (00:09:54) |
|test (roxie) |897 |897 |0 |213 sec  (00:03:33) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   32 sec (00:00:32) |  213 sec (00:03:33) |    0 sec (00:00:00) |    2 sec (00:00:02) |   17 sec (00:00:17) | 1275 sec (00:21:15) |   19 sec (00:00:19) | 1558 sec (00:25:58) |

2019-04-11 14:55 UTC, jakesmith requested changes

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/activities/keyedjoin/thkeyedjoinslave.cpp
> +                            DBGLOG("KJ service failed to remove [%u]", closeCmd);
this should prob. be a IWARNLOG

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/graph/thgraph.cpp
> +#endif
can remove the #ifndef - IERRLOG on it's own would be good.

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/graph/thgraph.cpp
> +            DBGLOG("Failed to capture process stacks: %s", output.str());
IWARNLOG

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/graph/thgraphmaster.cpp
> +                DBGLOG("CBarrierMaster, raise barrier message on tag %d, already received from slave %d", tag, sender);
IWARNLOG

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/graph/thgraphmaster.cpp
> +            OERRLOG("Unable to record exception in workunit: %s", m.str());
IWARNLOG

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/graph/thgraphmaster.cpp
> +            OERRLOG("Unable to record exception in workunit: unknown exception");
IWARNLOG

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/graph/thgraphmaster.cpp
> +            OERRLOG("Unable to record exception in workunit: %s", m.str());
IWARNLOG

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/graph/thgraphmaster.cpp
> +            OERRLOG("Unable to record exception in workunit: unknown exception");
IWARNLOG

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/master/thgraphmanager.cpp
> +        OERRLOG("Failed to reply to agent %s",agentep.getUrlStr(s).str());
IERRLOG

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/slave/slavmain.cpp
> +        OWARNLOG("Renamed to %s", bakName.str());
not sure why that was a warning. Change to DBGLOG

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/thorutil/thmem.cpp
> +            DBGLOG("CThorExpandingRowArray::serialize ignoring NULL row");
IWARNLOG

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/thorutil/thormisc.cpp
> +            DBGLOG("Failed to use %s as log directory, using current working directory", logdir); // default working directory should be open already
OWARLOG

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/thorutil/thormisc.cpp
> +    DBGLOG("Build %s", BUILD_TAG);
PROGLOG

2019-04-11 14:55 UTC, jakesmith commented on thorlcr/thorutil/thormisc.cpp
> +    DBGLOG("Opened log file %s", lf.str());
PROGLOG

2019-04-11 14:56 UTC, jakesmith commented
@shamser - added some comments/suggestions

2019-04-11 15:21 UTC, shamser commented
@jakesmith Modified as suggested.  Shall I squash?

2019-04-11 15:50 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: 39943442873f6212a9a6c0a8dae729530b225971
Estimated completion time is ~0.5 hour(s)

2019-04-11 16:08 UTC, jakesmith commented
@shamser - yes go ahead please.

2019-04-11 16:19 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 39943442873f6212a9a6c0a8dae729530b225971
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |106 |105 |0 |0 |1 |136 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |8 sec |



Unittest error(s):
```
ConfigMgr 2.0 - Load and Parse - Verifying configuration XSDs are compliant...
*** ConfigMgr 2.0 - Templates - Loading Only ***
*** ConfigMgr 2.0 - Templates - Inputs ***
*** ConfigMgr 2.0 - Templates - Variable substitution tests ***
*** ConfigMgr 2.0 - Templates - Execute Templates ***
*** ConfigMgr 2.0 - Templates - Find Node Tests ***
*** ConfigMgr 2.0 - Templates - Create Node Tests ***

```

Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |25 sec  (00:00:25) |
|setup (thor) |11 |11 |0 |45 sec  (00:00:45) |
|setup (roxie) |11 |11 |0 |18 sec  (00:00:18) |
|test (hthor) |825 |825 |0 |186 sec  (00:03:06) |
|test (thor) |750 |750 |0 |602 sec  (00:10:02) |
|test (roxie) |899 |899 |0 |222 sec  (00:03:42) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   31 sec (00:00:31) |  215 sec (00:03:35) |    0 sec (00:00:00) |    3 sec (00:00:03) |   18 sec (00:00:18) | 1409 sec (00:23:29) |   19 sec (00:00:19) | 1695 sec (00:28:15) |

2019-04-11 16:36 UTC, jakesmith commented
@AttilaVamos - not clear from above - can you see which unittest failed?

2019-04-11 16:41 UTC, AttilaVamos commented
@jakesmith It was the DFUAccessTests

2019-04-11 16:41 UTC, AttilaVamos commented
@jakesmith It was the DFUAccessTests

2019-04-11 16:44 UTC, AttilaVamos commented
Recheduled.

2019-04-11 16:48 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: 39943442873f6212a9a6c0a8dae729530b225971
Estimated completion time is ~0.5 hour(s)

2019-04-11 16:48 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: 39943442873f6212a9a6c0a8dae729530b225971
Estimated completion time is ~0.5 hour(s)

2019-04-11 17:14 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 39943442873f6212a9a6c0a8dae729530b225971
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |34 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |28 sec  (00:00:28) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |17 sec  (00:00:17) |
|test (hthor) |825 |825 |0 |168 sec  (00:02:48) |
|test (thor) |750 |750 |0 |587 sec  (00:09:47) |
|test (roxie) |901 |901 |0 |210 sec  (00:03:30) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   39 sec (00:00:39) |  212 sec (00:03:32) |    0 sec (00:00:00) |    3 sec (00:00:03) |   18 sec (00:00:18) | 1250 sec (00:20:50) |   20 sec (00:00:20) | 1542 sec (00:25:42) |

2019-04-11 17:15 UTC, jakesmith commented
>It was the DFUAccessTests

@AttilaVamos - ok interesting, can you send me the logs / core ?

2019-04-12 09:23 UTC, AttilaVamos commented
@jakesmith  sent via Flowdock

2019-04-15 08:55 UTC, jakesmith commented
@shamser - please squash

2019-04-17 11:51 UTC, shamser commented
@jakesmith Squashed.

2019-04-17 12:06 UTC, jakesmith commented
@shamser - need re-targeting to master (for 7.4)

2019-04-17 12:09 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: New commit.
Commit ID: d9e1436b7fdd0fabb5334adfa838466fff51baeb
Estimated completion time is ~0.5 hour(s)

2019-04-17 12:36 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d9e1436b7fdd0fabb5334adfa838466fff51baeb
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |37 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |3 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |25 sec  (00:00:25) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |21 sec  (00:00:21) |
|test (hthor) |825 |825 |0 |195 sec  (00:03:15) |
|test (thor) |750 |750 |0 |593 sec  (00:09:53) |
|test (roxie) |901 |901 |0 |206 sec  (00:03:26) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   31 sec (00:00:31) |  213 sec (00:03:33) |    0 sec (00:00:00) |    3 sec (00:00:03) |   20 sec (00:00:20) | 1305 sec (00:21:45) |   19 sec (00:00:19) | 1591 sec (00:26:31) |

2019-04-18 07:39 UTC, richardkchapman commented
I think some of the other changes in this series have gone in 7.2 - not sure whether it needs to be master?

2019-04-18 08:56 UTC, jakesmith commented
ok, I wasn't sure. I thought as not a regression/fix - it shouldn't be a point build change.

2019-04-18 10:21 UTC, richardkchapman commented
@shamser Are you ok with this going in 7.2.x?

2019-04-18 10:37 UTC, shamser commented
@richardkchapman May be merge master so that we can get the other logging related changes in together.  What do you think?

2019-04-18 12:29 UTC, richardkchapman commented
@shamser Fine by me

2019-04-18 12:45 UTC, HPCCSmoketest commented
Process of PR-12204, label: issue21519 starts now.
The reason of this test is: Base branch changed.
Commit ID: d9e1436b7fdd0fabb5334adfa838466fff51baeb
Estimated completion time is ~0.5 hour(s)

2019-04-18 13:12 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d9e1436b7fdd0fabb5334adfa838466fff51baeb
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |23 sec  (00:00:23) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |25 sec  (00:00:25) |
|test (hthor) |827 |827 |0 |154 sec  (00:02:34) |
|test (thor) |752 |752 |0 |582 sec  (00:09:42) |
|test (roxie) |903 |903 |0 |230 sec  (00:03:50) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   32 sec (00:00:32) |  209 sec (00:03:29) |    0 sec (00:00:00) |    2 sec (00:00:02) |   18 sec (00:00:18) | 1279 sec (00:21:19) |   19 sec (00:00:19) | 1559 sec (00:25:59) |

2019-04-18 13:20 UTC, merged