HPCC-21518 DALI - Make sure audience and message class is sensible
hpcc-systems/HPCC-Platform pull request #12202
Opened 2019-02-20 16:08 UTC by shamser

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2019-02-20 16:28 UTC, HPCCSmoketest commented
This PR (12202) is in the 2/2 position of the queue. Estimated start time is after ~1.0 hour(s)

2019-02-20 16:58 UTC, HPCCSmoketest commented
This PR (12202) is in the 1/1 position of the queue. Estimated start time is after ~0.5 hour(s)

2019-02-20 17:30 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-02-20 17:59 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: e0c344e04cc5e791b591e0229b6230919f5f9ff3
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |101 |101 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |819 |819 |0 |
|test (thor) |744 |744 |0 |
|test (roxie) |893 |893 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   32 sec (00:00:32) |  184 sec (00:03:04) |    0 sec (00:00:00) |    3 sec (00:00:03) |   19 sec (00:00:19) | 1445 sec (00:24:05) |   21 sec (00:00:21) | 1704 sec (00:28:24) |

2019-02-21 14:16 UTC, HPCCSmoketest commented
This PR (12202) is in the 1/4 position of the queue. Estimated start time is after ~0.5 hour(s)

2019-02-21 14:45 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-02-21 15:13 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: e0c344e04cc5e791b591e0229b6230919f5f9ff3
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |101 |101 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |819 |819 |0 |
|test (thor) |744 |744 |0 |
|test (roxie) |893 |893 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   27 sec (00:00:27) |  188 sec (00:03:08) |    0 sec (00:00:00) |    3 sec (00:00:03) |   18 sec (00:00:18) | 1438 sec (00:23:58) |   21 sec (00:00:21) | 1695 sec (00:28:15) |

2019-02-22 10:13 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-02-22 10:42 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: bbf2b4734f340f5d0bdd75510e0cb86ff4de5461
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |101 |101 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |819 |819 |0 |
|test (thor) |744 |739 |5 |
|test (roxie) |893 |888 |5 |


[Errors:](https://gist.github.com/5e380e78837f7b568c707e1ec73c93c8)
- test
  - thor
    - 597\. [spray_header_test (isTerminated=false)](https://gist.github.com/HPCCSmoketest/5e380e78837f7b568c707e1ec73c93c8#file-spray_header_test-isterminated-false-w20190222-053815-8-log), 598\. [spray_header_test (isTerminated=true)](https://gist.github.com/HPCCSmoketest/5e380e78837f7b568c707e1ec73c93c8#file-spray_header_test-isterminated-true-w20190222-053815-6-log), 605\. [spray_test_json (isSmallFile=false)](https://gist.github.com/HPCCSmoketest/5e380e78837f7b568c707e1ec73c93c8#file-spray_test_json-issmallfile-false-w20190222-053818-4-log), 603\. [spray_test_json (isSmallFile=true, isUnBallanced=false)](https://gist.github.com/HPCCSmoketest/5e380e78837f7b568c707e1ec73c93c8#file-spray_test_json-issmallfile-true,-isunballanced-false-w20190222-053817-8-log), 604\. [spray_test_json (isSmallFile=true, isUnBallanced=true)](https://gist.github.com/HPCCSmoketest/5e380e78837f7b568c707e1ec73c93c8#file-spray_test_json-issmallfile-true,-isunballanced-true-w20190222-053817-4-log), 
  - roxie
    - 675\. [spray_header_test (isTerminated=false)](https://gist.github.com/HPCCSmoketest/5e380e78837f7b568c707e1ec73c93c8#file-spray_header_test-isterminated-false-w20190222-054607-5-log), 676\. [spray_header_test (isTerminated=true)](https://gist.github.com/HPCCSmoketest/5e380e78837f7b568c707e1ec73c93c8#file-spray_header_test-isterminated-true-w20190222-054608-log), 683\. [spray_test_json (isSmallFile=false)](https://gist.github.com/HPCCSmoketest/5e380e78837f7b568c707e1ec73c93c8#file-spray_test_json-issmallfile-false-w20190222-054610-log), 681\. [spray_test_json (isSmallFile=true, isUnBallanced=false)](https://gist.github.com/HPCCSmoketest/5e380e78837f7b568c707e1ec73c93c8#file-spray_test_json-issmallfile-true,-isunballanced-false-w20190222-054609-2-log), 682\. [spray_test_json (isSmallFile=true, isUnBallanced=true)](https://gist.github.com/HPCCSmoketest/5e380e78837f7b568c707e1ec73c93c8#file-spray_test_json-issmallfile-true,-isunballanced-true-w20190222-054609-3-log), 

HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   30 sec (00:00:30) |  185 sec (00:03:05) |    0 sec (00:00:00) |    3 sec (00:00:03) |   18 sec (00:00:18) | 1444 sec (00:24:04) |   19 sec (00:00:19) | 1699 sec (00:28:19) |

2019-02-22 16:34 UTC, HPCCSmoketest commented
This PR (12202) is in the 9/11 position of the queue. Estimated start time is after ~4.5 hour(s)

2019-02-22 17:03 UTC, HPCCSmoketest commented
This PR (12202) is in the 8/10 position of the queue. Estimated start time is after ~4.0 hour(s)

2019-02-22 17:33 UTC, HPCCSmoketest commented
This PR (12202) is in the 7/9 position of the queue. Estimated start time is after ~3.5 hour(s)

2019-02-22 18:03 UTC, HPCCSmoketest commented
This PR (12202) is in the 6/8 position of the queue. Estimated start time is after ~3.0 hour(s)

2019-02-22 18:35 UTC, HPCCSmoketest commented
This PR (12202) is in the 5/7 position of the queue. Estimated start time is after ~2.5 hour(s)

2019-02-22 19:04 UTC, HPCCSmoketest commented
This PR (12202) is in the 4/6 position of the queue. Estimated start time is after ~2.0 hour(s)

2019-02-22 19:33 UTC, HPCCSmoketest commented
This PR (12202) is in the 3/5 position of the queue. Estimated start time is after ~1.5 hour(s)

2019-02-22 19:36 UTC, HPCCSmoketest commented
This PR (12202) is in the 2/4 position of the queue. Estimated start time is after ~1.0 hour(s)

2019-02-22 20:05 UTC, HPCCSmoketest commented
This PR (12202) is in the 1/3 position of the queue. Estimated start time is after ~0.5 hour(s)

2019-02-22 20:34 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now. Estimated completion time is ~ 0.5 hour(s)

2019-02-22 21:03 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: bbf2b4734f340f5d0bdd75510e0cb86ff4de5461
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |101 |101 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |819 |819 |0 |
|test (thor) |744 |744 |0 |
|test (roxie) |893 |893 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   37 sec (00:00:37) |  186 sec (00:03:06) |    0 sec (00:00:00) |    2 sec (00:00:02) |   18 sec (00:00:18) | 1459 sec (00:24:19) |   20 sec (00:00:20) | 1722 sec (00:28:42) |

2019-02-25 16:44 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now.
The reason of this test is: New commit.
Estimated completion time is ~0.5 hour(s)

2019-02-25 17:14 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d060f2f33a245c466758cbd962eefe5b613d4975
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |101 |101 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |819 |819 |0 |
|test (thor) |744 |744 |0 |
|test (roxie) |893 |893 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   25 sec (00:00:25) |  190 sec (00:03:10) |    0 sec (00:00:00) |    2 sec (00:00:02) |   18 sec (00:00:18) | 1456 sec (00:24:16) |   19 sec (00:00:19) | 1710 sec (00:28:30) |

2019-03-01 13:11 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now.
The reason of this test is: New commit.
Commit ID: f480c718683f993adff1a738ef63e02e1759bd30
Estimated completion time is ~0.5 hour(s)

2019-03-01 13:13 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: f480c718683f993adff1a738ef63e02e1759bd30
Number of Error(s): 5
/mnt/disk1/home/vamosax/smoketest/PR-12202/HPCC-Platform/system/jlib/jmutex.hpp:996:7: error: use of deleted function \xe2\x80\x98std::atomic<_Tp*>::atomic(const std::atomic<_Tp*>&) [with _Tp = OsDiskInfo]\xe2\x80\x99

[Build error:](https://gist.github.com/724d312cd3a7346674eba59910c8647d)
Build log [Build log](https://gist.github.com/HPCCSmoketest/724d312cd3a7346674eba59910c8647d#file-result-19-03-01-08-18-14-log)

2019-03-01 14:14 UTC, HPCCSmoketest commented
This PR (12202) is in the 1/7 position of the queue. Estimated start time is after ~0.5 hour(s)

2019-03-01 14:45 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now.
The reason of this test is: New commit.
Commit ID: f480c718683f993adff1a738ef63e02e1759bd30
Estimated completion time is ~0.5 hour(s)

2019-03-01 15:14 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: f480c718683f993adff1a738ef63e02e1759bd30
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |104 |104 |0 |0 |0 |34 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |28 sec  (00:00:28) |
|setup (thor) |11 |11 |0 |43 sec  (00:00:43) |
|setup (roxie) |11 |11 |0 |21 sec  (00:00:21) |
|test (hthor) |819 |819 |0 |261 sec  (00:04:21) |
|test (thor) |744 |744 |0 |585 sec  (00:09:45) |
|test (roxie) |893 |893 |0 |348 sec  (00:05:48) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   30 sec (00:00:30) |  194 sec (00:03:14) |    0 sec (00:00:00) |    2 sec (00:00:02) |   18 sec (00:00:18) | 1483 sec (00:24:43) |   18 sec (00:00:18) | 1745 sec (00:29:05) |

2019-04-23 15:28 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now.
The reason of this test is: Base branch changed.
Commit ID: f480c718683f993adff1a738ef63e02e1759bd30
Estimated completion time is ~0.5 hour(s)

2019-04-23 15:29 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: f480c718683f993adff1a738ef63e02e1759bd30
Conflicting files, should skip build and test.

[Build error:](https://gist.github.com/40db01acf2888b361db995f01026dfbb)
Build log [Build log](https://gist.github.com/HPCCSmoketest/40db01acf2888b361db995f01026dfbb#file-result-19-04-23-11-36-19-log)

2019-04-23 16:41 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now.
The reason of this test is: New commit.
Commit ID: b08ffddf8cfe4aa3a24a922546519605c1ae8b2c
Estimated completion time is ~0.5 hour(s)

2019-04-23 17:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: b08ffddf8cfe4aa3a24a922546519605c1ae8b2c
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |34 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |3 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |6 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |29 sec  (00:00:29) |
|setup (thor) |11 |11 |0 |46 sec  (00:00:46) |
|setup (roxie) |11 |11 |0 |19 sec  (00:00:19) |
|test (hthor) |827 |827 |0 |168 sec  (00:02:48) |
|test (thor) |752 |752 |0 |593 sec  (00:09:53) |
|test (roxie) |903 |903 |0 |199 sec  (00:03:19) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   38 sec (00:00:38) |  207 sec (00:03:27) |    0 sec (00:00:00) |    2 sec (00:00:02) |   19 sec (00:00:19) | 1247 sec (00:20:47) |   18 sec (00:00:18) | 1531 sec (00:25:31) |

2019-04-24 08:19 UTC, shamser commented
@jakesmith Please can your review

2019-04-24 09:10 UTC, jakesmith requested changes

2019-04-24 09:10 UTC, jakesmith commented on dali/datest/dfuwutest.cpp
> +        OERRLOG("WUID %s not found", wuid);
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on dali/datest/dfuwutest.cpp
> +        OERRLOG("Logical group %s not found",grpname.str());
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on dali/datest/dfuwutest.cpp
> +            OERRLOG("dataDirectory not specified");
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on dali/datest/floodtest.cpp
> +    OERRLOG("%s",err.str());
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on dali/datest/floodtest.cpp
> +            OERRLOG("Failed to find node in group");
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on dali/datest/floodtest.cpp
> +        OERRLOG("Failed to find node in group");
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on dali/datest/floodtest.cpp
> +                    OERRLOG("Failed to run slave on %d (%s)",idx+1,ips.str());
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on dali/datest/floodtest.cpp
> +        OERRLOG("Cannot find group %s",grpname);
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on dali/daunittest/daunittest.cpp
> +        OERRLOG("%s",s.str());
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on dali/dfu/dfurun.cpp
> +            OWARNLOG("DFURUN: Workunit %s aborted",dfuwuid);
IWARNLOG

2019-04-24 09:10 UTC, jakesmith commented on dali/sasha/packetstore.cpp
> +			DBGLOG("Warning: transaction previously locked (lockRead)");
odd indentation

2019-04-24 09:10 UTC, jakesmith commented on dali/server/daserver.cpp
> +        LOG(MCoperatorInfo, unknownJob, "Build %s", BUILD_TAG);
PROGLOG

2019-04-24 09:10 UTC, jakesmith commented on dali/server/daserver.cpp
> +        DBGLOG("DASERVER[%d] starting - listening to port %d",myrank,queryMyNode()->endpoint().port);
PROGLOG

2019-04-24 09:10 UTC, jakesmith commented on fs/dafilesrv/dafilesrv.cpp
> +                    oERRLOG("%s failed to stop",servicedisplayname);
typo' - won't compile under windows.

OERRLOG

2019-04-24 09:10 UTC, jakesmith commented on fs/dafscontrol/dafscontrol.cpp
> +                OERRLOG("%s: %s not running DAFILESRV",grpip,epstr.str());
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on fs/dafscontrol/dafscontrol.cpp
> +                    OERRLOG("%s: %s %s running DAFILESRV version %s",grpip,(mode==AMstopver)?"was":"is",epstr.str(),attr.text.get());
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on fs/dafscontrol/dafscontrol.cpp
> +                    OERRLOG("%s: %s not running DAFILESRV",grpip,epstr.str());
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on fs/dafscontrol/dafscontrol.cpp
> +                            OERRLOG("Could not stop server on %s, %d returned",epstr.str(),err);
UERRLOG

2019-04-24 09:10 UTC, jakesmith commented on fs/dafscontrol/dafscontrol.cpp
> +            OERRLOG("%s is not a group name or ip",grpip);
UERRLOG

2019-04-24 09:12 UTC, jakesmith commented
@shamser - back to you.

1 general comment - for command line tools (that may be used by an operator) (e.g. daliadmin), the messages that intended to be seen on the CLI should be user, not operator.

2019-04-24 09:52 UTC, shamser commented on dali/base/dasds.cpp
> +                        LOG(MCinternalError, unknownJob, e, "Failed to reply to client (CSDSTransactionServer thread)");
IWARNLOG does not have a version that supports exceptions... I'll have to use LOG(MCinternalWarning,...) for the same purpose.

2019-04-24 09:56 UTC, shamser commented on dali/base/dasds.cpp
> +            LOG(MCinternalError, unknownJob, e, s.str());
LOG(MCinternalError,..) should be the same as IERRLOG but with support for the IException

2019-04-24 10:00 UTC, shamser commented on dali/base/dasds.cpp
> +                LOG(MCinternalError, unknownJob, e, "Exception(1) - Error saving store file");
"LOG(MCoperatorError," is equivalent of OERRLOG but support IException parameter

2019-04-24 10:02 UTC, jakesmith commented on dali/base/dasds.cpp
> +                        LOG(MCinternalError, unknownJob, e, "Failed to reply to client (CSDSTransactionServer thread)");
>IWARNLOG does not have a version that supports exceptions

may be worth introducing one.

2019-04-24 10:03 UTC, jakesmith commented on dali/base/dasds.cpp
> +            LOG(MCinternalError, unknownJob, e, s.str());
I assumed an IERRLOG existed that took a IException.
Feels like there should be one to make usage more consistent.

2019-04-24 10:05 UTC, jakesmith commented on dali/base/dasds.cpp
> +                LOG(MCinternalError, unknownJob, e, "Exception(1) - Error saving store file");
from jlog.hpp: 

>inline IException *OERRLOG(IException *except, const char *prefix=NULL)

already seems to be a OERRLOG that supports an exception

2019-04-24 11:13 UTC, shamser commented on dali/base/dasds.cpp
> +                LOG(MCinternalError, unknownJob, e, "Exception(1) - Error saving store file");
you're right.  I missed that.

2019-04-24 13:43 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now.
The reason of this test is: New commit.
Commit ID: 0fc0564de22cfb615fc5a0f93fcfe005a20e17aa
Estimated completion time is ~0.5 hour(s)

2019-04-24 13:45 UTC, shamser commented on dali/base/dasds.cpp
> +            LOG(MCinternalError, unknownJob, e, s.str());
There is an IERRLOG for IExceptions.  Didn't see that initially.  Changing as suggested.

2019-04-24 14:10 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 0fc0564de22cfb615fc5a0f93fcfe005a20e17aa
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |6 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |30 sec  (00:00:30) |
|setup (thor) |11 |11 |0 |47 sec  (00:00:47) |
|setup (roxie) |11 |11 |0 |18 sec  (00:00:18) |
|test (hthor) |827 |827 |0 |202 sec  (00:03:22) |
|test (thor) |752 |752 |0 |609 sec  (00:10:09) |
|test (roxie) |903 |903 |0 |228 sec  (00:03:48) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   22 sec (00:00:22) |  209 sec (00:03:29) |    0 sec (00:00:00) |    2 sec (00:00:02) |   18 sec (00:00:18) | 1330 sec (00:22:10) |   20 sec (00:00:20) | 1601 sec (00:26:41) |

2019-04-24 14:11 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now.
The reason of this test is: New commit.
Commit ID: 018bc0c16af8ca8e3a38eafecd5ad6cb83d092f1
Estimated completion time is ~0.5 hour(s)

2019-04-24 14:41 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 018bc0c16af8ca8e3a38eafecd5ad6cb83d092f1
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |34 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |6 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |24 sec  (00:00:24) |
|setup (thor) |11 |11 |0 |46 sec  (00:00:46) |
|setup (roxie) |11 |11 |0 |23 sec  (00:00:23) |
|test (hthor) |827 |827 |0 |183 sec  (00:03:03) |
|test (thor) |752 |752 |0 |617 sec  (00:10:17) |
|test (roxie) |903 |903 |0 |410 sec  (00:06:50) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   31 sec (00:00:31) |  212 sec (00:03:32) |    0 sec (00:00:00) |    2 sec (00:00:02) |   19 sec (00:00:19) | 1521 sec (00:25:21) |   19 sec (00:00:19) | 1804 sec (00:30:04) |

2019-04-24 14:52 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now.
The reason of this test is: New commit.
Commit ID: 959aa6bc29542ce467fc8b8de98c0c3864695728
Estimated completion time is ~0.5 hour(s)

2019-04-24 15:08 UTC, shamser commented
@jakesmith That was a lot of changes!  I've modified as suggested.

2019-04-24 15:11 UTC, jakesmith commented on system/jlib/jlog.hpp
> +inline IException *IWARNLOG(IException *except, const char *prefix=NULL)
trivial: nullptr preferable

2019-04-24 15:18 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 959aa6bc29542ce467fc8b8de98c0c3864695728
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |5 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |26 sec  (00:00:26) |
|setup (thor) |11 |11 |0 |46 sec  (00:00:46) |
|setup (roxie) |11 |11 |0 |19 sec  (00:00:19) |
|test (hthor) |827 |827 |0 |162 sec  (00:02:42) |
|test (thor) |752 |752 |0 |611 sec  (00:10:11) |
|test (roxie) |903 |903 |0 |218 sec  (00:03:38) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   36 sec (00:00:36) |  205 sec (00:03:25) |    0 sec (00:00:00) |    3 sec (00:00:03) |   18 sec (00:00:18) | 1276 sec (00:21:16) |   19 sec (00:00:19) | 1557 sec (00:25:57) |

2019-04-24 15:46 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now.
The reason of this test is: New commit.
Commit ID: 6ac54bc5bdad7dcdc8f87f5cc724c57b3e5d4cd7
Estimated completion time is ~0.5 hour(s)

2019-04-24 16:13 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 6ac54bc5bdad7dcdc8f87f5cc724c57b3e5d4cd7
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |34 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |30 sec  (00:00:30) |
|setup (thor) |11 |11 |0 |43 sec  (00:00:43) |
|setup (roxie) |11 |11 |0 |19 sec  (00:00:19) |
|test (hthor) |827 |827 |0 |172 sec  (00:02:52) |
|test (thor) |752 |752 |0 |607 sec  (00:10:07) |
|test (roxie) |903 |903 |0 |214 sec  (00:03:34) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   26 sec (00:00:26) |  206 sec (00:03:26) |    0 sec (00:00:00) |    3 sec (00:00:03) |   18 sec (00:00:18) | 1282 sec (00:21:22) |   19 sec (00:00:19) | 1554 sec (00:25:54) |

2019-04-24 16:14 UTC, jakesmith commented
@shamser - one trivial comment (re. nullptr).
Please squash.

2019-04-25 08:34 UTC, shamser commented
@jakesmith nullptr change implemented and squashed

2019-04-25 09:08 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now.
The reason of this test is: New commit.
Commit ID: 1395c3ea73d808b3dc03feb60cc5fbabbcbc8d6f
Estimated completion time is ~0.5 hour(s)

2019-04-25 09:35 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 1395c3ea73d808b3dc03feb60cc5fbabbcbc8d6f
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |24 sec  (00:00:24) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |20 sec  (00:00:20) |
|test (hthor) |827 |827 |0 |183 sec  (00:03:03) |
|test (thor) |752 |752 |0 |593 sec  (00:09:53) |
|test (roxie) |903 |903 |0 |229 sec  (00:03:49) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   37 sec (00:00:37) |  212 sec (00:03:32) |    0 sec (00:00:00) |    3 sec (00:00:03) |   18 sec (00:00:18) | 1313 sec (00:21:53) |   19 sec (00:00:19) | 1602 sec (00:26:42) |

2019-04-25 09:49 UTC, jakesmith commented on dali/base/dafdesc.cpp
> +                OERRLOG("createFileDescriptorFromRoxie: %s missing part %s",id,xpath.str());
think should be changed to IERRLOG

2019-04-25 09:49 UTC, jakesmith commented on dali/base/dasds.cpp
> +            LOG(MCinternalError, e, "SDS: Error notifying subscriber");
could be IERRLOG

2019-04-25 09:49 UTC, jakesmith commented on dali/base/dasds.cpp
> +            LOG(MCinternalError, unknownJob, e, s.append("writeDelta, failed").str());
could be IERRLOG

2019-04-25 09:49 UTC, jakesmith commented on dali/base/dasds.cpp
> +            LOG(MCoperatorWarning, unknownJob, e, "BackupHandler(async) write operation failed, possible backup data loss");
could be IERRLOG

2019-04-25 09:49 UTC, jakesmith commented on dali/base/dasds.cpp
> +    DBGLOG("-------: stopping SDS server");
Some of this should be PROGLOG so we see something when DBGLOG's are suppressed.
Make this one a PROGLOG.

2019-04-25 09:49 UTC, jakesmith commented on dali/base/dasds.cpp
> +    DBGLOG("-------: restarted");
and this one

2019-04-25 09:49 UTC, jakesmith commented on dali/base/dasds.cpp
> +    LOG(MCinternalError, unknownJob, e, "Caught unhandled exception!");
could be IERRLOG

2019-04-25 09:49 UTC, jakesmith commented on dali/base/dasds.cpp
> +            LOG(MCinternalError, unknownJob, e, "Exception while restarting or shutting down");
could be IERRLOG

2019-04-25 09:49 UTC, jakesmith commented on dali/datest/datest.cpp
> +    DBGLOG("starting QTest %s",testput?"put":"get");
Not sure about any (most) of the changes to DBGLOG in this file.
We prob. want to see datest test tracing even in release, so wouldn't want these to go away if we start suppressing DBGLOG.

Bettter to change them all to either PROGLOG I think.

2019-04-25 09:49 UTC, jakesmith commented on dali/sasha/packetstore.cpp
> +            DBGLOG("Warning: transaction previously locked (lockRead)");
these and others below that were LOG(MCerror, ..
look like they should be IERRLOG

2019-04-25 10:02 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now.
The reason of this test is: New commit.
Commit ID: d88cfd11f79dbdefde1efb84d8f14c83ecd1e543
Estimated completion time is ~0.5 hour(s)

2019-04-25 10:29 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d88cfd11f79dbdefde1efb84d8f14c83ecd1e543
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |33 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |3 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |22 sec  (00:00:22) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |23 sec  (00:00:23) |
|test (hthor) |827 |827 |0 |161 sec  (00:02:41) |
|test (thor) |752 |752 |0 |597 sec  (00:09:57) |
|test (roxie) |903 |903 |0 |213 sec  (00:03:33) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   19 sec (00:00:19) |  214 sec (00:03:34) |    0 sec (00:00:00) |    3 sec (00:00:03) |   18 sec (00:00:18) | 1280 sec (00:21:20) |   20 sec (00:00:20) | 1554 sec (00:25:54) |

2019-04-25 10:54 UTC, shamser commented
@jakesmith Modified as you've suggested.  Shall I squash?

2019-04-25 10:57 UTC, HPCCSmoketest commented
Process of PR-12202, label: issue21518 starts now.
The reason of this test is: New commit.
Commit ID: 31b0b55b3015730988ac1989bb354959b8649f1e
Estimated completion time is ~0.5 hour(s)

2019-04-25 10:58 UTC, jakesmith commented
@shamser - yes please go ahead and squash.

2019-04-25 11:03 UTC, shamser commented
@jakesmith squashed.

2019-04-25 11:24 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 31b0b55b3015730988ac1989bb354959b8649f1e
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |36 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |3 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |28 sec  (00:00:28) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |24 sec  (00:00:24) |
|test (hthor) |827 |827 |0 |185 sec  (00:03:05) |
|test (thor) |752 |752 |0 |593 sec  (00:09:53) |
|test (roxie) |903 |903 |0 |228 sec  (00:03:48) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   27 sec (00:00:27) |  214 sec (00:03:34) |    0 sec (00:00:00) |    3 sec (00:00:03) |   18 sec (00:00:18) | 1323 sec (00:22:03) |   19 sec (00:00:19) | 1604 sec (00:26:44) |

2019-04-25 11:29 UTC, jakesmith commented
@richardkchapman - ready to merge.

2019-04-25 11:35 UTC, merged