HPCC-17821 UI support from ECLWatch
hpcc-systems/HPCC-Platform pull request #12219
Opened 2019-02-25 19:24 UTC by kunalaswani

Create email reporting option for ZAP Reports.

Signed-off-by: Aswani, Kunal <kunal.aswani@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2019-02-25 19:26 UTC, kunalaswani commented
@GordonSmith please review 
JIRA for backend response for sending email: https://track.hpccsystems.com/browse/HPCC-21547

2019-02-25 19:50 UTC, HPCCSmoketest commented
Process of PR-12219, label: HPCC-17821new starts now.
The reason of this test is: Did not build yet.
Estimated completion time is ~0.5 hour(s)

2019-02-25 20:20 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 95482dd5f4822a3356eb26afc922704f00a789a8
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |101 |101 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |819 |819 |0 |
|test (thor) |744 |744 |0 |
|test (roxie) |893 |893 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   25 sec (00:00:25) |  188 sec (00:03:08) |    0 sec (00:00:00) |   61 sec (00:01:01) |   18 sec (00:00:18) | 1448 sec (00:24:08) |   19 sec (00:00:19) | 1759 sec (00:29:19) |

2019-02-26 09:33 UTC, GordonSmith commented
@kunalaswani I am not sure "The commit message title makes sense in a changelog, by itself" is true (might want to mention ZAP in there).

2019-02-26 09:36 UTC, GordonSmith requested changes
Code looks good - just one commented line to remove and I would suggest improving the commit title at the same time.

2019-02-26 09:36 UTC, GordonSmith commented on esp/src/eclwatch/WUDetailsWidget.js
> +                //this._onCancelDialog();
Remove commented code.

2019-02-26 15:51 UTC, kunalaswani commented
@GordonSmith Changes made, please review. this.zapDialog.hide(); was added back into the _onsubmit area. thanks

2019-02-26 16:16 UTC, HPCCSmoketest commented
Process of PR-12219, label: HPCC-17821new starts now.
The reason of this test is: New commit.
Commit ID: e5fa59be2c562353686103c720a817b0633256f0
Estimated completion time is ~0.5 hour(s)

2019-02-26 16:46 UTC, GordonSmith approved these changes
Looks good.

2019-02-26 16:46 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: e5fa59be2c562353686103c720a817b0633256f0
Build: success
Build: success
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |101 |101 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |11 |11 |0 |
|setup (thor) |11 |11 |0 |
|setup (roxie) |11 |11 |0 |
|test (hthor) |819 |819 |0 |
|test (thor) |744 |744 |0 |
|test (roxie) |893 |893 |0 |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   41 sec (00:00:41) |  192 sec (00:03:12) |    0 sec (00:00:00) |   62 sec (00:01:02) |   18 sec (00:00:18) | 1472 sec (00:24:32) |   20 sec (00:00:20) | 1805 sec (00:30:05) |

2019-02-27 14:14 UTC, kunalaswani commented
@richardkchapman ok to merge

2019-02-27 16:23 UTC, richardkchapman commented
We've been round this once before - and coded this option only to reject it. It's too big a security hole to allow arbitrary email targets (selected by the user) for zap reports.

2019-02-27 16:23 UTC, closed without merging