HPCC-21708 Disk usage graphs added to ECL Watch doc
hpcc-systems/HPCC-Platform pull request #12364
Opened 2019-03-27 17:12 UTC by g-pan

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

@JamesDeFabia please review
@miguelvazq optionally review

See fully compiled PDF file for image rendering.
http://10.240.32.243/job/DocDev70/CE=ubuntu-18.04-amd64-1/70/artifact/build-docs/Release/docs/EN_US/The_ECL_Watch_Manual_EN_US-7.2.1-closedown0.pdf

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [x] The component(s) render as expected

## Testing:

Successful end to end unit test built at http://10.240.32.243/job/DocDev70/CE=ubuntu-18.04-amd64-1/

2019-03-27 17:12 UTC, HPCCSmoketest commented
Process of PR-12364, label: H21708-ECLWAct starts now.
The reason of this test is: Did not build yet.
Commit ID: f87c4f69f417e78fd24ad01c57a507b17db9f4c4
Estimated completion time is ~0.5 hour(s)

2019-03-27 17:44 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: f87c4f69f417e78fd24ad01c57a507b17db9f4c4
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |105 |104 |0 |0 |1 |135 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Unittest error(s):
```
ConfigMgr 2.0 - Load and Parse - Verifying configuration XSDs are compliant...
*** ConfigMgr 2.0 - Templates - Loading Only ***
*** ConfigMgr 2.0 - Templates - Inputs ***
*** ConfigMgr 2.0 - Templates - Variable substitution tests ***
*** ConfigMgr 2.0 - Templates - Execute Templates ***
*** ConfigMgr 2.0 - Templates - Find Node Tests ***
*** ConfigMgr 2.0 - Templates - Create Node Tests ***

```

Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |26 sec  (00:00:26) |
|setup (thor) |11 |11 |0 |43 sec  (00:00:43) |
|setup (roxie) |11 |11 |0 |17 sec  (00:00:17) |
|test (hthor) |821 |821 |0 |172 sec  (00:02:52) |
|test (thor) |746 |746 |0 |638 sec  (00:10:38) |
|test (roxie) |895 |895 |0 |216 sec  (00:03:36) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   21 sec (00:00:21) |  369 sec (00:06:09) |    0 sec (00:00:00) |   30 sec (00:00:30) |   18 sec (00:00:18) | 1411 sec (00:23:31) |   19 sec (00:00:19) | 1868 sec (00:31:08) |

2019-03-27 20:20 UTC, JamesDeFabia requested changes
Two comments inline

2019-03-27 20:20 UTC, JamesDeFabia commented on docs/EN_US/ECLWatch/TheECLWatchMan.xml
> +        along the top where some graphs provide a glimpse of usage activity on
The Cluster Activity page displays an informative graphic bar along the top where some graphs provide a glimpse of usage activity on the clusters.
s/b
The Cluster Activity page displays graphs along the top showing cluster disk usage.

2019-03-27 20:20 UTC, JamesDeFabia commented on docs/EN_US/ECLWatch/TheECLWatchMan.xml
> +        information about the individual disk usage activity. </para>
brings up s/b displays

2019-03-28 19:28 UTC, HPCCSmoketest commented
Process of PR-12364, label: H21708-ECLWAct starts now.
The reason of this test is: New commit.
Commit ID: 417d13c0e333f329038993d46811b5e06dc88d57
Estimated completion time is ~0.5 hour(s)

2019-03-28 19:57 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 417d13c0e333f329038993d46811b5e06dc88d57
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |25 sec  (00:00:25) |
|setup (thor) |11 |11 |0 |42 sec  (00:00:42) |
|setup (roxie) |11 |11 |0 |22 sec  (00:00:22) |
|test (hthor) |821 |821 |0 |141 sec  (00:02:21) |
|test (thor) |746 |746 |0 |623 sec  (00:10:23) |
|test (roxie) |895 |895 |0 |213 sec  (00:03:33) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   35 sec (00:00:35) |  355 sec (00:05:55) |    0 sec (00:00:00) |   27 sec (00:00:27) |   17 sec (00:00:17) | 1263 sec (00:21:03) |   20 sec (00:00:20) | 1717 sec (00:28:37) |

2019-04-02 18:52 UTC, g-pan commented
@JamesDeFabia please review revisions.

2019-04-02 19:05 UTC, JamesDeFabia approved these changes
Looks good from my POV

2019-04-03 10:40 UTC, richardkchapman commented
@miguelvazq Any comments?

2019-04-03 15:33 UTC, miguelvazq commented
Looks good to me after revision.

2019-04-03 15:38 UTC, merged