HPCC-21702 New Zap options added to ECL Watch doc
hpcc-systems/HPCC-Platform pull request #12368
Opened 2019-03-28 19:26 UTC by g-pan

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

@JamesDeFabia please review
@kunalaswani FYI, optionally review

View compiled PDF at http://10.240.32.243/view/Docs%207.0/job/AnotherDocBuild7

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

View Successful Build TEST at http://10.240.32.243/view/Docs%207.0/job/AnotherDocBuild7

2019-03-28 19:28 UTC, HPCCSmoketest commented
This PR (12368) is in the 1/1 position of the queue. Estimated start time is after ~0.5 hour(s)

2019-03-28 19:57 UTC, HPCCSmoketest commented
Process of PR-12368, label: H21702-ZapR starts now.
The reason of this test is: Did not build yet.
Commit ID: 9b9e77b35ff0a07824bd5d30a6f4dec61ef28d76
Estimated completion time is ~0.5 hour(s)

2019-03-28 20:55 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 9b9e77b35ff0a07824bd5d30a6f4dec61ef28d76
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |22 sec  (00:00:22) |
|setup (thor) |11 |11 |0 |42 sec  (00:00:42) |
|setup (roxie) |11 |11 |0 |16 sec  (00:00:16) |
|test (hthor) |821 |821 |0 |151 sec  (00:02:31) |
|test (thor) |746 |746 |0 |617 sec  (00:10:17) |
|test (roxie) |895 |894 |1 |1901 sec  (00:31:41) |


[Errors:](https://gist.github.com/af885f1c5b66bf2c183fa969d9f64cba)
- test
  - roxie
    - 604\. [schedule2](https://gist.github.com/HPCCSmoketest/af885f1c5b66bf2c183fa969d9f64cba#file-schedule2-w20190328-163158-1-log), 

HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   42 sec (00:00:42) |  356 sec (00:05:56) |    0 sec (00:00:00) |   29 sec (00:00:29) |   19 sec (00:00:19) | 2969 sec (00:49:29) |   16 sec (00:00:16) | 3431 sec (00:57:11) |

2019-04-03 11:59 UTC, HPCCSmoketest commented
Process of PR-12368, label: H21702-ZapR starts now.
The reason of this test is: Forced to re-test.
Commit ID: 9b9e77b35ff0a07824bd5d30a6f4dec61ef28d76
Estimated completion time is ~0.5 hour(s)

2019-04-03 12:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 9b9e77b35ff0a07824bd5d30a6f4dec61ef28d76
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   41 sec (00:00:41) |  353 sec (00:05:53) |    0 sec (00:00:00) |   27 sec (00:00:27) |   19 sec (00:00:19) |    0 sec (00:00:00) |   14 sec (00:00:14) |  454 sec (00:07:34) |

2019-04-16 12:35 UTC, JamesDeFabia requested changes
We should discuss what to do with sensitive info BEFORE the step that says "Press the Apply button." 

Something along the lines of:
If your ZAP package might contain sensitive information, use the utility to create a package, then sanitize it, and send manually. 
If it doesn't then you can use the email feature to send automatically.

2019-04-16 12:35 UTC, JamesDeFabia commented on docs/EN_US/ECLWatch/ECLWa_mods/ECLWatchSrc.xml
> +          configuration manager, but can be changed if desired. The Email
Configuration Manager (s/b title case)

2019-04-16 12:37 UTC, JamesDeFabia commented
@g-pan back to you

2019-04-16 18:58 UTC, g-pan commented
@JamesDeFabia Revised and Rebased. Please Review.

2019-04-16 18:58 UTC, HPCCSmoketest commented
Process of PR-12368, label: H21702-ZapR starts now.
The reason of this test is: New commit.
Commit ID: a5eddae69a0da395c68858da3147933e0bae71eb
Estimated completion time is ~0.1 hour(s)

2019-04-16 19:06 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: a5eddae69a0da395c68858da3147933e0bae71eb
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   34 sec (00:00:34) |  363 sec (00:06:03) |    0 sec (00:00:00) |   27 sec (00:00:27) |   20 sec (00:00:20) |    0 sec (00:00:00) |   14 sec (00:00:14) |  458 sec (00:07:38) |

2019-04-17 14:43 UTC, HPCCSmoketest commented
Process of PR-12368, label: H21702-ZapR starts now.
The reason of this test is: New commit.
Commit ID: 5aa1bc0c5c3d1ed9bad55bb15ff1ba8a25e2f1ba
Estimated completion time is ~0.1 hour(s)

2019-04-17 14:43 UTC, g-pan commented
@JamesDeFabia Revised and Rebased.

2019-04-17 14:51 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 5aa1bc0c5c3d1ed9bad55bb15ff1ba8a25e2f1ba
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   40 sec (00:00:40) |  359 sec (00:05:59) |    0 sec (00:00:00) |   27 sec (00:00:27) |   18 sec (00:00:18) |    0 sec (00:00:00) |   14 sec (00:00:14) |  458 sec (00:07:38) |

2019-04-17 14:57 UTC, HPCCSmoketest commented
Process of PR-12368, label: H21702-ZapR starts now.
The reason of this test is: New commit.
Commit ID: c1340b6eec4cf454c226e9c2d7a8dda2d2524893
Estimated completion time is ~0.1 hour(s)

2019-04-17 15:05 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: c1340b6eec4cf454c226e9c2d7a8dda2d2524893
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   35 sec (00:00:35) |  360 sec (00:06:00) |    0 sec (00:00:00) |   27 sec (00:00:27) |   18 sec (00:00:18) |    0 sec (00:00:00) |   14 sec (00:00:14) |  454 sec (00:07:34) |

2019-04-17 15:39 UTC, HPCCSmoketest commented
Process of PR-12368, label: H21702-ZapR starts now.
The reason of this test is: New commit.
Commit ID: cd83d0949ef0c38758bb4b6ab426c9594fbaabb4
Estimated completion time is ~0.1 hour(s)

2019-04-17 15:47 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: cd83d0949ef0c38758bb4b6ab426c9594fbaabb4
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   30 sec (00:00:30) |  361 sec (00:06:01) |    0 sec (00:00:00) |   28 sec (00:00:28) |   19 sec (00:00:19) |    0 sec (00:00:00) |   15 sec (00:00:15) |  453 sec (00:07:33) |

2019-04-17 20:04 UTC, HPCCSmoketest commented
Process of PR-12368, label: H21702-ZapR starts now.
The reason of this test is: New commit.
Commit ID: 5ac7e328b7545cda54d25720fb554bc07bbabf10
Estimated completion time is ~0.1 hour(s)

2019-04-17 20:11 UTC, JamesDeFabia requested changes
only one minor comment inline

2019-04-17 20:11 UTC, JamesDeFabia commented on docs/EN_US/ECLWatch/ECLWa_mods/ECLWatchSrc.xml
> +          all the dialog fields are filled. At that point if you checked the
...all the dialog fields are filled. Should be ...all the dialog fields are completed. (or filled in.)

2019-04-17 20:12 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 5ac7e328b7545cda54d25720fb554bc07bbabf10
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   36 sec (00:00:36) |  355 sec (00:05:55) |    0 sec (00:00:00) |   27 sec (00:00:27) |   18 sec (00:00:18) |    0 sec (00:00:00) |   15 sec (00:00:15) |  451 sec (00:07:31) |

2019-04-18 13:05 UTC, JamesDeFabia approved these changes
Ok to merge

2019-04-18 13:09 UTC, merged