HPCC-21829 Added HU Translations
hpcc-systems/HPCC-Platform pull request #12399
Opened 2019-04-04 16:16 UTC by kunalaswani

Added Hungarian translations for 7.2.x

Signed-off-by: Aswani, Kunal <kunal.aswani@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

2019-04-04 16:17 UTC, kunalaswani commented
@AttilaVamos please review

2019-04-04 16:37 UTC, HPCCSmoketest commented
This PR (12399) is in the 1/2 position of the queue. Estimated start time is after ~0.5 hour(s)

2019-04-04 17:08 UTC, HPCCSmoketest commented
Process of PR-12399, label: HPCC-21829 starts now.
The reason of this test is: Did not build yet.
Commit ID: 1f6a845895259a267ea215417fccaf2e9e65b5cf
Estimated completion time is ~0.5 hour(s)

2019-04-04 17:14 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 1f6a845895259a267ea215417fccaf2e9e65b5cf
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   42 sec (00:00:42) |  210 sec (00:03:30) |    0 sec (00:00:00) |   48 sec (00:00:48) |   19 sec (00:00:19) |    0 sec (00:00:00) |   15 sec (00:00:15) |  334 sec (00:05:34) |

2019-04-04 22:00 UTC, AttilaVamos requested changes
@kunalaswani It seems right, but there are some extra leading/trailing spaces

2019-04-04 22:00 UTC, AttilaVamos commented on esp/src/eclwatch/nls/hu/hpcc.js
> +    ComputerUpTime: " A számítógép újraindítása óta eltelt idő ",
Extra leading and trailing space

2019-04-04 22:00 UTC, AttilaVamos commented on esp/src/eclwatch/nls/hu/hpcc.js
> +    Copied: " Lemásolva ",
Extra leading/trailing spaces in some new lines

2019-04-08 19:49 UTC, kunalaswani commented
@AttilaVamos please review, spaces removed.

2019-04-08 20:10 UTC, HPCCSmoketest commented
Process of PR-12399, label: HPCC-21829 starts now.
The reason of this test is: Forced to re-test.
Commit ID: c7c233627d11682ed0641d35106950a790fdd05c
Estimated completion time is ~0.5 hour(s)

2019-04-08 20:16 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: c7c233627d11682ed0641d35106950a790fdd05c
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   37 sec (00:00:37) |  209 sec (00:03:29) |    0 sec (00:00:00) |   57 sec (00:00:57) |   19 sec (00:00:19) |    0 sec (00:00:00) |   15 sec (00:00:15) |  337 sec (00:05:37) |

2019-04-08 20:42 UTC, AttilaVamos approved these changes
@kunalaswani It is good.

2019-04-09 06:59 UTC, merged