HPCC-21929 Use QueryID in control:queries call if available
hpcc-systems/HPCC-Platform pull request #12450
Opened 2019-04-12 20:15 UTC by wangkx

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2019-04-12 20:15 UTC, wangkx commented
@afishbeck please review.

2019-04-12 20:22 UTC, HPCCSmoketest commented
Process of PR-12450, label: h21929 starts now.
The reason of this test is: Did not build yet.
Commit ID: 1b5042c86ed016004bf2a3c26c5bbf2c24b3b758
Estimated completion time is ~0.5 hour(s)

2019-04-12 20:49 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 1b5042c86ed016004bf2a3c26c5bbf2c24b3b758
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |3 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |27 sec  (00:00:27) |
|setup (thor) |11 |11 |0 |46 sec  (00:00:46) |
|setup (roxie) |11 |11 |0 |19 sec  (00:00:19) |
|test (hthor) |825 |825 |0 |198 sec  (00:03:18) |
|test (thor) |750 |750 |0 |595 sec  (00:09:55) |
|test (roxie) |901 |901 |0 |222 sec  (00:03:42) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   36 sec (00:00:36) |  212 sec (00:03:32) |    0 sec (00:00:00) |    2 sec (00:00:02) |   17 sec (00:00:17) | 1306 sec (00:21:46) |   19 sec (00:00:19) | 1592 sec (00:26:32) |

2019-04-16 21:31 UTC, afishbeck commented on esp/services/ws_workunits/ws_workunitsQuerySets.cpp
> +            for (unsigned i=0; i<queryIDs.ordinality(); i++)
There is a macro for this: "ForEachItemIn(i, queryIDs)"

2019-04-16 21:35 UTC, afishbeck commented on esp/services/ws_workunits/ws_workunitsQuerySets.cpp
> +IPropertyTree* getQueriesOnCluster(const char *target, const char *queryset, StringArray &queryIDs, bool checkAllNodes)
Up to you, but if you make this "StringArray *queryIDs" then where you define emptyIDs below you could just use nullptr instead... and when you define queryIDs bellow you can pass by address "&queryIDs".

2019-04-16 21:35 UTC, afishbeck reviewed
@wangkx a couple trivial comments.

2019-04-17 13:25 UTC, wangkx commented
@afishbeck please review my changes.

2019-04-17 13:30 UTC, HPCCSmoketest commented
Process of PR-12450, label: h21929 starts now.
The reason of this test is: New commit.
Commit ID: 5188d442013413b6e6a31acb850c0ffc5069c37a
Estimated completion time is ~0.5 hour(s)

2019-04-17 13:57 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 5188d442013413b6e6a31acb850c0ffc5069c37a
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |3 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |6 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |29 sec  (00:00:29) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |28 sec  (00:00:28) |
|test (hthor) |825 |825 |0 |161 sec  (00:02:41) |
|test (thor) |750 |750 |0 |617 sec  (00:10:17) |
|test (roxie) |901 |901 |0 |218 sec  (00:03:38) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   28 sec (00:00:28) |  214 sec (00:03:34) |    0 sec (00:00:00) |    2 sec (00:00:02) |   18 sec (00:00:18) | 1294 sec (00:21:34) |   20 sec (00:00:20) | 1576 sec (00:26:16) |

2019-04-17 14:09 UTC, afishbeck commented on esp/services/ws_workunits/ws_workunitsQuerySets.cpp
> +        if (!queryIDs)
I'd think !queryIDs or queryIDs->ordinality()==0 to make it easiest for callers.

2019-04-17 14:09 UTC, afishbeck requested changes
@wangkx one minor change.

2019-04-17 15:08 UTC, HPCCSmoketest commented
Process of PR-12450, label: h21929 starts now.
The reason of this test is: New commit.
Commit ID: 580e94a26e98726597c0430910a8ad6ded4f60bb
Estimated completion time is ~0.5 hour(s)

2019-04-17 15:09 UTC, wangkx commented
@afishbeck please review again.

2019-04-17 15:38 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 580e94a26e98726597c0430910a8ad6ded4f60bb
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |34 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |26 sec  (00:00:26) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |18 sec  (00:00:18) |
|test (hthor) |825 |825 |0 |167 sec  (00:02:47) |
|test (thor) |750 |750 |0 |601 sec  (00:10:01) |
|test (roxie) |901 |901 |0 |409 sec  (00:06:49) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   28 sec (00:00:28) |  213 sec (00:03:33) |    0 sec (00:00:00) |    2 sec (00:00:02) |   19 sec (00:00:19) | 1482 sec (00:24:42) |   18 sec (00:00:18) | 1762 sec (00:29:22) |

2019-04-17 15:51 UTC, afishbeck approved these changes
@wangkx looks good.

2019-04-17 16:57 UTC, HPCCSmoketest commented
Process of PR-12450, label: h21929 starts now.
The reason of this test is: New commit.
Commit ID: 9302cf4797a03bbc197c56527618ca5be39e8b9e
Estimated completion time is ~0.5 hour(s)

2019-04-17 17:26 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 9302cf4797a03bbc197c56527618ca5be39e8b9e
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |111 |111 |0 |0 |0 |34 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |8 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |26 sec  (00:00:26) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |16 sec  (00:00:16) |
|test (hthor) |825 |825 |0 |169 sec  (00:02:49) |
|test (thor) |750 |750 |0 |589 sec  (00:09:49) |
|test (roxie) |901 |901 |0 |408 sec  (00:06:48) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   30 sec (00:00:30) |  216 sec (00:03:36) |    0 sec (00:00:00) |    3 sec (00:00:03) |   18 sec (00:00:18) | 1449 sec (00:24:09) |   19 sec (00:00:19) | 1735 sec (00:28:55) |

2019-04-17 17:34 UTC, wangkx commented
@richardkchapman this PR is ready to be merged.

2019-04-18 07:19 UTC, merged