HPCC-21950 Document Logical File Copy Expire in (days) option
hpcc-systems/HPCC-Platform pull request #12508
Opened 2019-05-01 15:48 UTC by g-pan

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

@JamesDeFabia please review
@miguelvazq please review (optional) 
@kunalaswani optionally review

Please Review compiled documentation http://10.240.32.243/view/Docs%207.0/job/DocDevII/
See the ECL Watch Manual (Find: Expire in (days))

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Successful Build tests
http://10.240.32.243/view/Docs%207.0/job/DocDevII/

2019-05-01 15:52 UTC, HPCCSmoketest commented
Process of PR-12508, label: H21950-EExp starts now.
The reason of this test is: Did not build yet.
Commit ID: bf972bcbfe8f90367fd2c886b4a9844bdfae2e19
Estimated completion time is ~0.1 hour(s)

2019-05-01 16:00 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: bf972bcbfe8f90367fd2c886b4a9844bdfae2e19
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   32 sec (00:00:32) |  354 sec (00:05:54) |    0 sec (00:00:00) |   26 sec (00:00:26) |   18 sec (00:00:18) |    0 sec (00:00:00) |   14 sec (00:00:14) |  444 sec (00:07:24) |

2019-05-01 16:31 UTC, JamesDeFabia requested changes
see inline comments

2019-05-01 16:31 UTC, JamesDeFabia commented on docs/EN_US/ECLWatch/ECLWa_mods/ECLWatchSrc.xml
> +          <!--Now this here would be a really good spot to XInclude a dynamically built options table-->
remove this comment, if you want to do this, create a Jira

2019-05-01 16:31 UTC, JamesDeFabia commented on docs/EN_US/ECLWatch/ECLWa_mods/ECLWatchSrc.xml
> +                automatically removing the file from the queue. If omitted,
queue? it removes the file. Look at the other instances of this text in the manual. They should all be the same. Also, the presentation/format is different than the others. Look at Spray Fixed, for example, on page 80

2019-05-01 17:53 UTC, HPCCSmoketest commented
Process of PR-12508, label: H21950-EExp starts now.
The reason of this test is: New commit.
Commit ID: 92b17e3a6a1e6b29f915e52708557cb74fa965a5
Estimated completion time is ~0.1 hour(s)

2019-05-01 17:55 UTC, JamesDeFabia approved these changes
ok from my POV

2019-05-01 18:01 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 92b17e3a6a1e6b29f915e52708557cb74fa965a5
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   33 sec (00:00:33) |  355 sec (00:05:55) |    0 sec (00:00:00) |   29 sec (00:00:29) |   19 sec (00:00:19) |    0 sec (00:00:00) |   14 sec (00:00:14) |  450 sec (00:07:30) |

2019-05-01 18:26 UTC, miguelvazq commented
Automatically removing the file from where if its in the process of a copy?

2019-05-01 19:56 UTC, JamesDeFabia commented
> @miguelvazq  said:
> Automatically removing the file from where if it is in the process of a copy?

Expiring does not remove it from the copy process. The copy process is brief, it should NEVER take days :) 
Setting an expiration date on a file removes it from the Distributed File System (both physical file and logical file definition) upon expiration. The Expires in (Days) setting adds the expiration date during the copy process.

2019-05-02 15:07 UTC, miguelvazq commented
Looks good.

2019-05-02 15:13 UTC, JamesDeFabia commented
@richardkchapman This is good to merge now

2019-05-07 08:23 UTC, merged