HPCC-22003 Implement Portuguese Doc Build
hpcc-systems/HPCC-Platform pull request #12514
Opened 2019-05-03 15:39 UTC by g-pan

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

@JamesDeFabia please review
@xwang2713 please review (optional) 
@richardkchapman  please back merge this change into candidate-7.0.x as well. 

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Required additional CMake parameter - added on integration server (Jenkins) 
Tested and successful build can be reviewed : http://10.240.32.243/job/PT_BR_Build1/

2019-05-03 15:47 UTC, HPCCSmoketest commented
Process of PR-12514, label: PTBR_Build2 starts now.
The reason of this test is: Did not build yet.
Commit ID: ed6a60e85ab6de5ebfffefeff84f1da7d6f801f5
Estimated completion time is ~0.1 hour(s)

2019-05-03 15:54 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: ed6a60e85ab6de5ebfffefeff84f1da7d6f801f5
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   32 sec (00:00:32) |  356 sec (00:05:56) |    0 sec (00:00:00) |   29 sec (00:00:29) |   19 sec (00:00:19) |    0 sec (00:00:00) |   14 sec (00:00:14) |  450 sec (00:07:30) |

2019-05-03 16:48 UTC, JamesDeFabia requested changes
Looking at the output results: Only some of the filenames have the PT_BR portion included.

2019-05-06 14:22 UTC, HPCCSmoketest commented
Process of PR-12514, label: PTBR_Build2 starts now.
The reason of this test is: New commit.
Commit ID: f2f88f179bb6c3b583bf4c4df8f4dd6e2cd490af
Estimated completion time is ~0.1 hour(s)

2019-05-06 14:30 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: f2f88f179bb6c3b583bf4c4df8f4dd6e2cd490af
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   32 sec (00:00:32) |  354 sec (00:05:54) |    0 sec (00:00:00) |   27 sec (00:00:27) |   17 sec (00:00:17) |    0 sec (00:00:00) |   15 sec (00:00:15) |  445 sec (00:07:25) |

2019-05-06 14:40 UTC, g-pan commented
@JamesDeFabia good catch, please review build from clean workspace 
http://10.240.32.243/job/PTBR-build2/

2019-05-06 19:42 UTC, HPCCSmoketest commented
Process of PR-12514, label: PTBR_Build2 starts now.
The reason of this test is: New commit.
Commit ID: d3d65c97eb0e5c2ac811b9f0c28e576ddfb58284
Estimated completion time is ~0.1 hour(s)

2019-05-06 19:50 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d3d65c97eb0e5c2ac811b9f0c28e576ddfb58284
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   34 sec (00:00:34) |  357 sec (00:05:57) |    0 sec (00:00:00) |   28 sec (00:00:28) |   20 sec (00:00:20) |    0 sec (00:00:00) |   13 sec (00:00:13) |  452 sec (00:07:32) |

2019-05-07 08:13 UTC, richardkchapman commented
@g-pan If you want the change in 7.0.x, please target candidate-7.0.x in your pull request

2019-05-09 13:15 UTC, closed without merging