HPCC-22003 Implement Portuguese Doc Build
hpcc-systems/HPCC-Platform pull request #12533
Opened 2019-05-09 15:02 UTC by g-pan

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>
@JamesDeFabia please review
NOTE: This is same as PR # 12469 only targets candidate-7.0.x

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Successful Build Test: http://10.240.32.243/view/Docs%207.0/job/PT_BR_Build1/

2019-05-09 15:03 UTC, HPCCSmoketest commented
Process of PR-12533, label: H22003-BrBuild starts now.
The reason of this test is: Did not build yet.
Commit ID: 1e2dd2176064b630be7a8f305af06d9bca9f0390
Estimated completion time is ~0.1 hour(s)

2019-05-09 15:11 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 1e2dd2176064b630be7a8f305af06d9bca9f0390
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   28 sec (00:00:28) |  352 sec (00:05:52) |    0 sec (00:00:00) |   26 sec (00:00:26) |   20 sec (00:00:20) |    0 sec (00:00:00) |   14 sec (00:00:14) |  440 sec (00:07:20) |

2019-05-09 18:00 UTC, JamesDeFabia requested changes
I reviewed the output and they look great! 
Only one minor thing, the cmake.txt files under PT_BR are new and the copyright line has various dates such as:
HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®
I think they should all say 2019

2019-05-09 20:22 UTC, HPCCSmoketest commented
Process of PR-12533, label: H22003-BrBuild starts now.
The reason of this test is: New commit.
Commit ID: c1512195f88327f86e328f7f146a9ea0ed07246f
Estimated completion time is ~0.1 hour(s)

2019-05-09 20:24 UTC, g-pan commented
@JamesDeFabia back to you

2019-05-09 20:30 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: c1512195f88327f86e328f7f146a9ea0ed07246f
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   34 sec (00:00:34) |  353 sec (00:05:53) |    0 sec (00:00:00) |   29 sec (00:00:29) |   20 sec (00:00:20) |    0 sec (00:00:00) |   14 sec (00:00:14) |  450 sec (00:07:30) |

2019-05-10 14:35 UTC, JamesDeFabia requested changes
Still some (c) date inconsistencies

2019-05-10 14:35 UTC, JamesDeFabia commented on docs/PT_BR/ECLScheduler/CMakeLists.txt
> +#    HPCC SYSTEMS software Copyright (C) 2018 HPCC Systems®.
Why 2018?

2019-05-10 14:35 UTC, JamesDeFabia commented on docs/PT_BR/CMakeLists.txt
> +#    HPCC SYSTEMS software Copyright (C) 2018 HPCC Systems®.
Why 2018?

2019-05-10 14:35 UTC, JamesDeFabia commented on docs/PT_BR/HPCCCertify/CMakeLists.txt
> +#    HPCC SYSTEMS software Copyright (C) 2018 HPCC Systems®.
Why 2018?

2019-05-13 11:40 UTC, JamesDeFabia requested changes
@g-pan two dates missed

2019-05-14 21:29 UTC, HPCCSmoketest commented
Process of PR-12533, label: H22003-BrBuild starts now.
The reason of this test is: New commit.
Commit ID: 90c91c2f6713842deab60c701c3d6abf7648e4d6
Estimated completion time is ~0.1 hour(s)

2019-05-14 21:37 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 90c91c2f6713842deab60c701c3d6abf7648e4d6
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   28 sec (00:00:28) |  349 sec (00:05:49) |    0 sec (00:00:00) |   27 sec (00:00:27) |   19 sec (00:00:19) |    0 sec (00:00:00) |   15 sec (00:00:15) |  438 sec (00:07:18) |

2019-05-15 19:00 UTC, g-pan commented
@JamesDeFabia good to merge?

2019-05-15 19:22 UTC, JamesDeFabia approved these changes
@richardkchapman this is now good to merge

2019-05-16 07:51 UTC, merged