HPCC-21867 HPCC Administrator Group
hpcc-systems/HPCC-Platform pull request #12581
Opened 2019-05-22 14:39 UTC by g-pan

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>
View in compiled PDF http://10.240.32.243/job/DocDev70-1/CE=ubuntu-14.04-amd64-1/47/artifact/build-docs/Release/docs/EN_US/ConfiguringHPCC_EN_US-7.2.15-closedown0.pdf#page=65
and see also Installing and Running and System Administrators docs. 
@JamesDeFabia please review
@RussWhitehead please review

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Successful unit testing: http://10.240.32.243/job/DocDev70-1/
 Doc Changes in Configuration manager, Installing and Running, and System Administrators guide

2019-05-22 14:46 UTC, HPCCSmoketest commented
Process of PR-12581, label: H21867-admGp starts now.
The reason of this test is: Did not build yet.
Commit ID: 50067ec9fa7944027ef155a4c89aef769dd997cb
Estimated completion time is ~0.1 hour(s)

2019-05-22 14:54 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 50067ec9fa7944027ef155a4c89aef769dd997cb
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK

2019-05-22 15:05 UTC, RussWhitehead requested changes

2019-05-22 15:05 UTC, RussWhitehead commented on docs/EN_US/ConfiguringHPCC/ConfiguringHPCC.xml
> +          having rights to perform other system level administrative
other LDAP administrative functions.

2019-05-22 15:05 UTC, RussWhitehead commented on docs/EN_US/ConfiguringHPCC/ConfiguringHPCC.xml
> +                <para>Save and Deploy the new configuration file, then restart
...restart ESP...

2019-05-22 15:30 UTC, JamesDeFabia requested changes
In addition to Russ Whitehead's comments, please make sure to use the apostrophe consistently.

2019-05-22 19:09 UTC, g-pan commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/UserSecurityMaint.xml
> +        role="bold">Administrators</emphasis> group.</para>
See step 4. little further down the page.

2019-05-22 19:17 UTC, g-pan commented
@RussWhitehead please note changes to UserSecurityMain.xml file differ from suggested
and please review
@JamesDeFabia please review

2019-05-22 19:25 UTC, JamesDeFabia approved these changes
Looks good to me now, but @RussWhitehead should have the last word

2019-05-22 19:39 UTC, HPCCSmoketest commented
Process of PR-12581, label: H21867-admGp starts now.
The reason of this test is: New commit.
Commit ID: 9c1295f52f8f7b9f5b8371ca30f690b3758855cb
Estimated completion time is ~0.1 hour(s)

2019-05-22 19:47 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 9c1295f52f8f7b9f5b8371ca30f690b3758855cb
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK

2019-05-22 20:18 UTC, RussWhitehead requested changes

2019-05-22 20:18 UTC, RussWhitehead commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/UserSecurityMaint.xml
> +                    vary. It is a configurable value defined as the the value
the the

2019-05-22 20:18 UTC, RussWhitehead commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/hpcc_ldap.xml
> +      <para>Remember that the initldap utility leverages an LDAP
initldap does not create the admin group, so you can remove these 4 lines

2019-05-22 20:42 UTC, g-pan commented
revised and rebased. @RussWhitehead please review

2019-05-22 20:42 UTC, HPCCSmoketest commented
Process of PR-12581, label: H21867-admGp starts now.
The reason of this test is: New commit.
Commit ID: d555dfc141adcc1771faac03740d2973626fba18
Estimated completion time is ~0.1 hour(s)

2019-05-22 20:44 UTC, RussWhitehead approved these changes
@g-pan Looks good to go

2019-05-22 20:49 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.4.1708 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: d555dfc141adcc1771faac03740d2973626fba18
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK

2019-05-23 12:04 UTC, JamesDeFabia commented
@richardkchapman This should be good to merge now. Also please look at the Jira because Jirabot added the Pull Request but did not set it to Merge Pending.

2019-06-03 13:04 UTC, merged