HPCC-22150 Document Std.File functions DFUServerQueue option
hpcc-systems/HPCC-Platform pull request #12781
Opened 2019-07-12 19:28 UTC by JamesDeFabia

Signed-off-by: Jim DeFabia <jamesdefabia@lexisnexis.com>
@AttilaVamos Please review (there is a link to the PDF below)

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

http://10.240.32.243/view/Docs%207.0/job/JimDocBuild7/CE=ubuntu-18.04-amd64-1/lastSuccessfulBuild/artifact/build-docs/Release/docs/EN_US/ECLStandardLibraryReference_EN_US-7.4.1-closedown0.pdf#page=62

2019-07-12 19:29 UTC, HPCCSmoketest commented
Process of PR-12781, label: HPCC-22150dfuServerQueue starts now.
The reason of this test is: Did not build yet.
Commit ID: 73b08870469ff5d9babcc7fa176a1167eec2fce9
Estimated completion time is ~0.1 hour(s)

2019-07-12 19:37 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 73b08870469ff5d9babcc7fa176a1167eec2fce9
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   27 sec (00:00:27) |  389 sec (00:06:29) |    0 sec (00:00:00) |   27 sec (00:00:27) |   18 sec (00:00:18) |    0 sec (00:00:00) |   14 sec (00:00:14) |  475 sec (00:07:55) |

2019-07-17 09:24 UTC, AttilaVamos requested changes
@JamesDeFabia back to you.

2019-07-17 09:24 UTC, AttilaVamos commented on docs/EN_US/ECLStandardLibraryReference/SLR-Mods/SprayVariable.xml
> +          <entry>Name of target DFU Server queue. Default is ' ' (blank) for
Same as above

2019-07-17 09:24 UTC, AttilaVamos commented on docs/EN_US/ECLStandardLibraryReference/SLR-Mods/SprayXML.xml
> +          <entry>Name of target DFU Server queue. Default is ' ' (blank) for
Same as above.

2019-07-17 09:24 UTC, AttilaVamos commented on docs/EN_US/ECLStandardLibraryReference/SLR-Mods/SprayFixed.xml
> +          <entry>Name of target DFU Server queue. Default is ' ' (blank) for
By the source code:
```
const char * dfuServerQueue=nullptr
```
it is empty '' rater than ' ' (blank)

2019-07-17 09:27 UTC, AttilaVamos commented
@JamesDeFabia it seems the sequence of my comments is a bit out of order (the first became the last).

2019-07-17 14:49 UTC, JamesDeFabia commented
@AttilaVamos I made the edits you requested (and I edited the JavaDoc comments in **file.ecl**, as well). Please have another look.

2019-07-17 15:30 UTC, HPCCSmoketest commented
Process of PR-12781, label: HPCC-22150dfuServerQueue starts now.
The reason of this test is: New commit.
Commit ID: 1a0f0d11ecc57e53f6db28acde3806c115fe0af9
Estimated completion time is ~0.6 hour(s)

2019-07-17 16:05 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
Sha: 1a0f0d11ecc57e53f6db28acde3806c115fe0af9
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |113 |113 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |26 sec  (00:00:26) |
|setup (thor) |11 |11 |0 |47 sec  (00:00:47) |
|setup (roxie) |11 |11 |0 |28 sec  (00:00:28) |
|test (hthor) |845 |845 |0 |179 sec  (00:02:59) |
|test (thor) |768 |768 |0 |678 sec  (00:11:18) |
|test (roxie) |921 |921 |0 |418 sec  (00:06:58) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   32 sec (00:00:32) |  395 sec (00:06:35) |    0 sec (00:00:00) |   29 sec (00:00:29) |   19 sec (00:00:19) | 1597 sec (00:26:37) |   19 sec (00:00:19) | 2091 sec (00:34:51) |

2019-07-19 10:06 UTC, AttilaVamos approved these changes
@JamesDeFabia It seems good.

2019-07-22 12:22 UTC, JamesDeFabia commented
@richardkchapman This is now good to merge

2019-07-22 14:43 UTC, merged