HPCC-21297 Create System Servers Widget
hpcc-systems/HPCC-Platform pull request #12837
Opened 2019-08-01 03:24 UTC by miguelvazq

Fixes: HPCC-21297

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2019-08-01 03:27 UTC, miguelvazq commented
@GordonSmith Please review.

2019-08-01 03:29 UTC, HPCCSmoketest commented
Process of PR-12837, label: HPCC-21297 starts now.
The reason of this test is: Did not build yet.
Commit ID: d116a3015e50fdec00d73c5d164a681747a627d4
Estimated completion time is ~0.1 hour(s)

2019-08-01 03:37 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: d116a3015e50fdec00d73c5d164a681747a627d4
Build: success
Build: success
1 error
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! eclwatch@1.0.0 lint: `jshint --config ./.jshintrc ./eclwatch`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the eclwatch@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     /mnt/disk1/home/vamosax/.npm/_logs/2019-08-01T03_40_48_361Z-debug.log
ERROR: lint exited with 2.
npm ERR! Test failed.  See above for more details.
npm test end
~/smoketest/PR-12837/build
Makefiles created (2019-07-31_23-40-48 44 sec )
Milestone:Build it
cmd: make -j   (2019-07-31_23-40-48)
Get ECLWatch build result
Build and Install finished (2019-07-31_23-44-52 244 sec)
Check the build result
Get ECLWatch build result
Milestone:Install HPCC Platform

Lint error(s): 
eclwatch/SystemServersQueryWidget.js: line 426, col 30, PreflightDetailsWidget is not defined.

Install HPCC Platform
Installed (2019-07-31_23-46-31 99 sec )
HPCC Start: OK
HPCC Stop: OK

[Build error:](https://gist.github.com/d075cb53d9ae4cd9cfb37767b7a0e973)
Build log [Build log](https://gist.github.com/HPCCSmoketest/d075cb53d9ae4cd9cfb37767b7a0e973#file-result-19-07-31-23-39-40-log)

2019-08-01 09:51 UTC, GordonSmith requested changes

2019-08-01 09:51 UTC, GordonSmith commented on esp/src/src/Utility.ts
> +        break;
Indentation (minor)

2019-08-01 09:51 UTC, GordonSmith commented on esp/src/eclwatch/SystemServersQueryWidget.js
> +                retVal = new PreflightDetailsWidget({
Where is PreflightDetailsWidget defined?

2019-08-01 14:10 UTC, miguelvazq commented
@GordonSmith Updated.

2019-08-01 14:18 UTC, HPCCSmoketest commented
Process of PR-12837, label: HPCC-21297 starts now.
The reason of this test is: New commit.
Commit ID: 36abde43b238df9697d16aa904ef72d4cdfe80f3
Estimated completion time is ~0.1 hour(s)

2019-08-01 14:25 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 36abde43b238df9697d16aa904ef72d4cdfe80f3
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   45 sec (00:00:45) |  244 sec (00:04:04) |    0 sec (00:00:00) |   79 sec (00:01:19) |   20 sec (00:00:20) |    0 sec (00:00:00) |   15 sec (00:00:15) |  403 sec (00:06:43) |

2019-08-01 14:47 UTC, GordonSmith approved these changes
Looks ok.

2019-08-01 15:28 UTC, richardkchapman commented
Is this something that should go in 7.6 ?

2019-08-01 15:34 UTC, miguelvazq commented
It could potentially but, the other two components went into 7.4 and I believe it was mentioned it could go into a 7.4.6 / 7.4.8 if not 7.6 is fine. This widget will contain the legacy System Servers alongside the new ECL Watch improvement so it does not break any functionality.

2019-08-01 15:35 UTC, richardkchapman commented
@GordonSmith your call

2019-08-01 16:35 UTC, GordonSmith commented
7.6.x would be my preference.

2019-08-01 16:40 UTC, miguelvazq commented
> 7.6.x would be my preference?

I'm OK with that.

2019-08-06 05:59 UTC, GordonSmith commented
@miguelvazq can you re-target this PR?

2019-08-06 13:50 UTC, HPCCSmoketest commented
Process of PR-12837, label: HPCC-21297 starts now.
The reason of this test is: Base branch changed.
Commit ID: 36abde43b238df9697d16aa904ef72d4cdfe80f3
Estimated completion time is ~0.1 hour(s)

2019-08-06 13:58 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 36abde43b238df9697d16aa904ef72d4cdfe80f3
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   49 sec (00:00:49) |  247 sec (00:04:07) |    0 sec (00:00:00) |   87 sec (00:01:27) |   19 sec (00:00:19) |    0 sec (00:00:00) |   14 sec (00:00:14) |  416 sec (00:06:56) |

2019-08-06 17:45 UTC, miguelvazq commented
@GordonSmith Re-targeted.

2019-08-07 08:43 UTC, merged