HPCC-22506 Replace instances of HPCC with HPCC Systems(r)
hpcc-systems/HPCC-Platform pull request #12841
Opened 2019-08-02 14:50 UTC by g-pan

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

@JamesDeFabia please review.
Build : http://10.240.32.243/view/Docs%207.0/job/DocDevII/

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Complete successful Build tests: http://10.240.32.243/view/Docs%207.0/job/DocDevII/

2019-08-02 14:59 UTC, HPCCSmoketest commented
Process of PR-12841, label: H22506-HPCC-R starts now.
The reason of this test is: Did not build yet.
Commit ID: c4de686adafb222f5299f83fc6d7b8eb4058240c
Estimated completion time is ~0.1 hour(s)

2019-08-02 15:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: c4de686adafb222f5299f83fc6d7b8eb4058240c
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   35 sec (00:00:35) |  392 sec (00:06:32) |    0 sec (00:00:00) |   26 sec (00:00:26) |   19 sec (00:00:19) |    0 sec (00:00:00) |   14 sec (00:00:14) |  486 sec (00:08:06) |

2019-08-14 18:59 UTC, JamesDeFabia requested changes
Inline comments + Make sure all titles contain the (r) symbol as we discussed offline

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/anagram2.xml
> +    Systems, we must "spray" it to all the nodes. A <emphasis>spray</emphasis>
HPCC Systems cluster,

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +          <para>Install HPCC Systems.</para>
HPCC Systems platform

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +        <para>Now that you have HPCC Systems started and running, what do you want to
HPCC Systems platform

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +          interface for your HPCC Systems at this location
HPCC Systems platform

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/One-Click_HPCCinAWS/One-Click_RuningHPCCinAmazonWebServicesEC2.xml
> +        storage location attached to your HPCC Systems. It has a utility running to
platform

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/RoxieReference/RoxieRefMods/RoxieCapacityPlanning.xml
> +  (hpcc) , typically using indexed files. A cluster is capable of storing and
Why change to lowercase?

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/RoxieReference/RoxieReference.xml
> +    dedicated High Performance Computing Cluster (hpcc).</para>
Why change to lc?

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/RoxieReference/RoxieReference.xml
> +      HPCC Systems. Click on the <emphasis role="bold">Query Sets/Browse</emphasis>
platform

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/RunningHPCCinaVirtualMachine/RunningHPCCinaVirtualMachine.xml
> +      <para>Running HPCC Systems in a virtual machine requires (at minimum):</para>
the HPCC Systems platform

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/RunningHPCCinaVirtualMachine/RunningHPCCinaVirtualMachine.xml
> +      <para>To run HPCC Systems in a virtual machine, hardware virtualization must be
the HPCC Systems platform

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/RunningHPCCinaVirtualMachine/RunningHPCCinaVirtualMachine.xml
> +    <para>To run the virtual machine version of HPCC Systems, you need
the HPCC Systems platform

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/RunningHPCCinaVirtualMachine/RunningHPCCinaVirtualMachine.xml
> +          <para>You are now connected and ready to work with the HPCC Systems!</para>
the HPCC Systems platform

2019-08-14 18:59 UTC, JamesDeFabia commented on docs/EN_US/RunningHPCCinaVirtualMachine/RunningHPCCinaVirtualMachine.xml
> +        <para>A typical production HPCC Systems would have much more data
platform

2019-08-15 13:23 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +          <para>Install the HPCC Systems ECL IDE (Double-click the setup.msi file and
change setup.msi

2019-08-19 12:02 UTC, JamesDeFabia commented
@g-pan Back to you

2019-08-20 12:47 UTC, HPCCSmoketest commented
Process of PR-12841, label: H22506-HPCC-R starts now.
The reason of this test is: New commit.
Commit ID: 0e5fca809a5475a41adb95fe7998107749ea3785
Estimated completion time is ~0.1 hour(s)

2019-08-20 12:56 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 0e5fca809a5475a41adb95fe7998107749ea3785
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   34 sec (00:00:34) |  386 sec (00:06:26) |    0 sec (00:00:00) |   29 sec (00:00:29) |   18 sec (00:00:18) |    0 sec (00:00:00) |   15 sec (00:00:15) |  482 sec (00:08:02) |

2019-08-20 16:07 UTC, JamesDeFabia requested changes
Comments inline. I suggest you search for the word Platform (with match case on) as we had discussed. The word platform should not be capitalized (except in titles).

2019-08-20 16:07 UTC, JamesDeFabia commented on docs/EN_US/RuningHPCCinAmazonWebServicesEC2/RuningHPCCinAmazonWebServicesEC2.xml
> +        <para>You now have an un-configured cluster with the HPCC Systems Platform
platform should not be capitalized (except in titles)

2019-08-20 16:07 UTC, JamesDeFabia commented on docs/EN_US/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
> +    <para>The WsSQL service is included in the HPCC Systems Platform. </para>
platform should not be capitalized (except in titles)

2019-08-20 16:07 UTC, JamesDeFabia commented on docs/EN_US/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
> +    submitted to and executed by your HPCC Systems Platform. The result set is
platform should not be capitalized (except in titles)

2019-08-20 16:07 UTC, JamesDeFabia commented on docs/EN_US/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
> +        HPCC Systems Platform.</para>
platform should not be capitalized (except in titles)

2019-08-20 16:07 UTC, JamesDeFabia commented on docs/EN_US/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
> +        model of the target HPCC Systems as a SQL accessible DB. You can
platform

2019-08-20 16:07 UTC, JamesDeFabia commented on docs/EN_US/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
> +      <para>This methods allows you to query the HPCC Systems Platform and get
platform should not be capitalized (except in titles)

2019-08-20 16:07 UTC, JamesDeFabia commented on docs/EN_US/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
> +                  <entry>The name of the table to create in the HPCC Systems
platform should not be capitalized (except in titles)

2019-08-20 20:22 UTC, HPCCSmoketest commented
Process of PR-12841, label: H22506-HPCC-R starts now.
The reason of this test is: New commit.
Commit ID: 309d69d3f8b63fae1a38abc600932fb7e1fdb7ec
Estimated completion time is ~0.1 hour(s)

2019-08-20 20:31 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 309d69d3f8b63fae1a38abc600932fb7e1fdb7ec
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   35 sec (00:00:35) |  383 sec (00:06:23) |    0 sec (00:00:00) |   26 sec (00:00:26) |   19 sec (00:00:19) |    0 sec (00:00:00) |   14 sec (00:00:14) |  477 sec (00:07:57) |

2019-08-21 16:39 UTC, HPCCSmoketest commented
Process of PR-12841, label: H22506-HPCC-R starts now.
The reason of this test is: New commit.
Commit ID: 89e92db2e6a3f4d61123bb755706e76392d48d6a
Estimated completion time is ~0.1 hour(s)

2019-08-21 16:48 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 89e92db2e6a3f4d61123bb755706e76392d48d6a
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   38 sec (00:00:38) |  390 sec (00:06:30) |    0 sec (00:00:00) |   29 sec (00:00:29) |   20 sec (00:00:20) |    0 sec (00:00:00) |   14 sec (00:00:14) |  491 sec (00:08:11) |

2019-08-21 17:45 UTC, JamesDeFabia requested changes
@g-pan two comments inline.

2019-08-21 17:45 UTC, JamesDeFabia commented on docs/EN_US/HPCCSystemAdmin/SA-Mods/CassandraWUServer.xml
> +          <para>Once you have configured your HPCC Systems Platform to use Cassandra
platform should not be capitalized

2019-08-21 17:45 UTC, JamesDeFabia commented on docs/EN_US/HPCCSystemAdmin/SA-Mods/CassandraWUServer.xml
> +          <para>Stop all HPCC Systems Components, if they are running.</para>
components should not be capitalized

2019-08-21 18:00 UTC, HPCCSmoketest commented
Process of PR-12841, label: H22506-HPCC-R starts now.
The reason of this test is: New commit.
Commit ID: b7262fac6e344599833ccdf1f15c4eec53c64123
Estimated completion time is ~0.1 hour(s)

2019-08-21 18:00 UTC, JamesDeFabia approved these changes
@ghalliday This is good to merge now

2019-08-21 18:09 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: b7262fac6e344599833ccdf1f15c4eec53c64123
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   36 sec (00:00:36) |  392 sec (00:06:32) |    0 sec (00:00:00) |   30 sec (00:00:30) |   18 sec (00:00:18) |    0 sec (00:00:00) |   14 sec (00:00:14) |  490 sec (00:08:10) |

2019-08-22 09:29 UTC, ghalliday reviewed
@g-pan a few specific comments and a few general comments:

What does "HPCC Systems" mean?  It seems it has/can be used in a few different ways:

The company/organisation that provides the system. 
The platform - normally "HPCC Systems platform", but sometimes just "HPCC Systems".  Is HPCC Systems an equivalent to say "Spark".
An installation of the platform - - normally "HPCC Systems system"?, but sometimes just "HPCC Systems" or "HPCC Systems platform".  Should it be "HPCC Systems installation" or even "HPCC Systems platform installation"?
A cluster within an installation of the platform.  I think normally  "HPCC Systems cluster"

Also HPCC sometimes refers to an element - e.g., a user name, group name which doesn't seem to connect to HPCC Systems.

The documents are currently inconsistent in how some of the items above are described, and I assume this change is here to make them consistent.  What is the agreed term for each of those?

E.g. Some example sentences.  Should the words in [] be included or not, and what should the words in []?

The HPCC Systems [platform?] Manual contains
The HPCC Systems [platform?] is dependent on the 
To connnect to the HPCC Systems [platform/instance?] open ...
To spray data onto an HPCC Systems [cluster]

I don't know the answers, but I imagine someone must know the official answer.
Sorry to be pedantic, but the change itself is a bit pedantic, so we may as well get it right.

Also, there were a few conversations which were marked as closed, but didn't have any changes or any response, so I have unresolved some of them.

2019-08-22 09:29 UTC, ghalliday commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +      advantage of the true power of an HPCC Systems--the ability to perform
"an HPCC Systems" doesn't read right.

2019-08-22 09:29 UTC, ghalliday commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +        <para>HPCC Systems support Python2 by default. The HPCC Systems platform includes
supports I think

2019-08-22 09:29 UTC, ghalliday commented on docs/EN_US/RoxieReference/RoxieRefMods/RoxieCopySettings.xml
> +    Configuring your HPCC Systems see <emphasis>Installing and Running the HPCC Systems
This no longer reads correctly.  your HPCC Systems system?  your HPCC Systems platform.

2019-08-22 09:29 UTC, ghalliday commented on docs/EN_US/RuningHPCCinAmazonWebServicesEC2/RuningHPCCinAmazonWebServicesEC2.xml
> -                    <para>Type the Group ID for the HPCC group in the Source
I'm not sure that HPCC in this context refers to HPCC Systems.  Should it be hpcc group?  What exactly does it correspond to?

2019-08-22 09:29 UTC, ghalliday commented on docs/EN_US/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
> +                  <entry>Major of HPCC Systems platform</entry>
major version.  Also minor version and point version below.

2019-08-27 11:06 UTC, ghalliday commented on docs/EN_US/ECLWatch/ECLWa_mods/ECLWatchSrc.xml
> +      <para>ECL Watch provides an interface to the HPCC Systems and allows you
Either "HPCC Systems" or "the HPCC Systems platform", but not "the HPCC Systems"?

2019-08-27 12:56 UTC, ghalliday reviewed
I have gone through again in the light of the clarification of how the phases should be used.  I suspect I
missed a few.  Any places where "an", "the" or "your" are followed by "HPCC Systems" and nothing else tend to be confusing to read.  I'm also wonder if we should use different phrases to describe the product - "HPCC Systems" or "the HPCC Systems platform" in contrast to an install of the platform.

Whatever you and @JamesDeFabia decide is fine, but worth discussing between you.

@g-pan hopefully the comments are useful.

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
> +                  <entry>Major of HPCC Systems platform</entry>
Also missing "the": Major version of the HPCC Systems platform

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/RunningHPCCinaVirtualMachine/RunningHPCCinaVirtualMachine.xml
> +      </footnote> Systems<superscript>®</superscript> on a single node inside a Linux virtual machine
footnote is now in the wrong place should not split "HPCC" and "Systems"

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/RunningHPCCinaVirtualMachine/RunningHPCCinaVirtualMachine.xml
> +        joins, sorts, and builds that truly differentiate HPCC Systems<superscript>®</superscript>(High
does it make sense for the bracket contents to remain?

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/RunningHPCCinaVirtualMachine/RunningHPCCinaVirtualMachine.xml
> +      <para>Running HPCC Systems platform in a virtual machine requires (at minimum):</para>
remove platform

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/RunningHPCCinaVirtualMachine/RunningHPCCinaVirtualMachine.xml
> +      <para>To run HPCC Systems platform in a virtual machine, hardware virtualization must be
remove platform

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/RunningHPCCinaVirtualMachine/RunningHPCCinaVirtualMachine.xml
> +      <para>To run HPCC Systems platform in a virtual machine, hardware virtualization must be
(or possibly prefix with "the")

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/RunningHPCCinaVirtualMachine/RunningHPCCinaVirtualMachine.xml
> +        <para>ECL Watch is a Web-based interface to your HPCC Systems. It
probably better with instance.

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/RunningHPCCinaVirtualMachine/RunningHPCCinaVirtualMachine.xml
> +        enables you to examine and manage many aspects of the HPCC Systems and allows
remove the, or add platform.

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/RoxieReference/RoxieRefMods/RoxieCopySettings.xml
> +    Configuring your HPCC Systems see <emphasis>Installing and Running the HPCC Systems
or remove "your"

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/One-Click_HPCCinAWS/One-Click_RuningHPCCinAmazonWebServicesEC2.xml
> +          joins, sorts, and builds that truly differentiate HPCC Systems (High
does (High... ) still make sense?

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/InstantCloud/InstantCloud.xml
> +    <sect1 id="InstaCloud_LaunchNew                        ">
Extra spaces

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/InstantCloud/InstantCloud.xml
> +        in the HPCC Systems Thor cluster. The power of the HPCC Systems comes from its ability
probably best to delete "the" or add "platform"

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/hpcc_ldap.xml
> +          <para>Stop all HPCC Systems Components, if they are running.</para>
lower case components?

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/hpcc_ldap.xml
> +          <para>Stop all HPCC Systems Components, if they are running.</para>
lower case components

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/anagram2.xml
> +    the HPCC Systems cluster. The power of the HPCC Systems
remove the or add platform?

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/anagram1.xml
> +        IDE) and login to your HPCC Systems platform.</para>
platform -> instance? installation? not sure of the best word.

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/UserSecurityMaint.xml
> +        of the HPCC Systems where permissions may be set. Use this area to view
+ platform/instance or remove "the"?

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/UserSecurityMaint.xml
> +    <para>The HPCC Systems' LDAP <emphasis role="bold">Dali Server</emphasis>
remove apostrophe

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/Hardware.xml
> +    recommendations in order to run the HPCC Systems. Essentially the HPCC Systems platform is
remove the from 1st instance?

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +          <para>To submit a job using the ecl CLI, make sure the HPCC Systems has been
update: probably remove the or at platform

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +      advantage of the true power of an HPCC Systems--the ability to perform
update: remove "an"

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +        version of Python and the HPCC Systems are set up correctly to support
delete "the"

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/HPCCDataTutorial/DataTutorial.xml
> +          <para>You have a running HPCC Systems platform. This can be a VM Edition or a single
either "HPCC Systems" or "the HPCC Systems platform"

2019-08-27 12:56 UTC, ghalliday commented on docs/EN_US/ConfiguringHPCC/ConfiguringHPCC.xml
> +        transferred to or from your HPCC Systems platform. The drop zone is a logical
really an installation rather than a platform

2019-08-27 19:55 UTC, HPCCSmoketest commented
Process of PR-12841, label: H22506-HPCC-R starts now.
The reason of this test is: New commit.
Commit ID: b1fd0d7babb9499d7e21295f5ac6a5e972183637
Estimated completion time is ~0.1 hour(s)

2019-08-27 20:04 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: b1fd0d7babb9499d7e21295f5ac6a5e972183637
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   37 sec (00:00:37) |  383 sec (00:06:23) |    0 sec (00:00:00) |   27 sec (00:00:27) |   19 sec (00:00:19) |    0 sec (00:00:00) |   14 sec (00:00:14) |  480 sec (00:08:00) |

2019-08-29 10:13 UTC, ghalliday reviewed
@g-pan a couple of minor comments.  I can either merge or wait for changes.

2019-08-29 10:13 UTC, ghalliday commented on docs/EN_US/InstantCloud/InstantCloud.xml
> +        in HPCC Systems Thor cluster. The power of the HPCC Systems comes from its ability
missing the

2019-08-29 10:13 UTC, ghalliday commented on docs/EN_US/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
>                    Platform's distributed file system.</entry>
Platform still capitalized.

2019-08-29 14:25 UTC, g-pan commented
@ghalliday should be OK to merge now

2019-08-29 14:28 UTC, HPCCSmoketest commented
Process of PR-12841, label: H22506-HPCC-R starts now.
The reason of this test is: New commit.
Commit ID: 9fdfcda6f9960c3c6adf4e1f2a0d46367a839004
Estimated completion time is ~0.1 hour(s)

2019-08-29 14:36 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 9fdfcda6f9960c3c6adf4e1f2a0d46367a839004
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   39 sec (00:00:39) |  395 sec (00:06:35) |    0 sec (00:00:00) |   30 sec (00:00:30) |   18 sec (00:00:18) |    0 sec (00:00:00) |   14 sec (00:00:14) |  496 sec (00:08:16) |

2019-08-29 15:18 UTC, merged