HPCC-22806 Handle XML encoding &#nnn; properly in ESP
hpcc-systems/HPCC-Platform pull request #12964
Opened 2019-09-11 13:01 UTC by gaojx

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [x] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2019-09-11 13:02 UTC, gaojx commented
@mayx @afishbeck please review.

2019-09-11 13:23 UTC, richardkchapman commented on esp/bindings/SOAP/xpp/sxt/XmlTokenizer.h
> +		  assert(false);
throwUnexpected() would be better I think

2019-09-11 14:03 UTC, HPCCSmoketest commented
Process of PR-12964, label: HPCC22806-XML-entity-reference-not-handled-properly-in-ESP starts now.
The reason of this test is: Did not build yet.
Commit ID: 46b2f3f5712baa19dd60f829e36bc211225cd77a
Estimated completion time is ~0.5 hour(s)

2019-09-11 14:33 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 46b2f3f5712baa19dd60f829e36bc211225cd77a
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |116 |116 |0 |0 |0 |36 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |25 sec  (00:00:25) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |26 sec  (00:00:26) |
|test (hthor) |860 |860 |0 |183 sec  (00:03:03) |
|test (thor) |784 |784 |0 |703 sec  (00:11:43) |
|test (roxie) |935 |935 |0 |234 sec  (00:03:54) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   33 sec (00:00:33) |  256 sec (00:04:16) |    0 sec (00:00:00) |    3 sec (00:00:03) |   20 sec (00:00:20) | 1437 sec (00:23:57) |   22 sec (00:00:22) | 1771 sec (00:29:31) |

2019-09-11 16:28 UTC, HPCCSmoketest commented
Process of PR-12964, label: HPCC22806-XML-entity-reference-not-handled-properly-in-ESP starts now.
The reason of this test is: New commit.
Commit ID: bbd3922f458b32e16b0e0fd05506b654381fc0d1
Estimated completion time is ~0.5 hour(s)

2019-09-11 17:02 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: bbd3922f458b32e16b0e0fd05506b654381fc0d1
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |116 |116 |0 |0 |0 |36 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |8 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |26 sec  (00:00:26) |
|setup (thor) |11 |11 |0 |45 sec  (00:00:45) |
|setup (roxie) |11 |11 |0 |26 sec  (00:00:26) |
|test (hthor) |860 |860 |0 |196 sec  (00:03:16) |
|test (thor) |784 |784 |0 |706 sec  (00:11:46) |
|test (roxie) |935 |935 |0 |418 sec  (00:06:58) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   33 sec (00:00:33) |  259 sec (00:04:19) |    0 sec (00:00:00) |    3 sec (00:00:03) |   19 sec (00:00:19) | 1638 sec (00:27:18) |   21 sec (00:00:21) | 1973 sec (00:32:53) |

2019-09-11 17:02 UTC, afishbeck requested changes
@gaojx mostly changes to make things clearer.  Both in code and in error desc.

2019-09-11 17:02 UTC, afishbeck commented on esp/bindings/SOAP/xpp/sxt/XmlTokenizer.h
> +      snprintf(buf, 256, "Internal error at %s(%d) in %s", __FILE__, __LINE__, __func__);
Could provide a bit more description.  Such as "invalid UCS character" or "out of bounds UCS character"...
 at %s(%d) in %s.

2019-09-13 16:58 UTC, afishbeck approved these changes
@gaojx looks good.

2019-09-13 17:00 UTC, afishbeck requested changes
@gaojx actually isn't clean, please squash and make sure it's a clean merge, I see unrelated changes.

2019-09-13 17:01 UTC, afishbeck commented on roxie/udplib/udptopo.cpp
> +                    mySubChannels[channel] = slaves[channel].ordinality()-1;
@gaojx Looks like this needs rebasing.

2019-09-13 17:30 UTC, HPCCSmoketest commented
Process of PR-12964, label: HPCC22806-XML-entity-reference-not-handled-properly-in-ESP starts now.
The reason of this test is: New commit.
Commit ID: a07be9c0e55a27203c83def13cafe2d9ce30e002
Estimated completion time is ~0.5 hour(s)

2019-09-13 17:34 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: a07be9c0e55a27203c83def13cafe2d9ce30e002
Number of Error(s): 8
/mnt/disk1/home/vamosax/smoketest/PR-12964/HPCC-Platform/esp/bindings/SOAP/xpp/sxt/XmlTokenizer.h:251:7: error: \xe2\x80\x98throwUnexcepted\xe2\x80\x99 was not declared in this scope
/mnt/disk1/home/vamosax/smoketest/PR-12964/HPCC-Platform/esp/bindings/SOAP/xpp/sxt/XmlTokenizer.h:251:7: error: \xe2\x80\x98throwUnexcepted\xe2\x80\x99 was not declared in this scope
/mnt/disk1/home/vamosax/smoketest/PR-12964/HPCC-Platform/esp/bindings/SOAP/xpp/sxt/XmlTokenizer.h:251:7: error: \xe2\x80\x98throwUnexcepted\xe2\x80\x99 was not declared in this scope
make[2]: *** [esp/esdllib/CMakeFiles/esdllib.dir/build.make:115: esp/esdllib/CMakeFiles/esdllib.dir/__/bindings/SOAP/xpp/xpp/xpputils.cpp.o] Error 1
make[2]: *** [esp/esdllib/CMakeFiles/esdllib.dir/build.make:63: esp/esdllib/CMakeFiles/esdllib.dir/esdl_def.cpp.o] Error 1
make[2]: *** [esp/esdllib/CMakeFiles/esdllib.dir/build.make:89: esp/esdllib/CMakeFiles/esdllib.dir/esdl_transformer2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:12803: esp/esdllib/CMakeFiles/esdllib.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

[Build error:](https://gist.github.com/d7d94fddde0abe7c9870865253c2cf8a)
Build log [Build log](https://gist.github.com/HPCCSmoketest/d7d94fddde0abe7c9870865253c2cf8a#file-result-19-09-13-13-41-39-log)

2019-09-16 13:27 UTC, HPCCSmoketest commented
Process of PR-12964, label: HPCC22806-XML-entity-reference-not-handled-properly-in-ESP starts now.
The reason of this test is: New commit.
Commit ID: df20095314b57847f97492ff4266f4a6e15cf941
Estimated completion time is ~0.5 hour(s)

2019-09-16 14:01 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: df20095314b57847f97492ff4266f4a6e15cf941
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |116 |116 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |3 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |24 sec  (00:00:24) |
|setup (thor) |11 |11 |0 |45 sec  (00:00:45) |
|setup (roxie) |11 |11 |0 |20 sec  (00:00:20) |
|test (hthor) |860 |860 |0 |209 sec  (00:03:29) |
|test (thor) |784 |784 |0 |708 sec  (00:11:48) |
|test (roxie) |935 |935 |0 |420 sec  (00:07:00) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   35 sec (00:00:35) |  255 sec (00:04:15) |    0 sec (00:00:00) |    3 sec (00:00:03) |   20 sec (00:00:20) | 1670 sec (00:27:50) |   21 sec (00:00:21) | 2004 sec (00:33:24) |

2019-09-16 14:07 UTC, gaojx commented
It seems that rebase brought in more changes. This pull request is now very messy. I must did something wrong.  Would it be better for me to abandon the feature branch and restart a new branch from scratch?

2019-09-16 14:09 UTC, richardkchapman commented
git rebase --onto candidate-7.6.0 HEAD^ should fix it. (followed by a force-push).

2019-09-16 14:47 UTC, closed without merging

2019-09-16 14:51 UTC, gaojx commented
I did: 
git rebase --onto candidate-7.6.0 HEAD^
git push origin HPCC22806-XML-entity-reference-not-handled-properly-in-ESP --force

It brought in one more change. What should we do now?

2019-09-16 15:05 UTC, HPCCSmoketest commented
Process of PR-12964, label: HPCC22806-XML-entity-reference-not-handled-properly-in-ESP starts now.
The reason of this test is: New commit.
Commit ID: 1e81d25881d25bd41aee9380c683cc2dd0a8c31e
Estimated completion time is ~0.5 hour(s)

2019-09-16 15:35 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 1e81d25881d25bd41aee9380c683cc2dd0a8c31e
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |116 |116 |0 |0 |0 |36 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |8 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |27 sec  (00:00:27) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |16 sec  (00:00:16) |
|test (hthor) |860 |860 |0 |180 sec  (00:03:00) |
|test (thor) |784 |784 |0 |683 sec  (00:11:23) |
|test (roxie) |935 |935 |0 |232 sec  (00:03:52) |


HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   38 sec (00:00:38) |  256 sec (00:04:16) |    0 sec (00:00:00) |    3 sec (00:00:03) |   19 sec (00:00:19) | 1403 sec (00:23:23) |   20 sec (00:00:20) | 1739 sec (00:28:59) |