HPCC-19607 ECLWatch index information page to include Blooms
hpcc-systems/HPCC-Platform pull request #13144
Opened 2019-11-11 19:54 UTC by kunalaswani

Added new tab for Blooms information to Logical Files Details

Signed-off-by: Kunal Aswani <Kunal.Aswani@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2019-11-11 19:55 UTC, kunalaswani commented
@GordonSmith please review

2019-11-11 19:58 UTC, kunalaswani commented
HPCC-23109 was created for documentation.

2019-11-11 20:01 UTC, HPCCSmoketest commented
Process of PR-13144, label: HPCC-19607 starts now.
The reason of this test is: Did not build yet.
Commit ID: c19bf1a2302aa0c396b13eb57980a01d3f339d2a
Estimated completion time is ~0.1 hour(s)

2019-11-11 20:09 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: c19bf1a2302aa0c396b13eb57980a01d3f339d2a
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   49 sec (00:00:49) |  257 sec (00:04:17) |    0 sec (00:00:00) |   71 sec (00:01:11) |   25 sec (00:00:25) |    0 sec (00:00:00) |   17 sec (00:00:17) |  419 sec (00:06:59) |

2019-11-12 18:53 UTC, miguelvazq requested changes

2019-11-12 18:53 UTC, miguelvazq commented on esp/src/eclwatch/FileBloomsWidget.js
> +                        label: "Field Names",
Translation needed.

2019-11-12 18:53 UTC, miguelvazq commented on esp/src/eclwatch/FileBloomsWidget.js
> +            retVal.on(".dgrid-row-url:click", function (evt) {
Are you actually opening anything?

2019-11-12 18:53 UTC, miguelvazq commented on esp/src/eclwatch/FileBloomsWidget.js
> +        _onOpen: function (event) {
Are you actually opening anything?

2019-11-12 18:53 UTC, miguelvazq commented on esp/src/eclwatch/FileBloomsWidget.js
> +                        Name: nlsHPCC.Blooms,
Do we have to loop through them? Seems that your parent is static.

2019-11-13 12:07 UTC, GordonSmith requested changes

2019-11-13 12:07 UTC, GordonSmith commented on esp/src/eclwatch/FileBloomsWidget.js
> +            });
I suspect there is no need to refresh on tab selection (does it ever change once the file has been written)?

2019-11-13 12:07 UTC, GordonSmith commented on esp/src/eclwatch/FileBloomsWidget.js
> +                        selectorType: 'checkbox',
Minor, should be " (double quotes) for consistentcy

2019-11-13 12:07 UTC, GordonSmith commented on esp/src/eclwatch/FileBloomsWidget.js
> +                                type: "item",
Trailing comma

2019-11-13 12:07 UTC, GordonSmith commented on esp/src/eclwatch/templates/LFDetailsWidget.html
> +                </div>
Indentation

2019-11-13 18:07 UTC, HPCCSmoketest commented
Process of PR-13144, label: HPCC-19607 starts now.
The reason of this test is: New commit.
Commit ID: e813e240f2321d17f5f8dfdd0808d3d2629f35dd
Estimated completion time is ~0.1 hour(s)

2019-11-13 18:14 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: e813e240f2321d17f5f8dfdd0808d3d2629f35dd
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   46 sec (00:00:46) |  249 sec (00:04:09) |    0 sec (00:00:00) |   79 sec (00:01:19) |   27 sec (00:00:27) |    0 sec (00:00:00) |   16 sec (00:00:16) |  417 sec (00:06:57) |

2019-11-13 18:27 UTC, kunalaswani commented
@GordonSmith I spoke with Richard on what he would like to see, I have made the suggested changes from you and miguel as well as what Richard mentioned.

2019-11-13 19:28 UTC, miguelvazq commented on esp/src/eclwatch/LFDetailsWidget.js
> +                this.fileBloomsWidget = registry.byId(this.id + "_FileBlooms")
semicolon

2019-11-13 19:31 UTC, miguelvazq reviewed
Minor comment.

2019-11-13 19:35 UTC, miguelvazq commented on esp/src/eclwatch/FileBloomsWidget.js
> +                        collapseOnRefresh: false,
Not needed if your not using tree.

2019-11-13 19:35 UTC, miguelvazq commented on esp/src/eclwatch/FileBloomsWidget.js
> +                context.grid.refresh()
Minor: Missing semicolon

2019-11-13 19:35 UTC, miguelvazq commented on esp/src/eclwatch/FileBloomsWidget.js
> +                            type: "fieldname"
Do you still need this type? Usually add these for renderCell methods to perform an action on those rows.

2019-11-13 19:35 UTC, miguelvazq commented on esp/src/eclwatch/nls/hpcc.js
> +    FieldMask: "Field Mask",
FieldMask column is gone now.

2019-11-14 19:30 UTC, HPCCSmoketest commented
Process of PR-13144, label: HPCC-19607 starts now.
The reason of this test is: New commit.
Commit ID: 4d640a86bd7539567e8513e6293725e8afb460ad
Estimated completion time is ~0.1 hour(s)

2019-11-14 19:38 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 4d640a86bd7539567e8513e6293725e8afb460ad
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   39 sec (00:00:39) |  255 sec (00:04:15) |    0 sec (00:00:00) |   77 sec (00:01:17) |   25 sec (00:00:25) |    0 sec (00:00:00) |   16 sec (00:00:16) |  412 sec (00:06:52) |

2019-11-14 19:53 UTC, HPCCSmoketest commented
Process of PR-13144, label: HPCC-19607 starts now.
The reason of this test is: New commit.
Commit ID: 3de96196bfe84842d86d63e371a76f03c8cfeae6
Estimated completion time is ~0.1 hour(s)

2019-11-14 20:00 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 3de96196bfe84842d86d63e371a76f03c8cfeae6
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   48 sec (00:00:48) |  257 sec (00:04:17) |    0 sec (00:00:00) |   87 sec (00:01:27) |   23 sec (00:00:23) |    0 sec (00:00:00) |   15 sec (00:00:15) |  430 sec (00:07:10) |

2019-11-20 15:45 UTC, miguelvazq requested changes
One last minor change and then should be good.

2019-11-20 15:45 UTC, miguelvazq commented on esp/src/eclwatch/FileBloomsWidget.js
> +                        disabled: function (item) {
Probably do not need to disable anything since there is not actions to be taken.

2019-11-20 19:30 UTC, HPCCSmoketest commented
Process of PR-13144, label: HPCC-19607 starts now.
The reason of this test is: New commit.
Commit ID: 6ebf5ead3254286e5ccd32dbac5e656213a1a860
Estimated completion time is ~0.1 hour(s)

2019-11-20 19:38 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 6ebf5ead3254286e5ccd32dbac5e656213a1a860
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   49 sec (00:00:49) |  252 sec (00:04:12) |    0 sec (00:00:00) |   72 sec (00:01:12) |   23 sec (00:00:23) |    0 sec (00:00:00) |   15 sec (00:00:15) |  411 sec (00:06:51) |

2019-11-20 20:06 UTC, miguelvazq approved these changes

2019-11-20 20:08 UTC, kunalaswani commented
@miguelvazq change made

2019-12-02 15:38 UTC, kunalaswani commented
@GordonSmith changes were made, please review, thanks

2019-12-03 13:43 UTC, GordonSmith requested changes

2019-12-03 13:43 UTC, GordonSmith commented on esp/src/eclwatch/FileBloomsWidget.js
> +    "hpcc/DelayLoadWidget",
Trailing comma

2019-12-03 13:43 UTC, GordonSmith commented on esp/src/eclwatch/FileBloomsWidget.js
> +            var context = this;
context not used

2019-12-03 21:43 UTC, HPCCSmoketest commented
Process of PR-13144, label: HPCC-19607 starts now.
The reason of this test is: New commit.
Commit ID: 5092e7c629efc901bf6977b5de8692b979123a41
Estimated completion time is ~0.1 hour(s)

2019-12-03 21:50 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 5092e7c629efc901bf6977b5de8692b979123a41
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   41 sec (00:00:41) |  252 sec (00:04:12) |    0 sec (00:00:00) |   84 sec (00:01:24) |   20 sec (00:00:20) |    0 sec (00:00:00) |   16 sec (00:00:16) |  413 sec (00:06:53) |

2019-12-05 14:43 UTC, kunalaswani commented
@GordonSmith changes made

2019-12-05 16:44 UTC, GordonSmith requested changes
Two minor comments - otherwise looks good.

2019-12-05 16:44 UTC, GordonSmith commented on esp/src/eclwatch/FileBloomsWidget.js
> +            var context = this;
`context` not used.

2019-12-05 16:44 UTC, GordonSmith commented on esp/src/eclwatch/FileBloomsWidget.js
> +                    this.refreshGrid()
Missing semi-colon

2019-12-09 15:34 UTC, HPCCSmoketest commented
Process of PR-13144, label: HPCC-19607 starts now.
The reason of this test is: New commit.
Commit ID: 705d22972c4828e1dbc0f8fcbb625e4269eb8d68
Estimated completion time is ~0.1 hour(s)

2019-12-09 15:41 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 705d22972c4828e1dbc0f8fcbb625e4269eb8d68
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   50 sec (00:00:50) |  250 sec (00:04:10) |    0 sec (00:00:00) |   72 sec (00:01:12) |   23 sec (00:00:23) |    0 sec (00:00:00) |   16 sec (00:00:16) |  411 sec (00:06:51) |

2019-12-10 14:01 UTC, GordonSmith approved these changes
Looks good...

2019-12-10 15:01 UTC, merged