HPCC-22940 Add environment theme admin preference
hpcc-systems/HPCC-Platform pull request #13161
Opened 2019-11-18 18:00 UTC by miguelvazq

Fixes: HPCC-22940

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2019-11-18 18:01 UTC, miguelvazq commented
@GordonSmith Please review.

2019-11-18 18:31 UTC, HPCCSmoketest commented
Process of PR-13161, label: HPCC-22981 starts now.
The reason of this test is: Did not build yet.
Commit ID: 99019e3b02b2e53c31047a8596dbf84067139efd
Estimated completion time is ~0.1 hour(s)

2019-11-18 18:38 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 99019e3b02b2e53c31047a8596dbf84067139efd
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   45 sec (00:00:45) |  250 sec (00:04:10) |    0 sec (00:00:00) |   69 sec (00:01:09) |   20 sec (00:00:20) |    0 sec (00:00:00) |   19 sec (00:00:19) |  403 sec (00:06:43) |

2019-11-19 02:05 UTC, HPCCSmoketest commented
Process of PR-13161, label: HPCC-22981 starts now.
The reason of this test is: New commit.
Commit ID: 94957679ab470908110335a44c52e1b2d6ec75b4
Estimated completion time is ~0.1 hour(s)

2019-11-19 02:13 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 94957679ab470908110335a44c52e1b2d6ec75b4
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   44 sec (00:00:44) |  255 sec (00:04:15) |    0 sec (00:00:00) |   69 sec (00:01:09) |   27 sec (00:00:27) |    0 sec (00:00:00) |   16 sec (00:00:16) |  411 sec (00:06:51) |

2019-12-03 13:41 UTC, GordonSmith requested changes

2019-12-03 13:41 UTC, GordonSmith commented on esp/src/eclwatch/templates/HPCCPlatformWidget.html
> +            <div id="searchUserMoreComponents" class="searchUserMoreComponents">
id should have a "${id}" prefix

2019-12-03 13:41 UTC, GordonSmith commented on esp/src/src/UserPreferences/EnvironmentTheme.ts
> +let ws_store = globalKeyValStore();
Should be const?

2019-12-03 13:41 UTC, GordonSmith commented on esp/src/src/UserPreferences/EnvironmentTheme.ts
> +            context.toolbarColor.set("value", val);
Is `context` valid here?

2019-12-03 13:41 UTC, GordonSmith commented on esp/src/src/UserPreferences/EnvironmentTheme.ts
> +        let searchUserMoreComponents = dom.byId("searchUserMoreComponents");
Should be const?

2019-12-03 13:41 UTC, GordonSmith commented on esp/src/src/UserPreferences/EnvironmentTheme.ts
> +            var parent = domConstruct.create("div", {id: id + "BannerInnerText", class: "envrionmentText"}, searchUserMoreComponents, "before");
Should be const?

2019-12-03 13:41 UTC, GordonSmith commented on esp/src/src/UserPreferences/EnvironmentTheme.ts
> +    context.environmentText.set("value", "");
context is not valid here

2019-12-04 16:28 UTC, miguelvazq commented on esp/src/src/UserPreferences/EnvironmentTheme.ts
> +            context.toolbarColor.set("value", val);
Yes I pass it in line 13

2019-12-04 16:29 UTC, miguelvazq commented on esp/src/src/UserPreferences/EnvironmentTheme.ts
> +    context.environmentText.set("value", "");
It is passed in a line `68`

2019-12-04 16:57 UTC, GordonSmith commented
@richardkchapman this can be pulled (the let/const comments are very minor).

2019-12-04 16:58 UTC, GordonSmith approved these changes

2019-12-04 17:08 UTC, miguelvazq commented
@GordonSmith Modified the commit to reflect the comments that were valid.

2019-12-04 17:10 UTC, GordonSmith commented
@richardkchapman good to pull

2019-12-04 17:12 UTC, HPCCSmoketest commented
Process of PR-13161, label: HPCC-22981 starts now.
The reason of this test is: New commit.
Commit ID: 07312b9269b2b777051165b3755d34b10782da8d
Estimated completion time is ~0.1 hour(s)

2019-12-04 17:19 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-327.28.3.el7.x86_64)
 GCC:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Sha: 07312b9269b2b777051165b3755d34b10782da8d
Build: success
Build: success
Install HPCC Platform
HPCC Start: OK
HPCC Stop: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   44 sec (00:00:44) |  254 sec (00:04:14) |    0 sec (00:00:00) |   70 sec (00:01:10) |   24 sec (00:00:24) |    0 sec (00:00:00) |   17 sec (00:00:17) |  409 sec (00:06:49) |

2019-12-06 09:40 UTC, merged