HPCC-19274  Add ECLArchiveViewer
hpcc-systems/HPCC-Platform pull request #13384
Opened 2020-02-20 15:35 UTC by jbrundage

Add "ECLNew" tab that displays a list of ECL Archive sections on the left.

Clicking on a section name will display the contents on the right.

If no archive contents are found for a WU the ECL query is displayed.

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2020-02-20 16:28 UTC, HPCCSmoketest commented
Process of PR-13384, label: archive_viewer_1 starts now.
The reason of this test is: Did not build yet.
Commit ID: cd3fd3423ccc8885905d85a805f6eea01ac9fafd
Estimated completion time is ~0.2 hour(s)

2020-02-20 16:45 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-17.ca-central-1.compute.internal
Sha: cd3fd3423ccc8885905d85a805f6eea01ac9fafd
Build: success
Install warning(s): 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {os:darwin,arch:any} (current: {os:linux,arch:x64})

Lint error(s): 
eclwatch/ECLSourceWidgetNew.js: line 75, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 81, col 26, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 82, col 21, let is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 86, col 30, detectContent was used before it was defined.
eclwatch/ECLSourceWidgetNew.js: line 87, col 25, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 96, col 41, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 97, col 41, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 100, col 41, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 118, col 52, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
9 errors
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> run-s jslint tslint
> eclwatch@1.0.0 jslint /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! code ELIFECYCLE
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> run-s jslint tslint
> eclwatch@1.0.0 jslint /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! errno 2
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> run-s jslint tslint
> eclwatch@1.0.0 jslint /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! eclwatch@1.0.0 jslint: `jshint --config ./.jshintrc ./eclwatch`
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> run-s jslint tslint
> eclwatch@1.0.0 jslint /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! Exit status 2
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> run-s jslint tslint
> eclwatch@1.0.0 jslint /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> jshint --config ./.jshintrc ./eclwatch
npm ERR! 
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /home/centos/smoketest/PR-13384
 ... ( comment is too long, 200 lines, 9644 bytes, truncated) ... 
[Build error:](https://gist.github.com/b15daaec554f1f112bc4e123a0c00628)
Build log [Build log](https://gist.github.com/HPCCSmoketest/b15daaec554f1f112bc4e123a0c00628#file-result-20-02-20-16-28-30-log)

Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   35 sec (00:00:35) |  763 sec (00:12:43) |  122 sec (00:02:02) |   22 sec (00:00:22) |   17 sec (00:00:17) |    0 sec (00:00:00) |   15 sec (00:00:15) |  974 sec (00:16:14) |

```

2020-03-05 18:01 UTC, jbrundage commented
@GordonSmith this is updated with the latest. It successfully parses every xml archive structure I've come across.

2020-03-05 18:04 UTC, HPCCSmoketest commented
Process of PR-13384, label: archive_viewer_1 starts now.
The reason of this test is: Forced to re-test.
Commit ID: de74468176c84a3ed40bc67ea905d77436c40194
Estimated completion time is ~0.1 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-178.ca-central-1.compute.internal

2020-03-05 18:07 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-178.ca-central-1.compute.internal
Sha: de74468176c84a3ed40bc67ea905d77436c40194
Number of Error(s): 3
make[2]: *** [esp/src/CMakeFiles/eclwatch_fetchdeps.dir/build.make:61: /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src/lib/package-lock.json] Error 1
make[1]: *** [CMakeFiles/Makefile2:9870: esp/src/CMakeFiles/eclwatch_fetchdeps.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

[Build error:](https://gist.github.com/3d79009c59b5d2b20ea7d28dc758dd75)
Build log [Build log](https://gist.github.com/HPCCSmoketest/3d79009c59b5d2b20ea7d28dc758dd75#file-result-20-03-05-18-04-04-log)

2020-03-05 20:14 UTC, HPCCSmoketest commented
Process of PR-13384, label: archive_viewer_1 starts now.
The reason of this test is: New commit.
Commit ID: de74468176c84a3ed40bc67ea905d77436c40194
Estimated completion time is ~0.2 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal

2020-03-05 20:17 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
Sha: de74468176c84a3ed40bc67ea905d77436c40194
Number of Error(s): 3
make[2]: *** [esp/src/CMakeFiles/eclwatch_fetchdeps.dir/build.make:61: /home/centos/smoketest/PR-13384/HPCC-Platform/esp/src/lib/package-lock.json] Error 1
make[1]: *** [CMakeFiles/Makefile2:9870: esp/src/CMakeFiles/eclwatch_fetchdeps.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

[Build error:](https://gist.github.com/f62783496bf3aa8b3876026be51515ac)
Build log [Build log](https://gist.github.com/HPCCSmoketest/f62783496bf3aa8b3876026be51515ac#file-result-20-03-05-20-14-20-log)

2020-03-06 15:08 UTC, GordonSmith commented on esp/src/package.json
> +    "@hpcc-js/phosphor": "2.13.15",
@jbrundage When bumping the versions for @hpcc-js - its probably better to bump all of them to the latest,

2020-03-06 15:09 UTC, GordonSmith commented on esp/src/package.json
>      "codemirror": "5.50.2",
@jbrundage When editing package.json - you also need to run "npm install" local AND then commit package-lock.json at the same time (which is why your getting smoketest failures.

2020-03-06 15:15 UTC, GordonSmith requested changes
Had a quick play:
Looking at:  http://localhost:8080/esp/files/stub.htm?Wuid=W20200109-161403&Widget=WUDetailsWidget
1. When the page opens up, it shows the correct ECL - good.
2. ~~Once the the LHS tree loads, it should calculate which attribute in the tree corresponds to the displayed ECL and highlight/select it by default (so the user knows which attribute they are looking at).~~ The LHS line selection style (for me) was non obvious, have a look at the selection lines in the grids and make the tree selection match?
3. In the above example there is an erroneous node called "Query" in the tree.

2020-03-06 15:28 UTC, GordonSmith commented on esp/src/eclwatch/ECLSourceWidgetNew.js
> +                .relativeSizes([0.38,0.62])
It should render at this point.

2020-03-06 15:32 UTC, GordonSmith commented on esp/src/eclwatch/ECLSourceWidgetNew.js
> +                wu.fetchArchive().then(archiveResp => {
Minor:  This could be done in parallel with the refresh(true) call above...

2020-03-06 15:32 UTC, GordonSmith commented on esp/src/eclwatch/ECLSourceWidgetNew.js
> +                        pathToQuery = json._children[0]._children.find(n=>n.name && n.name.toLowerCase()==="query")["$"].attributePath;
This won't find attributes nested deeper than one level?

2020-03-09 16:01 UTC, jbrundage commented on esp/src/eclwatch/ECLSourceWidgetNew.js
> +            wu.refresh(true).then(wuInfo=>{
```
wu.Helpers.some(helper=>{
    return helper.type==="ArchiveQuery"
}).length > 0
```

2020-03-12 16:46 UTC, HPCCSmoketest commented
Process of PR-13384, label: archive_viewer_1 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 87274fd9a39f53f87d61321de4b50eda2936056d
Estimated completion time is ~0.1 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-163.ca-central-1.compute.internal

2020-03-12 16:57 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-163.ca-central-1.compute.internal
Sha: 87274fd9a39f53f87d61321de4b50eda2936056d
Build: success
Install warning(s): 
npm WARN dojo-themes@1.14.1 requires a peer of dojo@1.14.1 but none is installed. You must install peer dependencies yourself.
npm WARN dojo-themes@1.14.1 requires a peer of dijit@1.14.1 but none is installed. You must install peer dependencies yourself.

Lint error(s): 
eclwatch/ECLSourceWidgetNew.js: line 81, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 83, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 89, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 90, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 92, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 93, col 41, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 123, col 56, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 124, col 25, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 125, col 25, let is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 126, col 25, let is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 128, col 77, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 130, col 25, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 134, col 25, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 136, col 66, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 139, col 48, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 140, col 33, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 141, col 33, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 148, col 58, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 149, col 33, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 149, col 82, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 153, col 37, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 171, col 38, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 180, col 69, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 184, col 48, arrow function
 ... ( comment is too long, 236 lines, 14307 bytes, truncated) ... 
[Build error:](https://gist.github.com/754e7f48b45bf8835460c1c724bcc029)
Build log [Build log](https://gist.github.com/HPCCSmoketest/754e7f48b45bf8835460c1c724bcc029#file-result-20-03-12-16-46-03-log)

Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  450 sec (00:07:30) |  117 sec (00:01:57) |   22 sec (00:00:22) |   20 sec (00:00:20) |    0 sec (00:00:00) |   15 sec (00:00:15) |  633 sec (00:10:33) |

```

2020-03-12 17:41 UTC, HPCCSmoketest commented
Process of PR-13384, label: archive_viewer_1 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 8f8bf8fc2e30a0138ce407f016dabf82bc728912
Estimated completion time is ~0.1 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-138.ca-central-1.compute.internal

2020-03-12 17:52 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-138.ca-central-1.compute.internal
Sha: 8f8bf8fc2e30a0138ce407f016dabf82bc728912
Build: success
Install warning(s): 
npm WARN dojo-themes@1.14.1 requires a peer of dojo@1.14.1 but none is installed. You must install peer dependencies yourself.
npm WARN dojo-themes@1.14.1 requires a peer of dijit@1.14.1 but none is installed. You must install peer dependencies yourself.

Lint error(s): 
eclwatch/ECLSourceWidgetNew.js: line 81, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 83, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 87, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 88, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 90, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 91, col 41, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 121, col 56, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 122, col 25, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 123, col 25, let is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 124, col 25, let is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 126, col 77, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 128, col 25, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 132, col 25, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 134, col 66, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 137, col 48, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 138, col 33, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 139, col 33, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 146, col 58, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 147, col 33, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 147, col 82, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 151, col 37, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 169, col 38, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 178, col 69, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 182, col 48, arrow function
 ... ( comment is too long, 236 lines, 14307 bytes, truncated) ... 
[Build error:](https://gist.github.com/33148f456eef2c84261eb01533b0b309)
Build log [Build log](https://gist.github.com/HPCCSmoketest/33148f456eef2c84261eb01533b0b309#file-result-20-03-12-17-41-04-log)

Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  455 sec (00:07:35) |  121 sec (00:02:01) |   22 sec (00:00:22) |   18 sec (00:00:18) |    0 sec (00:00:00) |   15 sec (00:00:15) |  639 sec (00:10:39) |

```

2020-03-12 18:08 UTC, HPCCSmoketest commented
Process of PR-13384, label: archive_viewer_1 starts now.
The reason of this test is: New commit.
Commit ID: 8f8bf8fc2e30a0138ce407f016dabf82bc728912
Estimated completion time is ~0.2 hour(s)
centos 7.7.1908 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal

2020-03-12 18:25 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.7.1908 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
Sha: 8f8bf8fc2e30a0138ce407f016dabf82bc728912
Build: success
Install warning(s): 
npm WARN dojo-themes@1.14.1 requires a peer of dojo@1.14.1 but none is installed. You must install peer dependencies yourself.
npm WARN dojo-themes@1.14.1 requires a peer of dijit@1.14.1 but none is installed. You must install peer dependencies yourself.

Lint error(s): 
eclwatch/ECLSourceWidgetNew.js: line 81, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 83, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 87, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 88, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 90, col 13, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 91, col 41, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 121, col 56, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 122, col 25, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 123, col 25, let is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 124, col 25, let is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 126, col 77, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 128, col 25, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 132, col 25, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 134, col 66, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 137, col 48, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 138, col 33, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 139, col 33, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 146, col 58, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 147, col 33, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 147, col 82, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 151, col 37, const is available in ES6 (use esversion: 6) or Mozilla JS extensions (use moz).
eclwatch/ECLSourceWidgetNew.js: line 169, col 38, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 178, col 69, arrow function syntax (=>) is only available in ES6 (use esversion: 6).
eclwatch/ECLSourceWidgetNew.js: line 182, col 48, arrow function
 ... ( comment is too long, 236 lines, 14307 bytes, truncated) ... 
[Build error:](https://gist.github.com/f03143819b5597a679bcaaa8f670d7dd)
Build log [Build log](https://gist.github.com/HPCCSmoketest/f03143819b5597a679bcaaa8f670d7dd#file-result-20-03-12-18-08-14-log)

Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   15 sec (00:00:15) |  824 sec (00:13:44) |  126 sec (00:02:06) |   23 sec (00:00:23) |   17 sec (00:00:17) |    0 sec (00:00:00) |   14 sec (00:00:14) | 1019 sec (00:16:59) |

```

2020-03-13 14:12 UTC, HPCCSmoketest commented
Process of PR-13384, label: archive_viewer_1 starts now.
The reason of this test is: Forced to re-test.
Commit ID: b10dc3f9f732a8c0db3e4867a98617abbaf85aa9
Estimated completion time is ~0.1 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-193.ca-central-1.compute.internal

2020-03-13 14:22 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-193.ca-central-1.compute.internal
Sha: b10dc3f9f732a8c0db3e4867a98617abbaf85aa9
Build: success
Milestone:Install hpccsystems-platform-community_7.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  457 sec (00:07:37) |  116 sec (00:01:56) |   22 sec (00:00:22) |   17 sec (00:00:17) |    0 sec (00:00:00) |   15 sec (00:00:15) |  635 sec (00:10:35) |

2020-03-13 16:14 UTC, HPCCSmoketest commented
Process of PR-13384, label: archive_viewer_1 starts now.
The reason of this test is: New commit.
Commit ID: b10dc3f9f732a8c0db3e4867a98617abbaf85aa9
Estimated completion time is ~0.2 hour(s)
centos 7.7.1908 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal

2020-03-13 16:32 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.7.1908 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
Sha: b10dc3f9f732a8c0db3e4867a98617abbaf85aa9
Build: success
Milestone:Install hpccsystems-platform-community_7.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  815 sec (00:13:35) |  127 sec (00:02:07) |   22 sec (00:00:22) |   18 sec (00:00:18) |    0 sec (00:00:00) |   14 sec (00:00:14) | 1004 sec (00:16:44) |

2020-03-17 13:33 UTC, GordonSmith commented
Closing in favour of:  https://github.com/hpcc-systems/HPCC-Platform/pull/13516

2020-03-17 13:33 UTC, closed without merging