HPCC-23587 eclccserver on demand
hpcc-systems/HPCC-Platform pull request #13408
Opened 2020-02-27 14:21 UTC by richardkchapman

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [x] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:
Manual in minikube

2020-02-27 15:05 UTC, richardkchapman commented
@ghalliday Please review

2020-02-27 15:30 UTC, richardkchapman commented on dockerfiles/eclccserver/Dockerfile
> +USER root
Possibly should be in a base image

2020-02-27 15:32 UTC, richardkchapman commented on dockerfiles/eclccserver/Dockerfile
> +USER root
Also may need to make sure RBAC is properly set up to allow eclccserver to do this - it's working for me but I may have changed the default access controls. I'll raise a Jira to check that.

2020-02-27 15:33 UTC, richardkchapman commented on dockerfiles/eclccserver/Dockerfile
> +USER root
Also may need to make sure RBAC is properly set up to allow eclccserver to do this - it's working for me but I may have changed the default access controls. I'll raise a Jira to check that.

2020-02-27 16:08 UTC, HPCCSmoketest commented
Process of PR-13408, label: eclcc-cloud starts now.
The reason of this test is: Did not build yet.
Commit ID: 4f2db45e5ffff6a56e24bd7dd1b8ece701c4190f
Estimated completion time is ~0.9 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal

2020-02-27 16:15 UTC, ghalliday requested changes
@richardkchapman a couple of minor issues

2020-02-27 16:15 UTC, ghalliday commented on ecl/eclccserver/eclccserver.cpp
> +                DBGLOG("Using job yaml %s", jobYaml.str());
Already traced on line 466.  I suspect one of them should be deleted.

2020-02-27 16:15 UTC, ghalliday commented on system/jlib/jfile.cpp
> +#ifndef _CONTAINERIZED
Should also comment out the code in removeSentinalFile()

2020-02-27 17:04 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
Sha: 4f2db45e5ffff6a56e24bd7dd1b8ece701c4190f
Build: success
Milestone:Install hpccsystems-platform-community_7.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |116 |116 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |9 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |24 sec  (00:00:24) |
|setup (thor) |11 |11 |0 |46 sec  (00:00:46) |
|setup (roxie) |11 |11 |0 |22 sec  (00:00:22) |
|test (hthor) |871 |871 |0 |461 sec  (00:07:41) |
|test (thor) |810 |810 |0 |956 sec  (00:15:56) |
|test (roxie) |951 |951 |0 |605 sec  (00:10:05) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  768 sec (00:12:48) |  118 sec (00:01:58) |   22 sec (00:00:22) |   17 sec (00:00:17) | 2356 sec (00:39:16) |   17 sec (00:00:17) | 3306 sec (00:55:06) |

2020-02-27 19:00 UTC, HPCCSmoketest commented
Process of PR-13408, label: eclcc-cloud starts now.
The reason of this test is: New commit.
Commit ID: 8ac4ebf824941b5a62465ce89692a27c95c90d49
Estimated completion time is ~0.9 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal

2020-02-27 19:54 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
Sha: 8ac4ebf824941b5a62465ce89692a27c95c90d49
Build: success
Milestone:Install hpccsystems-platform-community_7.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |116 |116 |0 |0 |0 |36 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |9 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |26 sec  (00:00:26) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |22 sec  (00:00:22) |
|test (hthor) |871 |871 |0 |457 sec  (00:07:37) |
|test (thor) |810 |810 |0 |880 sec  (00:14:40) |
|test (roxie) |951 |951 |0 |601 sec  (00:10:01) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  767 sec (00:12:47) |  125 sec (00:02:05) |   22 sec (00:00:22) |   17 sec (00:00:17) | 2275 sec (00:37:55) |   19 sec (00:00:19) | 3233 sec (00:53:53) |

2020-02-28 09:54 UTC, HPCCSmoketest commented
Process of PR-13408, label: eclcc-cloud starts now.
The reason of this test is: New commit.
Commit ID: 1d1f8e88d7e151f73df10b9b88fe83d68a254e11
Estimated completion time is ~0.9 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal

2020-02-28 10:01 UTC, ghalliday reviewed
A couple of trivial comments

2020-02-28 10:05 UTC, richardkchapman commented on dockerfiles/hpcc/values.yaml
> +xroxie:
I treat values.yaml as a bit of a scratchpad for testing the bit currently under development.

Yes, at some point we should start regarding it as a proper example file, with documentation inline (comments) for all settings. There is a Jira open to do so.

2020-02-28 10:12 UTC, ghalliday approved these changes

2020-02-28 10:36 UTC, HPCCSmoketest commented
Process of PR-13408, label: eclcc-cloud starts now.
The reason of this test is: Forced to re-test.
Commit ID: 1d1f8e88d7e151f73df10b9b88fe83d68a254e11
Estimated completion time is ~0.5 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-176.ca-central-1.compute.internal

2020-02-28 10:48 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
Sha: 1d1f8e88d7e151f73df10b9b88fe83d68a254e11
Build: success
Milestone:Install hpccsystems-platform-community_7.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |116 |116 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |9 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |25 sec  (00:00:25) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |20 sec  (00:00:20) |
|test (hthor) |871 |871 |0 |458 sec  (00:07:38) |
|test (thor) |810 |810 |0 |941 sec  (00:15:41) |
|test (roxie) |951 |951 |0 |593 sec  (00:09:53) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  760 sec (00:12:40) |  114 sec (00:01:54) |   22 sec (00:00:22) |   17 sec (00:00:17) | 2305 sec (00:38:25) |   18 sec (00:00:18) | 3244 sec (00:54:04) |

2020-02-28 11:15 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-176.ca-central-1.compute.internal
Sha: 1d1f8e88d7e151f73df10b9b88fe83d68a254e11
Build: success
Milestone:Install hpccsystems-platform-community_7.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |116 |116 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |24 sec  (00:00:24) |
|setup (thor) |11 |11 |0 |42 sec  (00:00:42) |
|setup (roxie) |11 |11 |0 |26 sec  (00:00:26) |
|test (hthor) |871 |871 |0 |476 sec  (00:07:56) |
|test (thor) |810 |810 |0 |669 sec  (00:11:09) |
|test (roxie) |951 |951 |0 |416 sec  (00:06:56) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  253 sec (00:04:13) |  114 sec (00:01:54) |   22 sec (00:00:22) |   21 sec (00:00:21) | 1871 sec (00:31:11) |   19 sec (00:00:19) | 2309 sec (00:38:29) |

2020-02-28 11:20 UTC, HPCCSmoketest commented
Process of PR-13408, label: eclcc-cloud starts now.
The reason of this test is: Forced to re-test.
Commit ID: ada77d845279eb591abc8598d2a20c055aac72d4
Estimated completion time is ~0.5 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-75.ca-central-1.compute.internal

2020-02-28 11:23 UTC, merged

2020-02-28 11:53 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-75.ca-central-1.compute.internal
Sha: ada77d845279eb591abc8598d2a20c055aac72d4
Build: success
Milestone:Install hpccsystems-platform-community_7.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |116 |116 |0 |0 |0 |35 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |27 sec  (00:00:27) |
|setup (thor) |11 |11 |0 |41 sec  (00:00:41) |
|setup (roxie) |11 |11 |0 |17 sec  (00:00:17) |
|test (hthor) |871 |871 |0 |308 sec  (00:05:08) |
|test (thor) |810 |810 |0 |658 sec  (00:10:58) |
|test (roxie) |951 |951 |0 |258 sec  (00:04:18) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  251 sec (00:04:11) |  113 sec (00:01:53) |   22 sec (00:00:22) |   19 sec (00:00:19) | 1527 sec (00:25:27) |   19 sec (00:00:19) | 1960 sec (00:32:40) |