HPCC-22927 File service functions that can point to an external Esp should optionally take credentials
hpcc-systems/HPCC-Platform pull request #13552
Opened 2020-03-26 14:35 UTC by AttilaVamos

Update functions with username and password:

- fSprayFixed
- SprayFixed
- fSprayVariable
- SprayVariable
- fSprayDelimited
- SprayDelimited
- fSprayXml
- SprayXml
- fDespray
- Despray
- fCopy
- Copy
- fReplicate
- Replicate
- fMonitorLogicalFileName
- MonitorLogicalFileName
- fMonitorFile
- MonitorFile
- WaitDfuWorkunit
- AbortDfuWorkunit

Signed-off-by: Attila Vamos attila.vamos@gmail.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2020-03-26 14:40 UTC, HPCCSmoketest commented
Process of PR-13552, label: HPCC-22927-impr-7.8.x starts now.
The reason of this test is: Forced to re-test.
Commit ID: c1b342f901e5511c1b25d7045c637806387e6152
Estimated completion time is ~0.5 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-149.ca-central-1.compute.internal

2020-03-26 14:55 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-149.ca-central-1.compute.internal
Sha: c1b342f901e5511c1b25d7045c637806387e6152
Build: success
Milestone:Install hpccsystems-platform-community_7.8.1-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |120 |120 |0 |0 |0 |52 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |8 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |6 |5 |5 sec  (00:00:05) |
|setup (thor) |11 |6 |5 |5 sec  (00:00:05) |
|setup (roxie) |11 |6 |5 |5 sec  (00:00:05) |
|test (hthor) |0 |0 |0 |N/A |
|test (thor) |0 |0 |0 |N/A |
|test (roxie) |0 |0 |0 |N/A |


[Errors:](https://gist.github.com/0d943de1c66e4939abdfe2e978d38b7d)
- setup
  - hthor
    - 3\. [setup](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setup-no-wuid-log), 4\. [setup_fetch](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setup_fetch-no-wuid-log), 7\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setupsearchindex-no-wuid-log), 8\. [setupsq](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setupsq-no-wuid-log), 9\. [setupwordindex](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setupwordindex-no-wuid-log), 
  - thor
    - 3\. [setup](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setup-no-wuid-log), 4\. [setup_fetch](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setup_fetch-no-wuid-log), 7\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setupsearchindex-no-wuid-log), 8\. [setupsq](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setupsq-no-wuid-log), 9\. [setupwordindex](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setupwordindex-no-wuid-log), 
  - roxie
    - 3\. [setup](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setup-no-wuid-log), 4\. [setup_fetch](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setup_fetch-no-wuid-log), 7\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setupsearchindex-no-wuid-log), 8\. [setupsq](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setupsq-no-wuid-log), 9\. [setupwordindex](https://gist.github.com/HPCCSmoketest/0d943de1c66e4939abdfe2e978d38b7d#file-setupwordindex-no-wuid-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  472 sec (00:07:52) |  117 sec (00:01:57) |   22 sec (00:00:22) |   19 sec (00:00:19) |  224 sec (00:03:44) |   15 sec (00:00:15) |  878 sec (00:14:38) |

2020-03-26 19:50 UTC, HPCCSmoketest commented
Process of PR-13552, label: HPCC-22927-impr-7.8.x starts now.
The reason of this test is: Did not build yet.
Commit ID: c1b342f901e5511c1b25d7045c637806387e6152
Estimated completion time is ~0.9 hour(s)
centos 7.7.1908 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal

2020-03-26 20:12 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.7.1908 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
Sha: c1b342f901e5511c1b25d7045c637806387e6152
Build: success
Milestone:Install hpccsystems-platform-community_7.8.1-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |120 |120 |0 |0 |0 |52 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |8 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |6 |5 |6 sec  (00:00:06) |
|setup (thor) |11 |6 |5 |7 sec  (00:00:07) |
|setup (roxie) |11 |6 |5 |6 sec  (00:00:06) |
|test (hthor) |0 |0 |0 |N/A |
|test (thor) |0 |0 |0 |N/A |
|test (roxie) |0 |0 |0 |N/A |


[Errors:](https://gist.github.com/a80af394b9e794813bb4c637a739d6fd)
- setup
  - hthor
    - 3\. [setup](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setup-no-wuid-log), 4\. [setup_fetch](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setup_fetch-no-wuid-log), 7\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setupsearchindex-no-wuid-log), 8\. [setupsq](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setupsq-no-wuid-log), 9\. [setupwordindex](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setupwordindex-no-wuid-log), 
  - thor
    - 3\. [setup](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setup-no-wuid-log), 4\. [setup_fetch](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setup_fetch-no-wuid-log), 7\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setupsearchindex-no-wuid-log), 8\. [setupsq](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setupsq-no-wuid-log), 9\. [setupwordindex](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setupwordindex-no-wuid-log), 
  - roxie
    - 3\. [setup](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setup-no-wuid-log), 4\. [setup_fetch](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setup_fetch-no-wuid-log), 7\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setupsearchindex-no-wuid-log), 8\. [setupsq](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setupsq-no-wuid-log), 9\. [setupwordindex](https://gist.github.com/HPCCSmoketest/a80af394b9e794813bb4c637a739d6fd#file-setupwordindex-no-wuid-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  848 sec (00:14:08) |  123 sec (00:02:03) |   22 sec (00:00:22) |   17 sec (00:00:17) |  254 sec (00:04:14) |   14 sec (00:00:14) | 1287 sec (00:21:27) |

2020-03-27 18:34 UTC, HPCCSmoketest commented
Process of PR-13552, label: HPCC-22927-impr-7.8.x starts now.
The reason of this test is: Forced to re-test.
Commit ID: 38c34fb4a3281e874040a2f4a6dd7bd7c7859cd3
Estimated completion time is ~0.5 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-13.ca-central-1.compute.internal

2020-03-27 18:36 UTC, AttilaVamos commented
@jakesmith please review.

2020-03-27 18:40 UTC, HPCCSmoketest commented
Process of PR-13552, label: HPCC-22927-impr-7.8.x starts now.
The reason of this test is: New commit.
Commit ID: 38c34fb4a3281e874040a2f4a6dd7bd7c7859cd3
Estimated completion time is ~0.9 hour(s)
centos 7.7.1908 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal

2020-03-27 19:19 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-13.ca-central-1.compute.internal
Sha: 38c34fb4a3281e874040a2f4a6dd7bd7c7859cd3
Build: success
Milestone:Install hpccsystems-platform-community_7.8.1-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |120 |120 |0 |0 |0 |52 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |25 sec  (00:00:25) |
|setup (thor) |11 |11 |0 |43 sec  (00:00:43) |
|setup (roxie) |11 |11 |0 |16 sec  (00:00:16) |
|test (hthor) |873 |873 |0 |417 sec  (00:06:57) |
|test (thor) |812 |812 |0 |762 sec  (00:12:42) |
|test (roxie) |953 |953 |0 |401 sec  (00:06:41) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   10 sec (00:00:10) |  639 sec (00:10:39) |  118 sec (00:01:58) |   22 sec (00:00:22) |   18 sec (00:00:18) | 1900 sec (00:31:40) |   19 sec (00:00:19) | 2726 sec (00:45:26) |

2020-03-27 19:44 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.7.1908 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
Sha: 38c34fb4a3281e874040a2f4a6dd7bd7c7859cd3
Build: success
Milestone:Install hpccsystems-platform-community_7.8.1-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |120 |120 |0 |0 |0 |53 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |9 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |29 sec  (00:00:29) |
|setup (thor) |11 |11 |0 |45 sec  (00:00:45) |
|setup (roxie) |11 |11 |0 |20 sec  (00:00:20) |
|test (hthor) |873 |873 |0 |633 sec  (00:10:33) |
|test (thor) |812 |812 |0 |968 sec  (00:16:08) |
|test (roxie) |953 |953 |0 |715 sec  (00:11:55) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   10 sec (00:00:10) |  924 sec (00:15:24) |  126 sec (00:02:06) |   23 sec (00:00:23) |   17 sec (00:00:17) | 2672 sec (00:44:32) |   17 sec (00:00:17) | 3789 sec (01:03:09) |

2020-03-30 11:04 UTC, jakesmith requested changes

2020-03-30 11:04 UTC, jakesmith commented on roxie/udplib/udptrr.cpp
> +            unsigned timeoutExpires = msTick() + 5000;
@AttilaVamos - looks like this PR includes some unintentional changes.

2020-03-30 11:46 UTC, jakesmith commented
Have added a few comments, but there's issue around storing password in the DFU workunit in general.

We should not be storing password in the workunit.
It looks like setUserAuth might do too already, but if so that needs fixing as well, it's a security leak.

And I don't think it is needed anyway.
The places where getPassword is called and a IUserDescriptor is formed/set, it is then passed to DFS,
but it ends up calling serializeWithoutPassword ...
Because Dali only does LDAP lookups based on username.

It's okay to pass the password to the esp service, but not to store it in the workunit.
So we should not add password to workunit here, and I think it will still work without it.

@AttilaVamos - can you check, remove the code that stores the password in the DFU workunit(s) and retreives it, and test if it continues to work as expected?

2020-03-30 12:46 UTC, closed without merging