HPCC-23823 Report disk usages for eclcc server
hpcc-systems/HPCC-Platform pull request #13595
Opened 2020-04-03 19:58 UTC by wangkx

Also for ecl server and ecl scheduler.
Remove extra code from esp/services/ws_machine/ws_machineService.cpp. 

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2020-04-03 20:00 UTC, wangkx commented
@jakesmith please review

2020-04-03 20:02 UTC, HPCCSmoketest commented
Process of PR-13595, label: disk_usage_empty starts now.
The reason of this test is: Forced to re-test.
Commit ID: 65cf2bf6c587d1f683b07953a4ba2868406dce29
Estimated completion time is ~0.5 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-49.ca-central-1.compute.internal

2020-04-03 20:05 UTC, HPCCSmoketest commented
Process of PR-13595, label: disk_usage_empty starts now.
The reason of this test is: Did not build yet.
Commit ID: 65cf2bf6c587d1f683b07953a4ba2868406dce29
Estimated completion time is ~0.9 hour(s)
centos 7.7.1908 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal

2020-04-03 20:45 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-49.ca-central-1.compute.internal
Sha: 65cf2bf6c587d1f683b07953a4ba2868406dce29
Build: success
Milestone:Install hpccsystems-platform-community_7.8.3-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |120 |120 |0 |0 |0 |52 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |8 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |25 sec  (00:00:25) |
|setup (thor) |11 |11 |0 |45 sec  (00:00:45) |
|setup (roxie) |11 |11 |0 |21 sec  (00:00:21) |
|test (hthor) |873 |873 |0 |306 sec  (00:05:06) |
|test (thor) |812 |812 |0 |699 sec  (00:11:39) |
|test (roxie) |953 |953 |0 |410 sec  (00:06:50) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  642 sec (00:10:42) |  118 sec (00:01:58) |   22 sec (00:00:22) |   17 sec (00:00:17) | 1741 sec (00:29:01) |   19 sec (00:00:19) | 2568 sec (00:42:48) |

2020-04-03 21:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.7.1908 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
Sha: 65cf2bf6c587d1f683b07953a4ba2868406dce29
Build: success
Milestone:Install hpccsystems-platform-community_7.8.3-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |120 |120 |0 |0 |0 |53 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |9 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |29 sec  (00:00:29) |
|setup (thor) |11 |11 |0 |45 sec  (00:00:45) |
|setup (roxie) |11 |11 |0 |20 sec  (00:00:20) |
|test (hthor) |873 |873 |0 |624 sec  (00:10:24) |
|test (thor) |812 |812 |0 |973 sec  (00:16:13) |
|test (roxie) |953 |953 |0 |699 sec  (00:11:39) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   12 sec (00:00:12) |  928 sec (00:15:28) |  122 sec (00:02:02) |   22 sec (00:00:22) |   18 sec (00:00:18) | 2651 sec (00:44:11) |   18 sec (00:00:18) | 3771 sec (01:02:51) |

2020-04-07 09:00 UTC, jakesmith requested changes

2020-04-07 09:00 UTC, jakesmith commented on esp/services/ws_machine/ws_machineService.cpp
> +        targetClusterInfo->getECLCCServerName(eclccServer);
since a cluster can only a eclccserver or a eclserver, it's only worth having a single getEclServer() method

2020-04-07 09:01 UTC, jakesmith commented
@wangkx - looks good, only issue is re. avoiding need to pick up both eclccserver and eclserver

2020-04-07 12:33 UTC, wangkx commented on esp/services/ws_machine/ws_machineService.cpp
> -            componentType.set("sasha");
It is unnecessary because the componentType has been set by calling findComponentTypeFromProcessType() in line 2511.

2020-04-07 15:37 UTC, wangkx commented on common/environment/environment.cpp
> +    if (!isEmptyString(eclccServerName))
I need to know whether it is an eclserver or eclcc. Should I add a method: isECLCCServer() here or find it outside this class?

2020-04-07 15:38 UTC, jakesmith commented on common/environment/environment.cpp
> +    if (!isEmptyString(eclccServerName))
ok, didn't realize you did.. why is that? what code depends on it?

2020-04-07 16:05 UTC, wangkx commented on common/environment/environment.cpp
> +    if (!isEmptyString(eclccServerName))
@jakesmith I need the information about ECLCC / eclserver instances. Also I need to tell an ESP client whether a component is ECLCC or eclserver.

2020-04-08 13:57 UTC, jakesmith commented on common/environment/environment.cpp
> +    if (!isEmptyString(eclccServerName))
@wangkx ok, add a isLegacyEclServer() (if it's an EclServer).

2020-04-08 15:22 UTC, HPCCSmoketest commented
Process of PR-13595, label: disk_usage_empty starts now.
The reason of this test is: Forced to re-test.
Commit ID: c5b82a5e7ef799aad460f278b8c372f82085c508
Estimated completion time is ~0.5 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-183.ca-central-1.compute.internal

2020-04-08 15:42 UTC, HPCCSmoketest commented
Process of PR-13595, label: disk_usage_empty starts now.
The reason of this test is: New commit.
Commit ID: c5b82a5e7ef799aad460f278b8c372f82085c508
Estimated completion time is ~0.9 hour(s)
centos 7.7.1908 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal

2020-04-08 16:10 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-183.ca-central-1.compute.internal
Sha: c5b82a5e7ef799aad460f278b8c372f82085c508
Build: success
Milestone:Install hpccsystems-platform-community_7.8.3-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |120 |120 |0 |0 |0 |54 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |8 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |29 sec  (00:00:29) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |21 sec  (00:00:21) |
|test (hthor) |873 |873 |0 |568 sec  (00:09:28) |
|test (thor) |812 |812 |0 |702 sec  (00:11:42) |
|test (roxie) |953 |953 |0 |423 sec  (00:07:03) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  683 sec (00:11:23) |  117 sec (00:01:57) |   22 sec (00:00:22) |   18 sec (00:00:18) | 2025 sec (00:33:45) |   18 sec (00:00:18) | 2892 sec (00:48:12) |

2020-04-08 16:45 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.7.1908 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
Sha: c5b82a5e7ef799aad460f278b8c372f82085c508
Build: success
Milestone:Install hpccsystems-platform-community_7.8.3-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |120 |120 |0 |0 |0 |53 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |8 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |27 sec  (00:00:27) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |22 sec  (00:00:22) |
|test (hthor) |873 |873 |0 |574 sec  (00:09:34) |
|test (thor) |812 |812 |0 |961 sec  (00:16:01) |
|test (roxie) |953 |953 |0 |712 sec  (00:11:52) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  947 sec (00:15:47) |  123 sec (00:02:03) |   24 sec (00:00:24) |   17 sec (00:00:17) | 2581 sec (00:43:01) |   18 sec (00:00:18) | 3718 sec (01:01:58) |

2020-04-08 17:18 UTC, wangkx commented
@jakesmith please review.

2020-04-14 08:36 UTC, jakesmith commented
@wangkx - looks fine, please squash ready to be merged.

2020-04-14 13:11 UTC, HPCCSmoketest commented
Process of PR-13595, label: disk_usage_empty starts now.
The reason of this test is: Forced to re-test.
Commit ID: 242839c2ed11b3023a002fcf6f60c2ede6824f45
Estimated completion time is ~0.5 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-218.ca-central-1.compute.internal

2020-04-14 13:55 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-218.ca-central-1.compute.internal
Sha: 242839c2ed11b3023a002fcf6f60c2ede6824f45
Build: success
Milestone:Install hpccsystems-platform-community_7.8.5-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |120 |120 |0 |0 |0 |53 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |2 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |7 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |11 |11 |0 |30 sec  (00:00:30) |
|setup (thor) |11 |11 |0 |44 sec  (00:00:44) |
|setup (roxie) |11 |11 |0 |23 sec  (00:00:23) |
|test (hthor) |873 |873 |0 |369 sec  (00:06:09) |
|test (thor) |812 |812 |0 |695 sec  (00:11:35) |
|test (roxie) |953 |953 |0 |408 sec  (00:06:48) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  649 sec (00:10:49) |  118 sec (00:01:58) |   22 sec (00:00:22) |   19 sec (00:00:19) | 1806 sec (00:30:06) |   19 sec (00:00:19) | 2642 sec (00:44:02) |

2020-04-14 14:15 UTC, wangkx commented
@richardkchapman this PR is ready to be merged.

2020-04-14 15:51 UTC, merged