HPCC-25470 Add option to avoid scanning all KJ parts when mapping
hpcc-systems/HPCC-Platform pull request #14659
Opened 2021-03-05 19:11 UTC by jakesmith

HINT(keyedJoinAssumePrimary(true))

Will prevent KJ from checking every physical part in an index
involved in a keyed join.
This can be very expensive if it's a large super index.

When this option is used, it will assume the primary parts
exist, and will not utilize any secondary copies.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-03-05 19:13 UTC, jakesmith commented
@ghalliday - please take a look - leaving as draft PR for now to discuss.

This is essentially a workaround for when a very large super index is used.
The current code (without this option on), can take minutes to scan the 1000's of parts involved.

The scan for other copies (if primary is missing) isn't really correct here anyway, it would spot if primary is missing at initialization time, and use replica, but can't spot it once serialized to slave.

2021-03-09 10:36 UTC, HPCCSmoketest commented
Process of PR-14659, label: hpcc-25470-kj-assume-primary-option starts now.
The reason of this test is: Forced to re-test.
Commit ID: 807e5f6d872cbb1d3197da16d0d755b2dd09d77b
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-21.ca-central-1.compute.internal

2021-03-09 10:36 UTC, richardkchapman requested changes, later dismissed

2021-03-09 11:09 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-21.ca-central-1.compute.internal
Sha: 807e5f6d872cbb1d3197da16d0d755b2dd09d77b
Build: success
Milestone:Install hpccsystems-platform-community_7.8.81-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |120 |120 |0 |0 |0 |37 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |6 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |8 |8 |0 |21 sec  (00:00:21) |
|setup (thor) |8 |8 |0 |42 sec  (00:00:42) |
|setup (roxie) |11 |11 |0 |15 sec  (00:00:15) |
|test (hthor) |887 |887 |0 |681 sec  (00:11:21) |
|test (thor) |822 |822 |0 |981 sec  (00:16:21) |
|test (roxie) |967 |967 |0 |800 sec  (00:13:20) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  551 sec (00:09:11) |  103 sec (00:01:43) |   20 sec (00:00:20) |   16 sec (00:00:16) | 1267 sec (00:21:07) |   19 sec (00:00:19) | 1984 sec (00:33:04) |

2021-03-09 12:30 UTC, jakesmith commented on thorlcr/thorutil/thormisc.hpp
> +#define THOROPT_KJ_ASSUME_PRIMARY "keyedJoinAssumePrimary"      // assume priamry part exists (don't check when mapping, which can be slow)
Corrected

2021-03-09 12:32 UTC, HPCCSmoketest commented
Process of PR-14659, label: hpcc-25470-kj-assume-primary-option starts now.
The reason of this test is: Forced to re-test.
Commit ID: cb9453f4aee1d22cb638a9ba08e9d97d7e9f424b
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-197.ca-central-1.compute.internal

2021-03-09 12:33 UTC, jakesmith commented
In addition to the option, I noticed that a file part was being needlessly rechecked (file->exists()), if the node group contained multiple matches, which will happen if slavesPerNode>1.
I have moved that part exists check out of that loop and avoided the loop completely in the file part doesn't exist.
So that change should speed things up in the normal case (without option) where running on clusters with multiple slaves per node.

@richardkchapman @mckellyln - please review

2021-03-09 13:05 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-197.ca-central-1.compute.internal
Sha: cb9453f4aee1d22cb638a9ba08e9d97d7e9f424b
Build: success
Milestone:Install hpccsystems-platform-community_7.8.81-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |120 |120 |0 |0 |0 |37 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |5 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |8 |8 |0 |23 sec  (00:00:23) |
|setup (thor) |8 |8 |0 |41 sec  (00:00:41) |
|setup (roxie) |11 |11 |0 |21 sec  (00:00:21) |
|test (hthor) |887 |887 |0 |683 sec  (00:11:23) |
|test (thor) |822 |822 |0 |983 sec  (00:16:23) |
|test (roxie) |967 |967 |0 |802 sec  (00:13:22) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  543 sec (00:09:03) |  105 sec (00:01:45) |   19 sec (00:00:19) |   17 sec (00:00:17) | 1277 sec (00:21:17) |   19 sec (00:00:19) | 1988 sec (00:33:08) |

2021-03-09 13:31 UTC, mckellyln commented
Moving the exists() is good because I have seen when that gets called many times rapidly and can cause port exhaustion from TIME_WAITs.

2021-03-09 16:16 UTC, richardkchapman commented
@jakesmith Looks like it needs squashing?

2021-03-09 17:01 UTC, jakesmith commented
@richardkchapman @mckellyln - squashed.

2021-03-09 17:03 UTC, HPCCSmoketest commented
Process of PR-14659, label: hpcc-25470-kj-assume-primary-option starts now.
The reason of this test is: Forced to re-test.
Commit ID: 7e651d7662af45f1f49732ec34e9d1556d36919c
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-224.ca-central-1.compute.internal

2021-03-09 17:36 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-224.ca-central-1.compute.internal
Sha: 7e651d7662af45f1f49732ec34e9d1556d36919c
Build: success
Milestone:Install hpccsystems-platform-community_7.8.81-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |120 |120 |0 |0 |0 |37 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |6 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |8 |8 |0 |20 sec  (00:00:20) |
|setup (thor) |8 |8 |0 |40 sec  (00:00:40) |
|setup (roxie) |11 |11 |0 |21 sec  (00:00:21) |
|test (hthor) |887 |887 |0 |668 sec  (00:11:08) |
|test (thor) |822 |822 |0 |974 sec  (00:16:14) |
|test (roxie) |967 |967 |0 |788 sec  (00:13:08) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    7 sec (00:00:07) |  554 sec (00:09:14) |  106 sec (00:01:46) |   20 sec (00:00:20) |   18 sec (00:00:18) | 1262 sec (00:21:02) |   19 sec (00:00:19) | 1986 sec (00:33:06) |

2021-03-10 15:01 UTC, mckellyln approved these changes
Looks fine.

2021-03-10 15:33 UTC, richardkchapman approved these changes

2021-03-10 15:33 UTC, merged