HPCC-25489 LDAP credentials should be configurable as secrets
hpcc-systems/HPCC-Platform pull request #14789
Opened 2021-03-31 12:57 UTC by RussWhitehead

Enabled LDAP Admin username/pwd to be optionally configured to be retrieved from
secrets repo (Vault or local secrets). Added ESP category to secrets in values.yaml,
added secret Key and Vault ID to configuration, and updated LDAP startup to optionally
query values from repo if keys specified in configuration

Signed-off-by: Russ Whitehead <william.whitehead@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-03-31 13:01 UTC, HPCCSmoketest commented
Process of PR-14789, label: ldapSecrets starts now.
The reason of this test is: Forced to re-test.
Commit ID: 224daa82fd20e117b49996c1d81b61d2571e4464
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-154.ca-central-1.compute.internal

2021-04-01 15:31 UTC, richardkchapman commented
@RussWhitehead Should this target 8.0.x ?

2021-04-15 12:47 UTC, RussWhitehead commented
@richardkchapman Will rebase with next commit. @afishbeck Please review

2021-04-26 23:18 UTC, afishbeck requested changes

2021-04-26 23:18 UTC, afishbeck commented on system/security/LdapSecurity/ldapconnection.cpp
> +                secretTree.setown(getVaultSecret("esp", vaultId, systemUserSecretKey.str(), nullptr));
"esp" as the category worked as a proof of concept, but if components other than ESP (like DALI, any others?) then the category has to be something that identifies the group of components.  We need a new category like "authn".  Because we don't want the secrets to show up anywhere except the exact components that need them... and there is no current category that would get it on only ESP and DALI.  A good example of a category like that is "codeVerify".. it's secrets end up on ESP and eclccserver.

2021-04-26 23:18 UTC, afishbeck commented on initfiles/componentfiles/configschema/xsd/ldapserver.xsd
> +                <xs:attribute name="systemUserVaultID" type="xs:string" hpcc:displayName="System User Vault ID"
I may have missed something, but these two values need to be settable through the helm chart.  
Well actually we have 2 choices... 1. use a well known name as the secret name and search for it in our new category.  or 2. add helm configuration as you've done here for configmgr.

If you want to use a well defined name like for example "ldapSystemUser" under the new secrets category of "authn" then you just have to change your call to getSecret below to:

secretTree.setown(getSecret("authn", "ldapSystemUser"));

That method will search the category local secrets and vaults to find the secret with that name.

2021-05-12 16:56 UTC, HPCCSmoketest commented
Process of PR-14789, label: ldapSecrets starts now.
The reason of this test is: Forced to re-test.
Commit ID: 9dfb4813c69b11edc8fbece17344bcdbdbb88b18
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-208.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-05-12 17:32 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-208.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 9dfb4813c69b11edc8fbece17344bcdbdbb88b18
Build: success
Milestone:Install hpccsystems-platform-community_8.1.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |158 |158 |0 |0 |0 |58 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |5 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |25 sec  (00:00:25) |
|setup (thor) |9 |9 |0 |40 sec  (00:00:40) |
|setup (roxie) |19 |19 |0 |19 sec  (00:00:19) |
|test (hthor) |981 |981 |0 |872 sec  (00:14:32) |
|test (thor) |892 |892 |0 |1033 sec  (00:17:13) |
|test (roxie) |1050 |1050 |0 |976 sec  (00:16:16) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  640 sec (00:10:40) |  110 sec (00:01:50) |   21 sec (00:00:21) |   19 sec (00:00:19) | 1347 sec (00:22:27) |   20 sec (00:00:20) | 2165 sec (00:36:05) |

2021-05-12 23:16 UTC, afishbeck commented on helm/hpcc/values.yaml
> +    MyLDAPServerKey: MyLDAPServerValue
This example should be removed or commented out.  If someone uses this and the secret doesn't exist their pods won't run.. so this should only be added when the user really wants to use ldap.

2021-05-12 23:21 UTC, afishbeck commented on system/security/LdapSecurity/ldapconnection.cpp
> +                WARNLOG("Please specify either systemCommonName or systemUserSecretKey in configuration");
Warning is a little confusing saying that you have to specify one of them, but really the issue is that they specified both.  Should probably be something like:

 WARNLOG("Please specify either systemCommonName or systemUserSecretKey but not both in configuration");

2021-05-12 23:24 UTC, afishbeck commented on system/security/LdapSecurity/ldapconnection.cpp
> +            DBGLOG("Retrieving LDAP Admin username/password from secrets repo: %s %s", !vaultId.isEmpty() ? vaultId.str() : "", systemUserSecretKey.str());
StringBuffer::str() won't return nullptr so 
```
!vaultId.isEmpty() ? vaultId.str() : ""
```
is redundant, just "vaultId.str()" should be enough.

2021-05-12 23:25 UTC, afishbeck commented on system/security/LdapSecurity/ldapconnection.cpp
> +                secretTree.setown(getVaultSecret("esp", vaultId, systemUserSecretKey.str(), nullptr));
You've added the authn category above, so you can replace "esp" with "authn" here and below.

2021-05-12 23:27 UTC, afishbeck requested changes
@RussWhitehead several comments.

2021-06-15 15:05 UTC, closed without merging