HPCC-25783 add dropzone storage example settings.
hpcc-systems/HPCC-Platform pull request #14939
Opened 2021-05-09 15:09 UTC by xwang2713

These include "auto" and "retained" dropzone examples for local, Azure
and AWS.

NFS support either will be added later or directly added to NFS PR which is in reviewing process now.

To enable auto storage creation "storage.dropzoneStorage" is added to HPCC helm chart schema and values.yaml.
Also it is added to global ConfigMap if no dropzone plane supplied.

Tested on local, Azure and AWS

2021-05-09 15:09 UTC, HPCCSmoketest commented
Process of PR-14939, label: HPCC-25783-add-dropzone-storage is skipped.
The reason is: It is related to containerised environment only.
Commit ID: ffd632be3373a68f8ec74ec16255d2e035abbe72
OS: centos 7.7.1908 (Linux 3.10.0-327.10.1.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: hpcc-platform-dev-el7-smoketest-2
 Git:  git version 1.8.3.1

2021-05-10 10:37 UTC, HPCCSmoketest commented
Process of PR-14939, label: HPCC-25783-add-dropzone-storage is skipped.
The reason is: It is related to containerised environment only.
Commit ID: ffd632be3373a68f8ec74ec16255d2e035abbe72
OS: centos 7.7.1908 (Linux 3.10.0-327.10.1.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: hpcc-platform-dev-el7-smoketest-2
 Git:  git version 1.8.3.1

2021-05-13 12:48 UTC, jakesmith reviewed
I think it looks ok.
Not entirely sure we need it though.
You can define an arbitrary number of planes with labels already in the example charts,
and dfuserver should automatically pick up all that are labeled as 'lz' and use them as drop zones.

This change/PR implies there's should only be one (by dropzoneStorage:), a bit like dataStorage: which we're trying to move away from I think, with planes: and engines default storage planes being the primary way you define storage.

However, planes need to point to a pvc, where as *Storage: can point to a storageClass only and auto-instantiate ephemeral storage.

I suspect we should not be adding this to the main hpcc chart, or extending the example.
I think a better route (if anything) would be to add an example that creates some PVC from storage class (includnig "" for ephemeral). Then they could be used by planes direclty.

@ghalliday - my have some thoughts on this.

2021-05-13 13:50 UTC, ghalliday commented
I don't really understand this change for a few reasons.

* As jake says the helm charts already support multiple drop zones by adding a 'lz' label to a plane.  I don't think the main helm charts need any change.
* The main reason for a drop zone is so that an external process can copy files to and from the drop zone.  That means they must be externally accessible.  I don't think there is any point in creating an implicit one because it can't be accessed externally.

Have I missed something?

The following might be useful as examples:
* azure blob storage account - users can directly copy to blob storage
* A legacy bare metal storage dropzone (with a dafilesrv running on it)
* Possibly an implicit drop zone for the local file example

I think they would need to be examples to be pasted into an existing values.yaml, not something that can automatically be combined.

2021-05-14 15:12 UTC, ghalliday requested changes
See comments above

2021-05-18 02:52 UTC, xwang2713 commented
Let me try adding plane with label "lz" for ephemeral  storage. I am not sure it will work without same change.

2021-05-18 08:09 UTC, ghalliday commented
Following on from yesterdays discussion, it will make sense to have an ephemeral dropzone defined in our standard values.yaml - it would allow drop zone functionality to be tested and files could be uploaded using the esp upload function.

It is possible to define a bare metal drop zone, by using a storage plane that is based on a hostGroup.

dfuplus currently has to use srcip=127.0.0.1 srcfilename=<plane-prefix>/<relative-of-file> nolocal=1, which is ugly.  See HPCC-25910 to improve this.

2021-05-18 08:10 UTC, ghalliday commented on helm/examples/local/hpcc-localfile/values.schema.json
> +        "mountPrefix": {
unused.

2021-05-20 09:32 UTC, HPCCSmoketest commented
Process of PR-14939, label: HPCC-25783-add-dropzone-storage is skipped.
The reason is: It is related to containerised environment only.
Commit ID: ffd632be3373a68f8ec74ec16255d2e035abbe72
OS: Ubuntu 16.04 (Linux 4.4.0-210-generic)
 GCC:  gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
 Host: ati-VirtualBox
 Git:  git version 2.7.4

2021-06-14 10:49 UTC, HPCCSmoketest commented
Process of PR-14939, label: HPCC-25783-add-dropzone-storage is skipped.
The reason is: It is related to containerised environment only.
Commit ID: ffd632be3373a68f8ec74ec16255d2e035abbe72
OS: centos 7.7.1908 (Linux 3.10.0-1062.9.1.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: hpcc-platform-dev-el7-smoketest-2.novalocal
 Git:  git version 1.8.3.1

2021-06-14 10:50 UTC, HPCCSmoketest commented
Process of PR-14939, label: HPCC-25783-add-dropzone-storage starts now.
The reason of this test is: Forced to re-test.
Commit ID: ffd632be3373a68f8ec74ec16255d2e035abbe72
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-47.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-06-14 10:50 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-47.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: ffd632be3373a68f8ec74ec16255d2e035abbe72
Error in git command, should skip build and test.

[Build error:](https://gist.github.com/42617c22a2f97980e9fa052589c64b36)
Build log [Build log](https://gist.github.com/HPCCSmoketest/42617c22a2f97980e9fa052589c64b36#file-result-21-06-14-10-50-16-log)

2021-06-29 04:30 UTC, xwang2713 commented
With gavin's change for dropzone in storage examples this PR is not needed.

2021-06-29 04:30 UTC, closed without merging