HPCC-25854 WsSQL nested dataset support should be versioned
hpcc-systems/HPCC-Platform pull request #14965
Opened 2021-05-14 17:51 UTC by rpastrana

- Versions nested dataset related interface changes
- Improves logic rejecting normalized column arithmatic

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-05-14 17:52 UTC, rpastrana commented
@wangkx please review. https://github.com/hpcc-systems/HPCC-Platform/pull/14644 should have been version aware

2021-05-14 17:54 UTC, HPCCSmoketest commented
Process of PR-14965, label: HPCC-25854-wssqlnestedupdate starts now.
The reason of this test is: Forced to re-test.
Commit ID: cbbda77b7bb80fa2150e95f4f4068fa2377f4b20
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-191.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-05-14 17:55 UTC, rpastrana commented
@Michael-Gardner once this PR is merged, we'll need to target this HPCC version in the hpcc4j repo to avoid false negative junit failures

2021-05-14 18:29 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-191.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: cbbda77b7bb80fa2150e95f4f4068fa2377f4b20
Build: success
Milestone:Install hpccsystems-platform-community_8.0.15-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |158 |158 |0 |0 |0 |58 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |5 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |24 sec  (00:00:24) |
|setup (thor) |9 |9 |0 |40 sec  (00:00:40) |
|setup (roxie) |19 |19 |0 |19 sec  (00:00:19) |
|test (hthor) |980 |980 |0 |891 sec  (00:14:51) |
|test (thor) |891 |891 |0 |1010 sec  (00:16:50) |
|test (roxie) |1050 |1050 |0 |957 sec  (00:15:57) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  605 sec (00:10:05) |  111 sec (00:01:51) |   21 sec (00:00:21) |   17 sec (00:00:17) | 1322 sec (00:22:02) |   19 sec (00:00:19) | 2103 sec (00:35:03) |

2021-05-17 17:47 UTC, wangkx requested changes
@rpastrana please see my minor comments

2021-05-17 17:47 UTC, wangkx commented on esp/services/ws_sql/SQL2ECL/HPCCFileCache.cpp
> +					   IArrayOf<HPCCColumnMetaData> * ccols = currcol.getChildColumns();
wrong indent

2021-05-17 17:47 UTC, wangkx commented on esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.cpp
> +                    throw MakeStringException(-1, "Cannot apply arithmetic logic to normalized nested column: '%s'!\n", invalidexp.str());
Please use makeStringExceptionV

2021-05-17 17:47 UTC, wangkx commented on esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.cpp
> +                    throw MakeStringException(-1, "Cannot apply arithmetic logic to normalized nested column: '%s'!\n", invalidexp.str());
Please use makeStringExceptionV

2021-05-17 17:47 UTC, wangkx commented on esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.cpp
> +                    throw MakeStringException(-1, "Cannot apply arithmetic logic to normalized nested column: '%s'!\n", expstr.str());
Please use makeStringExceptionV

2021-05-17 17:47 UTC, wangkx commented on esp/services/ws_sql/ws_sqlService.cpp
> +        tmpHPCCFileCache->populateTablesResponse(resp, req.getTableFilter(), context.getClientVersion() > 3.05);
Better use '>= 3.06'

2021-05-17 19:07 UTC, HPCCSmoketest commented
Process of PR-14965, label: HPCC-25854-wssqlnestedupdate starts now.
The reason of this test is: Forced to re-test.
Commit ID: 37eb4f448ab59dc6f8931971e09ddd488700dc21
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-5.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-05-17 19:43 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-5.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 37eb4f448ab59dc6f8931971e09ddd488700dc21
Build: success
Milestone:Install hpccsystems-platform-community_8.0.15-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |158 |158 |0 |0 |0 |58 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |6 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |24 sec  (00:00:24) |
|setup (thor) |9 |9 |0 |40 sec  (00:00:40) |
|setup (roxie) |19 |19 |0 |20 sec  (00:00:20) |
|test (hthor) |980 |980 |0 |895 sec  (00:14:55) |
|test (thor) |891 |891 |0 |1071 sec  (00:17:51) |
|test (roxie) |1050 |1050 |0 |951 sec  (00:15:51) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  600 sec (00:10:00) |  107 sec (00:01:47) |   23 sec (00:00:23) |   16 sec (00:00:16) | 1384 sec (00:23:04) |   19 sec (00:00:19) | 2158 sec (00:35:58) |

2021-05-18 17:46 UTC, wangkx approved these changes
@rpastrana looks fine.

2021-05-19 10:40 UTC, merged