HPCC-25950 Institute lower default log level
hpcc-systems/HPCC-Platform pull request #15005
Opened 2021-06-02 19:32 UTC by rpastrana

- Updates global default log level
- Updates helm chart global default log level

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-06-02 19:36 UTC, HPCCSmoketest commented
Process of PR-15005, label: HPCC-25950-DefaultJlogLevel starts now.
The reason of this test is: Forced to re-test.
Commit ID: 7aa6f63ba7b6c04e862f3429db91079bea324ce2
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-69.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-06-02 20:10 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-69.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 7aa6f63ba7b6c04e862f3429db91079bea324ce2
Build: success
Milestone:Install hpccsystems-platform-community_8.2.1-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |158 |158 |0 |0 |0 |58 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |5 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |24 sec  (00:00:24) |
|setup (thor) |9 |9 |0 |40 sec  (00:00:40) |
|setup (roxie) |19 |19 |0 |20 sec  (00:00:20) |
|test (hthor) |981 |981 |0 |877 sec  (00:14:37) |
|test (thor) |892 |892 |0 |1046 sec  (00:17:26) |
|test (roxie) |1050 |1050 |0 |932 sec  (00:15:32) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  506 sec (00:08:26) |  109 sec (00:01:49) |   22 sec (00:00:22) |   16 sec (00:00:16) | 1360 sec (00:22:40) |   19 sec (00:00:19) | 2041 sec (00:34:01) |

2021-06-02 20:17 UTC, HPCCSmoketest commented
Process of PR-15005, label: HPCC-25950-DefaultJlogLevel starts now.
The reason of this test is: Forced to re-test.
Commit ID: a000baaadf0a9b5ffe831bb60f4dfa83351c1977
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-4.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-06-02 20:51 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-4.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: a000baaadf0a9b5ffe831bb60f4dfa83351c1977
Build: success
Milestone:Install hpccsystems-platform-community_8.2.1-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |158 |158 |0 |0 |0 |57 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |5 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |24 sec  (00:00:24) |
|setup (thor) |9 |9 |0 |40 sec  (00:00:40) |
|setup (roxie) |19 |19 |0 |19 sec  (00:00:19) |
|test (hthor) |981 |981 |0 |878 sec  (00:14:38) |
|test (thor) |892 |892 |0 |1050 sec  (00:17:30) |
|test (roxie) |1050 |1050 |0 |939 sec  (00:15:39) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  507 sec (00:08:27) |  108 sec (00:01:48) |   21 sec (00:00:21) |   16 sec (00:00:16) | 1362 sec (00:22:42) |   19 sec (00:00:19) | 2042 sec (00:34:02) |

2021-06-03 10:52 UTC, HPCCSmoketest commented
Process of PR-15005, label: HPCC-25950-DefaultJlogLevel starts now.
The reason of this test is: Base branch changed.
Commit ID: a000baaadf0a9b5ffe831bb60f4dfa83351c1977
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-155.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-06-03 11:27 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-155.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: a000baaadf0a9b5ffe831bb60f4dfa83351c1977
Build: success
Milestone:Install hpccsystems-platform-community_8.2.1-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |158 |158 |0 |0 |0 |58 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |5 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |24 sec  (00:00:24) |
|setup (thor) |9 |9 |0 |40 sec  (00:00:40) |
|setup (roxie) |19 |19 |0 |19 sec  (00:00:19) |
|test (hthor) |981 |981 |0 |881 sec  (00:14:41) |
|test (thor) |892 |892 |0 |1104 sec  (00:18:24) |
|test (roxie) |1050 |1050 |0 |930 sec  (00:15:30) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  507 sec (00:08:27) |  109 sec (00:01:49) |   22 sec (00:00:22) |   16 sec (00:00:16) | 1418 sec (00:23:38) |   18 sec (00:00:18) | 2099 sec (00:34:59) |

2021-06-03 12:02 UTC, jakesmith reviewed
@rpastrana - changes look good, but there some other places that currently also have a default of 100, which should be changed at same time.
e.g. the defaultYaml in roxie, daserver and saserver.

I think we should just remove those override setting, to match others, and to pick up global default.

2021-06-03 19:46 UTC, HPCCSmoketest commented
Process of PR-15005, label: HPCC-25950-DefaultJlogLevel starts now.
The reason of this test is: Forced to re-test.
Commit ID: 7b58dd98bfad239c86d1402bc7092236aa449972
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-143.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-06-03 20:20 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-143.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 7b58dd98bfad239c86d1402bc7092236aa449972
Build: success
Milestone:Install hpccsystems-platform-community_8.2.1-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |158 |158 |0 |0 |0 |58 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |5 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |24 sec  (00:00:24) |
|setup (thor) |9 |9 |0 |40 sec  (00:00:40) |
|setup (roxie) |19 |19 |0 |20 sec  (00:00:20) |
|test (hthor) |981 |981 |0 |884 sec  (00:14:44) |
|test (thor) |892 |892 |0 |1047 sec  (00:17:27) |
|test (roxie) |1050 |1050 |0 |932 sec  (00:15:32) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  508 sec (00:08:28) |  112 sec (00:01:52) |   21 sec (00:00:21) |   16 sec (00:00:16) | 1361 sec (00:22:41) |   18 sec (00:00:18) | 2045 sec (00:34:05) |

2021-06-03 21:08 UTC, rpastrana commented
@jakesmith please review.

2021-06-03 21:08 UTC, HPCCSmoketest commented
Process of PR-15005, label: HPCC-25950-DefaultJlogLevel starts now.
The reason of this test is: Forced to re-test.
Commit ID: 7b41f281295a660f16bfd65e1872c98fb81b0598
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-111.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-06-03 21:43 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-111.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 7b41f281295a660f16bfd65e1872c98fb81b0598
Build: success
Milestone:Install hpccsystems-platform-community_8.2.1-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |158 |158 |0 |0 |0 |58 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |5 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |24 sec  (00:00:24) |
|setup (thor) |9 |9 |0 |40 sec  (00:00:40) |
|setup (roxie) |19 |19 |0 |20 sec  (00:00:20) |
|test (hthor) |981 |981 |0 |913 sec  (00:15:13) |
|test (thor) |892 |892 |0 |1085 sec  (00:18:05) |
|test (roxie) |1050 |1050 |0 |965 sec  (00:16:05) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  517 sec (00:08:37) |  118 sec (00:01:58) |   21 sec (00:00:21) |   17 sec (00:00:17) | 1400 sec (00:23:20) |   19 sec (00:00:19) | 2101 sec (00:35:01) |

2021-06-04 13:28 UTC, rpastrana commented
@AttilaVamos the check failure seems unrelated:
"CMake Error at cmake_modules/commonSetup.cmake:756 (MESSAGE):
-- Found Bison v3.5.1
  You need Gnu c++ version 7.3.0 or later to build this project (version
-- Configuring incomplete, errors occurred!"

2021-06-04 13:42 UTC, mckellyln commented
The error "You need Gnu c++ version 7.3.0 or later to build this project ..." occurs sometimes on additional commits or a squash.  It is something to do with re-running cmake and its cache - it is not related to anything specific to this PR.
@jakesmith has looked into it and I have as well but it is difficult to reproduce.
@AttilaVamos fyi

2021-06-08 11:24 UTC, jakesmith commented on dali/dfu/dfuserver.cpp
> +    detail: 100
not sure why this was added?

2021-06-08 11:25 UTC, jakesmith requested changes
@rpastrana - There's a couple of other components that override the default (used to be same as default) unnecessarily, that should also be removed.

2021-06-08 13:23 UTC, rpastrana commented
> 
> 
> @rpastrana - There's a couple of other components that override the default (used to be same as default) unnecessarily, that should also be removed.

I didn't feel comfortable overriding those components' explicit logging levels because there is evidence (at least in bare metal) they are meant to log at the highest level. 
Looks like you @jakesmith were involved in the sasha baremetal and container logging detail:
https://github.com/hpcc-systems/HPCC-Platform/blame/b895abd1e8d54ae9d6d4a3675037d405b576e4a1/dali/sasha/saserver.cpp#L357
https://github.com/hpcc-systems/HPCC-Platform/blob/b895abd1e8d54ae9d6d4a3675037d405b576e4a1/dali/sasha/saserver.cpp#L357
If you confirm it should default, I'll go ahead and remove.

@richardkchapman can you confirm this Roxie config entry can be removed and allowed to default?
https://github.com/hpcc-systems/HPCC-Platform/blob/b4bdebe56a7c40af5631559bb5d9b9581a5604ca/roxie/roxie/roxie.cpp#L55

2021-06-08 13:56 UTC, jakesmith commented
> > @rpastrana - There's a couple of other components that override the default (used to be same as default) unnecessarily, that should also be removed.
> 
> I didn't feel comfortable overriding those components' explicit logging levels because there is evidence (at least in bare metal) they are meant to log at the highest level.
> Looks like you @jakesmith were involved in the sasha baremetal and container logging detail:
> https://github.com/hpcc-systems/HPCC-Platform/blame/b895abd1e8d54ae9d6d4a3675037d405b576e4a1/dali/sasha/saserver.cpp#L357
> https://github.com/hpcc-systems/HPCC-Platform/blob/b895abd1e8d54ae9d6d4a3675037d405b576e4a1/dali/sasha/saserver.cpp#L357
> 
> 
> If you confirm it should default, I'll go ahead and remove.
> @richardkchapman can you confirm this Roxie config entry can be removed and allowed to default?
> https://github.com/hpcc-systems/HPCC-Platform/blob/b4bdebe56a7c40af5631559bb5d9b9581a5604ca/roxie/roxie/roxie.cpp#L55

@rpastrana - please go ahead and remove the sasha one.

Before this PR, these per component overrides (of detail: 100) were effectively no-op's, setting the component default to what the global default already specified. I don't think they were intentional, just there as a sort of self-documenting attribute.
Sasha doesn't want to raise the global logging default above the global logging default.
I don't think anywhere does.

2021-06-08 14:44 UTC, rpastrana commented
@jakesmith updated per your suggestions.

2021-06-08 14:46 UTC, HPCCSmoketest commented
Process of PR-15005, label: HPCC-25950-DefaultJlogLevel starts now.
The reason of this test is: Forced to re-test.
Commit ID: 1192e492f3df238e032341ca39999ecfa2a287e6
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-38.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-06-08 15:20 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-38.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 1192e492f3df238e032341ca39999ecfa2a287e6
Build: success
Milestone:Install hpccsystems-platform-community_8.2.1-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |158 |158 |0 |0 |0 |58 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |0 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |6 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |24 sec  (00:00:24) |
|setup (thor) |9 |9 |0 |40 sec  (00:00:40) |
|setup (roxie) |19 |19 |0 |20 sec  (00:00:20) |
|test (hthor) |981 |981 |0 |876 sec  (00:14:36) |
|test (thor) |892 |892 |0 |1044 sec  (00:17:24) |
|test (roxie) |1050 |1050 |0 |930 sec  (00:15:30) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  506 sec (00:08:26) |  112 sec (00:01:52) |   22 sec (00:00:22) |   17 sec (00:00:17) | 1358 sec (00:22:38) |   19 sec (00:00:19) | 2043 sec (00:34:03) |

2021-06-09 08:40 UTC, jakesmith approved these changes
@rpastrana - looks good.

2021-06-09 09:11 UTC, merged