HPCC-25746 React version of Landing Zone
hpcc-systems/HPCC-Platform pull request #15027
Opened 2021-06-08 17:17 UTC by jeclrsg

Signed-off-by: Jeremy Clements <jeremy.clements@lexisnexisrisk.com>

Create react components for landing zone in ECL watch. Squashed commit messages below

- adding routes / links to react and "legacy" landing zone pages
- fix issue preventing LZBrowseWidget from rendering
- add TargetDropzoneField component
- preview button click, change url to route landingzone preview
- download and delete button actions
- add target-server field type
- change target-dropzone field type after an earlier rebase
- fix some column defintions
- correct Fields and Filter import paths
- wip, test updating prop dropdown dependant upon another
- wip, try overriding getSelection of ESPUtil to change store
- override DojoGrid getSelected method
- conditionally add getSelected to widget params
- formatQuery return promise
- change loop in filterExists
- add a css grid-based version of form field grouping
- adding spray dialogs
- change GridForm to merge multiple groups of fields for state
- reorganizing some code for spray modals in LandingZone
- fix npm lint issues
- rearrange delimited form fields to make form a bit shorter
- revert changes to Filter component
- add react-hook-form as dependency
- some additional strings for LandingZone.tsx
- add FixedImportForm
- add Delimited, Json & Xml import forms
- add Variable & Blob import forms
- vscode sorted imports?
- additional constant for a generic required validation error
- removed unused import
- change TargetDropzone field to include the actual path as a property of
  each IDropdownOption object
- change TargetServer field to include OS as a property of the returned IDropdownOption objects
- correct types of TargetDfuSprayQueue field
- add TargetFolder field for LZ upload form
- fix lint error for async callback in useConst
- add dropzone for dragging files into LZ pane
- removing some debugging console logs
- add FileListForm to LandingZone
- removing some debug console logs & unused imports
- change how grid store and query are created / updated

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-06-21 10:18 UTC, GordonSmith commented
@jeclrsg is this still draft or Ready for Review?

2021-07-13 02:44 UTC, HPCCSmoketest commented
Process of PR-15027, label: hpcc-25746-react-landing-zone starts now.
The reason of this test is: Forced to re-test.
Commit ID: 429847ae8445bffaf58138bd6a45a40243ea600a
Estimated completion time is ~0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-39.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-07-13 02:56 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-39.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 429847ae8445bffaf58138bd6a45a40243ea600a
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  513 sec (00:08:33) |  109 sec (00:01:49) |   21 sec (00:00:21) |   16 sec (00:00:16) |    0 sec (00:00:00) |   15 sec (00:00:15) |  682 sec (00:11:22) |

2021-07-14 01:05 UTC, HPCCSmoketest commented
Process of PR-15027, label: hpcc-25746-react-landing-zone starts now.
The reason of this test is: Forced to re-test.
Commit ID: 95d7f0bfffab8c226044cc74e1d0ed36a3346a6b
Estimated completion time is ~0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-45.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-07-14 01:17 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-45.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 95d7f0bfffab8c226044cc74e1d0ed36a3346a6b
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  521 sec (00:08:41) |  121 sec (00:02:01) |   22 sec (00:00:22) |   16 sec (00:00:16) |    0 sec (00:00:00) |   15 sec (00:00:15) |  704 sec (00:11:44) |

2021-07-14 13:07 UTC, GordonSmith requested changes

2021-07-14 13:07 UTC, GordonSmith commented on esp/src/src-react/components/forms/landing-zone/BlobImportForm.tsx
> +                ariaLabel="Close popup modal"
Translations

2021-07-14 13:07 UTC, GordonSmith commented on esp/src/src-react/components/forms/landing-zone/BlobImportForm.tsx
> +                        placeholder={"Select a value"}
Translations

2021-07-14 13:07 UTC, GordonSmith commented on esp/src/src-react/components/forms/landing-zone/BlobImportForm.tsx
> +                                <input type="hidden" { ...register(`selectedFiles.${idx}.SourceIP` as const) } value={file["NetAddress"]} />
Expensive, foces re-refresh every time...  Looks like it shoould be a "useMemo"?

2021-07-14 13:07 UTC, GordonSmith commented on esp/src/src-react/components/forms/landing-zone/BlobImportForm.tsx
> +                                errorMessage={ error && error.message }
Change to error?.message

2021-07-14 13:07 UTC, GordonSmith commented on esp/src/src-react/components/forms/landing-zone/DelimitedImportForm.tsx
> +        closeMenuItemText: "Close",
Translations

2021-07-14 13:07 UTC, GordonSmith commented on esp/src/src-react/components/forms/landing-zone/DelimitedImportForm.tsx
> +                        errorMessage={ error && error.message }
Change to error?.message

2021-07-14 13:07 UTC, GordonSmith commented on esp/src/src-react/components/forms/landing-zone/DelimitedImportForm.tsx
> +                        errorMessage={ error && error.message }
error?.message

2021-07-14 13:07 UTC, GordonSmith commented on esp/src/src-react/components/forms/landing-zone/DelimitedImportForm.tsx
> +                        required: `Select a ${nlsHPCC.Queue}`
Translations

2021-07-14 13:07 UTC, GordonSmith commented on esp/src/src-react/components/forms/landing-zone/DelimitedImportForm.tsx
> +                        errorMessage={ error && error.message }
ditto

2021-07-14 13:07 UTC, GordonSmith commented on esp/src/src-react/components/forms/landing-zone/DelimitedImportForm.tsx
> +                                <input type="hidden" { ...register(`selectedFiles.${idx}.SourceIP` as const) } value={file["NetAddress"]} />
Expensive

2021-07-14 13:07 UTC, GordonSmith commented on esp/src/src-react/components/forms/landing-zone/DelimitedImportForm.tsx
> +                                errorMessage={ error && error.message }
ditto

2021-07-14 15:40 UTC, HPCCSmoketest commented
Process of PR-15027, label: hpcc-25746-react-landing-zone starts now.
The reason of this test is: Forced to re-test.
Commit ID: 1fa4927d1baa4b7f9b3a1efd35345a41fd2f1c67
Estimated completion time is ~0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-239.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-07-14 15:51 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-239.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 1fa4927d1baa4b7f9b3a1efd35345a41fd2f1c67
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  501 sec (00:08:21) |  108 sec (00:01:48) |   21 sec (00:00:21) |   16 sec (00:00:16) |    0 sec (00:00:00) |   15 sec (00:00:15) |  669 sec (00:11:09) |

2021-07-14 21:17 UTC, HPCCSmoketest commented
Process of PR-15027, label: hpcc-25746-react-landing-zone starts now.
The reason of this test is: Forced to re-test.
Commit ID: 266c47f67bf1448a0c4e0fb7a3281e86c7a608df
Estimated completion time is ~0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-75.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-07-14 21:29 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-75.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 266c47f67bf1448a0c4e0fb7a3281e86c7a608df
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  502 sec (00:08:22) |  111 sec (00:01:51) |   21 sec (00:00:21) |   21 sec (00:00:21) |    0 sec (00:00:00) |   15 sec (00:00:15) |  679 sec (00:11:19) |

2021-07-16 08:58 UTC, GordonSmith requested changes

2021-07-16 08:58 UTC, GordonSmith commented on esp/src/src-react/components/LandingZone.tsx
> +                    style={{ display: "none" }} onChange={handleFileSelect} multiple={true}
@jeclrsg bump

2021-07-16 08:58 UTC, GordonSmith commented on esp/src/src-react/components/forms/landing-zone/BlobImportForm.tsx
> +                    { selection.length && selection.map((file, idx) => {
No need to test for length?

2021-07-20 20:09 UTC, HPCCSmoketest commented
Process of PR-15027, label: hpcc-25746-react-landing-zone starts now.
The reason of this test is: Forced to re-test.
Commit ID: 7cdd293a4711c6cd994735deafe1da473eb89aba
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-239.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-07-20 20:21 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-239.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 7cdd293a4711c6cd994735deafe1da473eb89aba
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  512 sec (00:08:32) |  116 sec (00:01:56) |   21 sec (00:00:21) |   16 sec (00:00:16) |    0 sec (00:00:00) |   15 sec (00:00:15) |  688 sec (00:11:28) |

2021-07-21 13:03 UTC, GordonSmith approved these changes, later dismissed

2021-07-22 09:48 UTC, richardkchapman commented
Needs rebasing for a clean merge

2021-07-22 13:19 UTC, HPCCSmoketest commented
Process of PR-15027, label: hpcc-25746-react-landing-zone starts now.
The reason of this test is: Forced to re-test.
Commit ID: 8233d8e26fad1437ee38d02c0d06cbe7adc4703a
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-11.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-07-22 13:31 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-11.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 8233d8e26fad1437ee38d02c0d06cbe7adc4703a
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  523 sec (00:08:43) |  112 sec (00:01:52) |   21 sec (00:00:21) |   16 sec (00:00:16) |    0 sec (00:00:00) |   15 sec (00:00:15) |  696 sec (00:11:36) |

2021-08-04 03:04 UTC, HPCCSmoketest commented
Process of PR-15027, label: hpcc-25746-react-landing-zone starts now.
The reason of this test is: Forced to re-test.
Commit ID: c6249c89102426f821a79dbf6215dad5e6e46c2b
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-22.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-08-04 03:16 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-22.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: c6249c89102426f821a79dbf6215dad5e6e46c2b
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  525 sec (00:08:45) |  116 sec (00:01:56) |   21 sec (00:00:21) |   17 sec (00:00:17) |    0 sec (00:00:00) |   14 sec (00:00:14) |  702 sec (00:11:42) |

2021-08-05 12:38 UTC, GordonSmith approved these changes

2021-08-05 12:39 UTC, merged