HPCC-25489 LDAP credentials should be configurable as secrets
hpcc-systems/HPCC-Platform pull request #15056
Opened 2021-06-15 15:08 UTC by RussWhitehead

Add support to externalize LDAP and other credentials as Kubernetes secrets
and Hashicorp vault secrets. Added "authn" category to secrets and vault, and
modified ECLWatch ldap.yaml to allow specification of secret name. Added README.md
markdown to document LDAP configuration using plain text yaml, k8s secrets, or
Hashicorp vault

Signed-off-by: Russ Whitehead <william.whitehead@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-06-15 15:13 UTC, HPCCSmoketest commented
Process of PR-15056, label: authn_82x starts now.
The reason of this test is: Forced to re-test.
Commit ID: 4648c08d4b24f71c7354c97c4d3135f1176fc3d3
Estimated completion time is ~0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-14.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-06-15 15:47 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-14.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 4648c08d4b24f71c7354c97c4d3135f1176fc3d3
Build: success
Milestone:Install hpccsystems-platform-community_8.2.1-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |159 |159 |0 |0 |0 |59 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |0 sec |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |6 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |24 sec  (00:00:24) |
|setup (thor) |9 |9 |0 |40 sec  (00:00:40) |
|setup (roxie) |19 |19 |0 |20 sec  (00:00:20) |
|test (hthor) |981 |981 |0 |907 sec  (00:15:07) |
|test (thor) |892 |892 |0 |1028 sec  (00:17:08) |
|test (roxie) |1050 |1050 |0 |966 sec  (00:16:06) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  512 sec (00:08:32) |  116 sec (00:01:56) |   21 sec (00:00:21) |   16 sec (00:00:16) | 1344 sec (00:22:24) |   19 sec (00:00:19) | 2036 sec (00:33:56) |

2021-06-15 16:29 UTC, RussWhitehead commented
@afishbeck  Please review

2021-06-16 15:14 UTC, afishbeck requested changes
@RussWhitehead comments may be a bit repetitive.. mainly about not supporting configured passwords.  We can always add some dev shortcut for passwords later if it ever makes sense.

2021-06-16 15:14 UTC, afishbeck commented on helm/examples/ldap/README.md
> +esp --application=eclwatch --auth=ldap --ldapAddress=10.200.1.2 ...
This shouldn't be necessary, you should be able to set  "auth: ldap" and "ldapAddress: 10.200.1.2" in values.yaml under the esp instance.  Also needs testing to make sure it's right.

2021-06-16 15:14 UTC, afishbeck commented on helm/examples/ldap/README.md
> +   In the HPCC-Platform\esp\applications\common\ldap\ldap.yaml or override, set the "ldapAdminSecretKey" to the key name created above. Note that the key name "ldapadminsecretkey" is used by the LDAP
Again, should never override the yaml files that are part of our repository.  These values can be overriden in values.yaml.

2021-08-11 22:39 UTC, closed without merging