Add component instrumentation section
hpcc-systems/HPCC-Platform pull request #15086
Opened 2021-06-21 18:12 UTC by kenrowland

Signed-off-by: Ken Rowland <kenneth.rowland@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-06-21 18:17 UTC, HPCCSmoketest commented
Process of PR-15086, label: HPCC-26021 starts now.
The reason of this test is: Forced to re-test.
Commit ID: f7da3fd8bb584a6532046da2db40c74ac18ee8ec
Estimated completion time is ~0.19 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-83.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-06-21 18:36 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-83.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: f7da3fd8bb584a6532046da2db40c74ac18ee8ec
Build: success
Milestone:Install hpccsystems-platform-community_8.1.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  790 sec (00:13:10) |  260 sec (00:04:20) |   21 sec (00:00:21) |   17 sec (00:00:17) |    0 sec (00:00:00) |   14 sec (00:00:14) | 1111 sec (00:18:31) |

2021-06-23 08:56 UTC, ghalliday requested changes
Some minor comments

2021-06-23 08:56 UTC, ghalliday commented on devdoc/Metrics.rst
> +uses retrieval methods to get current state when reporting. The metric insures shnchronized access.
typo 'shnchronized'

2021-06-23 08:56 UTC, ghalliday commented on devdoc/Metrics.rst
> +metric value as the custom metric clsas provides no update methods. The component is also responsible
typo: 'clsas'

2021-06-23 08:56 UTC, ghalliday commented on devdoc/Metrics.rst
>  metrics.sinks.sink.type
remove ".sink", possibly metrics.sinks[].type for clarity.  Same for following definitions.

2021-06-23 08:56 UTC, ghalliday commented on devdoc/Metrics.rst
> +The *metrics reporter* is a singleton created using the platform defined singleton pattern template. The compoent
typo: compoent

2021-06-23 08:56 UTC, ghalliday commented on devdoc/Metrics.rst
> +constructor arguments as needed. It should also be noted that all metrics inherit from the *ImMtric* interface should
typo: "ImMtric"

2021-06-23 08:56 UTC, ghalliday commented on devdoc/Metrics.rst
> +constructor arguments as needed. It should also be noted that all metrics inherit from the *ImMtric* interface should
I'm not sure this sentence is worth including.

2021-06-24 19:52 UTC, JamesDeFabia requested changes
With the exception of the typos @ghalliday already noted, this looks good.

2021-06-25 13:27 UTC, kenrowland commented
@ghalliday I went ahead and rebased since the changes were minimal. Please take a look and let me know if there is anything else.

2021-06-25 13:29 UTC, HPCCSmoketest commented
Process of PR-15086, label: HPCC-26021 starts now.
The reason of this test is: Forced to re-test.
Commit ID: a154f661680f01c0000b8436c26d329b19eaa625
Estimated completion time is ~0.19 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-82.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-06-25 13:47 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-82.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: a154f661680f01c0000b8436c26d329b19eaa625
Build: success
Milestone:Install hpccsystems-platform-community_8.1.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  753 sec (00:12:33) |  237 sec (00:03:57) |   23 sec (00:00:23) |   17 sec (00:00:17) |    0 sec (00:00:00) |   15 sec (00:00:15) | 1054 sec (00:17:34) |

2021-06-28 09:39 UTC, ghalliday commented
I re-targeted to 8.2.x.  The PR will need rebasing into the correct base branch

2021-06-28 09:42 UTC, HPCCSmoketest commented
Process of PR-15086, label: HPCC-26021 starts now.
The reason of this test is: Forced to re-test.
Commit ID: a154f661680f01c0000b8436c26d329b19eaa625
Estimated completion time is ~1.09 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-189.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-06-28 09:42 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-189.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: a154f661680f01c0000b8436c26d329b19eaa625
Error in git command, should skip build and test.

[Build error:](https://gist.github.com/ebd6473b512f8e9c8f1ae6a8e78ed4e7)
Build log [Build log](https://gist.github.com/HPCCSmoketest/ebd6473b512f8e9c8f1ae6a8e78ed4e7#file-result-21-06-28-09-42-16-log)

2021-06-28 09:43 UTC, ghalliday approved these changes
ok to merge once it is rebased.

2021-06-29 13:46 UTC, kenrowland commented
Resubmitting new PR as unable to rebase to candidate-8.2.x for some reason. Unknown merge conflict un related to any local changes.

2021-06-29 13:46 UTC, closed without merging