HPCC-26144 LogicalFile details missing actions
hpcc-systems/HPCC-Platform pull request #15131
Opened 2021-07-02 13:44 UTC by jeclrsg

Signed-off-by: Jeremy Clements <jeremy.clements@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-07-07 14:23 UTC, HPCCSmoketest commented
Process of PR-15131, label: hpcc-26144-FileDetails-missing-actions starts now.
The reason of this test is: Forced to re-test.
Commit ID: 5ec0ac5129017705b4dbb2ec933a2ac52e677b5c
Estimated completion time is ~0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-155.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-07-07 14:35 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-155.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 5ec0ac5129017705b4dbb2ec933a2ac52e677b5c
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  513 sec (00:08:33) |  121 sec (00:02:01) |   25 sec (00:00:25) |   16 sec (00:00:16) |    0 sec (00:00:00) |   15 sec (00:00:15) |  699 sec (00:11:39) |

2021-07-07 15:02 UTC, GordonSmith requested changes
I stopped reviewing after the first form as I suspect my comments there are relevant to all the forms?

2021-07-07 15:02 UTC, GordonSmith commented on esp/src/src-react/components/forms/CopyFile.tsx
> +        closeMenuItemText: "Close",
Should use nlsHPCC for translations.

2021-07-07 16:18 UTC, HPCCSmoketest commented
Process of PR-15131, label: hpcc-26144-FileDetails-missing-actions starts now.
The reason of this test is: Forced to re-test.
Commit ID: acad024ac671a3e74d3c7ce1406297d6f37ed089
Estimated completion time is ~0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-57.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-07-07 16:22 UTC, jeclrsg commented on esp/src/src-react/components/forms/CopyFile.tsx
> +    const { handleSubmit, control, reset } = useForm<CopyFileFormValues>({ defaultValues });
No, defaultValues is also a key for the config object passed into useForm

2021-07-07 16:25 UTC, jeclrsg commented on esp/src/src-react/components/forms/CopyFile.tsx
> +            </Stack>
I think so. The validation, resetting of default values, and submission mechanism this module provides seem pretty nice.

2021-07-07 16:28 UTC, jeclrsg commented on esp/src/src-react/components/forms/CopyFile.tsx
> +        </div>
I'm not sure. I would defer to your opinion, but I think of dialog type of components as a replacement for simpler things, sort of like JS alert / confirm. Whereas modals are for things that might be more complicated, like forms and such.

2021-07-07 16:29 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-57.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: acad024ac671a3e74d3c7ce1406297d6f37ed089
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  507 sec (00:08:27) |  111 sec (00:01:51) |   21 sec (00:00:21) |   17 sec (00:00:17) |    0 sec (00:00:00) |   15 sec (00:00:15) |  680 sec (00:11:20) |

2021-07-20 10:45 UTC, GordonSmith approved these changes, later dismissed

2021-07-20 11:00 UTC, richardkchapman commented
Needs rebasing for a clean merge

2021-07-20 17:11 UTC, HPCCSmoketest commented
Process of PR-15131, label: hpcc-26144-FileDetails-missing-actions starts now.
The reason of this test is: Forced to re-test.
Commit ID: c0fa9ad7b11115b4b7bc724f34dc983178b240c9
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-190.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-07-20 17:23 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-190.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: c0fa9ad7b11115b4b7bc724f34dc983178b240c9
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  514 sec (00:08:34) |  113 sec (00:01:53) |   21 sec (00:00:21) |   17 sec (00:00:17) |    0 sec (00:00:00) |   15 sec (00:00:15) |  688 sec (00:11:28) |

2021-07-21 12:47 UTC, GordonSmith commented on esp/src/src-react/components/FileDetails.tsx
> +        }
Should this check all the parts? - maybe not if their state is always the same?

2021-07-21 12:54 UTC, GordonSmith approved these changes, later dismissed

2021-07-22 09:59 UTC, richardkchapman commented
Still needs rebasing...

2021-07-22 13:07 UTC, HPCCSmoketest commented
Process of PR-15131, label: hpcc-26144-FileDetails-missing-actions starts now.
The reason of this test is: Forced to re-test.
Commit ID: e7fb31643965d63bace9d1cb376c4cc370582de2
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-145.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-07-22 13:09 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-145.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: e7fb31643965d63bace9d1cb376c4cc370582de2
Containerized:False
Number of Error(s): 3
make[2]: *** [esp/src/CMakeFiles/eclwatch_fetchdeps.dir/build.make:61: esp/src/lib/package-lock.json] Error 1
make[1]: *** [CMakeFiles/Makefile2:10354: esp/src/CMakeFiles/eclwatch_fetchdeps.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
Get ECLWatch build result
ReportTimes.
Finish at: 2021-07-22_13-09-36
time logs started
Prep time   :     9 sec (00:00:09)
Build time  :   110 sec (00:01:50)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :   119 sec (00:01:59)
time logs end

[Build error:](https://gist.github.com/b18cf4ca7d2b84776df4c1535ae72480)
Build log [Build log](https://gist.github.com/HPCCSmoketest/b18cf4ca7d2b84776df4c1535ae72480#file-result-21-07-22-13-07-24-log)

2021-07-22 13:42 UTC, HPCCSmoketest commented
Process of PR-15131, label: hpcc-26144-FileDetails-missing-actions starts now.
The reason of this test is: Forced to re-test.
Commit ID: 8b0df9af0c6227ce9d88fa48c20902e799b3600d
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-68.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-07-22 13:54 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-68.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 8b0df9af0c6227ce9d88fa48c20902e799b3600d
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  509 sec (00:08:29) |  110 sec (00:01:50) |   21 sec (00:00:21) |   17 sec (00:00:17) |    0 sec (00:00:00) |   15 sec (00:00:15) |  681 sec (00:11:21) |

2021-08-04 03:20 UTC, HPCCSmoketest commented
Process of PR-15131, label: hpcc-26144-FileDetails-missing-actions starts now.
The reason of this test is: Forced to re-test.
Commit ID: 8c2a29618a1befc762d11499f338d09f9afa27e2
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-207.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-08-04 03:32 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-207.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 8c2a29618a1befc762d11499f338d09f9afa27e2
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  518 sec (00:08:38) |  119 sec (00:01:59) |   21 sec (00:00:21) |   17 sec (00:00:17) |    0 sec (00:00:00) |   15 sec (00:00:15) |  699 sec (00:11:39) |

2021-08-04 03:38 UTC, HPCCSmoketest commented
Process of PR-15131, label: hpcc-26144-FileDetails-missing-actions starts now.
The reason of this test is: Forced to re-test.
Commit ID: ee315e610e5c9a6e4ba831d646f97afad8b9ac6a
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-147.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-08-04 03:50 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-147.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: ee315e610e5c9a6e4ba831d646f97afad8b9ac6a
Containerized:False
Build: success
Lint error(s): 
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> eslint eclwatch/**/*.js src/**/*.ts? src-react/**/*.ts?
/home/centos/smoketest/PR-15131/HPCC-Platform/esp/src/src-react/components/FileDetails.tsx
  68:15  error  Missing semicolon  semi
\xe2\x9c\x96 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
npm ERR! code ELIFECYCLE
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> eslint eclwatch/**/*.js src/**/*.ts? src-react/**/*.ts?
/home/centos/smoketest/PR-15131/HPCC-Platform/esp/src/src-react/components/FileDetails.tsx
  68:15  error  Missing semicolon  semi
\xe2\x9c\x96 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
npm ERR! errno 1
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> eslint eclwatch/**/*.js src/**/*.ts? src-react/**/*.ts?
/home/centos/smoketest/PR-15131/HPCC-Platform/esp/src/src-react/components/FileDetails.tsx
  68:15  error  Missing semicolon  semi
\xe2\x9c\x96 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
npm ERR! eclwatch@1.0.0 lint: `eslint eclwatch/**/*.js src/**/*.ts? src-react/**/*.ts?`
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> eslint eclwatch/**/*.js src/**/*.ts? src-react/**/*.ts?
/home/centos/smoketest/PR-15131/HPCC-Platform/esp/src/src-react/components/FileDetails.tsx
  68:15  error  Missing semicolon  semi
\xe2\x9c\x96 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
npm ERR! Exit status 1
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> eslint eclwatch/**/*.js src/**/*.ts? src-react/**/*.ts?
/home/centos/smoketest/PR-15131/HPCC-Platform/esp/src/src-react/components/FileDetails.tsx
  68:15  error  Missing semicolon  semi
\xe2\x9c\x96 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
npm ERR! 
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> run-s lint
> eclwatch@1.0.0 lint /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> eslint eclwatch/**/*.js src/**/*.ts? src-react/**/*.ts?
/home/centos/smoketest/PR-15131/HPCC-Platform/esp/src/src-react/components/FileDetails.tsx
  68:15  error  Missing semicolon  semi
\xe2\x9c\x96 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
npm ERR! Failed at the eclwatch@1.0.0 lint script.
res:
> eclwatch@1.0.0 test /home/centos/smoketest/PR-15131/HPCC-Platform/esp/src
> run-s lint
> eclwatc
 ... ( comment is too long, 214 lines, 10877 bytes, truncated) ... 
[Build error:](https://gist.github.com/c813c145ed44c4944bfd73cfead4092c)
Build log [Build log](https://gist.github.com/HPCCSmoketest/c813c145ed44c4944bfd73cfead4092c#file-result-21-08-04-03-38-31-log)

Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  508 sec (00:08:28) |  108 sec (00:01:48) |   21 sec (00:00:21) |   16 sec (00:00:16) |    0 sec (00:00:00) |   15 sec (00:00:15) |  676 sec (00:11:16) |

```

2021-08-04 13:18 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-235.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: fa3da2c1add357b2848d7e1686c2224314658460
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  515 sec (00:08:35) |  109 sec (00:01:49) |   21 sec (00:00:21) |   17 sec (00:00:17) |    0 sec (00:00:00) |   14 sec (00:00:14) |  685 sec (00:11:25) |

2021-08-05 12:39 UTC, GordonSmith submitted a review, later dismissed

2021-08-05 12:40 UTC, GordonSmith commented
@jeclrsg please rebase

2021-08-05 16:39 UTC, HPCCSmoketest commented
Process of PR-15131, label: hpcc-26144-FileDetails-missing-actions starts now.
The reason of this test is: New commit.
Commit ID: 3341b21eb898c95d39b8d1d427122137dfa39da8
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-47.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-08-05 16:51 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-47.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 3341b21eb898c95d39b8d1d427122137dfa39da8
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  516 sec (00:08:36) |  119 sec (00:01:59) |   23 sec (00:00:23) |   16 sec (00:00:16) |    0 sec (00:00:00) |   15 sec (00:00:15) |  697 sec (00:11:37) |

2021-08-13 20:39 UTC, HPCCSmoketest commented
Process of PR-15131, label: hpcc-26144-FileDetails-missing-actions starts now.
The reason of this test is: Forced to re-test.
Commit ID: 7fd52e18cdbacfbb5f75ce2d281bb3a6b1a6dd80
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-209.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-08-13 20:42 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-209.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 7fd52e18cdbacfbb5f75ce2d281bb3a6b1a6dd80
Containerized:False
Number of Error(s): 7
src-react/components/forms/CopyFile.tsx(6,25): error TS2307: Cannot find module ../../hooks/File or its corresponding type declarations.
src-react/components/forms/DesprayFile.tsx(6,25): error TS2307: Cannot find module ../../hooks/File or its corresponding type declarations.
src-react/components/forms/RenameFile.tsx(6,25): error TS2307: Cannot find module ../../hooks/File or its corresponding type declarations.
src-react/components/forms/ReplicateFile.tsx(6,25): error TS2307: Cannot find module ../../hooks/File or its corresponding type declarations.
make[2]: *** [esp/src/CMakeFiles/eclwatch.dir/build.make:311: esp/src/build/dist/stub.eclwatch.js] Error 1
make[1]: *** [CMakeFiles/Makefile2:10418: esp/src/CMakeFiles/eclwatch.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
Get ECLWatch build result
ReportTimes.
Finish at: 2021-08-13_20-42-31
time logs started
Prep time   :     8 sec (00:00:08)
Build time  :   164 sec (00:02:44)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :   172 sec (00:02:52)
time logs end

[Build error:](https://gist.github.com/4208498f0be06042baf66e0895922361)
Build log [Build log](https://gist.github.com/HPCCSmoketest/4208498f0be06042baf66e0895922361#file-result-21-08-13-20-39-25-log)

2021-08-13 21:43 UTC, HPCCSmoketest commented
Process of PR-15131, label: hpcc-26144-FileDetails-missing-actions starts now.
The reason of this test is: Forced to re-test.
Commit ID: 52452e7d09d8dd47e42853ea4a94b2456dc97039
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-23.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-08-13 21:55 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-23.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 52452e7d09d8dd47e42853ea4a94b2456dc97039
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  517 sec (00:08:37) |  113 sec (00:01:53) |   21 sec (00:00:21) |   17 sec (00:00:17) |    0 sec (00:00:00) |   15 sec (00:00:15) |  692 sec (00:11:32) |

2021-08-16 13:00 UTC, GordonSmith requested changes

2021-08-16 13:39 UTC, HPCCSmoketest commented
Process of PR-15131, label: hpcc-26144-FileDetails-missing-actions starts now.
The reason of this test is: Forced to re-test.
Commit ID: 1570815a981f772d0054a1b90d2f4d6fe00f45f5
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-28.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-08-16 13:51 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-28.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 1570815a981f772d0054a1b90d2f4d6fe00f45f5
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    9 sec (00:00:09) |  527 sec (00:08:47) |  125 sec (00:02:05) |   22 sec (00:00:22) |   16 sec (00:00:16) |    0 sec (00:00:00) |   15 sec (00:00:15) |  714 sec (00:11:54) |

2021-08-16 16:47 UTC, GordonSmith approved these changes

2021-08-19 14:19 UTC, merged