HPCC-26510 ES Translations for 8.4.X
hpcc-systems/HPCC-Platform pull request #15354
Opened 2021-09-16 15:10 UTC by kunalaswani

Translations added for Spanish (ES).

Signed-off-by: Kunal Aswani <kunal.aswani@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [x] I have tested my changes in multiple modern browsers
  - [x] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-09-16 15:11 UTC, kunalaswani commented
@rpastrana please review

2021-09-16 15:33 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-25.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 8f6241ad113dde2dc94d316e45cdbe7033fcda11
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  564 sec (00:09:24) |  125 sec (00:02:05) |   22 sec (00:00:22) |   16 sec (00:00:16) |    0 sec (00:00:00) |   15 sec (00:00:15) |  750 sec (00:12:30) |

2021-09-16 15:37 UTC, rpastrana commented on esp/src/src/nls/es/hpcc.ts
> +    IgnoreGlobalStoreOutEdges: "Ignorar los bordes de salida de la tienda global",
this is a very specialized message, but I think we need 
"almacén" instead of "tienda"

2021-09-16 15:37 UTC, rpastrana commented on esp/src/src/nls/es/hpcc.ts
> +    Length: "Largo",
depends on the context, but likely "largura"

2021-09-16 15:38 UTC, rpastrana commented on esp/src/src/nls/es/hpcc.ts
> +    Move: "Moverse",
depends on context, but likely "Mover" as in Move something

2021-09-16 15:38 UTC, rpastrana commented on esp/src/src/nls/es/hpcc.ts
> +    OpenModernECLWatch: "Abierto moderno ECL Watch",
Abrir instead of abierto

2021-09-16 15:39 UTC, rpastrana commented on esp/src/src/nls/es/hpcc.ts
> +    SelectA: "Seleccione a",
depends on context, but likely Seleccione un

2021-09-16 15:46 UTC, rpastrana commented on esp/src/src/nls/es/hpcc.ts
> +    SizeMeanPeakMemory: "Tamaño de memoria máxima media",
this one is tough!
Perhaps: "Promedio Maximo de Memoria"

2021-09-16 15:47 UTC, rpastrana commented on esp/src/src/nls/es/hpcc.ts
> +    TimeMinTotalExecuteMinutes: "Tiempo Mínimo Total Ejecutar Minutos",
just pointing out that Minimo is capitalized here, but maximo and promedio isn't in the previous 2 translations.

2021-09-16 15:48 UTC, rpastrana reviewed
@kunalaswani this translation was tough (some very specialized terms). I left a few comments.

2021-09-17 14:40 UTC, kunalaswani commented
@rpastrana changes made.

2021-09-17 14:48 UTC, HPCCSmoketest commented
Process of PR-15354, label: HPCC-26510 starts now.
The reason of this test is: Forced to re-test.
Commit ID: c18a40e03ce54efb0d49494d771ad8dc0efc5bf6
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-51.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-09-17 15:00 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-51.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: c18a40e03ce54efb0d49494d771ad8dc0efc5bf6
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  550 sec (00:09:10) |  109 sec (00:01:49) |   22 sec (00:00:22) |   16 sec (00:00:16) |    0 sec (00:00:00) |   15 sec (00:00:15) |  720 sec (00:12:00) |

2021-09-21 13:38 UTC, rpastrana requested changes
@kunalaswani just a few more comments

2021-09-21 13:38 UTC, rpastrana commented on esp/src/src/nls/es/hpcc.ts
> +    CompressedSize: "Tamaño comprimido",
should comprimido be capitalized?

2021-09-21 13:38 UTC, rpastrana commented on esp/src/src/nls/es/hpcc.ts
> +    IgnoreGlobalStoreOutEdges: "Ignorar los bordes de salida de la almacén global",
la should be el

2021-09-21 13:38 UTC, rpastrana commented on esp/src/src/nls/es/hpcc.ts
> +    OpenModernECLWatch: "Abrir moderno ECL Watch",
Abrir ECLWatch moderno

2021-09-21 13:38 UTC, rpastrana commented on esp/src/src/nls/es/hpcc.ts
> +    TimeMinTotalExecuteMinutes: "Tiempo mínimo Total Ejecutar Minutos",
"Total" capitalized here, but not in previous 2 messages, same for Ejecutar/ejecucion and minutos.

In fact these 3 messages should be:
Maximo/Total/Minomo tiempo total de ejecucion en minutos.

2021-09-21 14:20 UTC, kunalaswani commented on esp/src/src/nls/es/hpcc.ts
> +    CompressedSize: "Tamaño comprimido",
yes, it should

2021-09-21 14:20 UTC, kunalaswani commented
changes made.

2021-09-21 14:22 UTC, rpastrana approved these changes
@kunalaswani great job on these translations

2021-09-21 14:28 UTC, HPCCSmoketest commented
Process of PR-15354, label: HPCC-26510 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 90f98dac35aa0e9d9894e11b2b707a0d409ffc6c
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-132.ca-central-1.compute.internal
 Git:  git version 2.9.5

2021-09-21 14:33 UTC, merged

2021-09-21 14:40 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Host: ip-10-20-0-132.ca-central-1.compute.internal
 Git:  git version 2.9.5
Sha: 90f98dac35aa0e9d9894e11b2b707a0d409ffc6c
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|    8 sec (00:00:08) |  556 sec (00:09:16) |  112 sec (00:01:52) |   21 sec (00:00:21) |   16 sec (00:00:16) |    0 sec (00:00:00) |   15 sec (00:00:15) |  728 sec (00:12:08) |