HPCC-26633 Add cost template
hpcc-systems/HPCC-Platform pull request #15490
Opened 2021-10-18 13:39 UTC by Michael-Gardner

Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-10-18 16:04 UTC, kenrowland requested changes

2021-10-18 16:04 UTC, kenrowland commented on initfiles/componentfiles/configschema/templates/AddCost.json
> +
Trivial, but some don't like blank lines

2021-10-18 16:04 UTC, kenrowland commented on initfiles/componentfiles/configschema/templates/CMakeLists.txt
> +        ${CMAKE_CURRENT_SOURCE_DIR}/AddCost.json
In my opinion, we should include all the mod templates that might be used instead of the user having to research where to find the template.

2022-01-14 18:09 UTC, Michael-Gardner commented
@kenrowland

- Added all the templates to the package.
- Fixed whitespace issue
- Delete action now removes cost so no duplicates occur

2022-01-14 18:54 UTC, HPCCSmoketest commented
Process of PR-15490, label: HPCC-26633-cost-template starts now.
The reason of this test is: New commit.
Commit ID: 84180961563a692a3db0e24bb8aa777f5229a62e
Estimated completion time is 0.64 hour(s)
centos 7.9.2009 (Linux 3.10.0-1160.49.1.el7.x86_64)
 Host: bctldroxie011.noam.lnrm.net
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 1.8.3.1,  CMake: 3.17.5,  cUrl: 7.29.0,  node.js: v14.15.4,  npm: 6.14.10

2022-01-14 19:46 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.9.2009 (Linux 3.10.0-1160.49.1.el7.x86_64)
 Host: bctldroxie011.noam.lnrm.net
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 1.8.3.1,  CMake: 3.17.5,  cUrl: 7.29.0,  node.js: v14.15.4,  npm: 6.14.10
Sha: 84180961563a692a3db0e24bb8aa777f5229a62e
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.4.23-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |76 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |27 sec  (00:00:27) |
|setup (thor) |9 |9 |0 |42 sec  (00:00:42) |
|setup (roxie) |19 |19 |0 |30 sec  (00:00:30) |
|test (hthor) |983 |983 |0 |1783 sec  (00:29:43) |
|test (thor) |893 |890 |3 |1617 sec  (00:26:57) |
|test (roxie) |1052 |1052 |0 |978 sec  (00:16:18) |


[Errors:](https://gist.github.com/c9e9bf35186da785e6c03c3853aac478)
- test
  - thor
    - 280\. [genjoin2](https://gist.github.com/HPCCSmoketest/c9e9bf35186da785e6c03c3853aac478#file-genjoin2-w20220114-192052-5-log), 281\. [genjoin3](https://gist.github.com/HPCCSmoketest/c9e9bf35186da785e6c03c3853aac478#file-genjoin3-w20220114-192053-2-log), 416\. [joinattr2](https://gist.github.com/HPCCSmoketest/c9e9bf35186da785e6c03c3853aac478#file-joinattr2-w20220114-192621-3-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   14 sec (00:00:14) |  816 sec (00:13:36) |  128 sec (00:02:08) |   22 sec (00:00:22) |   20 sec (00:00:20) | 2084 sec (00:34:44) |   20 sec (00:00:20) | 3104 sec (00:51:44) |

2022-01-18 14:58 UTC, kenrowland approved these changes
Approved

2022-01-18 15:00 UTC, Michael-Gardner commented
@richardkchapman Ready for merge

2022-01-18 15:14 UTC, merged