HPCC-26790 Provide HPCC Metrics via Azure Insights write-up
hpcc-systems/HPCC-Platform pull request #15557
Opened 2021-11-05 21:50 UTC by rpastrana

- Updates structure of metrics README
- Provides detailed steps to route HPCC metrics to Azure insights

Signed-off-by: Rodrigo Pastrana <Rodrigo.Pastrana@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-11-05 21:53 UTC, rpastrana commented
@JamesDeFabia / @g-pan please review

2021-11-05 21:56 UTC, rpastrana commented
@jakesmith or @ghalliday please review

2021-11-05 21:58 UTC, HPCCSmoketest commented
Process of PR-15557, label: HPCC-26790-AzurePrometheus starts now.
The reason of this test is: New commit.
Commit ID: d6259dbd8e56104b4f3dec2710a2202cccce68d7
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-162.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Build only for containerized environment.

2021-11-05 22:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-162.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: d6259dbd8e56104b4f3dec2710a2202cccce68d7
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.4.7-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   14 sec (00:00:14) |  487 sec (00:08:07) |  102 sec (00:01:42) |   18 sec (00:00:18) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  621 sec (00:10:21) |

2021-11-08 16:42 UTC, JamesDeFabia requested changes

2021-11-08 16:42 UTC, JamesDeFabia commented on helm/examples/metrics/README.md
> +  - Can be done from Azure portal, or via CLI
no need for a comma.

2021-11-08 16:42 UTC, JamesDeFabia commented on helm/examples/metrics/README.md
> +### Self Managed Prometheus
s/b Self-managed

2021-11-08 16:42 UTC, JamesDeFabia commented on helm/examples/metrics/README.md
> +On a self managed Prometheus set-up, an "additionalScrapeConfigs" entry is necessary to link the HPCC metrics services to Prometheus
s/b self-managed

2021-11-08 16:45 UTC, JamesDeFabia commented
Also, at the beginning, it might be better to say:
...collection system such as Prometheus, Elasticsearch, or Azure Insights.

2021-11-08 17:38 UTC, JamesDeFabia approved these changes
Looks good from my POV

2021-11-08 17:43 UTC, HPCCSmoketest commented
Process of PR-15557, label: HPCC-26790-AzurePrometheus starts now.
The reason of this test is: Forced to re-test.
Commit ID: 247c793a0a022b4085039c5a1b4e677b7b07ace8
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-66.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Build only for containerized environment.

2021-11-08 17:53 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-66.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: 247c793a0a022b4085039c5a1b4e677b7b07ace8
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.4.7-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   18 sec (00:00:18) |  486 sec (00:08:06) |   98 sec (00:01:38) |   18 sec (00:00:18) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  620 sec (00:10:20) |

2021-11-08 19:41 UTC, HPCCSmoketest commented
Process of PR-15557, label: HPCC-26790-AzurePrometheus starts now.
The reason of this test is: Forced to re-test.
Commit ID: 99541864a9f15e37acfe9e2e3c85ea904f373bc8
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-86.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Build only for containerized environment.

2021-11-08 19:51 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-86.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: 99541864a9f15e37acfe9e2e3c85ea904f373bc8
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.4.7-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   15 sec (00:00:15) |  482 sec (00:08:02) |   98 sec (00:01:38) |   17 sec (00:00:17) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  612 sec (00:10:12) |

2021-11-10 10:26 UTC, ghalliday approved these changes
@rpastrana looks good.  A couple of trivial comments to prove I read it!

2021-11-10 10:26 UTC, ghalliday commented on helm/examples/metrics/container-azm-ms-agentconfig-prometheusperpod.yaml
> +    #   tail_buf_maxsize_megabytes = "1"              # defautl value is 32kb (comment out this line for default)
typo: default

2021-11-10 10:26 UTC, ghalliday commented on helm/examples/metrics/container-azm-ms-agentconfig-prometheusperpod.yaml
> +        # Threshold for completed job count , metric will be sent only for those jobs which were completed earlier than the following threshold
trivia, space before comma.

2021-11-10 14:08 UTC, rpastrana commented
Resolved minor issues and squashed.
@richardkchapman ready for merge

2021-11-10 14:15 UTC, HPCCSmoketest commented
Process of PR-15557, label: HPCC-26790-AzurePrometheus starts now.
The reason of this test is: Forced to re-test.
Commit ID: 29b63575d19fcb2a5ba0b1f634b0568d3b450af7
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-132.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Build only for containerized environment.

2021-11-10 14:25 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-132.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: 29b63575d19fcb2a5ba0b1f634b0568d3b450af7
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.4.7-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   14 sec (00:00:14) |  480 sec (00:08:00) |   97 sec (00:01:37) |   18 sec (00:00:18) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  609 sec (00:10:09) |

2021-11-10 15:38 UTC, merged