HPCC-26786 React version of Banner
hpcc-systems/HPCC-Platform pull request #15567
Opened 2021-11-10 20:27 UTC by jeclrsg

Signed-off-by: Jeremy Clements <jeremy.clements@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-11-10 20:35 UTC, HPCCSmoketest commented
Process of PR-15567, label: hpcc-26786-react-banner starts now.
The reason of this test is: Forced to re-test.
Commit ID: eebc854423e0874260fea4695b8b65edd5904357
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-58.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0

2021-11-10 20:46 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-58.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: eebc854423e0874260fea4695b8b65edd5904357
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.4.11-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  494 sec (00:08:14) |  103 sec (00:01:43) |   20 sec (00:00:20) |   16 sec (00:00:16) |    0 sec (00:00:00) |   14 sec (00:00:14) |  663 sec (00:11:03) |

2021-11-11 07:38 UTC, GordonSmith requested changes

2021-11-11 07:38 UTC, GordonSmith commented on esp/src/src-react/components/Title.tsx
> +
The encapsulation feels wrong here (the "activity" instance should be moved into the Banner file), I would suggest:
* Rename BannerConfig.tsx to Banner.tsx
* Create a new component "BannerMessageBar" inside that file
* Move the "activity" instance (its a global singleton anyway) into both the  BannerConfig and BannerMessageBar components

2021-11-12 19:16 UTC, HPCCSmoketest commented
Process of PR-15567, label: hpcc-26786-react-banner starts now.
The reason of this test is: Forced to re-test.
Commit ID: c2a49a91d3aed157d1e8b9795eb330821e35079b
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-40.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0

2021-11-12 19:19 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-40.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: c2a49a91d3aed157d1e8b9795eb330821e35079b
Containerized:False
Number of Error(s): 4
src-react/components/forms/Banner.tsx(52,26): error TS2339: Property updateBanner does not exist on type Activity.
make[2]: *** [esp/src/CMakeFiles/eclwatch.dir/build.make:337: esp/src/build/dist/stub.eclwatch.js] Error 1
make[1]: *** [CMakeFiles/Makefile2:12844: esp/src/CMakeFiles/eclwatch.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
Get ECLWatch build result
ReportTimes.
Finish at: 2021-11-12_19-19-29
time logs started
Prep time   :    16 sec (00:00:16)
Build time  :   157 sec (00:02:37)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :   173 sec (00:02:53)
time logs end

[Build error:](https://gist.github.com/b2f2122b1c96284ab80cfdca08b92c8d)
Build log [Build log](https://gist.github.com/HPCCSmoketest/b2f2122b1c96284ab80cfdca08b92c8d#file-result-21-11-12-19-16-22-log)

2021-11-12 22:08 UTC, jeclrsg commented
@GordonSmith I converted this to a draft due because it was failing tasks. I also opened a PR for the change to the Activity in hpcc-js that this depends on. And like we'd talked about earlier today, there's still a short delay between changing the banner & the DOM reacting to that change. I thought adding that lastUpdate timestamp in the watch() in the hook I created might work, but no dice.

2021-11-17 10:09 UTC, GordonSmith requested changes

2021-11-19 09:48 UTC, GordonSmith approved these changes

2021-11-19 09:57 UTC, HPCCSmoketest commented
Process of PR-15567, label: hpcc-26786-react-banner starts now.
The reason of this test is: Forced to re-test.
Commit ID: c40f9c7b91756059202b99701e7e1441c0d48e90
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-51.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0

2021-11-19 10:01 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-51.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: c40f9c7b91756059202b99701e7e1441c0d48e90
Containerized:False
Number of Error(s): 7
warn(226) A package without a profile could throw errors or warnings. package: dojo-util
warn(226) A package without a profile could throw errors or warnings. package: dojo-util
\terrors: 0
/home/centos/smoketest/PR-15567/HPCC-Platform/common/thorhelper/thorcommon.cpp:2047:27: error: request for member \xe2\x80\x98length\xe2\x80\x99 in \xe2\x80\x98layoutECL\xe2\x80\x99, which is of non-class type \xe2\x80\x98const char*\xe2\x80\x99
make[2]: *** [common/thorhelper/CMakeFiles/thorhelper.dir/build.make:108: common/thorhelper/CMakeFiles/thorhelper.dir/thorcommon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:10242: common/thorhelper/CMakeFiles/thorhelper.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
Get ECLWatch build result
ReportTimes.
Finish at: 2021-11-19_10-01-35
time logs started
Prep time   :    19 sec (00:00:19)
Build time  :   222 sec (00:03:42)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :   241 sec (00:04:01)
time logs end

[Build error:](https://gist.github.com/1e3f8c71fa4d4e92fa2b402a85f60849)
Build log [Build log](https://gist.github.com/HPCCSmoketest/1e3f8c71fa4d4e92fa2b402a85f60849#file-result-21-11-19-09-57-19-log)

2021-11-19 10:17 UTC, AttilaVamos commented
@jeclrsg I think this PR need to rebase to fix build error.

2021-11-19 14:14 UTC, HPCCSmoketest commented
Process of PR-15567, label: hpcc-26786-react-banner starts now.
The reason of this test is: Forced to re-test.
Commit ID: db2e05049fb6811735c1eaa4a709b5d10f2e4299
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-167.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0

2021-11-19 14:25 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-167.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: db2e05049fb6811735c1eaa4a709b5d10f2e4299
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.4.15-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  496 sec (00:08:16) |  108 sec (00:01:48) |   24 sec (00:00:24) |   16 sec (00:00:16) |    0 sec (00:00:00) |   14 sec (00:00:14) |  674 sec (00:11:14) |

2021-11-29 10:33 UTC, merged