HPCC-26627 Add CookieConsent form component
hpcc-systems/HPCC-Platform pull request #15560
Opened 2021-11-08 15:07 UTC by jbrundage

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2021-11-17 10:15 UTC, GordonSmith commented
@jbrundage - is this still draft?

2021-11-30 15:10 UTC, jbrundage commented
@GordonSmith it's ready for review

2021-11-30 15:18 UTC, HPCCSmoketest commented
Process of PR-15560, label: HPCC-26627 starts now.
The reason of this test is: Forced to re-test.
Commit ID: af6b181275ae1703e9a61194f86f62a17fdf43c6
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-22.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0

2021-11-30 15:21 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-22.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: af6b181275ae1703e9a61194f86f62a17fdf43c6
Containerized:False
Number of Error(s): 6
src-react/components/Frame.tsx(46,29): error TS2739: Type { showCookieConsent: boolean; } is missing the following properties from type CookieConsentProps: onApply, setShowCookieConsent
src-react/components/forms/CookieConsent.tsx(5,10): error TS6133: Fields is declared but its value is never read.
src-react/components/forms/CookieConsent.tsx(33,25): error TS2304: Cannot find name CookieConsentFields.
make[2]: *** [esp/src/CMakeFiles/eclwatch.dir/build.make:337: esp/src/build/dist/stub.eclwatch.js] Error 1
make[1]: *** [CMakeFiles/Makefile2:12844: esp/src/CMakeFiles/eclwatch.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
Get ECLWatch build result
ReportTimes.
Finish at: 2021-11-30_15-21-20
time logs started
Prep time   :    15 sec (00:00:15)
Build time  :   154 sec (00:02:34)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :   169 sec (00:02:49)
time logs end

[Build error:](https://gist.github.com/6571b1863e3f2cf282c8d2fab244ab2d)
Build log [Build log](https://gist.github.com/HPCCSmoketest/6571b1863e3f2cf282c8d2fab244ab2d#file-result-21-11-30-15-18-18-log)

2021-12-03 14:54 UTC, HPCCSmoketest commented
Process of PR-15560, label: HPCC-26627 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 7e8e3b91a9bf42ba515026a682c62aa50176a41b
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-21.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0

2021-12-03 14:57 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-21.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: 7e8e3b91a9bf42ba515026a682c62aa50176a41b
Containerized:False
Number of Error(s): 5
src-react/components/forms/CookieConsent.tsx(16,39): error TS1109: Expression expected.
src-react/components/forms/CookieConsent.tsx(18,1): error TS1109: Expression expected.
make[2]: *** [esp/src/CMakeFiles/eclwatch.dir/build.make:337: esp/src/build/dist/stub.eclwatch.js] Error 1
make[1]: *** [CMakeFiles/Makefile2:12844: esp/src/CMakeFiles/eclwatch.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
Get ECLWatch build result
ReportTimes.
Finish at: 2021-12-03_14-57-32
time logs started
Prep time   :    15 sec (00:00:15)
Build time  :   164 sec (00:02:44)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :   179 sec (00:02:59)
time logs end

[Build error:](https://gist.github.com/7487983382c95190a369f7f4b157025b)
Build log [Build log](https://gist.github.com/HPCCSmoketest/7487983382c95190a369f7f4b157025b#file-result-21-12-03-14-54-18-log)

2021-12-06 13:33 UTC, GordonSmith requested changes
Can you also review:  https://www.cookiepro.com/knowledge/cookie-banner-guidelines/ specifically the GDPR one?

2021-12-06 13:33 UTC, GordonSmith commented on esp/src/src-react/components/Frame.tsx
> +    const consent = !!(getCookie("user_cookie_consent"));
Should use `LocalStorage` from `src/KeyValStore.ts`

2021-12-10 14:18 UTC, HPCCSmoketest commented
Process of PR-15560, label: HPCC-26627 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 89b4880aa86456a22648ca72df90478efc451548
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-254.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0

2021-12-10 14:30 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-254.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.18.0,  cUrl: 7.67.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: 89b4880aa86456a22648ca72df90478efc451548
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.4.15-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   15 sec (00:00:15) |  521 sec (00:08:41) |  118 sec (00:01:58) |   20 sec (00:00:20) |   16 sec (00:00:16) |    0 sec (00:00:00) |   14 sec (00:00:14) |  704 sec (00:11:44) |

2021-12-14 16:26 UTC, GordonSmith requested changes
I am not seeing the GDPR verbage?

2022-01-12 16:20 UTC, GordonSmith requested changes

2022-01-12 16:20 UTC, GordonSmith commented on esp/src/src-react/components/Frame.tsx
> +    sessionKeyValStore().get("user_cookie_consent")
This should be a "userKeyValStore" otherwise it nag the user every session.

2022-01-12 16:20 UTC, GordonSmith commented on esp/src/src-react/components/Frame.tsx
> +    sessionKeyValStore().get("user_cookie_consent")
Also there isa React hook for this:  "useUserStore"

2022-01-12 16:25 UTC, GordonSmith requested changes
Switch from sessionKeyValStore to useUserStore.

2022-01-13 10:26 UTC, richardkchapman commented
Should this target 8.6.x

2022-01-13 14:58 UTC, GordonSmith commented
@richardkchapman it should now.

2022-01-13 15:30 UTC, richardkchapman commented
@jbrundage Please rebase and retarget to 8.6

2022-01-14 12:23 UTC, HPCCSmoketest commented
Process of PR-15560, label: HPCC-26627 starts now.
The reason of this test is: New commit.
Commit ID: 89b4880aa86456a22648ca72df90478efc451548
Estimated completion time is 0.13 hour(s)
centos 7.9.2009 (Linux 3.10.0-1160.49.1.el7.x86_64)
 Host: bctldroxie011.noam.lnrm.net
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 1.8.3.1,  CMake: 3.17.5,  cUrl: 7.29.0,  node.js: v14.15.4,  npm: 6.14.10

2022-01-14 12:41 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.9.2009 (Linux 3.10.0-1160.49.1.el7.x86_64)
 Host: bctldroxie011.noam.lnrm.net
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 1.8.3.1,  CMake: 3.17.5,  cUrl: 7.29.0,  node.js: v14.15.4,  npm: 6.14.10
Sha: 89b4880aa86456a22648ca72df90478efc451548
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.4.15-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   15 sec (00:00:15) |  825 sec (00:13:45) |  144 sec (00:02:24) |   23 sec (00:00:23) |   23 sec (00:00:23) |    0 sec (00:00:00) |   15 sec (00:00:15) | 1045 sec (00:17:25) |

2022-01-19 15:09 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.9.2009 (Linux 3.10.0-1160.49.1.el7.x86_64)
 Host: bctldroxie011.noam.lnrm.net
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 1.8.3.1,  CMake: 3.18.0,  cUrl: 7.29.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: ca4acbde8c765c149469423bc0949194a24363b8
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.6.0-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   21 sec (00:00:21) |  647 sec (00:10:47) |  124 sec (00:02:04) |   22 sec (00:00:22) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  814 sec (00:13:34) |

2022-01-19 16:14 UTC, GordonSmith requested changes

2022-01-19 16:14 UTC, GordonSmith commented on esp/src/src-react/components/Frame.tsx
> +        ;
This should be inside a `React.useEffect` (as it has side effects)

2022-01-19 16:14 UTC, GordonSmith commented on esp/src/src-react/components/Frame.tsx
> +    }}/>;
You can move this into the full return structure

2022-01-19 16:14 UTC, GordonSmith commented on esp/src/src-react/components/forms/CookieConsent.tsx
> +    const closeCookieConsent = () => setShowCookieConsent(false);
This can be moved inline into line 20

2022-01-19 16:19 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.9.2009 (Linux 3.10.0-1160.49.1.el7.x86_64)
 Host: bctldroxie011.noam.lnrm.net
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 1.8.3.1,  CMake: 3.18.0,  cUrl: 7.29.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: 344bd3d4cd42ae813f9c5dbca12ea1c16f783ac9
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.0-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  663 sec (00:11:03) |  131 sec (00:02:11) |   24 sec (00:00:24) |   20 sec (00:00:20) |    0 sec (00:00:00) |   14 sec (00:00:14) |  869 sec (00:14:29) |

2022-01-19 16:20 UTC, HPCCSmoketest commented
Process of PR-15560, label: HPCC-26627 starts now.
The reason of this test is: Base branch changed.
Commit ID: 344bd3d4cd42ae813f9c5dbca12ea1c16f783ac9
Estimated completion time is 0.13 hour(s)
centos 7.9.2009 (Linux 3.10.0-1160.49.1.el7.x86_64)
 Host: bctldroxie011.noam.lnrm.net
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 1.8.3.1,  CMake: 3.18.0,  cUrl: 7.29.0,  node.js: v16.13.0,  npm: 8.1.0

2022-01-19 16:35 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.9.2009 (Linux 3.10.0-1160.49.1.el7.x86_64)
 Host: bctldroxie011.noam.lnrm.net
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 1.8.3.1,  CMake: 3.18.0,  cUrl: 7.29.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: 344bd3d4cd42ae813f9c5dbca12ea1c16f783ac9
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.0-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  655 sec (00:10:55) |  128 sec (00:02:08) |   24 sec (00:00:24) |   19 sec (00:00:19) |    0 sec (00:00:00) |   15 sec (00:00:15) |  858 sec (00:14:18) |

2022-01-19 18:37 UTC, HPCCSmoketest commented
Process of PR-15560, label: HPCC-26627 starts now.
The reason of this test is: New commit.
Commit ID: f69712769ed400c61c21a805cf812352f092497d
Estimated completion time is 0.13 hour(s)
centos 7.9.2009 (Linux 3.10.0-1160.49.1.el7.x86_64)
 Host: bctldroxie011.noam.lnrm.net
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 1.8.3.1,  CMake: 3.18.0,  cUrl: 7.29.0,  node.js: v16.13.0,  npm: 8.1.0

2022-01-19 18:43 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.9.2009 (Linux 3.10.0-1160.49.1.el7.x86_64)
 Host: bctldroxie011.noam.lnrm.net
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 1.8.3.1,  CMake: 3.18.0,  cUrl: 7.29.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: f69712769ed400c61c21a805cf812352f092497d
Containerized:False
Number of Error(s): 6
src-react/components/forms/CookieConsent.tsx(17,94): error TS2552: Cannot find name closeCookieConsent. Did you mean showCookieConsent?
src-react/components/forms/CookieConsent.tsx(19,42): error TS2339: Property CookiesNoticeLinkText does not exist on type { Abort: string; AbortedBy: string; AbortedTime: string; About: string; AboutGraphControl: string; AboutHPCCSystems: string; AboutHPCCSystemsGraphControl: string; AboutToLoseSessionInformation: string; ... 1019 more ...; ZoomWidth: string; }.
src-react/components/forms/CookieConsent.tsx(22,42): error TS2339: Property CookiesAcceptButtonText does not exist on type { Abort: string; AbortedBy: string; AbortedTime: string; About: string; AboutGraphControl: string; AboutHPCCSystems: string; AboutHPCCSystemsGraphControl: string; AboutToLoseSessionInformation: string; ... 1019 more ...; ZoomWidth: string; }.
make[2]: *** [esp/src/CMakeFiles/eclwatch.dir/build.make:337: esp/src/build/dist/stub.eclwatch.js] Error 1
make[1]: *** [CMakeFiles/Makefile2:13264: esp/src/CMakeFiles/eclwatch.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
Get ECLWatch build result
ReportTimes.
Finish at: 2022-01-19_18-43-37
time logs started
Prep time   :    17 sec (00:00:17)
Build time  :   346 sec (00:05:46)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :   363 sec (00:06:03)
time logs end

[Build error:](https://gist.github.com/7ddeff6f0e0c98561a9aef013b9a515f)
Build log [Build log](https://gist.github.com/HPCCSmoketest/7ddeff6f0e0c98561a9aef013b9a515f#file-result-22-01-19-18-37-06-log)

2022-01-19 19:02 UTC, HPCCSmoketest commented
Process of PR-15560, label: HPCC-26627 starts now.
The reason of this test is: Base branch changed.
Commit ID: 9c36cb85be3798f12dae61cb70457b9dbf85d89c
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-56.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-01-19 19:05 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-56.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 9c36cb85be3798f12dae61cb70457b9dbf85d89c
Containerized:False
Number of Error(s): 4
src-react/components/forms/CookieConsent.tsx(17,94): error TS2552: Cannot find name closeCookieConsent. Did you mean showCookieConsent?
make[2]: *** [esp/src/CMakeFiles/eclwatch.dir/build.make:330: esp/src/build/dist/stub.eclwatch.js] Error 1
make[1]: *** [CMakeFiles/Makefile2:12071: esp/src/CMakeFiles/eclwatch.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
Get ECLWatch build result
ReportTimes.
Finish at: 2022-01-19_19-05-10
time logs started
Prep time   :    11 sec (00:00:11)
Build time  :   158 sec (00:02:38)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :   169 sec (00:02:49)
time logs end

[Build error:](https://gist.github.com/3b64b734ae58124125f24a001b2407d5)
Build log [Build log](https://gist.github.com/HPCCSmoketest/3b64b734ae58124125f24a001b2407d5#file-result-22-01-19-19-02-04-log)

2022-01-19 20:16 UTC, HPCCSmoketest commented
Process of PR-15560, label: HPCC-26627 starts now.
The reason of this test is: New commit.
Commit ID: 9c36cb85be3798f12dae61cb70457b9dbf85d89c
Estimated completion time is 0.13 hour(s)
centos 7.9.2009 (Linux 3.10.0-1160.49.1.el7.x86_64)
 Host: bctldroxie011.noam.lnrm.net
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 1.8.3.1,  CMake: 3.18.0,  cUrl: 7.29.0,  node.js: v16.13.0,  npm: 8.1.0

2022-01-19 20:20 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.9.2009 (Linux 3.10.0-1160.49.1.el7.x86_64)
 Host: bctldroxie011.noam.lnrm.net
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 1.8.3.1,  CMake: 3.18.0,  cUrl: 7.29.0,  node.js: v16.13.0,  npm: 8.1.0
Sha: 9c36cb85be3798f12dae61cb70457b9dbf85d89c
Containerized:False
Number of Error(s): 4
src-react/components/forms/CookieConsent.tsx(17,94): error TS2552: Cannot find name closeCookieConsent. Did you mean showCookieConsent?
make[2]: *** [esp/src/CMakeFiles/eclwatch.dir/build.make:337: esp/src/build/dist/stub.eclwatch.js] Error 1
make[1]: *** [CMakeFiles/Makefile2:13264: esp/src/CMakeFiles/eclwatch.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
Get ECLWatch build result
ReportTimes.
Finish at: 2022-01-19_20-20-35
time logs started
Prep time   :    21 sec (00:00:21)
Build time  :   218 sec (00:03:38)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :   239 sec (00:03:59)
time logs end

[Build error:](https://gist.github.com/14b5e5db38ed2e44b3a5d895e0ce62e3)
Build log [Build log](https://gist.github.com/HPCCSmoketest/14b5e5db38ed2e44b3a5d895e0ce62e3#file-result-22-01-19-20-16-04-log)

2022-01-20 16:41 UTC, HPCCSmoketest commented
Process of PR-15560, label: HPCC-26627 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 4fdde97659552fcc9a746b83609a459716aa06d6
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-97.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-01-20 16:52 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-97.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 4fdde97659552fcc9a746b83609a459716aa06d6
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.0-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   25 sec (00:00:25) |  407 sec (00:06:47) |  104 sec (00:01:44) |   19 sec (00:00:19) |   19 sec (00:00:19) |    0 sec (00:00:00) |   14 sec (00:00:14) |  588 sec (00:09:48) |

2022-01-20 16:56 UTC, GordonSmith requested changes

2022-01-20 16:56 UTC, GordonSmith commented on esp/src/src-react/components/Frame.tsx
> +
Nees to be inside a `React.useEffect`

2022-01-21 14:36 UTC, GordonSmith approved these changes

2022-01-26 12:39 UTC, merged