HPCC-27093 Add ESDL based ECL result monitoring support for MySQL
hpcc-systems/HPCC-Platform pull request #15705
Opened 2022-01-28 21:11 UTC by afishbeck

Signed-off-by: Anthony Fishbeck <anthony.fishbeck@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-01-28 21:15 UTC, afishbeck commented
@richardkchapman note that this is a change to a "esdl" command line command only used by scapps for creating alert monitors.

The new file "esdl2monitor_cassandra.xslt" file is really just a copy of the old xslt that did not change at all.

The generated code is being tested by scapps next week, so we shouldn't actually merge until their test is complete.

2022-01-28 21:17 UTC, HPCCSmoketest commented
Process of PR-15705, label: resultMonitorMySql starts now.
The reason of this test is: Forced to re-test.
Commit ID: e6dc9a530ba868012d44f2bdfe24e0d77ac89ecc
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-151.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-01-28 21:48 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-151.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: e6dc9a530ba868012d44f2bdfe24e0d77ac89ecc
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.0-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |65 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |19 |19 |0 |17 sec  (00:00:17) |
|test (hthor) |983 |983 |0 |787 sec  (00:13:07) |
|test (thor) |893 |893 |0 |1011 sec  (00:16:51) |
|test (roxie) |1052 |1052 |0 |905 sec  (00:15:05) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   12 sec (00:00:12) |  420 sec (00:07:00) |  103 sec (00:01:43) |   20 sec (00:00:20) |   16 sec (00:00:16) | 1265 sec (00:21:05) |   17 sec (00:00:17) | 1853 sec (00:30:53) |

2022-02-02 15:44 UTC, HPCCSmoketest commented
Process of PR-15705, label: resultMonitorMySql starts now.
The reason of this test is: Forced to re-test.
Commit ID: 29656307fdd4f81b7482af8e206cb8ac41934f2d
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-11.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-02-02 16:15 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-11.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 29656307fdd4f81b7482af8e206cb8ac41934f2d
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.0-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |65 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |19 |19 |0 |17 sec  (00:00:17) |
|test (hthor) |983 |983 |0 |833 sec  (00:13:53) |
|test (thor) |893 |893 |0 |999 sec  (00:16:39) |
|test (roxie) |1052 |1052 |0 |879 sec  (00:14:39) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  419 sec (00:06:59) |  107 sec (00:01:47) |   19 sec (00:00:19) |   16 sec (00:00:16) | 1254 sec (00:20:54) |   18 sec (00:00:18) | 1850 sec (00:30:50) |

2022-02-03 22:21 UTC, afishbeck commented on esp/xslt/esdl2monitor.xslt
> +IMPORT mysql;
Note that Cassandra support has been moved to a different file: `esdl2monitor_cassandra.xslt`

2022-02-03 22:22 UTC, afishbeck commented on esp/xslt/esdl2monitor_cassandra.xslt
> +<?xml version="1.0" encoding="UTF-8"?>
Note that this is just a copy of the old esdl2monitor.xslt.  Nothing has changed except the copyright date.

2022-02-03 22:24 UTC, afishbeck commented
The ECL and ESP (WsNotify) developers have given a thumbs up to these changes.  They have tested the ECL code generated by this tool for their project.

2022-02-03 22:31 UTC, HPCCSmoketest commented
Process of PR-15705, label: resultMonitorMySql starts now.
The reason of this test is: Forced to re-test.
Commit ID: 640af6a8597839d8227447c6e6c62884ee29d27a
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-135.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-02-03 23:02 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-135.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 640af6a8597839d8227447c6e6c62884ee29d27a
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.0-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |64 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |0 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |19 |19 |0 |18 sec  (00:00:18) |
|test (hthor) |983 |983 |0 |789 sec  (00:13:09) |
|test (thor) |893 |893 |0 |1008 sec  (00:16:48) |
|test (roxie) |1052 |1052 |0 |887 sec  (00:14:47) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   15 sec (00:00:15) |  415 sec (00:06:55) |  102 sec (00:01:42) |   20 sec (00:00:20) |   15 sec (00:00:15) | 1264 sec (00:21:04) |   18 sec (00:00:18) | 1849 sec (00:30:49) |

2022-02-04 16:20 UTC, asselitx requested changes
@afishbeck Perhaps just two small changes needed that I've commented on.

2022-02-04 18:07 UTC, afishbeck commented on tools/esdlcmd/esdlcmd_monitor.cpp
> +        puts("   --use-cassandra                        Gerate monitoring code that stores it's state in Cassandra (default is MySQL)");
I've fixed the spelling.

2022-02-04 18:08 UTC, afishbeck commented on esp/xslt/esdl2monitor.xslt
>      <xsl:param name="diffmode" select="'Monitor'"/>
We don't typically update the copyright when we make code changes to a file.

2022-02-04 18:08 UTC, HPCCSmoketest commented
Process of PR-15705, label: resultMonitorMySql starts now.
The reason of this test is: Forced to re-test.
Commit ID: 912fd7ff521fe850917300a913c1c0244382b094
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-64.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-02-04 18:09 UTC, afishbeck commented
@asselitx updated the spelling.

2022-02-04 18:11 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-64.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 912fd7ff521fe850917300a913c1c0244382b094
Containerized:False
Number of Error(s): 3
make[2]: *** [esp/src/CMakeFiles/eclwatch_fetchdeps.dir/build.make:73: esp/src/lib/package-lock.json] Error 1
make[1]: *** [CMakeFiles/Makefile2:12294: esp/src/CMakeFiles/eclwatch_fetchdeps.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
Get ECLWatch build result
ReportTimes.
Finish at: 2022-02-04_18-11-11
time logs started
Prep time   :    22 sec (00:00:22)
Build time  :   129 sec (00:02:09)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :   151 sec (00:02:31)
time logs end

[Build error:](https://gist.github.com/58016b172dbb9c5e6df6175191a45f38)
Build log [Build log](https://gist.github.com/HPCCSmoketest/58016b172dbb9c5e6df6175191a45f38#file-result-22-02-04-18-08-24-log)

2022-02-04 18:34 UTC, HPCCSmoketest commented
Process of PR-15705, label: resultMonitorMySql starts now.
The reason of this test is: Forced to re-test.
Commit ID: 912fd7ff521fe850917300a913c1c0244382b094
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-224.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-02-04 19:05 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-224.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 912fd7ff521fe850917300a913c1c0244382b094
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.0-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |66 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |22 sec  (00:00:22) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |19 |19 |0 |17 sec  (00:00:17) |
|test (hthor) |983 |983 |0 |817 sec  (00:13:37) |
|test (thor) |893 |893 |0 |991 sec  (00:16:31) |
|test (roxie) |1052 |1052 |0 |933 sec  (00:15:33) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  419 sec (00:06:59) |  113 sec (00:01:53) |   20 sec (00:00:20) |   16 sec (00:00:16) | 1248 sec (00:20:48) |   17 sec (00:00:17) | 1849 sec (00:30:49) |

2022-02-04 20:35 UTC, asselitx approved these changes
@afishbeck  looks good.

2022-02-04 22:08 UTC, afishbeck commented
@richardkchapman the PR is ready to merge.  It only affects a command line tools used to generate ECL used for alerting/monitoring projects.

2022-02-07 11:33 UTC, merged