HPCC-24728 Convert fileservices to use ecllib for windows installs
hpcc-systems/HPCC-Platform pull request #15700
Opened 2022-01-27 16:09 UTC by GordonSmith

Removes the need to load the dll and choke on any further dependencies

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-01-27 16:15 UTC, HPCCSmoketest commented
Process of PR-15700, label: HPCC-24728-LIBFILESERVES starts now.
The reason of this test is: Forced to re-test.
Commit ID: 424c9b00873a2aa0f6e7294458e8ca8ba2ecb96b
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-195.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-01-27 16:29 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-195.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 424c9b00873a2aa0f6e7294458e8ca8ba2ecb96b
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.0-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |64 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |4 |5 |4 sec  (00:00:04) |
|setup (thor) |9 |4 |5 |5 sec  (00:00:05) |
|setup (roxie) |19 |14 |5 |9 sec  (00:00:09) |
|test (hthor) |0 |0 |0 |N/A |
|test (thor) |0 |0 |0 |N/A |
|test (roxie) |0 |0 |0 |N/A |


[Errors:](https://gist.github.com/62e8d291becf9dd2669e72bac1ab7e46)
- setup
  - hthor
    - 2\. [setup](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setup-w20220127-162822-3-log), 3\. [setup_fetch](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setup_fetch-w20220127-162822-log), 6\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setupsearchindex-w20220127-162823-4-log), 7\. [setupsq](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setupsq-w20220127-162823-6-log), 8\. [setupwordindex](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setupwordindex-w20220127-162823-log), 
  - thor
    - 2\. [setup](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setup-w20220127-162827-2-log), 3\. [setup_fetch](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setup_fetch-w20220127-162827-3-log), 6\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setupsearchindex-w20220127-162827-8-log), 7\. [setupsq](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setupsq-w20220127-162827-6-log), 8\. [setupwordindex](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setupwordindex-w20220127-162827-1-log), 
  - roxie
    - 11\. [setup](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setup-w20220127-162835-log), 12\. [setup_fetch](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setup_fetch-w20220127-162835-7-log), 15\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setupsearchindex-w20220127-162835-2-log), 16\. [setupsq](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setupsq-w20220127-162836-log), 17\. [setupwordindex](https://gist.github.com/HPCCSmoketest/62e8d291becf9dd2669e72bac1ab7e46#file-setupwordindex-w20220127-162836-2-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   30 sec (00:00:30) |  425 sec (00:07:05) |  108 sec (00:01:48) |   20 sec (00:00:20) |   16 sec (00:00:16) |  182 sec (00:03:02) |   14 sec (00:00:14) |  795 sec (00:13:15) |

2022-01-31 11:07 UTC, richardkchapman commented
There's a typo in the commit message

2022-01-31 12:54 UTC, GordonSmith commented
@richardkchapman that was already fixed, but I updated the title here to reflect the change.

2022-01-31 15:02 UTC, richardkchapman commented
@GordonSmith The smoketest failures need looking at

2022-01-31 15:26 UTC, GordonSmith commented
Yes, I saw that.  May need to liaise with @ghalliday to work out why (and I would like to start building the client tools on my windows machine again).

2022-01-31 15:53 UTC, richardkchapman requested changes

2022-01-31 15:53 UTC, richardkchapman commented on plugins/proxies/lib_fileservices.ecllib
> +export FileServices := SERVICE : plugin('fileserviceslib'), time
I think this should say "plugin('fileservices')"

2022-01-31 15:53 UTC, richardkchapman commented
@GordonSmith I think you have the plugin name wrong in the ecllib file which is causing the setup errors

2022-01-31 16:14 UTC, HPCCSmoketest commented
Process of PR-15700, label: HPCC-24728-LIBFILESERVES starts now.
The reason of this test is: Forced to re-test.
Commit ID: 14e0fdbf61a31632b7530bb4ab6e60760a76cb92
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-148.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-01-31 16:45 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-148.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 14e0fdbf61a31632b7530bb4ab6e60760a76cb92
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.0-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |64 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |19 |19 |0 |17 sec  (00:00:17) |
|test (hthor) |983 |983 |0 |786 sec  (00:13:06) |
|test (thor) |893 |893 |0 |1015 sec  (00:16:55) |
|test (roxie) |1052 |1052 |0 |903 sec  (00:15:03) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  415 sec (00:06:55) |  102 sec (00:01:42) |   19 sec (00:00:19) |   16 sec (00:00:16) | 1269 sec (00:21:09) |   18 sec (00:00:18) | 1855 sec (00:30:55) |

2022-01-31 16:53 UTC, richardkchapman approved these changes

2022-02-01 05:21 UTC, GordonSmith commented
@ghalliday @richardkchapman - if the plugin loader only uses the ecllib file. "if" the dll does not include it, then this won't fix the underlying issue?

2022-02-01 09:30 UTC, ghalliday commented
@GordonSmith this should fix the problem - because the system will not try to load the .dll file - so you will not hit the problem of the missing dependency.  You would still hit the problem if you built a local stand alone program and tried to run it - but that is fairly unusual.

2022-02-01 09:32 UTC, ghalliday approved these changes

2022-02-01 09:32 UTC, merged