HPCC-27097 NLP Plugin: Fails to execute sample code
hpcc-systems/HPCC-Platform pull request #15737
Opened 2022-02-04 21:41 UTC by dehilsterlexis

Signed-off-by: David de Hilster <david.dehilster@lexisnexisrisk.com>

2022-02-04 21:48 UTC, HPCCSmoketest commented
Process of PR-15737, label: HPCC-27097 starts now.
The reason of this test is: New commit.
Commit ID: c4a628d9b8748743aa6aaaf4faaccdcc9b2f0f48
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-179.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-02-04 22:20 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-179.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: c4a628d9b8748743aa6aaaf4faaccdcc9b2f0f48
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |67 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |22 sec  (00:00:22) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |19 |19 |0 |18 sec  (00:00:18) |
|test (hthor) |983 |983 |0 |847 sec  (00:14:07) |
|test (thor) |893 |893 |0 |1027 sec  (00:17:07) |
|test (roxie) |1052 |1052 |0 |907 sec  (00:15:07) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  441 sec (00:07:21) |  108 sec (00:01:48) |   22 sec (00:00:22) |   15 sec (00:00:15) | 1287 sec (00:21:27) |   19 sec (00:00:19) | 1908 sec (00:31:48) |

2022-02-07 11:31 UTC, richardkchapman requested changes

2022-02-07 11:31 UTC, richardkchapman commented on plugins/nlp/nlp.cpp
> +        char *txtBuff = (char *)malloc(txtLen+1);
Is this ever freed?

Use of StringBuffer might be more appropriate.

2022-02-07 13:13 UTC, HPCCSmoketest commented
Process of PR-15737, label: HPCC-27097 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 7102047dbeae310eba8f4ffeb24de3ced3010a48
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-139.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-02-07 13:51 UTC, richardkchapman approved these changes

2022-02-07 13:51 UTC, dehilsterlexis commented
@GordonSmith for review

2022-02-07 13:52 UTC, merged