HPCC-27209 VCPKG Client Tools Support
hpcc-systems/HPCC-Platform pull request #15794
Opened 2022-02-18 11:55 UTC by GordonSmith

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-02-18 12:06 UTC, richardkchapman approved these changes

2022-02-18 16:14 UTC, GordonSmith commented on system/logaccess/CMakeLists.txt
>  ENDIF()
@rpastrana is it ok to assume that the elasticstack client can be omitted for client tools?

2022-02-18 16:19 UTC, HPCCSmoketest commented
Process of PR-15794, label: HPCC-27209-NSIS starts now.
The reason of this test is: Forced to re-test.
Commit ID: dff39adcbc921f013907671beeed319017bce703
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-34.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-02-18 16:52 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-34.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: dff39adcbc921f013907671beeed319017bce703
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.3-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |68 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |0 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |23 sec  (00:00:23) |
|setup (thor) |9 |9 |0 |40 sec  (00:00:40) |
|setup (roxie) |19 |19 |0 |19 sec  (00:00:19) |
|test (hthor) |984 |984 |0 |856 sec  (00:14:16) |
|test (thor) |894 |894 |0 |1071 sec  (00:17:51) |
|test (roxie) |1053 |1053 |0 |903 sec  (00:15:03) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   24 sec (00:00:24) |  446 sec (00:07:26) |  112 sec (00:01:52) |   20 sec (00:00:20) |   16 sec (00:00:16) | 1336 sec (00:22:16) |   19 sec (00:00:19) | 1973 sec (00:32:53) |

2022-03-04 05:50 UTC, HPCCSmoketest commented
Process of PR-15794, label: HPCC-27209-NSIS starts now.
The reason of this test is: Forced to re-test.
Commit ID: e8fd61b5949781772f971009b20b38a402c479c7
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-141.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-04 06:22 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-141.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: e8fd61b5949781772f971009b20b38a402c479c7
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.9-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |69 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |22 sec  (00:00:22) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |20 |20 |0 |18 sec  (00:00:18) |
|test (hthor) |984 |984 |0 |849 sec  (00:14:09) |
|test (thor) |894 |894 |0 |1029 sec  (00:17:09) |
|test (roxie) |1054 |1054 |0 |908 sec  (00:15:08) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  440 sec (00:07:20) |  108 sec (00:01:48) |   22 sec (00:00:22) |   16 sec (00:00:16) | 1290 sec (00:21:30) |   19 sec (00:00:19) | 1912 sec (00:31:52) |

2022-03-04 09:30 UTC, richardkchapman requested changes

2022-03-04 09:30 UTC, richardkchapman commented on CMakeLists.txt
> +            if (EXISTS "${SIGN_DIRECTORY}/passphrase.txt")
Indentation feels off here

2022-03-04 10:38 UTC, GordonSmith commented on CMakeLists.txt
> +            if (EXISTS "${SIGN_DIRECTORY}/passphrase.txt")
Fixed

2022-03-04 10:43 UTC, HPCCSmoketest commented
Process of PR-15794, label: HPCC-27209-NSIS starts now.
The reason of this test is: Forced to re-test.
Commit ID: 82bf1f3915c64b81ec3735f19e660931138fc086
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-230.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-04 11:18 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-230.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 82bf1f3915c64b81ec3735f19e660931138fc086
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.9-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |66 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |20 |20 |0 |17 sec  (00:00:17) |
|test (hthor) |984 |984 |0 |786 sec  (00:13:06) |
|test (thor) |894 |894 |0 |952 sec  (00:15:52) |
|test (roxie) |1054 |1053 |1 |1220 sec  (00:20:20) |


[Errors:](https://gist.github.com/13bab81765517fc8a83fa6d322988ed5)
- test
  - roxie
    - 1031\. [workflow_contingency_8 (parallel=true)](https://gist.github.com/HPCCSmoketest/13bab81765517fc8a83fa6d322988ed5#file-workflow_contingency_8-parallel-true-w20220304-111148-5-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   15 sec (00:00:15) |  415 sec (00:06:55) |  104 sec (00:01:44) |   19 sec (00:00:19) |   16 sec (00:00:16) | 1476 sec (00:24:36) |   18 sec (00:00:18) | 2063 sec (00:34:23) |

2022-03-04 11:46 UTC, AttilaVamos commented
@GordonSmith I am sure the regression is not related to this PR.

2022-03-04 11:55 UTC, HPCCSmoketest commented
Process of PR-15794, label: HPCC-27209-NSIS starts now.
The reason of this test is: Forced to re-test.
Commit ID: 82bf1f3915c64b81ec3735f19e660931138fc086
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-35.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-09 16:36 UTC, rpastrana approved these changes
@GordonSmith do any of the clienttool components require access to jlog output?
Currently WsLogAccess, and soon WsWorkunits will be referencing logaccess if those are not part of clienttools, it is safe to exclude elasticlient.

2022-03-10 06:39 UTC, GordonSmith commented
@rpastrana I don't know offhand, but even if they did, they would access via ESP?

2022-03-10 14:07 UTC, rpastrana commented
> @rpastrana I don't know offhand, but even if they did, they would access via ESP?

Accessing the logs via ESP is fine, the problem would come in if any client tool components required accessing the jlog output directly through the logaccess API. It seems fine to exclude elasticlient from client tools. @GordonSmith

2022-03-10 14:12 UTC, richardkchapman approved these changes

2022-03-10 14:12 UTC, merged