HPCC-27211 process dynamic shared lib path for files under lib2 separately
hpcc-systems/HPCC-Platform pull request #15803
Opened 2022-02-21 19:53 UTC by xwang2713

The root problem of that the files under lib2/ may also depend other libraries in this directory. But the process order may leave some libraries improbably handled. For example libicui18n.60.2.dylib depends on lib2/libicuuc.60.2.dylib. If libicui18n.60.2.dylib is processed before libicuuc.60.2.dylib adding to lib2 directory the dependency of libicuuc.60.2.dylib is not correctly updated.

The current fix is to process all files under lib2 after all of them added to lib2 directory.

Also fixed JIRA HPCC-27193  extra "endif()" in lib2/CMakeLists.txt
Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-02-21 19:55 UTC, xwang2713 commented
Private fix to verify: http://10.224.20.10/builds/custom/JIRA/HPCC-27211/hpccsystems-clienttools-community_8.6.5-closedown0Darwin-x86_64.dmg

2022-02-21 19:58 UTC, HPCCSmoketest commented
Process of PR-15803, label: HPCC-27211-dynamic-shared-lib-path-4-files-in-lib2 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 4ee71849d464b7e3508590c0e524548bcfea6c82
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-80.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-02-21 20:28 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-80.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 4ee71849d464b7e3508590c0e524548bcfea6c82
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.5-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |64 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |0 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |19 |19 |0 |17 sec  (00:00:17) |
|test (hthor) |984 |984 |0 |796 sec  (00:13:16) |
|test (thor) |894 |894 |0 |966 sec  (00:16:06) |
|test (roxie) |1053 |1053 |0 |901 sec  (00:15:01) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   15 sec (00:00:15) |  410 sec (00:06:50) |  101 sec (00:01:41) |   19 sec (00:00:19) |   18 sec (00:00:18) | 1220 sec (00:20:20) |   19 sec (00:00:19) | 1802 sec (00:30:02) |

2022-02-22 09:39 UTC, richardkchapman requested changes

2022-02-22 09:39 UTC, richardkchapman commented on lib2/CMakeLists.txt
> +# Update dynmaic shared library path for libraries under lib2/
typo: dynamic

2022-02-22 13:17 UTC, dcamper commented
> @dcamper a private fix to verify: http://10.224.20.10/builds/custom/JIRA/HPCC-27211/hpccsystems-clienttools-community_8.6.5-closedown0Darwin-x86_64.dmg

I just tested this and it appears to work (using the simple tests found in the Jira):

[2022-02-22 07:15:06 -0600]
campda01@HBECAMPDA01-MAC:/opt/HPCCSystems/8.6.5/clienttools/bin $ ./ecl --version
community_8.6.5-closedown0[remotes/origin/HPCC-27211-dynamic-shared-lib-path-4-files-in-lib2-0-g4ee718]

[2022-02-22 07:15:10 -0600]
campda01@HBECAMPDA01-MAC:/opt/HPCCSystems/8.6.5/clienttools/bin $ ./eclcc --version
8.6.5 community_8.6.5-closedown0[remotes/origin/HPCC-27211-dynamic-shared-lib-path-4-files-in-lib2-0-g4ee718]

2022-02-23 17:57 UTC, Michael-Gardner approved these changes
Approving. I had noticed that the get_filename_component cmake call had changed in the latest cmake release, but had no difficulty building.

2022-02-24 15:27 UTC, xwang2713 commented on lib2/CMakeLists.txt
> +# Update dynmaic shared library path for libraries under lib2/
Fixed and rebased

2022-02-24 15:32 UTC, HPCCSmoketest commented
Process of PR-15803, label: HPCC-27211-dynamic-shared-lib-path-4-files-in-lib2 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 2ec6e85ec6144af59b3c2d0cbe01312212293246
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-22.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-02-24 16:04 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-22.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 2ec6e85ec6144af59b3c2d0cbe01312212293246
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.5-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |69 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |23 sec  (00:00:23) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |19 |19 |0 |18 sec  (00:00:18) |
|test (hthor) |984 |984 |0 |895 sec  (00:14:55) |
|test (thor) |894 |894 |0 |1016 sec  (00:16:56) |
|test (roxie) |1053 |1053 |0 |896 sec  (00:14:56) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  440 sec (00:07:20) |  118 sec (00:01:58) |   21 sec (00:00:21) |   16 sec (00:00:16) | 1279 sec (00:21:19) |   19 sec (00:00:19) | 1910 sec (00:31:50) |

2022-02-24 16:41 UTC, richardkchapman approved these changes

2022-02-24 16:42 UTC, merged