HPCC-24691 Convert ESP to use jlog standards
hpcc-systems/HPCC-Platform pull request #15877
Opened 2022-03-09 14:11 UTC by kenrowland

Converted code for container builds to use log category set
in config yaml files. Legacy bare metal continues to use
existing ESP log level.

Signed-off-by: Ken Rowland kenneth.rowland@lexisnexisrisk.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-03-09 16:59 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-252.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: baa307977356ce068df8289d354a427ccd1e5551
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |65 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |0 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |22 sec  (00:00:22) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |20 |20 |0 |18 sec  (00:00:18) |
|test (hthor) |984 |984 |0 |833 sec  (00:13:53) |
|test (thor) |894 |894 |0 |1002 sec  (00:16:42) |
|test (roxie) |1054 |1054 |0 |887 sec  (00:14:47) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   15 sec (00:00:15) |  418 sec (00:06:58) |  107 sec (00:01:47) |   22 sec (00:00:22) |   16 sec (00:00:16) | 1258 sec (00:20:58) |   18 sec (00:00:18) | 1854 sec (00:30:54) |

2022-03-09 21:35 UTC, HPCCSmoketest commented
Process of PR-15877, label: HPCC-24691 starts now.
The reason of this test is: Forced to re-test.
Commit ID: bd41052721dfe74aa686b2772ef492c87c8cfd06
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-97.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-09 21:48 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-97.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: bd41052721dfe74aa686b2772ef492c87c8cfd06
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |64 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |0 |9 |2 sec  (00:00:02) |
|setup (thor) |9 |0 |9 |2 sec  (00:00:02) |
|setup (roxie) |20 |0 |20 |3 sec  (00:00:03) |
|test (hthor) |0 |0 |0 |N/A |
|test (thor) |0 |0 |0 |N/A |
|test (roxie) |0 |0 |0 |N/A |


[Errors:](https://gist.github.com/3fc6a6acb7603102f4e70091f7642e7c)
- setup
  - hthor
    - 1\. [aaawriteresult](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-aaawriteresult-no-wuid-log), 2\. [setup](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setup-no-wuid-log), 3\. [setup_fetch](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setup_fetch-no-wuid-log), 4\. [setupdict](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setupdict-no-wuid-log), 5\. [setuppersist](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setuppersist-no-wuid-log), 6\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setupsearchindex-no-wuid-log), 7\. [setupsq](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setupsq-no-wuid-log), 8\. [setupwordindex](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setupwordindex-no-wuid-log), 9\. [setupxml](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setupxml-no-wuid-log), 
  - thor
    - 1\. [aaawriteresult](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-aaawriteresult-no-wuid-log), 2\. [setup](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setup-no-wuid-log), 3\. [setup_fetch](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setup_fetch-no-wuid-log), 4\. [setupdict](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setupdict-no-wuid-log), 5\. [setuppersist](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setuppersist-no-wuid-log), 6\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setupsearchindex-no-wuid-log), 7\. [setupsq](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setupsq-no-wuid-log), 8\. [setupwordindex](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setupwordindex-no-wuid-log), 9\. [setupxml](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-setupxml-no-wuid-log), 
  - roxie
    - 1\. [aaajavalibrary](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-aaajavalibrary-no-wuid-log), 2\. [aaalibrary2](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-aaalibrary2-no-wuid-log), 3\. [aaalibrary3a](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-aaalibrary3a-no-wuid-log), 4\. [aaalibrary3b](https://gist.github.com/HPCCSmoketest/3fc6a6acb7603102f4e70091f7642e7c#file-aaalibrary3b-no-wu
 ... ( comment is too long, 49 lines, 6095 bytes, truncated) ... 
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  412 sec (00:06:52) |  101 sec (00:01:41) |   19 sec (00:00:19) |   16 sec (00:00:16) |  171 sec (00:02:51) |   14 sec (00:00:14) |  749 sec (00:12:29) |

```

2022-03-10 10:53 UTC, HPCCSmoketest commented
Process of PR-15877, label: HPCC-24691 starts now.
The reason of this test is: Forced to re-test.
Commit ID: bd41052721dfe74aa686b2772ef492c87c8cfd06
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-250.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-10 11:06 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-250.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: bd41052721dfe74aa686b2772ef492c87c8cfd06
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |65 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |0 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |0 |9 |2 sec  (00:00:02) |
|setup (thor) |9 |0 |9 |2 sec  (00:00:02) |
|setup (roxie) |20 |0 |20 |3 sec  (00:00:03) |
|test (hthor) |0 |0 |0 |N/A |
|test (thor) |0 |0 |0 |N/A |
|test (roxie) |0 |0 |0 |N/A |


[Errors:](https://gist.github.com/bdb714ef71c4b7927c890febd92550f1)
- setup
  - hthor
    - 1\. [aaawriteresult](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-aaawriteresult-no-wuid-log), 2\. [setup](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setup-no-wuid-log), 3\. [setup_fetch](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setup_fetch-no-wuid-log), 4\. [setupdict](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setupdict-no-wuid-log), 5\. [setuppersist](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setuppersist-no-wuid-log), 6\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setupsearchindex-no-wuid-log), 7\. [setupsq](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setupsq-no-wuid-log), 8\. [setupwordindex](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setupwordindex-no-wuid-log), 9\. [setupxml](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setupxml-no-wuid-log), 
  - thor
    - 1\. [aaawriteresult](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-aaawriteresult-no-wuid-log), 2\. [setup](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setup-no-wuid-log), 3\. [setup_fetch](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setup_fetch-no-wuid-log), 4\. [setupdict](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setupdict-no-wuid-log), 5\. [setuppersist](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setuppersist-no-wuid-log), 6\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setupsearchindex-no-wuid-log), 7\. [setupsq](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setupsq-no-wuid-log), 8\. [setupwordindex](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setupwordindex-no-wuid-log), 9\. [setupxml](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-setupxml-no-wuid-log), 
  - roxie
    - 1\. [aaajavalibrary](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-aaajavalibrary-no-wuid-log), 2\. [aaalibrary2](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-aaalibrary2-no-wuid-log), 3\. [aaalibrary3a](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-aaalibrary3a-no-wuid-log), 4\. [aaalibrary3b](https://gist.github.com/HPCCSmoketest/bdb714ef71c4b7927c890febd92550f1#file-aaalibrary3b-no-w
 ... ( comment is too long, 49 lines, 6096 bytes, truncated) ... 
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   14 sec (00:00:14) |  419 sec (00:06:59) |  102 sec (00:01:42) |   20 sec (00:00:20) |   16 sec (00:00:16) |  171 sec (00:02:51) |   14 sec (00:00:14) |  756 sec (00:12:36) |

```

2022-03-10 14:14 UTC, HPCCSmoketest commented
Process of PR-15877, label: HPCC-24691 starts now.
The reason of this test is: Forced to re-test.
Commit ID: a449893e9a00b070a5a4ef4e87e00b5f74b66978
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-196.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-10 14:44 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-196.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: a449893e9a00b070a5a4ef4e87e00b5f74b66978
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |65 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |20 |20 |0 |17 sec  (00:00:17) |
|test (hthor) |984 |984 |0 |784 sec  (00:13:04) |
|test (thor) |894 |894 |0 |954 sec  (00:15:54) |
|test (roxie) |1054 |1054 |0 |892 sec  (00:14:52) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   24 sec (00:00:24) |  411 sec (00:06:51) |  101 sec (00:01:41) |   19 sec (00:00:19) |   18 sec (00:00:18) | 1209 sec (00:20:09) |   19 sec (00:00:19) | 1801 sec (00:30:01) |

2022-03-11 09:27 UTC, ghalliday requested changes
This PR contains various categories of changes.  I think it is worth looking at each of them in turn.

1. ESPLOG(LogMax, ...) -> LOG(LegacyMsgCatMax, ...)

Previously these would have been output as DBGLOG() if the logging level was set sufficiently high.  Now they generate invalid logging lines because LegacyMsgCatMax does not define a valid category/audience.  (Audience/class unknown).  E.g.

`00000017 UNK 2022-03-11 08:53:29.986 397162 397682 "POST /WsStore/Set.json, from 192.168.86.202"
`
This suggests the logging output wasn't compared, or looked at carefully.

This change makes sense, but it should be using a valid category, and it is worth taking the time to choose the correct category as those changes are done.

See https://github.com/hpcc-systems/HPCC-Platform/pull/12188 for a similar change in the rest of the platform a while back - where each log message was carefully categorized when the function was changed.


2. ESPLOG(LogMax, "CLogFailSafe::~CLogFailSafe()"); -> DBGLOG()

It is now generating a message for normal logging, where it would have been a max level before.  Probably just a bug , there may be more like this (I didn't check).


3. DBGLOG(...) -> LOG(LegacyMsgCatMax, ...)

E.g.
```
if (getEspLogLevel()>LogNormal)
    DBGLOG("Response content: %s", response.str());

```
->
`    LOG(LegacyMsgCatMax,"Response content: %s", response.str());
`
Previously this would have output a DBGLOG entry with a log level of DebugMsgThreshold(80) if the logging level was raised.   Now it will be reported with level of ExtraneousMsgThreshold(90).  It will appear in any logs which have also had their logging detail level increased (esp log and stderr).  This is a reasonable change, (except for the change of category), because it is being more specific about the category of the line being output..

4. Elevated logging

```
if (getEspLogLevel(rpccall.queryContext())>LogNormal)
    DBGLOG("Content type: %s", contenttypestr.str());

```
->
```
auto logCat = (rpccall.queryContext() != nullptr) ? (rpccall.queryContext()->debugTraceEnabled() ? MsgCatEspElevated : LegacyMsgCatMax) : LegacyMsgCatMax;
LOG(logCat, "Content type: %s", contenttypestr.str());
```

The new code is much harder to read/understand.

Previously it would have output the logging as a DebugMsgThreshold if detailed logging as selected, or if the special debug mode was selected.

Now it always reports the message.  It either has a detail level of ExtraneousMsgThreshold, or it has a elevated category.   It has the same effect (other than losing the category) for bare-metal, including if the detail level was changed on the logging.

The way the MsgCatEspElevated has been implemented means that the logging lines will no longer be output as "DBG" - so it has lost details of the expected audience and category.  I'm also not convinced the mechanism is clearly explained - what this category means.

There are two separate questions, which logging lines should be generated, and which logging lines should be output to each of the different targets.  I think this is attempting to solve the first question using the mechanism that solves the second.  It probably requires a different solution.  

NOTE: With this change the log lines are now comming out non-sequentially in esp e.g.

```
00000009 UNK 2022-03-11 08:53:29.771 397162 397364 "GET /esp/files/dist/font-awesome/css/font-awesome.min.css, from 192.168.86.202"
0000000F UNK 2022-03-11 08:53:29.771 397162 397376 "GET /esp/files/node_modules/es6-promise/dist/es6-promise.auto.min.js, from 192.168.86.202"
```

This suggests that logging is not being caught by the pre-filter, or some other issue that needs investigating.


In conclusion, I don't think any of the categories of changes to the logging lines is correct (except for #3) - the problem needs to be understood better.  There are also some implementation issues, but I haven't checked carefully or commented on them.

2022-03-14 12:38 UTC, ghalliday commented
A couple of other comments.  It would be better to have the change broken up into smaller chunks.  It looks like something similar happened to https://github.com/hpcc-systems/HPCC-Platform/pull/12188 - it was broken up into smaller changes.
I'll discuss this with Richard/Jake/others to see if we can agree on the best approach.

2022-03-15 19:23 UTC, HPCCSmoketest commented
Process of PR-15877, label: HPCC-24691 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 44df1e75bd47b98676e3ca0903b4476f7cc666f8
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-192.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-15 19:36 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-192.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 44df1e75bd47b98676e3ca0903b4476f7cc666f8
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |65 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |0 |9 |2 sec  (00:00:02) |
|setup (thor) |9 |0 |9 |2 sec  (00:00:02) |
|setup (roxie) |20 |0 |20 |3 sec  (00:00:03) |
|test (hthor) |0 |0 |0 |N/A |
|test (thor) |0 |0 |0 |N/A |
|test (roxie) |0 |0 |0 |N/A |


[Errors:](https://gist.github.com/370037661e72d0345ddd010dd1344b87)
- setup
  - hthor
    - 1\. [aaawriteresult](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-aaawriteresult-no-wuid-log), 2\. [setup](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setup-no-wuid-log), 3\. [setup_fetch](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setup_fetch-no-wuid-log), 4\. [setupdict](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setupdict-no-wuid-log), 5\. [setuppersist](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setuppersist-no-wuid-log), 6\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setupsearchindex-no-wuid-log), 7\. [setupsq](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setupsq-no-wuid-log), 8\. [setupwordindex](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setupwordindex-no-wuid-log), 9\. [setupxml](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setupxml-no-wuid-log), 
  - thor
    - 1\. [aaawriteresult](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-aaawriteresult-no-wuid-log), 2\. [setup](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setup-no-wuid-log), 3\. [setup_fetch](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setup_fetch-no-wuid-log), 4\. [setupdict](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setupdict-no-wuid-log), 5\. [setuppersist](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setuppersist-no-wuid-log), 6\. [setupsearchindex](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setupsearchindex-no-wuid-log), 7\. [setupsq](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setupsq-no-wuid-log), 8\. [setupwordindex](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setupwordindex-no-wuid-log), 9\. [setupxml](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-setupxml-no-wuid-log), 
  - roxie
    - 1\. [aaajavalibrary](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-aaajavalibrary-no-wuid-log), 2\. [aaalibrary2](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-aaalibrary2-no-wuid-log), 3\. [aaalibrary3a](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-aaalibrary3a-no-wuid-log), 4\. [aaalibrary3b](https://gist.github.com/HPCCSmoketest/370037661e72d0345ddd010dd1344b87#file-aaalibrary3b-no-w
 ... ( comment is too long, 49 lines, 6096 bytes, truncated) ... 
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   20 sec (00:00:20) |  419 sec (00:06:59) |  104 sec (00:01:44) |   23 sec (00:00:23) |   15 sec (00:00:15) |  172 sec (00:02:52) |   14 sec (00:00:14) |  767 sec (00:12:47) |

```

2022-03-15 20:27 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-183.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: f52ca1bf596da6bb4de42e7ba13e55909d6ca399
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |65 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |20 |20 |0 |17 sec  (00:00:17) |
|test (hthor) |984 |984 |0 |789 sec  (00:13:09) |
|test (thor) |894 |894 |0 |1007 sec  (00:16:47) |
|test (roxie) |1054 |1054 |0 |947 sec  (00:15:47) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   15 sec (00:00:15) |  415 sec (00:06:55) |  101 sec (00:01:41) |   20 sec (00:00:20) |   16 sec (00:00:16) | 1261 sec (00:21:01) |   19 sec (00:00:19) | 1847 sec (00:30:47) |

2022-03-15 21:27 UTC, HPCCSmoketest commented
Process of PR-15877, label: HPCC-24691 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 7a52480a3ac5b7430a4ecf68a12c9c1ea7ab3e9c
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-69.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-15 21:48 UTC, kenrowland commented
The following changes were made. The commit was rebased so that the entirety of the changes can be seen in context with the original code.

The audience and class values for the "legacy" logging categories were set to those used by MCdebugInfo which matches the DBGLOG calls employed by the ESPLOG function. 

The conversion of ESPLOG calls to use JLOG specific targeted log functions (ERRLOG, AUDLOG, etc.) were removed and replaced with LOG statements in line with what was done elsewhere in this PR.

Non sequential log ID values were not seen in captured ESP logs after the above changes. It was unclear if the log output above was created based on elevated logging in an ESP context. Knowing this would be useful.

The checks for context based elevated logging were not changed. Guards against a null context are required as the smoketest will fail if the guards are removed. The ESPLOG overload that accepted a context provided the guard in the existing code. An intermediate version of this code provided a function that returned the log category for the context and guarded against null.

Perhaps a meeting is in order to discuss the motivation for these changes, including the new category filter used for elevated logging. Let me know.

2022-03-15 21:58 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-69.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 7a52480a3ac5b7430a4ecf68a12c9c1ea7ab3e9c
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.7.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |65 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |0 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |22 sec  (00:00:22) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |20 |20 |0 |17 sec  (00:00:17) |
|test (hthor) |984 |984 |0 |823 sec  (00:13:43) |
|test (thor) |894 |894 |0 |1004 sec  (00:16:44) |
|test (roxie) |1054 |1054 |0 |893 sec  (00:14:53) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  414 sec (00:06:54) |  104 sec (00:01:44) |   20 sec (00:00:20) |   16 sec (00:00:16) | 1259 sec (00:20:59) |   19 sec (00:00:19) | 1848 sec (00:30:48) |

2022-03-23 17:59 UTC, closed without merging