Hpcc 27322 log access host instance fields
hpcc-systems/HPCC-Platform pull request #15872
Opened 2022-03-08 22:55 UTC by rpastrana

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-03-08 22:56 UTC, rpastrana commented
Dependent on several other PRs

2022-03-09 16:28 UTC, HPCCSmoketest commented
Process of PR-15872, label: HPCC-27322-LogAccess-HostInstanceFields starts now.
The reason of this test is: Forced to re-test.
Commit ID: 5b248590caa3e5d076a8e3b9b74cdc3fe8ece071
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-37.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-03-09 16:37 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-37.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 5b248590caa3e5d076a8e3b9b74cdc3fe8ece071
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.6.9-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  399 sec (00:06:39) |   99 sec (00:01:39) |   18 sec (00:00:18) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  532 sec (00:08:52) |

2022-03-14 13:13 UTC, HPCCSmoketest commented
Process of PR-15872, label: HPCC-27322-LogAccess-HostInstanceFields starts now.
The reason of this test is: Forced to re-test.
Commit ID: e5c22f4f1deeb649f94d5348f5d273b3b5c9f68c
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-223.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-03-14 13:16 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-223.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: e5c22f4f1deeb649f94d5348f5d273b3b5c9f68c
Containerized:True
Number of Error(s): 6
/home/centos/smoketest/PR-15872/HPCC-Platform/system/logaccess/ElasticStack/ElasticStackLogAccess.cpp:73:6: error: redefinition of \xe2\x80\x98void ElasticStackLogAccess::getMinReturnColumns(std::string&)\xe2\x80\x99
/home/centos/smoketest/PR-15872/HPCC-Platform/system/logaccess/ElasticStack/ElasticStackLogAccess.cpp:79:6: error: redefinition of \xe2\x80\x98void ElasticStackLogAccess::getDefaultReturnColumns(std::string&)\xe2\x80\x99
/home/centos/smoketest/PR-15872/HPCC-Platform/system/logaccess/ElasticStack/ElasticStackLogAccess.cpp:85:6: error: redefinition of \xe2\x80\x98void ElasticStackLogAccess::getAllColumns(std::string&)\xe2\x80\x99
make[2]: *** [system/logaccess/ElasticStack/CMakeFiles/elasticstacklogaccess.dir/build.make:76: system/logaccess/ElasticStack/CMakeFiles/elasticstacklogaccess.dir/ElasticStackLogAccess.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6699: system/logaccess/ElasticStack/CMakeFiles/elasticstacklogaccess.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
Get ECLWatch build result
ReportTimes.
Finish at: 2022-03-14_13-16-11
time logs started
Prep time   :    15 sec (00:00:15)
Build time  :   131 sec (00:02:11)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :   146 sec (00:02:26)
time logs end

[Build error:](https://gist.github.com/7363e332d22ffe8228b5b0e66e0e152d)
Build log [Build log](https://gist.github.com/HPCCSmoketest/7363e332d22ffe8228b5b0e66e0e152d#file-result-22-03-14-13-13-28-log)

2022-03-14 13:47 UTC, HPCCSmoketest commented
Process of PR-15872, label: HPCC-27322-LogAccess-HostInstanceFields starts now.
The reason of this test is: Forced to re-test.
Commit ID: 5e37343362e1aac904dd4f4a59650a6acfbdcc9d
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-232.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-03-14 13:56 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-232.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 5e37343362e1aac904dd4f4a59650a6acfbdcc9d
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.6.9-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   14 sec (00:00:14) |  393 sec (00:06:33) |   95 sec (00:01:35) |   18 sec (00:00:18) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  520 sec (00:08:40) |

2022-03-14 14:20 UTC, rpastrana commented
@jakesmith this is dependent on another PR (https://github.com/hpcc-systems/HPCC-Platform/pull/15837) with substantial number of changes, and therefore not worth reviewing this one yet...
but this PR exposes logaccess filters based on "instance" as you requested, and also by "host" which would be useful in baremetal. Please provide you thoughts.
BTW, I do plan on exposing a free-hand filter mechanism which would allow caller to filter by field name.

2022-04-01 02:08 UTC, HPCCSmoketest commented
Process of PR-15872, label: HPCC-27322-LogAccess-HostInstanceFields starts now.
The reason of this test is: Forced to re-test.
Commit ID: b360e8da30dbfefb90d45de07fc5fc08db618cfc
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-218.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-04-01 02:14 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-218.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: b360e8da30dbfefb90d45de07fc5fc08db618cfc
Containerized:True
Number of Error(s): 28
warn(226) A package without a profile could throw errors or warnings. package: dojo-util
warn(226) A package without a profile could throw errors or warnings. package: dojo-util
\terrors: 0
/home/centos/smoketest/PR-15872/HPCC-Platform/esp/services/ws_workunits/ws_workunitsHelpers.hpp:671:10: error: \xe2\x80\x98void ws_workunits::CWsWuFileHelper::createWULogFile(IConstWorkUnit*, ws_workunits::WsWuInfo&, const char*, unsigned int, LogAccessReturnColsMode, LogAccessLogFormat, unsigned int)\xe2\x80\x99 cannot be overloaded
/home/centos/smoketest/PR-15872/HPCC-Platform/esp/services/ws_workunits/ws_workunitsHelpers.hpp:669:10: error: with \xe2\x80\x98void ws_workunits::CWsWuFileHelper::createWULogFile(IConstWorkUnit*, ws_workunits::WsWuInfo&, const char*, unsigned int, LogAccessReturnColsMode, LogAccessLogFormat, unsigned int)\xe2\x80\x99
/home/centos/smoketest/PR-15872/HPCC-Platform/esp/services/ws_workunits/ws_workunitsHelpers.hpp:671:10: error: \xe2\x80\x98void ws_workunits::CWsWuFileHelper::createWULogFile(IConstWorkUnit*, ws_workunits::WsWuInfo&, const char*, unsigned int, LogAccessReturnColsMode, LogAccessLogFormat, unsigned int)\xe2\x80\x99 cannot be overloaded
/home/centos/smoketest/PR-15872/HPCC-Platform/esp/services/ws_workunits/ws_workunitsHelpers.hpp:669:10: error: with \xe2\x80\x98void ws_workunits::CWsWuFileHelper::createWULogFile(IConstWorkUnit*, ws_workunits::WsWuInfo&, const char*, unsigned int, LogAccessReturnColsMode, LogAccessLogFormat, unsigned int)\xe2\x80\x99
/home/centos/smoketest/PR-15872/HPCC-Platform/esp/services/ws_workunits/ws_workunitsHelpers.hpp:671:10: error: \xe2\x80\x98void ws_workunits::CWsWuFileHelper::createWULogFile(IConstWorkUnit*, ws_workunits::WsWuInfo&, const char*, unsigned int, LogAccessReturnColsMode, LogAccessLogFormat, unsigned int)\xe2\x80\x99 cannot be overloaded
/home/centos/smoketest/PR-15872/HPCC-Platform/esp/services/ws_workunits/ws_workunitsHelpers.hpp:669:10: error: with \xe2\x80\x98void ws_workunits::CWsWuFileHelper::createWULogFile(IConstWorkUnit*, ws_workunits::WsWuInfo&, const char*, unsigned int, LogAccessReturnColsMode, LogAccessLogFormat, unsigned int)\xe2\x80\x99
/home/centos/smoketest/PR-15872/HPCC-Platform/esp/services/ws_workunits/ws_workunitsHelpers.cpp:209:6: error: prototype for \xe2\x80\x98void ws_workunits::WsWuInfo::readWorkunitComponentLogs(MemoryBuffer&, const char*, unsigned int, LogAccessReturnColsMode, LogAccessLogFormat, unsigned int)\xe2\x80\x99 does not match any in class \xe2\x80\x98ws_workunits::WsWuInfo\xe2\x80\x99
/home/centos/smoketest/PR-15872/HPCC-Platform/esp/services/ws_workunits/ws_workunitsHelpers.hpp:176:10: error: candidate is: void ws_workunits::WsWuInfo::readWorkunitComponentLogs(const char*, unsigned int, LogAccessReturnColsMode, LogAccessLogFormat, unsigned int)
/home/centos/smoketest/PR-15872/HPCC-Platform/esp/services/ws_workunits/ws_workunitsHelpers.hpp:671:10: error: \xe2\x80\x98void ws_workunits::CWsWuFileHelper::createWULogFile(IConstWorkUnit*, ws_workunits::WsWuInfo&, const char*, unsigned int, LogAccessReturnColsMode, LogAccessLogFormat, unsigned int)\xe2\x80\x99 cannot be overloaded
/home/centos/smoketest/PR-15872/HPCC-Platform/esp/services/ws_workunits/ws_workunitsHelpers.hpp:669:10: error: with \xe2\x80\x98void ws_workunits::CWsWuFileHelper::createWULogFile(IConstWorkUnit*, ws_workunits::WsWuInfo&, const char*, unsigned int, LogAccessReturnColsMode, LogAccessLogFormat, unsigned int)\xe2\x80\x99
make[
 ... ( comment is too long, 53 lines, 7853 bytes, truncated) ... 
[Build error:](https://gist.github.com/36916f5749abf8ef5622a9848407a1e4)
Build log [Build log](https://gist.github.com/HPCCSmoketest/36916f5749abf8ef5622a9848407a1e4#file-result-22-04-01-02-08-22-log)

```

2022-04-01 02:51 UTC, HPCCSmoketest commented
Process of PR-15872, label: HPCC-27322-LogAccess-HostInstanceFields starts now.
The reason of this test is: Forced to re-test.
Commit ID: 423e5f83b3c2c1a168093f8a651c1e43d6de894f
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-70.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-04-01 02:57 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-70.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 423e5f83b3c2c1a168093f8a651c1e43d6de894f
Containerized:True
Number of Error(s): 8
warn(226) A package without a profile could throw errors or warnings. package: dojo-util
warn(226) A package without a profile could throw errors or warnings. package: dojo-util
\terrors: 0
/home/centos/smoketest/PR-15872/HPCC-Platform/esp/services/ws_workunits/ws_workunitsHelpers.cpp:209:6: error: prototype for \xe2\x80\x98void ws_workunits::WsWuInfo::readWorkunitComponentLogs(MemoryBuffer&, const char*, unsigned int, LogAccessReturnColsMode, LogAccessLogFormat, unsigned int)\xe2\x80\x99 does not match any in class \xe2\x80\x98ws_workunits::WsWuInfo\xe2\x80\x99
/home/centos/smoketest/PR-15872/HPCC-Platform/esp/services/ws_workunits/ws_workunitsHelpers.hpp:176:10: error: candidate is: void ws_workunits::WsWuInfo::readWorkunitComponentLogs(const char*, unsigned int, LogAccessReturnColsMode, LogAccessLogFormat, unsigned int)
make[2]: *** [esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/build.make:230: esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/ws_workunitsHelpers.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:12103: esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
Get ECLWatch build result
ReportTimes.
Finish at: 2022-04-01_02-57-08
time logs started
Prep time   :    16 sec (00:00:16)
Build time  :   313 sec (00:05:13)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :   329 sec (00:05:29)
time logs end

[Build error:](https://gist.github.com/85243bb1915c31aae7218aee99758768)
Build log [Build log](https://gist.github.com/HPCCSmoketest/85243bb1915c31aae7218aee99758768#file-result-22-04-01-02-51-23-log)

2022-04-01 03:35 UTC, HPCCSmoketest commented
Process of PR-15872, label: HPCC-27322-LogAccess-HostInstanceFields starts now.
The reason of this test is: Forced to re-test.
Commit ID: 3b7986ff85d90582898562ac70928088bf3e8063
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-12.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-04-01 03:44 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-12.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 3b7986ff85d90582898562ac70928088bf3e8063
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.6.17-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   24 sec (00:00:24) |  399 sec (00:06:39) |   97 sec (00:01:37) |   18 sec (00:00:18) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  538 sec (00:08:58) |

2022-04-01 16:28 UTC, jakesmith requested changes
@rpastrana - looks ok, apart from left in tracing.

2022-04-01 16:56 UTC, rpastrana commented on system/logaccess/ElasticStack/ElasticStackLogAccess.cpp
> +                DBGLOG("m_instanceSearchColName new value: '%s'", m_instanceSearchColName.str());
Yep, these snuck in. Removing all trace messages.

2022-04-01 17:04 UTC, HPCCSmoketest commented
Process of PR-15872, label: HPCC-27322-LogAccess-HostInstanceFields starts now.
The reason of this test is: Forced to re-test.
Commit ID: d8278d2af818734bf2042b0f69d36cd6a67666a6
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-159.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-04-01 17:13 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-159.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: d8278d2af818734bf2042b0f69d36cd6a67666a6
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.6.17-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  397 sec (00:06:37) |   95 sec (00:01:35) |   18 sec (00:00:18) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  526 sec (00:08:46) |

2022-04-01 17:20 UTC, HPCCSmoketest commented
Process of PR-15872, label: HPCC-27322-LogAccess-HostInstanceFields starts now.
The reason of this test is: New commit.
Commit ID: 37c4137b1064196c0c762137723263a68663b8f2
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-25.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-04-01 17:29 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-25.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 37c4137b1064196c0c762137723263a68663b8f2
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.6.17-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   15 sec (00:00:15) |  400 sec (00:06:40) |   95 sec (00:01:35) |   17 sec (00:00:17) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  527 sec (00:08:47) |

2022-04-01 18:44 UTC, jakesmith approved these changes
@rpastrana - looks good

2022-04-01 18:50 UTC, rpastrana commented
@richardkchapman please merge

2022-04-04 10:26 UTC, merged