HPCC-26680 ESDL tool not honoring exceptions_inline
hpcc-systems/HPCC-Platform pull request #15880
Opened 2022-03-09 22:26 UTC by asselitx

The esdl command-line tool and ESDL engine-based services do not honor the
exceptions_inline attribute when creating XSD or WSDL output.

Update the esdl transform to honor the exceptions_inline attribute in the
same way that hidl-based services do- when it appears in the EspResponse
element of an ecm file.

This change fixes both the esdl command-line and ESDL engine-based services.

Also correct the esdl tool generated wsdl where it differed from the hidl-generated
wsdl in these ways:

1. Make it validate by defining the wsdl namespace prefix it uses
2. Output a properly formatted version number without trailing zeros in the SoapAction section

Signed-off-by: Terrence Asselin <terrence.asselin@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-03-09 22:31 UTC, HPCCSmoketest commented
Process of PR-15880, label: exceptions_inline-wsdl-hpcc-26680 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 611a9b5a4547f1ac92cd20fa1348e7275ab1f82c
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-142.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-09 23:02 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-142.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 611a9b5a4547f1ac92cd20fa1348e7275ab1f82c
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.9-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |67 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |39 sec  (00:00:39) |
|setup (roxie) |20 |20 |0 |18 sec  (00:00:18) |
|test (hthor) |984 |984 |0 |790 sec  (00:13:10) |
|test (thor) |894 |894 |0 |1009 sec  (00:16:49) |
|test (roxie) |1054 |1054 |0 |904 sec  (00:15:04) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  413 sec (00:06:53) |  101 sec (00:01:41) |   20 sec (00:00:20) |   16 sec (00:00:16) | 1267 sec (00:21:07) |   18 sec (00:00:18) | 1852 sec (00:30:52) |

2022-03-10 14:28 UTC, rpastrana commented
@asselitx can you provide a sample wsdl generated w/ your recent changes, thanks.

2022-03-14 21:03 UTC, HPCCSmoketest commented
Process of PR-15880, label: exceptions_inline-wsdl-hpcc-26680 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 5ec3680fb299b0bdba37828c12874b68527c43a8
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-198.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-14 21:35 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-198.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 5ec3680fb299b0bdba37828c12874b68527c43a8
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.9-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |68 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |22 sec  (00:00:22) |
|setup (thor) |9 |9 |0 |39 sec  (00:00:39) |
|setup (roxie) |20 |20 |0 |18 sec  (00:00:18) |
|test (hthor) |984 |984 |0 |838 sec  (00:13:58) |
|test (thor) |894 |894 |0 |1018 sec  (00:16:58) |
|test (roxie) |1054 |1054 |0 |907 sec  (00:15:07) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   24 sec (00:00:24) |  439 sec (00:07:19) |  109 sec (00:01:49) |   21 sec (00:00:21) |   16 sec (00:00:16) | 1279 sec (00:21:19) |   19 sec (00:00:19) | 1907 sec (00:31:47) |

2022-03-14 23:03 UTC, rpastrana commented on esp/xslt/esxdl2xsd.xslt
> +                            <xsl:value-of select="$serviceName"/>/<xsl:value-of select="@name"/>?ver_=<xsl:value-of select="number($version)"/>
this seems like a worthwhile change, but it's outside the scope of this change

2022-03-14 23:07 UTC, rpastrana requested changes
@asselitx change looks good. 
However the version number change should be in it's own dedicated PR, mostly because we're not clear on the impact of losing the floating point.
Also, the test files seem ok, but only skimmed over them.

2022-03-15 15:52 UTC, HPCCSmoketest commented
Process of PR-15880, label: exceptions_inline-wsdl-hpcc-26680 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 4fa8cb3113ff97c26918e1f5a4a301502e20e887
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-171.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-15 16:23 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-171.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 4fa8cb3113ff97c26918e1f5a4a301502e20e887
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.9-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |66 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |20 |20 |0 |18 sec  (00:00:18) |
|test (hthor) |984 |984 |0 |827 sec  (00:13:47) |
|test (thor) |894 |894 |0 |995 sec  (00:16:35) |
|test (roxie) |1054 |1054 |0 |934 sec  (00:15:34) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   24 sec (00:00:24) |  412 sec (00:06:52) |  103 sec (00:01:43) |   20 sec (00:00:20) |   16 sec (00:00:16) | 1251 sec (00:20:51) |   19 sec (00:00:19) | 1845 sec (00:30:45) |

2022-03-16 17:21 UTC, asselitx commented
@timothyklemm  in Rodrigo's absence could you please review?

2022-03-16 17:25 UTC, HPCCSmoketest commented
Process of PR-15880, label: exceptions_inline-wsdl-hpcc-26680 starts now.
The reason of this test is: Forced to re-test.
Commit ID: c3169c2fc3b130176f28ad1ebdc4838558ffcb9b
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-142.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-16 17:56 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-142.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: c3169c2fc3b130176f28ad1ebdc4838558ffcb9b
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.9-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |65 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |20 |20 |0 |17 sec  (00:00:17) |
|test (hthor) |984 |984 |0 |794 sec  (00:13:14) |
|test (thor) |894 |894 |0 |1011 sec  (00:16:51) |
|test (roxie) |1054 |1054 |0 |891 sec  (00:14:51) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  413 sec (00:06:53) |  100 sec (00:01:40) |   19 sec (00:00:19) |   16 sec (00:00:16) | 1265 sec (00:21:05) |   19 sec (00:00:19) | 1849 sec (00:30:49) |

2022-03-21 16:47 UTC, rpastrana approved these changes
@asselitx looks reasonable.

2022-03-24 11:11 UTC, richardkchapman commented
@asselitx I think the checks failed to run because github was having issues - if you force-push an amended commit (without any changes) then it should retrigger them

2022-03-24 14:40 UTC, asselitx commented
Note just pushed the last commit to re-trigger the workflow checks to run. It didn't contain any changes, just a rebase and force push.

2022-03-24 14:43 UTC, HPCCSmoketest commented
Process of PR-15880, label: exceptions_inline-wsdl-hpcc-26680 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 99b40579ee68263430842782b7758f0a3a108b08
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-40.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-28 11:21 UTC, merged