HPCC-26614 Document Helm Job Memory Sections
hpcc-systems/HPCC-Platform pull request #15899
Opened 2022-03-14 20:04 UTC by g-pan

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:
Complete integration tested successfully
 http://10.240.61.86/view/Docs-gp/job/DocBuild-01/

2022-03-14 20:11 UTC, HPCCSmoketest commented
Process of PR-15899, label: H26614-hMem starts now.
The reason of this test is: Forced to re-test.
Commit ID: b62843991e7f291c500a9ed4f1dc037c3de1409c
Estimated completion time is 0.19 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-165.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-14 20:28 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-165.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: b62843991e7f291c500a9ed4f1dc037c3de1409c
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.11-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  701 sec (00:11:41) |  215 sec (00:03:35) |   20 sec (00:00:20) |   16 sec (00:00:16) |    0 sec (00:00:00) |   14 sec (00:00:14) |  983 sec (00:16:23) |

2022-03-16 19:20 UTC, JamesDeFabia requested changes
Just a few typos from my POV

2022-03-16 19:20 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +        <para>The "memory" sections were introduced initially for Thor only,
Is this information necessary to share? I don't think anyone needs to know it was Thor only at first.

2022-03-16 19:20 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +        resources section, e.g. if "thirdParty" was set to "2G" in the above
e.g.,

2022-03-16 19:20 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +        memory (e.g. "thirdParty"). </para>
e.g.,

2022-03-16 19:20 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +        defined their Kubernetes resource needs, and now they have a
define, not defined

2022-03-17 22:18 UTC, HPCCSmoketest commented
Process of PR-15899, label: H26614-hMem starts now.
The reason of this test is: Forced to re-test.
Commit ID: 3dc1b057c0cef4e85f0763c89ad39f7295bd6511
Estimated completion time is 0.19 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-28.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-17 22:33 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-28.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 3dc1b057c0cef4e85f0763c89ad39f7295bd6511
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.11-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  613 sec (00:10:13) |  195 sec (00:03:15) |   19 sec (00:00:19) |   18 sec (00:00:18) |    0 sec (00:00:00) |   14 sec (00:00:14) |  876 sec (00:14:36) |

2022-03-18 14:38 UTC, JamesDeFabia approved these changes
Looks ok from my POV, but Jake should be the final reviewer.

2022-03-21 16:48 UTC, jakesmith reviewed
A couple of minor change suggestions.

2022-03-23 12:30 UTC, jakesmith approved these changes
@g-pan - looks good, please squash

2022-03-24 12:30 UTC, HPCCSmoketest commented
Process of PR-15899, label: H26614-hMem starts now.
The reason of this test is: Forced to re-test.
Commit ID: c68b0d2246969d518ab46788dc78861caf82774b
Estimated completion time is 0.19 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-21.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-24 12:45 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-21.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: c68b0d2246969d518ab46788dc78861caf82774b
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.11-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  612 sec (00:10:12) |  194 sec (00:03:14) |   19 sec (00:00:19) |   16 sec (00:00:16) |    0 sec (00:00:00) |   14 sec (00:00:14) |  871 sec (00:14:31) |

2022-03-24 15:44 UTC, JamesDeFabia approved these changes

2022-03-24 15:45 UTC, merged