HPCC-27170 Fix remote index filter/limit issues
hpcc-systems/HPCC-Platform pull request #15938
Opened 2022-03-24 15:16 UTC by jakesmith

Fix a number of issues related to reading indexes remotely
(via dafilesrv streaming), where filtering or limits are present.

The indexread/count/normalize activities optionally pass a threshold
limit to the remote side, to suppress excessive unecessary rows
being serialized back.
This is total remoteLimit disabled if there are is any post filtering,
because it is not known how many remote rows will eventually be
needed.
Three issues fixed:
1) IndexCount was using helper->hasMatchFilter() but hasFilter()
was set instead. This was causing it to send a remoteLimit, and
therefore not receive rows back which would have matched the post-
filter.
2) IndexNormalize was also basing remoteLimit on hasMatchFilter().
However, it neither sets hasFilter or hasMatchFilter. Change to
assume no remoteLimit in indexnormalize case.
3) getRowLimit was being used as a remoteLimit boundary, meaning
it would falsely hit the limit, when post filters would reduce
it below that limit.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-03-24 15:54 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-173.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 2538754ad30b949f43b5bb88ea25f8b30dd545bf
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.13-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |67 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |22 sec  (00:00:22) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |20 |20 |0 |18 sec  (00:00:18) |
|test (hthor) |986 |986 |0 |812 sec  (00:13:32) |
|test (thor) |896 |896 |0 |1042 sec  (00:17:22) |
|test (roxie) |1056 |1054 |2 |936 sec  (00:15:36) |


[Errors:](https://gist.github.com/86a4779e167b3549c92963f2b0b52146)
- test
  - roxie
    - 370\. [indexlimit3 (optRemoteRead=false)](https://gist.github.com/HPCCSmoketest/86a4779e167b3549c92963f2b0b52146#file-indexlimit3-optremoteread-false-w20220324-154136-5-log), 371\. [indexlimit3 (optRemoteRead=true)](https://gist.github.com/HPCCSmoketest/86a4779e167b3549c92963f2b0b52146#file-indexlimit3-optremoteread-true-w20220324-154137-4-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  422 sec (00:07:02) |  115 sec (00:01:55) |   19 sec (00:00:19) |   18 sec (00:00:18) | 1300 sec (00:21:40) |   19 sec (00:00:19) | 1910 sec (00:31:50) |

2022-03-24 20:15 UTC, HPCCSmoketest commented
Process of PR-15938, label: HPCC-27170-remote-index-filter-limit-issues starts now.
The reason of this test is: Forced to re-test.
Commit ID: e625d002fc3da58a8c647c9a9b1848e4c40303c0
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-104.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-24 20:29 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-104.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: e625d002fc3da58a8c647c9a9b1848e4c40303c0
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.15-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |65 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |22 sec  (00:00:22) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |20 |19 |1 |17 sec  (00:00:17) |
|test (hthor) |0 |0 |0 |N/A |
|test (thor) |0 |0 |0 |N/A |
|test (roxie) |0 |0 |0 |N/A |


[Errors:](https://gist.github.com/be4bbab6ce3dba839f4bf04e14c2875c)
- setup
  - roxie
    - 15\. [setuppersist](https://gist.github.com/HPCCSmoketest/be4bbab6ce3dba839f4bf04e14c2875c#file-setuppersist-w20220324-202853-4-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  415 sec (00:06:55) |  102 sec (00:01:42) |   19 sec (00:00:19) |   16 sec (00:00:16) |  240 sec (00:04:00) |   15 sec (00:00:15) |  823 sec (00:13:43) |

2022-03-25 09:22 UTC, jakesmith commented
> <Warning><Code>4523</Code><Filename>indexlimit3.ecl</Filename><Line>55</Line><Source>eclcc</Source><Message>Neither LIMIT() nor CHOOSEN() supplied for index read on  ~keyx</Message></Warning>

@ghalliday - for some reason I can't reproduce this locally (in Release or Debug).
and also not sure why it's saying that the index read need a LIMIT or CHOOSEN ?

2022-03-25 09:23 UTC, jakesmith commented
Also wondering if this should target 7.12.x

2022-03-25 09:35 UTC, ghalliday commented
@richardkchapman note the persist failure due to the new roxie message....
@jakesmith since this changes the behaviour of existing queries it should really target master.  @richardkchapman thoughts?

2022-03-25 09:40 UTC, jakesmith commented
>@richardkchapman note the persist failure due to the new roxie message....

I'm blind, assume it was the thor run of the query that was failing.
Ok, well, I can suppress the warning I guess in the test.

> @jakesmith since this changes the behaviour of existing queries it should really target master. @richardkchapman thoughts?

True, it does change the behaviour. It's a very subtle bug though, which to the users is non-deterministic.
It depends whether their copy of the index is local or remote (+ whether the limit effects the overall results or not)

2022-03-25 17:38 UTC, jakesmith commented
@ghalliday - please review carefully.

2022-03-25 17:42 UTC, HPCCSmoketest commented
Process of PR-15938, label: HPCC-27170-remote-index-filter-limit-issues starts now.
The reason of this test is: New commit.
Commit ID: 6f14f9d93561018519da0a12de2d063d2fbe6d91
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-132.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-25 18:13 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-132.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 6f14f9d93561018519da0a12de2d063d2fbe6d91
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_7.12.101-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |146 |146 |0 |0 |0 |47 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |0 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |20 sec  (00:00:20) |
|setup (thor) |9 |9 |0 |39 sec  (00:00:39) |
|setup (roxie) |19 |19 |0 |19 sec  (00:00:19) |
|test (hthor) |956 |956 |0 |700 sec  (00:11:40) |
|test (thor) |867 |867 |0 |993 sec  (00:16:33) |
|test (roxie) |1029 |1027 |2 |812 sec  (00:13:32) |


[Errors:](https://gist.github.com/47a34c7b66056e95f796d611c8a01c43)
- test
  - roxie
    - 365\. [indexlimit3 (optRemoteRead=false)](https://gist.github.com/HPCCSmoketest/47a34c7b66056e95f796d611c8a01c43#file-indexlimit3-optremoteread-false-w20220325-180049-log), 366\. [indexlimit3 (optRemoteRead=true)](https://gist.github.com/HPCCSmoketest/47a34c7b66056e95f796d611c8a01c43#file-indexlimit3-optremoteread-true-w20220325-180049-4-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   25 sec (00:00:25) |  431 sec (00:07:11) |  107 sec (00:01:47) |   21 sec (00:00:21) |   16 sec (00:00:16) | 1232 sec (00:20:32) |   18 sec (00:00:18) | 1850 sec (00:30:50) |

2022-03-25 18:29 UTC, jakesmith commented
New test in roxie is hitting:
<Exception><Source>Roxie</Source><Message>LimitSkipException (in Index Normalize 27)</Message></Exception>

(it didn't in 8.6.x)

Not sure why at the moment.
@richardkchapman - any initial thoughts?

2022-03-28 09:51 UTC, ghalliday approved these changes
@richardkchapman I think this is good/safe.  Even if there was a problem it would only have the effect of removing an optimization.

2022-03-28 11:19 UTC, richardkchapman commented
@jakesmith Probably because of 

    HPCC-21884 Index Normalize ignoring LIMIT SKIP and generating exception

(fixed in 8.0)

2022-03-28 11:23 UTC, jakesmith commented
> @jakesmith Probably because of
> 
> ```
> HPCC-21884 Index Normalize ignoring LIMIT SKIP and generating exception
> ```
> 
> (fixed in 8.0)

@richardkchapman - ok, could remove this particular test in 7.12 - to avoid keep seeing it on future 7.12 point builds, and then issue new PR to add it back in 8.0.x ?

2022-03-28 11:41 UTC, richardkchapman commented
@jakesmith That sounds sensible

2022-03-28 13:49 UTC, HPCCSmoketest commented
Process of PR-15938, label: HPCC-27170-remote-index-filter-limit-issues starts now.
The reason of this test is: Forced to re-test.
Commit ID: cb0590e2045ffb5498d8d35e8cee85f613d23e4c
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-77.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-28 14:16 UTC, richardkchapman approved these changes

2022-03-28 14:19 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-77.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: cb0590e2045ffb5498d8d35e8cee85f613d23e4c
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_7.12.101-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |146 |146 |0 |0 |0 |46 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |39 sec  (00:00:39) |
|setup (roxie) |19 |19 |0 |19 sec  (00:00:19) |
|test (hthor) |956 |956 |0 |670 sec  (00:11:10) |
|test (thor) |867 |867 |0 |960 sec  (00:16:00) |
|test (roxie) |1029 |1027 |2 |781 sec  (00:13:01) |


[Errors:](https://gist.github.com/918e05e78ace4c119c72c10c13d2a774)
- test
  - roxie
    - 365\. [indexlimit3 (optRemoteRead=false)](https://gist.github.com/HPCCSmoketest/918e05e78ace4c119c72c10c13d2a774#file-indexlimit3-optremoteread-false-w20220328-140707-3-log), 366\. [indexlimit3 (optRemoteRead=true)](https://gist.github.com/HPCCSmoketest/918e05e78ace4c119c72c10c13d2a774#file-indexlimit3-optremoteread-true-w20220328-140708-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   24 sec (00:00:24) |  423 sec (00:07:03) |   93 sec (00:01:33) |   18 sec (00:00:18) |   16 sec (00:00:16) | 1198 sec (00:19:58) |   17 sec (00:00:17) | 1789 sec (00:29:49) |

2022-03-28 14:39 UTC, richardkchapman requested changes

2022-03-28 14:39 UTC, richardkchapman commented on testing/regress/ecl/indexlimit3.ecl
> +// OUTPUT(LIMIT(fi.kkeys(ckey>=992), 3, ONFAIL(TRANSFORM(RECORDOF(crec), SELF.info := '**ROW LIMIT HIT IN INDEXNORMALIZE**'; SELF := []))));
This one should not be commented out

2022-03-28 14:39 UTC, richardkchapman commented on testing/regress/ecl/indexlimit3.ecl
> + OUTPUT(LIMIT(fi.kkeys(ckey>=992), 2, ONFAIL(TRANSFORM(RECORDOF(crec), SELF.info := '**ROW LIMIT HIT IN INDEXNORMALIZE**'; SELF := []))));
This is the one that will fail on roxie

2022-03-28 14:50 UTC, richardkchapman approved these changes

2022-03-28 14:53 UTC, HPCCSmoketest commented
Process of PR-15938, label: HPCC-27170-remote-index-filter-limit-issues starts now.
The reason of this test is: Forced to re-test.
Commit ID: fe6dd685a49c5950c0d3ab2be86857f8e34ccf7a
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-50.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-28 15:24 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-50.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: fe6dd685a49c5950c0d3ab2be86857f8e34ccf7a
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_7.12.101-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |146 |146 |0 |0 |0 |47 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |19 sec  (00:00:19) |
|setup (thor) |9 |9 |0 |39 sec  (00:00:39) |
|setup (roxie) |19 |19 |0 |19 sec  (00:00:19) |
|test (hthor) |956 |955 |1 |694 sec  (00:11:34) |
|test (thor) |867 |867 |0 |994 sec  (00:16:34) |
|test (roxie) |1029 |1029 |0 |814 sec  (00:13:34) |


[Errors:](https://gist.github.com/51fcc160a6b2190c4fe970ae04d9d8aa)
- test
  - hthor
    - 351\. [indexlimit3 (optRemoteRead=false)](https://gist.github.com/HPCCSmoketest/51fcc160a6b2190c4fe970ae04d9d8aa#file-indexlimit3-optremoteread-false-w20220328-151118-1-log), 

HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   22 sec (00:00:22) |  433 sec (00:07:13) |  103 sec (00:01:43) |   17 sec (00:00:17) |   19 sec (00:00:19) | 1233 sec (00:20:33) |   18 sec (00:00:18) | 1845 sec (00:30:45) |

2022-03-28 15:49 UTC, jakesmith commented
@richardkchapman - github test passed now (apart from usual helm chart failure)

2022-03-29 10:09 UTC, HPCCSmoketest commented
Process of PR-15938, label: HPCC-27170-remote-index-filter-limit-issues starts now.
The reason of this test is: Forced to re-test.
Commit ID: f94c1014d18a418e683abee87363c281d9157e50
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-56.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-03-29 10:39 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-56.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: f94c1014d18a418e683abee87363c281d9157e50
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_7.12.101-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |146 |146 |0 |0 |0 |47 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |0 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |23 sec  (00:00:23) |
|setup (thor) |9 |9 |0 |39 sec  (00:00:39) |
|setup (roxie) |19 |19 |0 |19 sec  (00:00:19) |
|test (hthor) |956 |956 |0 |671 sec  (00:11:11) |
|test (thor) |867 |867 |0 |959 sec  (00:15:59) |
|test (roxie) |1029 |1029 |0 |779 sec  (00:12:59) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   24 sec (00:00:24) |  421 sec (00:07:01) |   92 sec (00:01:32) |   17 sec (00:00:17) |   16 sec (00:00:16) | 1200 sec (00:20:00) |   17 sec (00:00:17) | 1787 sec (00:29:47) |

2022-03-29 11:41 UTC, merged