HPCC-27424 Document 64-bit Client Tools should be used for large WUs
hpcc-systems/HPCC-Platform pull request #16009
Opened 2022-04-18 19:56 UTC by JamesDeFabia

Signed-off-by: Jim DeFabia <jamesdefabia@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-04-18 20:01 UTC, HPCCSmoketest commented
Process of PR-16009, label: HPCC-27424 starts now.
The reason of this test is: Forced to re-test.
Commit ID: d91c9d464c566584b13fc22ebbf7866137f55fe2
Estimated completion time is 0.19 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-148.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-04-18 20:16 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-148.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: d91c9d464c566584b13fc22ebbf7866137f55fe2
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.21-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  621 sec (00:10:21) |  196 sec (00:03:16) |   19 sec (00:00:19) |   16 sec (00:00:16) |    0 sec (00:00:00) |   13 sec (00:00:13) |  882 sec (00:14:42) |

2022-04-19 05:48 UTC, GordonSmith approved these changes
@JamesDeFabia looks ok - It might be worth highlighting that in general the user should always install the 64bit version of client tools (unless they have a 32bit windows, which is not likely)

2022-04-20 10:14 UTC, richardkchapman commented
I think there are cases where the 64-bit compiler uses more memory, on weedy machines this can be a problem? @ghalliday can you comment?

2022-04-20 10:54 UTC, ghalliday commented
Yes.  If your machine only has 4Gb of memory you are probably better off using the 32bit version of the client tools (I would estimate eclcc consumes up to 10% less memory).  If you have more than 4GB you are probably better off with the 64bit tools.
I don't know how the speed compares running on a 64bit OS.

2022-04-20 17:44 UTC, JamesDeFabia commented
I updated based on Richard and Gavin's feedback. @GordonSmith please review again

2022-04-20 18:04 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-54.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 28e28c828a711ffc250b28589c0a4e9f1f36d4f4
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.21-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   24 sec (00:00:24) |  636 sec (00:10:36) |  201 sec (00:03:21) |   19 sec (00:00:19) |   16 sec (00:00:16) |    0 sec (00:00:00) |   14 sec (00:00:14) |  910 sec (00:15:10) |

2022-04-21 14:06 UTC, GordonSmith requested changes
Minor:  more truthful explanation of what `apt-get install -f` does

2022-04-21 14:06 UTC, GordonSmith commented on docs/EN_US/HPCCClientTools/CT_Mods/CT_Overview.xml
> +      dependencies:</para>
`run the following to "fix" any missing dependencies`

2022-04-22 12:44 UTC, HPCCSmoketest commented
Process of PR-16009, label: HPCC-27424 starts now.
The reason of this test is: Forced to re-test.
Commit ID: cf6e8dd8a840fc67782888c09cd14eba8389fad7
Estimated completion time is 0.19 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-224.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-04-22 12:46 UTC, GordonSmith requested changes
As per comments

2022-04-22 12:59 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-224.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: cf6e8dd8a840fc67782888c09cd14eba8389fad7
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.21-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  610 sec (00:10:10) |  192 sec (00:03:12) |   19 sec (00:00:19) |   16 sec (00:00:16) |    0 sec (00:00:00) |   13 sec (00:00:13) |  867 sec (00:14:27) |

2022-04-22 14:24 UTC, GordonSmith approved these changes

2022-04-22 14:28 UTC, HPCCSmoketest commented
Process of PR-16009, label: HPCC-27424 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 9b48d6c390b46e7981882ec0e75ec662721c303c
Estimated completion time is 0.19 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-201.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-04-22 14:45 UTC, JamesDeFabia commented
Squashed. 
@richardkchapman This should be good to merge now

2022-04-22 14:50 UTC, HPCCSmoketest commented
Process of PR-16009, label: HPCC-27424 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 7bebce87cdf6b68c31e6cb36fdf87ee16e2e4233
Estimated completion time is 0.19 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-119.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-04-22 15:06 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-119.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 7bebce87cdf6b68c31e6cb36fdf87ee16e2e4233
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.21-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  663 sec (00:11:03) |  207 sec (00:03:27) |   24 sec (00:00:24) |   16 sec (00:00:16) |    0 sec (00:00:00) |   13 sec (00:00:13) |  940 sec (00:15:40) |

2022-04-25 15:15 UTC, merged