HPCC-27532 Send HTTP response on all exceptions
hpcc-systems/HPCC-Platform pull request #16018
Opened 2022-04-19 17:30 UTC by timothyklemm

Signed-off-by: Tim Klemm <tim.klemm@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-04-19 17:35 UTC, HPCCSmoketest commented
Process of PR-16018, label: hpcc-27532_exception_handling starts now.
The reason of this test is: Forced to re-test.
Commit ID: 67dd20cb924c79cd4c67c3e47b9536f3cd62daae
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-184.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-04-19 18:06 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-184.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 67dd20cb924c79cd4c67c3e47b9536f3cd62daae
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.21-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |64 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |21 sec  (00:00:21) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |20 |20 |0 |18 sec  (00:00:18) |
|test (hthor) |986 |986 |0 |828 sec  (00:13:48) |
|test (thor) |896 |896 |0 |992 sec  (00:16:32) |
|test (roxie) |1056 |1056 |0 |872 sec  (00:14:32) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   18 sec (00:00:18) |  417 sec (00:06:57) |  106 sec (00:01:46) |   21 sec (00:00:21) |   16 sec (00:00:16) | 1247 sec (00:20:47) |   19 sec (00:00:19) | 1844 sec (00:30:44) |

2022-04-20 20:08 UTC, rpastrana requested changes
@timothyklemm left a few comments.
More importantly, I assume this wouldn't be considered a SOAPFault because it occurs higher up in the stack, but if there's a standard response format for http level faults, let's make sure we're following it.

2022-04-21 11:31 UTC, timothyklemm commented on esp/bindings/http/platform/httpservice.cpp
> +    if (e)
e is already released in the catch blocks, where it may be still be used after calling this method.

2022-04-21 11:43 UTC, timothyklemm commented on esp/bindings/http/platform/httpservice.cpp
> +        content.append(". Check log files for more information");
The rationale offered for why arbitrary exception messages were not being returned to callers is that the messages are likely to contain internal information we do not want exposed to end users. The presence of e is used here to indicate whether the trace logs are likely to contain such internal information.

The exception is currently logged with DBGLOG. Should trace output be controlled such that these message are excluded, we might want to consider logging with IERRLOG instead.

2022-04-21 12:00 UTC, timothyklemm commented on esp/bindings/http/platform/httpservice.cpp
> +    m_response->send();
There is nothing named setCode, but to which code are you referring? There might be something under a different name.

The intent of this response is to mimic the handling of IEspHttpExceptions, with the obvious difference being message content. In terms of this comment and the overall review comment, would sending a response differently be in the scope of this PR or might standardizing error responses be a separate issue?

2022-04-21 12:34 UTC, rpastrana commented on esp/bindings/http/platform/httpservice.cpp
> +        content.append(". Check log files for more information");
Ok, fair enough, but that rationale isn't intuitive nor clearly documented here...
I would suggest adding a comment to that affect either at the method level, or around line 1645

2022-04-21 12:57 UTC, rpastrana commented on esp/bindings/http/platform/httpservice.cpp
> +    m_response->send();
If the response object doesn't provide a setcode, I was going to suggest you pass the exception errcode (and audience and message).

The response is likely to simply read "Request failed", that's likely ok, but if there's a standard exception response format (I don't know if there is, you'd have to research it) your response in this change should adhere to it.

2022-04-27 13:03 UTC, timothyklemm commented on esp/bindings/http/platform/httpservice.cpp
> +        content.append(". Check log files for more information");
A method comment is added, and the exception is replaced as a method parameter by a flag representing what the exception was being used for.

2022-04-27 13:03 UTC, timothyklemm commented on esp/bindings/http/platform/httpservice.cpp
> +    content.append('.');
Agreed.

2022-04-27 13:07 UTC, timothyklemm commented on esp/bindings/http/platform/httpservice.cpp
> +    m_response->send();
I am unaware of a standard response that calls for anything more than plain text. This is consistent with the existing handling of IEspHttpException instances.

2022-04-27 13:08 UTC, HPCCSmoketest commented
Process of PR-16018, label: hpcc-27532_exception_handling starts now.
The reason of this test is: Forced to re-test.
Commit ID: 88413b60e8ceb7d212b0ca46b5cb5d1f158bab4b
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-145.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-04-27 13:40 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-145.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 88413b60e8ceb7d212b0ca46b5cb5d1f158bab4b
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.21-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |222 |222 |0 |0 |0 |68 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |22 sec  (00:00:22) |
|setup (thor) |9 |9 |0 |39 sec  (00:00:39) |
|setup (roxie) |20 |20 |0 |18 sec  (00:00:18) |
|test (hthor) |986 |986 |0 |846 sec  (00:14:06) |
|test (thor) |896 |896 |0 |1020 sec  (00:17:00) |
|test (roxie) |1056 |1056 |0 |904 sec  (00:15:04) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  444 sec (00:07:24) |  110 sec (00:01:50) |   21 sec (00:00:21) |   16 sec (00:00:16) | 1281 sec (00:21:21) |   19 sec (00:00:19) | 1908 sec (00:31:48) |

2022-05-06 08:41 UTC, richardkchapman commented
@rpastrana Looks like this is waiting a response from you?

2022-05-06 13:21 UTC, rpastrana approved these changes
@timothyklemm looks fine.

2022-05-06 13:55 UTC, richardkchapman commented
@timothyklemm Please squash

2022-05-06 14:20 UTC, HPCCSmoketest commented
Process of PR-16018, label: hpcc-27532_exception_handling starts now.
The reason of this test is: Forced to re-test.
Commit ID: 86afe21fc6fb887f0c9af45267fab81d59a48c84
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-107.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-05-06 14:52 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-107.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 86afe21fc6fb887f0c9af45267fab81d59a48c84
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.25-closedown0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | elaps | 
|---|---|---|---|---|---|---|
|unittest |223 |223 |0 |0 |0 |69 sec |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |1 sec |



Regression test result:

| phase | total | pass | fail | elaps | 
|---|---|---|---|---|
|setup (hthor) |9 |9 |0 |23 sec  (00:00:23) |
|setup (thor) |9 |9 |0 |38 sec  (00:00:38) |
|setup (roxie) |20 |20 |0 |19 sec  (00:00:19) |
|test (hthor) |986 |986 |0 |894 sec  (00:14:54) |
|test (thor) |896 |896 |0 |1014 sec  (00:16:54) |
|test (roxie) |1056 |1056 |0 |901 sec  (00:15:01) |


HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   23 sec (00:00:23) |  450 sec (00:07:30) |  109 sec (00:01:49) |   21 sec (00:00:21) |   16 sec (00:00:16) | 1276 sec (00:21:16) |   19 sec (00:00:19) | 1914 sec (00:31:54) |

2022-05-09 09:42 UTC, merged