HPCC-27584 NP selector should be on dynamic thor-eclagent label value
hpcc-systems/HPCC-Platform pull request #16064
Opened 2022-05-04 10:55 UTC by jakesmith

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-05-04 10:59 UTC, jakesmith commented
@richardkchapman - noticed that I'd left a static app label in for the thor-eclagent - it should have been based on the constructed name (otherwise all agents from other thor's could connect).

Please review.
I could reinstate the 'job' label in this PR, and introduce another label (e.g. 'instance')..?
But it would need to be based on the same value (_HPCC_JOBNAME_), and would need to add one an 'instance' to thor-eclagent as well.

2022-05-04 11:01 UTC, HPCCSmoketest commented
Process of PR-16064, label: HPCC-27584-Thor-agent-networkpolicy-2 starts now.
The reason of this test is: Forced to re-test.
Commit ID: e6a254ef4ea2903e907b40d9f88889dda853cb26
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-66.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-05-04 11:04 UTC, richardkchapman commented
It feels correct to me to have app as it was, job with jobname, and a new label to use for selection of which pods get the thormaster network policy

2022-05-04 11:36 UTC, HPCCSmoketest commented
Process of PR-16064, label: HPCC-27584-Thor-agent-networkpolicy-2 starts now.
The reason of this test is: Forced to re-test.
Commit ID: ac7e666b2a5d89f8520292ac7c328a41b8950939
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-98.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-05-04 11:40 UTC, jakesmith commented
@richardkchapman - reverted app and job label to what they were, introduced new instance label, which in Thor pods is same as job, and in agents is same as app, such that the manager NP ingress selector can select on both the thor job and the thor-eclagent.

2022-05-04 11:45 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-98.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: ac7e666b2a5d89f8520292ac7c328a41b8950939
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.6.25-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   16 sec (00:00:16) |  405 sec (00:06:45) |   98 sec (00:01:38) |   19 sec (00:00:19) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  538 sec (00:08:58) |

2022-05-04 15:33 UTC, richardkchapman requested changes
Not sure what app is now used for but it feels like it should be constant.

2022-05-04 15:33 UTC, richardkchapman commented on helm/hpcc/templates/thor.yaml
> +        app: {{ $commonCtx.eclAgentName | quote }}
I would think app should be a constant

2022-05-04 15:33 UTC, richardkchapman commented on helm/hpcc/templates/thor.yaml
> +      app: {{ $commonCtx.thorAgentName | quote }}
And here

2022-05-04 15:33 UTC, richardkchapman commented on helm/hpcc/templates/thor.yaml
> +        app: {{ $commonCtx.thorAgentName | quote }}
And here

2022-05-04 16:26 UTC, HPCCSmoketest commented
Process of PR-16064, label: HPCC-27584-Thor-agent-networkpolicy-2 starts now.
The reason of this test is: Forced to re-test.
Commit ID: f919ffba0e9291eaceffca82c85c80414084ce1c
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-6.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-05-04 16:35 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-6.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: f919ffba0e9291eaceffca82c85c80414084ce1c
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.6.25-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   22 sec (00:00:22) |  406 sec (00:06:46) |   98 sec (00:01:38) |   18 sec (00:00:18) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  544 sec (00:09:04) |

2022-05-05 08:21 UTC, richardkchapman approved these changes

2022-05-05 11:01 UTC, ghalliday approved these changes
Looks sensible to me

2022-05-05 12:32 UTC, richardkchapman commented
@jakesmith Please squash

2022-05-05 12:45 UTC, jakesmith commented
@richardkchapman - squashed

2022-05-05 12:50 UTC, HPCCSmoketest commented
Process of PR-16064, label: HPCC-27584-Thor-agent-networkpolicy-2 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 9727aad93db217c03eb46a80cc8952120c4489c3
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-198.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-05-05 12:59 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-20-0-198.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 9727aad93db217c03eb46a80cc8952120c4489c3
Containerized:True
Build: success
Milestone:Install hpccsystems-platform-community_8.6.25-closedown0.el7.x86_64.rpm
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   17 sec (00:00:17) |  404 sec (00:06:44) |   99 sec (00:01:39) |   18 sec (00:00:18) |    0 sec (00:00:00) |    0 sec (00:00:00) |    0 sec (00:00:00) |  538 sec (00:08:58) |

2022-05-05 13:02 UTC, merged