HPCC-27663 Mine checkbox on WU list page unclickable
hpcc-systems/HPCC-Platform pull request #16110
Opened 2022-05-19 20:49 UTC by jeclrsg

Signed-off-by: Jeremy Clements <jeremy.clements@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-05-19 20:51 UTC, jeclrsg commented
@GordonSmith I need to go back and check for other list pages that might have this toggle in the toolbar, but wanted to check with you about the method used for the WU list page.

2022-05-20 07:45 UTC, GordonSmith requested changes

2022-05-20 07:45 UTC, GordonSmith commented on esp/src/src-react/components/Workunits.tsx
> +            key: "mine", text: nlsHPCC.Mine, disabled: !!store || !!currentUser, iconProps: { iconName: "Contact" }, canCheck: true, checked: mine,
This doesn't look right to me - Should probably be `!currentUser`?

2022-05-20 07:45 UTC, GordonSmith commented on esp/src/src-react/hooks/user.ts
> +export function useCurrentUser(): { currentUser: WsAccount.MyAccountResponse } {
Should really be called `useMyAccount`?

2022-06-01 11:46 UTC, GordonSmith approved these changes
@jeclrsg this looks good, if you want it pulled you will need to click on "ready for review".

2022-06-01 12:25 UTC, HPCCSmoketest commented
Process of PR-16110, label: hpcc-27663-mine-checkbox-always-disabled starts now.
The reason of this test is: Forced to re-test.
Commit ID: a351e4129b6f2ce7b118bb85ea600968b1dfcf82
Estimated completion time is 0.15 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-224.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-06-01 12:35 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-224.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: a351e4129b6f2ce7b118bb85ea600968b1dfcf82
Containerized:False
Build: success
Milestone:Install hpccsystems-platform-community_8.6.29-closedown0.el7.x86_64.rpm
HPCC Start: OK
HPCC Stop: OK
HPCC Uninstall: OK
Time stats:

| Prep time | Build time | Package time | Install time | Start time | Test time | Stop time | Summary | 
|---|---|---|---|---|---|---|---|
|   34 sec (00:00:34) |  418 sec (00:06:58) |  109 sec (00:01:49) |   20 sec (00:00:20) |   16 sec (00:00:16) |    0 sec (00:00:00) |   14 sec (00:00:14) |  611 sec (00:10:11) |

2022-06-01 12:46 UTC, merged