HPCC-27738 Remove H3 submodule
hpcc-systems/HPCC-Platform pull request #16168
Opened 2022-06-08 07:52 UTC by GordonSmith

Switch to vcpkg version

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-06-08 07:59 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: b6f85f4f6cdab39da50ec9706ce5d48a39b38226
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-57.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2

2022-06-08 07:59 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-57.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: b6f85f4f6cdab39da50ec9706ce5d48a39b38226
Containerized:False
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-08_07-59-41 11 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-08_07-59-41)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
\tmodified: vcpkg (new commits)
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-08_07-59-29.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-08_07-59-29.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-08_07-59-41
time logs started
Prep time   :    11 sec (00:00:11)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    11 sec (00:00:11)
time logs end


 ... ( comment is too long, 65 lines, 2900 bytes, truncated) ... 
[Build error:](https://gist.github.com/1e05b51ab560f669c7d5a159c2a7b668)
Build log [Build log](https://gist.github.com/HPCCSmoketest/1e05b51ab560f669c7d5a159c2a7b668#file-result-22-06-08-07-59-16-log)

```

2022-06-08 08:12 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-28.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 6bec5d9e10c7bd28b151e9a6222b8f3dbd7de443
Containerized:False
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-08_08-12-02 26 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-08_08-12-02)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-08_08-11-35.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-08_08-11-35.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-08_08-12-02
time logs started
Prep time   :    26 sec (00:00:26)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    26 sec (00:00:26)
time logs end


 ... ( comment is too long, 67 lines, 2971 bytes, truncated) ... 
[Build error:](https://gist.github.com/e136bf0720c4a0cd06c008e223c84f31)
Build log [Build log](https://gist.github.com/HPCCSmoketest/e136bf0720c4a0cd06c008e223c84f31#file-result-22-06-08-08-11-20-log)

```

2022-06-08 08:27 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: eea7f38448c7296ad15151d2109ef9d96777ab70
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-193.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-06-08 08:27 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-193.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: eea7f38448c7296ad15151d2109ef9d96777ab70
Containerized:True
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-08_08-27-55 20 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-08_08-27-55)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-08_08-27-34.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-08_08-27-34.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-08_08-27-55
time logs started
Prep time   :    20 sec (00:00:20)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    20 sec (00:00:20)
time logs end


 ... ( comment is too long, 67 lines, 2971 bytes, truncated) ... 
[Build error:](https://gist.github.com/ac866fb32e43de93f6896e8a303803a2)
Build log [Build log](https://gist.github.com/HPCCSmoketest/ac866fb32e43de93f6896e8a303803a2#file-result-22-06-08-08-27-19-log)

```

2022-06-08 08:45 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 3c3619f3512fe4d6c2854daa846f0b449fb43dc8
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-154.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

2022-06-08 08:45 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-154.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 3c3619f3512fe4d6c2854daa846f0b449fb43dc8
Containerized:True
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-08_08-45-44 9 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-08_08-45-44)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-08_08-45-33.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-08_08-45-33.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-08_08-45-44
time logs started
Prep time   :     9 sec (00:00:09)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :     9 sec (00:00:09)
time logs end


 ... ( comment is too long, 67 lines, 2970 bytes, truncated) ... 
[Build error:](https://gist.github.com/ee891d5b478db9af6fb436d2f5752bad)
Build log [Build log](https://gist.github.com/HPCCSmoketest/ee891d5b478db9af6fb436d2f5752bad#file-result-22-06-08-08-45-19-log)

```

2022-06-08 08:57 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 3c3619f3512fe4d6c2854daa846f0b449fb43dc8
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-159.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

Using VCPKG to build HPCC.

2022-06-08 08:57 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-159.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 3c3619f3512fe4d6c2854daa846f0b449fb43dc8
Containerized:True
Number of Error(s): 7
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      Failed to download file with error: 1
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxys remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/apr/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:146 (include)
error: building apr:x64-linux failed with: BUILD_FAILED
Please ensure youre using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+apr
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[apr]+Build+error
Include [apr] Build error in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 978efd0 2022-05-18 (3 weeks ago)
-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  /home/centos/smoketest/PR-16168/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:121 (include)
  CMakeLists.txt:75 (project)
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLangu
 ... ( comment is too long, 107 lines, 5992 bytes, truncated) ... 
[Build error:](https://gist.github.com/aafe83afd60213ae7d3310d5957e3f63)
Build log [Build log](https://gist.github.com/HPCCSmoketest/aafe83afd60213ae7d3310d5957e3f63#file-result-22-06-08-08-57-18-log)

```

2022-06-08 09:13 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 9004bd0388455cd16801ad48dd89f4d68c0020c8
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-198.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

Using VCPKG to build HPCC.

2022-06-08 09:13 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-198.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 9004bd0388455cd16801ad48dd89f4d68c0020c8
Containerized:True
Number of Error(s): 7
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      Failed to download file with error: 1
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxys remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/apr/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:146 (include)
error: building apr:x64-linux failed with: BUILD_FAILED
Please ensure youre using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+apr
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[apr]+Build+error
Include [apr] Build error in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 978efd0 2022-05-18 (3 weeks ago)
-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  /home/centos/smoketest/PR-16168/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:121 (include)
  CMakeLists.txt:75 (project)
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLangu
 ... ( comment is too long, 107 lines, 5992 bytes, truncated) ... 
[Build error:](https://gist.github.com/2f1c45fb7e0d7ac9f59b363f3a971db9)
Build log [Build log](https://gist.github.com/HPCCSmoketest/2f1c45fb7e0d7ac9f59b363f3a971db9#file-result-22-06-08-09-13-22-log)

```

2022-06-08 09:48 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: New commit.
Commit ID: 0848ba7b6dba85c5eb271bafe150243673024746
Estimated completion time is 0.90 hour(s)
centos 7.9.2009 (Linux 3.10.0-1160.42.2.el7.x86_64)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.23.0,  CMake: 3.18.0,  cUrl: 7.29.0,  node.js: v16.11.0,  npm: 8.0.0
Build only for containerized environment.

Using VCPKG to build HPCC.

2022-06-08 09:49 UTC, richardkchapman requested changes

2022-06-08 09:54 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 0848ba7b6dba85c5eb271bafe150243673024746
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-231.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

Using VCPKG to build HPCC.

2022-06-08 10:01 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.9.2009 (Linux 3.10.0-1160.42.2.el7.x86_64)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.23.0,  CMake: 3.18.0,  cUrl: 7.29.0,  node.js: v16.11.0,  npm: 8.0.0
Sha: 0848ba7b6dba85c5eb271bafe150243673024746
Containerized:True
Number of Error(s): 7
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Error code: 1
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /home/centos/smoketest/PR-16168/HPCC-Platform/vcpkg/downloads/tools/cmake-3.22.2-linux/cmake-3.22.2-linux-x86_64/bin/cmake /home/centos/smoketest/PR-16168/HPCC-Platform/vcpkg/buildtrees/libmysql/src/a9fb86d137-105364cf5b.clean -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/centos/smoketest/PR-16168/HPCC-Platform/vcpkg/packages/libmysql_x64-linux/debug -DWITHOUT_SERVER=ON -DWITH_UNIT_TESTS=OFF -DENABLED_PROFILING=OFF -DENABLE_TESTING=OFF -DWIX_DIR=OFF -DSTACK_DIRECTION=-1 -DIGNORE_BOOST_VERSION=ON -DWITH_SYSTEMD=OFF -DWITH_TEST_TRACE_PLUGIN=OFF -DMYSQL_MAINTAINER_MODE=OFF -DBUNDLE_RUNTIME_LIBRARIES=OFF -DDOWNLOAD_BOOST=OFF -DENABLE_DOWNLOADS=OFF -DWITH_NDB_TEST=OFF -DWITH_NDB_NODEJS_DEFAULT=OFF -DWITH_NDBAPI_EXAMPLES=OFF -DMYSQLX_ADDITIONAL_TESTS_ENABLE=OFF -DWITH_SSL=system -DWITH_ICU=system -DWITH_LIBEVENT=system -DWITH_LZ4=system -DWITH_ZLIB=system -DFORCE_UNSUPPORTED_COMPILER= -DINSTALL_STATIC_LIBRARIES=1 -DLINK_STATIC_RUNTIME_LIBRARIES=0 -DCMAKE_MAKE_PROGRAM=/home/centos/smoketest/PR-16168/HPCC-Platform/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/centos/smoketest/PR-16168/HPCC-Platform/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/centos/smoketest/PR-16168/HPCC-Platform/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/centos/smoketest/PR-16168/HPCC-Platform/vcpkg -D_VCPKG_INSTALLED_DIR=/home/centos/smoketest/PR-16168/build/vcpkg_installed -DVCPKG_MANIFEST_INSTALL=OFF
    Working Directory: /home/centos/smoketest/PR-16168/HPCC-Platform/vcpkg/buildtrees/libmysql/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/centos/smoketest/PR-16168/HPCC-Platform/vcpkg/buildtrees/libmysql/config-x64-linux-dbg-out.log
      /home/centos/smoketest/PR-16168/HPCC-Platform/vcpkg/buildtrees/libmysql/config-x64-linux-dbg-err.log
Call Stack (most recent call first):
  /home/centos/smoketest/PR-16168/build/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:343 (vcpkg_execute_required_process)
  ports/libmysql/portfile.cmake:39 (vcpkg_cmake_configure)
  scripts/ports.cmake:146 (include
 ... ( comment is too long, 90 lines, 7316 bytes, truncated) ... 
[Build error:](https://gist.github.com/ab7c9d86af5b14cb610aa09435e572e4)
Build log [Build log](https://gist.github.com/HPCCSmoketest/ab7c9d86af5b14cb610aa09435e572e4#file-result-22-06-08-09-48-01-log)

```

2022-06-08 10:02 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: New commit.
Commit ID: 3a1730415b016856249f911fb35642a40a9a3932
Estimated completion time is 0.90 hour(s)
centos 7.9.2009 (Linux 3.10.0-1160.42.2.el7.x86_64)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.23.0,  CMake: 3.18.0,  cUrl: 7.29.0,  node.js: v16.11.0,  npm: 8.0.0
Build only for containerized environment.

Using VCPKG to build HPCC.

2022-06-08 10:07 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: New commit.
Commit ID: 6a13bdea7a0bb076b73973c858c4c4e7193f2909
Estimated completion time is 0.90 hour(s)
centos 7.9.2009 (Linux 3.10.0-1160.42.2.el7.x86_64)
 Host: ip-10-20-0-116.ca-central-1.compute.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.23.0,  CMake: 3.18.0,  cUrl: 7.29.0,  node.js: v16.11.0,  npm: 8.0.0
Build only for containerized environment.

Using VCPKG to build HPCC.

2022-06-08 10:08 UTC, GordonSmith commented on dockerfiles/platform-build-base/Dockerfile
> +# This is version 8.8 of the platform-build-base, and anyone building/using it should have set that in BASE_VER
I have rolled back the version bump

2022-06-08 10:08 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 6a13bdea7a0bb076b73973c858c4c4e7193f2909
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-223.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

Using VCPKG to build HPCC.

2022-06-08 10:09 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-223.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 6a13bdea7a0bb076b73973c858c4c4e7193f2909
Containerized:True
Number of Error(s): 7
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      Failed to download file with error: 1
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxys remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/apr/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:146 (include)
error: building apr:x64-linux failed with: BUILD_FAILED
Please ensure youre using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+apr
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[apr]+Build+error
Include [apr] Build error in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 978efd0 2022-05-18 (3 weeks ago)
-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  /home/centos/smoketest/PR-16168/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:121 (include)
  CMakeLists.txt:75 (project)
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLangu
 ... ( comment is too long, 107 lines, 5992 bytes, truncated) ... 
[Build error:](https://gist.github.com/27598a459d42665e6956360e853f9409)
Build log [Build log](https://gist.github.com/HPCCSmoketest/27598a459d42665e6956360e853f9409#file-result-22-06-08-10-08-27-log)

```

2022-06-08 11:02 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 6ac9958f4ef574fd72bd7fa159161881cda899a2
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-72.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

Using VCPKG to build HPCC.

2022-06-08 11:02 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-72.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 6ac9958f4ef574fd72bd7fa159161881cda899a2
Containerized:True
Number of Error(s): 7
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      Failed to download file with error: 1
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxys remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/apr/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:146 (include)
error: building apr:x64-linux failed with: BUILD_FAILED
Please ensure youre using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+apr
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[apr]+Build+error
Include [apr] Build error in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 978efd0 2022-05-18 (3 weeks ago)
-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  /home/centos/smoketest/PR-16168/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:121 (include)
  CMakeLists.txt:75 (project)
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLangua
 ... ( comment is too long, 107 lines, 5991 bytes, truncated) ... 
[Build error:](https://gist.github.com/65c146ff0de4b102737d7f79d604eb82)
Build log [Build log](https://gist.github.com/HPCCSmoketest/65c146ff0de4b102737d7f79d604eb82#file-result-22-06-08-11-02-22-log)

```

2022-06-08 11:11 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 67465c04a80d3e3a780ba47f354ad64bfd652852
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-176.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

Using VCPKG to build HPCC.

2022-06-08 11:11 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-176.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 67465c04a80d3e3a780ba47f354ad64bfd652852
Containerized:True
Number of Error(s): 7
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      Failed to download file with error: 1
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxys remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/apr/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:146 (include)
error: building apr:x64-linux failed with: BUILD_FAILED
Please ensure youre using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+apr
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[apr]+Build+error
Include [apr] Build error in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 978efd0 2022-05-18 (3 weeks ago)
-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  /home/centos/smoketest/PR-16168/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:121 (include)
  CMakeLists.txt:75 (project)
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLangu
 ... ( comment is too long, 107 lines, 5992 bytes, truncated) ... 
[Build error:](https://gist.github.com/7c6aa7fe1f743437b5ab60fdae1fcaf3)
Build log [Build log](https://gist.github.com/HPCCSmoketest/7c6aa7fe1f743437b5ab60fdae1fcaf3#file-result-22-06-08-11-11-17-log)

```

2022-06-08 11:20 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 38aae7da804e43809075e74a01843510eee88e36
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-232.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

Using VCPKG to build HPCC.

2022-06-08 11:21 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-232.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 38aae7da804e43809075e74a01843510eee88e36
Containerized:True
Number of Error(s): 7
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      Failed to download file with error: 1
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxys remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/apr/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:146 (include)
error: building apr:x64-linux failed with: BUILD_FAILED
Please ensure youre using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+apr
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[apr]+Build+error
Include [apr] Build error in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 978efd0 2022-05-18 (3 weeks ago)
-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  /home/centos/smoketest/PR-16168/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:121 (include)
  CMakeLists.txt:75 (project)
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLangu
 ... ( comment is too long, 107 lines, 5992 bytes, truncated) ... 
[Build error:](https://gist.github.com/6edd1efc1edc3f6d63adc277e8efed79)
Build log [Build log](https://gist.github.com/HPCCSmoketest/6edd1efc1edc3f6d63adc277e8efed79#file-result-22-06-08-11-20-29-log)

```

2022-06-08 11:29 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 0f8578ec2b769303f56a9ae8d0024e230a888256
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-87.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

Using VCPKG to build HPCC.

2022-06-08 11:29 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-87.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 0f8578ec2b769303f56a9ae8d0024e230a888256
Containerized:True
Number of Error(s): 7
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      Failed to download file with error: 1
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxys remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/apr/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:146 (include)
error: building apr:x64-linux failed with: BUILD_FAILED
Please ensure youre using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+apr
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[apr]+Build+error
Include [apr] Build error in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 978efd0 2022-05-18 (3 weeks ago)
-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  /home/centos/smoketest/PR-16168/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:121 (include)
  CMakeLists.txt:75 (project)
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLangua
 ... ( comment is too long, 107 lines, 5990 bytes, truncated) ... 
[Build error:](https://gist.github.com/5647b9ab84937f8d1cda629b3246c7d5)
Build log [Build log](https://gist.github.com/HPCCSmoketest/5647b9ab84937f8d1cda629b3246c7d5#file-result-22-06-08-11-29-19-log)

```

2022-06-08 11:37 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: f49ebccedc388bb64a0df939d473813e36418eaa
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-20.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.

Using VCPKG to build HPCC.

2022-06-08 11:37 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-20.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: f49ebccedc388bb64a0df939d473813e36418eaa
Containerized:True
Number of Error(s): 7
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      Failed to download file with error: 1
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxys remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/apr/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:146 (include)
error: building apr:x64-linux failed with: BUILD_FAILED
Please ensure youre using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+apr
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[apr]+Build+error
Include [apr] Build error in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 978efd0 2022-05-18 (3 weeks ago)
-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  /home/centos/smoketest/PR-16168/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:121 (include)
  CMakeLists.txt:75 (project)
CMake Error: CMake was unable to find a build program corresponding to Unix Makefiles.  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLangua
 ... ( comment is too long, 107 lines, 5991 bytes, truncated) ... 
[Build error:](https://gist.github.com/23450743a7df1fe2406d8984bd4693b6)
Build log [Build log](https://gist.github.com/HPCCSmoketest/23450743a7df1fe2406d8984bd4693b6#file-result-22-06-08-11-37-15-log)

```

2022-06-08 13:19 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-83.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: fb9bda1786dc6bc37e95b7525c851def5c5ec133
Containerized:True
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-08_13-19-42 9 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-08_13-19-42)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-08_13-19-32.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-08_13-19-32.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-08_13-19-42
time logs started
Prep time   :     9 sec (00:00:09)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :     9 sec (00:00:09)
time logs end


 ... ( comment is too long, 67 lines, 2969 bytes, truncated) ... 
[Build error:](https://gist.github.com/d84e966cbbb5dfebcc40ef8c60951348)
Build log [Build log](https://gist.github.com/HPCCSmoketest/d84e966cbbb5dfebcc40ef8c60951348#file-result-22-06-08-13-19-17-log)

```

2022-06-09 05:26 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: c12c81d55d3bcef60d435517111395b22b29dd43
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-22.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-09 05:27 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-22.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: c12c81d55d3bcef60d435517111395b22b29dd43
Containerized:True
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-09_05-27-02 30 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-09_05-27-02)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-09_05-26-31.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-09_05-26-31.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-09_05-27-02
time logs started
Prep time   :    30 sec (00:00:30)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    30 sec (00:00:30)
time logs end


 ... ( comment is too long, 67 lines, 2970 bytes, truncated) ... 
[Build error:](https://gist.github.com/2dc7e4a0f45df0168508afd4e5639493)
Build log [Build log](https://gist.github.com/HPCCSmoketest/2dc7e4a0f45df0168508afd4e5639493#file-result-22-06-09-05-26-16-log)

```

2022-06-09 05:38 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: New commit.
Commit ID: b8d20f9eb08b8e19e3f113e0ea89c7c21e6d36e9
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-47.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-09 05:38 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-47.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: b8d20f9eb08b8e19e3f113e0ea89c7c21e6d36e9
Containerized:True
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-09_05-38-50 19 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-09_05-38-50)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-09_05-38-30.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-09_05-38-30.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-09_05-38-50
time logs started
Prep time   :    19 sec (00:00:19)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    19 sec (00:00:19)
time logs end


 ... ( comment is too long, 67 lines, 2970 bytes, truncated) ... 
[Build error:](https://gist.github.com/5ae202f6ccce943a83e11713e33da9db)
Build log [Build log](https://gist.github.com/HPCCSmoketest/5ae202f6ccce943a83e11713e33da9db#file-result-22-06-09-05-38-15-log)

```

2022-06-10 06:11 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: aab10d3313f38d2b98e90fad6d425af9ff0bfc8e
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-80.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-10 06:11 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-80.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: aab10d3313f38d2b98e90fad6d425af9ff0bfc8e
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-10_06-11-52 20 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-10_06-11-52)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-10_06-11-31.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-10_06-11-31.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-10_06-11-52
time logs started
Prep time   :    20 sec (00:00:20)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    20 sec (00:00:20)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/b7379968854395f4f8b191606de3dabc)
Build log [Build log](https://gist.github.com/HPCCSmoketest/b7379968854395f4f8b191606de3dabc#file-result-22-06-10-06-11-16-log)

```

2022-06-10 06:26 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 2bd21785ef5fa5bd5aff1868b065d80b2934bbc5
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-191.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-10 06:26 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-191.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 2bd21785ef5fa5bd5aff1868b065d80b2934bbc5
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-10_06-26-57 20 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-10_06-26-57)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-10_06-26-36.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-10_06-26-36.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-10_06-26-57
time logs started
Prep time   :    20 sec (00:00:20)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    20 sec (00:00:20)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/17bfd4dabe455adef52ce654b6443be2)
Build log [Build log](https://gist.github.com/HPCCSmoketest/17bfd4dabe455adef52ce654b6443be2#file-result-22-06-10-06-26-21-log)

```

2022-06-10 09:01 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: New commit.
Commit ID: 22bc267584b4b0aa4c07ca8e0b9e5acb09d962c0
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-10.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-10 09:02 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-10.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 22bc267584b4b0aa4c07ca8e0b9e5acb09d962c0
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-10_09-02-13 33 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-10_09-02-13)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-10_09-01-39.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-10_09-01-39.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-10_09-02-13
time logs started
Prep time   :    33 sec (00:00:33)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    33 sec (00:00:33)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/053ab1470a16d731f0305066eb0701e9)
Build log [Build log](https://gist.github.com/HPCCSmoketest/053ab1470a16d731f0305066eb0701e9#file-result-22-06-10-09-01-24-log)

```

2022-06-10 10:07 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 8cdf8b49e1d12391fb6e15534efb5f4f41a77590
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-67.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-10 10:08 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-67.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 8cdf8b49e1d12391fb6e15534efb5f4f41a77590
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-10_10-08-00 25 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-10_10-08-00)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-10_10-07-33.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-10_10-07-33.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-10_10-08-01
time logs started
Prep time   :    25 sec (00:00:25)
Build time  :     1 sec (00:00:01)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    26 sec (00:00:26)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/d93cd71a7b61570235389440658a673c)
Build log [Build log](https://gist.github.com/HPCCSmoketest/d93cd71a7b61570235389440658a673c#file-result-22-06-10-10-07-19-log)

```

2022-06-10 10:16 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: ed7dab868c90a3ef634adb239b8d4ba71163e553
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-182.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-10 10:17 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-182.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: ed7dab868c90a3ef634adb239b8d4ba71163e553
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-10_10-17-00 26 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-10_10-17-00)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-10_10-16-33.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-10_10-16-33.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-10_10-17-00
time logs started
Prep time   :    26 sec (00:00:26)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    26 sec (00:00:26)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/bfb27329fecd5c22c6a3ff2d40872344)
Build log [Build log](https://gist.github.com/HPCCSmoketest/bfb27329fecd5c22c6a3ff2d40872344#file-result-22-06-10-10-16-18-log)

```

2022-06-10 10:28 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: fb3d9cea1dd51140f32af2549a88d75e80447f7d
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-30.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-10 10:28 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-30.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: fb3d9cea1dd51140f32af2549a88d75e80447f7d
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-10_10-28-51 13 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-10_10-28-51)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-10_10-28-37.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-10_10-28-37.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-10_10-28-51
time logs started
Prep time   :    13 sec (00:00:13)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    13 sec (00:00:13)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/62dccc377d591e8b8159d6f8ae30ff07)
Build log [Build log](https://gist.github.com/HPCCSmoketest/62dccc377d591e8b8159d6f8ae30ff07#file-result-22-06-10-10-28-22-log)

```

2022-06-10 10:38 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 07aa426ae78c2b57b012c503a82a9dc7ec05cdd7
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-94.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-10 10:38 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-94.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 07aa426ae78c2b57b012c503a82a9dc7ec05cdd7
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-10_10-38-47 14 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-10_10-38-47)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-10_10-38-31.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-10_10-38-31.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-10_10-38-47
time logs started
Prep time   :    14 sec (00:00:14)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    14 sec (00:00:14)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/fdb3656c79073c55c26b440d562ffd04)
Build log [Build log](https://gist.github.com/HPCCSmoketest/fdb3656c79073c55c26b440d562ffd04#file-result-22-06-10-10-38-16-log)

```

2022-06-10 10:48 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: ead0c9d81a747ad940fc0f6bf22694b243a18441
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-108.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-10 13:09 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: New commit.
Commit ID: 6150895707686bcadd947bcafbf423b77314db71
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-131.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-10 13:09 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-131.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 6150895707686bcadd947bcafbf423b77314db71
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-10_13-09-49 15 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-10_13-09-49)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-10_13-09-33.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-10_13-09-33.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-10_13-09-49
time logs started
Prep time   :    15 sec (00:00:15)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    15 sec (00:00:15)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/ae762d8b3159eb2fef37918ecd966fa6)
Build log [Build log](https://gist.github.com/HPCCSmoketest/ae762d8b3159eb2fef37918ecd966fa6#file-result-22-06-10-13-09-18-log)

```

2022-06-10 14:23 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: f1c30af963a8048b3dadac8b7a70d6fe81b77f96
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-80.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-11 06:08 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 250fcb923f859959a8e1e0c870976f1ca857ebff
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-11.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-11 06:09 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-11.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 250fcb923f859959a8e1e0c870976f1ca857ebff
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-11_06-09-45 62 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-11_06-09-45)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-11_06-08-42.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-11_06-08-42.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-11_06-09-45
time logs started
Prep time   :    62 sec (00:01:02)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    62 sec (00:01:02)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/171bafe796b46d6f8088543887685848)
Build log [Build log](https://gist.github.com/HPCCSmoketest/171bafe796b46d6f8088543887685848#file-result-22-06-11-06-08-27-log)

```

2022-06-11 11:07 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 12054989f5bebdff1db4c833981ff3cfa9dea306
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-197.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-11 11:07 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-197.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 12054989f5bebdff1db4c833981ff3cfa9dea306
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-11_11-07-56 21 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-11_11-07-56)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-11_11-07-34.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-11_11-07-34.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-11_11-07-56
time logs started
Prep time   :    21 sec (00:00:21)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    21 sec (00:00:21)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/0d73b88aa3da503a94ef081690219a10)
Build log [Build log](https://gist.github.com/HPCCSmoketest/0d73b88aa3da503a94ef081690219a10#file-result-22-06-11-11-07-19-log)

```

2022-06-11 11:16 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 1f6c1a04f9aa707c5b4fa4b2bb589b9028ab2ae1
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-150.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-11 11:16 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-150.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 1f6c1a04f9aa707c5b4fa4b2bb589b9028ab2ae1
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-11_11-16-47 16 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-11_11-16-47)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-11_11-16-30.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-11_11-16-30.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-11_11-16-47
time logs started
Prep time   :    16 sec (00:00:16)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    16 sec (00:00:16)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/89d8e7b084cfe18fd4afe457f97a8374)
Build log [Build log](https://gist.github.com/HPCCSmoketest/89d8e7b084cfe18fd4afe457f97a8374#file-result-22-06-11-11-16-15-log)

```

2022-06-11 11:33 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: a995ff15edae844a1971f232cf996846ed65feb8
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-118.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-11 11:33 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-118.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: a995ff15edae844a1971f232cf996846ed65feb8
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-11_11-33-52 19 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-11_11-33-52)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-11_11-33-32.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-11_11-33-32.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-11_11-33-52
time logs started
Prep time   :    19 sec (00:00:19)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    19 sec (00:00:19)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/65ff0f0e9262b6f493f56baa92e14294)
Build log [Build log](https://gist.github.com/HPCCSmoketest/65ff0f0e9262b6f493f56baa92e14294#file-result-22-06-11-11-33-17-log)

```

2022-06-11 11:49 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: b1dbd685471952241bc0a4fe1ebbba512cd7c7c8
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-181.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-11 11:49 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-181.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: b1dbd685471952241bc0a4fe1ebbba512cd7c7c8
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-11_11-49-41 10 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-11_11-49-41)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-11_11-49-30.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-11_11-49-30.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-11_11-49-41
time logs started
Prep time   :    10 sec (00:00:10)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    10 sec (00:00:10)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/a559491a3686e181090b68ba325bb77b)
Build log [Build log](https://gist.github.com/HPCCSmoketest/a559491a3686e181090b68ba325bb77b#file-result-22-06-11-11-49-15-log)

```

2022-06-12 04:48 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 87ad2ca8b5657537cc7e3a726bb467a2621f3c4f
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-13.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 04:48 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-13.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 87ad2ca8b5657537cc7e3a726bb467a2621f3c4f
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_04-48-42 9 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_04-48-42)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_04-48-32.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_04-48-32.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_04-48-42
time logs started
Prep time   :     9 sec (00:00:09)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :     9 sec (00:00:09)
time logs end


 ... ( comment is too long, 68 lines, 2993 bytes, truncated) ... 
[Build error:](https://gist.github.com/6caaae8fc99d563edef2b70c0885d243)
Build log [Build log](https://gist.github.com/HPCCSmoketest/6caaae8fc99d563edef2b70c0885d243#file-result-22-06-12-04-48-17-log)

```

2022-06-12 05:00 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: ee296fb402556a76116a37a04f7b378c40cb4286
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-34.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 05:00 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-34.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: ee296fb402556a76116a37a04f7b378c40cb4286
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_05-00-43 10 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_05-00-43)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_05-00-32.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_05-00-32.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_05-00-43
time logs started
Prep time   :    10 sec (00:00:10)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    10 sec (00:00:10)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/279d44199adf016b90c3efad94f62896)
Build log [Build log](https://gist.github.com/HPCCSmoketest/279d44199adf016b90c3efad94f62896#file-result-22-06-12-05-00-17-log)

```

2022-06-12 05:12 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 267d73522d9d128199500cf53bb777f3d2b9c421
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-207.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 05:13 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-207.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 267d73522d9d128199500cf53bb777f3d2b9c421
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_05-13-05 31 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_05-13-05)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_05-12-32.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_05-12-32.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_05-13-05
time logs started
Prep time   :    31 sec (00:00:31)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    31 sec (00:00:31)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/a2d34f6abe54b20af3a6f300095ce218)
Build log [Build log](https://gist.github.com/HPCCSmoketest/a2d34f6abe54b20af3a6f300095ce218#file-result-22-06-12-05-12-18-log)

```

2022-06-12 05:22 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: fa7c1e19c7a4b73e3204626904cc9203ee22bbf2
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-196.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 05:22 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-196.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: fa7c1e19c7a4b73e3204626904cc9203ee22bbf2
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_05-22-41 9 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_05-22-41)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_05-22-31.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_05-22-31.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_05-22-41
time logs started
Prep time   :     9 sec (00:00:09)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :     9 sec (00:00:09)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/aaa8d67e4de3a2fcf267789dd9d7011b)
Build log [Build log](https://gist.github.com/HPCCSmoketest/aaa8d67e4de3a2fcf267789dd9d7011b#file-result-22-06-12-05-22-16-log)

```

2022-06-12 05:30 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 8fb99f8d4a27cf477111cc236a79bd5cd9df18d2
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-197.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 05:30 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-197.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 8fb99f8d4a27cf477111cc236a79bd5cd9df18d2
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_05-30-44 13 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_05-30-44)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_05-30-30.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_05-30-30.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_05-30-44
time logs started
Prep time   :    13 sec (00:00:13)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    13 sec (00:00:13)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/9104c7994229774171553d5c21d19a7a)
Build log [Build log](https://gist.github.com/HPCCSmoketest/9104c7994229774171553d5c21d19a7a#file-result-22-06-12-05-30-15-log)

```

2022-06-12 05:42 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: b73b305c8675a0e1489da97f9bd365bfabf8ad4d
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-230.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 05:42 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-230.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: b73b305c8675a0e1489da97f9bd365bfabf8ad4d
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_05-42-42 10 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_05-42-42)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_05-42-31.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_05-42-31.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_05-42-42
time logs started
Prep time   :    10 sec (00:00:10)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    10 sec (00:00:10)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/79de6e994bc6ede734cbc6bdabb091e1)
Build log [Build log](https://gist.github.com/HPCCSmoketest/79de6e994bc6ede734cbc6bdabb091e1#file-result-22-06-12-05-42-16-log)

```

2022-06-12 06:02 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 2d1f02c68c84f556de0f4f2c946cb41aeab6fc4d
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-22.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 06:03 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-22.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 2d1f02c68c84f556de0f4f2c946cb41aeab6fc4d
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_06-03-01 23 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_06-03-01)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_06-02-37.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_06-02-37.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_06-03-01
time logs started
Prep time   :    23 sec (00:00:23)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    23 sec (00:00:23)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/4ad0af9c6ccc5ffbd95b93e54123512d)
Build log [Build log](https://gist.github.com/HPCCSmoketest/4ad0af9c6ccc5ffbd95b93e54123512d#file-result-22-06-12-06-02-17-log)

```

2022-06-12 06:22 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: fb786410b018038fbea144bf8f29d3bde42e233e
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-234.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 06:22 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-234.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: fb786410b018038fbea144bf8f29d3bde42e233e
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_06-22-51 10 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_06-22-51)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_06-22-40.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_06-22-40.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_06-22-51
time logs started
Prep time   :    10 sec (00:00:10)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    10 sec (00:00:10)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/31db1328273ea242a89afddbcd2342c4)
Build log [Build log](https://gist.github.com/HPCCSmoketest/31db1328273ea242a89afddbcd2342c4#file-result-22-06-12-06-22-18-log)

```

2022-06-12 07:19 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: e90348b2f1316176b77b72272c420d96f72a1071
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-40.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 07:19 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-40.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: e90348b2f1316176b77b72272c420d96f72a1071
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_07-19-52 16 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_07-19-52)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_07-19-35.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_07-19-35.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_07-19-52
time logs started
Prep time   :    16 sec (00:00:16)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    16 sec (00:00:16)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/34c5c78eccb1e60f222b80a93d741070)
Build log [Build log](https://gist.github.com/HPCCSmoketest/34c5c78eccb1e60f222b80a93d741070#file-result-22-06-12-07-19-20-log)

```

2022-06-12 07:27 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: New commit.
Commit ID: 95df60716f7e594de520223fd0170b41fce8426e
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-80.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 07:27 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-80.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 95df60716f7e594de520223fd0170b41fce8426e
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_07-27-44 12 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_07-27-45)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_07-27-31.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_07-27-31.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_07-27-45
time logs started
Prep time   :    12 sec (00:00:12)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    12 sec (00:00:12)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/ef6ce83871eaa235dc8e614bcebfcb4a)
Build log [Build log](https://gist.github.com/HPCCSmoketest/ef6ce83871eaa235dc8e614bcebfcb4a#file-result-22-06-12-07-27-16-log)

```

2022-06-12 07:35 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 82b021fadc188e6821a55c5d12f66dc8f0ae6ebb
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-156.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 07:35 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-156.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 82b021fadc188e6821a55c5d12f66dc8f0ae6ebb
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_07-35-48 14 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_07-35-48)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_07-35-33.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_07-35-33.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_07-35-48
time logs started
Prep time   :    14 sec (00:00:14)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    14 sec (00:00:14)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/b7593d0fb544b8e91da6f94cac755292)
Build log [Build log](https://gist.github.com/HPCCSmoketest/b7593d0fb544b8e91da6f94cac755292#file-result-22-06-12-07-35-18-log)

```

2022-06-12 07:47 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 85a415d0b87070cf0abc0c513afd3c9bf5578474
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-53.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 07:48 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-53.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 85a415d0b87070cf0abc0c513afd3c9bf5578474
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_07-48-08 28 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_07-48-08)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_07-47-39.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_07-47-39.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_07-48-08
time logs started
Prep time   :    28 sec (00:00:28)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    28 sec (00:00:28)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/c9e6a5c05ddf82302898975fc65dac6a)
Build log [Build log](https://gist.github.com/HPCCSmoketest/c9e6a5c05ddf82302898975fc65dac6a#file-result-22-06-12-07-47-24-log)

```

2022-06-12 07:55 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 7735e90a5101b1be00f2912f6479f557b253f521
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-210.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-12 07:55 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-210.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 7735e90a5101b1be00f2912f6479f557b253f521
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-12_07-55-47 16 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-12_07-55-47)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-12_07-55-30.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-12_07-55-30.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-12_07-55-47
time logs started
Prep time   :    16 sec (00:00:16)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    16 sec (00:00:16)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/ded2571c56e0f578afe43ebb6c14c892)
Build log [Build log](https://gist.github.com/HPCCSmoketest/ded2571c56e0f578afe43ebb6c14c892#file-result-22-06-12-07-55-15-log)

```

2022-06-15 06:00 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 2b79e17a4dff699b4635aa3edb2dc9f5840e1723
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-136.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-15 06:01 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-136.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 2b79e17a4dff699b4635aa3edb2dc9f5840e1723
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-15_06-01-10 34 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-15_06-01-10)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-15_06-00-35.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-15_06-00-35.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-15_06-01-11
time logs started
Prep time   :    34 sec (00:00:34)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    34 sec (00:00:34)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/6a23440b9f953e405cb434eebf1bd8b4)
Build log [Build log](https://gist.github.com/HPCCSmoketest/6a23440b9f953e405cb434eebf1bd8b4#file-result-22-06-15-06-00-20-log)

```

2022-06-15 07:01 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 41b234ca52db21cfdb47e78418d66f63d57b5f57
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-158.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-15 07:01 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-158.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 41b234ca52db21cfdb47e78418d66f63d57b5f57
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-15_07-01-57 22 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-15_07-01-57)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-15_07-01-34.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-15_07-01-34.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-15_07-01-57
time logs started
Prep time   :    22 sec (00:00:22)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    22 sec (00:00:22)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/e66af5a9b0d339c950293e6ba40de105)
Build log [Build log](https://gist.github.com/HPCCSmoketest/e66af5a9b0d339c950293e6ba40de105#file-result-22-06-15-07-01-19-log)

```

2022-06-15 07:16 UTC, GordonSmith commented on .github/workflows/smoketest.yml
> +
No need to "setapikey" for read-only nuget access

2022-06-15 07:16 UTC, GordonSmith commented on .github/workflows/smoketest.yml
> +          -username "hpcc-systems" \
Username should be GITHUB_OWNER

2022-06-15 07:16 UTC, GordonSmith commented on .github/workflows/smoketest.yml
> +        -DUSE_NLP=OFF \
This should be ON?

2022-06-15 07:29 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 3c265457c33414f88fe567efc61b69fc0a05803c
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-167.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-15 07:30 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-167.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 3c265457c33414f88fe567efc61b69fc0a05803c
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-15_07-30-05 27 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-15_07-30-05)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-15_07-29-37.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-15_07-29-37.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-15_07-30-05
time logs started
Prep time   :    27 sec (00:00:27)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    27 sec (00:00:27)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/95528bc56ef8b4b56d2eb2762d33b32d)
Build log [Build log](https://gist.github.com/HPCCSmoketest/95528bc56ef8b4b56d2eb2762d33b32d#file-result-22-06-15-07-29-22-log)

```

2022-06-15 08:21 UTC, GordonSmith commented on dockerfiles/platform-build-incremental-container/Dockerfile
> +
@richardkchapman - the mono installation above should be moved into the build base at some point.

2022-06-15 08:22 UTC, GordonSmith commented on dockerfiles/platform-build-incremental-container/Dockerfile
> +ARG USE_CPPUNIT=1
The above two ARGs are not needed?

2022-06-15 08:34 UTC, GordonSmith commented on dockerfiles/platform-build-incremental-container/Dockerfile
> +
@jakesmith - I think this was needed as the currently cached base does include the VCPKG settings?

2022-06-15 08:55 UTC, GordonSmith commented on dockerfiles/platform-build-incremental-container/Dockerfile
> +ARG USE_CPPUNIT=1
They are needed

2022-06-15 09:10 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: d3d34ff48918513480d8ed3c657a5ed006b90917
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-52.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-15 09:10 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-52.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: d3d34ff48918513480d8ed3c657a5ed006b90917
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-15_09-10-47 12 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-15_09-10-47)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-15_09-10-34.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-15_09-10-34.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-15_09-10-47
time logs started
Prep time   :    12 sec (00:00:12)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    12 sec (00:00:12)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/47ed5342bc274f5273e81ad1e16ea780)
Build log [Build log](https://gist.github.com/HPCCSmoketest/47ed5342bc274f5273e81ad1e16ea780#file-result-22-06-15-09-10-19-log)

```

2022-06-17 05:28 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 35b4a6face3b8616f06c1da660889bf160e2fb7e
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-95.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-17 05:29 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-95.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 35b4a6face3b8616f06c1da660889bf160e2fb7e
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-17_05-28-59 24 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-17_05-28-59)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-17_05-28-33.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-17_05-28-33.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-17_05-29-00
time logs started
Prep time   :    24 sec (00:00:24)
Build time  :     1 sec (00:00:01)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    25 sec (00:00:25)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/e540df4c3122b12d70c1a0aa61712baf)
Build log [Build log](https://gist.github.com/HPCCSmoketest/e540df4c3122b12d70c1a0aa61712baf#file-result-22-06-17-05-28-19-log)

```

2022-06-17 05:36 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: New commit.
Commit ID: 9b16c4cc771ed8e6789bae9d0c3f26fe0697c703
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-120.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-17 05:36 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-120.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 9b16c4cc771ed8e6789bae9d0c3f26fe0697c703
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-17_05-36-53 19 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-17_05-36-53)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-17_05-36-33.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-17_05-36-33.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-17_05-36-53
time logs started
Prep time   :    19 sec (00:00:19)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    19 sec (00:00:19)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/9165129547f22872dadea30cbded7b66)
Build log [Build log](https://gist.github.com/HPCCSmoketest/9165129547f22872dadea30cbded7b66#file-result-22-06-17-05-36-18-log)

```

2022-06-17 05:50 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: f22fcd56aaf8cca8805fcf3cc492989479058364
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-174.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-17 05:50 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-174.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: f22fcd56aaf8cca8805fcf3cc492989479058364
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-17_05-50-52 19 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-17_05-50-52)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-17_05-50-32.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-17_05-50-32.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-17_05-50-52
time logs started
Prep time   :    19 sec (00:00:19)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    19 sec (00:00:19)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/6b91dade6bb90fb8dd9fb9a15d4c7715)
Build log [Build log](https://gist.github.com/HPCCSmoketest/6b91dade6bb90fb8dd9fb9a15d4c7715#file-result-22-06-17-05-50-18-log)

```

2022-06-17 05:58 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 3dc0f40f13199a7174b4831e6db586efe6723e4a
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-166.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-17 05:58 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-166.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 3dc0f40f13199a7174b4831e6db586efe6723e4a
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-17_05-58-47 12 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-17_05-58-47)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-17_05-58-34.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-17_05-58-34.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-17_05-58-47
time logs started
Prep time   :    12 sec (00:00:12)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    12 sec (00:00:12)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/4c3b093bff9ad098d495350727f3df5b)
Build log [Build log](https://gist.github.com/HPCCSmoketest/4c3b093bff9ad098d495350727f3df5b#file-result-22-06-17-05-58-19-log)

```

2022-06-17 06:10 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 4346ebf8b1ea92881fb17ec2d668731bcc36dad6
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-47.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-17 06:10 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-47.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 4346ebf8b1ea92881fb17ec2d668731bcc36dad6
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-17_06-10-44 9 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-17_06-10-44)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-17_06-10-34.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-17_06-10-34.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-17_06-10-44
time logs started
Prep time   :     9 sec (00:00:09)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :     9 sec (00:00:09)
time logs end


 ... ( comment is too long, 68 lines, 2993 bytes, truncated) ... 
[Build error:](https://gist.github.com/b796503397b9fd8b954ac84958a96a96)
Build log [Build log](https://gist.github.com/HPCCSmoketest/b796503397b9fd8b954ac84958a96a96#file-result-22-06-17-06-10-19-log)

```

2022-06-17 06:18 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: b049e115f97d5a6c31d320638e0dd765561f1f28
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-142.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-17 06:18 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-142.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: b049e115f97d5a6c31d320638e0dd765561f1f28
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-17_06-18-51 18 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-17_06-18-51)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-17_06-18-32.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-17_06-18-32.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-17_06-18-51
time logs started
Prep time   :    18 sec (00:00:18)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    18 sec (00:00:18)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/c82e2f610c4381484c14be6ca23e72e1)
Build log [Build log](https://gist.github.com/HPCCSmoketest/c82e2f610c4381484c14be6ca23e72e1#file-result-22-06-17-06-18-17-log)

```

2022-06-17 06:35 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: New commit.
Commit ID: 75340403bde90094c2b628d62752f6845bd5d458
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-12.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-17 06:35 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-12.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 75340403bde90094c2b628d62752f6845bd5d458
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-17_06-35-55 21 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-17_06-35-55)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-17_06-35-33.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-17_06-35-33.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-17_06-35-55
time logs started
Prep time   :    21 sec (00:00:21)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    21 sec (00:00:21)
time logs end


 ... ( comment is too long, 68 lines, 2994 bytes, truncated) ... 
[Build error:](https://gist.github.com/9235154e5f4870a299c381e5e81f49f3)
Build log [Build log](https://gist.github.com/HPCCSmoketest/9235154e5f4870a299c381e5e81f49f3#file-result-22-06-17-06-35-18-log)

```

2022-06-17 07:47 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 39b27ac79166a2fe98bedbcff2bcc616ef004ee1
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-206.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-17 07:47 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-206.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 39b27ac79166a2fe98bedbcff2bcc616ef004ee1
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-17_07-47-54 19 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-17_07-47-54)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-17_07-47-34.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-17_07-47-34.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-17_07-47-54
time logs started
Prep time   :    19 sec (00:00:19)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    19 sec (00:00:19)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/12b37211acb9d6cca440334dc23b2159)
Build log [Build log](https://gist.github.com/HPCCSmoketest/12b37211acb9d6cca440334dc23b2159#file-result-22-06-17-07-47-19-log)

```

2022-06-17 08:51 UTC, HPCCSmoketest commented
Process of PR-16168, label: DROP_H3 starts now.
The reason of this test is: Forced to re-test.
Commit ID: 61b51c00d272e45547839a0d914fa0c4316bdf0e
Estimated completion time is 0.75 hour(s)
centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-170.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Build only for containerized environment.
VCPKG build disabled.

2022-06-17 08:51 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
OS: centos 7.6.1810 (Linux 3.10.0-957.1.3.el7.x86_64)
 Host: ip-10-22-254-170.ec2.internal
 GCC:  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
 Git: 2.9.5,  CMake: 3.22.1,  cUrl: 7.67.0,  node.js: v16.13.1,  npm: 8.1.2
Sha: 61b51c00d272e45547839a0d914fa0c4316bdf0e
Containerized: True
VCPKG build disabled.
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
  Could not find a package configuration file provided by h3 with any of
  the following names:
    h3Config.cmake
    h3-config.cmake
  Add the installation prefix of h3 to CMAKE_PREFIX_PATH or set h3_DIR to
  a directory containing one of the above files.  If h3 provides a separate
  development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeOutput.log.
See also /home/centos/smoketest/PR-16168/build/CMakeFiles/CMakeError.log.
We keep the source and build files only
so, uninstall HPCC...
HPCC Uninstall: failed (Missing complete-uninstall.sh file.)
Remove Cassandra leftovers.
To remove hpccsystems-platform* success
Makefiles created (2022-06-17_08-51-50 15 sec )
Keep ECLWatch build as is.
Milestone:Build it
cmd: make -j 32 (2022-06-17_08-51-50)
make: *** No targets specified and no makefile found.  Stop.
res: On branch DROP_H3-smoketest
Changes not staged for commit:
 (use git add <file>... to update what will be committed)
 (use git checkout -- <file>... to discard changes in working directory)
\tmodified: cmake_modules/buildBOOST_REGEX.cmake
\tmodified: plugins/cassandra/CMakeLists.txt
\tmodified: plugins/couchbase/CMakeLists.txt
\tmodified: plugins/redis/CMakeLists.txt
\tmodified: system/aws/CMakeLists.txt
\tmodified: system/azure/CMakeLists.txt
Untracked files:
 (use git add <file>... to include in what will be committed)
\tplugins/h3/uber-h3/
no changes added to commit (use git add and/or git commit -a)
Number of Error(s): 2
CMake Error at plugins/h3/CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
CMakeFiles/CMakeOutput.log copied into ../CMakeOutput-2022-06-17_08-51-34.log
CMakeFiles/CMakeError.log copied into ../CMakeError-2022-06-17_08-51-34.log
Get ECLWatch build result
ReportTimes.
Finish at: 2022-06-17_08-51-50
time logs started
Prep time   :    15 sec (00:00:15)
Build time  :     0 sec (00:00:00)
Package time:     0 sec (00:00:00)
Install time:     0 sec (00:00:00)
Start time  :     0 sec (00:00:00)
Test time   :     0 sec (00:00:00)
Stop time   :     0 sec (00:00:00)
Summary     :    15 sec (00:00:15)
time logs end


 ... ( comment is too long, 68 lines, 2995 bytes, truncated) ... 
[Build error:](https://gist.github.com/e3fa1f7270ea722c68ed74b44078aec5)
Build log [Build log](https://gist.github.com/HPCCSmoketest/e3fa1f7270ea722c68ed74b44078aec5#file-result-22-06-17-08-51-19-log)

```

2022-06-17 10:02 UTC, GordonSmith commented
@richardkchapman @jakesmith - this is (finally) ready for review.

2022-06-17 10:11 UTC, GordonSmith commented on dockerfiles/platform-build/Dockerfile
> +
@richardkchapman the above should really be in platform-build-base

2022-06-20 10:47 UTC, GordonSmith commented
@richardkchapman @jakesmith - this is ready for review.

2022-06-21 17:04 UTC, jakesmith reviewed
@GordonSmith - a few minor comments

2022-06-21 17:06 UTC, jakesmith commented
@GordonSmith - this PR appear more to do with refactoring the actions to use vcpkg and to target centos7, than "Remove H3 submodule" - can the H3 bit be split off / this retitled ?

2022-06-22 14:00 UTC, jakesmith commented
>GordonSmith requested review from Michael-Gardner and jakesmith 10 minutes ago

@GordonSmith , actually, maybe you refreshed [my] review state unintentionally? because other prev. review comments not seen/responded to?

2022-06-22 14:05 UTC, GordonSmith commented
@jakesmith - yes, saw your comment after I clicked refresh - change is incomming.

2022-06-22 14:10 UTC, GordonSmith commented on .github/workflows/smoketest.yml
> +      shell: "bash"
Good to know - FWIW its not default in Windows runners (which is where this got copied from)

2022-06-22 14:12 UTC, GordonSmith commented on .github/workflows/smoketest.yml
> +          -storepasswordincleartext \
Also I think this specific token is only valid for the duration of the run, so will be invalid if it did end up in the artifact.

2022-06-22 14:29 UTC, GordonSmith commented on dockerfiles/platform-build-incremental-container/Dockerfile
> +
I have updated the cache id to:  "platform_build::smoketest-platform-build-vcpkg" so they won't clash while we are migrating - which now means the above is not needed (I will remove and test)?

2022-06-22 14:36 UTC, GordonSmith commented
@jakesmith - now its ready for re-review!

2022-06-22 15:43 UTC, GordonSmith commented
@jakesmith @Michael-Gardner @richardkchapman - I have removed the H3 part of this PR and changed Jira reference / commit comment

2022-06-24 10:06 UTC, jakesmith reviewed
@GordonSmith - please see comments

2022-06-24 10:06 UTC, jakesmith commented on .github/workflows/build-vcpkg.yml
> +      - name: CentOS-7 image
minor: as this is a matrix of OS's flavour (which happens to only have 1 element in it at the moment), this step should really have a generic name.

2022-06-24 11:35 UTC, GordonSmith commented on .github/workflows/build-vcpkg.yml
> +            cmake_build_options: "--config Debug -j2 -- -m"
-j passed to cmake is "parallel jobs":
* For underlying make builds, its the same as `-- -j`
* For MSBuild it means how many "vcproj" projects are run in parallel, while the `-m` enables parallel c++ compiles

2022-06-24 11:37 UTC, GordonSmith commented on .github/workflows/build-vcpkg.yml
> +            -username "${{ github.actor }}" \
No - to fetch "public" nuget packages the requestor must be authenticated and the auth token is on behalf of the actor and not the owner of the target PR.

2022-06-24 11:41 UTC, GordonSmith commented on .github/workflows/smoketest.yml
> +          -username "hpcc-systems" \
Actually should be `github.actor` will change.

2022-06-24 11:49 UTC, GordonSmith commented on .github/workflows/build-vcpkg.yml
> +            cmake_build_options: "--config Debug -j2 -- -m"
Was using Debug here as its quicker - the Docker images are release to lower the size?

2022-06-24 14:53 UTC, jakesmith commented
@GordonSmith squashing changes between reviews makes it a little more difficult to follow up/re-review/see what's change since last-review. Can you leave unsquashed until end?

2022-06-24 15:14 UTC, jakesmith approved these changes
@GordonSmith - approving, but still think should use Release mode consistently (see comment)

2022-06-24 15:31 UTC, jakesmith approved these changes
@GordonSmith - looks good to me.

As new commit was for my review benefit, I'm happy for it to be squashed in now

2022-06-27 17:03 UTC, GordonSmith commented on dockerfiles/platform-build-centos-7/Dockerfile
> +    -DUSE_CPPUNIT=${USE_CPPUNIT}"
Check if this matches the latest Ubuntu variant

2022-06-27 17:05 UTC, GordonSmith commented on dockerfiles/platform-build/Dockerfile
> +ENV VCPKG_BINARY_SOURCES="clear;nuget,GitHub,readwrite"
Should be read-only for consistency (it can't write without the setapi nuget call anyway)

2022-06-27 17:11 UTC, GordonSmith commented on dockerfiles/platform-build-centos-7/Dockerfile
> +ARG BUILD_TYPE=RelWithDebInfo
It is Release in the GH Action call

2022-06-27 17:14 UTC, GordonSmith commented on dockerfiles/platform-build-centos-7/Dockerfile
> +    -DUSE_CPPUNIT=${USE_CPPUNIT}"
No changes needed.

2022-06-27 17:16 UTC, GordonSmith commented on dockerfiles/platform-build/Dockerfile
> +ENV VCPKG_BINARY_SOURCES="clear;nuget,GitHub,readwrite"
Fixed.

2022-06-28 14:50 UTC, Michael-Gardner approved these changes
Gordon this work is looking great.  I checked the output against what we're getting in our jenkins builds. Biggest difference of course is that this build is generating several plugins that our baremetal community build won't include (they're generated separately and packaged individually).  I took the dockerfile and added a make package to it, then copied the final artifact out and was digging through it as a sanity check to see if anything would be missing from the build. Nothing stood out.

2022-06-29 08:58 UTC, jakesmith commented
@GordonSmith - Did something change? The ubuntu22.04 and macos-12 tests are now failing - I thought all passed before.

```
2022-06-29T07:43:30.9548790Z /home/runner/work/HPCC-Platform/HPCC-Platform/system/azure/azure-storage-cpplite/src/hash.cpp: In function ‘std::string azure::storage_lite::hash(const string&, const std::vector<unsigned char>&)’:
2022-06-29T07:43:30.9550226Z /home/runner/work/HPCC-Platform/HPCC-Platform/system/azure/azure-storage-cpplite/src/hash.cpp:54:38: error: ‘HMAC_CTX* HMAC_CTX_new()’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
2022-06-29T07:43:30.9550923Z    54 |         HMAC_CTX * ctx = HMAC_CTX_new();
2022-06-29T07:43:30.9551247Z       |                          ~~~~~~~~~~~~^~
```

2022-06-29 10:22 UTC, GordonSmith commented
@jakesmith fixed couchbase build issue in smoketest (and centos)

2022-06-29 10:23 UTC, GordonSmith commented
@jakesmith OSX 12 and 22.04 are known to be failing (there are open issues for them)

2022-06-29 14:40 UTC, GordonSmith commented
@ghalliday rebased

2022-06-29 15:02 UTC, jakesmith approved these changes
@GordonSmith - looks good afaics

2022-06-29 15:13 UTC, GordonSmith commented
@ghalliday squashed

2022-07-01 08:26 UTC, merged