HPCC-27646 Create theme editor
hpcc-systems/HPCC-Platform pull request #16221
Opened 2022-06-17 14:22 UTC by jeclrsg

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-06-21 12:40 UTC, GordonSmith requested changes

2022-06-21 12:40 UTC, GordonSmith commented on esp/src/src-react/hooks/theme.ts
> +    }, [setBackgroundColor, setTextColor, themeDark]);
Lint issues

2022-06-22 06:38 UTC, GordonSmith requested changes

2022-06-22 06:38 UTC, GordonSmith commented on esp/src/src-react/components/ThemeEditor.tsx
> +    const _onTextFieldValueChange = (ev: any, newValue: string | undefined) => {
Should be a React.callback?

2022-06-22 06:38 UTC, GordonSmith commented on esp/src/src-react/hooks/theme.ts
> +    }, [setBackgroundColor, setTextColor, themeDark]); // eslint-disable-line react-hooks/exhaustive-deps
So the user never gets to set the actual text color?

2022-08-02 18:15 UTC, jeclrsg commented
@GordonSmith I rebased to 8.8.x & fixed some merge conflicts in .../hooks/theme.ts. The color selection controls still work as expected. It doesn't update the v9 theme however. Should I update this PR to do so, or just worry about it whenever we start using any v9 components?

2022-08-04 13:12 UTC, GordonSmith approved these changes
@jeclrsg - I suspect this is going to need a global get/setter with broadcast capability?  Happy to pull and add if needed.

2022-09-23 10:37 UTC, ghalliday commented
@jeclrsg @GordonSmith this seems to have stalled/need rebasing.

2022-11-23 12:02 UTC, ghalliday commented
@jeclrsg @GordonSmith either needs rebasing, or closing because it is stale.

2022-11-23 14:20 UTC, closed without merging