HPCC-27893 Create Data Pattern Bundle Chapter
hpcc-systems/HPCC-Platform pull request #16447
Opened 2022-08-05 13:43 UTC by amy88ma

Signed-off-by: Amy Ma <MaAmy001@risk.regn.net>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-08-16 14:06 UTC, dcamper requested changes

2022-08-16 14:06 UTC, dcamper commented on docs/EN_US/DataPatterns/DataPatternsMods/DataPatternsBundle.xml
> +        <listitem>
Shouldn't this section be moved to after the ECL IDE installation section, because it is applicable to all IDEs?

2022-08-16 14:06 UTC, dcamper commented on docs/EN_US/DataPatterns/DataPatternsMods/DataPatternsBundle.xml
> +    to the Profile method in the Standard Library. See ___: </emphasis></para>
Update ___ ?

2022-08-16 14:06 UTC, dcamper commented on docs/EN_US/DataPatterns/DataPatternsMods/DataPatternsBundle.xml
> +    <para>NORMALIZEPROFILERESULTS accepts only one argument: the dataset
Maybe camelcase that function name:  NormalizeProfileResults()

2022-08-16 14:06 UTC, dcamper commented on docs/EN_US/DataPatterns/DataPatternsMods/DataPatternsBundle.xml
> +    representing the result of a call to either PROFILE. The result is a
Remove 'either'

2022-08-16 14:06 UTC, dcamper commented on docs/EN_US/DataPatterns/DataPatternsMods/DataPatternsBundle.xml
> +    See ___: </emphasis></para>
Update ___ ?

2022-08-16 14:08 UTC, dcamper commented
Function names are stylized differently in the document.  In some places Profile() is used, while in others it is PROFILE().  I recommend normalizing on one form of the other.

2022-08-29 11:45 UTC, dcamper commented
Only one of the issues I raised previous;ly has been addressed.  What of the others?

2022-09-21 15:07 UTC, JamesDeFabia approved these changes

2022-09-22 12:21 UTC, merged