HPCC-27862 Add Logging Analytics details to Doc
hpcc-systems/HPCC-Platform pull request #16475
Opened 2022-08-19 16:21 UTC by g-pan

Signed-off-by: g-pan <greg.panagiotatos@lexisnexis.com>
Note: Composed PDF File can be viewed: 
http://10.224.20.18/view/Docs-gp/job/Doc-Build-04-GPRepo2/lastSuccessfulBuild/artifact/build-docs/Release/docs/EN_US/Containerized_HPCC_Systems_Platform_EN_US-8.8.0-closedown0.pdf#page=52

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Successful Unit Testing completed on Region 8 Jenkins system: http://10.224.20.18/view/Docs-gp/job/Doc-Build-04-GPRepo2/

2022-08-19 16:53 UTC, rpastrana commented
@g-pan  looks good. this sentence isn't 100% clear to me, specially because it doesn't provide the script name, but also because it's not clear that the user should populate the values in the accompanying env-loganalytics file.

The script located at  https://github.com/hpcc-systems/HPCC-Platform/tree/master/helm/examples/azure/log-analyt-ics requires populating a few values in the env-loganalytics environment file.

2022-08-24 15:45 UTC, rpastrana approved these changes
It's difficult to discern the code review change since it was squashed, but it seems fine.

2022-08-24 16:14 UTC, JamesDeFabia requested changes
Couple of minor comments inline

2022-08-24 16:14 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ContainerLogging.xml
> +      <para>Enabling Azure's Log Analytics (ALA) on the target AKS cluster can
Enable Azure's Log Analytics (ALA) on the target AKS cluster using one of the following options:

2022-08-24 16:14 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ContainerLogging.xml
> +            associated with target AKS cluster. A new workspace will be
A new workspace is created if this value does not exist

2022-08-25 18:50 UTC, JamesDeFabia approved these changes
Good from my POV

2022-08-26 17:26 UTC, g-pan commented
good to merge

2022-09-09 07:58 UTC, merged