HPCC-28280 Revise and Rename the More Helm and Yaml section
hpcc-systems/HPCC-Platform pull request #16584
Opened 2022-09-28 17:33 UTC by g-pan

Signed-off-by: g-pan <greg.panagiotatos@lexisnexis.com>
No new content, just revising what was already there. 

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Successful Unit/Build tests: http://10.224.20.18/view/Docs-gp/job/DocBuild-01-GPRepo

2022-09-28 18:34 UTC, JamesDeFabia requested changes
Couple of minor comments inline

2022-09-28 18:34 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
>          <para>Having multiple yaml files, such as one for logging, another for
consistency: YAML is used elsewhere

2022-09-28 18:34 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +        <para>The rule here to keep in mind where multiple yaml files are
consistency: YAML is uses elsewhere

2022-09-28 18:45 UTC, JamesDeFabia approved these changes
Good from my POV

2022-10-03 11:35 UTC, jakesmith commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +      referred to as a hash or a dictionary. The key-value pair construct
trivial/not new: if you're going to mention "hash", it should really say "hash table", though I'd be inclined not to mention it at all and only say "sometimes referred to as a dictionary" ( "hash table" is more commonly used to describe the implementation )

2022-10-03 11:54 UTC, jakesmith commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +        <para>A key is denoted using the hyphen, which is an entry item in the
minor/not new: I think the use of the word "key" here is misleading, there is no key field of a list entry.. there is only an order of entries, the hyphen signifies the start of the next entry in the list.
It's an unfortunate example that the list is a dictionary with the a key field called "key" in the above example..
A list doesn't have to be a list of dictionaries, e.g.:
```
mylist: [ 1, 2, 3 ]
```
which is equivalent to:
```
mylist:
- 1
- 2
- 3
```

2022-10-03 12:00 UTC, jakesmith approved these changes
@g-pan - a couple of comments, but they're minor and not new, so approving (but you might want to address them in this PR).

2022-10-03 19:38 UTC, JamesDeFabia requested changes
Comments inline

2022-10-04 13:01 UTC, JamesDeFabia requested changes
Comments inline

2022-10-04 13:32 UTC, g-pan commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +        configuration.. These configuration files can all be under version
good catch

2022-10-05 14:30 UTC, jakesmith reviewed
One rewording suggestion.

2022-10-05 18:11 UTC, g-pan commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +        have to be a list of dictionaries, which may in turn also have list
Thank you Jake, that is a very helpful suggestion to clarify that statement.

2022-10-05 18:25 UTC, jakesmith commented
@g-pan - looks good

2022-10-05 19:48 UTC, JamesDeFabia approved these changes
Looks good

2022-10-06 08:51 UTC, merged