HPCC-28507 Display file min and max skews as percentages
hpcc-systems/HPCC-Platform pull request #16687
Opened 2022-11-09 21:14 UTC by jeclrsg

Signed-off-by: Jeremy Clements <Jeremy.Clements@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2022-11-10 10:53 UTC, GordonSmith requested changes

2022-11-10 10:53 UTC, GordonSmith commented on esp/src/eclwatch/LFDetailsWidget.js
> +                var formatNum = hpccCommon.format(",.2f");
formatNum declaration should be moved to module scope or the Util module as "skewFormat"?

2022-11-10 10:53 UTC, GordonSmith commented on esp/src/eclwatch/DFUQueryWidget.js
> +            var formatNum = hpccCommon.format(",.2f");
formatNum declaration should be moved to module scope or the Util module as "skewFormat"?

2022-11-10 10:53 UTC, GordonSmith commented on esp/src/src/Session.ts
> +export const formatNum = format;
Could be in a module that is accessible from Dojo and React?

2022-11-11 07:11 UTC, GordonSmith requested changes

2022-11-11 07:11 UTC, GordonSmith commented on esp/src/src/Utility.ts
> +    const format = d3Format(",.2f");
This should be moved into module scope

2022-11-14 12:23 UTC, GordonSmith requested changes

2022-11-14 12:23 UTC, GordonSmith commented on esp/src/eclwatch/DFUQueryWidget.js
> +                            return value ? "-" + Utility.formatDecimal(value / 100) + "%" : "";
I don't think we actually display the "-" anywhere else for skews?

2022-11-14 12:23 UTC, GordonSmith commented on esp/src/src-react/components/Files.tsx
> +                label: nlsHPCC.MinSkew, width: 60, formatter: React.useCallback((value, row) => value ? `-${Utility.formatDecimal(value / 100)}%` : "", [])
I don't think we want the "-"

2022-11-14 17:29 UTC, GordonSmith requested changes

2022-11-14 17:29 UTC, GordonSmith commented on esp/src/eclwatch/DFUQueryWidget.js
> +                            if (value.toString().indexOf(".") >= 0) {
value could be undefined?

2022-11-14 18:25 UTC, jeclrsg commented on esp/src/src-react/components/Files.tsx
> +                label: nlsHPCC.MinSkew, width: 60, formatter: React.useCallback((value, row) => value ? `${Utility.formatDecimal(value / 100)}%` : "", [])
There's that ternary there that should be handling that, returning ""

2022-11-15 11:57 UTC, GordonSmith requested changes

2022-11-15 11:57 UTC, GordonSmith commented on esp/src/eclwatch/DFUQueryWidget.js
> +                            if (value) {
Value could equal `0`

2022-11-15 11:57 UTC, GordonSmith commented on esp/src/eclwatch/DFUQueryWidget.js
> +                            if (value) {
Value could equal `0`

2022-11-15 15:49 UTC, GordonSmith approved these changes

2022-11-23 14:34 UTC, jeclrsg commented
rebased to fix a merge conflict

2023-01-06 13:08 UTC, GordonSmith commented
@ghalliday this is ready for pull

2023-01-18 12:11 UTC, merged