HPCC-28510 Pass sort param into LogicalFile detail tabs
hpcc-systems/HPCC-Platform pull request #16760
Opened 2022-12-02 16:29 UTC by jeclrsg

Signed-off-by: Jeremy Clements <Jeremy.Clements@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-01-06 13:44 UTC, GordonSmith requested changes

2023-01-06 13:44 UTC, GordonSmith commented on esp/src/src-react/components/FileDetailsGraph.tsx
> +            onClick: () => refreshTable()
Can you double check that this is fetching data from the server?

2023-01-06 13:44 UTC, GordonSmith commented on esp/src/src-react/components/FileHistory.tsx
> +            onClick: () => refreshTable()
Can you double check that this is fetching data from the server?

2023-01-06 13:44 UTC, GordonSmith commented on esp/src/src-react/components/FileParts.tsx
> +            onClick: () => refreshTable()
Can you double check that this is fetching data from the server?

2023-01-06 13:44 UTC, GordonSmith commented on esp/src/src-react/components/ProtectedBy.tsx
> +            onClick: () => refreshTable()
Can you double check that this is fetching data from the server?

2023-01-06 13:44 UTC, GordonSmith commented on esp/src/src-react/components/SuperFiles.tsx
> +            onClick: () => refreshTable()
Can you double check that this is fetching data from the server?

2023-01-10 14:02 UTC, GordonSmith approved these changes

2023-01-18 17:10 UTC, ghalliday approved these changes

2023-01-18 17:11 UTC, merged