HPCC-28624 Display additional details of indexes on detail page
hpcc-systems/HPCC-Platform pull request #16821
Opened 2023-01-09 15:37 UTC by jeclrsg

Signed-off-by: Jeremy Clements <Jeremy.Clements@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-01-09 15:58 UTC, jeclrsg commented
@GordonSmith NPM build step failed because of some missing properties in the WsDFU service in comms (https://github.com/hpcc-systems/Visualization/pull/4055). Will have to update the package files in here w/ the new version number.

2023-01-10 14:04 UTC, GordonSmith commented
@jeclrsg I will review once the upstream changes are available...

2023-01-23 10:25 UTC, ghalliday commented
@GordonSmith is this now possible to review?

2023-01-25 12:40 UTC, GordonSmith requested changes

2023-01-25 12:40 UTC, GordonSmith commented on esp/src/src-react/components/IndexFileSummary.tsx
> +            });
Error handling

2023-01-25 12:40 UTC, GordonSmith commented on esp/src/src-react/components/IndexFileSummary.tsx
> +                });
Error handling

2023-01-25 12:40 UTC, GordonSmith commented on esp/src/src/Utility.ts
> +        const x = intsize > 0 ? Math.floor(Math.log(intsize) / Math.log(1024)) : 0;
Should the `if` above just be a `isNaN`?

2023-01-31 10:51 UTC, GordonSmith approved these changes

2023-02-09 13:58 UTC, GordonSmith commented
@ghalliday this has been approved.

2023-02-09 17:41 UTC, ghalliday commented
I will merge this after the next set of rcs

2023-02-14 11:07 UTC, ghalliday approved these changes

2023-02-14 11:08 UTC, merged