HPCC-28811 Remove configuration logic related to SPARK-HPCC
hpcc-systems/HPCC-Platform pull request #16906
Opened 2023-01-27 20:02 UTC by kenrowland

Removed config files and other references to SPARK configuration

Signed-Off-By: Kenneth Rowland kenneth.rowland@lexisnexisrisk.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-01-27 22:57 UTC, rpastrana reviewed
@kenrowland Michael Gardner is a better reviewer for this change. Also, make sure this is not merged until the feature is removed.

2023-01-30 13:41 UTC, kenrowland commented
Michael added to review list

2023-01-30 14:31 UTC, Michael-Gardner requested changes
see comment about environment.xml.in variable

2023-01-30 14:31 UTC, Michael-Gardner commented on initfiles/etc/DIR_NAME/environment.xml.in
> -  @SPARK_ENV_S@
This variable is coming from initfiles/etc/DIR_NAME/CMakeLists.txt around line 20-26?

Should remove that block as part of this PR. 

Also remove @DNG_SPARKTHOR@ from initfiles/etc/DIR_NAME/genenvrules.conf.in at the end of line 4

2023-01-30 16:28 UTC, kenrowland commented
@Michael-Gardner How about the spark reference in initfiles/bash/etc/systemd/system/thorslave@instance.service.in,
or is that beyond the scope of this Jira?

2023-01-30 20:59 UTC, Michael-Gardner commented
@kenrowland I think that's beyond the scope. I'll go ahead and clean up files like that after your PR is done. Lets just keep your PR targeted towards the environment and configuration files.

2023-02-21 16:06 UTC, Michael-Gardner approved these changes
Looks great now. Thanks for the change @kenrowland

2023-02-21 16:06 UTC, Michael-Gardner commented on initfiles/etc/DIR_NAME/environment.xml.in
> -  @SPARK_ENV_S@
Perfect thanks.

2023-02-21 16:08 UTC, kenrowland commented
@ghalliday Please merge

2023-02-21 21:13 UTC, rpastrana reviewed
@kenrowland I have to input on this change, @Michael-Gardner is the expert in this area and his approval should suffice

2023-02-23 15:33 UTC, kenrowland commented
@ghalliday Not sure how to officially mark it as such, but this PR should only be merged when the feature is fully removed. There is no more work for this PR and it is ready for merge when the rest of the work is complete.

2023-02-27 09:05 UTC, ghalliday commented
@kenrowland please squash.  Also, what is stopping this from being merged?  If it is dependent on something else what are the jira numbers?

2023-02-27 13:37 UTC, kenrowland commented
@ghalliday rebased. This is a sub-task of HPCC-28520 "Sunset integrated SPARK feature". Per comments from @rpastrana earlier in this PR, these changes should not  be merged until the feature is removed. There are still several open sub tasks on the parent Jira, so I wanted to make sure it wasn't merged before it should be.

2023-03-07 15:42 UTC, merged