HPCC-28771 Add masking XPath extension functions
hpcc-systems/HPCC-Platform pull request #17004
Opened 2023-02-24 02:44 UTC by timothyklemm

- maskValue(value, valueType)
- maskValue(value, valueType, maskStyle)
- maskContent(content)
- maskContent(content, contentType)

Signed-off-by: Tim Klemm <tim.klemm@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-02-24 21:16 UTC, afishbeck approved these changes

2023-03-02 22:34 UTC, asselitx requested changes

2023-03-06 12:48 UTC, timothyklemm commented on esp/esdllib/docs/maskContent.md
> +Managing selected rules is handled by manipulating the **rule-set** custom profile property. Valid values for the property include "" (the empty string) and other masking profile-defined identifiers
https://track.hpccsystems.com/browse/HPCC-29109

2023-03-07 03:21 UTC, asselitx approved these changes

2023-03-07 13:02 UTC, timothyklemm commented
@ghalliday this extends HPCC-28770. I'll rebase after https://github.com/hpcc-systems/HPCC-Platform/pull/17003 is merged.

2023-03-10 14:56 UTC, timothyklemm commented
@ghalliday this has been rebased and squashed. It's ready to merge.

2023-03-14 13:54 UTC, merged