HPCC-29098 Support / in multi-line string at end of line on windows
hpcc-systems/HPCC-Platform pull request #17044
Opened 2023-03-03 14:30 UTC by ghalliday

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-03-07 09:52 UTC, shamser reviewed
Please can you clarify line 2184-2186.

2023-03-07 09:52 UTC, shamser commented on ecl/hql/hqlparse.cpp
> +                StringBuffer msg("Can not terminate a string with escape char '\\': ");
Isn't \ a line joiner rather than escape character?  Also, how do you know that you are at the end of the string here?

2023-03-07 10:22 UTC, richardkchapman requested changes
This feels like the wrong fix to me - suggests the "dossiness" of the source file has an impact on its meaning which doesn't feel desirable. Perhaps something to discuss?

2023-03-07 10:22 UTC, richardkchapman commented on ecl/hql/hqlparse.cpp
> +                    continue;
Does this continue do anything?

2023-03-07 10:22 UTC, richardkchapman commented on ecl/hql/hqlparse.cpp
> +                    continue;
Or this one?

2023-03-07 10:22 UTC, richardkchapman commented on ecl/hql/hqlparse.cpp
> +            else if (next == '\r')
Feels like something bigger is wrong if a multiline string literal from a Windows source file has a different contents than from a non-windows one. Isn't a more correct fix to have translate \r\n to \n earlier?

2023-03-30 12:23 UTC, ghalliday commented
@richardkchapman what do you think about these changes?

2023-03-30 12:44 UTC, richardkchapman approved these changes
Looks good - one minor quibble is that the function "stripSlashNewline" now does a little more than just what its name suggests.

2023-04-03 13:45 UTC, shamser approved these changes

2023-04-06 12:38 UTC, merged