HPCC-29139 LDAP socket connections may need additional code to set ke…
hpcc-systems/HPCC-Platform pull request #17093
Opened 2023-03-10 15:57 UTC by RussWhitehead

…epalive

Query config for keepAlive options, set them in LDAP when it is initialized

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-03-10 18:27 UTC, mckellyln requested changes

2023-03-10 18:27 UTC, mckellyln commented on system/security/LdapSecurity/ldaputils.cpp
> +
I think all this should be done both if ldaps or just ldap, so not in this if (stricmp(ldaps)) block but before or after.  And probably also ok if _WIN32.

2023-03-11 18:07 UTC, mckellyln reviewed
Just have a question about where we need to set the options.

2023-03-11 18:07 UTC, mckellyln commented on system/security/LdapSecurity/ldaputils.cpp
> +
Do you have to call all the ldap_set_option()s before calling LDAP_INIT() ?

2023-03-13 13:17 UTC, mckellyln commented on system/security/LdapSecurity/ldaputils.cpp
> +        DBGLOG("queryKeepAlive returns time=%d, intvl=%d, probes=%d", kaTime, kaInterval, kaProbes);
skip DBGLOG ?  Perhaps change it to only log one line if any of the keepalive settings are made ?

2023-03-13 13:20 UTC, mckellyln requested changes
Just one change - to log keepalive settings a little differently, only log if any of them are not -1, so perhaps build up a string of what was changed and then log it as a single line.

2023-03-13 13:42 UTC, mckellyln commented on system/security/LdapSecurity/ldaputils.cpp
> +                ERRLOG("LdapUtils::LdapInit : ldap_set_option(LDAP_OPT_X_KEEPALIVE_PROBES, %d) error - %s", kaProbes, ldap_err2string(rc));
if (kaTime != -1 || kaInterval != -1 || kaProbes != -1)
    {
        StringBuffer kaLogStr;
        if (kaTime != -1)
            kaLogStr.appendf(" time: %d", kaTime);
        if (kaInterval != -1)
            kaLogStr.appendf(" interval: %d", kaInterval);
        if (kaProbes != -1)
            kaLogStr.appendf(" probes: %d", kaProbes);
        DBGLOG("LDAP tcp keepalive%s", StringBuffer.str());
    }

2023-03-13 14:13 UTC, mckellyln commented on system/security/LdapSecurity/ldaputils.cpp
> +            DBGLOG("queryKeepAlive returns time=%d, intvl=%d, probes=%d", kaTime, kaInterval, kaProbes);
ok, but "queryKeepAlive" maybe should be "LDAP tcp keepalive settings:" or something.  I was thinking more like:
```
StringBuffer kaLogStr;

rc = ldap_set_option()
if (rc != LDAP_SUCCESS)
     ERRLOG()
else
     kaLogStr.appendf(" time: %d", kaTime);
```
then at the end of the block:
```
if (!kaLogStr.isEmpty())
    DBGLOG("LDAP tcp keepalive%s", kaLogStr.str());
```

2023-03-13 16:35 UTC, mckellyln approved these changes
Looks good.

2023-03-14 12:27 UTC, ghalliday approved these changes

2023-03-14 12:27 UTC, merged