HPCC-29199 Remove SCMInterface only ECM files
hpcc-systems/HPCC-Platform pull request #17202
Opened 2023-04-04 16:53 UTC by kenrowland

Removed SCMInterface only ECM files.
Created hpp files for defined interfaces and added to source tree Updated CMake files to reflect newly added hpp interface files

Signed-Off-By: Kenneth Rowland kenneth.rowland@lexisnexisrisk.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-04-05 23:28 UTC, afishbeck commented on esp/bindings/soapesp.hpp
> +
Trivial but doesn't really need 2 blank lines.?.  I'll approve as is though.

2023-04-05 23:29 UTC, afishbeck approved these changes

2023-04-06 11:33 UTC, ghalliday requested changes
One test is failing for a related reason - not sure exactly why though.

2023-04-06 12:32 UTC, kenrowland commented
@ghalliday @afishbeck @AttilaVamos 

The test that is failing appears to not be a completely clean build. Inspection of the output shows the following as an example of an error generated during the build

/hpcc-dev/build/generated/esp.hpp:627:11: note: previous definition of 'struct IEspNgServiceBinding'

Note that the duplicate symbol is in the 'generated' directory. This PR has removed the ECM file that generates the referenced header file (esp.hpp in the example above).

Who is responsible for the "Docker smoketest build / build-images (pull_request)" build?

2023-04-07 13:31 UTC, kenrowland commented
https://track.hpccsystems.com/browse/HPCC-29351 created to fix the Smoketest build failure

2023-04-19 13:26 UTC, kenrowland commented
@GordonSmith I can confirm that I can create an image with ./dockerfiles/incr.sh locally

2023-04-26 16:07 UTC, ghalliday approved these changes

2023-04-26 16:09 UTC, merged