HPCC-29382 Add tips for writing dev docs
hpcc-systems/HPCC-Platform pull request #17243
Opened 2023-04-13 10:36 UTC by GordonSmith

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-04-13 17:36 UTC, GordonSmith commented on devdoc/DevDocs.md
> +npm install
No - the -D simply adds the reference inside package.json (where it is already).

2023-04-13 17:40 UTC, GordonSmith commented on devdoc/DevDocs.md
> +To add a new document, you need to add a new markdown file to the repository.  The file should be named appropriatly and have the `.md` file extension.  Once the file exists, you can view it by navig
Good to know about 5173.

The vitepress local server is only used when your writing docs and want to see what they look like locally.  For releasing it does a single build of all the docs and creates static html pages which GitHub hosts so no VitePress server is needed.

There are no advantages either way, so grouping docs by folders would make sense.

2023-04-13 18:21 UTC, stuartort commented
Looks good

2023-04-14 10:24 UTC, GordonSmith commented
@stuartort I tweaked the text around the port number.

2023-04-14 12:43 UTC, stuartort approved these changes

2023-04-17 11:01 UTC, ghalliday requested changes
A few minor typos etc.

Also note, I think the links in `<root>.README.md` still refer to the rst files.

2023-04-17 11:01 UTC, ghalliday commented on devdoc/README.md
>  -   [ECL style guide](/ecllibrary/StyleGuide): Style guide for ECL code.
StyleGuide.md (and other .md files need the extension).

2023-04-18 09:54 UTC, GordonSmith commented
@ghalliday bump

2023-04-19 09:19 UTC, ghalliday commented
@GordonSmith will merge, but note root README.md still has broken links to rst files.

2023-04-19 09:19 UTC, ghalliday approved these changes

2023-04-19 09:20 UTC, merged