HPCC-29370 Revise validateDropZonePath() and related code
hpcc-systems/HPCC-Platform pull request #17311
Opened 2023-05-05 14:14 UTC by wangkx

1. Add findDropZonePlaneWithName();
2. Rename the validateDropZonePath to validateDropZoneHostAndPath.
3. Call the findDropZonePlaneWithName in validateDropZoneHostAndPath.
4. Revise validateDropZonePath related code in downloadFile(), onStartUpload(), and onFileList().

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-05-19 11:10 UTC, jakesmith requested changes
@wangkx - looks a lot cleaner, but see comment re. splitting findDropZonePlane / adding a validateDropZone

2023-05-19 11:10 UTC, jakesmith commented on esp/smc/SMCLib/TpCommon.cpp
> +    Owned<IPropertyTree> plane = findDropZonePlaneWithName(dropZoneName, path, hostToCheck, isIPAddress(hostToCheck), false);
not keen on adding this (backward compatibility) functionality at a lower level.
I think this code should be:
```
    if (isEmptyString(dropZoneName))
    {
        Owned<IPropertyTree> plane = findDropZonePlane(path, hostToCheck, isIPAddress(hostToCheck), false);
        return nullptr != plane;
    }
    else
    {
        Owned<IPropertyTree> plane = getDropZonePlane(dropZoneName);
        if (nullptr == plane)
            return false;
        return validateDropZone(plane, path, hostToCheck, isIPAddress(hostToCheck));
    }
```

With validateDropZone being a new function in dautils.hpp which is code extracted out of the existing findDropZonePlane, so it calls it, and here calls it.

2023-05-19 11:11 UTC, jakesmith commented
@wangkx - also, should retarget this against 9.2/master

2023-05-22 17:12 UTC, wangkx commented
@jakesmith Please review.

2023-05-23 16:02 UTC, jakesmith approved these changes
@wangkx - looks good, please squash.

2023-05-23 19:03 UTC, wangkx commented
@ghalliday please merge this PR.

2023-05-23 21:17 UTC, afishbeck reviewed
@wangkx one comment when checking for OS_WINDOWS.

2023-05-23 21:17 UTC, afishbeck commented on esp/services/ws_fs/ws_fsBinding.cpp
> +        if (osStr.isEmpty() && (atoi(osStr.str())== OS_WINDOWS))
I think you mean "!osStr.isEmpty()"?  For the atoi the string shouldn't be empty.

2023-05-24 13:19 UTC, afishbeck approved these changes

2023-05-25 11:47 UTC, wangkx commented
@ghalliday please merge this PR.

2023-05-25 12:20 UTC, merged