HPCC-29523 Add sources to developer image
hpcc-systems/HPCC-Platform pull request #17333
Opened 2023-05-12 15:26 UTC by GordonSmith

When building developer images using "image.sh", a snapshot of the sources should be included

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-05-15 09:16 UTC, jakesmith commented on dockerfiles/image.sh
> +        docker exec --workdir /hpcc-dev/HPCC-Platform $CONTAINER /bin/bash -c "cp -r ../HPCC-Platform-local/.git ./.git"
minor: I know it's temporary, but .git (with history etc.) can be quite big/time consuming to copy.
I think you could instead copy everything with git archive like this:
```
cd ../HPCC-Platform-local
git archive --format=tar HEAD | tar xf - -C /hpcc-dev/HPCC-Platform
git submodule foreach --recursive 'git archive --format=tar HEAD | (cd /hpcc-dev/HPCC-Platform; mkdir -p $path; cd $path; tar xf -)'
```

2023-05-15 09:17 UTC, jakesmith approved these changes
@GordonSmith - looks good and works for me in testing.
approving, but 1 suggestion to potentially speed up the copy.

2023-05-17 09:32 UTC, jakesmith commented on dockerfiles/image.sh
> +        docker exec --workdir /hpcc-dev/HPCC-Platform-local $CONTAINER /bin/bash -c "git ls-files --modified --exclude-standard -z | xargs -0 -I {} cp {} /hpcc-dev/HPCC-Platform/"
this needs to be:
... cp {} /hpcc-dev/HPCC-Platform/{}

(it's currently copying changed files in to the roo of /hpcc-dev/HPCC-Platform)

2023-05-17 09:32 UTC, jakesmith requested changes
@GordonSmith - noticed 1 issue in testing.

2023-05-24 13:41 UTC, jakesmith reviewed
@GordonSmith - a couple of comments.

2023-05-24 13:41 UTC, jakesmith commented on dockerfiles/image.sh
> +    echo "--- Create 'platform-core:debug' image ---"
question: now unconditionally building platform-core:release and platform-core:debug ?
Isn't that time consuming/wasteful?

2023-05-31 14:03 UTC, jakesmith reviewed
as far as the image with sources/ability to debug looks good.

Might be unrelated, to these changes, building on my system, rebuilds and redownloads many packages (150+).

Discussing with @GordonSmith, it turned out to be related to the final step:
```
        finalize_platform_core_image $crc \
            "cmake --build /hpcc-dev/build --parallel --target install"
```

Gordon's suggested change of:

```
        finalize_platform_core_image $crc \
            "cmake --install /hpcc-dev/build --prefix /opt/HPCCSystems"
```

resolved the issue for me.

2023-05-31 16:38 UTC, GordonSmith commented
@jakesmith I added that one line change.

2023-05-31 16:40 UTC, jakesmith approved these changes

2023-05-31 16:41 UTC, jakesmith approved these changes
@GordonSmith - looks good to me, please squash.

2023-06-01 06:14 UTC, GordonSmith commented
@jakesmith @ghalliday squashed

2023-06-08 13:21 UTC, merged