HPCC-29541 Fix ZAP report postmortem directory structure
hpcc-systems/HPCC-Platform pull request #17345
Opened 2023-05-17 10:56 UTC by jakesmith

Ensure the postmortem directory structure is preserved in the ZAP report.
This prevents multiple component postmortem repots being folded and potentially overwriting each other in the report.

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-05-17 21:04 UTC, wangkx reviewed
@jakesmith should some changes be made in the ZAPReport Import function to match with the new directory structure in a ZAPReport? When importing a WU from a ZAP report, the existing ZAPReport Import function verifies the postmortem folder using ImportDIR + the Tail of the @filename in WU XML (see the updateWUQueryAssociatedFilesAttrs() in workunit.cpp). Now, the verification will not work because a subFolder is added between the ImportDIR and  the Tail.

2023-05-18 11:51 UTC, jakesmith commented on common/workunit/workunit.cpp
> +            fileName.set(di->query().queryFilename());
NB: this is an incidental change, but cleaner and relates to removal of a spurious extra PATHSEPCHAR in the unzipDir (removed in another change).

2023-05-18 11:51 UTC, jakesmith commented on common/workunit/workunit.cpp
> +            addPathSepChar(unzipDir).append(wuid.get());
NB: somewhat unrelated, but prior to this change, there would be a double // created in the path.

2023-05-18 11:52 UTC, jakesmith commented
> @jakesmith should some changes be made in the ZAPReport Import function to match with the new directory structure in a ZAPReport? When importing a WU from a ZAP report, the existing ZAPReport Import function verifies the postmortem folder using ImportDIR + the Tail of the @filename in WU XML (see the updateWUQueryAssociatedFilesAttrs() in workunit.cpp). Now, the verification will not work because a subFolder is added between the ImportDIR and the Tail.

Yes, it needed reworking. Please see new commit and explanation within the commit comment.

2023-05-18 20:36 UTC, wangkx approved these changes
@jakesmith looks fine now

2023-05-24 15:49 UTC, ghalliday requested changes
@jakesmith the windows build failure looks like a real error.

2023-05-24 17:29 UTC, jakesmith commented
@ghalliday - windows build issue resolved.

2023-05-25 11:13 UTC, ghalliday approved these changes
@jakesmith looks reasonable, no problems spotted.  Please squash.

2023-05-25 12:13 UTC, jakesmith commented
> @jakesmith looks reasonable, no problems spotted. Please squash.

@ghalliday - now squashed.

2023-05-26 09:29 UTC, merged