HPCC-261190 Update Environment.conf documentation
hpcc-systems/HPCC-Platform pull request #17364
Opened 2023-05-23 19:54 UTC by g-pan

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Successful integration testing: 
http://10.224.20.18/view/Docs-gp/job/Doc-Build-04-GPRepo2/

2023-05-23 20:13 UTC, JamesDeFabia requested changes
Comments inline

2023-05-23 20:13 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +          <para>There are several environment.conf settings for Bare Metal
bare-metal is hyphenated elsewhere in this manual

2023-05-23 20:13 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +          be set using the helm chart. The following bare metal
Helm chart 
(Helm s/b capitalized)

2023-05-23 20:13 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +                    Vallue</emphasis></entry>
typo Value

2023-05-23 21:05 UTC, JamesDeFabia approved these changes
Looks ok from my POV, but a SME needs to review

2023-05-31 15:28 UTC, ghalliday commented
@g-pan waiting for your response to Jake....

2023-06-02 15:23 UTC, JamesDeFabia requested changes
A couple of minor issues (comments inline)

2023-06-02 15:23 UTC, JamesDeFabia commented on docs/EN_US/HPCCSystemAdmin/HPCCSystemAdministratorsGuide.xml
> +      <para>A component of HPCC Systems on bare metal configuration is the
bare-metal

2023-06-02 15:23 UTC, JamesDeFabia commented on docs/EN_US/HPCCSystemAdmin/HPCCSystemAdministratorsGuide.xml
> +      <para>The environment.conf file only works for bare metal deployments.
bare-metal

2023-06-02 15:46 UTC, jakesmith approved these changes
@g-pan - looks fine

2023-06-02 16:40 UTC, JamesDeFabia approved these changes
Good from my POV

2023-06-02 16:45 UTC, g-pan commented
squashed and ready to merge

2023-06-06 08:50 UTC, merged