HPCC-28529 Document Landing Zone Scopes
hpcc-systems/HPCC-Platform pull request #17572
Opened 2023-07-10 16:27 UTC by g-pan

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Successfully executed unit tests: http://10.224.20.18/view/Docs-gp/job/Doc-Build-04-GPRepo2/

2023-07-10 16:28 UTC, g-pan commented
why did this pull in Jakes split from 9.2.2 commit?? How can I separate that?

2023-07-10 17:32 UTC, JamesDeFabia requested changes
This PR may need rebasing (I see lots of files that I don't think you intended to include, such as YAML files). 
Additional comments inline

2023-07-10 17:32 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/UserSecurityMaint.xml
> +    allows you to set permissions on sub-folders in a Landing zone. This
consistency: Landing Zone

2023-07-10 17:32 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/UserSecurityMaint.xml
> +      <para>An HPCC Administrator can define one or more Landing Zone scopes
Can a folder have more than one scope? "An HPCC Administrator can define one or more Landing Zone scopes for each folder..." implies that you can. But, later you say each folder is one scope and each scope is one folder.

2023-07-10 17:32 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/UserSecurityMaint.xml
> +      <para>The landing zone file scopes can be defined using ECLWatch for
consistency:  Landing Zone

2023-07-10 17:32 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/UserSecurityMaint.xml
> +      folder, go to the Security page of ECL Watch, and click on
Awkward sentence: To create a new file scope landing zone folder. 
Perhaps: To create a new Landing Zone scope

2023-07-10 17:32 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/UserSecurityMaint.xml
> +      <para>You can set the landing zone file permissions according to your
consistency: Landing Zone

2023-07-10 17:32 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/UserSecurityMaint.xml
> +      requirements. Access your new landing zone using the following
consistency: Landing Zone

2023-07-10 18:01 UTC, wangkx reviewed
One comment

2023-07-18 15:09 UTC, JamesDeFabia requested changes
Comments inline

2023-07-18 15:09 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/UserSecurityMaint.xml
> +      <para>An HPCC Administrator can define one or more Landing Zone scopes
This sentence is still confusing. The following sentence is a contradiction.

2023-07-18 20:17 UTC, JamesDeFabia reviewed
Looks ok now, but there are still many unrelated files included. Rebase, perhaps?

2023-07-19 12:21 UTC, g-pan commented
Once @wangkx and @RussWhitehead (please review) approve content will look to rebase

2023-07-19 17:12 UTC, wangkx approved these changes
My comment has been addressed.

2023-07-20 15:10 UTC, RussWhitehead approved these changes
@g-pan Looks reasonable

2023-07-20 15:27 UTC, JamesDeFabia requested changes
The content for this Jira looks ok, but there are unrelated files included.

2023-07-21 20:38 UTC, JamesDeFabia approved these changes
Looks good from my POV now

2023-07-27 15:12 UTC, merged