HPCC-29403 Allow disabling time zone adjustments in ECLWatch
hpcc-systems/HPCC-Platform pull request #17655
Opened 2023-08-08 10:20 UTC by kunalaswani

Toggle Button added to switch between Local and UTC timezones.

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-08-08 10:21 UTC, kunalaswani commented
@jeclrsg having some trouble with       

const currentTime = uiState.isUTC ? Utility.convertToUTCTime(WsDfu.DFUInfo.Modified) : Utility.convertToLocalTime(WsDfu.DFUInfo.Modified);

Can you advise... then i can apply to the other pages this is needed on.

2023-08-22 18:20 UTC, jeclrsg requested changes
@kunalaswani Added an example that should fix the error you were getting w/ the time conversion formatter

2023-08-22 18:20 UTC, jeclrsg commented on esp/src/src-react/components/Files.tsx
> +import { useEffect } from "react";
This include isn't necessary

2023-08-22 18:20 UTC, jeclrsg commented on esp/src/src-react/components/Files.tsx
> +      useEffect(() => {
These would be `React.useEffect(...` like the others already present

2023-08-22 18:20 UTC, jeclrsg commented on esp/src/src-react/components/Files.tsx
> +      const currentTime = uiState.isUTC ? Utility.convertToUTCTime(WsDfu.DFUInfo.Modified) : Utility.convertToLocalTime(WsDfu.DFUInfo.Modified);
This should be something like:

<pre>
const currentTime = React.useCallback(timestamp => {
    return uiState.isUTC ? Utility(convertToUTCTime(timestamp) : Utility.convertToLocalTime(timestamp);
}, [uiState.isUTC]);
</pre>

2023-08-22 18:20 UTC, jeclrsg commented on esp/src/src-react/components/Files.tsx
> +            Modified: { label: nlsHPCC.ModifiedUTCGMT, formatter: () => currentTime },
no need for the `() =>`, should just be `formatter: currentTime`

2023-08-22 18:20 UTC, jeclrsg commented on esp/src/src/Utility.ts
> +    return modifiedDate.toLocaleString();
These conversion functions may have to be slightly more complicated unfortunately. Using the `Date.toLocaleString()` and `.toUTCString()` functions as is would also change the formatting of the timestamps from something like `2023-07-21 01:14:44` to `Fri, 21 Jul 2023 01:14:44 GMT`. Which might be an improvement, actually... But just something to consider.

2023-10-06 10:06 UTC, ghalliday commented
@kunalaswani this looks like it has stalled.  Is it because you didn't ask for a re-review?  (I have now done that.)

2023-10-26 13:50 UTC, jeclrsg requested changes

2024-04-05 19:52 UTC, jeclrsg commented
@kunalaswani You'll need to rebase to the latest 9.2.x to take care of the conflicts GitHub is noting above. Hopefully there won't be too many conflicts that make it difficult.

Also, something like this could address several of my previous comments about the timestamps not actually changing in the grid and the modified column's label not reflecting whether or not UTC was being used https://github.com/jeclrsg/HPCC-Platform/commit/a79880f0ac6bf08058dfb520354428402ffae607?diff=unified&w=1 Or you might could use it as a reference at least.

2024-07-30 18:45 UTC, jeclrsg commented
> Also, something like this could address several of my previous comments about the timestamps not actually changing in the grid and the modified column's label not reflecting whether or not UTC was being used [jeclrsg@a79880f?diff=unified&w=1](https://github.com/jeclrsg/HPCC-Platform/commit/a79880f0ac6bf08058dfb520354428402ffae607?diff=unified&w=1) Or you might could use it as a reference at least.

@kunalaswani GH Actions noted some lint issues, after rebasing. Also, there were still some pending comments from my last review. The main issue I was seeing while testing just now was that the state of the UTC isn't properly tracked, so the grid rows aren't updating. Might've been some artifact of rebasing; merge collisions or whatnot. 

But that branch I'd linked to in a previous comment showed one way you could fix it, by moving the UTC status into it's own state variable. And the "currentTime" callback also made the way the datetimes were printed be consistent regardless of the timezone being used in the grid.

2025-05-16 18:07 UTC, jeclrsg commented on esp/src/src-react/components/Files.tsx
> +      const currentTime = uiState.isUTC ? Utility.convertToUTCTime(WsDfu.DFUInfo.Modified) : Utility.convertToLocalTime(WsDfu.DFUInfo.Modified);
This comment is still relevant. You're not using the Utility functions you added for converting back and forth between UTC and local time, but should be.

2025-06-16 13:46 UTC, kunalaswani commented
I am closing this ticket in replacement of a new PR due to issues with smoke test and inactivity. See: https://github.com/hpcc-systems/HPCC-Platform/pull/20010

2025-06-16 13:46 UTC, closed without merging