HPCC-27943 File name in info section of workunits displaying &apos;
hpcc-systems/HPCC-Platform pull request #17662
Opened 2023-08-09 09:39 UTC by kunalaswani

Corrected to display ' instead of Message with &apos; in field.

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-08-09 09:40 UTC, kunalaswani commented
We were displaying messages with the &apos; appended to the front and end of the message in the info section. due to a mismatch.

2023-08-09 13:41 UTC, jeclrsg reviewed
@kunalaswani The fix for that issue is probably elsewhere

2023-08-09 13:41 UTC, jeclrsg commented on esp/src/src/Utility.ts
> +        .replace(/"/g, "&apos;")
This change is incorrect. A single-quote character should be encoded as `&apos;`, a double-quote as `&quot;`.

2023-08-22 17:50 UTC, jeclrsg requested changes

2023-08-23 10:25 UTC, kunalaswani commented on esp/src/src-react/components/InfoGrid.tsx
>                      } else {
removal of the else solved the issue all together.

2023-08-23 14:33 UTC, jeclrsg approved these changes

2023-08-25 11:00 UTC, merged