HPCC-30140 Initial test cases for roxie https soapcall
hpcc-systems/HPCC-Platform pull request #17694
Opened 2023-08-22 16:23 UTC by ghalliday

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-08-22 21:48 UTC, afishbeck commented
@ghalliday I think this is a fine starting point.  I'm not sure you'll like some of the things we do to put a structured ESDL interface in front.  It will give you a chance to put your 2 cents in.

We will probably separate out a url input/stored for each of the soapcalls.  Mostly to emulate how things are done in production.

2023-08-22 21:49 UTC, afishbeck commented on testing/regress/ecl/setup/soaptest_getdocumentcount.ecl
> +//nothor
I think even in the regression suite we usually put a comment block at the top of every ecl file.

2023-08-22 22:07 UTC, afishbeck commented on testing/regress/ecl/common/SoapTextTest.ecl
> +    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
Copy and paste of an old date.

2023-08-22 22:10 UTC, afishbeck requested changes
Minor comments about copy right dates and file headings.

The url inputs would likely be split into one for each soapcall, and there might be other minor changes, when we put an ESDL interface in front.

2023-08-22 22:10 UTC, afishbeck commented on testing/regress/ecl/soaptext1.ecl
> +    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
Copy and paste of an old date.

2023-09-15 21:21 UTC, afishbeck reviewed
@ghalliday the test itself looks fine to me.  But it would be nice if we could get the regression test to actually test https and maybe secrets.  A first step could be doing that for kubernetes.

Having the test suite write a secret to disk in bare-metal might not be that hard for a single node system.

Beyond just supporting https soapcalls, in the cloud test repository we can make our queries work properly with scapps and desdl.

2023-09-19 12:00 UTC, ghalliday commented on testing/regress/ecl/common/SoapTextTest.ecl
> +    EXPORT countServiceRequest := RECORD
Yes.  I will switch so it uses them, but I will save switching to the ESDL style as a separate PR.

2023-09-25 14:56 UTC, afishbeck approved these changes

2023-09-26 08:06 UTC, merged