HPCC-28033 Document CORS Section of values.yaml
hpcc-systems/HPCC-Platform pull request #17817
Opened 2023-09-26 12:19 UTC by g-pan

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

All Tests Successful http://10.224.20.18/view/Docs-gp/job/DocBuild-GPRepo3/

2023-09-26 12:51 UTC, afishbeck requested changes
A couple of comments about example values.  I know you just used what I put in the comments of the yaml file, but I'd like to start improving these examples.

If you want you could update the values.yaml comments as well.  They are really internal documentation.

2023-09-26 12:51 UTC, afishbeck commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +    - "X-X"
Maybe, for clarity, change "X-X" to  "X-Custom-Header"

2023-09-26 12:51 UTC, afishbeck commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +  - origin: https://*.my.com
Just to slowly make examples more consistent over time, use "https://*.example2.com"?

2023-09-26 13:06 UTC, JamesDeFabia requested changes
One minor suggestion.

2023-09-26 13:06 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/ConfigureValues.xml
> +        domain. As a further enhancement to HPCC Systems we've added support
Suggested: The configuration settings for CORS access are in the ESP section of the values.yaml file.

2023-09-26 13:59 UTC, JamesDeFabia approved these changes
Looks good from my POV

2023-09-26 14:47 UTC, afishbeck approved these changes

2023-09-27 11:07 UTC, ghalliday commented
@g-pan please squash and I will merge

2023-09-27 13:44 UTC, g-pan commented
Squashed and ready to merge. Thank you @ghalliday

2023-09-28 18:23 UTC, merged