HPCC-30576 ECL Watch v9 fix Logs view column mappings
hpcc-systems/HPCC-Platform pull request #17933
Opened 2023-10-20 18:20 UTC by jeclrsg

use LogType returned in GetLogAccessInfo for column ids

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-10-20 18:22 UTC, jeclrsg commented
@jeclrsg need to bump hpcc-js/comms, dependent upon https://github.com/hpcc-systems/Visualization/pull/4130

2023-10-26 10:46 UTC, GordonSmith approved these changes

2023-10-26 15:56 UTC, GordonSmith commented
@jeclrsg - this PR is failing the build ECLWatch test

2023-10-27 06:41 UTC, GordonSmith requested changes
Failing ECL Watch test (looks like pulling in tamdem with https://github.com/hpcc-systems/HPCC-Platform/pull/17922/files/bd230f08ab28acb87a7139a316d3b4135c67fc61..b4381c5718c8a0d577a0ef5b5bdb0e8d7e67107e?notification_referrer_id=NT_kwDOAA7Az7E4MTE2MTEwMjQ2Ojk2Njg2Mw) will resolve?)

2023-10-27 16:16 UTC, GordonSmith approved these changes

2023-11-02 17:08 UTC, merged