HPCC-30612 Warn user when Platform is too old
hpcc-systems/HPCC-Platform pull request #18031
Opened 2023-11-15 11:28 UTC by GordonSmith

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-11-15 13:46 UTC, jeclrsg requested changes
@GordonSmith Saw a couple of spots that I wasn't sure if the Dates might be invalid, if stuff was undefined?

2023-11-15 13:46 UTC, jeclrsg commented on esp/src/src-react/hooks/platform.ts
> +            setTimestamp(new Date(response?.BuildTagTimestamp));
I think this could be an invalid date if BuildTagTimestamp were undefined

2023-11-15 13:46 UTC, jeclrsg commented on esp/src/eclwatch/HPCCPlatformWidget.js
> +                const age = Math.floor((Date.now() - new Date(features.BuildTagTimestamp).getTime()) / DAY);
If features didn't come back for some reason, might have an invalid date here also, and a NaN for age.

2023-11-16 17:20 UTC, jeclrsg approved these changes

2023-11-21 12:42 UTC, ghalliday reviewed
@GordonSmith Looks good.  A couple of comments on the message, and one on colouring (can ignore that one).

2023-11-21 12:42 UTC, ghalliday commented on esp/src/eclwatch/HPCCPlatformWidget.js
> +                    severity = "Alert";
The colouring of alerts in the old eclwatch looks less important than errors,

2023-11-21 12:42 UTC, ghalliday commented on esp/src/src/nls/hpcc.ts
> +        PlatformIsNNNDaysOld: "Platform is NNN days old",
Suggest reword to 
"Platform build is NNN days old."

Once it is reported as a warning it should be

"Platform build is NNN days old.  Please upgrade to a later point release."

to make it clear that it isn't the version we are complaining about, and how to resolve it.

2023-11-21 12:42 UTC, ghalliday commented on esp/src/src/nls/hpcc.ts
> +        PlatformIsNNNDaysOld: "Platform is NNN days old",
Possibly add "(See About/Latest Releases for details.)"

2023-11-22 14:45 UTC, jeclrsg approved these changes

2023-11-23 16:04 UTC, ghalliday approved these changes

2023-11-23 16:04 UTC, merged