HPCC-30921 Improve Graph Rendering Root
hpcc-systems/HPCC-Platform pull request #18087
Opened 2023-11-28 13:01 UTC by GordonSmith

* Add breadcrumbs for graph lineage
* Don't render parent for select subgraphs
* Add status spinner with node count

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2023-11-28 15:02 UTC, jeclrsg requested changes
@GordonSmith looked good, just a couple questions & saw some commented out code in there

2023-11-30 11:43 UTC, GordonSmith commented on esp/src/src-react/components/Metrics.tsx
> -            key: "reset", text: nlsHPCC.Reset, iconProps: { iconName: "Undo" },
Yes intentional - seemed to cause more confusion than anything useful.

2023-11-30 14:43 UTC, jeclrsg requested changes
@GordonSmith just saw a couple lines of commented out code in some of the new additions.

2023-11-30 16:32 UTC, GordonSmith commented on esp/src/src-react/components/Metrics.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
I don't want this to be called when the updateXXX functions changed

2023-11-30 16:44 UTC, jeclrsg approved these changes

2023-11-30 16:44 UTC, merged