HPCC-31263 Document security manager user authentication
hpcc-systems/HPCC-Platform pull request #18322
Opened 2024-02-20 21:17 UTC by kenrowland

Added document covering user authentication for defined security managers

Signed-Off-By: Kenneth Rowland kenneth.rowland@lexinexirisk.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-02-20 22:16 UTC, afishbeckln commented on devdoc/SecurityUserAuthentication.md
> +user. The signature is used to detect if there has been a change to the user. If changed, the user is marked
What kind of change to the user does the signature checking detect?

2024-02-20 22:20 UTC, afishbeckln requested changes
One minor comment and one request for clarification.

2024-02-23 19:11 UTC, afishbeckln approved these changes

2024-02-23 20:00 UTC, JamesDeFabia requested changes
minor comments inline

2024-02-23 20:00 UTC, JamesDeFabia commented on devdoc/SecurityUserAuthentication.md
> +ECLWatch uses user authentication during authorization during its log in process. Instead of first authenticating
ECL Watch s/b two words

2024-02-23 20:00 UTC, JamesDeFabia commented on devdoc/SecurityUserAuthentication.md
> +have access in order to log into ECLWatch.
ECL Watch s/b two words

2024-02-27 14:55 UTC, JamesDeFabia approved these changes
Looks good from my POV

2024-02-27 15:07 UTC, kenrowland commented
@ghalliday Please merge

2024-02-28 13:36 UTC, merged