HPCC-24527 Document Single User Security Manager
hpcc-systems/HPCC-Platform pull request #18321
Opened 2024-02-20 20:20 UTC by g-pan

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [x] Test my draft Pull Request.

## Testing:

successful completion of Unit tests: http://10.224.20.18/view/Docs-gp/job/DocBuild-05-GPanRepo04/

2024-02-20 20:36 UTC, JamesDeFabia requested changes
Comments inline

2024-02-20 20:36 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/hpcc_ldap.xml
> +    ESP startup command line. At run time, when you attempt to access any
run time s/b runtime

2024-02-20 20:36 UTC, JamesDeFabia commented on docs/EN_US/Installing_and_RunningTheHPCCPlatform/Inst-Mods/hpcc_ldap.xml
> +    <para>The Single User security manager is a very specialized security
remove "very"

2024-02-21 16:59 UTC, JamesDeFabia approved these changes
Looks ok to me

2024-02-22 11:47 UTC, ghalliday requested changes
This contains unrelated changes to vcpkg and spark-hadoop

2024-02-22 14:55 UTC, g-pan commented
Closing this PR with intent to reissue. Smoketest is reporting problems.

2024-02-22 14:55 UTC, closed without merging