HPCC-31258 Initial File structure and page layout creation
hpcc-systems/HPCC-Platform pull request #18356
Opened 2024-02-28 18:28 UTC by kunalaswani

This is to create the initial design of Sasha in Cloud. Feature availability to come as it is created.

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-02-28 19:43 UTC, jeclrsg reviewed
@kunalaswani There are a lot of lint errors getting annotated by GH Actions

2024-03-01 22:32 UTC, jeclrsg requested changes
I would think this should be more similar to your Dali Admin PR(s), both with respect to the changes to routes.tsx and the Sasha.tsx component, ie using FluentUI components.

2024-03-01 22:32 UTC, jeclrsg commented on esp/src/src-react/routes.tsx
> +                path: "/sasha", action: (ctx, params) => import("./components/Sasha").then(_ => {
Should look more like the routing changes you'd made for the Dali admin, with child routes based on which "Tab" of the UI was selected?

2024-03-01 22:32 UTC, jeclrsg commented on esp/src/src-react/components/Sasha.tsx
> +
This component should probably be using the FluentUI components for any HTML it returns.

2024-03-06 16:48 UTC, jeclrsg approved these changes

2024-03-07 13:41 UTC, ghalliday reviewed
See comment about embedded text

2024-03-07 13:41 UTC, ghalliday commented on esp/src/src-react/components/Sasha.tsx
> +            { key: "", text: "Select an option" },
Should these display strings be i18n?

2024-03-07 21:21 UTC, kunalaswani commented on esp/src/src-react/components/Sasha.tsx
> +            { key: "", text: "Select an option" },
@ghalliday corrected

2024-03-08 09:55 UTC, ghalliday commented
@kunalaswani if you are making changes to a PR, please push them as separate commits, which can than be squashed later - otherwise it is hard to spot the changes.  Also, you need to re-request reviews.

2024-03-08 09:57 UTC, ghalliday approved these changes

2024-03-08 14:39 UTC, jeclrsg requested changes
@kunalaswani just noticed a couple other small things, other strings that should be using the translations file

2024-03-08 14:39 UTC, jeclrsg commented on esp/src/src-react/components/Sasha.tsx
> +  const defaultValue = result ? null : <div>No data available</div>;
"No data available" should be in translations

2024-03-08 14:39 UTC, jeclrsg commented on esp/src/src-react/components/Sasha.tsx
> +          placeholder="Select an option"
should be nlsHPCC.SelectAnOption

2024-03-08 14:39 UTC, jeclrsg commented on esp/src/src-react/components/Sasha.tsx
> +              label="Work Unit ID:"
There's an nlsHPCC.WUID, or this one should be added

2024-03-11 13:48 UTC, jeclrsg approved these changes

2024-03-14 15:40 UTC, merged