HPCC-31384 Add release cadence to README.md
hpcc-systems/HPCC-Platform pull request #18368
Opened 2024-03-01 12:57 UTC by GordonSmith

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-03-01 13:01 UTC, GordonSmith commented
@ghalliday you preview how it renders here:
![image](https://github.com/hpcc-systems/HPCC-Platform/assets/966863/fb02c1e9-4732-4007-b9c8-076e8cc0ac83)

2024-03-06 10:13 UTC, ghalliday reviewed
Looks good.  Some suggested changes to the dates.

2024-03-06 10:13 UTC, ghalliday commented on README.md
> +        Active:          active, 2023-04-01, 1y
2023-07-01, 6M

2024-03-06 10:13 UTC, ghalliday commented on README.md
> +        Active:          done, 2022-10-01, 1y
2023-04-01, 9M

2024-03-06 10:13 UTC, ghalliday commented on README.md
> +        Active:          done, 2022-04-01, 1y
2023-02-07, 6M

2024-03-06 10:13 UTC, ghalliday commented on README.md
> +        Security:        done, 6M
9M

2024-03-06 10:13 UTC, ghalliday commented on README.md
> +        Active:          active, 2023-10-01, 1y
, 9M

2024-03-07 13:47 UTC, ghalliday commented on README.md
> +        Active:          2024-04-01, 1y
, 6M and also line 43.  Standard is really 6M active, 6M security, but it has changed a bit around the 9.4.x release.

2024-03-07 13:48 UTC, ghalliday reviewed
@GordonSmith a couple of final comments

2024-03-07 13:48 UTC, ghalliday commented on README.md
> +In general, a new version of the HPCC Platform is released every 6 months. These releases can be either Major (with breaking changes) or Minor (with new features). Maintenance and security releases (
Every 3 months

2024-03-14 14:46 UTC, ghalliday requested changes
Active is still too long for 9.6 and 10.0.0.  Also 10.0.0 is more likely to be 9.8.

2024-07-04 05:06 UTC, GordonSmith commented
@ghalliday, @cloLN - updated to include 9.8.x and 9.10.x

2024-07-08 11:47 UTC, cloLN commented
Looks good.  thanks.

2024-07-09 13:17 UTC, cloLN approved these changes
Changes look good.

2024-07-16 08:13 UTC, ghalliday approved these changes

2024-07-16 08:14 UTC, merged