HPCC-31535 ALA declare KQL timespan
hpcc-systems/HPCC-Platform pull request #18509
Opened 2024-04-09 02:33 UTC by rpastrana

- Adds method to serialize tieme range as ISO 8601 Time intervals
- Supply query time interval as KQL timespan
- Replace api.loganalytics.io endpoint with api.loganalytics.azure.com.

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-04-11 15:41 UTC, jakesmith commented
@rpastrana - assume typo in commit comment 'tieme'

2024-04-11 15:46 UTC, jakesmith commented
>This change is a bug fix (non-breaking change which fixes an issue).

@rpastrana - can you update the PR commit to describe what the symptoms of the bug was, and how it fixes it?

2024-04-11 15:48 UTC, jakesmith reviewed
@rpastrana - changes look sensible afaics.
Please update PR commit message to describe what bug/bug symptoms were seen and how this fixes it.

2024-04-11 15:51 UTC, rpastrana commented
Per HPCC-31535, ALA rest queries have been timing out after 3 minutes.
Per recommendations from Daniel Polk from Azure, the in-query timestamp is applied late in the query filtering. The in-request timespan should be declared in order to minimize the scope of the query. Also, "api.loganalytics.io endpoint is being replaced by api.loganalytics.azure.com. Even though api.loganalytics.io is fully supported at this time, it is recommended to transition to the new endpoint for long-term compatibility"

2024-04-11 16:14 UTC, rpastrana commented
@jakesmith updated.
@ghalliday please merge

2024-04-11 16:19 UTC, ghalliday requested changes

2024-04-11 16:19 UTC, ghalliday commented on system/logaccess/Azure/LogAnalytics/CurlClient/AzureLogAnalyticsCurlClient.cpp
> +        queryTimeSpan.appendf("/%s", fromTimeStr);
I think CDateTime::getString() may do what you need.

2024-04-11 16:38 UTC, rpastrana commented on system/logaccess/Azure/LogAnalytics/CurlClient/AzureLogAnalyticsCurlClient.cpp
> +        queryTimeSpan.appendf("/%s", fromTimeStr);
Good copy/paste error catch. fixing

2024-04-12 13:19 UTC, rpastrana commented
@jakesmith this change is urgent and should be made available in current rc if possible
@rwagner42 fyi

2024-04-15 08:44 UTC, jakesmith reviewed
@rpastrana - 2 minor comments, but looks good.

Please respond to comments, but go ahead and squash

2024-04-15 08:44 UTC, jakesmith commented on system/logaccess/Azure/LogAnalytics/CurlClient/AzureLogAnalyticsCurlClient.cpp
> +    azureLogAnalyticsQueryTimeSpanString(queryTimeSpan, trange.getStartt().getSimple(),trange.getEndt().isNull() ? -1 : trange.getEndt().getSimple());
trivial/formatting: inconsistent spacing (missing space after 2nd comma)

2024-04-15 08:44 UTC, jakesmith commented on system/logaccess/Azure/LogAnalytics/CurlClient/AzureLogAnalyticsCurlClient.cpp
> +        queryTimeSpan.appendf("/%s", fromTimeStr);
minor: per above comments, did you consider using CDateTime::getString ?

2024-04-15 15:47 UTC, rpastrana commented on system/logaccess/Azure/LogAnalytics/CurlClient/AzureLogAnalyticsCurlClient.cpp
> +    azureLogAnalyticsQueryTimeSpanString(queryTimeSpan, trange.getStartt().getSimple(),trange.getEndt().isNull() ? -1 : trange.getEndt().getSimple());
missing space added.

2024-04-15 15:48 UTC, rpastrana commented on system/logaccess/Azure/LogAnalytics/CurlClient/AzureLogAnalyticsCurlClient.cpp
> +        queryTimeSpan.appendf("/%s", fromTimeStr);
Considered, chose not make changes at this point.

2024-04-17 09:14 UTC, jakesmith approved these changes
@rpastrana looks good.

2024-04-18 12:19 UTC, ghalliday approved these changes

2024-04-18 12:20 UTC, merged