HPCC-22453 Document Import ZAP Feature
hpcc-systems/HPCC-Platform pull request #18719
Opened 2024-05-31 12:29 UTC by g-pan

**NOTE**: Used XXE 10.7 on unmanaged Linux workstation  

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

SUCCESSFUL INTEGRATION TESTING: https://github.com/g-pan/github-action-dev-build/actions/runs/9312847884

2024-06-03 19:28 UTC, JamesDeFabia requested changes
Needs info about the importzap action.
`importzap <zapreport-filename> <output-helper-directory> [<zapreport-password>] `
needs to be added to the usage table on page 133.
Also, the reason why you may want to import one is in the Jira comments

2024-06-04 23:30 UTC, JamesDeFabia requested changes
See comments inline

2024-06-04 23:30 UTC, JamesDeFabia commented on docs/EN_US/HPCCSystemAdmin/SA-Mods/WUTool.xml
> +          [&lt;zapreport-password&gt;]</para></entry>
zapreport-password is optional. Also, it is unclear what **output-helper-directory** is.

2024-06-11 21:55 UTC, JamesDeFabia approved these changes
Looks good from my POV, but needs SME review before merging.

2024-06-12 08:48 UTC, jakesmith reviewed
@g-pan 1 comment.

output-helper-directory ideally would be optional, but it is not.

2024-06-12 08:48 UTC, jakesmith commented on docs/EN_US/HPCCSystemAdmin/SA-Mods/WUTool.xml
> +          [optional] temporary directory to unpack the zap report
output-helper-directory is not optional.

2024-06-14 10:55 UTC, jakesmith approved these changes
@g-pan - looks good.

2024-06-14 15:19 UTC, merged