HPCC-32002 Create documentation for bundleTest-thor GitHub Action
hpcc-systems/HPCC-Platform pull request #18731
Opened 2024-06-06 12:40 UTC by Charan-Sharan

Initial check-in of draft documentation

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-06-07 10:32 UTC, AttilaVamos requested changes
There are some part where it would be nice to give a bit more information.
You need to change the bundle install part in this documentation as well as in the action script.

2024-06-07 10:32 UTC, AttilaVamos commented on .github/workflows/bundleTest-thor.md
> +- **test-core-file-generation** :A boolean input that determines whether the core file generation test step should be executed. It helps us to know whether the core files are generated as expected.
I think this help us to test whether our core handler working fine if a core file generated during tests.

2024-06-07 10:32 UTC, AttilaVamos commented on .github/workflows/bundleTest-thor.md
> +- `ML_SUPPRESS_WARNING_FILES:` Specifies the files requiring a warning suppression parameter during runtime.
I thin it would be clearer if "Specifies the files requiring a warning suppression parameter injection into the ECL code before they are executed."

2024-06-07 10:32 UTC, AttilaVamos commented on .github/workflows/bundleTest-thor.md
> +The HPCC Platform is installed from the downloaded artifact.
I think it would be better if "Install the HPCC Platform from the downloaded artifact, set permissions an configure the Thor engine to use 2 slaves."

2024-06-07 10:32 UTC, AttilaVamos commented on .github/workflows/bundleTest-thor.md
> +Setup the core generation and start the HPCC Platform
A couple of more words would be nice about why it is needed and how it configure the core generation.

2024-06-07 10:32 UTC, AttilaVamos commented on .github/workflows/bundleTest-thor.md
> +This step is used to check if the core generation is working as expected. This is an optional step. This step runs only when it is specified in the inputs via workflow call.
A couple of words about how it is working and where the core file will be generated would be nice.

2024-06-07 10:32 UTC, AttilaVamos commented on .github/workflows/bundleTest-thor.md
> +                        BUNDLE_VERSION=$( echo "${cRes}" | egrep "^$BUNDLE_NAME" | awk '{ print $2 }' )
This BUNDLE_VERSION is acquired, but not used. 
In the original version of bundleTest.sh some information has been logged like bundle name, repo name, install CMD and the finally installed bundle version, or error message if the install failed.
I think they are useful information and would be nice to put them into the action code as well in this documentation.

2024-06-07 10:32 UTC, AttilaVamos commented on .github/workflows/bundleTest-thor.md
> +      ProcessLog()
Some words about this function would be nice

2024-06-10 14:06 UTC, JamesDeFabia requested changes
Just one comment inline.

2024-06-14 13:11 UTC, JamesDeFabia approved these changes
Looks good from my POV

2024-06-18 08:42 UTC, AttilaVamos approved these changes
Looks good. 
Please fill the relevant checkboxes and convert it to standard pull request.

2024-06-24 09:54 UTC, merged