HPCC-32250 Track PeakTempSize for all activities that use lookahead
hpcc-systems/HPCC-Platform pull request #18895
Opened 2024-07-18 12:06 UTC by shamser

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-07-19 15:26 UTC, jakesmith requested changes
@shamser - please see comments.

I do wonder whether we shouldn't just add spilling stats to the base activity stats.
The downside, mergeStats will walk over stats in the mapping, and query them, in activities that never used them, unnecessarily.
The upside, cleaner code, future changes won't have to keep these common attributes in sync.

@ghalliday - what's your thoughts? is the overhead of cycling through a few unused stat. kinds an issue. NB: in general there will be many stats that are are used I suspect. We could also think about optimizing mergeStats/tracking the stats that have been used..

2024-07-19 15:26 UTC, jakesmith commented on thorlcr/activities/enth/thenth.cpp
> +        return new CMasterActivity(container, spillingActivityStatistics);
in fact - both local and global Enth *may* use a lookahead, but I don't think localenth should - I will open a separate JIRA to change it - for now it is better to mirror how it's implemented and ensure spillingActivityStatistics used for both (as it is in worker impl.)

2024-07-19 15:26 UTC, jakesmith commented on thorlcr/activities/selectnth/thselectnth.cpp
> +        return new CMasterActivity(container, spillingActivityStatistics);
as per previous comments. The local version doesn't use a lookahead. The global does.

2024-07-24 12:10 UTC, ghalliday commented on thorlcr/activities/choosesets/thchoosesets.cpp
> +        return new CMasterActivity(container, spillingActivityStatistics);
Doesn't local use lookahead?  Simpler for all use use spilling stats.

2024-07-24 12:17 UTC, ghalliday reviewed
@jakesmith I agree with your comments.

2024-07-24 12:17 UTC, ghalliday commented on thorlcr/activities/choosesets/thchoosesetsslave.cpp
> +    BaseChooseSetsActivity(CGraphElementBase *_container, const StatisticsMapping & _mapping = basicActivityStatistics) : CSlaveActivity(_container, _mapping)
Clearer/safer to not have a default parameter so it is easy to check the correct mapping is being used for all variants.

2024-07-24 12:17 UTC, ghalliday commented on thorlcr/activities/firstn/thfirstnslave.cpp
> +    CFirstNSlaveBase(CGraphElementBase *_container, const StatisticsMapping & _mapping = basicActivityStatistics) : CSlaveActivity(_container, _mapping)
similar comment to above about not using a default parameter

2024-07-24 12:17 UTC, ghalliday commented on thorlcr/thorutil/thormisc.cpp
> +const StatisticsMapping indexWriteActivityStatistics({StPerReplicated, StNumLeafCacheAdds, StNumNodeCacheAdds, StNumBlobCacheAdds }, spillingActivityStatistics, basicActivityStatistics, diskWriteRemo
spillingActivityStatistics -> spillStatistics

2024-07-26 12:05 UTC, ghalliday commented
Replaced by https://github.com/hpcc-systems/HPCC-Platform/pull/18920

2024-07-26 12:05 UTC, closed without merging