HPCC-32238 Add large_list data type to Parquet Plugin
hpcc-systems/HPCC-Platform pull request #18918
Opened 2024-07-25 22:01 UTC by ilhan2316

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-07-26 15:11 UTC, jackdelv requested changes
@ilhan2316 I have just a few small comments.

2024-07-26 15:11 UTC, jackdelv commented on plugins/parquet/parquetembed.cpp
> -    arrow::ListBuilder *listBuilder = static_cast<arrow::ListBuilder *>(childBuilder);
This piece of code pads the list builder and sets it up for adding list elements to it. I believe what was meant to go here was a change from a ListBuilder to LargeListBuilder.

2024-07-26 15:11 UTC, jackdelv commented on plugins/parquet/parquetembed.cpp
> +void ParquetRowBuilder::processBeginSet(const RtlFieldInfo *field, bool &isAll) {
Style: Curly braces should be on a line of their own.

2024-07-26 15:11 UTC, jackdelv commented on plugins/parquet/parquetembed.cpp
> -
Style: not sure why this line was removed.

2024-07-26 15:11 UTC, jackdelv commented on plugins/parquet/parquetembed.hpp
> +#endif
Style: Missing newline and end of file.

2024-07-26 15:11 UTC, jackdelv commented on plugins/parquet/parquetembed.cpp
> -    arrow::ListBuilder *listBuilder = static_cast<arrow::ListBuilder *>(childBuilder);
Make sure that you are testing writing Parquet files with an ECL SET as this change would cause an error.

2024-07-26 19:47 UTC, jackdelv requested changes
@ilhan2316 It's close. Just one minor comment.

2024-07-26 19:47 UTC, jackdelv commented on plugins/parquet/parquetembed.cpp
> +    reportIfFailure(LargeListBuilder->Append());
Should be largeListBuilder.

2024-07-29 18:44 UTC, jackdelv approved these changes
@ilhan2316 The changes look good. Please squash the commits.

2024-07-30 13:11 UTC, jackdelv commented
@dcamper Please take a look. This changes the default when writing Parquet files to use the Large String type and adds it to the checked types when reading Parquet files.

2024-07-30 13:19 UTC, dcamper approved these changes
Looks good to me.

2024-07-30 13:36 UTC, ilhan2316 commented
Squashed and ready to be merged. Please have a look @ghalliday

2024-07-31 09:31 UTC, merged