HPCC-32311 Update hyperlinks-testing documentation to use escape char…
hpcc-systems/HPCC-Platform pull request #18923
Opened 2024-07-26 16:40 UTC by Charan-Sharan

HPCC-32311 Update hyperlinks-testing documentation to use escape characters while using triple backticks.

When using triple backticks in markdown file for purposes other than representing code blocks, ensure that they are escaped with a backslash ("\\") to prevent misinterpretation by the hyperlink-testing logic.

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-07-29 13:20 UTC, AttilaVamos approved these changes
Looks good.

2024-07-30 13:11 UTC, JamesDeFabia requested changes
One comment inline

2024-07-30 13:11 UTC, JamesDeFabia commented on .github/workflows/test-hyperlinks.md
> +Note: Using triple backticks for purposes other than representing code snippets is not recommended in markdown files. If using triple backticks is unavoidable, ensure they are escaped with a backslas
Trivial: Markdown s/b capitalized for consistency.

2024-07-30 17:49 UTC, JamesDeFabia approved these changes
Looks good from my POV

2024-07-31 09:29 UTC, merged