HPCC-30048 ECL Watch disable password change when unsupported
hpcc-systems/HPCC-Platform pull request #18927
Opened 2024-07-29 15:07 UTC by jeclrsg

use the "CanUpdatePassword" boolean returned by /ws_account/MyAccount to enable/disable the change password fields in ECL Watch

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-07-29 15:23 UTC, kenrowland commented
I am not sure this is the best way to solve this. I have been working with Tim on the best way to implement a policy like this. Depending on the "CanUpdatePassword" flag requires that all security managers know about this policy disable the ability to set the password. This may not be desirable since feature flags define manager capabilities that are not currently based on a policy. Additionally, policies may not apply to certain users such as service account users that may still need to perform certain operations. Disabling based on a policy at the security manager will prevent these types of operations.

I would delay approving this PR until we decide the best way to support these types of policies and if any support will be added to Security Managers.

2024-07-31 04:35 UTC, GordonSmith requested changes
Code looks good - just one minor pedantic issue.

2024-07-31 04:35 UTC, GordonSmith commented on esp/src/eclwatch/CurrentUserDetailsWidget.js
> +            CanUpdatePassword: false,
Minor:  prop casing consistency, change to `canUpdatePassword`

2024-08-02 09:51 UTC, GordonSmith approved these changes

2024-08-02 09:51 UTC, merged