HPCC-32171 ARM64 constant-folding support
hpcc-systems/HPCC-Platform pull request #18940
Opened 2024-07-31 12:07 UTC by richardkchapman

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [x] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Cloud-compatibility
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Added tests to regression suite, ran on Mac M2 arm64 system

2024-07-31 12:54 UTC, AttilaVamos commented
On Rocky 8 there are some warnings treated as error:
```
/home/rocky/smoketest/PR-18940/HPCC-Platform/plugins/exampleplugin/exampleplugin.cpp:71:39: error: format â€˜%lluâ€™ expects argument of type â€˜long long unsigned intâ€™, but argument 6 has type â€˜uint64_tâ€™ {aka â€˜long unsigned intâ€™} [-Werror=format=]
/home/rocky/smoketest/PR-18940/HPCC-Platform/plugins/exampleplugin/exampleplugin.cpp:71:53: error: format â€˜%lldâ€™ expects argument of type â€˜long long intâ€™, but argument 10 has type â€˜int64_tâ€™ {aka â€˜long intâ€™} [-Werror=format=]
/home/rocky/smoketest/PR-18940/HPCC-Platform/plugins/exampleplugin/exampleplugin.cpp:71:58: error: format â€˜%lluâ€™ expects argument of type â€˜long long unsigned intâ€™, but argument 11 has type â€˜uint64_tâ€™ {aka â€˜long unsigned intâ€™} [-Werror=format=]
/home/rocky/smoketest/PR-18940/HPCC-Platform/plugins/exampleplugin/exampleplugin.cpp:71:63: error: format â€˜%lluâ€™ expects argument of type â€˜long long unsigned intâ€™, but argument 12 has type â€˜uint64_tâ€™ {aka â€˜long unsigned intâ€™} [-Werror=format=]
/home/rocky/smoketest/PR-18940/HPCC-Platform/plugins/exampleplugin/exampleplugin.cpp:93:39: error: format â€˜%lluâ€™ expects argument of type â€˜long long unsigned intâ€™, but argument 6 has type â€˜uint64_tâ€™ {aka â€˜long unsigned intâ€™} [-Werror=format=]
/home/rocky/smoketest/PR-18940/HPCC-Platform/plugins/exampleplugin/exampleplugin.cpp:93:53: error: format â€˜%lldâ€™ expects argument of type â€˜long long intâ€™, but argument 10 has type â€˜int64_tâ€™ {aka â€˜long intâ€™} [-Werror=format=]
/home/rocky/smoketest/PR-18940/HPCC-Platform/plugins/exampleplugin/exampleplugin.cpp:93:58: error: format â€˜%lluâ€™ expects argument of type â€˜long long unsigned intâ€™, but argument 11 has type â€˜uint64_tâ€™ {aka â€˜long unsigned intâ€™} [-Werror=format=]
/home/rocky/smoketest/PR-18940/HPCC-Platform/plugins/exampleplugin/exampleplugin.cpp:93:63: error: format â€˜%lluâ€™ expects argument of type â€˜long long unsigned intâ€™, but argument 12 has type â€˜uint64_tâ€™ {aka â€˜long unsigned intâ€™} [-Werror=format=]
cc1plus: some warnings being treated as errors
```

2024-08-01 14:31 UTC, GordonSmith requested changes

2024-08-02 10:29 UTC, richardkchapman commented on ecl/hql/hqlfold.cpp
> +           "0: \n\t"
They don't need to be.

2024-08-07 10:22 UTC, richardkchapman commented on ecl/hql/hqlfold.cpp
> +        assertex((len & 7) == 4);  // We need to make sure we add an ODD number of words to stack, so that it gets #8-byte aligned once pc is pushed by the call
Probably (the #)

2024-08-07 10:24 UTC, richardkchapman commented on cmake_modules/vcpkg.cmake
> +    set(VCPKG_TARGET_TRIPLET "arm64-osx" CACHE STRING "target triplet")
Makes sense

2024-08-19 16:19 UTC, ghalliday approved these changes
Looks good to me.  @GordonSmith ?

2024-08-21 12:27 UTC, GordonSmith approved these changes

2024-08-21 15:04 UTC, ghalliday commented
@richardkchapman please squash and I will merge

2024-08-28 09:35 UTC, merged