HPCC-32398 update references to system requirements
hpcc-systems/HPCC-Platform pull request #19001
Opened 2024-08-15 12:14 UTC by g-pan

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [x] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

https://github.com/g-pan/github-action-dev-build/actions/runs/10394628523

2024-08-15 16:49 UTC, JamesDeFabia requested changes
The PT_BR version of Hardware.xml also needs to be removed.

2024-08-16 17:43 UTC, JamesDeFabia requested changes
@g-pan Let me know when build issue is resolved.

2024-08-16 19:49 UTC, JamesDeFabia approved these changes
Looks good

2024-08-16 19:50 UTC, JamesDeFabia commented
Make sure @vfumene knows about https://hpccsystems.atlassian.net/browse/HPCC-32445

2024-08-22 16:03 UTC, ghalliday reviewed
@g-pan will need squashing, but it also looks like a section of the file should be deleted.

2024-08-22 16:03 UTC, ghalliday commented on docs/PT_BR/HPCCSystemAdmin/HPCCSystemAdministratorsGuide.xml
> +<!-- COMMENTING FOR TEST - THIS WHOLE SECTION SHOULD BE REMOVED.
Are you going to remove this section?

2024-08-26 13:17 UTC, g-pan commented
something is not right here, squashed yet git is not reflecting that. 
Closing this request to reissue cleanly.

2024-08-26 13:17 UTC, closed without merging