HPCC-31972 Update Docs for Cost Tracking improvements
hpcc-systems/HPCC-Platform pull request #19020
Opened 2024-08-20 21:21 UTC by g-pan

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Successful Unit Tests : https://github.com/g-pan/github-action-dev-build/actions/runs/10474453301

2024-08-20 21:28 UTC, JamesDeFabia requested changes
comments inline

2024-08-20 21:28 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/CustomConfig.xml
> +        operations. The cost of reading and writing to the file are
SV agreement. Either "costs are included" or "costs is included"

2024-08-20 21:28 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/CustomConfig.xml
> +    These columns may be sorted by any cost columns, just like the other
Use "can" instead of "may"

2024-08-21 13:26 UTC, g-pan commented
@shamser please verify the information going into the doc is currently accurate.

2024-08-21 13:44 UTC, JamesDeFabia requested changes
one minor comment inline

2024-08-21 13:44 UTC, JamesDeFabia commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/CustomConfig.xml
> +For example, data that was accessed from page cache doesn’t incur any file access cost.  HPCC Systems cost tracking now detects data that has been returned from the page cache and adjust cost calcula
s/b "adjusts" for SV agreement

2024-08-22 10:25 UTC, shamser requested changes

2024-08-22 10:25 UTC, shamser commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/CustomConfig.xml
> +            <para>File Cost at Rest</para>
Storage Cost is listed as a separate item in the list of costs above.  Storage cost isn't a separate cost item. Storage Cost = File Access Cost + File Cost At Rest.  Also, the Execution cost is not listed.  The Types of costs tracked are:
- Execute Cost
- Compile Cost
- File Access Cost
- File Cost At Rest

2024-08-22 10:25 UTC, shamser commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/CustomConfig.xml
> +<para> For logical files, the costs calculated are based on two types of file access.  </para>
It should probably be "...there are two types of file costs:".  There is just one type of file access cost (File Access Cost) but there are 2 storage related costs (File Access Cost and File Cost at Rest)

2024-08-22 10:25 UTC, shamser commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/CustomConfig.xml
> +        <title>File Access Costs</title>
The title should be something like "File Cost".  File Access Costs doesn't include Storage At Rest cost.

Also, the paragraph on line 1003-1007, is no longer correct. The two types of storage costs has been separated into 2 different fields and can now be viewed as separate fields.

2024-08-22 10:25 UTC, shamser commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/CustomConfig.xml
>          <para>The file access cost displays as part of the cost field on the
There are now two separate fields for the file costs now.  The file access costs isn't displayed _as part of_ the cost field.  File access cost is shown as a field. The At rest is shown as separate field.

2024-08-22 10:25 UTC, shamser commented on docs/EN_US/ContainerizedHPCC/ContainerizedMods/CustomConfig.xml
> +        is the cost of storing the file without accessing the data. Only the storage costs associated with housing the file in the cloud. This value has been added to better differentiate between fil
"File Cost at Rest field" is the file storage costs.  I think the last line in the previous paragraph should be removed.  File Costs At Rest and File Access cost are both shown in the logical file's summary page.

2024-09-04 16:35 UTC, g-pan commented
provided PDF file for review offline.

2024-09-06 13:37 UTC, shamser approved these changes
Looks good.

2024-09-24 12:51 UTC, JamesDeFabia approved these changes
Good from my POV

2024-09-25 16:19 UTC, ghalliday commented
@g-pan please squash

2024-09-26 10:32 UTC, shamser approved these changes

2024-09-30 11:37 UTC, merged