HPCC-29356 add JIRA creation guidelines to userdocs
hpcc-systems/HPCC-Platform pull request #19123
Opened 2024-09-16 17:52 UTC by cloLN

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [x] Security
  - [x] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-09-16 18:00 UTC, stuartort approved these changes
This addition looks fine

2024-09-25 16:54 UTC, ghalliday reviewed
Looks good.  Please remove adding core files.  I'm happy for you to leave the rest as it is.

2024-09-25 16:54 UTC, ghalliday commented on devdoc/userdoc/JiraGuidelines.md
> +   - Include stack traces and a copy of the core file if possible.
I don't think we generally want core files attached - they may contain pii, and can be GBs in size.

2024-09-25 16:54 UTC, ghalliday commented on devdoc/userdoc/JiraGuidelines.md
> +   - Which browser and its version.
would it be worth grouping this with screenshot under user-interface issues?

2024-10-04 10:50 UTC, ghalliday commented
@cloLN this is waiting for you to update it...

2024-11-11 15:00 UTC, ghalliday commented on devdoc/userdoc/JiraGuidelines.md
> +      - URL to environment.
url to environment and workunit are relevant to all issues.

Which browser and version is only relevant to UI.

2024-12-04 13:03 UTC, ghalliday commented
@cloLN this is still waiting for you...

2025-01-13 16:43 UTC, cloLN commented on devdoc/userdoc/JiraGuidelines.md
> +      - URL to environment.
I made another commit for this.  comment.  It should take care of it.

2025-01-14 14:36 UTC, ghalliday approved these changes
@cloLN thanks, please squash

2025-02-06 11:00 UTC, ghalliday requested changes
@cloLN your force push removed the last commit rather than squashing them.

2025-02-19 13:47 UTC, cloLN commented
> @cloLN your force push removed the last commit rather than squashing them.

Oof.  Let me try again.

2025-02-19 16:17 UTC, cloLN commented
I'm not quite sure how to roll back my changes.  Suggestions?  Should I try to revert changes in git or should I proceed with what I have here as it should fix all the concerns in the previous comments?

2026-01-26 19:58 UTC, cloLN commented
This PR should probably be deleted and a new one be made for Github Issues.

2026-02-06 15:38 UTC, cloLN commented
Will refactor for Github Issues

2026-02-06 15:38 UTC, closed without merging