HPCC-32688 Add JirabotMerge Github Action
hpcc-systems/HPCC-Platform pull request #19135
Opened 2024-09-20 00:58 UTC by jpmcmu

- Added a Github action to update Jira issues upon PR merger

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [X] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [X] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [X] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the CONTRIBUTORS document.
- [X] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [X] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-09-20 01:15 UTC, jpmcmu commented
**Notes on merge script:** The script uses the target branch and the git tags to determine the correct fix versions to add to the Jira issue. The logic for this is as follow:

- If merging into master, find latest tag version and increment to next major. IE: merging while 9.8.X is the latest release will result in a 9.10.0 fix version
- If merging into candidate-9.X, find the latest point in that minor increment it and to fix versions, increment minor and repeat process until we are at latest minor

Here is an example run from my fork merging into master. It added 9.10.0 to the Jira issue: https://github.com/jpmcmu/HPCC-Platform/actions/runs/10951362829

2024-09-23 13:21 UTC, ghalliday approved these changes
Looks good afaics.  I have added the relevant variable.

2024-09-26 12:38 UTC, GordonSmith approved these changes
Looks good - I didn't review the python code...

2024-09-26 12:38 UTC, GordonSmith commented on .github/workflows/jirabot-merge.yml
> +        uses: actions/checkout@v2
Should be version 4

2024-09-26 12:38 UTC, GordonSmith commented on .github/workflows/jirabot-merge.yml
> +      - uses: "actions/setup-python@v2"
Should be version 5?

2024-09-26 12:38 UTC, GordonSmith commented on .github/workflows/jirabot-merge.yml
> +        shell: python
Minor: Move shell to above the run for consistency with other actions

2024-09-26 12:40 UTC, GordonSmith requested changes
Just minor changes

2024-10-01 01:48 UTC, jpmcmu commented
@GordonSmith thanks for the review, made those changes

2024-10-04 11:13 UTC, ghalliday commented
@jpmcmu please look at the security warning - which does indicate a real vulnerability

2024-10-04 18:09 UTC, jpmcmu commented
@ghalliday Addressed the security issue and squashed

2024-10-10 12:16 UTC, GordonSmith approved these changes

2024-10-16 16:21 UTC, ghalliday commented
@jpmcmu can you explain how your change avoids the security problem?  Will it not sill be possible for someone to insert arbitrary text into a title, which will then be echoed?  I haven't understood why putting it in an environment variable first helps (other than confusing the checking tool)

2024-10-16 17:43 UTC, jpmcmu commented
@ghalliday Good question, I followed Github's recommendations on how to address the issue, but should have added a comment about why the changes addressed the security issue. (GitHubs: recommendation: https://github.com/hpcc-systems/HPCC-Platform/security/code-scanning/278)

Bash apparently treats the environment variable as a single string which is escaped and prevents injection.

2024-10-17 15:40 UTC, merged