HPCC-30886 Changelog automation to build-assets workflow
hpcc-systems/HPCC-Platform pull request #19219
Opened 2024-10-21 13:37 UTC by Michael-Gardner

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-10-21 13:40 UTC, Michael-Gardner commented
@cloLN and @xwang2713 please give this a good look before I ping Gordon on it.

I tested all the logic with a standalone workflow on my own repository.

The output: https://github.com/Michael-Gardner/HPCC-Platform/releases/tag/community_9.10.0-rc1
Action run: https://github.com/Michael-Gardner/HPCC-Platform/actions/runs/11392119417

2024-10-21 13:48 UTC, xwang2713 reviewed
Upload part looks good

2024-10-21 13:54 UTC, cloLN commented
Output files look good.

2024-10-29 11:02 UTC, GordonSmith requested changes
Do we want to relocate `gfortil/PrettyGitLogs` into hpcc-systems now or in the future?

2024-11-07 13:49 UTC, Michael-Gardner commented on .github/workflows/build-assets.yml
> +          repository: hpcc-systems/PrettyGitLogs
Fixed so we use the PrettyGitLogs in the hpcc-systems namespace

2024-11-08 13:30 UTC, xwang2713 approved these changes
Looks good

2024-11-20 09:49 UTC, GordonSmith approved these changes

2024-11-21 12:30 UTC, merged