HPCC-32946 Capture and report lookahead timings for hash distribute
hpcc-systems/HPCC-Platform pull request #19272
Opened 2024-11-05 14:22 UTC by shamser

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-11-08 13:24 UTC, jakesmith requested changes
I don't think this is right, the stream it's counting lookahead time *may* be the input that you want to count look ahead time, but createHashDistributor could be distributing anything, it's a general utility.

It would better to count the time it spent reading it's input, then let the calling activity gather it's time if it needed to.

2024-11-13 11:38 UTC, shamser commented
@jakesmith None of the code from the earlier PR remains, so I haven't retained the earlier commit in this PR.

2024-12-05 17:22 UTC, jakesmith reviewed
@shamser - please see comments

2024-12-05 17:22 UTC, jakesmith commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +                    MEASURE_CYCLES_ATOMIC(lookAheadCycles, owner.activity->queryTimeActivities(),
not a fan of macros :)
I doubt the complexity added to check enabled is worth. I vote for keeping it simple (and avoiding the macro), e.g.:

```
                    CCycleTimer rowTimer;
                    const void *row = input->ungroupedNextRow();
                    lookAheadCycles.fastAdd(rowTimer.elapsedCycles());
```

2024-12-05 17:22 UTC, jakesmith commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +        cycle_t lookAheadCycles = slaveTimerStats.lookAheadCycles;
can you change to :
```
        cycle_t lookAheadCycles = PARENT::queryLookAheadCycles();
```

2024-12-05 17:22 UTC, jakesmith commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +        cycle_t lookAheadCycles = slaveTimerStats.lookAheadCycles;
can you change to :
```
        cycle_t lookAheadCycles = PARENT::queryLookAheadCycles();
```

2024-12-05 17:22 UTC, jakesmith commented on thorlcr/activities/indexread/thindexreadslave.cpp
> +        cycle_t lookAheadCycles = slaveTimerStats.lookAheadCycles;
can you change to :
```
        cycle_t lookAheadCycles = PARENT::queryLookAheadCycles();
```

2024-12-05 17:22 UTC, jakesmith commented on thorlcr/activities/lookupjoin/thlookupjoinslave.cpp
> +        cycle_t lookAheadCycles = slaveTimerStats.lookAheadCycles;
can you change to :
```
        cycle_t lookAheadCycles = PARENT::queryLookAheadCycles();
```

2024-12-16 18:47 UTC, jakesmith approved these changes
@shamser - looks good. Please squash

2025-01-06 16:14 UTC, ghalliday reviewed
@shamser 
As far as I can see distributor->queryLookAheadCycles() (and rhsDistributor) is never merged into the slaveTimerStats.
I think it means the local time will be adjusted correctly, but they will not be reported for the activity.
I am not sure of the best solution.  Should local stats be calculated inside gatherActiveStats and should that sync distributed lookup stats before calculating?
@jakesmith any thoughts, especially as a general pattern.

2025-01-07 10:03 UTC, jakesmith commented
> @shamser As far as I can see distributor->queryLookAheadCycles() (and rhsDistributor) is never merged into the slaveTimerStats. I think it means the local time will be adjusted correctly, but they will not be reported for the activity. I am not sure of the best solution. Should local stats be calculated inside gatherActiveStats and should that sync distributed lookup stats before calculating? @jakesmith any thoughts, especially as a general pattern.

I see what you mean, the time is not folded into slaveTimerStats's ActivityTimeAccumulator::lookAheadCycles.
That is also true of totalCycles I think (e.g. CThorStrandedActivity::queryTotalCycles() const).

>but they will not be reported for the activity

but the reporting (via CSlaveActivity::serializeStats) uses the virtual (that calls through to the base COuputTiming::queryLookAheadCycles()), it doesn't read slaveTimerStats.lookAheadCycles directly.
What am I missing?

2025-01-07 11:43 UTC, shamser commented
> hat you mean, the time is not folded into slaveTimerStats's ActivityTimeAccumulator::lookAheadCycles. That is also true of totalCycles I think (e.g. CThorStrandedActivity::queryTotalCycles() const).
> 
> > but they will not be reported for the activity
> 
> but the reporting (via CSlaveActivity::serializeStats) uses the virtual (that calls through to the base COuputTiming::queryLookAheadCycles()), it doesn't read slaveTimerStats.lookAheadCycles directly. What am I missing?

Also, that the value of lookAheadCycles is needed to calculate local execute time (see CSlaveActivity::queryLocalCycles).  If it's merged to slaveTimerStats, there will need to be a lot more refactoring and complications.

2025-01-10 11:41 UTC, ghalliday commented
PR  https://github.com/hpcc-systems/HPCC-Platform/pull/19345/files changed that.  

That change will need regressing as far as lookahead cycles goes for this to work.

2025-01-14 14:19 UTC, ghalliday approved these changes
Please squash.

I think the clean way to implement this is
* restore the code to add the lookahead stats from thorcommon
* Add lookahead stats for distributors etc in gatherActiveStats() for the activity
* After all stats have been gathered and added, calculate the localExecuteTime stat from serializedStats and the inputs.

That way all lookahead stats does not need special casing - all active stats are handled in the same way.

2025-01-15 10:47 UTC, shamser commented
> That way all lookahead stats does not need special casing - all active stats are handled in the same way.

There are other activities that also handles lookahead like in this PR, so I've
I've created a jira to do this separately: https://hpccsystems.atlassian.net/browse/HPCC-33241

2025-01-20 11:46 UTC, merged