HPCC-32683 Fix issues with postmortem and container death
hpcc-systems/HPCC-Platform pull request #19296
Opened 2024-11-13 18:03 UTC by jakesmith

helm changes:
- Consistently generate command via addCommandAndLifecycle, and collect added container information in lifeCycleCtx based on containers added to lifeCycleCtx
- Add terminationGracePeriodSeconds option
- Mount ephemeral directories in distinct subPaths.
- Fix issues with postmortem's from different containers overwriting one another
- Add addPostRunContainer to generate postrun container, to monitor running containers.

script changes:
- add container_watch.sh for postrun pod.
- move all options handling into check_executes.sh

code changes:
- code grace time into k8s job file into, so that postjob clearup can also use
- Clear wuid file (prevents spurious error association)

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2024-11-15 12:59 UTC, ghalliday commented
Mark I would value you reviewing this change as well.

2024-11-28 14:22 UTC, ghalliday reviewed
Looks good as far as I can tell.  I didn't see any issues.

2024-12-03 20:04 UTC, jakesmith commented on helm/hpcc/templates/thor.yaml
> +          terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds | default 60 }}
yes, will change it to 600.

2024-12-03 20:05 UTC, jakesmith commented on initfiles/bin/container_watch.sh
> +#!/bin/bash
Have added comment blocks.

2024-12-03 20:05 UTC, jakesmith commented
@ghalliday - see 2nd commit.

2024-12-04 12:59 UTC, ghalliday approved these changes

2024-12-04 14:04 UTC, mckellyln requested changes, later dismissed
Looks good to me.
Approved.
(But I am not an expert in this area)

2024-12-04 14:06 UTC, mckellyln approved these changes
Looks good to me.
Approved.
(But I am not an expert in the area)

2024-12-04 17:31 UTC, jakesmith commented
@ghalliday - now squashed.

2024-12-09 16:44 UTC, merged