HPCC-33145: Optimize ESP server span creation
hpcc-systems/HPCC-Platform pull request #19373
Opened 2024-12-20 18:10 UTC by timothyklemm

- Create the server span as soon as the request information needed to decide
  if a span should be created is available.
- Change the server span's start time to reflect the time when the first line
  of the incoming request is read.

Signed-off-by: Tim Klemm <Tim.Klemm@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

2025-01-02 15:14 UTC, ghalliday reviewed
A couple of minor comments

2025-01-02 15:14 UTC, ghalliday commented on esp/bindings/http/platform/httpservice.cpp
> +                    strieq(methodName, "frame") ||
is "body" deliberately missing?

How do we ensure this stays in sync with the code later in the function?  Should at least be a comment.

2025-01-02 16:26 UTC, timothyklemm commented on esp/bindings/http/platform/httpservice.cpp
> +                    strieq(methodName, "frame") ||
Good catch. Not only is "body" not intentionally missing, but this doesn't account for the underscore that could be added to each name.

I'm thinking about defining a mapping of method name to enumerated value. This tracing check will only need to check the map for a matching entry. The subsequent handling code will be refactored to switch on the enumerated value. Only one set of string comparisons will be necessary, for a small performance boost.

2025-01-02 22:18 UTC, timothyklemm commented on esp/bindings/http/platform/httptransport.cpp
> +    m_receivedAt.now(); // use receipt of a first loe as the start time for a server span
Yep

2025-01-07 09:46 UTC, ghalliday requested changes
@timothyklemm I like the change.  There is one issue.

The other two comments I would not have added if there was no other comments.  They are there for discussion/to help the clarity of the code.

2025-01-07 09:46 UTC, ghalliday commented on esp/bindings/http/platform/httpservice.cpp
> +                    untracedRequestIt = getRequests.find(methodName);
This will not be executed if !isTracingEnabled, which means the switch statement later on will not work.  This needs to be unconditional - and because it is now using a map it should be ok to be unconditional.

2025-01-07 09:46 UTC, ghalliday commented on esp/bindings/http/platform/httpservice.cpp
> +                if (untracedRequestIt != getRequests.end())
picky style/encapsulation:  Rather than comparing against the map null entry I would add a None entry to UntracedGetMethod, and have a local variable of that type, which was filled in.  Why?  Because the later test is reasonably separated from where the variable is set up, and a test against getRequests.end() isn't immediately obvious that what it is checking.

2025-01-07 09:46 UTC, ghalliday commented on esp/bindings/http/platform/httpservice.cpp
> +enum class UntracedGetMethod
picky naming: What characteristic do these methods have that means they are not traced?  Is it they are simple file requests?  Something else?  That adjective should be used to describe the method, rather than "Untraced"  - because they are untraced for that reason, not the other way around.

2025-01-09 16:48 UTC, ghalliday reviewed
Looks a close.  A couple of minor comment.

2025-01-09 16:48 UTC, ghalliday commented on esp/bindings/http/platform/httpservice.cpp
> +// pprocessRequest to decide if the request should be traced before processing the request, without
typo: pprocessRequest

2025-01-09 16:48 UTC, ghalliday commented on esp/bindings/http/platform/httpservice.cpp
>          bool wantTracing = true;
minor: Should be initialised to queryTraceManager().isTracingEnabled()
otherwise it will be true if it is an unhandled get method even if that function returns false.

2025-01-10 08:54 UTC, ghalliday approved these changes
Looks good afaics.  Thanks, please squash.

2025-01-10 11:08 UTC, timothyklemm commented
@ghalliday it's squashed.

2025-01-10 11:40 UTC, timothyklemm commented
@ghalliday there's a build break on master unrelated to this change. I just ran into it after updating my local build.

2025-01-14 14:48 UTC, merged