HPCC-12131 Xref Upgrade
hpcc-systems/HPCC-Platform pull request #9107
Opened 2016-09-14 15:06 UTC by miguelvazq

Incorporate Xref into the new ecl watch paradigm.

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

2016-09-14 15:06 UTC, miguelvazq commented
@GordonSmith Please review.

2016-09-14 15:23 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 00d1e94190f0bd84329dbf870aa1a72b08145ecd
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-15 20:13 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 25fd2c7e14398eeb734c12f0975a4b2ed1f432ef
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-16 08:08 UTC, GordonSmith commented on esp/src/eclwatch/WsDFUXref.js
> +#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
Year?

2016-09-16 08:09 UTC, GordonSmith commented on esp/src/eclwatch/WsDFUXref.js
> +#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
Actually I believe we don't need this copyright message in each file any more as the single licence.txt should suffice?

2016-09-16 09:00 UTC, GordonSmith commented on esp/src/eclwatch/XrefDirectoriesWidget.js
> +            var context = this;
Context not used (I will be enabling this test with the linter soon!)

2016-09-16 09:02 UTC, GordonSmith commented on esp/src/eclwatch/XrefErrorsWarningsWidget.js
> +            var context = this;
context not used

2016-09-16 09:03 UTC, GordonSmith commented on esp/src/eclwatch/XrefErrorsWarningsWidget.js
> +            var context = this;
context not used

2016-09-16 09:03 UTC, GordonSmith commented on esp/src/eclwatch/XrefErrorsWarningsWidget.js
> +                        Status: context.i18n.Warning,
trailing comma

2016-09-16 09:03 UTC, GordonSmith commented on esp/src/eclwatch/XrefFoundFilesWidget.js
> +            var context = this;
context not used

2016-09-16 09:04 UTC, GordonSmith commented on esp/src/eclwatch/XrefFoundFilesWidget.js
> +            var context = this;
context not used

2016-09-16 09:04 UTC, GordonSmith commented on esp/src/eclwatch/XrefLostFilesWidget.js
> +            var context = this;
context not used

2016-09-16 09:04 UTC, GordonSmith commented on esp/src/eclwatch/XrefLostFilesWidget.js
> +            var context = this;
context not used.

2016-09-16 09:05 UTC, GordonSmith commented on esp/src/eclwatch/XrefOrphanFilesWidget.js
> +            var context = this;
context not used.

2016-09-16 09:06 UTC, GordonSmith commented on esp/src/eclwatch/XrefOrphanFilesWidget.js
> +                    if (confirm(context.i18n.RunningServerStrain)) {
context not declared.

2016-09-16 09:06 UTC, GordonSmith commented on esp/src/eclwatch/XrefOrphanFilesWidget.js
> +                        })
missing ;

2016-09-16 09:07 UTC, GordonSmith commented on esp/src/eclwatch/XrefOrphanFilesWidget.js
> +            var context = this;
Ahh here it is  - should move to top of procedure.

2016-09-16 09:07 UTC, GordonSmith commented on esp/src/eclwatch/XrefQueryWidget.js
> +            var context = this;
context not used

2016-09-16 09:09 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    CancelAllMessage: "This will attempt to stop any running jobs and clear the job queue. Do you wish to continue?",
How about "Abort running jobs and clear queue.  Do you wish to continue?"

2016-09-16 09:09 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    DeleteDirectories: "You are about to delete empty directories. Do you wish to continue?",
"Remove empty directories.  Do you with to continue?"

2016-09-16 09:11 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    FoundFileMessage: "A found file has all of its parts on disk that are not referenced in the Dali server. All the file parts are accounted for so they can be added back to the Dali server. They ca
Does this text come from the legacy version?  @JamesDeFabia do you want some input on these messages?

2016-09-16 09:12 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    LastMessage2: "Last Message:",
Could we move the ":" into the JS?

2016-09-16 09:12 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    LastRun2: "Last Run:",
Could we move the ":" into the JS?

2016-09-16 09:13 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    LostFileMessage: "A logical file that is missing at least one file part on both the primary and replicated locations in storage. The logical file is still referenced in the Dali server. Deleting
@JamesDeFabia Please review

2016-09-16 09:13 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    OrphanMessage: "An orphan file has partial file parts on disk. However, a full set of parts is not available to construct a complete logical file. These partial file parts, therefore, do not have
@JamesDeFabia Please review

2016-09-16 09:13 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    RunningServerStrain: "Running this process may take a long time and will put a heavy strain on the servers. Do you wish to continue?",
@JamesDeFabia Please Review

2016-09-16 09:15 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefDetailsWidget.html
> +            <div id="${id}_FoundFiles" title="Found Files" data-dojo-props="delayWidget: 'XrefFoundFilesWidget'" data-dojo-type="DelayLoadWidget">
translations

2016-09-16 09:15 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefDetailsWidget.html
> +            <div id="${id}_OrphanFiles" title="Orphan Files" data-dojo-props="delayWidget: 'XrefOrphanFilesWidget'" data-dojo-type="DelayLoadWidget">
translations

2016-09-16 09:15 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefDetailsWidget.html
> +            <div id="${id}_LostFiles" title="Lost Files" data-dojo-props="delayWidget: 'XrefLostFilesWidget'" data-dojo-type="DelayLoadWidget">
translations

2016-09-16 09:15 UTC, richardkchapman commented on esp/src/eclwatch/WsDFUXref.js
> +#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
@fvillanustre Can you comment on what our policy on copyright messages in files needs to be?

2016-09-16 09:15 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefDetailsWidget.html
> +            <div id="${id}_Errors" title="Errors/Warnings" data-dojo-props="delayWidget: 'XrefErrorsWarningsWidget'" data-dojo-type="DelayLoadWidget">
translations

2016-09-16 09:15 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefDetailsWidget.html
> +            <div id="${id}_Directories" title="Directories" data-dojo-props="delayWidget: 'XrefDirectoriesWidget'" data-dojo-type="DelayLoadWidget">
translations

2016-09-16 09:16 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +            };*/
remove commented code.

2016-09-16 09:16 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +                    if (confirm("Running this process may take a long time and will put a heavy strain on the servers. Do you wish to continue?")) {
translation

2016-09-16 09:16 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +             }).placeAt(this.directories.domNode, "after");*/
remove commented code

2016-09-16 09:16 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +            new ToolbarSeparator().placeAt(this.foundFiles.domNode, "before");*/
remove commented code.

2016-09-16 09:17 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +            }*/
remove commented code (is filter used in this widget?)

2016-09-16 09:17 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +                context.grid.set("query", /*this.getFilter()*/{});
remove commented code (and all refs to filters?)

2016-09-16 09:17 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +                var context = this;
context not used.

2016-09-16 09:18 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefLostFilesWidget.js
> +            };*/
remove commented code

2016-09-16 09:18 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefLostFilesWidget.js
> +                    if (confirm("Running this process may take a long time and will put a heavy strain on the servers. Do you wish to continue?")) {
translation

2016-09-16 09:18 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefLostFilesWidget.js
> +             }).placeAt(this.directories.domNode, "after");*/
remove commented code.

2016-09-16 09:18 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefLostFilesWidget.js
> +            new ToolbarSeparator().placeAt(this.foundFiles.domNode, "before");*/
remove commented code.

2016-09-16 09:19 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefLostFilesWidget.js
> +            }*/
remove commented code.

2016-09-16 09:19 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefLostFilesWidget.js
> +                context.grid.set("query", /*this.getFilter()*/{});
remove commentedd code and all refs to filters?

2016-09-16 09:19 UTC, GordonSmith requested changes

2016-09-16 13:18 UTC, miguelvazq commented on esp/src/eclwatch/XrefDetailsWidget.js
> +            if (currSel.id == this.widget._FoundFiles.id && !this.widget._FoundFiles.__hpcc_initalized) {
I started seeing those in your code review and the `for (key` will now == `for (var key`

2016-09-16 15:22 UTC, JamesDeFabia commented on esp/src/eclwatch/nls/hpcc.js
> +    DeleteDirectories: "You are about to delete empty directories. Do you wish to continue?",
"Remove empty directories. Do you wish to continue?"

2016-09-16 15:24 UTC, JamesDeFabia commented on esp/src/eclwatch/nls/hpcc.js
> +    LostFileMessage: "A logical file that is missing at least one file part on both the primary and replicated locations in storage. The logical file is still referenced in the Dali server. Deleting
this text is fine

2016-09-16 15:26 UTC, JamesDeFabia commented on esp/src/eclwatch/nls/hpcc.js
> +    OrphanMessage: "An orphan file has partial file parts on disk. However, a full set of parts is not available to construct a complete logical file. These partial file parts, therefore, do not have
"An orphan file has partial file parts on disk. However, a full set of parts is not available to construct a complete logical file. This no reference to these file parts in the Dali server."

2016-09-16 15:26 UTC, JamesDeFabia commented on esp/src/eclwatch/nls/hpcc.js
> +    RunningServerStrain: "Running this process may take a long time and will put a heavy strain on the servers. Do you wish to continue?",
This text is ok

2016-09-19 09:22 UTC, richardkchapman commented
@miguelvazq Back to you

2016-09-19 19:35 UTC, miguelvazq commented on esp/src/eclwatch/nls/hpcc.js
> +    LastMessage2: "Last Message:",
How about in the html I can do something like `<label class="Prompt" for="${id}LastMessage">${i18n.LastMessage2}:</label>`

2016-09-19 19:44 UTC, miguelvazq commented
@GordonSmith Updated

2016-09-19 20:05 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: b7dd3691f87e6593d99006b4c9f0d6c59e8dd402
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-20 06:05 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    FoundFile2: "Found File:",
This can be removed

2016-09-20 06:06 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    LostFile2: "Lost File:",
Are the ":" going to be moved into the HTML?

2016-09-20 06:06 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    OrphanFile2: "Orphan File:",
Are the ":" going to be moved into the HTML?

2016-09-20 06:06 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    title_DirectoriesFor: "Directories for:",
Are the ":" going to be moved into the HTML?

2016-09-20 06:06 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    title_ErrorsWarnings: "Errors/Warnings for:",
Are the ":" going to be moved into the HTML?

2016-09-20 06:06 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    title_FoundFilesFor: "Found files for:",
Are the ":" going to be moved into the HTML?

2016-09-20 06:06 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    title_LostFilesFor: "Lost files for:",
Are the ":" going to be moved into the HTML?

2016-09-20 06:06 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    title_OrphanFilesFor: "Orphan files for:",
Are the ":" going to be moved into the HTML?

2016-09-20 06:07 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    LastMessage2: "Last Message",
LastMessage2 Not needed (same as LastMessage)

2016-09-20 06:07 UTC, GordonSmith commented on esp/src/eclwatch/nls/hpcc.js
> +    LastRun2: "Last Run",
LastRun2 duplicate of LastRun

2016-09-20 06:08 UTC, GordonSmith requested changes

2016-09-21 14:51 UTC, richardkchapman commented
@miguelvazq Back to you

2016-09-23 13:56 UTC, miguelvazq commented
@GordonSmith updated.

2016-09-23 14:08 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 0849c7dbf32f0f3e8bc5216b335ca802a782b8e9
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-23 14:23 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: f6f50a979b4107697d401380f59d15c2749c04bc
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-26 14:05 UTC, GordonSmith commented on esp/src/eclwatch/XrefFoundFilesWidget.js
> +                    Size: {label: this.i18n.Size, width: 30, sortable: true},
Trailing ","

2016-09-26 14:06 UTC, GordonSmith commented on esp/src/eclwatch/XrefOrphanFilesWidget.js
> +        createGrid: function (domID) {\
trailing "\"

2016-09-26 14:07 UTC, GordonSmith commented on esp/src/eclwatch/XrefQueryWidget.js
> +                    Status: {label: this.i18n.LastMessage, width: 30, sortable: false},
trailing ","

2016-09-26 14:10 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +            };*/
Still needs removing

2016-09-26 14:10 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +                    if (confirm("Running this process may take a long time and will put a heavy strain on the servers. Do you wish to continue?")) {
Still needs translation

2016-09-26 14:11 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +             }).placeAt(this.directories.domNode, "after");*/
Commented code still needs removing

2016-09-26 14:11 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +            new ToolbarSeparator().placeAt(this.foundFiles.domNode, "before");*/
Needs removing

2016-09-26 14:11 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +            }*/
commented code

2016-09-26 14:11 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +                context.grid.set("query", /*this.getFilter()*/{});
Commented code.

2016-09-26 14:11 UTC, GordonSmith commented on esp/src/eclwatch/templates/XrefErrorsWarningsWidget.js
> +                var context = this;
Context can be removed?

2016-09-26 14:11 UTC, GordonSmith requested changes

2016-09-26 15:16 UTC, miguelvazq commented
I removed an accidental file that was added into templates. The ones with the commented code comments. All else was updated.

2016-09-26 15:24 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: bc843747f2866f60d5365edd68547ea6f299374f
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-27 16:46 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 5a0fb3bccbbe5731ecbacb1d8fa131e25ee51d1a
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-28 09:59 UTC, GordonSmith approved these changes

2016-09-28 10:02 UTC, merged