HPCC-12464 Dynamic ESDL U/I
hpcc-systems/HPCC-Platform pull request #9118
Opened 2016-09-15 20:06 UTC by miguelvazq

Incorporate a GUI for dynamic ESDL.

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

2016-09-15 20:06 UTC, miguelvazq commented
@GordonSmith Please review.

2016-09-15 20:28 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 7c7befbb7ff7976ed93d028e19dd5a843312258b
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-19 15:55 UTC, miguelvazq commented
FYI @JamesDeFabia

2016-09-21 14:49 UTC, richardkchapman commented
@GordonSmith

2016-09-22 08:00 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDetailsWidget.js
> +            this.inherited(arguments);
Very minor:  always cleaner to have the inherited call as the first line item.

2016-09-22 08:01 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDetailsWidget.js
> +                label: "Apply",
Translation

2016-09-22 08:02 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDetailsWidget.js
> +                                if (publishresponse.PublishESDLBindingResponse.status.Code === 0) {
Does this need an "exists" test before using it (there might have been an exception)?

2016-09-22 08:04 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDetailsWidget.js
> +                });
Minor: indentation

2016-09-22 08:05 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLMethodWidget.js
> +            }).placeAt(this.openButton.domNode, "after");*/
Remove commented code.

2016-09-22 08:05 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLMethodWidget.js
> +
Blank line

2016-09-22 08:06 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLMethodWidget.js
> +                label: "Attribute",
Translation?

2016-09-22 08:06 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLMethodWidget.js
> +                label: "Value",
Translation?

2016-09-22 08:06 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLMethodWidget.js
> +                label: "Add Attribute(s)"
Translation?

2016-09-22 08:06 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLMethodWidget.js
> +               return retVal;
Minor: no need for retVal;

2016-09-22 08:14 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLMethodWidget.js
> +            var hasSelection = false;
Not used

2016-09-22 08:14 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLMethodWidget.js
> +                hasSelection = true;
Not used

2016-09-22 08:14 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLQueryWidget.js
> +               return retVal;
Minor: retval not needed

2016-09-22 08:17 UTC, GordonSmith commented on esp/src/eclwatch/templates/DynamicESDLDetailsWidget.html
> +            <div id="${id}_Binding" title="Binding" data-dojo-type="dijit.layout.BorderContainer">
Translation

2016-09-22 08:17 UTC, GordonSmith commented on plugins/cassandra/cpp-driver
> +Subproject commit d7bbad34db39a51f209c6fadd07c9ec3a0bb86b7
This should not be in your PR

2016-09-22 08:18 UTC, GordonSmith requested changes

2016-09-23 14:37 UTC, miguelvazq commented on esp/src/eclwatch/DynamicESDLQueryWidget.js
> +               return retVal;
Tested and children do not show if removed.

2016-09-23 14:38 UTC, miguelvazq commented on esp/src/eclwatch/DynamicESDLMethodWidget.js
> +               return retVal;
Tested and children do not show if removed.

2016-09-23 14:38 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 73124a158d2d10c21c23257b3deac9af2ca6be92
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-23 14:53 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: b158824d557128cc5eef70d945725bf030fa9fe9
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-26 10:33 UTC, richardkchapman commented
@miguelvazq This is yours...

2016-09-26 13:17 UTC, GordonSmith commented on esp/src/eclwatch/TargetSelectClass.js
> +        var context = this;
Indentation

2016-09-26 13:18 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLQueryWidget.js
> +               return retVal;
I meant:  ```return this.query({__hpcc_parentName: parent.__hpcc_id}, options);``` (minor)

2016-09-26 13:19 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLMethodWidget.js
> +               return retVal;
I meant ```return this.query({__hpcc_parentName: parent.__hpcc_id}, options);``` (minor)

2016-09-26 13:20 UTC, GordonSmith approved these changes
Just minor + indentation comments

2016-09-26 14:08 UTC, miguelvazq commented
@GordonSmith updated.

2016-09-26 14:32 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: dacef99e538846b62d6c77fafa39ff3c70cdc800
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-28 14:26 UTC, miguelvazq commented
Rebased to fix conflicts.

2016-09-28 14:58 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 26da7f104d785c362162c03aa396d9f26f887db7
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-29 09:12 UTC, GordonSmith approved these changes
Good to go.

2016-09-29 09:21 UTC, richardkchapman commented
Merged manually to resolve conflict

2016-09-29 09:21 UTC, closed without merging