HPCC-16245 Support rootless array in ESDL ECM
hpcc-systems/HPCC-Platform pull request #9131
Opened 2016-09-18 02:01 UTC by wangkx

Also fix a bug for retrieving primitive array input

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

2016-09-18 02:01 UTC, wangkx commented
@afishbeck please review

2016-09-18 02:09 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: be40fa3b6a3f6215abca499a4af4e1970861bf2c
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-21 23:09 UTC, afishbeck commented on esp/esdllib/esdl_transformer2.cpp
> +                        {
Why did this EsdlArray (non-list) behavior change? It looks like you are supporting multiple sections even for EsdlArrays now?

 ```
<root>
   <myarray>
     <item>a</item>
     <item>b</item>
     <item>c</item>
  </myarray>
  <tag1>www</tag1>
  <myarray>
     <item>x</item>
     <item>y</item>
     <item>z</item>
  </myarray>
</root>
```
?

2016-09-21 23:15 UTC, afishbeck commented on esp/esdllib/esdl_transformer2.cpp
> +                            child.process(ctx, pt->queryPropTree(tagname), child.queryOutputName(ctx), &local, count);
Why is the (numChildren<2) case needed.  Wouldn't looping through the ForEach() below work the same?

2016-09-21 23:18 UTC, afishbeck commented on esp/esdllib/esdl_transformer2.cpp
> +                            ///ctx.writer->outputEndArray(tagname);
Have you tested this?  I'm wondering if the commented out "///ctx.writer->outputEndArray(tagname);" should be added back to get the state right?  or is the writer smart enough to figure out that the rewind removes the beginarray?

2016-09-21 23:30 UTC, afishbeck requested changes
A couple questions.

2016-09-22 01:39 UTC, wangkx commented on esp/esdllib/esdl_transformer2.cpp
> +                        {
Just a mistake. I will change it back.

2016-09-22 01:41 UTC, wangkx commented on esp/esdllib/esdl_transformer2.cpp
> +                            child.process(ctx, pt->queryPropTree(tagname), child.queryOutputName(ctx), &local, count);
You are correct. I will fix.

2016-09-22 01:51 UTC, wangkx commented on esp/esdllib/esdl_transformer2.cpp
> +                            ///ctx.writer->outputEndArray(tagname);
I guess I does not understand the rewindTo(). Here I want to 'rewind' to the position (prevLocation) before the outputBeginArray(). Why should I output (write) the EndArray if I know that the EndArray will be 'rewind' or 'removed' by the rewindTo()?

2016-09-22 02:16 UTC, wangkx commented on esp/esdllib/esdl_transformer2.cpp
> +                            ///ctx.writer->outputEndArray(tagname);
I just tested the rewindTo() and it works without the outputEndArray().

2016-09-22 02:17 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: acb0216252d2c9b683a7675af75d52813b7aa2ad
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-22 13:32 UTC, afishbeck commented on esp/esdllib/esdl_transformer2.cpp
> +                            ///ctx.writer->outputEndArray(tagname);
Ok good.  I think that commented line made me think of an old bug, I'm glad it works as it should.  Remove the commented line?

2016-09-23 00:26 UTC, wangkx commented on esp/esdllib/esdl_transformer2.cpp
> +                            ///ctx.writer->outputEndArray(tagname);
I left the commented line there in order to get the second opinion from you just in case I miss something. Now, it has been removed.

2016-09-23 00:40 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: c262d1095d7d8b8d700b60da8dddc1851343d0a3
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-23 10:36 UTC, richardkchapman commented
@afishbeck Is this good to merge now?

2016-09-23 13:57 UTC, afishbeck approved these changes
Looks good.

2016-09-23 14:52 UTC, merged