HPCC-15608 Method Level Authentication
hpcc-systems/HPCC-Platform pull request #9134
Opened 2016-09-19 21:13 UTC by gaojx

- Add ESDL attribute: auth_feature
- In Dynamic ESDL, the auth manager can use this attribute to auth a method

Signed-off-by: Jiafu Gao <Jiafu.Gao@lexisnexis.com>

2016-09-19 21:14 UTC, gaojx commented
@rpastrana, @afishbeck please code review.

2016-09-19 21:20 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 96e848b09c2897a1dffffcc66671d16666310fcf
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-20 12:40 UTC, rpastrana commented on CMakeLists.txt
> -if(UNIX AND NOT APPLE)
this cmake check shouldn't be removed.

2016-09-20 12:45 UTC, rpastrana commented on esp/esdllib/esdl_transformer2.cpp
> +            if (!ctx.authorizeFeature(auth_feature,access) || access!=SecAccess_Full)
the auth_feature level should be configurable, here it's always assumed "FULL", even if SCApps will always set to full.
auth_feature("featurename:level");

2016-09-20 12:46 UTC, rpastrana requested changes
A couple of changes required.

2016-09-20 13:31 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: dc17a766a80f273f07de02477c55d8e3135f8750
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-20 17:55 UTC, rpastrana commented
@gaojx one more change needed.

2016-09-20 18:01 UTC, gaojx commented
The access level is implemented:  The commit is: 9f1b5fa3df3b16a1ce21e789cae32e2bce593cb1. However it does not show up in github somehow.

2016-09-20 18:06 UTC, gaojx commented
Now it shows up. Please code review again: @rpastrana

2016-09-20 18:24 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 9f1b5fa3df3b16a1ce21e789cae32e2bce593cb1
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-20 18:28 UTC, rpastrana commented
@gaojx looks fine.

2016-09-20 18:29 UTC, rpastrana commented
@gaojx when you're ready, let Richard know this PR is ready to be merged.

2016-09-20 18:30 UTC, gaojx commented
@richardkchapman this PR is ready for merging.

2016-09-21 11:55 UTC, merged