HPCC-15656: Add the ability to log Response Time
hpcc-systems/HPCC-Platform pull request #9138
Opened 2016-09-20 19:34 UTC by gaojx

- add ResponseTime in ms to logging

Signed-off-by: Jiafu Gao <Jiafu.Gao@lexisnexis.com>

2016-09-20 19:35 UTC, gaojx commented
@wangkx please code review

2016-09-20 19:54 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 9e6fa8a11c942640f9ce5f5e1be83016138581f5
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-20 20:40 UTC, wangkx approved these changes
@gaojx looks fine.

2016-09-20 21:10 UTC, gaojx commented
@richardkchapman this PR is ready to merge.

2016-09-21 11:27 UTC, richardkchapman requested changes
THe commit message says it is logging the response time in ms, but this code looks to me as though it is converting to seconds (/1000).

I would have thought ms was preferable, in which case shouldn't the /1000 be removed?

2016-09-21 11:28 UTC, richardkchapman commented
@gaojx One question

2016-09-21 11:35 UTC, gaojx commented
The ms is a typo. It should be in seconds. In all our transaction log, the response_time is decimal(8,4), and the unit is second.

2016-09-21 11:40 UTC, richardkchapman commented
What you're storing will be truncated to the complete second... if you want a decimal(8,4) then you should do a setPropString and a sprintf, or something like that, I would have thought?

2016-09-21 11:44 UTC, gaojx commented
You are right. Will make the change.

2016-09-21 12:38 UTC, gaojx commented
@wangkx please review.

2016-09-21 12:50 UTC, wangkx commented on esp/logging/loggingmanager/loggingmanager.cpp
> +        espContextTree->addProp("ResponseTime", VStringBuffer("%.4f", (msTick()-espContext.queryCreationTime())/1000.0));
You may need to add .str() after the VStringBuffer to match: void addProp(const char *xpath, const char *val).

2016-09-21 12:52 UTC, gaojx commented on esp/logging/loggingmanager/loggingmanager.cpp
> +        espContextTree->addProp("ResponseTime", VStringBuffer("%.4f", (msTick()-espContext.queryCreationTime())/1000.0));
I think it is optional: the operator const char* () will do this conversation automatically.

2016-09-21 12:53 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: b963a2c60474e8d0a52cc16c48a4f39119704556
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-21 12:55 UTC, merged