HPCC-14453 Preflight upgrade
hpcc-systems/HPCC-Platform pull request #9165
Opened 2016-09-23 22:12 UTC by miguelvazq

Add pre flight submission form into new ECL Watch.

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

2016-09-23 22:12 UTC, miguelvazq commented
@GordonSmith Please review.

2016-09-23 22:35 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: b316a1645e4b7fd65026bb257842a869e990c8f7
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-26 13:05 UTC, GordonSmith commented on esp/src/eclwatch/PreflightDetailsWidget.js
> +                            [clean] : {
What does this syntax do (I have not seen it before)?

2016-09-26 13:05 UTC, GordonSmith commented on esp/src/eclwatch/PreflightDetailsWidget.js
> +                    var clean = finalColumns[index].replace(/([~!@#$%^&*()_+=`{}\[\]\|\\:;'<>,.\/? ])+/g, '').replace(/^(-)+|(-)+$/g,'');
Is this removing HTML formatting?

2016-09-26 13:05 UTC, GordonSmith commented on esp/src/eclwatch/PreflightDetailsWidget.js
> +                    } if (clean === 'State') {
The "if" should be on a new line.

2016-09-26 13:10 UTC, GordonSmith commented on esp/src/eclwatch/TopologyWidget.js
> +                                    [MachineInformationCount]: 1000,
Is this syntax correct?

2016-09-26 13:10 UTC, GordonSmith commented on esp/src/eclwatch/TopologyWidget.js
> +                                [TargetClusterCount]: 1000,
Is this syntax correct?

2016-09-26 13:13 UTC, GordonSmith commented on esp/src/eclwatch/TopologyWidget.js
> +            var context = this;
should declare ```var element;``` here and then assign values to it in the switch statement

2016-09-26 13:15 UTC, GordonSmith requested changes

2016-09-26 13:15 UTC, GordonSmith commented
Some questions.

2016-09-26 13:32 UTC, miguelvazq commented on esp/src/eclwatch/PreflightDetailsWidget.js
> +                    var clean = finalColumns[index].replace(/([~!@#$%^&*()_+=`{}\[\]\|\\:;'<>,.\/? ])+/g, '').replace(/^(-)+|(-)+$/g,'');
Since the response returns "Column Name" I am removing any spaces and or special characters in it so that they come back like so: "ColumnName"

2016-09-26 13:38 UTC, miguelvazq commented on esp/src/eclwatch/PreflightDetailsWidget.js
> +                            [clean] : {
This creates dynamic properties with the value from clean which in turn is 'Condition' 'State' 'RoxieCluster'

2016-09-26 13:39 UTC, miguelvazq commented on esp/src/eclwatch/TopologyWidget.js
> +                                    [MachineInformationCount]: 1000,
I verified with @wangkx this count seems to increase based on selections and is subjective.

2016-09-26 13:39 UTC, miguelvazq commented on esp/src/eclwatch/TopologyWidget.js
> +                                [TargetClusterCount]: 1000,
I verified with @wangkx this count seems to increase based on selections and is subjective.

2016-09-26 14:01 UTC, miguelvazq commented
@GordonSmith updated.

2016-09-26 14:23 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 52dd2a39bf11fc437fc73f65156ec8c3bf958300
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-26 15:19 UTC, GordonSmith commented on esp/src/eclwatch/PreflightDetailsWidget.js
> +                            [clean] : {
I didn't know you could do that with this syntax!

2016-09-28 10:03 UTC, richardkchapman commented
@miguelvazq Needs rebasing for a clean merge

2016-09-28 14:24 UTC, miguelvazq commented
@richardkchapman rebased.

2016-09-28 14:50 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 684916f238f8de5c3d4b5b967bc733b188d754b5
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-28 15:16 UTC, GordonSmith requested changes

2016-09-28 16:13 UTC, miguelvazq commented
@GordonSmith changes made after latest comments

2016-09-28 16:32 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 37283ae0c8663cb2e57db8814e7aeea57a7585b4
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-29 06:36 UTC, richardkchapman commented
@GordonSmith Please re-review/approve

2016-09-29 07:18 UTC, GordonSmith approved these changes

2016-09-29 07:18 UTC, GordonSmith commented
Good to go.

2016-09-29 08:33 UTC, merged