HPCC-16345 Optimize MAX(unsigned, 0) and IF(unsigned < 0, 0, unsigned)
hpcc-systems/HPCC-Platform pull request #9170
Opened 2016-09-26 13:48 UTC by richardkchapman

Helps avoid C++ compiler warnings.

Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

2016-09-26 13:48 UTC, richardkchapman commented
@ghalliday Please review

2016-09-26 14:08 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 6c28ef8cf4e1cc26a6e3a0835a51aa8c57f148a1
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-26 14:30 UTC, ghalliday commented on ecl/hql/hqlfold.cpp
> +            case no_ge:
Should be no_gt

2016-09-26 14:36 UTC, ghalliday commented on ecl/hql/hqlfold.cpp
> +        if (isUnsigned && rightValue->getIntValue()==0)
could use isZero(rightChild)

2016-09-26 14:38 UTC, ghalliday commented on ecl/hql/hqlfold.cpp
> +        bool isUnsigned = lType->getTypeCode()==type_int && !lType->isSigned();
Could also match decimal, swapint, and packed int.  Worth extracting into an isUnsignedType()

2016-09-26 14:40 UTC, ghalliday commented on ecl/hql/hqlfold.cpp
> +                            }
unlikely to catch anything, but if no_minlist it could return LINK(cur).

2016-09-26 14:40 UTC, ghalliday requested changes
@richardkchapman this also needs some test cases.

2016-09-26 16:21 UTC, richardkchapman commented
Repushed to address comments - @ghalliday Please re-review

2016-09-26 16:39 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 7c0deeb4f54f688ab98df7c5618a84096bd4e29b
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-27 09:37 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 6342d90f83c11c80be78f8be4fa0870ac2be5bdc
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-27 13:09 UTC, ghalliday commented
@richardkchapman I'll run the regression test.  Curious why you didn't also support decimal and swap int.

2016-09-27 13:10 UTC, ghalliday commented
It still needs a test case or two...

2016-09-27 15:54 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 9b9767c165ae43d2ae3c40a3803f798e4d5a123d
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-28 10:16 UTC, ghalliday approved these changes

2016-09-28 10:16 UTC, merged