HPCC-16369 Fix missing child query progress issue
hpcc-systems/HPCC-Platform pull request #9184
Opened 2016-09-28 11:37 UTC by jakesmith

Child queries which did not require meta data initialization,
did not flag master that they were initialized and as a
consequence their progress data was not updated, so missing from
the graph control.

Signed-off-by: Jake Smith <jake.smith@lexisnexis.com>

2016-09-28 11:37 UTC, jakesmith commented
@ghalliday - please review

2016-09-28 11:53 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 747da2048ff87f5225f2632d78dd49d00c404d8c
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-28 12:11 UTC, jakesmith commented
@ghalliday - don't merge, I spotted an issue.

2016-09-28 12:20 UTC, ghalliday requested changes
@jakesmith Changes look broadly correct.  atomic operation should probably be changed.

2016-09-28 12:20 UTC, ghalliday commented on thorlcr/graph/thgraph.hpp
> +        return progressUpdated.compare_exchange_strong(b, false);
I think progressUpdated.exchange(false); is more efficient, and also clearer in its intent.

2016-09-28 12:20 UTC, ghalliday commented on thorlcr/graph/thgraph.hpp
> +    bool hasProgressUpdated()
minor: it isn't clear from the function name that it has the side-effect of clearing the current setting.

2016-09-28 12:57 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 2f2896647d093ee2d9a809608c06d83b702f107c
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-28 13:02 UTC, jakesmith commented on thorlcr/graph/thgraph.hpp
> +        return progressUpdated.compare_exchange_strong(b, false);
agreed, will change.

2016-09-28 13:08 UTC, jakesmith commented on thorlcr/graph/thgraph.hpp
> +    bool hasProgressUpdated()
Have changed.

2016-09-28 13:08 UTC, jakesmith commented
@ghalliday - please see update.

2016-09-28 13:27 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: fabab9b7bfd04eb2ddd9c55443d58688e5a8e1ca
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-29 15:01 UTC, ghalliday commented on thorlcr/graph/thgraph.hpp
> +        bool b=true;
trivial: unused variable

2016-09-29 15:32 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: ccb5e6ff37aa12b6c80e43ebdb345f4f38bf8393
Build: success
Install hpccsystems-platform-community_6.1.0-trunk0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:83 passed:83 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-09-30 09:39 UTC, merged