HPCC-16400 Document Keyboard Shortcuts in IDE
hpcc-systems/HPCC-Platform pull request #9209
Opened 2016-10-03 19:46 UTC by JamesDeFabia

Signed-off-by: Jim DeFabia <jamesdefabia@lexisnexis.com>
@dehilsterlexis Please review (PDF sent)

2016-10-03 19:58 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 1569db7a8e5b1718de6fb1a62722a02bbf489fdf
Build: success
Install hpccsystems-platform-documentation_6.0.0-continuous0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:81 passed:81 failed:0

HPCC Stop: OK
HPCC Uninstall: OK

2016-10-04 09:39 UTC, GordonSmith requested changes
Minor comments

2016-10-04 09:39 UTC, GordonSmith commented on docs/HPCCClientTools/CT_Mods/CT_ECL_IDE.xml
> +                  <entry>Print</entry>
Not sure we ever supported printing?

2016-10-04 09:39 UTC, GordonSmith commented on docs/HPCCClientTools/CT_Mods/CT_ECL_IDE.xml
> +                  <entry>Toggle Horizontal scroll bar</entry>
Should be "Toggle Word Wrap"

2016-10-04 13:12 UTC, JamesDeFabia commented on docs/HPCCClientTools/CT_Mods/CT_ECL_IDE.xml
> +                  <entry>Print</entry>
Printing with Ctrl+P works for me :)

2016-10-04 13:12 UTC, JamesDeFabia commented on docs/HPCCClientTools/CT_Mods/CT_ECL_IDE.xml
> +                  <entry>Toggle Horizontal scroll bar</entry>
Removing this row, Toggle Word Wrap is already listed above

2016-10-04 13:43 UTC, JamesDeFabia commented
@GordonSmith Edits made. please look again. Note that ctrl+P does work so I left that in

2016-10-04 13:44 UTC, merged

2016-10-04 13:45 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 5c8a28961fe7eb589d8b0dc63ae3c0addf00a91b
Build: success
Install hpccsystems-platform-documentation_6.0.0-continuous0.el6.x86_64.rpm
HPCC Start: OK
Unittest result: total:81 passed:81 failed:0

HPCC Stop: OK
HPCC Uninstall: OK