HPCC-16458 Spray regression test cases failed after drop zone restriction reactivated.
hpcc-systems/HPCC-Platform pull request #9250
Opened 2016-10-10 02:53 UTC by AttilaVamos

Rewrite test cases to avoid spray from /testing/regress/download:
 1. generate simple dataset
 2. despray it to default drop zone
 3. (fixed, variable) spray it back from the default drop zone

Signed-off-by: Attila.Vamos <attila.vamos@gmail.com>

2016-10-10 03:11 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: d9ee3f2bb603826b85101fe25413d0485a9588d9
Build: success
Install hpccsystems-platform-community_6.2.0-rc2.el6.x86_64.rpm
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| spray_test | Pass | Excl. | Excl. |
| spray_test2 | Pass | Excl. | Excl. |
 
HPCC Stop: OK
HPCC Uninstall: OK

2016-10-10 13:33 UTC, AttilaVamos commented
Actually it is still WIP.

2016-10-11 02:26 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 8959d6b75b00f9fa7905a854c1a27f4d07e14556
Build: success
Install hpccsystems-platform-community_6.2.0-rc3.el6.x86_64.rpm
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| spray_test (sprayFixed=false) | Pass | Excl. | Excl. |
| spray_test (sprayFixed=true) | Pass | Excl. | Excl. |
 
HPCC Stop: OK
HPCC Uninstall: OK

2016-10-11 02:29 UTC, AttilaVamos commented
@ghalliday please review.

2016-10-17 08:55 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 9c8fa7a76cb57f07c684d336f7f29f50d179c530
Build: success
Install hpccsystems-platform-community_6.2.0-rc3.el6.x86_64.rpm
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| spray_test (sprayFixed=false) | Pass | Excl. | Excl. |
| spray_test (sprayFixed=true) | Pass | Excl. | Excl. |
 
HPCC Stop: OK
HPCC Uninstall: OK

2016-10-17 09:12 UTC, AttilaVamos commented
@ghalliday it is modified. It compares result dataset inside the ECL and outputs 'Passed' or 'Fail' instead. Please review.

2016-10-19 09:03 UTC, ghalliday requested changes
@AttilaVamos looks ok - one comment on the scope of the files being produced.

2016-10-19 09:03 UTC, ghalliday commented on testing/regress/ecl/spray_test.ecl
> +sprayOutFileName := '~::spray_test';
I think other files generated by the regression suite are in the regress (check that!) scope, this should be as well.

2016-10-19 09:03 UTC, ghalliday commented on testing/regress/ecl/spray_test.ecl
> +sprayPrepFileName := '~::spray_prep';
same comment as below

2016-10-19 09:03 UTC, ghalliday commented on testing/regress/ecl/spray_test.ecl
> +   boolean result := (0 = COUNT(JOIN(ds1, ds2, left.name=right.name, FULL ONLY, LOCAL)));
Shouldn't really have LOCAL here.  It is ignored by roxie and hthor, and would be wrong for thor.

2016-10-19 09:03 UTC, ghalliday commented on testing/regress/ecl/spray_test.ecl
> +  BOOLEAN good;
I was concerned that this would generate true/false in the output, but that doesn't seem to be the case.

2016-10-19 12:21 UTC, AttilaVamos commented on testing/regress/ecl/spray_test.ecl
> +  BOOLEAN good;
Ok

2016-10-19 12:24 UTC, AttilaVamos commented on testing/regress/ecl/spray_test.ecl
> +sprayPrepFileName := '~::spray_prep';
Ok

2016-10-19 12:24 UTC, AttilaVamos commented on testing/regress/ecl/spray_test.ecl
> +sprayOutFileName := '~::spray_test';
Ok

2016-10-19 12:32 UTC, AttilaVamos commented
@ghalliday updated, please check.

2016-10-19 12:55 UTC, HPCCSmoketest commented
Automated Smoketest 
Sha: 04e717fbfe9ac63a3a6ed05b07c7d7c1b866b624
Build: success
Install hpccsystems-platform-community_6.2.0-rc3.el6.x86_64.rpm
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| spray_test (sprayFixed=false) | Pass | Excl. | Excl. |
| spray_test (sprayFixed=true) | Pass | Excl. | Excl. |
 
HPCC Stop: OK
HPCC Uninstall: OK

2016-10-19 13:52 UTC, ghalliday approved these changes

2016-10-19 13:52 UTC, merged