HPCC-16565 ws_access/UserQuery needs to return employeeID
hpcc-systems/HPCC-Platform pull request #9302
Opened 2016-11-03 14:53 UTC by RussWhitehead

Employee ID not returned from ws_access UserQuery feature. This PR adds
it to the returned values

Signed-off-by: Russ Whitehead <william.whitehead@lexisnexis.com>

2016-11-03 14:53 UTC, RussWhitehead commented
@rpastrana Please review

2016-11-03 14:59 UTC, rpastrana requested changes
2 minor comments.

2016-11-03 14:59 UTC, rpastrana commented on esp/scm/ws_access.ecm
> +    EmployeeID("EmployeeID"),
should this be versioned?

2016-11-03 14:59 UTC, rpastrana commented on system/security/LdapSecurity/ldapconnection.cpp
>              userTree->addProp(getUserFieldNames(UFFullName), fullName);
legacy, but worth fixing the indentation issue here (fixing it won't confuse reviewer)

2016-11-03 15:08 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: d82afcde68a4ca47c40dd349c08893e3c51f641f
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 90.35 seconds |

Install hpccsystems-platform-community_6.2.0-rc4.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|88 |88 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2016-11-03 15:25 UTC, RussWhitehead commented
@ghalliday Please merge

2016-11-04 19:54 UTC, miguelvazq commented
Can we make sure that the FilterBy options are as follows:

username vs. Name
fullname vs. FullName
passwordexpiration vs. PasswordExpiration
employeeID vs. EmployeeID

2016-11-04 20:23 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 59d2b9c5baa5ca55f044a00937eccecb9603e676
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 90.785 seconds |

Install hpccsystems-platform-community_6.2.0-rc4.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|88 |88 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2016-11-07 11:12 UTC, merged