HPCC-16188 Physical Tabs in DESDL not changing
hpcc-systems/HPCC-Platform pull request #9319
Opened 2016-11-09 20:14 UTC by miguelvazq

The user was having issues when selecting a parent tree element and while in the bindings tab it would not reset the display. We have overcome this by resetting selection and disabling tabs if not in anything but a child tree element.

Fixes: HPCC-16188
Fixes: HPCC-16189

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

2016-11-09 20:14 UTC, miguelvazq commented
@GordonSmith Please review.

2016-11-09 20:23 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: f4b664149a8a6db440d4359d4118fb7b0303c53b
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 89.801 seconds |

Install hpccsystems-platform-community_6.2.0-rc4.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|88 |88 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2016-11-10 04:55 UTC, GordonSmith requested changes

2016-11-10 04:55 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDetailsWidget.js
> +                domConstruct.destroy("serviceInformation");
serviceInformation needs to be prefixed with the widgets ID

2016-11-10 04:55 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDetailsWidget.js
> +                var table = domConstruct.create("table", {id: "serviceInformation"});
serviceInformation needs to be prefixed with the widgets ID

2016-11-10 16:08 UTC, miguelvazq commented
@GordonSmith Updated.

2016-11-10 16:23 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 1df28dbf05ab40ffd509cdd2d9fb01a14df79143
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 90.114 seconds |

Install hpccsystems-platform-community_6.2.0-rc4.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|88 |88 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2016-11-10 16:42 UTC, GordonSmith requested changes

2016-11-10 16:42 UTC, GordonSmith commented on esp/src/eclwatch/DynamicESDLDetailsWidget.js
> +                var table = domConstruct.create("table", {id: this.id + "_serviceInformation"});
Its probably ok here - but the "_" will get interpreted as being a tab for the "#" id - probably best to remove it.

2016-11-10 17:28 UTC, miguelvazq commented on esp/src/eclwatch/DynamicESDLDetailsWidget.js
> +                var table = domConstruct.create("table", {id: this.id + "_serviceInformation"});
I added it because it differentiates the start of a new item. However, I do agree "_" should be reserved for tabs. Removed.

2016-11-10 17:42 UTC, GordonSmith commented
Looks fine

2016-11-14 08:15 UTC, merged