HPCC-16419 Fix compiler warning
hpcc-systems/HPCC-Platform pull request #9394
Opened 2016-12-02 13:43 UTC by richardkchapman

Compiler wanred that client was uninitialized at the point that it was passed
to base class constructor.

As far as I can tell it is never used, so refactored to remove it.

Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

2016-12-02 13:43 UTC, richardkchapman commented
@afishbeck Please review

2016-12-02 13:51 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: eaae3256637765f04b02236d01757d5a9cb41d9b
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.657 seconds |

Install hpccsystems-platform-community_6.2.0-rc6.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|88 |88 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2016-12-02 16:19 UTC, afishbeck requested changes
Changes look fine, but there is a misspelling in your commit message.

2016-12-05 11:54 UTC, richardkchapman commented
Repushed to fix typo

@ghalliday Please merge

2016-12-05 12:06 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 171c5d70b6f6a829dde8a4ecc10130444936bfc0
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.748 seconds |

Install hpccsystems-platform-community_6.2.0-rc6.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|88 |88 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2016-12-06 08:36 UTC, merged