HPCC-9999 Release log queue lock after a queue item is read
hpcc-systems/HPCC-Platform pull request #9410
Opened 2016-12-12 18:19 UTC by rpastrana

In the existing code, after a log thread gets log queue lock, it
does not release the lock before finishing all of queued log items.
ESP logging manager may wait for a long time to add a log request
into the queue if the log thread is working on the queued items.
In this fix, the log thread releases the queue lock as soon as it
reads a queue item from the queue.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

2016-12-12 18:19 UTC, rpastrana commented
@gaojx please review

2016-12-12 18:36 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 04a8985df5c640ba786259c03d6ad681afb46831
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 90.4 seconds |

Install hpccsystems-platform-community_6.2.0-rc6.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|88 |88 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2016-12-13 09:33 UTC, ghalliday requested changes

2016-12-13 09:33 UTC, ghalliday commented on esp/logging/logginglib/logthread.cpp
> +IEspUpdateLogRequestWrap* CLogThread::readWriteJobQueue(IEspUpdateLogRequestWrap* jobToWrite)
I think extracting some of the code into a separate function is a good idea, but combining two different actions into the same function is not.  The only thing they share in common is that they need a critical section - they don't even share a parameter or a return value.  Much better would be "void writeJobQueue(item)" and IRequest * readJobQueue()

In this case a minimal change would probably be better, witht eh refactor as a separate commit.  I think it request the critical section to be moved into a local scope, something like:

```
   {
       CriticalBlock b(logQueueCrit);
       logRequest  = (IEspUpdateLogRequestWrap*)logQueue.dequeue();
   }

```

2016-12-13 12:27 UTC, richardkchapman commented
Commit message still refers to HPCC-9999

2016-12-13 13:07 UTC, rpastrana commented
@ghalliday please review (squashed commits in order to fix Kevin's commit message)

2016-12-13 13:15 UTC, ghalliday requested changes

2016-12-13 13:15 UTC, ghalliday commented on esp/logging/logginglib/logthread.cpp
> +	if (logQueue.ordinality() > 0)
minor: This test is redundant since dequeue() already returns null if it is empty.

2016-12-13 13:15 UTC, ghalliday commented on esp/logging/logginglib/logthread.cpp
> +	if (jobToWrite)
whitespace: This has been indented with tabs rather than space characters.

2016-12-13 13:15 UTC, ghalliday commented on esp/logging/logginglib/logthread.cpp
> +	CriticalBlock b(logQueueCrit);
whitespace: tabs used instead of spaces.

2016-12-13 13:21 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 2119f5308f1435c9a0d617ac4900e6118bb7a7a9
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.675 seconds |

Install hpccsystems-platform-community_6.2.0-rc6.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|88 |88 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2016-12-13 13:26 UTC, rpastrana commented
@ghalliday one last review. Thanks.

2016-12-13 13:30 UTC, ghalliday approved these changes

2016-12-13 13:30 UTC, merged