HPCC-16769 Avoid locking out stats/watchdog thread for long periods during slow disk opens
hpcc-systems/HPCC-Platform pull request #9416
Opened 2016-12-13 16:47 UTC by jakesmith

Signed-off-by: Jake Smith <jake.smith@lexisnexis.com>

2016-12-13 16:52 UTC, jakesmith commented
@ghalliday - please review.
Don't merge until I've run regression suite though please.

2016-12-13 16:59 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 3f5611f1f4df3907d4b15654beef766d2e5ebcb9
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.15 seconds |

Install hpccsystems-platform-community_6.0.10-rc1.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|87 |86 |0 |1 |

Error(s):
CcdFileTest run timeout



HPCC Stop: OK
HPCC Uninstall: OK

2016-12-13 17:00 UTC, jakesmith commented
@ghalliday - regression suite passed.

2016-12-14 10:00 UTC, ghalliday requested changes

2016-12-14 10:00 UTC, ghalliday commented on thorlcr/activities/csvread/thcsvrslave.cpp
> -                    iFileIO.setown(createCompressedFileReader(iFile, activity.eexp));
I don't think this is the correct fix.  You should be creating the reader outside of the critical section, and then having code like the following:

      {
                  CriticalBlock block(statsCs);
                  iFileIO.setown(partFileIO.getClear());
     }

2016-12-14 10:00 UTC, ghalliday commented on thorlcr/activities/csvread/thcsvrslave.cpp
> +                iFileIO.clear();
Ideally this should assign iFileIO to a variable declared outside the block, so that the close isn't within the critical section.

2016-12-14 10:00 UTC, ghalliday commented on thorlcr/activities/csvread/thcsvrslave.cpp
> +                iFileIO.clear();
as you have done in CDiskRecordPartHandler::close

2016-12-14 10:00 UTC, ghalliday commented on thorlcr/activities/diskread/thdiskreadslave.cpp
> +            CriticalBlock block(statsCs);
Same comment here - I think this is protecting the wrong code.

2016-12-14 10:00 UTC, ghalliday commented on thorlcr/activities/xmlread/thxmlreadslave.cpp
>                  CriticalBlock block(statsCs);
same here

2016-12-14 10:00 UTC, ghalliday commented
@jakesmith see comments

2016-12-14 10:05 UTC, jakesmith commented
Yes agree, rather silly change(s).
I'll fix.

2016-12-14 10:27 UTC, jakesmith commented
@ghalliday - please rereview.

2016-12-14 10:35 UTC, ghalliday requested changes

2016-12-14 10:35 UTC, ghalliday commented on thorlcr/activities/csvread/thcsvrslave.cpp
>              iFileIO.clear();
This also needs to be in the critical section

2016-12-14 10:35 UTC, ghalliday commented on thorlcr/activities/xmlread/thxmlreadslave.cpp
>              iFileIO.clear();
needs to be in the critical section (or assigned to a local variable outside - as in other places)

2016-12-14 10:36 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: aea2c99e9c2940afdc6870a6120742df03b57435
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 89.819 seconds |

Install hpccsystems-platform-community_6.0.10-rc1.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|87 |86 |0 |1 |

Error(s):
CcdFileTest run timeout



HPCC Stop: OK
HPCC Uninstall: OK

2016-12-14 10:51 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 4ee0899f5635f1cacb1496c7e37a43c6dad9d06a
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.072 seconds |

Install hpccsystems-platform-community_6.0.10-rc1.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|87 |86 |0 |1 |

Error(s):
CcdFileTest run timeout



HPCC Stop: OK
HPCC Uninstall: OK

2016-12-14 10:55 UTC, jakesmith commented
@ghalliday - squashed

2016-12-14 11:06 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 68204fa4a05cdfd10c6e05bddb3020185fc20ec5
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.011 seconds |

Install hpccsystems-platform-community_6.0.10-rc1.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|87 |86 |0 |1 |

Error(s):
CcdFileTest run timeout



HPCC Stop: OK
HPCC Uninstall: OK

2016-12-14 11:29 UTC, ghalliday approved these changes

2016-12-14 11:30 UTC, merged