HPCC-15564 Document DESDL Front End
hpcc-systems/HPCC-Platform pull request #9458
Opened 2017-01-04 21:19 UTC by g-pan

Fix HPCC-15564 Document DESDL Front End
Document new DESDL front end functionality in the ECL Watch.

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>
@JamesDeFabia (optionally) please review if you can
@rpastrana please review

2017-01-04 21:39 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: c891cf474925116e0600dd49246ff78c02753d09
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.757 seconds |

Install hpccsystems-platform-community_6.2.0-2.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|88 |88 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-05 09:05 UTC, richardkchapman commented
I changed the target without any need for rebasing. Reviewers, please proceed

2017-01-05 12:44 UTC, g-pan commented
thank you

2017-01-06 13:55 UTC, JamesDeFabia requested changes
Other than my 2 comments, this looks good from my POV, but please wait for the SME to approve, too.

2017-01-06 13:55 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +          button to view, or add to the configurations. <figure>
button to view, or add to the configurations. <--remove  comma

2017-01-06 13:55 UTC, JamesDeFabia commented on docs/ECLWatch/TheECLWatchMan.xml
> +      <para>The DESDL based ESP services available are listed in the navigator
DESDL-based (needs hyphen)

2017-01-06 15:08 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 63525918b5a9cfb162996f4bb38215b7da0bb9ee
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.507 seconds |

Install hpccsystems-platform-community_6.2.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|88 |88 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-09 09:07 UTC, richardkchapman commented
@rpastrana Please review

2017-01-09 16:23 UTC, rpastrana commented
@g-pan send me the latest PDF based on these changes, thanks.

2017-01-09 16:50 UTC, rpastrana requested changes
@g-pan left several comments.

2017-01-09 16:50 UTC, rpastrana commented on docs/ECLWatch/TheECLWatchMan.xml
> +      url="https://hpccsystems.com/download/documentation/all">https://hpccsystems.com/download/documentation/all</ulink></para>
This link should point to the actual DESDL Doc

2017-01-09 16:50 UTC, rpastrana commented on docs/ECLWatch/TheECLWatchMan.xml
> +        <para>Click on the triangle to expand the ESP process and display the
rather than "triangle" we might want to say "expand/collapse icon"

2017-01-09 16:50 UTC, rpastrana commented on docs/ECLWatch/TheECLWatchMan.xml
> +          button to view or add to the configurations. <figure>
"to view or edit the method configurations."

2017-01-09 16:50 UTC, rpastrana commented on docs/ECLWatch/TheECLWatchMan.xml
> +                <para>press the arrow next to the method (if there are are
There's a couple of issues w/ this line: Press should be capitalized, and there seems to be an extra "are" in the parenthesis, but I recommend changing this sentence to something like:
"Expand the target method configuration attributes (if there are.."

2017-01-09 16:50 UTC, rpastrana commented on docs/ECLWatch/TheECLWatchMan.xml
> +          <para><emphasis role="bold">To Add an attribute:</emphasis></para>
It feels like we should explain that the methods are configured by adding/editing these attributes.

2017-01-09 18:52 UTC, rpastrana commented
@g-pan PDF reviewed, looks fine.

2017-01-09 19:00 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 9a093b94e127a47f5ca8a906fd6e5b27bad0cd70
Build: failed
Number of Error(s): 8
\r  3 2573k    3 81927    0     0   101k      0  0:00:25 --:--:--  0:00:25  101kError: no ID for constraint linkend: ssl4esp.
/bin/ar: lib/libcouchbaseS.a: Error reading generated/probes.o: File truncated
gmake[5]: *** [lib/libcouchbaseS.a] Error 1
gmake[4]: *** [CMakeFiles/couchbaseS.dir/all] Error 2
gmake[3]: *** [all] Error 2
make[2]: *** [plugins/couchbase/libcouchbase-build/lib/libcouchbase.so] Error 2
make[1]: *** [plugins/couchbase/CMakeFiles/libcouchbase-build.dir/all] Error 2
make: *** [all] Error 2

2017-01-09 19:06 UTC, rpastrana commented
@AttilaVamos  the changes that went in this PR are documentation related, not sure how it could have caused the smoketest error reported, can you look into this? Thanks.

2017-01-09 22:39 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 9a093b94e127a47f5ca8a906fd6e5b27bad0cd70
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.9 seconds |

Install hpccsystems-platform-community_6.2.1-documentation0.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|88 |88 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-10 08:38 UTC, merged