HPCC-14734 UI items login/logout in ECL Watch
hpcc-systems/HPCC-Platform pull request #9489
Opened 2017-01-11 22:31 UTC by miguelvazq

Create the landing page for session management integration.

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

2017-01-11 22:31 UTC, miguelvazq commented
@GordonSmith Please review. FYI @wangkx

2017-01-11 22:50 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: cad045c920aafd369917b1e09fcced1079515fb5
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 41.835 seconds |

Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|86 |86 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-13 16:57 UTC, GordonSmith requested changes
Hard to review it without seeing it on a web page - but it will need to handle the translation scheme.

2017-01-13 16:57 UTC, GordonSmith commented on esp/src/eclwatch/templates/Login.html
> +			<p>Please log into ECL Watch</p>
Needs translation string

2017-01-13 16:57 UTC, GordonSmith commented on esp/src/eclwatch/templates/Login.html
> +					<input type="text" name="username" placeholder="username"></input>
Needs translation string

2017-01-13 16:57 UTC, GordonSmith commented on esp/src/eclwatch/templates/Login.html
> +					<input type="password" name="password" placeholder="password"></input>
Needs translation string

2017-01-25 21:38 UTC, miguelvazq commented
@GordonSmith Please review. Translations added. I am going to start adding Spanish translations as we go. I do however get this message about Conflicting files (see above).

2017-01-25 21:50 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: e1d5a0ff219c4762b34dac70a4a263316205b877
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 4 | 75 | 42.787 seconds |

Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|86 |86 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-26 13:03 UTC, richardkchapman commented
Needs rebasing for a clean merge

2017-01-27 17:42 UTC, miguelvazq commented
@richardkchapman rebased.

2017-01-27 20:10 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: c641728dfb2bdaae0f9f8453ad4ba1d9b3a4b3fd
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 41.962 seconds |

Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|86 |86 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-30 09:22 UTC, richardkchapman commented
@GordonSmith This is waiting for you I think

2017-01-31 15:38 UTC, GordonSmith approved these changes
Looks fine.

2017-02-01 13:00 UTC, merged