HPCC-16896 Specify ZAP report file name when creating the report.
hpcc-systems/HPCC-Platform pull request #9502
Opened 2017-01-17 21:00 UTC by wangkx

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

2017-01-17 21:09 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 93a7c5de3090b2e65f376a23f8460df2d7f35a7f
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 90.934 seconds |

Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|86 |86 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-17 21:10 UTC, wangkx commented
@RussWhitehead please review.

2017-01-17 21:27 UTC, RussWhitehead requested changes

2017-01-17 21:27 UTC, RussWhitehead commented on esp/services/ws_workunits/ws_workunitsService.cpp
> +                if (!streq(tail, ".zip"))
Should be strieq

2017-01-17 21:27 UTC, RussWhitehead commented on esp/services/ws_workunits/ws_workunitsService.cpp
> +                char* tail = (char*) zipFName + len - 4;
trivial, but should be "const char *"

2017-01-17 21:33 UTC, wangkx commented
@RussWhitehead please review my changes.

2017-01-17 21:34 UTC, RussWhitehead commented
@wangkx Looks good

2017-01-17 21:37 UTC, wangkx commented
@richardkchapman this PR is ready to be merged to 6.4.0

2017-01-17 21:54 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 40fff0d7c1aeee8714960524cd9523ca4d0e296c
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 94.076 seconds |

Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|86 |86 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-18 09:07 UTC, richardkchapman commented on esp/services/ws_workunits/ws_workunitsService.cpp
> +        {
This code would be rather simpler/clearer using pathExtension (from jlib)

2017-01-18 09:08 UTC, richardkchapman commented
@wangkx one comment

2017-01-18 14:09 UTC, wangkx commented
@richardkchapman The code is using pathExtension() now.

2017-01-18 14:21 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: a4afa99686914d532c2d39e7e5bee3f215666128
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.421 seconds |

Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|86 |86 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-19 07:32 UTC, merged