HPCC-16877 Xref not showing found file
hpcc-systems/HPCC-Platform pull request #9518
Opened 2017-01-20 15:33 UTC by miguelvazq

Found file not displaying when user browses the found file tab.

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

2017-01-20 15:50 UTC, miguelvazq commented
@GordonSmith Please review.

A few things are happening here: 

- When the response only contains one file it is returned in a JSONObject when it is multiple rows it is returned in a JSONArray so I have added logic to handle both scenarios.
- Attach functionality was added
- I have used the dojo/all to handle the removal of multiple files
- Added selector to dgrid

2017-01-20 15:59 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 600908ad2c9666b77929f9d982f16d07b9527fdc
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.146 seconds |

Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|86 |86 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-20 16:31 UTC, GordonSmith requested changes

2017-01-20 16:31 UTC, GordonSmith commented on esp/src/eclwatch/XrefFoundFilesWidget.js
> +            var context = this;
Context not used.

2017-01-20 16:31 UTC, GordonSmith commented on esp/src/eclwatch/XrefFoundFilesWidget.js
> +                        })
No need for the mixin, since the target is empty.

2017-01-20 16:31 UTC, GordonSmith commented on esp/src/eclwatch/XrefLostFilesWidget.js
> +                        })
No need for the mixin, since the target is empty. (and missing ";")

2017-01-20 16:31 UTC, GordonSmith commented on esp/src/eclwatch/XrefOrphanFilesWidget.js
> +                        })
No need for the mixin, since the target is empty. (and missing ";")

2017-01-20 16:31 UTC, GordonSmith commented on esp/src/eclwatch/XrefQueryWidget.js
> +                    })
No need for the mixin, since the target is empty.

2017-01-20 16:47 UTC, miguelvazq commented on esp/src/eclwatch/XrefFoundFilesWidget.js
> +                        })
If there is a file present (single row) we need to manually insert the row into an array.

2017-01-20 16:57 UTC, GordonSmith commented on esp/src/eclwatch/XrefFoundFilesWidget.js
> +                        })
The following code is equivilant:
```
newRows.push({
    Name: results.Partmask,
    Modified: results.Modified,
    Parts: results.Numparts,
    Size: results.Size
});
```

2017-01-23 12:49 UTC, richardkchapman commented
@miguelvazq Back to you

2017-01-24 17:30 UTC, miguelvazq commented
Updated.

2017-01-24 17:35 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 578d3b4cf3da0469c96454b88e92c55065a84153
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.509 seconds |

Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|86 |86 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-24 18:36 UTC, GordonSmith commented
Looks fine.

2017-01-24 19:55 UTC, miguelvazq commented
Verified by @cloLN Errors/Warnings has same issue. Let me add same logic.

2017-01-24 20:12 UTC, miguelvazq commented
@GordonSmith added logic to errors/warnings widget to handle this same scenario. FYI @cloLN

2017-01-24 20:21 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 6cca2db26a5d32cc3e12d70de95d7808cc685edd
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.23 seconds |

Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|86 |86 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-24 20:36 UTC, HPCCSmoketest commented
Automated Smoketest
Sha: 7db9c9ed41aa5f85548f532cd921c4f0e06f75c3
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.688 seconds |

Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unittest result:

| total | passed | failed | timeout | 
|---|---|---|---|
|86 |86 |0 |0 |

HPCC Stop: OK
HPCC Uninstall: OK

2017-01-31 15:55 UTC, GordonSmith requested changes

2017-01-31 15:55 UTC, GordonSmith commented on esp/src/eclwatch/XrefErrorsWarningsWidget.js
> +                }
This should be more along the lines of:
```
if (lang.exists("Warning.length", results)) {
	arrayUtil.forEach(results.Warning, function (row, idx) {
	   newRows.push({
			File: row.File,
			Text: row.Text,
			Status: context.i18n.Warning
		});
	});
} else if (results.Warning) {
	newRows.push({
		File: results.Warning.File,
		Text: results.Warning.Text,
		Status: context.i18n.Warning
	});
}

if (lang.exists("Error.length", results)) {
	arrayUtil.forEach(results.Error, function (row, idx) {
	   newRows.push({
			File: row.File,
			Text: row.Text,
			Status: context.i18n.Error
		});
	});
} else if (results.Error) {
	newRows.push({
		File: results.Error.File,
		Text: results.Error.Text,
		Status: context.i18n.Error
	});
}
```

2017-01-31 15:55 UTC, GordonSmith commented on esp/src/eclwatch/XrefFoundFilesWidget.js
> +            if (confirm(this.i18n.DeleteSelectedFiles)) {
Should display a list of the items you are about to delete (similar to other places we delete)

2017-01-31 15:55 UTC, GordonSmith commented on esp/src/eclwatch/XrefFoundFilesWidget.js
> +            if (confirm(this.i18n.AddTheseFilesToDali)) {
hould display a list of the items you are about to delete (similar to other places we delete)

2017-01-31 15:55 UTC, GordonSmith commented on esp/src/eclwatch/XrefFoundFilesWidget.js
> +                            XRefFiles_i2: row.Name
Should probably be "XRefFiles_i0"?

In fact you can probably group all the actions into a single call using XRefFiles_i0, XRefFiles_i1, XRefFiles_i2...  (search for "flattenArray" for other places we do this.)

2017-01-31 15:55 UTC, GordonSmith commented on esp/src/eclwatch/XrefFoundFilesWidget.js
> +                            XRefFiles_i2: row.Name
See previous comment re _i0

2017-01-31 15:55 UTC, GordonSmith commented on esp/src/eclwatch/XrefLostFilesWidget.js
> +                            XRefFiles_i2: row.Name
See previous comment re _i0

2017-01-31 15:55 UTC, GordonSmith commented on esp/src/eclwatch/XrefLostFilesWidget.js
> +                    }
Note:  Having to check the response structures from ESP for the existence of an array smells like a bug in the ESP API (which may be too late to do anything about).

I would suggest moving this "cleanup" logic into WsDFUXref.

2017-01-31 15:55 UTC, GordonSmith commented on esp/src/eclwatch/XrefOrphanFilesWidget.js
> +            if (confirm(this.i18n.DeleteSelectedFiles)) {
Confirmation should include list of items

2017-01-31 15:55 UTC, GordonSmith commented on esp/src/eclwatch/XrefOrphanFilesWidget.js
> +                            XRefFiles_i2: row.Name
See previous comment re _i0

2017-02-01 12:59 UTC, richardkchapman commented
@miguelvazq Back to you

2017-02-01 15:02 UTC, miguelvazq commented
Cherry-picked and tested in emulation mode. IE8 is successfully displaying treemap and a graph on the following page. Looks good.

2017-02-13 22:07 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 7d03b27237e1a66cffee1ad6f4bef4f155ba36a0
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 1 | 65 | 89.43 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |86 |86 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-02-13 22:11 UTC, miguelvazq commented
@GordonSmith Changes made.

2017-02-13 22:27 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: dca057ac3af26ba6a0465d53ffac16ca6c61ed3a
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 1 | 65 | 91.522 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |86 |86 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-02-21 16:05 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: dca057ac3af26ba6a0465d53ffac16ca6c61ed3a
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 1 | 65 | 90.376 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |86 |86 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-02-21 17:41 UTC, GordonSmith requested changes
There is a build error - I suspect the trailing comma below is the culprit.  I will do a full review once that is resolved.

2017-02-21 17:41 UTC, GordonSmith commented on esp/src/eclwatch/XrefFoundFilesWidget.js
> +    "hpcc/ESPUtil",
Trailing comma

2017-02-22 14:41 UTC, miguelvazq commented
@GordonSmith modified. Waiting for build passing

2017-02-22 15:06 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 32334c4cd0e948ee03c5ed266ca1bbc3c7b4eadc
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.858 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |86 |86 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-02-28 11:07 UTC, GordonSmith requested changes
Minor indentations and some duplicate code.

2017-02-28 11:07 UTC, GordonSmith commented on esp/src/eclwatch/_Widget.js
> +             arrayUtil.some(arr, function (item, idx) {
Minor:  indentation

2017-02-28 11:07 UTC, GordonSmith commented on esp/src/eclwatch/_Widget.js
>                  }
Duplicate code - would suggest something like:
```
...
if (idx >= 10) {
    retVal += "\n..." + (arr.length - 10) + " " + this.i18n.More + "...";
    return true;
}
var lineStr = field ? item[field] : item;
if (lineStr.length > 50) {
    retVal += "..." + lineStr.slice(25,item[field].length);
} else {
    retVal += lineStr;
}
...
```

2017-02-28 11:38 UTC, richardkchapman commented
@miguelvazq Back to you

2017-03-01 05:06 UTC, miguelvazq commented
@GordonSmith changes made.

2017-03-01 05:18 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 26302aa51be1394d5ce2c00823e2f55172e7c69a
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.839 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



HPCC Stop: OK
HPCC Uninstall: OK

2017-03-01 08:12 UTC, GordonSmith approved these changes
Looks good.

2017-03-01 11:50 UTC, merged