HPCC-16873 Get/set dfuserver queue in FileSpray web services
hpcc-systems/HPCC-Platform pull request #9605
Opened 2017-02-13 19:15 UTC by wangkx

1. When FileSpray service is started, check whether default
dfuserver queue label is a valid dfuserver queue; 2. A new
service method is added to query dfuserver queue list; 3. A
caller may specify dfuserver queue in a FileSpray service
request. If not specified, the default dfuserver queue will
be used.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x ] My code follows the code style of this project.
  - [x ] My code does not create any new warnings from compiler, build system, or lint.
- [x ] The commit message is properly formatted and free of typos.
  - [x ] The commit message title makes sense in a changelog, by itself.
  - [x ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x ] I have read the CONTRIBUTORS document.
- [x ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [x ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [x ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [x ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately

## Testing:

2017-02-13 19:27 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 005b5381833a8b009e0fcc1ffc46cacf0aed41d6
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.477 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |86 |86 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-02-13 19:28 UTC, wangkx commented
@jakesmith please review.

2017-02-14 09:20 UTC, richardkchapman commented
Note - checklist looks betterif you take out the spaces when adding the x ...

2017-02-15 13:59 UTC, jakesmith requested changes
@wangkx - looks good, a few comments/questions.

2017-02-15 13:59 UTC, jakesmith commented on common/workunit/workunit.cpp
> +            continue;
style: never care for continue much if it can be avoided and you could just as well put block below in true test of condition.

2017-02-15 13:59 UTC, jakesmith commented on common/workunit/workunit.cpp
> +    VStringBuffer pName("@%s", (propName && *propName) ? propName: "queue");
I can't see anywhere that propname (qtype) is used, or think of any use cases..
For a DFUServer the queue name will always be called @queue.

So I think you should remove this code, 'propname' and associated code.

2017-02-15 13:59 UTC, jakesmith commented on common/workunit/workunit.cpp
> +            queueNames.append(',');
Would be cleaner if used StringArray and appendList .

And should it dedup them? e.g. use appendListUnique

2017-02-15 13:59 UTC, jakesmith commented on esp/services/ws_fs/ws_fsService.cpp
> +    getDFUServerQueueNameArray(NULL, NULL, qlist);
style: nullptr preferred

2017-02-15 13:59 UTC, jakesmith commented on common/workunit/workunit.cpp
> +    if (process && *process)
minor: could use isEmptyString

2017-02-15 13:59 UTC, jakesmith commented on esp/services/ws_fs/ws_fsService.cpp
> +                throw MakeStringException(-1, "Invalid DFU Queue Label in configuration file");
Error should contain the queue name it was looking for.

2017-02-15 13:59 UTC, jakesmith commented on esp/services/ws_fs/ws_fsService.cpp
> +            m_QueueLabel.append(qlist.item(0));
could you comment on the logic here?
If the EspService specifies no QueueLabel, then the 1st DfuServer queue name found is used?

Is that right/sensible?

2017-02-15 15:13 UTC, wangkx commented on esp/services/ws_fs/ws_fsService.cpp
> +            m_QueueLabel.append(qlist.item(0));
The logic here is: if no default queue is configured,  the 1st DfuServer queue will be used as the default. The default will be used only if a user does not specify DfuServer queue.

2017-02-15 15:22 UTC, wangkx commented on common/workunit/workunit.cpp
> +            continue;
I thought that we prefer using continue to avoid multiple nested {}.

2017-02-15 15:55 UTC, wangkx commented
@jakesmith I made the changes based on your comments. Please review.

2017-02-15 16:19 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 4e3c56033186344078e7c36e00f8000c19ce36a9
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.099 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |86 |86 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-02-16 00:33 UTC, afishbeck commented on esp/services/ws_fs/ws_fsService.cpp
> +            bool found = false;
could just call qlist.contains(m_QueueLabel.str());

2017-02-16 00:36 UTC, afishbeck reviewed
Other than one simplification, looks good.

2017-02-16 09:29 UTC, richardkchapman commented on esp/services/ws_fs/ws_fsService.cpp
> +            bool found = false;
is that case-insensitive?

2017-02-16 14:30 UTC, wangkx commented on esp/services/ws_fs/ws_fsService.cpp
> +            bool found = false;
I think that queue name is case-insensitive. The contains() may not work if m_QueueLabel does not match the queue name case stored inside the qlist. Or, I have to force the queue names in the qlist to be lowercase. Not sure it is worth.

2017-02-16 14:41 UTC, afishbeck commented on esp/services/ws_fs/ws_fsService.cpp
> +            bool found = false;
ok, missed the case insensitive issue.

2017-02-16 15:00 UTC, jakesmith commented on esp/services/ws_fs/ws_fsService.cpp
> +            bool found = false;
I agree probably not worth it for this PR, you could add a find option for case insensitivity to StringArray (there are similar already in the sort funcs.)

2017-02-16 15:00 UTC, jakesmith commented
@richardkchapman - looks ready to merge.

2017-02-21 15:33 UTC, merged

2017-02-23 12:15 UTC, richardkchapman commented on esp/services/ws_fs/ws_fsService.cpp
> +    wu->setQueue((dfuServerQueue && dfuServerQueue) ? dfuServerQueue : m_QueueLabel.str());
@wangkx Typo here caused OBT to fail - regression suite should have been run?