HPCC-17070 Ensure system can build with USE_ICU=0 and USE_OPENLDAP=0
hpcc-systems/HPCC-Platform pull request #9608
Opened 2017-02-14 17:27 UTC by ghalliday

Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately

## Testing:
Checked it compiled.

2017-02-14 17:29 UTC, ghalliday commented
I will run a full regression test, but no code should have been affected if _USE_ICU is defined.  If it isn't defined, then I have implemented a few functions so that utf8->string should work on ascii characters.  I haven't tested it properly though.
@richardkchapman

2017-02-14 17:37 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 4445b3971c3f832b7a1184f7110749a0c22d1970
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.409 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |86 |86 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-02-15 11:08 UTC, richardkchapman commented on common/thorhelper/thorrparse.cpp
>          UNIMPLEMENTED;
Should probably be changed to 

      throw MakeStringException(99, "System was built without Unicode support");

2017-02-15 11:38 UTC, richardkchapman requested changes

2017-02-15 11:38 UTC, richardkchapman commented on common/thorhelper/thorrparse.cpp
> +#endif
default should be changed to

    throw MakeStringException(99, "System was built without Unicode support");

2017-02-15 11:38 UTC, richardkchapman commented on ecl/hqlcpp/hqlregex.cpp
> +#endif
Any need for an else, or is this just an optimization that can be skipped ?

2017-02-15 11:38 UTC, richardkchapman commented on ecl/hqlcpp/hqlregex.cpp
> +            UNIMPLEMENTED;
Better error message?

2017-02-15 11:38 UTC, richardkchapman commented on ecl/hqlcpp/hqlregex.cpp
> +                UNIMPLEMENTED;
Better error message

2017-02-15 11:38 UTC, richardkchapman commented on ecl/hqlcpp/hqlregex.cpp
> +                UNIMPLEMENTED;
Better error message?

2017-02-15 11:38 UTC, richardkchapman commented on rtl/eclrtl/eclrtl.cpp
> +    UNIMPLEMENTED;
Better error message?

2017-02-15 11:38 UTC, richardkchapman commented on rtl/eclrtl/eclrtl.cpp
> +    UNIMPLEMENTED;
Better error message

2017-02-15 12:26 UTC, richardkchapman commented
@ghalliday A few comments

2017-02-17 14:58 UTC, ghalliday commented
@richardkchapman cleaned up the code and made the error messages consistent.

2017-02-17 15:06 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 9cfe94f755fdbe1227f2564c681a3b7070024345
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 90.15 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |86 |86 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-02-27 10:01 UTC, richardkchapman commented on ecl/hqlcpp/hqlregex.cpp
> +                UNIMPLEMENTED;
@ghalliday Looks like you missed this one?

2017-02-28 10:44 UTC, ghalliday commented on ecl/hqlcpp/hqlregex.cpp
> +                UNIMPLEMENTED;
@richardkchapman I moved the appropriate errors into the case branches - this is UNIMPLEMENTED is correct

2017-02-28 11:29 UTC, richardkchapman approved these changes

2017-02-28 11:30 UTC, merged