HPCC-17161 Add delete confirmation dialog
hpcc-systems/HPCC-Platform pull request #9662
Opened 2017-03-03 23:03 UTC by miguelvazq

All details area should container confirmation dialog like the query areas do.

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-03-03 23:18 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 313440145e4bdef05d8182a9ceb5b772d91e952c
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.253 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



HPCC Stop: OK
HPCC Uninstall: OK

2017-03-06 09:20 UTC, richardkchapman commented
Can you update the PR checklist please

2017-03-06 16:20 UTC, miguelvazq commented
Yep,

2017-03-06 16:21 UTC, miguelvazq commented
@GordonSmith Please review.

2017-03-06 16:22 UTC, GordonSmith requested changes
We normally pass in the list of items that are about to be deleted?

2017-03-06 16:22 UTC, miguelvazq commented
This is at the details level.

2017-03-06 16:42 UTC, GordonSmith approved these changes
Looks ok - one minor comment.

2017-03-06 16:42 UTC, GordonSmith commented on esp/src/eclwatch/LFDetailsWidget.js
> +                    }
Minor = Load callback not needed.

2017-03-06 17:14 UTC, miguelvazq commented
@GordonSmith Minor comment updated.

2017-03-06 17:20 UTC, miguelvazq commented
@rpastrana Can you review the Spanish translations?

2017-03-06 17:28 UTC, rpastrana requested changes
@miguelvazq a couple of comments.

2017-03-06 17:28 UTC, rpastrana commented on esp/src/eclwatch/nls/es/hpcc.js
> +    YouAreAboutToDeleteThisQueryset: "Usted esta a punto de eliminar este grupo de query. ¿Desea continuar?",
Looked through the file and for the most part we do translate query to consulta. Although I did see a few entries where we don't translate query.
And perhaps outside the scope of this issue, but there's a instace where we (prob me) misspelled Consulta:
ResetThisQuery: "Reajustar esta Consulat",

2017-03-06 17:28 UTC, rpastrana commented on esp/src/eclwatch/nls/hpcc.js
> +    YouAreAboutToDeleteThisFile: "You are about to delete this file. Are you sure you want to do this?",
These didn't get translated

2017-03-06 17:30 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 7182df3f3659aa7b94c4b040e074a8e1bc911154
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.45 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



HPCC Stop: OK
HPCC Uninstall: OK

2017-03-06 17:45 UTC, miguelvazq reviewed
Changed 'query' to 'consulta'

2017-03-06 17:45 UTC, miguelvazq commented on esp/src/eclwatch/nls/es/hpcc.js
> +    YouAreAboutToDeleteThisQueryset: "Usted esta a punto de eliminar este grupo de query. ¿Desea continuar?",
I will open a JIRA for this spelling mistake.

2017-03-06 17:45 UTC, miguelvazq commented on esp/src/eclwatch/nls/hpcc.js
> +    YouAreAboutToDeleteThisFile: "You are about to delete this file. Are you sure you want to do this?",
One is for the default English version and one for the Spanish file.

2017-03-06 18:01 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 95fa64a2cd6dfd6ad87a1ba77e73fd04036ced34
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.903 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



HPCC Stop: OK
HPCC Uninstall: OK

2017-03-07 12:42 UTC, rpastrana approved these changes

2017-03-07 12:43 UTC, rpastrana commented
@miguelvazq

2017-03-08 14:36 UTC, miguelvazq commented
@richardkchapman This is ready to merge.

2017-03-14 11:29 UTC, merged