HPCC-17132 DOCS:ConfigMgr can use IP or Hostnames
hpcc-systems/HPCC-Platform pull request #9700
Opened 2017-03-15 19:46 UTC by g-pan

Fix HPCC-17132 DOCS:ConfigMgr can use IP or Hostnames
Document that we can use IP addresses of the host names
in configuring the HPCC.

@rpastrana please review
@JamesDeFabia please review

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

Tested by building the changed documents. All built successfully.

2017-03-15 20:03 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: e8eda7c61790609eebbaea2b9531ee6db7eddd3d
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.457 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



HPCC Stop: OK
HPCC Uninstall: OK

2017-03-15 20:14 UTC, rpastrana requested changes
@g-pan some minor comments

2017-03-16 08:54 UTC, richardkchapman commented
@g-pan Back to you

2017-03-16 12:55 UTC, g-pan commented on docs/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> -            <para>Alternatively, you could find the IP addresses using Auto
Addressed in https://github.com/hpcc-systems/HPCC-Platform/pull/9703
only not merged yet, Removed this bit to ensure the text does not get reintroduced.

2017-03-16 16:46 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 52eff2ee935bdf6ec9a0af3b2f233f5521aed91a
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.181 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



HPCC Stop: OK
HPCC Uninstall: OK

2017-03-16 21:14 UTC, rpastrana commented
@gpan squash these commits, and update the "add hardware" screen documentation.

2017-03-17 14:06 UTC, richardkchapman commented
@g-pan

2017-03-21 17:19 UTC, g-pan commented
Comments addressed. Squashed and rebased.

2017-03-21 17:38 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 74f04f877add15fb801a3a1f716865130e9ada78
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.432 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



HPCC Stop: OK
HPCC Uninstall: OK

2017-03-21 17:58 UTC, g-pan commented
@rpastrana please review

2017-03-21 18:10 UTC, rpastrana commented
@g-pan changes look fine. I did not confirm all necessary sections were updated.

2017-03-22 08:29 UTC, merged