HPCC-16381 Add GetNumFileToCopy
hpcc-systems/HPCC-Platform pull request #9729
Opened 2017-03-21 18:48 UTC by miguelvazq

Add deploy complete notification on the cluster level for Roxie clusters.

Signed-off-by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-03-21 18:54 UTC, miguelvazq commented
@GordonSmith Please comment

2017-03-21 19:07 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: a8cd2923f131c5c944474bf98d387e58ca0bba44
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 1 | 75 | 40.588 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



HPCC Stop: OK
HPCC Uninstall: OK

2017-03-22 01:22 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 32942df53d2b59fac0e0ba94c5a33023ea359d45
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 43.259 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



HPCC Stop: OK
HPCC Uninstall: OK

2017-03-22 01:33 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: bcb929bf6c76b5f2f8f2ccc96d00afdf5a45f10f
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 42.715 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



HPCC Stop: OK
HPCC Uninstall: OK

2017-03-24 14:37 UTC, GordonSmith commented
@miguelvazq Is this for 6.4?

2017-03-24 15:22 UTC, miguelvazq commented
@GordonSmith Good catch will rebase

2017-03-27 15:30 UTC, miguelvazq commented
@GordonSmith Rebased.

2017-03-28 12:37 UTC, GordonSmith requested changes

2017-03-28 12:37 UTC, GordonSmith commented on esp/src/eclwatch/GetNumberOfFilesToCopyWidget.js
> +            var context = this;
Not needed

2017-03-28 12:37 UTC, GordonSmith commented on esp/src/eclwatch/GetNumberOfFilesToCopyWidget.js
> +        },
The whole postCreate is not needed.

2017-03-28 12:37 UTC, GordonSmith commented on esp/src/eclwatch/GetNumberOfFilesToCopyWidget.js
> +            var context = this;
Not used.

2017-03-28 12:37 UTC, GordonSmith commented on esp/src/eclwatch/GetNumberOfFilesToCopyWidget.js
> +                    NumQueryFileToCopy: {label:this.i18n.FilesPending, width: 30, sortable: false}
One column should not have a width set?

2017-03-28 18:49 UTC, miguelvazq commented
@GordonSmith Updated.

2017-03-28 19:19 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: db04f4d028e577c23277c833f9783811173e019a
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.959 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |9 |9 |0 |
|setup (thor) |9 |9 |0 |
|setup (roxie) |9 |9 |0 |
|test (hthor) |719 |719 |0 |
|test (thor) |614 |614 |0 |
|test (roxie) |744 |744 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-03-28 19:22 UTC, miguelvazq commented
@GordonSmith Updated.

2017-03-29 13:43 UTC, miguelvazq commented
@rpastrana Please review translations.

2017-03-30 15:03 UTC, rpastrana reviewed
@miguelvazq couple of comments

2017-03-30 15:03 UTC, rpastrana commented on esp/src/eclwatch/nls/es/hpcc.js
> +    FilesPending: "Archivos pendiente",
I think we need to pluralize the "pendiente" as well

2017-03-30 15:03 UTC, rpastrana commented on esp/src/eclwatch/nls/es/hpcc.js
> +    RoxieFileCopy: "Estado de copia para archivos de Roxie",
"de" instead of "para"

2017-03-30 15:03 UTC, rpastrana commented on esp/src/eclwatch/nls/es/hpcc.js
> +    title_FilesPendingCopy: "Archivos pendiente de copia",
Archivos pendiente para copiar

2017-04-05 12:40 UTC, GordonSmith requested changes

2017-04-05 12:40 UTC, GordonSmith commented on esp/src/eclwatch/GetNumberOfFilesToCopyWidget.js
> +    "hpcc/DelayLoadWidget",
Not used

2017-04-05 12:40 UTC, GordonSmith commented on esp/src/eclwatch/TopologyWidget.js
> +    "hpcc/GetNumberOfFilesToCopyWidget",
Is this used?  I think it is supposed to be in TopologyDetailsWidget?

2017-04-05 12:40 UTC, GordonSmith commented on esp/src/eclwatch/templates/TopologyDetailsWidget.html
> +            <div id="${id}_GetNumberOfFilesToCopy" title="${i18n.RoxieFileCopy}" data-dojo-type="GetNumberOfFilesToCopyWidget">
"GetNumberOfFilesToCopyWidget" should be added to "TopologyDetailsWidget.js"

2017-04-05 12:58 UTC, richardkchapman commented
@miguelvazq

2017-04-11 20:19 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: aeaa5440b6670a93b308861d610c636d238fbc11
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 94.159 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |721 |721 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-12 02:23 UTC, miguelvazq commented
@GordonSmith Updated per your comments

2017-04-12 02:51 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 83bcb52c08083c409e4af2c7ba788629d6a9c94d
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 94.155 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |721 |721 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-17 13:47 UTC, miguelvazq commented
@GordonSmith bump

2017-04-19 12:55 UTC, GordonSmith approved these changes
Looks fine.

2017-04-19 13:25 UTC, merged