HPCC-15951 ECLWatch to support package parts
hpcc-systems/HPCC-Platform pull request #9763
Opened 2017-03-28 15:14 UTC by miguelvazq

Package map process now supports add-part, get-part and remove-part. Adding to ECL Watch to allow users to interact with it via the GUI.

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-03-28 15:15 UTC, miguelvazq commented
@GordonSmith Please review.

2017-03-28 16:27 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 3e51d93ee62a0887d61a08768b81393424506c6e
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 1 | 65 | 91.724 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |9 |9 |0 |
|setup (thor) |9 |9 |0 |
|setup (roxie) |9 |9 |0 |
|test (hthor) |719 |719 |0 |
|test (thor) |614 |614 |0 |
|test (roxie) |744 |743 |1 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-03-28 21:42 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 228011ac8792af383a001af2e1847c85c4abb6ee
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 1 | 65 | 92.862 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |9 |9 |0 |
|setup (thor) |9 |9 |0 |
|setup (roxie) |9 |9 |0 |
|test (hthor) |719 |719 |0 |
|test (thor) |614 |614 |0 |
|test (roxie) |744 |744 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-05 12:49 UTC, GordonSmith requested changes

2017-04-05 12:49 UTC, GordonSmith commented on esp/src/eclwatch/PackageMapPartsWidget.js
> +#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
Date?  Do we still need to include this header given the licence file?

2017-04-05 12:49 UTC, GordonSmith commented on esp/src/eclwatch/Utility.js
> +            parser = new DOMParser();
missing "var"?  (you might want to lint this PR?)

2017-04-05 12:49 UTC, GordonSmith commented on esp/src/eclwatch/Utility.js
> +            xmlDoc = parser.parseFromString(val,"text/xml");
Missing var?

2017-04-05 12:58 UTC, richardkchapman commented
@miguelvazq

2017-04-05 13:28 UTC, miguelvazq commented on esp/src/eclwatch/PackageMapPartsWidget.js
> +#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
Not sure. There are numerous files with this date currently.

2017-04-05 13:31 UTC, GordonSmith commented on esp/src/eclwatch/PackageMapPartsWidget.js
> +#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
Yea more a general question - will ignore for now.

2017-04-12 02:26 UTC, miguelvazq commented
@GordonSmith Updated.

2017-04-12 03:22 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: 2dc39bb3b2e06a761161b0042c479974057346e5
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 1 | 65 | 92.256 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |721 |721 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-14 16:52 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 16843bbbfae34d2145fe27cbcbed42385ea926af
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.802 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |721 |721 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-17 13:47 UTC, miguelvazq commented
@GordonSmith bump

2017-04-19 13:33 UTC, GordonSmith requested changes

2017-04-19 13:33 UTC, GordonSmith commented on esp/src/eclwatch/PackageMapPartsWidget.js
> +                    retVal = context.getFilter();
Missing var?

2017-04-19 13:33 UTC, GordonSmith commented on esp/src/eclwatch/PackageMapPartsWidget.js
> +                    retVal = context.getFilter();
Is this retVal actually used to return something?  Maybe it could have a more sensible name?

2017-04-19 13:41 UTC, miguelvazq commented
@GordonSmith Modified

2017-04-19 14:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 65a3273587ae9425c1ff0f1100964eb422ea2935
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.607 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |721 |721 |0 |
|test (thor) |616 |616 |0 |
|test (roxie) |745 |745 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-21 04:24 UTC, GordonSmith approved these changes
Looks good

2017-04-21 07:50 UTC, merged