Hpcc 17293 feature 6.4.0
hpcc-systems/HPCC-Platform pull request #9786
Opened 2017-03-30 18:05 UTC by AttilaVamos

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-03-30 18:40 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 53b8a14471de8977bd961f33d6ab04592cc35a5e
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 95.647 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |9 |9 |0 |
|setup (thor) |9 |9 |0 |
|setup (roxie) |9 |9 |0 |
|test (hthor) |720 |720 |0 |
|test (thor) |615 |615 |0 |
|test (roxie) |745 |745 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-03-30 22:29 UTC, AttilaVamos commented
@jakesmith please review.

2017-03-31 11:06 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 53b8a14471de8977bd961f33d6ab04592cc35a5e
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.057 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |9 |9 |0 |
|setup (thor) |9 |9 |0 |
|setup (roxie) |9 |9 |0 |
|test (hthor) |720 |718 |2 |
|test (thor) |615 |615 |0 |
|test (roxie) |745 |744 |1 |


Errors:
- test
  - hthor
    - despray, persist_refresh (persistRefresh=false), 
  - roxie
    - despray, 

HPCC Stop: OK
HPCC Uninstall: OK

2017-03-31 11:12 UTC, AttilaVamos commented
The despray error was expected, because this PR enables the DropZone restriction, but the despray.ecl key file (intentionally) didn't changed.  (The persist_refresh in a known issue)

2017-03-31 12:36 UTC, jakesmith requested changes
@AttilaVamos - a couple of minor comments.

>The despray error was expected, because this PR enables the DropZone restriction, but the despray.ecl key file (intentionally) didn't changed.

Why (didn't you change the despray key) ?

2017-03-31 12:36 UTC, jakesmith commented on dali/ft/filecopy.cpp
> +                    throwError1(DFTERR_NoMatchingDropzonePath, pfilePath);
If not enabled, should still log.

2017-03-31 12:36 UTC, jakesmith commented on initfiles/etc/DIR_NAME/environment.conf.in
> +# Default is enable (true).
"enabled"

2017-03-31 15:22 UTC, AttilaVamos commented on dali/ft/filecopy.cpp
> +                    throwError1(DFTERR_NoMatchingDropzonePath, pfilePath);
Changed

2017-03-31 15:25 UTC, AttilaVamos commented
@jakesmith updated.

2017-03-31 15:55 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 3a72033a2cc7ab60e7eba9d4444cb13406ab9032
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.736 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |9 |9 |0 |
|setup (thor) |9 |9 |0 |
|setup (roxie) |9 |9 |0 |
|test (hthor) |720 |719 |1 |
|test (thor) |615 |615 |0 |
|test (roxie) |745 |744 |1 |


Errors:
- test
  - hthor
    - despray, 
  - roxie
    - despray, 

HPCC Stop: OK
HPCC Uninstall: OK

2017-03-31 16:01 UTC, jakesmith commented
@AttilaVamos - what was the answer to https://github.com/hpcc-systems/HPCC-Platform/pull/9786#pullrequestreview-30233575 ?

2017-03-31 18:07 UTC, AttilaVamos commented
I didn't change the key because I would like to test the feature.

2017-03-31 18:42 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 3affa94d6597c8fdba9103356fc8e3659939b1c9
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.72 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |9 |9 |0 |
|setup (thor) |9 |9 |0 |
|setup (roxie) |9 |9 |0 |
|test (hthor) |720 |719 |1 |
|test (thor) |615 |615 |0 |
|test (roxie) |745 |745 |0 |


Errors:
- test
  - hthor
    - stepping7h (multiPart=true), 

HPCC Stop: OK
HPCC Uninstall: OK

2017-03-31 19:10 UTC, AttilaVamos commented
The stepping7h (multiPart=true) error is parallel query related issue.

2017-04-03 08:36 UTC, jakesmith commented
@richardkchapman - looks good to merge.

2017-04-03 09:40 UTC, merged

2017-04-03 09:43 UTC, richardkchapman commented
I merged this then noticed that it needed squashing (2 of the commits are not properly formatted) so rolled back

2017-04-03 09:46 UTC, richardkchapman commented
manually squashed and merged

2017-04-03 10:04 UTC, AttilaVamos commented
@richardkchapman thank you.