HPCC-16110 Dedup unexpected results when using KEEP n and RIGHT
hpcc-systems/HPCC-Platform pull request #9803
Opened 2017-04-05 10:06 UTC by shamser

Signed-off-by: Shamser Ahmed <shamser.ahmed@lexisnexis.co.uk>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-04-05 10:09 UTC, shamser commented
@ghalliday Please can you review

2017-04-05 10:36 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 2084bcfb2d71c1f219e11af38e30dd6bab787d1a
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 43.675 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |9 |9 |0 |
|setup (thor) |9 |9 |0 |
|setup (roxie) |9 |9 |0 |
|test (hthor) |726 |726 |0 |
|test (thor) |621 |621 |0 |
|test (roxie) |752 |748 |4 |


Errors:
- test
  - roxie
    - dedup, dedupright, dedupwithbest, sqgroup (multiPart=false), 

HPCC Stop: OK
HPCC Uninstall: OK

2017-04-06 08:27 UTC, AttilaVamos commented
The errors are:
```
126. Test: dedup.ecl
    '<Exception><Code>3000</Code><Source>Roxie</Source><Message>assert(numToKeep == 1) failed - file: ccdserver.cpp, line 7241</Message></Exception>
    '
131. Test: dedupright.ecl
    '<Exception><Code>3000</Code><Source>Roxie</Source><Message>assert(numToKeep == 1) failed - file: ccdserver.cpp, line 7241</Message></Exception>
    '
132. Test: dedupwithbest.ecl
    '<Exception><Code>3000</Code><Source>Roxie</Source><Message>assert(numToKeep == 1) failed - file: ccdserver.cpp, line 7241</Message></Exception>
    '
599. Test: sqgroup.ecl ( version: multiPart=false )
    '<Exception><Code>3000</Code><Source>Roxie</Source><Message>assert(numToKeep == 1) failed - file: ccdserver.cpp, line 7241 (in Project 4)</Message></Exception>
    '
```

2017-04-06 14:25 UTC, ghalliday commented
@shamser various regression tests are failing, and the code makes some attempt to implement keep(n).

The failures need addressing/commenting.

2017-04-26 17:59 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 4222054fe7274f75985c49bf08161f6d8c029688
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 44.533 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |728 |728 |0 |
|test (thor) |623 |623 |0 |
|test (roxie) |753 |753 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-26 18:04 UTC, HPCCSmoketest commented
Automated Smoketest: :x:
Sha: a4b0f9864b27316c2d30364c85d2010a813ff0ef
Build: failed
Number of Error(s): 28
/mnt/disk1/home/vamosax/smoketest/PR-9803/HPCC-Platform/roxie/ccd/ccdserver.cpp:7295:9: error: \xe2\x80\x98kept\xe2\x80\x99 does not name a type
/mnt/disk1/home/vamosax/smoketest/PR-9803/HPCC-Platform/roxie/ccd/ccdserver.cpp:7297:9: error: expected unqualified-id before \xe2\x80\x98if\xe2\x80\x99
/mnt/disk1/home/vamosax/smoketest/PR-9803/HPCC-Platform/roxie/ccd/ccdserver.cpp:7298:9: error: expected unqualified-id before \xe2\x80\x98return\xe2\x80\x99
/mnt/disk1/home/vamosax/smoketest/PR-9803/HPCC-Platform/roxie/ccd/ccdserver.cpp:7299:5: error: expected \xe2\x80\x98;\xe2\x80\x99 after class definition
/mnt/disk1/home/vamosax/smoketest/PR-9803/HPCC-Platform/roxie/ccd/ccdserver.cpp:7276:1: error: expected primary-expression before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-9803/HPCC-Platform/roxie/ccd/ccdserver.cpp:7276:3: error: expected primary-expression before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-9803/HPCC-Platform/roxie/ccd/ccdserver.cpp:7276:5: error: expected primary-expression before \xe2\x80\x98<<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-9803/HPCC-Platform/roxie/ccd/ccdserver.cpp:7276:7: error: expected primary-expression before \xe2\x80\x98<\xe2\x80\x99 token
/mnt/disk1/home/vamosax/smoketest/PR-9803/HPCC-Platform/roxie/ccd/ccdserver.cpp:7276:9: error: \xe2\x80\x98HEAD\xe2\x80\x99 was not declared in this scope
/mnt/disk1/home/vamosax/smoketest/PR-9803/HPCC-Platform/roxie/ccd/ccdserver.cpp:7277:13: error: expected \xe2\x80\x98;\xe2\x80\x99 before \xe2\x80\x98}\xe2\x80\x99 token
/mnt/disk1/home/vamo
 ... ( comment is too long, 35 lines, 4349 bytes, truncated) ... 
98}\xe2\x80\x99 token
cc1plus: some warnings being treated as errors
make[2]: *** [roxie/ccd/CMakeFiles/ccd.dir/ccdserver.cpp.o] Error 1
make[1]: *** [roxie/ccd/CMakeFiles/ccd.dir/all] Error 2
make: *** [all] Error 2
Get ECLWatch build result


```

2017-04-27 09:40 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 7cc86810b12d3ac5167feb953a214548408ed7d4
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 41.466 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |728 |728 |0 |
|test (thor) |623 |623 |0 |
|test (roxie) |753 |753 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-27 10:22 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 2e96f79c9aa043a2eb38c69ba52956c9bbd96091
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 40.666 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |728 |728 |0 |
|test (thor) |623 |623 |0 |
|test (roxie) |753 |752 |1 |


Errors:
- test
  - roxie
    - schedule2, 

HPCC Stop: OK
HPCC Uninstall: OK

2017-04-27 10:32 UTC, shamser commented
@ghalliday Please can you review again. Thanks.

2017-04-27 13:28 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 4a9f5e977e8d3007bd5b1a8de97ac57078d12f88
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 75 | 45.206 seconds |


Install hpccsystems-platform-community_6.5.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |728 |728 |0 |
|test (thor) |623 |623 |0 |
|test (roxie) |753 |753 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-27 13:39 UTC, shamser commented
@ghalliday Regression issue fixed.  Please can you  review

2017-05-02 12:43 UTC, ghalliday requested changes
This should also have a test that triggers the problem (KEEP with a stored variable?)

2017-05-02 12:43 UTC, ghalliday commented on roxie/ccd/ccdserver.cpp
> +        assertex(numToKeep <= 1);
If an error can be provoked by SENSIBLE user CODE then it should be caught and throw with a better error message.

2017-05-02 12:43 UTC, ghalliday commented on roxie/ccd/ccdserver.cpp
> +        assertex(numToKeep <= 1);
This test is in the wrong place - the value will not be correctly initialised until *after* the base class start method is called.

2017-05-02 12:43 UTC, ghalliday commented
@shamser back to you

2017-05-08 14:53 UTC, closed without merging