HPCC-17181 Refactor aggregate HT to use Roxiemem+avoid heap allocations
hpcc-systems/HPCC-Platform pull request #9814
Opened 2017-04-06 15:07 UTC by jakesmith

Previously hash aggregates, were creating a rowbuilder object per new
row, with a large number of unique values, this created a lot of heap
objects that would be randomly accessed as the hash table was used.
This was particularly expensive during the merge phase and the time
was extremely variable. In most extreme cases it was 60x slower than
fastest run.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-04-06 15:13 UTC, jakesmith commented
@ghalliday - please review.

NB: The next step would be to refactor either SuperHashTable or CMinHashTable so that it supported:
a) a arbitrary structure as in the HT implemented here.
b) could overload allocations, so could use roxiemem.

2017-04-06 15:58 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 0d87b5b57934e001fa3e59fec1b650532c4f2213
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.852 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |9 |9 |0 |
|setup (thor) |9 |9 |0 |
|setup (roxie) |9 |9 |0 |
|test (hthor) |721 |720 |1 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


Errors:
- test
  - hthor
    - persist_refresh (persistRefresh=false), 

HPCC Stop: OK
HPCC Uninstall: OK

2017-04-06 16:12 UTC, AttilaVamos commented
The persist_refresh is a known --pq related issue.

2017-04-10 15:07 UTC, ghalliday reviewed
@jakesmith generally looks good.  One comment to remove a local row builder, and open question about commoning up the hash table code.

2017-04-10 15:07 UTC, ghalliday commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +                const void *row = rowBuilder.finalizeRowClear(ht.size);
Simpler code (with no rowBuilder):

`        const void * row = rowAllocator->finalizeRow(ht.size, ht.row, ht.size);
`

2017-04-10 15:07 UTC, ghalliday commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +            RtlDynamicRowBuilder rowBuilder(rowAllocator, ht.size, ht.row);
ht.size isn't actually the same as maxLength, but I don't think it will cause any ill effects.

2017-04-19 13:31 UTC, jakesmith commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +        HTEntry *t = table+htn; // more interesting going backwards
Not sure, it was originally a line+comment copied from CMinHashTable. I should have removed here though.

2017-04-19 13:31 UTC, jakesmith commented on thorlcr/activities/diskread/thdiskreadslave.cpp
> +            return next;;
will remove

2017-04-19 13:31 UTC, jakesmith commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +    struct HTEntry
Yes agree, I said that in my leading review request comment here: https://github.com/hpcc-systems/HPCC-Platform/pull/9814#issuecomment-292205958

But would prefer to get this into 6.4 and leave that for another JIRA/PR.

2017-04-19 13:31 UTC, jakesmith commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +            RtlDynamicRowBuilder rowBuilder(rowAllocator, ht.size, ht.row);
@ghalliday - not sure I understand..

ht.size is the current size of the element in the HT. The row builder is being initialised with that.. isn't that correct?

2017-04-19 13:31 UTC, jakesmith commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +                const void *row = rowBuilder.finalizeRowClear(ht.size);
ok, yes, I will change.

2017-04-20 17:34 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: bc5f590e3ae6af4d37e087461222fcf9db04fd3b
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.666 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |722 |722 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-21 13:24 UTC, jakesmith commented
@ghalliday - please re-review.

Some timings:
![image](https://cloud.githubusercontent.com/assets/902700/25279400/39e9f0ca-269e-11e7-854c-ff5b907e95bf.png)

2017-04-21 13:50 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: a18e35a5e12cddf47f1b7064cc39819b5a76c941
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.848 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |722 |722 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-04 11:17 UTC, ghalliday reviewed
Code generally looks correct.

It needs some more comments on the new functions and classes, and also an overall description of how the activity is implemented.  I suspect the disk and index varieties haven't been fully tested.

2017-05-04 11:17 UTC, ghalliday commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +        while (t-- != table)
minor: Slightly strange to walk backwards - some processors might not like it.

2017-05-04 11:17 UTC, ghalliday commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +                distributor.disconnect(true);
Should this be called even if input != null

2017-05-04 11:17 UTC, ghalliday commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +    class CStream : public CSimpleInterfaceOf<IRowStream>
Could do with some comments describing what this class does

2017-05-04 11:17 UTC, ghalliday commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +class CAggregateHT : public CSimpleInterfaceOf<IAggregateTable>
A new class, so should have a summary description

2017-05-04 11:17 UTC, ghalliday commented
@jakesmith see comments

2017-05-08 13:29 UTC, jakesmith commented
@ghalliday - see changes, please review.

2017-05-09 03:20 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 2fa840c8c4c519dca54b4b42a0b9f2a09ac71e77
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 94.996 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |727 |727 |0 |
|test (thor) |620 |619 |1 |
|test (roxie) |748 |748 |0 |


Errors:
- test
  - thor
    - grouphashagg, 

HPCC Stop: OK
HPCC Uninstall: OK

2017-05-09 09:23 UTC, ghalliday requested changes
Looks close to ready.  Failure form regression suite is concerning.

2017-05-09 09:23 UTC, ghalliday commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +                    ::ReleaseRoxieRow(rows);
This will leak any rows not read.

2017-05-09 09:23 UTC, ghalliday commented
@jakesmith

2017-05-09 12:11 UTC, jakesmith commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +                    ::ReleaseRoxieRow(rows);
Glad you spotted, if not, another case where HPCC-17289 would have been helpful.

2017-05-09 12:11 UTC, jakesmith commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +    CCycleTimer timer;
removed

2017-05-09 12:11 UTC, jakesmith commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +    class CStream : public CSimpleInterfaceOf<IRowStream>
renamed

2017-05-09 12:11 UTC, jakesmith commented
@ghalliday - please re-review

2017-05-09 14:32 UTC, ghalliday reviewed
Please can you fix the leak, and then push squashing all the commits.  I'll do a final review on the squashed code.

2017-05-09 14:32 UTC, ghalliday commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +                    roxiemem::ReleaseRoxieRowArray(numRows, rows);
You still need to release rows.

2017-05-09 14:32 UTC, ghalliday commented
@jakesmith

2017-05-09 14:40 UTC, jakesmith commented
@ghalliday - fixed row array leak and squashed

2017-05-09 23:45 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 46d7a6fbb9175c176577afa45ca80d996195972a

2017-05-10 00:51 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 46d7a6fbb9175c176577afa45ca80d996195972a

2017-05-10 01:56 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 46d7a6fbb9175c176577afa45ca80d996195972a

2017-05-10 03:03 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 46d7a6fbb9175c176577afa45ca80d996195972a

2017-05-10 04:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 46d7a6fbb9175c176577afa45ca80d996195972a

2017-05-10 05:14 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 46d7a6fbb9175c176577afa45ca80d996195972a

2017-05-10 06:20 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 46d7a6fbb9175c176577afa45ca80d996195972a

2017-05-10 07:07 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 46d7a6fbb9175c176577afa45ca80d996195972a

2017-05-10 07:53 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 46d7a6fbb9175c176577afa45ca80d996195972a

2017-05-10 08:39 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 46d7a6fbb9175c176577afa45ca80d996195972a

2017-05-10 09:16 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 46d7a6fbb9175c176577afa45ca80d996195972a

2017-05-10 11:39 UTC, ghalliday approved these changes
One small comment - which is unlikely to cause problems.

2017-05-10 11:39 UTC, ghalliday commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +            sz = 0;
minor: Should also call rowBuilder.clear()

2017-05-10 11:44 UTC, jakesmith commented on thorlcr/activities/hashdistrib/thhashdistribslave.cpp
> +            sz = 0;
ok will add, though in practice as it stands it wouldn't make any difference as object isn't reused.

2017-05-10 11:48 UTC, merged