HPCC-17288 DOCS:New Scope Options for R plugin
hpcc-systems/HPCC-Platform pull request #9817
Opened 2017-04-06 20:22 UTC by g-pan

Fix HPCC-17288 DOCS:New Scope Options for R plugin
Update documentation for Embedded R code.
NOTE: Initial commit, expecting comments. 

@Michael-Gardner please review
@JamesDeFabia please review

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

Not fully tested yet, expecting feedback. 
Testing will occur after review.

2017-04-06 20:59 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 92f6f6e22f7fee5f439400f667dadacf194f804a
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.272 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |9 |9 |0 |
|setup (thor) |9 |9 |0 |
|setup (roxie) |9 |9 |0 |
|test (hthor) |721 |720 |1 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


Errors:
- test
  - hthor
    - persist_refresh (persistRefresh=false), 

HPCC Stop: OK
HPCC Uninstall: OK

2017-04-11 15:08 UTC, Michael-Gardner reviewed
Couple small changes

2017-04-11 15:08 UTC, Michael-Gardner commented on docs/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +            </emphasis>Install using <emphasis>apt-get install
For debian you might want to say "Install using <emphasis>dpkg -i</emphasis> followed by <emphasis>apt-get install -f</emphasis>.

2017-04-11 15:08 UTC, Michael-Gardner commented on docs/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +            url="https://github.com/hpcc-systems/HPCC-Platform/tree/master/testing/ecl/embedjava.ecl">https://github.com/hpcc-systems/HPCC-Platform/tree/master/testing/ecl/embedjava.ecl*</ulink></par
testing/regress/ecl/embedR.ecl

2017-04-11 18:02 UTC, g-pan commented
Revised and added another line derived from the parent HPCC-17280 @Michael-Gardner please review and in the case of the new text, please review for accuracy/relevance.

2017-04-11 18:28 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 6fc854b856daf5422ddb0d5dd27da7a0b59ca1d4
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 96.554 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |721 |721 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-12 06:31 UTC, richardkchapman commented
I can't say I'm a fan of the change from plugin to plug-in. to me, plug-in feels like an adjective (as in "plug-in hybrid car") but plugin feels more like a noun which is what we want.

This change looks ok as far as it goes but needs much more detail on the scope options.

2017-04-12 17:18 UTC, g-pan commented
@richardkchapman please review. Scope content added.

2017-04-12 17:45 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 23ae85a12709e222174c577f1d4d844d8d75bc57
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.404 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |721 |721 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-12 18:37 UTC, Michael-Gardner reviewed
Minor change that Richard pointed out. Otherwise looks good.

2017-04-12 18:37 UTC, Michael-Gardner commented on docs/Installing_and_RunningTheHPCCPlatform/Inst-Mods/hpcc_ldap.xml
> +          <para>Select the security Plug-in for each service that requires a
Plug-in -> Plugin

2017-04-13 08:51 UTC, richardkchapman commented
@gpan back to you. Scope content looks good

2017-04-17 13:00 UTC, g-pan commented on docs/Installing_and_RunningTheHPCCPlatform/Inst-Mods/hpcc_ldap.xml
> +          <para>Select the security Plug-in for each service that requires a
This instance is outside of the scope of this issue. Note I opened https://track.hpccsystems.com/browse/HPCC-17400 specifically for these other occurrences.

2017-04-17 15:29 UTC, JamesDeFabia requested changes
the rest looks good

2017-04-17 15:29 UTC, JamesDeFabia commented on docs/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
> +          <para>The GLOBALSCOPE The value passed to GLOBALSCOPE can be any
Extra words in this sentence?
The GLOBALSCOPE The value passed to GLOBALSCOPE can be any...
s/b 
The value passed to GLOBALSCOPE can be any

2017-04-17 16:31 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 6e08770af30c92546af6dc6f3d543fc2ddb960b1
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 95.453 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |721 |721 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-17 20:22 UTC, JamesDeFabia approved these changes
looks good now

2017-04-18 11:24 UTC, richardkchapman commented on docs/Installing_and_RunningTheHPCCPlatform/Inst-Mods/hpcc_ldap.xml
> +          <para>Select the security Plug-in for each service that requires a
But you have introduced the incorrect version with this pull request - that makes it inside the scope!

2017-04-18 11:25 UTC, richardkchapman commented
@g-pan Ok apart from one minor comment - but please squash before I merge.

2017-04-18 12:54 UTC, g-pan commented
squashed and ready

2017-04-18 13:22 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: ac0b52ab988351bdb5264b428dd916aca5d2cb46
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.717 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |722 |722 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-18 16:04 UTC, merged