HPCC-16850 Document expireDays for file spray
hpcc-systems/HPCC-Platform pull request #9824
Opened 2017-04-07 15:15 UTC by JamesDeFabia

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-04-07 15:16 UTC, JamesDeFabia commented
@AttilaVamos Please review

2017-04-07 16:55 UTC, AttilaVamos requested changes

2017-04-07 16:55 UTC, AttilaVamos commented on docs/ECLStandardLibraryReference/SLR-Mods/SprayVariable.xml
> +  <emphasis> sourceCsvEscape </emphasis> <emphasis role="bold">]</emphasis>,
It seems something wrong. My 'HPCC-16630 Add expiry parameter to spray commands' merged into 7.0.0 therefore the expireDays doesn't available in 6.4.0. 
@richardkchapman @ghalliday I can see two solutions:
1. Merge https://github.com/hpcc-systems/HPCC-Platform/pull/9470 down to 6.4.0
2. Retarget this PR to 7.0.0

2017-04-07 16:56 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 457b6398aade7f53d406d60719cdccfd2e2e2458
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.604 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |721 |721 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-07 17:07 UTC, AttilaVamos commented on docs/ECLStandardLibraryReference/SLR-Mods/SprayVariable.xml
> +  <emphasis> sourceCsvEscape </emphasis> <emphasis role="bold">]</emphasis>,
Independently my comment above there are some other parameters missing from the STD.File.SprayDelimited() and STD.File.fSprayDelimited() functions argument list: failIfNoSourceFile, recordStructurePresent, quotedTerminator.

They are exists in the table later.

2017-04-07 17:12 UTC, AttilaVamos commented
@JamesDeFabia back to you.

2017-04-19 16:09 UTC, JamesDeFabia commented
@AttilaVamos Edits made, back to you

2017-04-19 17:01 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 702dcfa8a5b22fcb7a56211b831230fa4638e358
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.95 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |721 |721 |0 |
|test (thor) |616 |616 |0 |
|test (roxie) |745 |745 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-04-21 15:04 UTC, AttilaVamos commented on docs/ECLStandardLibraryReference/SLR-Mods/SprayVariable.xml
> +  <emphasis>expireDays</emphasis> <emphasis role="bold">])</emphasis></para>
One parameter missing, the 'encoding' between 'quotedTerminator' and 'expireDays'.
'... [quotedTerminator ], [encoding ], [expireDays])'

2017-04-21 15:04 UTC, AttilaVamos commented on docs/ECLStandardLibraryReference/SLR-Mods/SprayVariable.xml
> +  <emphasis>expireDays</emphasis> <emphasis role="bold">])</emphasis></para>
One parameter missing, the 'encoding' between 'quotedTerminator' and 'expireDays'.
'... [quotedTerminator ], [encoding ], [expireDays])'

2017-04-21 15:05 UTC, AttilaVamos commented
@JamesDeFabia one parameter missing from two places (see my comments).

2017-05-04 08:17 UTC, richardkchapman commented
The Jira ticket says 6.4.0 but this PR targets master. Which is right?

2017-05-04 14:02 UTC, JamesDeFabia commented
Should be 6.4.0, sorry. I changed it

2017-05-05 16:57 UTC, richardkchapman commented
Can you squash before I merge. @AttilaVamos Are you happy now?

2017-05-05 17:13 UTC, AttilaVamos commented
I can’t see the missing 'encoding' is added.

2017-05-05 17:37 UTC, JamesDeFabia commented
I missed that, will add that now

2017-05-05 19:03 UTC, AttilaVamos commented
@richardkchapman it is correct now.

2017-05-05 19:25 UTC, JamesDeFabia commented
I corrected the missing element and squashed

2017-05-05 19:26 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 4967ac756976660bd3060251297d70845afd851d
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.138 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |727 |727 |0 |
|test (thor) |620 |620 |0 |
|test (roxie) |748 |748 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-05 20:23 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 521ea6af2da828386629d2c981081b0862c3e864
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.456 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |727 |727 |0 |
|test (thor) |620 |620 |0 |
|test (roxie) |748 |748 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-06 10:36 UTC, merged