HPCC-17186 DOCS: Spray queue dropdown
hpcc-systems/HPCC-Platform pull request #9915
Opened 2017-05-01 18:55 UTC by g-pan

Fix HPCC-17186 DOCS: Spray queue dropdown
Document a new queue select field inside of the spray areas of the landing zone widget.
@JamesDeFabia please review
@miguelvazq please review, verify if this sufficiently covers the new queues

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-05-01 19:04 UTC, miguelvazq commented
@g-pan The queue screenshot is not included here.

2017-05-01 19:25 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: a96e296f8b7fe588f6d0b800ce9570cb0b045518
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.386 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |722 |722 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-01 19:54 UTC, JamesDeFabia requested changes
The title says Spray queue dropdown, but I don't see that described or depicted.

2017-05-01 19:54 UTC, JamesDeFabia commented on docs/ECLWatch/ECLWa_mods/ECLWatchSrc.xml
> +      <para>Click on the arrow next to a drop zone container, or folder to
comma not needed -- "container or folder"

2017-05-02 10:03 UTC, richardkchapman commented
@g-pan Back to you

2017-05-02 11:04 UTC, g-pan commented
@JamesDeFabia please review
@miguelvazq please review

2017-05-02 11:24 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: ee5504e89cbfbd339ca8d50ce6e401876a28b2e2
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.589 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |722 |722 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-02 11:54 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 9f261be1cb94b275c831f3792d47c590f70987b3
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.451 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |722 |722 |0 |
|test (thor) |617 |617 |0 |
|test (roxie) |746 |746 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-02 13:09 UTC, JamesDeFabia commented
Looks good from my point of view.  @miguelvazq You get the last word.

2017-05-03 15:29 UTC, miguelvazq reviewed
Seems that ECLWA412.jpg and ECLWA440.jpg are different themes of ECLWatch. 440 is using a theme that we are going to use in a later release and 412 is a different theme altogether (perhaps a different browser)

2017-05-04 07:35 UTC, richardkchapman commented
@g-pan Back to you

2017-05-04 18:12 UTC, g-pan commented
updated. @JamesDeFabia please review @miguelvazq please review

2017-05-04 18:23 UTC, JamesDeFabia commented
Looks good from my point of view. @miguelvazq  Please give final approval

2017-05-04 18:48 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 38c5c67d08ea36f8b611fe682927e7dbaf1152de
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 94.102 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |726 |726 |0 |
|test (thor) |619 |619 |0 |
|test (roxie) |747 |747 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-05 13:30 UTC, miguelvazq commented
@g-pan Not sure if it matter but, those internal IP's are not blurred. Not sure what you do documentation wide.

2017-05-05 13:50 UTC, g-pan commented
Should be ok, still better safe than sorry. Good catch. Image updated.

2017-05-05 14:15 UTC, miguelvazq commented
Looks good now.

2017-05-05 14:28 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: d3c859e9a480256d0a39040b7a98143a047af9bf
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 94.101 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |726 |726 |0 |
|test (thor) |619 |619 |0 |
|test (roxie) |747 |747 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-05 15:10 UTC, merged