HPCC-17447 Document built in compile time constants
hpcc-systems/HPCC-Platform pull request #9931
Opened 2017-05-04 17:28 UTC by JamesDeFabia

Signed-off-by: Jim DeFabia <jamesdefabia@lexisnexis.com>

@ghalliday Please review for accuracy
@g-pan Please review for formatting, etc.

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-05-04 18:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 0a7ca393ba7eb475af79e66e4c6eea3ffea8783d
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.217 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |726 |726 |0 |
|test (thor) |619 |619 |0 |
|test (roxie) |747 |747 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-11 15:27 UTC, ghalliday requested changes
Documentation looks good except for the example.

2017-05-11 15:27 UTC, ghalliday commented on docs/ECLLanguageReference/ECLR_mods/Basics-Constants.xml
> +      strftime(__result, 15, "%Y%m%d%H%M%S", &amp;localt); // Formats the localtime to YYYYMMDDhhmmss
Bad code - this corrupts memory.  It needs to write to a temporary, and then copy 14 bytes from it.

2017-05-11 19:03 UTC, JamesDeFabia commented
@ghalliday Edits made, back to you

2017-05-11 22:02 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 80fb397fcaa09fe6192ed8070c421c7be6dc71bc
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.677 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |727 |727 |0 |
|test (thor) |621 |621 |0 |
|test (roxie) |748 |748 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-12 10:08 UTC, ghalliday requested changes
Sorry, one comment from 1st review got lost, and spotted something else on second view.

2017-05-12 10:08 UTC, ghalliday commented on docs/ECLLanguageReference/ECLR_mods/Basics-Constants.xml
> +  #IF(__ECL_VERSION__ &gt;= '5.2')
I seem to have lost a comment on this line.  This doesn't work once the major version goes above 9.  Should be

(__ECL_VERSION_MAJOR__ > 5) or ((__ECL_VERSION_MAJOR__ = 5) AND (__ECL_VERSION_MINOR__ >= 2))

(untested)

2017-05-12 10:08 UTC, ghalliday commented on docs/ECLLanguageReference/ECLR_mods/Basics-Constants.xml
> +              <entry><emphasis>_ECL_VERSION_<indexterm>
All these symbols should be prefixed and suffixed with double underscores.

2017-05-12 10:08 UTC, ghalliday commented
@JamesDeFabia

2017-05-12 12:35 UTC, JamesDeFabia commented
@ghalliday More edits made, back to you

2017-05-12 13:41 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: e0b77b7e20a8faacd5a9d2fdd8aa955b516be5a9
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.021 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |727 |727 |0 |
|test (thor) |621 |621 |0 |
|test (roxie) |748 |748 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-12 14:48 UTC, ghalliday commented
@JamesDeFabia should you have also fixed <primary> tags.
Also, please can you squash the commits.

2017-05-12 15:26 UTC, richardkchapman commented on docs/ECLLanguageReference/ECLR_mods/Basics-Constants.xml
> +              <entry><emphasis>__ECL_VERSION_<indexterm>
trailing is a double underbar too, I think (and on the others)

2017-05-12 15:28 UTC, JamesDeFabia commented
@ghalliday Final edits made and squashed

2017-05-12 15:29 UTC, JamesDeFabia commented
@ghalliday  
wait, RKC commented... back to editing

2017-05-12 15:37 UTC, JamesDeFabia commented
@ghalliday OK, all edits made and squashed.. back to you

2017-05-12 16:28 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 666e3d1b8fa97e00410c04b6ee6db5a328237ddd
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.244 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |727 |726 |1 |
|test (thor) |621 |620 |1 |
|test (roxie) |748 |747 |1 |


Errors:
- test
  - hthor
    - distributeddataset, 
  - thor
    - distributeddataset, 
  - roxie
    - distributeddataset, 

HPCC Stop: OK
HPCC Uninstall: OK

2017-05-15 10:37 UTC, ghalliday approved these changes

2017-05-15 10:38 UTC, merged