HPCC-17351 Logical file meta data migration tool
hpcc-systems/HPCC-Platform pull request #9948
Opened 2017-05-08 08:39 UTC by jakesmith

Add option to daliadmin to map an existing group of
logical files onto a new cluster group.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

Tested with various small sets of files on small test clusters (on performance cluster nodes).
Needs further testing/feedback by ops.

2017-05-08 08:57 UTC, richardkchapman commented
@jakesmith Who can review this change?

2017-05-08 09:16 UTC, jakesmith commented
@rwagner42 - please use/test.

@AttilaVamos - please review.

2017-05-09 06:31 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: dce1cab01925f0be89424c0f55ff90f70045758e
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.613 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |727 |727 |0 |
|test (thor) |620 |620 |0 |
|test (roxie) |748 |748 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-10 09:28 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: dc8422f88fde38f96dcc9ded0513a6232bdc7688

2017-05-10 16:48 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: dc8422f88fde38f96dcc9ded0513a6232bdc7688
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 91.995 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |727 |727 |0 |
|test (thor) |621 |621 |0 |
|test (roxie) |748 |748 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-12 13:38 UTC, AttilaVamos reviewed
There are several questions.

2017-05-12 13:38 UTC, AttilaVamos commented on dali/daliadmin/daliadmin.cpp
> +                Owned<IFileIO> iFileIO = iFile->open(IFOcreate);
Should not this object creation be checked? If iFile is a valid pointer?

2017-05-12 13:38 UTC, AttilaVamos commented on dali/daliadmin/daliadmin.cpp
> +                            IPartDescriptor *part = fileDesc->queryPart(p);
Can '*part' be nullptr?

2017-05-12 13:39 UTC, AttilaVamos commented
@jake @back to you with some questions.

2017-05-12 14:02 UTC, jakesmith commented on dali/daliadmin/daliadmin.cpp
> +  printf("  migratefiles <src-group> <target-group> [<filemask>] [DRYRUN] [CREATEMAPS] [LISTONLY] [VERBOSE]\n");
could change usage print, but tests are case-insensitive, so no need for conversion.

2017-05-12 14:03 UTC, jakesmith commented on dali/daliadmin/daliadmin.cpp
> +        if (strieq("CREATEMAPS", opt))
strieq is case insensitive test.

2017-05-12 14:05 UTC, jakesmith commented on dali/daliadmin/daliadmin.cpp
> +                Owned<IFileIO> iFileIO = iFile->open(IFOcreate);
iFile can't be null, either valid or exception.
iFileIO could be I think.
I'll add a catch/throw exception here.

2017-05-12 14:07 UTC, jakesmith commented on dali/daliadmin/daliadmin.cpp
> +                    group.set(clusterGroupName, sub-clusterGroupName);
this is common style (no spaces) elsewhere

2017-05-12 14:09 UTC, jakesmith commented on dali/daliadmin/daliadmin.cpp
> +                        const SocketEndpoint &srcEp = fileDesc->queryPart(p)->queryNode()->endpoint();
this is deserialized file descriptor neither part or node can be null here.

2017-05-12 14:09 UTC, jakesmith commented on dali/daliadmin/daliadmin.cpp
> +                            IPartDescriptor *part = fileDesc->queryPart(p);
no

2017-05-12 14:09 UTC, jakesmith commented on dali/daliadmin/daliadmin.cpp
> +            for (unsigned g=0; g<numClusters; g++)
I'll change.

2017-05-15 09:16 UTC, jakesmith commented
@AttilaVamos - could you take a look/review the new commit. Which are mostly changes following testing against Dataland DFS.

2017-05-15 09:41 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 4b4e909000f7a77fdc46e5fd8e1f88f0887decea
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.062 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |728 |728 |0 |
|test (thor) |622 |622 |0 |
|test (roxie) |749 |749 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-15 10:35 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 84037c9dc8d37bbd0a9fb8608f0f48a0e116d770
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 94.25 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |728 |728 |0 |
|test (thor) |622 |622 |0 |
|test (roxie) |749 |749 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-15 13:41 UTC, AttilaVamos requested changes
One changes remained.

2017-05-15 13:41 UTC, AttilaVamos commented on dali/daliadmin/daliadmin.cpp
> +        if (strieq("CREATEMAPS", opt))
Right

2017-05-15 13:41 UTC, AttilaVamos commented on dali/daliadmin/daliadmin.cpp
> +                Owned<IFileIO> iFileIO = iFile->open(IFOcreate);
Ok, please add catch/throw exception.

2017-05-16 19:36 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 1136b99750d472aa3fc1ad98f23fa476e5ba02e6
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 93.305 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |728 |728 |0 |
|test (thor) |622 |622 |0 |
|test (roxie) |749 |749 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-17 13:13 UTC, jakesmith commented
@AttilaVamos - added check for failing to open file.
Other changes are just moving code that was only used in inner block and minor change to logging.

Please check and I'll squash ready for merge.

2017-05-17 19:15 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 093d256078d5b4a7a9733c95cc28bafe26694a48
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.783 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |728 |728 |0 |
|test (thor) |622 |622 |0 |
|test (roxie) |749 |749 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-18 11:08 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: b8e769913d4af0d3be501c23aa542ac4b259052f
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.496 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |728 |728 |0 |
|test (thor) |622 |622 |0 |
|test (roxie) |749 |749 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-19 14:47 UTC, AttilaVamos commented
@jakesmith it seems good. Do you plan to add more commit?

2017-05-19 15:27 UTC, jakesmith commented
No, I will squash it in a moment.

2017-05-19 15:29 UTC, jakesmith commented
@richardkchapman - please merge.

2017-05-19 16:01 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 6e3687c18df17d0c4e1aa52fa875f2bc4630dda4
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.16 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |728 |728 |0 |
|test (thor) |622 |622 |0 |
|test (roxie) |749 |749 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-22 08:30 UTC, merged