HPCC-17456 Improve EsdlDefStruct efficiency by using map lookup
hpcc-systems/HPCC-Platform pull request #9951
Opened 2017-05-08 13:41 UTC by mayx

- Add hash maps for quick look up of the struct from name
- Add addChild function
- Change queryChild to use map look up instead of array iterating.

Signed-off-by: mayx <yanrui.ma@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-05-08 13:43 UTC, mayx commented
@afishbeck Hi Tony please review the change...

2017-05-09 07:25 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: f72c928e29f7aea272adb8923712fcd5ced83e0b
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.482 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |727 |727 |0 |
|test (thor) |620 |620 |0 |
|test (roxie) |748 |748 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-09 16:20 UTC, afishbeck requested changes
@mayx See comment.

2017-05-09 16:20 UTC, afishbeck commented on esp/esdllib/esdl_def.cpp
> +        addChild(dynamic_cast<IEsdlDefObject*>(et));
@mayx I know it was already this way, but since you are optimizing... these should all work and be faster as static_cast, can you change and test?

2017-05-09 21:49 UTC, mayx commented
@afishbeck good point. Change made per suggstion, please review again.

2017-05-09 22:12 UTC, afishbeck approved these changes
@mayx looks good.

2017-05-09 23:57 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 8c8af3c27c84d6fbb1975c90aabeb89bb7baa293

2017-05-10 01:04 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 8c8af3c27c84d6fbb1975c90aabeb89bb7baa293

2017-05-10 02:09 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 8c8af3c27c84d6fbb1975c90aabeb89bb7baa293

2017-05-10 03:15 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 8c8af3c27c84d6fbb1975c90aabeb89bb7baa293

2017-05-10 04:21 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 8c8af3c27c84d6fbb1975c90aabeb89bb7baa293

2017-05-10 05:27 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 8c8af3c27c84d6fbb1975c90aabeb89bb7baa293

2017-05-10 06:12 UTC, merged