HPCC-17596 Document DFUPlus listhistory and erasehistory
hpcc-systems/HPCC-Platform pull request #9979
Opened 2017-05-11 17:20 UTC by JamesDeFabia

Signed-off-by: Jim DeFabia <jamesdefabia@lexisnexis.com>

@AttilaVamos Please review

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

2017-05-11 21:05 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 8ec2cc8acc553a5668c0a6685734e76d3bebe18e
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.728 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |727 |727 |0 |
|test (thor) |621 |621 |0 |
|test (roxie) |748 |748 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-12 13:02 UTC, AttilaVamos requested changes
'Spray' operation is missing from 2 places.

2017-05-12 13:02 UTC, AttilaVamos commented on docs/HPCCClientTools/CT_Mods/CT_Comm_Line_DFU.xml
> +          <para>History metadata is created from a copy or remote copy
or spray operation

2017-05-12 13:02 UTC, AttilaVamos commented on docs/HPCCClientTools/CT_Mods/CT_Comm_Line_DFU.xml
> +          <para>History metadata is created from a copy or remote copy
or spray operation

2017-05-12 13:03 UTC, AttilaVamos commented
@JamesDeFabia back to you.

2017-05-12 13:53 UTC, JamesDeFabia commented
@AttilaVamos Edits made, back to you

2017-05-12 13:57 UTC, AttilaVamos requested changes
I found two typos, otherwise I think it is correct now.

2017-05-12 13:57 UTC, AttilaVamos commented on docs/HPCCClientTools/CT_Mods/CT_Comm_Line_DFU.xml
> +                  to include header information in the first row whan
it seems typo at the end

2017-05-12 13:57 UTC, AttilaVamos commented on docs/HPCCClientTools/CT_Mods/CT_Comm_Line_DFU.xml
> +  // this removes the hostory metadata from the file and writes an XML file containing the following:
typo 'hostory'

2017-05-12 13:58 UTC, AttilaVamos commented
@JamesDeFabia back to you.

2017-05-12 14:32 UTC, JamesDeFabia commented
@AttilaVamos Edited, back to you

2017-05-12 15:05 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 5e03c49c172cec50a9959640f6c6968df08ab204
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 92.456 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |727 |727 |0 |
|test (thor) |621 |621 |0 |
|test (roxie) |748 |748 |0 |


HPCC Stop: OK
HPCC Uninstall: OK

2017-05-12 15:30 UTC, AttilaVamos commented
@JamesDeFabia Thanks, it is ready to merge.

2017-05-12 16:58 UTC, HPCCSmoketest commented
Automated Smoketest: :white_check_mark:
Sha: 3cb120009ef5264fde03122283cd013024442c96
Build: success
Build: success
ECL Watch:  Rebuilding Site

| errors | warnings | build time | 
|---|---|---|
| 0 | 65 | 97.596 seconds |


Install hpccsystems-platform-community_6.3.0-trunk0.el7.x86_64.rpm
HPCC Start: OK

Unit tests result:

| Test | total | passed | failed | errors | timeout | 
|---|---|---|---|---|---|
|unittest |93 |93 |0 |0 |0 |
|wutoolTest(Dali) |19 |19 |0 |0 |0 |
|wutoolTest(Cassandra) |19 |19 |0 |0 |0 |



Regression test result:

| phase | total | pass | fail | 
|---|---|---|---|
|setup (hthor) |10 |10 |0 |
|setup (thor) |10 |10 |0 |
|setup (roxie) |10 |10 |0 |
|test (hthor) |727 |726 |1 |
|test (thor) |621 |620 |1 |
|test (roxie) |748 |747 |1 |


Errors:
- test
  - hthor
    - distributeddataset, 
  - thor
    - distributeddataset, 
  - roxie
    - distributeddataset, 

HPCC Stop: OK
HPCC Uninstall: OK

2017-05-15 07:58 UTC, merged